/-
# Discrete ATE heterogeneity frontier: real-outcome model

This file defines the finite-confounder, real-outcome observational experiment used
throughout the paper.  The nearby `DiscreteAteMinimaxLoggap` development is reused
for the binary source experiment, but its binary outcome law cannot represent the
paper's conditional-second-moment model (`bypass-justified`).
-/

module
public import Causalean.Stat.Sample
public import Causalean.Stat.Sample.PiTransport
public import Mathlib.Probability.ProductMeasure
public import Mathlib.MeasureTheory.Integral.Bochner.Basic

@[expose] public section

namespace CausalSmith.Stat.DiscreteAteHeterogeneityFrontier

open MeasureTheory ProbabilityTheory Set
open scoped BigOperators ENNReal NNReal

/-- One observed record `(X,A,Y)` in the real-outcome experiment. -/
structure Obs (d : ℕ) where
  x : Fin d -- @realizes X(carrier Fin d) @realizes k(category index Fin d)
  a : Bool -- @realizes A(binary treatment) @realizes a(treatment level Bool)
  y : ℝ -- @realizes Y(real observed outcome)

/-- Observed records carry the measurable structure generated by their covariate, treatment, and
  outcome coordinates. -/
instance {d : ℕ} : MeasurableSpace (Obs d) :=
  MeasurableSpace.comap (fun o : Obs d => (o.x, o.a, o.y)) inferInstance

/-- One full-data record `(X,A,Y(0),Y(1),Y)`. -/
structure FullObs (d : ℕ) where
  x : Fin d -- @realizes X(full-data confounder)
  a : Bool -- @realizes A(full-data treatment)
  y0 : ℝ -- @realizes Y(a)(potential outcome at a=false)
  y1 : ℝ -- @realizes Y(a)(potential outcome at a=true)
  y : ℝ -- @realizes Y(full-data observed outcome)

/-- Full-data records carry the measurable structure generated by the covariate, treatment, both
  potential outcomes, and the observed outcome. -/
instance {d : ℕ} : MeasurableSpace (FullObs d) :=
  MeasurableSpace.comap
    (fun z : FullObs d => (z.x, z.a, z.y0, z.y1, z.y)) inferInstance

/-- Projection from full data to the observed record. -/
def FullObs.observed {d : ℕ} (z : FullObs d) : Obs d :=
  ⟨z.x, z.a, z.y⟩ -- @realizes O(O=(X,A,Y))

/-- Real mass of an event under a measure. -/
noncomputable def realMass {α : Type*} [MeasurableSpace α]
    (μ : Measure α) (s : Set α) : ℝ := (μ s).toReal

/-- A real-outcome finite-cell law, including the primitive cell parametrization
and a full-data coupling.  The identities below pin every auxiliary to the law. -/
structure RealLaw (d : ℕ) where
  observedLaw : Measure (Obs d) -- @realizes P_O(probability law on observed O)
  observed_isProbability : IsProbabilityMeasure observedLaw
  fullLaw : Measure (FullObs d) -- @realizes P(probability law on full data)
  full_isProbability : IsProbabilityMeasure fullLaw
  cellMass : Fin d → ℝ -- @realizes p_k(carrier Fin d -> Real)
  propensity : Fin d → ℝ -- @realizes pi_k(carrier Fin d -> Real)
  outcomeLaw : Bool → Fin d → Measure ℝ
    -- @realizes mu_{ak}(arm-cell outcome law carrier) @realizes a(Bool index)
  outcome_isProbability : ∀ a k, IsProbabilityMeasure (outcomeLaw a k)
    -- @realizes mu_{ak}(conditional outcome law is a probability law)
  outcomeMean : Bool → Fin d → ℝ -- @realizes mu_{ak}(carrier Bool -> Fin d -> Real)
  observed_margin : Measure.map FullObs.observed fullLaw = observedLaw
    -- @realizes P_O(observed margin of P)
  cellMass_eq : ∀ k, cellMass k = realMass observedLaw {o | o.x = k}
    -- @realizes p_k(p_k=P(X=k))
  cellMass_range : ∀ k, cellMass k ∈ Icc (0 : ℝ) 1
    -- @realizes p_k(range [0,1])
  propensity_range : ∀ k, propensity k ∈ Icc (0 : ℝ) 1
    -- @realizes pi_k(range [0,1])
  arm_outcome_factorization : ∀ a k s, MeasurableSet s →
    cellMass k * (if a then propensity k else 1 - propensity k) *
        realMass (outcomeLaw a k) s =
      realMass observedLaw {o | o.x = k ∧ o.a = a ∧ o.y ∈ s}
    -- @realizes pi_k(P(A=1|X=k))
  outcomeMean_eq : ∀ a k, outcomeMean a k = ∫ y, y ∂outcomeLaw a k
    -- @realizes mu_{ak}(conditional mean identity)

attribute [instance] RealLaw.observed_isProbability RealLaw.full_isProbability

/-- Cell treatment effect `tau_k = mu_1k - mu_0k`. -/
def cellEffect {d : ℕ} (P : RealLaw d) (k : Fin d) : ℝ :=
  P.outcomeMean true k - P.outcomeMean false k
  -- @realizes tau_k(tau_k=mu_1k-mu_0k)

/-- The finite-cell g-formula attached to an arbitrary real law.  This auxiliary
is used while the identified model classes are being assembled. -/
noncomputable def rawAteFormula {d : ℕ} (P : RealLaw d) : ℝ :=
  ∑ k : Fin d, P.cellMass k * cellEffect P k

/-- The causal full-data average `E[Y(1)-Y(0)]`. -/
noncomputable def causalATE {d : ℕ} (P : RealLaw d) : ℝ :=
  ∫ z, z.y1 - z.y0 ∂P.fullLaw
  -- @realizes tau(P)(causal expectation E[Y(1)-Y(0)])

/-- Cell deviation from the average treatment effect. -/
noncomputable def cellDeviation {d : ℕ} (P : RealLaw d) (k : Fin d) : ℝ :=
  cellEffect P k - rawAteFormula P
  -- @realizes delta_k(delta_k=tau_k-tau(P))

/-- Standing range condition for the known outcome scale. -/
def OutcomeScale (M : ℝ) : Prop :=
  1 ≤ M
  -- @realizes M(range [1,infinity) at the shared binder scope)

-- @env: S1
variable (n d : ℕ) -- @realizes n(sample size Nat) @realizes d(alphabet size Nat)
variable (epsilon M sigma c_epsilon C_epsilon : ℝ)
  -- @realizes epsilon(overlap constant) @realizes M(outcome scale)
  -- @realizes sigma(heterogeneity radius) @realizes c_epsilon(positive epsilon-only constant)
  -- @realizes C_epsilon(finite epsilon-only constant)
variable (i j : Fin n) -- @realizes i(unit index Fin n) @realizes j(unit index Fin n)
variable (hij : j ≠ i) -- @realizes j(distinct from i in pair kernels)
variable (k : Fin d) (a : Bool)
variable (P : RealLaw d) (O : Obs d) (O_i : Fin n → Obs d)
  -- @realizes O(observed record) @realizes O_i(i-th observed record)
variable (hM : OutcomeScale M)
  -- @realizes M(standing range condition 1 <= M)

-- @node: ass:consistency
/-- `Y = Y(A)` almost surely under the full-data law. -/
def Consistency {d : ℕ} (P : RealLaw d) : Prop :=
  P.fullLaw {z | z.y ≠ if z.a then z.y1 else z.y0} = 0
  -- @realizes Y(observed outcome equals selected potential outcome)
  -- @realizes Y(a)(selected by A)

-- @node: ass:conditional-exchangeability
/-- Atomic-cell formulation of `(Y(0),Y(1))` conditionally independent of `A`
given `X`, valid for arbitrary measurable potential-outcome events. -/
def ConditionalExchangeability {d : ℕ} (P : RealLaw d) : Prop :=
  ∀ k a s0 s1, MeasurableSet s0 → MeasurableSet s1 →
    P.fullLaw {z | z.x = k ∧ z.a = a ∧ z.y0 ∈ s0 ∧ z.y1 ∈ s1} *
        P.fullLaw {z | z.x = k} =
      P.fullLaw {z | z.x = k ∧ z.a = a} *
        P.fullLaw {z | z.x = k ∧ z.y0 ∈ s0 ∧ z.y1 ∈ s1}
  -- @realizes Y(a)(potential-outcome pair in conditional independence)
  -- @realizes A(treatment in conditional independence)
  -- @realizes X(conditioning category)

-- @node: ass:overlap
/-- Positive-mass cells have propensity in `[epsilon,1-epsilon]`. -/
def Overlap {d : ℕ} (epsilon : ℝ) (P : RealLaw d) : Prop :=
  ∀ k, 0 < P.cellMass k →
    epsilon ≤ P.propensity k ∧ P.propensity k ≤ 1 - epsilon
    -- @realizes epsilon(fixed strong overlap)
    -- @realizes pi_k(range [epsilon,1-epsilon] on support)
    -- @realizes p_k(support qualifier p_k>0)

-- @node: ass:mean-normalization
/-- Conditional means lie in `[-M/2,M/2]` on positive-mass cells. -/
def MeanNormalization {d : ℕ} (M : ℝ) (P : RealLaw d) : Prop :=
  ∀ a k, 0 < P.cellMass k → |P.outcomeMean a k| ≤ M / 2
  -- @realizes mu_{ak}(absolute conditional mean bounded by M/2)
  -- @realizes M(mean-envelope scale)

-- @node: ass:second-central-moment
/-- The conditional second central moment is bounded by `M^2`; outcomes themselves
need not be bounded. -/
def SecondCentralMoment {d : ℕ} (M : ℝ) (P : RealLaw d) : Prop :=
  ∀ a k, 0 < P.cellMass k →
    Integrable (fun y => (y - P.outcomeMean a k) ^ 2) (P.outcomeLaw a k) ∧
      ∫ y, (y - P.outcomeMean a k) ^ 2 ∂P.outcomeLaw a k ≤ M ^ 2
  -- @realizes Y(unbounded real outcome under conditional moment control)
  -- @realizes mu_{ak}(centering conditional mean)
  -- @realizes M(second-moment envelope)

/-- If [conditional second moments are finite and bounded](hyp:hsecond) and [the stated condition
  on the cell holds](hyp:hk), [a finite conditional second central moment implies the first-moment
  integrability needed by the finite-cell g-formula](goal). -/
lemma outcome_integrable_of_second_moment {d : ℕ} {M : ℝ}
    (P : RealLaw d) (hsecond : SecondCentralMoment M P)
    (a : Bool) (k : Fin d) (hk : 0 < P.cellMass k) :
    Integrable (fun y : ℝ => y) (P.outcomeLaw a k) := by
  let _ : IsProbabilityMeasure (P.outcomeLaw a k) :=
    P.outcome_isProbability a k
  have hsq := (hsecond a k hk).1
  have hcenter_meas : AEStronglyMeasurable
      (fun y : ℝ => y - P.outcomeMean a k) (P.outcomeLaw a k) :=
    (measurable_id.sub measurable_const).aestronglyMeasurable
  have hcenterLp : MemLp (fun y : ℝ => y - P.outcomeMean a k) 2
      (P.outcomeLaw a k) :=
    (memLp_two_iff_integrable_sq hcenter_meas).2 hsq
  have hcenter : Integrable (fun y : ℝ => y - P.outcomeMean a k)
      (P.outcomeLaw a k) := hcenterLp.integrable (by norm_num)
  refine (hcenter.add (integrable_const (P.outcomeMean a k))).congr ?_
  filter_upwards with y
  simp only [Pi.add_apply]
  ring

-- @node: ass:approximate-homogeneity
/-- Every supported cell effect is within `sigma*M` of the ATE. -/
def ApproximateHomogeneity {d : ℕ} (M sigma : ℝ) (P : RealLaw d) : Prop :=
  ∀ k, 0 < P.cellMass k → |cellDeviation P k| ≤ sigma * M
  -- @realizes delta_k(maximal supported cell deviation)
  -- @realizes sigma(radius in [0,2] supplied by ModelClass)

/-- The causal-identification domain for the finite-cell functional.  It records
exactly consistency, conditional exchangeability, overlap, and the supported-cell
first-moment integrability presupposed by the g-formula. -/
structure CausalIdentificationDomain (d : ℕ) (epsilon : ℝ) (law : RealLaw d) where
  epsilon_pos : 0 < epsilon
  epsilon_lt_half : epsilon < 1 / 2
  consistency : Consistency law
  exchangeability : ConditionalExchangeability law
  overlap : Overlap epsilon law
  outcome_integrable : ∀ a k, 0 < law.cellMass k →
    Integrable (fun y : ℝ => y) (law.outcomeLaw a k)

-- @node: def:ate-functional
/-- The identified ATE functional on the causal model domain.  Its value is the
finite-cell g-formula; `ate_identification` proves that this equals the causal
expectation `E[Y(1)-Y(0)]`. -/
noncomputable def ateFunctional {d : ℕ} {epsilon : ℝ}
    (P : RealLaw d) (_hP : CausalIdentificationDomain d epsilon P) : ℝ :=
  rawAteFormula P
  -- @realizes tau(P)(causal ATE equals the weighted finite-cell formula)

-- @node: def:model-class
/-- The approximately homogeneous real-outcome model class. -/
structure ModelClass (d : ℕ) (epsilon M sigma : ℝ) where
  law : RealLaw d -- @realizes P(member full-data law)
  epsilon_pos : 0 < epsilon -- @realizes epsilon(range (0,1/2))
  epsilon_lt_half : epsilon < 1 / 2 -- @realizes epsilon(range (0,1/2))
  M_ge_one : 1 ≤ M -- @realizes M(effective range [1,infinity) on every class member)
  sigma_nonneg : 0 ≤ sigma -- @realizes sigma(range [0,2])
  sigma_le_two : sigma ≤ 2 -- @realizes sigma(range [0,2])
  consistency : Consistency law
  exchangeability : ConditionalExchangeability law
  overlap : Overlap epsilon law
  mean_normalization : MeanNormalization M law
  second_moment : SecondCentralMoment M law
  homogeneity : ApproximateHomogeneity M sigma law
  -- @realizes \mathcal P_{d,epsilon,M,sigma}(approximately homogeneous class)

-- @node: def:unrestricted-class
/-- The corresponding model without a heterogeneity-radius restriction. -/
structure UnrestrictedClass (d : ℕ) (epsilon M : ℝ) where
  law : RealLaw d -- @realizes P(member unrestricted full-data law)
  epsilon_pos : 0 < epsilon -- @realizes epsilon(range (0,1/2))
  epsilon_lt_half : epsilon < 1 / 2
  M_ge_one : 1 ≤ M -- @realizes M(effective range [1,infinity) on every class member)
  consistency : Consistency law
  exchangeability : ConditionalExchangeability law
  overlap : Overlap epsilon law
  mean_normalization : MeanNormalization M law
  second_moment : SecondCentralMoment M law
  -- @realizes \mathcal P_{d,epsilon,M}^{unr}(unrestricted heterogeneity class)

/-- [The identified-law view carried by every approximately homogeneous model](goal). -/
theorem ModelClass.identifiedLaw {d : ℕ} {epsilon M sigma : ℝ}
    (P : ModelClass d epsilon M sigma) :
    CausalIdentificationDomain d epsilon P.law :=
  { epsilon_pos := P.epsilon_pos
    epsilon_lt_half := P.epsilon_lt_half
    consistency := P.consistency
    exchangeability := P.exchangeability
    overlap := P.overlap
    outcome_integrable :=
      outcome_integrable_of_second_moment P.law P.second_moment }

/-- [The identified-law view carried by every unrestricted model](goal). -/
theorem UnrestrictedClass.identifiedLaw {d : ℕ} {epsilon M : ℝ}
    (P : UnrestrictedClass d epsilon M) :
    CausalIdentificationDomain d epsilon P.law :=
  { epsilon_pos := P.epsilon_pos
    epsilon_lt_half := P.epsilon_lt_half
    consistency := P.consistency
    exchangeability := P.exchangeability
    overlap := P.overlap
    outcome_integrable :=
      outcome_integrable_of_second_moment P.law P.second_moment }

/-- The `n`-fold observed product law generated by a one-unit real law. -/
noncomputable def productLaw {d : ℕ} (n : ℕ) (P : RealLaw d) :
    Measure (Fin n → Obs d) :=
  Measure.pi (fun _ : Fin n => P.observedLaw)
  -- @realizes Q_P^{(n)}(P_O tensor power n)
  -- @realizes Q_P^{(m)}(same product construction at block size m)
  -- @realizes m(block size when the argument is m)

/-- Every finite product of the observed-data law is a probability measure. -/
instance {d n : ℕ} (P : RealLaw d) : IsProbabilityMeasure (productLaw n P) := by
  unfold productLaw
  infer_instance

-- @node: def:sample-experiment
/-- The induced experiment of all observed `n`-sample laws from the model class. -/
noncomputable def sampleExperiment (n d : ℕ) (epsilon M sigma : ℝ) :
    Set (Measure (Fin n → Obs d)) :=
  {Q | ∃ P : ModelClass d epsilon M sigma, Q = productLaw n P.law}
  -- @realizes \mathcal E_{n,d,epsilon,M,sigma}(set of induced product laws)

/-- Total estimators with measurable output clipped to `[-M,M]`. -/
def Estimator (n d : ℕ) (M : ℝ) :=
  {f : (Fin n → Obs d) → ℝ // Measurable f ∧ ∀ x, f x ∈ Icc (-M) M}
  -- @realizes \mathcal T_{n,M}(measurable maps into [-M,M])

/-- Mean-squared error under the model's product sample law. -/
noncomputable def mse {n d : ℕ} (P : RealLaw d)
    (est : (Fin n → Obs d) → ℝ) : ℝ :=
  ∫ x, (est x - rawAteFormula P) ^ 2 ∂productLaw n P

/-- Worst-case risk of an estimator over the specified model class. -/
noncomputable def worstCaseMSE (n d : ℕ) (epsilon M sigma : ℝ)
    (est : (Fin n → Obs d) → ℝ) : ℝ :=
  ⨆ P : ModelClass d epsilon M sigma, mse P.law est

-- @node: def:minimax-risk
/-- Minimax MSE over all total measurable `[-M,M]`-valued estimators. -/
noncomputable def minimaxRisk (n d : ℕ) (epsilon M sigma : ℝ) : ℝ :=
  ⨅ est : Estimator n d M, worstCaseMSE n d epsilon M sigma est.1
  -- @realizes \mathsf R_{n,d,epsilon,M,sigma}(infimum worst-case MSE)

/-- The logarithmic scale `log(e n)`. -/
noncomputable def logEN (n : ℕ) : ℝ := Real.log (Real.exp 1 * (n : ℝ))

/-- Polynomial-estimator component `d^2/(n^2 log(en)^2)`. -/
noncomputable def polynomialComponent (n d : ℕ) : ℝ :=
  (d : ℝ) ^ 2 / ((n : ℝ) ^ 2 * logEN n ^ 2)

/-- Collision-estimator component `sigma^2+d/n^2`. -/
noncomputable def collisionComponent (n d : ℕ) (sigma : ℝ) : ℝ :=
  sigma ^ 2 + (d : ℝ) / (n : ℝ) ^ 2

/-- The paper's upper frontier rate. -/
noncomputable def frontierRate (n d : ℕ) (sigma : ℝ) : ℝ :=
  1 / (n : ℝ) + min 1 (min (polynomialComponent n d) (collisionComponent n d sigma))
  -- @realizes r_{n,d,sigma}(n^-1 plus the three-way minimum)

/-- If [the sample is nonempty](hyp:hn), [on its declared positive-sample domain, the frontier
  rate is positive](goal). -/
lemma frontierRate_pos {n d : ℕ} {sigma : ℝ} (hn : 0 < n) :
    0 < frontierRate n d sigma := by
  have hn_real : 0 < (n : ℝ) := by exact_mod_cast hn
  have hpoly : 0 ≤ polynomialComponent n d := by
    unfold polynomialComponent
    positivity
  have hcollision : 0 ≤ collisionComponent n d sigma := by
    unfold collisionComponent
    positivity
  unfold frontierRate
  have hminimum : 0 ≤ min 1
      (min (polynomialComponent n d) (collisionComponent n d sigma)) :=
    le_min zero_le_one (le_min hpoly hcollision)
  positivity
  -- @realizes r_{n,d,sigma}(range (0,infinity) for n>0)

/-- The proved capped converse benchmark. -/
noncomputable def converseRate (n d : ℕ) (sigma : ℝ) : ℝ :=
  1 / (n : ℝ) + min 1 ((d : ℝ) / (n : ℝ) ^ 2) +
    sigma ^ 2 * min 1 (polynomialComponent n d)

/-- Number of observations in arm `a` and cell `k`. -/
def armCount {n d : ℕ} (sample : Fin n → Obs d) (a : Bool) (k : Fin d) : ℕ :=
  (Finset.univ.filter fun i => (sample i).x = k ∧ (sample i).a = a).card

/-- Total number of observations in cell `k`. -/
def cellCount {n d : ℕ} (sample : Fin n → Obs d) (k : Fin d) : ℕ :=
  armCount sample false k + armCount sample true k

-- keep: Required formal realization of the frozen D_ij symbol; intentionally not a theorem dependency.
/-- Pairwise collision-denominator kernel: the two records share a cell and
belong to opposite treatment arms. -/
def collisionDenominatorKernel {n d : ℕ} (sample : Fin n → Obs d)
    (i j : Fin n) : Bool :=
  decide ((sample i).x = (sample j).x ∧ (sample i).a ≠ (sample j).a)
  -- @realizes D_{ij}(same-cell opposite-arm pair indicator)

/-- Whether both treatment arms occur in a cell. -/
def usableCell {n d : ℕ} (sample : Fin n → Obs d) (k : Fin d) : Bool :=
  decide (0 < armCount sample false k ∧ 0 < armCount sample true k)

/-- Total occupancy among cells containing both treatment arms. -/
def usableTotal {n d : ℕ} (sample : Fin n → Obs d) : ℕ :=
  ∑ k : Fin d, if usableCell sample k then cellCount sample k else 0

/-- Sum of observed outcomes in arm `a` and cell `k`. -/
noncomputable def armSum {n d : ℕ} (sample : Fin n → Obs d)
    (a : Bool) (k : Fin d) : ℝ :=
  ∑ i : Fin n, if (sample i).x = k ∧ (sample i).a = a then (sample i).y else 0

/-- Indicator-totalized empirical arm mean. -/
noncomputable def empiricalArmMean {n d : ℕ} (sample : Fin n → Obs d)
    (a : Bool) (k : Fin d) : ℝ :=
  if 0 < armCount sample a k then armSum sample a k / armCount sample a k else 0

/-- Population collision weight for cell `k`. -/
def collisionWeight {d : ℕ} (P : RealLaw d) (k : Fin d) : ℝ :=
  2 * P.cellMass k ^ 2 * P.propensity k * (1 - P.propensity k)
  -- @realizes w_k(2 p_k^2 pi_k(1-pi_k))

/-- Total collision weight on the positive-overlap model. -/
noncomputable def totalCollisionWeight {d : ℕ} {epsilon M sigma : ℝ}
    (P : ModelClass d epsilon M sigma) : ℝ :=
  ∑ k : Fin d, collisionWeight P.law k
  -- @realizes W_P(sum of collision weights on the positive-overlap model)

/-- [The finite collection of cell masses partitions the observed probability law](goal). -/
-- @node: sum_cellMass_eq_one
lemma sum_cellMass_eq_one {d : ℕ} (P : RealLaw d) :
    ∑ k : Fin d, P.cellMass k = 1 := by
  classical
  have htuple : Measurable (fun o : Obs d => (o.x, o.a, o.y)) := by
    rw [measurable_iff_comap_le]
    rfl
  have hx : Measurable (fun o : Obs d => o.x) := measurable_fst.comp htuple
  have hsum := MeasureTheory.sum_measureReal_preimage_singleton
    (μ := P.observedLaw) (Finset.univ : Finset (Fin d))
    (f := fun o : Obs d => o.x)
    (hf := by
      intro k hk
      exact (measurableSet_singleton k).preimage hx)
    (h := by
      intro k hk
      exact measure_ne_top P.observedLaw _)
  rw [Finset.sum_congr rfl (fun k _ => P.cellMass_eq k)]
  convert hsum using 1 <;> simp [Measure.real, realMass, Set.preimage]

/-- If [the alphabet is nonempty](hyp:_hd), [a nonempty positive-overlap model has strictly
  positive collision weight](goal). -/
-- @node: totalCollisionWeight_pos
lemma totalCollisionWeight_pos {d : ℕ} {epsilon M sigma : ℝ}
    (P : ModelClass d epsilon M sigma) (_hd : 0 < d) :
    0 < totalCollisionWeight P := by
  classical
  have hmass_nonneg (k : Fin d) : 0 ≤ P.law.cellMass k :=
    (P.law.cellMass_range k).1
  obtain ⟨k, hkpos⟩ : ∃ k : Fin d, 0 < P.law.cellMass k := by
    by_contra h
    simp only [not_exists, not_lt] at h
    have hzero : ∀ k : Fin d, P.law.cellMass k = 0 := by
      intro k
      exact le_antisymm (h k) (hmass_nonneg k)
    have := sum_cellMass_eq_one P.law
    simp [hzero] at this
  obtain ⟨hpi_lower, hpi_upper⟩ := P.overlap k hkpos
  have hpi_pos : 0 < P.law.propensity k :=
    lt_of_lt_of_le P.epsilon_pos hpi_lower
  have hone_sub_pi_pos : 0 < 1 - P.law.propensity k := by
    linarith [P.epsilon_pos]
  have hweight_pos : 0 < collisionWeight P.law k := by
    unfold collisionWeight
    exact mul_pos
      (mul_pos (mul_pos (by norm_num) (sq_pos_of_pos hkpos)) hpi_pos)
      hone_sub_pi_pos
  have hweight_nonneg (l : Fin d) : 0 ≤ collisionWeight P.law l := by
    unfold collisionWeight
    obtain ⟨hpi0, hpi1⟩ := P.law.propensity_range l
    exact mul_nonneg
      (mul_nonneg (mul_nonneg (by norm_num) (sq_nonneg _)) hpi0)
      (sub_nonneg.mpr hpi1)
  unfold totalCollisionWeight
  exact Finset.sum_pos' (fun l _ => hweight_nonneg l)
    ⟨k, Finset.mem_univ k, hweight_pos⟩
  -- @realizes W_P(range (0,infinity))

-- @node: sum_cellMass_le_one
/-- [The primitive cell masses of a real law sum to at most one](goal). -/
lemma sum_cellMass_le_one {d : ℕ} (P : RealLaw d) :
    ∑ k : Fin d, P.cellMass k ≤ 1 := by
  have htuple : Measurable (fun o : Obs d => (o.x, o.a, o.y)) := by
    rw [measurable_iff_comap_le]
    rfl
  have hx : Measurable (fun o : Obs d => o.x) := measurable_fst.comp htuple
  have hmeas : ∀ k : Fin d, MeasurableSet {o : Obs d | o.x = k} := by
    intro k
    exact (measurableSet_singleton k).preimage hx
  have hdisj : (↑(Finset.univ : Finset (Fin d)) : Set (Fin d)).Pairwise
      (Function.onFun (AEDisjoint P.observedLaw) (fun k => {o : Obs d | o.x = k})) := by
    intro i hi j hj hij
    apply Disjoint.aedisjoint
    exact Set.disjoint_left.2 (by
      intro o hoi hoj
      exact hij (hoi.symm.trans hoj))
  have hsum_enn :
      (∑ k : Fin d, P.observedLaw {o : Obs d | o.x = k}) ≤ P.observedLaw Set.univ :=
    sum_measure_le_measure_univ (fun k _ => (hmeas k).nullMeasurableSet) hdisj
  rw [measure_univ] at hsum_enn
  have hfinite : ∀ k ∈ (Finset.univ : Finset (Fin d)),
      P.observedLaw {o : Obs d | o.x = k} ≠ ∞ := by
    intro k hk
    exact measure_ne_top P.observedLaw _
  rw [Finset.sum_congr rfl (fun k _ => P.cellMass_eq k)]
  change (∑ k : Fin d, (P.observedLaw {o : Obs d | o.x = k}).toReal) ≤ 1
  rw [← ENNReal.toReal_sum hfinite]
  rw [← ENNReal.toReal_one]
  exact ENNReal.toReal_mono ENNReal.one_ne_top hsum_enn

-- @node: lem:scale-sanity
/-- [Mean normalization bounds every cell effect and the ATE, so radius `2` is equivalent to the
  unrestricted class](goal). -/
lemma scale_sanity {d : ℕ} {epsilon M : ℝ} :
    (∀ P : UnrestrictedClass d epsilon M,
      (∀ k, 0 < P.law.cellMass k → |cellEffect P.law k| ≤ M) ∧
      |rawAteFormula P.law| ≤ M ∧
      (∀ k, 0 < P.law.cellMass k → |cellDeviation P.law k| ≤ 2 * M)) ∧
        -- @realizes delta_k(range [-2M,2M] on positive-mass cells)
    (∀ P : UnrestrictedClass d epsilon M,
      ∃ Q : ModelClass d epsilon M 2, Q.law = P.law) ∧
    (∀ Q : ModelClass d epsilon M 2,
      ∃ P : UnrestrictedClass d epsilon M, P.law = Q.law) := by
  have bounds : ∀ P : UnrestrictedClass d epsilon M,
      (∀ k, 0 < P.law.cellMass k → |cellEffect P.law k| ≤ M) ∧
      |rawAteFormula P.law| ≤ M ∧
      (∀ k, 0 < P.law.cellMass k → |cellDeviation P.law k| ≤ 2 * M) := by
    intro P
    have hM : 0 ≤ M := le_trans zero_le_one P.M_ge_one
    have hcell : ∀ k, 0 < P.law.cellMass k → |cellEffect P.law k| ≤ M := by
      intro k hk
      unfold cellEffect
      calc
        |P.law.outcomeMean true k - P.law.outcomeMean false k| ≤
            |P.law.outcomeMean true k| + |P.law.outcomeMean false k| := abs_sub _ _
        _ ≤ M / 2 + M / 2 := add_le_add
          (P.mean_normalization true k hk) (P.mean_normalization false k hk)
        _ = M := by ring
    have hterm : ∀ k : Fin d,
        |P.law.cellMass k * cellEffect P.law k| ≤ P.law.cellMass k * M := by
      intro k
      rcases eq_or_lt_of_le (P.law.cellMass_range k).1 with hk | hk
      · simp [← hk]
      · rw [abs_mul, abs_of_nonneg (le_of_lt hk)]
        exact mul_le_mul_of_nonneg_left (hcell k hk) (le_of_lt hk)
    have hate : |rawAteFormula P.law| ≤ M := by
      unfold rawAteFormula
      calc
        |∑ k : Fin d, P.law.cellMass k * cellEffect P.law k| ≤
            ∑ k : Fin d, |P.law.cellMass k * cellEffect P.law k| :=
          Finset.abs_sum_le_sum_abs _ _
        _ ≤ ∑ k : Fin d, P.law.cellMass k * M :=
          Finset.sum_le_sum (fun k _ => hterm k)
        _ = (∑ k : Fin d, P.law.cellMass k) * M := by rw [Finset.sum_mul]
        _ ≤ 1 * M := mul_le_mul_of_nonneg_right (sum_cellMass_le_one P.law) hM
        _ = M := one_mul M
    refine ⟨hcell, hate, ?_⟩
    intro k hk
    unfold cellDeviation
    calc
      |cellEffect P.law k - rawAteFormula P.law| ≤
          |cellEffect P.law k| + |rawAteFormula P.law| := abs_sub _ _
      _ ≤ M + M := add_le_add (hcell k hk) hate
      _ = 2 * M := by ring
  refine ⟨bounds, ?_, ?_⟩
  · intro P
    refine ⟨{
      law := P.law
      epsilon_pos := P.epsilon_pos
      epsilon_lt_half := P.epsilon_lt_half
      M_ge_one := P.M_ge_one
      sigma_nonneg := by norm_num
      sigma_le_two := by norm_num
      consistency := P.consistency
      exchangeability := P.exchangeability
      overlap := P.overlap
      mean_normalization := P.mean_normalization
      second_moment := P.second_moment
      homogeneity := ?_ }, rfl⟩
    exact (bounds P).2.2
  · intro Q
    exact ⟨{
      law := Q.law
      epsilon_pos := Q.epsilon_pos
      epsilon_lt_half := Q.epsilon_lt_half
      M_ge_one := Q.M_ge_one
      consistency := Q.consistency
      exchangeability := Q.exchangeability
      overlap := Q.overlap
      mean_normalization := Q.mean_normalization
      second_moment := Q.second_moment }, rfl⟩

end CausalSmith.Stat.DiscreteAteHeterogeneityFrontier
