import CausalSmith.Experimentation.EXP_BinaryTruthboundComplete_Research.Basic
import Causalean.Experimentation.DesignBased.Product
import Causalean.Experimentation.DesignBased.Chebyshev
import Causalean.Experimentation.DesignBased.InProb
import Causalean.Experimentation.DesignBased.GaussianCDF
import Causalean.Experimentation.DesignBased.WaldCoverage
import Causalean.Experimentation.DesignBased.FiniteDesignMeasure
import Mathlib.Analysis.SpecialFunctions.Pow.Real

/-! Arbitrary row-law triangular arrays and the separate independent product experiment. -/

open scoped BigOperators
open Finset Set Filter Topology

namespace CausalSmith.Experimentation.BinaryTruthbound

open Causalean.Experimentation.DesignBased

/-- A triangular array of block designs and block-local score/bound statistics. -/
structure BlockArray where
  -- @realizes B(row block count); @realizes j(block index)
  -- @realizes X_{Bj}(assignment carrier); @realizes G_{Bj}(assignment carrier)
  Omega : ∀ B : ℕ, Fin B → Type
  fintypeOmega : ∀ B j, Fintype (Omega B j)
  X : ∀ B j, Omega B j → ℝ -- @realizes X_{Bj}(block effect score)
  G : ∀ B j, Omega B j → ℝ -- @realizes G_{Bj}(block bound estimator)
  rowLaw : ∀ B, FiniteDesign (∀ j, Omega B j)

attribute [instance] BlockArray.fintypeOmega

-- @env: S5
variable (Arr : BlockArray)

/-- The (not necessarily product) randomization law for row `B`. -/
def rowDesign (B : ℕ) : FiniteDesign (∀ j : Fin B, Arr.Omega B j) :=
  Arr.rowLaw B

/-- The block score's design mean. -/
def blockTau (B : ℕ) (j : Fin B) : ℝ :=
  (Arr.rowLaw B).E (fun w => Arr.X B j (w j))
  -- @realizes \tau_{Bj}(E X_Bj)

/-- The block score's design variance. -/
def sigmaSq (B : ℕ) (j : Fin B) : ℝ :=
  (Arr.rowLaw B).Var (fun w => Arr.X B j (w j))
  -- @realizes \sigma_{Bj}^2(Var X_Bj)

/-- The expected block bound. -/
def blockBoundMean (B : ℕ) (j : Fin B) : ℝ :=
  (Arr.rowLaw B).E (fun w => Arr.G B j (w j))
  -- @realizes b_{Bj}(E G_Bj)

/-- Average true variance. -/
noncomputable def VBar (B : ℕ) : ℝ := (B : ℝ)⁻¹ * ∑ j, sigmaSq Arr B j
  -- @realizes V_B(B inverse times sum sigmaSq)

/-- Average expected conservative bound. -/
noncomputable def WBar (B : ℕ) : ℝ := (B : ℝ)⁻¹ * ∑ j, blockBoundMean Arr B j
  -- @realizes W_B(B inverse times sum b_Bj)

/-- Average realized bound under the row product design. -/
noncomputable def WHat (B : ℕ) (w : ∀ j : Fin B, Arr.Omega B j) : ℝ :=
  (B : ℝ)⁻¹ * ∑ j, Arr.G B j (w j)
  -- @realizes \widehat W_B(realized average of G_Bj)

/-- Average realized effect score. -/
noncomputable def tauHat (B : ℕ) (w : ∀ j : Fin B, Arr.Omega B j) : ℝ :=
  (B : ℝ)⁻¹ * ∑ j, Arr.X B j (w j)
  -- @realizes \widehat\tau_B(realized average of X_Bj)

/-- Average fixed block target. -/
noncomputable def tauBar (B : ℕ) : ℝ := (B : ℝ)⁻¹ * ∑ j, blockTau Arr B j
  -- @realizes \bar\tau_B(average of tau_Bj)

/-- Independence of the block-local `(X,G)` pairs under the row law, expressed by factorization of
expectations of products of arbitrary functions of the pairs.  Since every row has finite support,
this is equivalent to factorization of their finite joint mass function, while avoiding any
identification of assignment atoms whose `(X,G)` values coincide. -/
-- @node: ass:block-independence
def BlockIndependence (Arr : BlockArray) : Prop :=
  by
    classical
    exact
      (∀ (B : ℕ) (f : ∀ j : Fin B, ℝ → ℝ → ℝ),
        (Arr.rowLaw B).E (fun w => ∏ j, f j (Arr.X B j (w j)) (Arr.G B j (w j))) =
          ∏ j, (Arr.rowLaw B).E (fun w => f j (Arr.X B j (w j)) (Arr.G B j (w j)))) ∧
      (∀ B : ℕ,
        letI : MeasurableSpace (∀ k : Fin B, Arr.Omega B k) := ⊤
        ProbabilityTheory.iIndepFun
          (fun j (w : ∀ k : Fin B, Arr.Omega B k) => Arr.X B j (w j))
          (Arr.rowLaw B).toMeasure)

/-- A deterministic uniform bound on all block scores. -/
-- @node: ass:uniform-score-bound
def UniformScoreBound (Arr : BlockArray) (M : ℝ) : Prop :=
  0 ≤ M ∧ ∀ B j w, |Arr.X B j w| ≤ M
  -- @realizes M(nonnegative finite uniform score bound)

/-- The average true variance converges to a positive limit. -/
-- @node: ass:nondegenerate-average-variance
def NondegenerateAverageVariance (Arr : BlockArray) (V : ℝ) : Prop :=
  0 < V ∧ Tendsto (VBar Arr) atTop (𝓝 V)
  -- @realizes V(positive limiting average variance)

/-- The average variance of the realized lookup tables is asymptotically negligible. -/
-- @node: ass:bound-lln
def BoundTableVarianceNegligible (Arr : BlockArray) : Prop :=
  Tendsto (fun B : ℕ => ((B : ℝ) ^ 2)⁻¹ *
    ∑ j, (Arr.rowLaw B).Var (fun w => Arr.G B j (w j)))
    atTop (𝓝 0)

/-- Every expected block bound dominates that block's true design variance. -/
-- @node: ass:block-conservativeness
def BlockConservativeness (Arr : BlockArray) : Prop :=
  ∀ B j, sigmaSq Arr B j ≤ blockBoundMean Arr B j

/-- Every assignment-specific joint observed-data table generated by the product observation
sets. -/
abbrev ProductAssignmentRule (B : ℕ) (comp : Fin B → Setup) :=
  (w : ∀ j, (comp j).Omega) → ((j : Fin B) → (comp j).O (w j) → Fin 2) → ℝ

/-- Data of an independent product experiment, including the product objective and the entire joint
observed-table comparison space. -/
structure ProductExperimentData (B : ℕ) (comp : Fin B → Setup) (a : Fin B → ℝ)
    (q : ∀ j, FullSupportObjective (comp j)) where
  design : FiniteDesign (∀ j, (comp j).Omega)
  aggregateScore : (∀ j, Theta (comp j)) → (∀ j, (comp j).Omega) → ℝ
  objectiveWeight : (∀ j, Theta (comp j)) → ℝ
  jointObservedTables : Set (ProductAssignmentRule B comp)

/-- Construct the independent product law, weighted score, product objective, and all generated
joint observed-data tables. -/
-- @node: def:product-experiment
def productExperiment (B : ℕ) (comp : Fin B → Setup) (a : Fin B → ℝ)
    (q : ∀ j, FullSupportObjective (comp j)) : ProductExperimentData B comp a q where
  design := prodDesign (fun j => (comp j).design)
  aggregateScore := fun θ w => ∑ j, a j * score (comp j) (w j) (θ j)
  objectiveWeight := fun θ => ∏ j, (q j).1 (θ j)
  jointObservedTables := Set.univ
  -- @realizes a_j(deterministic block weight); @realizes X_j(component score)

/-- Conservative studentized Wald interval at a valid nominal level and its characterized normal
cutoff. -/
-- @node: def:wald-interval
noncomputable def waldInterval (Arr : BlockArray) (B : ℕ) (α zAlpha : ℝ)
    (_hAlpha : 0 < α ∧ α < 1) -- @realizes \alpha(significance level in (0,1))
    (_hzAlpha : 0 ≤ zAlpha ∧ stdNormalCdf zAlpha = 1 - α / 2)
      -- @realizes z_\alpha(nonnegative normal cutoff with Phi(z_alpha) = 1 - alpha/2)
    (w : ∀ j : Fin B, Arr.Omega B j) : Set ℝ :=
  Set.Icc
    (tauHat Arr B w - zAlpha * Real.sqrt (max (WHat Arr B w) 0 / B))
    (tauHat Arr B w + zAlpha * Real.sqrt (max (WHat Arr B w) 0 / B))
  -- @realizes I_B(studentized confidence interval)

/-- The standard normal CDF used in the limiting statements. -/
noncomputable abbrev normalCDF := stdNormalCdf
  -- @realizes \Phi(standard normal CDF)

/-- Under [independence of the block assignments](hyp:hInd), [the variance of the averaged variance estimator equals the sum of blockwise variances divided by the squared row count](goal). -/
lemma variance_WHat (Arr : BlockArray) (hInd : BlockIndependence Arr) (B : ℕ) :
    (rowDesign Arr B).Var (WHat Arr B) =
      ((B : ℝ) ^ 2)⁻¹ *
        ∑ j, (Arr.rowLaw B).Var (fun w => Arr.G B j (w j)) := by
  classical
  let Y : Fin B → (∀ j : Fin B, Arr.Omega B j) → ℝ :=
    fun j w => Arr.G B j (w j)
  have hcov (i j : Fin B) (hij : i ≠ j) :
      (Arr.rowLaw B).Cov (Y i) (Y j) = 0 := by
    rw [FiniteDesign.Cov_eq]
    let f : ∀ k : Fin B, ℝ → ℝ → ℝ := fun k _ g =>
      if k = i then g else if k = j then g else 1
    have hfac := hInd.1 B f
    have hleft :
        (fun w => ∏ k, f k (Arr.X B k (w k)) (Arr.G B k (w k))) =
          fun w => Y i w * Y j w := by
      funext w
      have hpoint : ∀ k : Fin B,
          f k (Arr.X B k (w k)) (Arr.G B k (w k)) =
            (if k = i then Y i w else 1) * (if k = j then Y j w else 1) := by
        intro k
        by_cases hki : k = i
        · subst k
          simp [f, Y, hij]
        · by_cases hkj : k = j
          · subst k
            simp [f, Y, hij, hki]
          · simp [f, hki, hkj]
      simp_rw [hpoint, Finset.prod_mul_distrib]
      simp
    have hright :
        (∏ k, (Arr.rowLaw B).E
          (fun w => f k (Arr.X B k (w k)) (Arr.G B k (w k)))) =
          (Arr.rowLaw B).E (Y i) * (Arr.rowLaw B).E (Y j) := by
      have hpoint : ∀ k : Fin B,
          (Arr.rowLaw B).E
              (fun w => f k (Arr.X B k (w k)) (Arr.G B k (w k))) =
            (if k = i then (Arr.rowLaw B).E (Y i) else 1) *
              (if k = j then (Arr.rowLaw B).E (Y j) else 1) := by
        intro k
        by_cases hki : k = i
        · subst k
          simp [f, Y, hij]
        · by_cases hkj : k = j
          · subst k
            simp [f, Y, hij, hki]
          · simp [f, hki, hkj, FiniteDesign.E_const]
      simp_rw [hpoint, Finset.prod_mul_distrib]
      simp
    rw [hleft, hright] at hfac
    rw [hfac, sub_self]
  unfold rowDesign WHat
  rw [(Arr.rowLaw B).Var_const_mul]
  have hsum : (fun w => ∑ j, Arr.G B j (w j)) =
      (fun (w : ∀ j : Fin B, Arr.Omega B j) => ∑ j : Fin B, 1 * Y j w) := by
    funext w
    simp [Y]
  rw [hsum]
  rw [show (Arr.rowLaw B).Var (fun w => ∑ j : Fin B, 1 * Y j w) =
      ∑ i : Fin B, ∑ j : Fin B,
        (1 : ℝ) * 1 * (Arr.rowLaw B).Cov (Y i) (Y j) by
    simpa using (Arr.rowLaw B).Var_linear_comb Finset.univ (fun _ => 1) Y]
  simp only [one_mul]
  have hinner : ∀ i : Fin B,
      (∑ j, (Arr.rowLaw B).Cov (Y i) (Y j)) = (Arr.rowLaw B).Var (Y i) := by
    intro i
    rw [Finset.sum_eq_single i]
    · exact (Arr.rowLaw B).Cov_self (Y i)
    · intro j _ hji
      exact hcov i j hji.symm
    · simp
  simp_rw [hinner]
  simp only [Y]
  rw [inv_pow]

/-- Under [independence of the block assignments](hyp:hInd) and [the stated blockwise variance-negligibility condition](hyp:hLLN), [the average variance estimator minus its mean converges in probability to zero](goal). -/
lemma WHat_sub_WBar_tendstoInProb (Arr : BlockArray) (hInd : BlockIndependence Arr)
    (hLLN : BoundTableVarianceNegligible Arr) :
    FiniteDesign.TendstoInProb (rowDesign Arr)
      (fun B w => WHat Arr B w - WBar Arr B) (fun _ => 0) := by
  have hvar : Tendsto (fun B => (rowDesign Arr B).Var (WHat Arr B)) atTop (𝓝 0) := by
    simp only [variance_WHat Arr hInd]
    exact hLLN
  have hp := FiniteDesign.tendstoInProb_of_var (rowDesign Arr) (WHat Arr) hvar
  have hmean : ∀ B, (rowDesign Arr B).E (WHat Arr B) = WBar Arr B := by
    intro B
    unfold rowDesign WHat WBar blockBoundMean
    rw [(Arr.rowLaw B).E_const_mul]
    congr 1
    simpa using (Arr.rowLaw B).E_sum Finset.univ
      (fun j w => Arr.G B j (w j))
  unfold FiniteDesign.TendstoInProb at hp ⊢
  simpa only [hmean, sub_zero] using hp

end CausalSmith.Experimentation.BinaryTruthbound
