import CausalSmith.PartialID.PID_ImperfectrefCutoffRegret_Research.Basic
import Mathlib.Order.Interval.Set.LinearOrder
import Mathlib.Order.Interval.Finset.Basic
import Mathlib.MeasureTheory.Measure.Real
import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
import Mathlib.Data.Fintype.Order
import Mathlib.Data.EReal.Basic

set_option linter.style.longLine false

/-! The finite Borel partition generated by a cutoff-policy grid fixed before sampling. -/

open MeasureTheory
open scoped BigOperators

namespace CausalSmith.PartialID.ImperfectrefCutoffRegret

noncomputable section

/-- Region `0` is all scores, regions `1,...,K` are upper tails, and region
`K+1` is empty. -/
def policyRegionFrom (K : ℕ) (tau : Fin K → ℝ) (j : ℕ) : Set ℝ :=
  if hj0 : j = 0 then Set.univ
  else if hj : j ≤ K then Set.Ici (tau ⟨j - 1, by omega⟩)
  else ∅

/-- A policy grid is prespecified independently of the sample.  Its fields say
that the ordered finite boundaries exhaust every cutoff policy and that every
interior boundary policy is represented. -/
-- @env: S5
structure PolicyGrid (M : ImperfectReferenceModel) where
  K : ℕ -- @realizes \(K\)(number of finite cutoff boundaries)
  tau : Fin K → ℝ -- @realizes \(\tau_k\)(ordered real cutoff boundaries)
  tau_strictMono : StrictMono tau -- @realizes \(\tau_k\)(strict boundary ordering)
  exhaustive : ∀ t ∈ M.T, ∃ j ≤ K + 1,
    (referSet t : Set ℝ) = policyRegionFrom K tau j
    -- @realizes \(J_{\mathcal T}\)(every cutoff is represented by a grid region)
  interior_represented : ∀ j, 1 ≤ j → j ≤ K →
    ∃ t ∈ M.T, (referSet t : Set ℝ) = policyRegionFrom K tau j
    -- @realizes \(J_{\mathcal T}\)(all finite-boundary policies occur)

/-- The half-open cutoff atom `B_k`, including both unbounded tails and the
degenerate `K=0` atom `B_0=ℝ`. -/
def policyAtom {M : ImperfectReferenceModel} (G : PolicyGrid M) (k : ℕ) : Set ℝ :=
  if hK : G.K = 0 then
    if hk : k = 0 then Set.univ else ∅
  else if hk0 : k = 0 then
    Set.Iio (G.tau ⟨0, Nat.zero_lt_of_ne_zero hK⟩)
  else if hk : k < G.K then
    Set.Ico (G.tau ⟨k - 1, by omega⟩) (G.tau ⟨k, hk⟩)
  else if hkK : k = G.K then
    Set.Ici (G.tau ⟨G.K - 1, by omega⟩)
  else ∅
  -- @realizes \(B_k\)(cutoff-generated Borel atom, including both tails)

/-- The nested referral region `E_j`. -/
def policyRegion {M : ImperfectReferenceModel} (G : PolicyGrid M) (j : ℕ) : Set ℝ :=
  policyRegionFrom G.K G.tau j
  -- @realizes \(E_j\)(nested referral region, including all and none)

/-- The represented nonempty index set `J_T`. -/
noncomputable def policyIndexSet {M : ImperfectReferenceModel}
    (G : PolicyGrid M) : Finset ℕ := by
  classical
  exact (Finset.range (G.K + 2)).filter fun j =>
    ∃ t ∈ M.T, (referSet t : Set ℝ) = policyRegion G j
  -- @realizes \(J_{\mathcal T}\)(represented policy-region indices)

lemma policyIndexSet_nonempty {M : ImperfectReferenceModel} (G : PolicyGrid M) :
    (policyIndexSet G).Nonempty := by
  classical
  obtain ⟨t, ht⟩ := M.T_nonempty
  obtain ⟨j, hj, heq⟩ := G.exhaustive t ht
  refine ⟨j, ?_⟩
  change j ∈ (Finset.range (G.K + 2)).filter _
  refine Finset.mem_filter.mpr ⟨?_, t, ht, ?_⟩
  · exact Finset.mem_range.mpr (Nat.lt_succ_iff.mpr hj)
  · simpa [policyRegion] using heq

lemma policyIndexSet_subset_range {M : ImperfectReferenceModel} (G : PolicyGrid M) :
    ∀ j ∈ policyIndexSet G, j ≤ G.K + 1 := by
  classical
  intro j hj
  change j ∈ (Finset.range (G.K + 2)).filter _ at hj
  exact Nat.lt_succ_iff.mp (Finset.mem_range.mp (Finset.mem_filter.mp hj).1)

lemma interior_mem_policyIndexSet {M : ImperfectReferenceModel} (G : PolicyGrid M)
    {j : ℕ} (hj0 : 1 ≤ j) (hjK : j ≤ G.K) :
    j ∈ policyIndexSet G := by
  classical
  obtain ⟨t, ht, heq⟩ := G.interior_represented j hj0 hjK
  change j ∈ (Finset.range (G.K + 2)).filter _
  exact Finset.mem_filter.mpr ⟨Finset.mem_range.mpr
    (Nat.lt_succ_iff.mpr (hjK.trans (Nat.le_succ G.K))),
    t, ht, by simpa [policyRegion] using heq⟩

lemma zero_mem_policyIndexSet_iff {M : ImperfectReferenceModel} (G : PolicyGrid M) :
    0 ∈ policyIndexSet G ↔ ∃ t ∈ M.T, (referSet t : Set ℝ) = Set.univ := by
  classical
  change 0 ∈ (Finset.range (G.K + 2)).filter _ ↔ _
  rw [Finset.mem_filter, Finset.mem_range]
  simp [policyRegion, policyRegionFrom]

lemma terminal_mem_policyIndexSet_iff {M : ImperfectReferenceModel} (G : PolicyGrid M) :
    G.K + 1 ∈ policyIndexSet G ↔ ∃ t ∈ M.T, (referSet t : Set ℝ) = ∅ := by
  classical
  change G.K + 1 ∈ (Finset.range (G.K + 2)).filter _ ↔ _
  rw [Finset.mem_filter, Finset.mem_range]
  simp [policyRegion, policyRegionFrom]

/-- A chosen cutoff representative for a represented region index. -/
noncomputable def policyRepresentative {M : ImperfectReferenceModel}
    (G : PolicyGrid M) (j : {j // j ∈ policyIndexSet G}) : Cutoff M := by
  classical
  have h := (Finset.mem_filter.mp j.property).2
  exact ⟨Classical.choose h, (Classical.choose_spec h).1⟩

/-- The represented region index of a cutoff. -/
noncomputable def policyIndexOf {M : ImperfectReferenceModel}
    (G : PolicyGrid M) (t : Cutoff M) : {j // j ∈ policyIndexSet G} := by
  classical
  let j := Classical.choose (G.exhaustive t.1 t.2)
  have hj := Classical.choose_spec (G.exhaustive t.1 t.2)
  refine ⟨j, Finset.mem_filter.mpr ⟨?_, t.1, t.2, ?_⟩⟩
  · exact Finset.mem_range.mpr (Nat.lt_succ_iff.mpr hj.1)
  · simpa [policyRegion] using hj.2

/-- Population mass in cutoff atom `B_k` and reference stratum `r`. -/
noncomputable def atomMass (M : ImperfectReferenceModel) (G : PolicyGrid M)
    (r : Bool) (k : ℕ) : ℝ :=
  (obsMeasure M r).real (policyAtom G k)
  -- @realizes \(\omega_{rk}\)(population atom-reference mass)

/-- Population prefix `Φ_r(j)`; only `0 ≤ j ≤ K+1` is used. -/
noncomputable def atomPrefix (M : ImperfectReferenceModel) (G : PolicyGrid M)
    (r : Bool) (j : ℕ) : ℝ :=
  ∑ k ∈ Finset.range j, atomMass M G r k
  -- @realizes \(\Phi_r(j)\)(population prefix over atoms below j)

/-- Empirical atom-reference frequency. -/
noncomputable def empAtomFreq {Ω : Type*} {M : ImperfectReferenceModel}
    (G : PolicyGrid M) {n : ℕ} (Z : Fin n → Ω → ℝ × Bool)
    (ω : Ω) (r : Bool) (k : ℕ) : ℝ := by
  classical
  exact (n : ℝ)⁻¹ * ∑ i : Fin n,
    if (Z i ω).1 ∈ policyAtom G k ∧ (Z i ω).2 = r then 1 else 0
  -- @realizes \(\widehat\omega_{rk}\)(held-out atom-reference frequency)

/-- Empirical prefix `Φ̂_r(j)`. -/
noncomputable def empAtomPrefix {Ω : Type*} {M : ImperfectReferenceModel}
    (G : PolicyGrid M) {n : ℕ} (Z : Fin n → Ω → ℝ × Bool)
    (ω : Ω) (r : Bool) (j : ℕ) : ℝ :=
  ∑ k ∈ Finset.range j, empAtomFreq G Z ω r k
  -- @realizes \(\widehat\Phi_r(j)\)(empirical prefix over atoms below j)

lemma measurableSet_policyAtom {M : ImperfectReferenceModel}
    (G : PolicyGrid M) (k : ℕ) : MeasurableSet (policyAtom G k) := by
  unfold policyAtom
  split
  · split <;> simp_all
  · split
    · exact measurableSet_Iio
    · split
      · exact measurableSet_Ico
      · split
        · exact measurableSet_Ici
        · exact MeasurableSet.empty

lemma measurableSet_policyRegion {M : ImperfectReferenceModel}
    (G : PolicyGrid M) (j : ℕ) : MeasurableSet (policyRegion G j) := by
  unfold policyRegion policyRegionFrom
  split
  · exact MeasurableSet.univ
  · split
    · exact measurableSet_Ici
    · exact MeasurableSet.empty

def regionDifferenceBorel {M : ImperfectReferenceModel} (G : PolicyGrid M)
    (i j : ℕ) : BorelScoreSet :=
  ⟨policyRegion G i \ policyRegion G j,
    (measurableSet_policyRegion G i).diff (measurableSet_policyRegion G j)⟩

/-- The cutoff atoms exhaust the real line. -/
lemma policyAtom_iUnion_eq_univ {M : ImperfectReferenceModel} (G : PolicyGrid M) :
    {s : ℝ | ∃ k ≤ G.K, s ∈ policyAtom G k} = Set.univ := by
  ext s
  simp only [Set.mem_ofPred_eq, Set.mem_univ, iff_true]
  by_cases hK : G.K = 0
  · exact ⟨0, by omega, by simp [policyAtom, hK]⟩
  · by_cases hfirst : s < G.tau ⟨0, Nat.zero_lt_of_ne_zero hK⟩
    · exact ⟨0, by omega, by simp [policyAtom, hK, hfirst]⟩
    · by_cases hlast : G.tau ⟨G.K - 1, by omega⟩ ≤ s
      · exact ⟨G.K, le_rfl, by simp [policyAtom, hK, hlast]⟩
      · let P : ℕ → Prop := fun k => ∃ hk : k < G.K, s < G.tau ⟨k, hk⟩
        have hex : ∃ k, P k :=
          ⟨G.K - 1, by refine ⟨by omega, ?_⟩; exact lt_of_not_ge hlast⟩
        let k := Nat.find hex
        obtain ⟨hklt, hks⟩ := Nat.find_spec hex
        have hkpos : 0 < k := by
          by_contra hz
          have hkzero : k = 0 := by omega
          subst k
          apply hfirst
          convert hks using 1
          apply congrArg G.tau
          exact Fin.ext hkzero.symm
        have hprev : G.tau ⟨k - 1, by omega⟩ ≤ s := by
          by_contra hp
          have hlt : P (k - 1) := ⟨by omega, lt_of_not_ge hp⟩
          have := Nat.find_min' hex hlt
          omega
        refine ⟨k, by omega, ?_⟩
        rw [policyAtom, dif_neg hK, dif_neg (Nat.ne_of_gt hkpos), dif_pos hklt]
        exact ⟨hprev, hks⟩

/-- Distinct cutoff atoms are disjoint. -/
lemma policyAtom_pairwiseDisjoint {M : ImperfectReferenceModel} (G : PolicyGrid M) :
    Set.PairwiseDisjoint (Set.Iic G.K) (policyAtom G) := by
  intro k hk l hl hkl
  change Disjoint (policyAtom G k) (policyAtom G l)
  simp only [Set.mem_Iic] at hk hl
  rw [Set.disjoint_left]
  intro s hsk hsl
  by_cases hK : G.K = 0
  · exfalso
    apply hkl
    omega
  have lower_mem (n : ℕ) (hnpos : 0 < n) (hnle : n ≤ G.K)
      (hs : s ∈ policyAtom G n) : G.tau ⟨n - 1, by omega⟩ ≤ s := by
    by_cases hnK : n = G.K
    · subst n
      simpa [policyAtom, hK] using hs
    · have hnlt : n < G.K := lt_of_le_of_ne hnle hnK
      have hmem : G.tau ⟨n - 1, by omega⟩ ≤ s ∧ s < G.tau ⟨n, hnlt⟩ := by
        simpa [policyAtom, hK, Nat.ne_of_gt hnpos, hnlt] using hs
      exact hmem.1
  have separate (a b : ℕ) (ha : a ≤ G.K) (hb : b ≤ G.K)
      (hab : a < b) (hsa : s ∈ policyAtom G a) (hsb : s ∈ policyAtom G b) : False := by
    have hbpos : 0 < b := by omega
    have hbelow := lower_mem b hbpos hb hsb
    by_cases ha0 : a = 0
    · subst a
      have habove : s < G.tau ⟨0, Nat.zero_lt_of_ne_zero hK⟩ := by
        simpa [policyAtom, hK] using hsa
      have hmono : G.tau ⟨0, Nat.zero_lt_of_ne_zero hK⟩ ≤
          G.tau ⟨b - 1, by omega⟩ :=
        G.tau_strictMono.monotone (Fin.mk_le_mk.mpr (by omega))
      exact (not_lt_of_ge (hmono.trans hbelow)) habove
    · have halt : a < G.K := lt_of_lt_of_le hab hb
      have hmem : G.tau ⟨a - 1, by omega⟩ ≤ s ∧ s < G.tau ⟨a, halt⟩ := by
        simpa [policyAtom, hK, ha0, halt] using hsa
      have habove : s < G.tau ⟨a, halt⟩ := hmem.2
      have hmono : G.tau ⟨a, halt⟩ ≤ G.tau ⟨b - 1, by omega⟩ :=
        G.tau_strictMono.monotone (Fin.mk_le_mk.mpr (by omega))
      exact (not_lt_of_ge (hmono.trans hbelow)) habove
  rcases lt_or_gt_of_ne hkl with hkl' | hlk'
  · exact separate k l hk hl hkl' hsk hsl
  · exact separate l k hl hk hlk' hsl hsk

-- @node: policyRegion_antitone
lemma policyRegion_antitone {M : ImperfectReferenceModel} (G : PolicyGrid M)
    {i j : ℕ} (hij : i ≤ j) (_hj : j ≤ G.K + 1) :
    policyRegion G j ⊆ policyRegion G i := by
  unfold policyRegion policyRegionFrom
  by_cases hi0 : i = 0
  · simp [hi0]
  have hj0 : j ≠ 0 := by omega
  by_cases hjK : j ≤ G.K
  · have hiK : i ≤ G.K := hij.trans hjK
    simp only [dif_neg hi0, dif_pos hiK, dif_neg hj0, dif_pos hjK]
    intro s hs
    exact (G.tau_strictMono.monotone
      (Fin.mk_le_mk.mpr (Nat.sub_le_sub_right hij 1))).trans hs
  · simp [hi0, hj0, hjK]

-- @node: policyAtom_eq_region_diff
lemma policyAtom_eq_region_diff {M : ImperfectReferenceModel} (G : PolicyGrid M)
    {k : ℕ} (hk : k ≤ G.K) :
    policyAtom G k = policyRegion G k \ policyRegion G (k + 1) := by
  by_cases hK : G.K = 0
  · have hk0 : k = 0 := by omega
    subst k
    simp [policyAtom, policyRegion, policyRegionFrom, hK]
  · by_cases hk0 : k = 0
    · subst k
      have hKpos : 1 ≤ G.K := Nat.one_le_iff_ne_zero.mpr hK
      ext s
      simp [policyAtom, policyRegion, policyRegionFrom, hK, hKpos]
    · by_cases hklt : k < G.K
      · simp only [policyAtom, dif_neg hK, dif_pos hklt,
          policyRegion, policyRegionFrom, dif_neg hk0,
          dif_pos (show k ≤ G.K by omega),
          dif_neg (show k + 1 ≠ 0 by omega),
          dif_pos (show k + 1 ≤ G.K by omega)]
        ext s
        simp only [Set.mem_Ico, Set.mem_sdiff, Set.mem_Ici, not_le]
        rw [show (⟨k + 1 - 1, by omega⟩ : Fin G.K) = ⟨k, hklt⟩ by
          apply Fin.ext
          simp]
      · have hkK : k = G.K := by omega
        subst k
        simp [policyAtom, policyRegion, policyRegionFrom, hK]

/-- Nested policy-region disagreements are exactly unions of whole atoms. -/
lemma policyRegion_diff_eq_atom_union {M : ImperfectReferenceModel}
    (G : PolicyGrid M) {i j : ℕ} (hij : i < j) (hj : j ≤ G.K + 1) :
    policyRegion G i \ policyRegion G j =
      {s : ℝ | ∃ k, i ≤ k ∧ k < j ∧ s ∈ policyAtom G k} := by
  ext s
  simp only [Set.mem_sdiff, Set.mem_ofPred_eq]
  constructor
  · rintro ⟨hsi, hsj⟩
    have hsall : s ∈ {x : ℝ | ∃ k ≤ G.K, x ∈ policyAtom G k} := by
      rw [policyAtom_iUnion_eq_univ G]
      trivial
    obtain ⟨k, hkK, hsk⟩ := hsall
    have hkatom := Set.ext_iff.mp (policyAtom_eq_region_diff G hkK) s |>.mp hsk
    refine ⟨k, ?_, ?_, hsk⟩
    · by_contra hki
      have hkile : k + 1 ≤ i := by omega
      have hsub := policyRegion_antitone G hkile (by omega : i ≤ G.K + 1)
      exact hkatom.2 (hsub hsi)
    · by_contra hkj
      have hjk : j ≤ k := by omega
      have hsub := policyRegion_antitone G hjk (by omega : k ≤ G.K + 1)
      exact hsj (hsub hkatom.1)
  · rintro ⟨k, hik, hkj, hsk⟩
    have hkK : k ≤ G.K := by omega
    have hkatom := Set.ext_iff.mp (policyAtom_eq_region_diff G hkK) s |>.mp hsk
    constructor
    · exact policyRegion_antitone G hik (by omega) hkatom.1
    · intro hsj
      have hsub := policyRegion_antitone G (show k + 1 ≤ j by omega) hj
      exact hkatom.2 (hsub hsj)

/-- The terminal population prefix is the observed stratum mass `q_r`. -/
lemma atomPrefix_terminal (M : ImperfectReferenceModel) (G : PolicyGrid M)
    (r : Bool) : atomPrefix M G r (G.K + 1) = obsMass M r := by
  have hd : Set.PairwiseDisjoint (↑(Finset.range (G.K + 1))) (policyAtom G) := by
    intro k hk l hl hkl
    apply policyAtom_pairwiseDisjoint G
    · simpa using Nat.le_of_lt_succ (Finset.mem_range.mp hk)
    · simpa using Nat.le_of_lt_succ (Finset.mem_range.mp hl)
    · exact hkl
  have hm : ∀ k ∈ Finset.range (G.K + 1), MeasurableSet (policyAtom G k) :=
    fun k _ => measurableSet_policyAtom G k
  have hunion : (⋃ k ∈ Finset.range (G.K + 1), policyAtom G k) = Set.univ :=
    calc
      (⋃ k ∈ Finset.range (G.K + 1), policyAtom G k) =
          {s : ℝ | ∃ k ≤ G.K, s ∈ policyAtom G k} := by
        ext s
        simp only [Set.mem_iUnion, Finset.mem_range, Set.mem_ofPred_eq]
        constructor
        · rintro ⟨k, hk, hs⟩
          exact ⟨k, by omega, hs⟩
        · rintro ⟨k, hk, hs⟩
          exact ⟨k, by omega, hs⟩
      _ = Set.univ := policyAtom_iUnion_eq_univ G
  unfold atomPrefix atomMass
  rw [← measureReal_biUnion_finset hd hm, hunion]
  rfl

/-- Prefix differences equal the mass of the corresponding policy disagreement. -/
lemma atomPrefix_sub_eq_regionDifference (M : ImperfectReferenceModel)
    (G : PolicyGrid M) (r : Bool) {i j : ℕ} (hij : i ≤ j)
    (hj : j ≤ G.K + 1) :
    atomPrefix M G r j - atomPrefix M G r i =
      stratumMass M r (regionDifferenceBorel G i j) := by
  by_cases heq : i = j
  · subst j
    simp [regionDifferenceBorel, stratumMass]
  · have hlt : i < j := lt_of_le_of_ne hij heq
    have hd : Set.PairwiseDisjoint (↑(Finset.Ico i j)) (policyAtom G) := by
      intro k hk l hl hkl
      apply policyAtom_pairwiseDisjoint G
      · simp only [Set.mem_Iic]
        have := (Finset.mem_Ico.mp hk).2
        omega
      · simp only [Set.mem_Iic]
        have := (Finset.mem_Ico.mp hl).2
        omega
      · exact hkl
    have hm : ∀ k ∈ Finset.Ico i j, MeasurableSet (policyAtom G k) :=
      fun k _ => measurableSet_policyAtom G k
    have hunion : (⋃ k ∈ Finset.Ico i j, policyAtom G k) =
        policyRegion G i \ policyRegion G j := by
      rw [policyRegion_diff_eq_atom_union G hlt hj]
      ext s
      simp only [Set.mem_iUnion, Finset.mem_Ico, Set.mem_ofPred_eq]
      constructor
      · rintro ⟨k, ⟨hik, hkj⟩, hsk⟩
        exact ⟨k, hik, hkj, hsk⟩
      · rintro ⟨k, hik, hkj, hsk⟩
        exact ⟨k, ⟨hik, hkj⟩, hsk⟩
    unfold atomPrefix atomMass stratumMass
    rw [← Finset.sum_Ico_eq_sub _ hij]
    rw [← measureReal_biUnion_finset hd hm, hunion]
    rfl

lemma atomMass_mem_Icc (M : ImperfectReferenceModel) (G : PolicyGrid M)
    (r : Bool) (k : ℕ) : atomMass M G r k ∈ Set.Icc (0 : ℝ) 1 := by
  constructor
  · exact measureReal_nonneg
  · calc
      atomMass M G r k ≤ (obsMeasure M r).real Set.univ :=
        measureReal_mono (Set.subset_univ _)
      _ = obsMass M r := rfl
      _ ≤ 1 := (obsMass_mem_Icc M r).2
  -- @realizes \(\omega_{rk}\)(population probability range [0,1])

lemma atomPrefix_mem_Icc (M : ImperfectReferenceModel) (G : PolicyGrid M)
    (r : Bool) (j : ℕ) (hj : j ≤ G.K + 1) :
    atomPrefix M G r j ∈ Set.Icc (0 : ℝ) 1 := by
  constructor
  · unfold atomPrefix
    exact Finset.sum_nonneg fun _ _ => measureReal_nonneg
  · calc
      atomPrefix M G r j ≤ atomPrefix M G r (G.K + 1) := by
        unfold atomPrefix
        apply Finset.sum_le_sum_of_subset_of_nonneg
        · intro k hk
          simp only [Finset.mem_range] at hk ⊢
          omega
        · intro k _ _
          exact measureReal_nonneg
      _ = obsMass M r := atomPrefix_terminal M G r
      _ ≤ 1 := (obsMass_mem_Icc M r).2
  -- @realizes \(\Phi_r(j)\)(population probability-prefix range [0,1])

lemma empAtomFreq_mem_Icc {Ω : Type*} {M : ImperfectReferenceModel}
    (G : PolicyGrid M) {n : ℕ} (Z : Fin n → Ω → ℝ × Bool)
    (hn : 1 ≤ n) (sample : Ω) (r : Bool) (k : ℕ) :
    empAtomFreq G Z sample r k ∈ Set.Icc (0 : ℝ) 1 := by
  classical
  have hnpos : (0 : ℝ) < n := by exact_mod_cast (lt_of_lt_of_le Nat.zero_lt_one hn)
  have hterm (i : Fin n) :
      (0 : ℝ) ≤ if (Z i sample).1 ∈ policyAtom G k ∧ (Z i sample).2 = r then 1 else 0 := by
    split <;> positivity
  have hterm_le (i : Fin n) :
      (if (Z i sample).1 ∈ policyAtom G k ∧ (Z i sample).2 = r then (1 : ℝ) else 0) ≤ 1 := by
    split <;> norm_num
  constructor
  · simp only [empAtomFreq]
    exact mul_nonneg (inv_nonneg.mpr (le_of_lt hnpos))
      (Finset.sum_nonneg fun i _ => hterm i)
  · simp only [empAtomFreq]
    calc
      (n : ℝ)⁻¹ * ∑ i : Fin n,
          (if (Z i sample).1 ∈ policyAtom G k ∧ (Z i sample).2 = r then 1 else 0) ≤
          (n : ℝ)⁻¹ * ∑ _i : Fin n, (1 : ℝ) :=
        mul_le_mul_of_nonneg_left
          (Finset.sum_le_sum fun i _ => hterm_le i) (inv_nonneg.mpr (le_of_lt hnpos))
      _ = 1 := by simp [ne_of_gt hnpos]
  -- @realizes \(\widehat\omega_{rk}\)(empirical frequency range [0,1])

lemma empAtomPrefix_mem_Icc {Ω : Type*} {M : ImperfectReferenceModel}
    (G : PolicyGrid M) {n : ℕ} (Z : Fin n → Ω → ℝ × Bool)
    (hn : 1 ≤ n) (sample : Ω) (r : Bool) (j : ℕ) (hj : j ≤ G.K + 1) :
    empAtomPrefix G Z sample r j ∈ Set.Icc (0 : ℝ) 1 := by
  classical
  have hnpos : (0 : ℝ) < n := by exact_mod_cast (lt_of_lt_of_le Nat.zero_lt_one hn)
  have hone (i : Fin n) :
      (∑ k ∈ Finset.range j,
        if (Z i sample).1 ∈ policyAtom G k ∧ (Z i sample).2 = r then (1 : ℝ) else 0) ≤ 1 := by
    by_cases hex : ∃ k ∈ Finset.range j,
        (Z i sample).1 ∈ policyAtom G k ∧ (Z i sample).2 = r
    · obtain ⟨k, hk, hki⟩ := hex
      have hkltj := Finset.mem_range.mp hk
      apply le_of_eq
      rw [Finset.sum_eq_single k]
      · simp [hki]
      · intro l hl hne
        have hdis := policyAtom_pairwiseDisjoint G
          (show k ∈ Set.Iic G.K by simp only [Set.mem_Iic]; omega)
          (show l ∈ Set.Iic G.K by
            simp only [Set.mem_Iic]
            have := Finset.mem_range.mp hl
            omega)
          hne.symm
        have hnmem : ¬(Z i sample).1 ∈ policyAtom G l := by
          intro hli
          exact Set.disjoint_left.mp hdis hki.1 hli
        simp [hnmem]
      · exact fun hnot => (hnot hk).elim
    · have hzero : (∑ k ∈ Finset.range j,
          if (Z i sample).1 ∈ policyAtom G k ∧ (Z i sample).2 = r then (1 : ℝ) else 0) = 0 := by
        rw [Finset.sum_eq_zero]
        intro k hk
        split
        · rename_i hcond
          exact (hex ⟨k, hk, hcond⟩).elim
        · rfl
      rw [hzero]
      norm_num
  have hrearrange : empAtomPrefix G Z sample r j =
      (n : ℝ)⁻¹ * ∑ i : Fin n, ∑ k ∈ Finset.range j,
        if (Z i sample).1 ∈ policyAtom G k ∧ (Z i sample).2 = r then 1 else 0 := by
    simp only [empAtomPrefix, empAtomFreq, Finset.mul_sum]
    rw [Finset.sum_comm]
  rw [hrearrange]
  constructor
  · exact mul_nonneg (inv_nonneg.mpr (le_of_lt hnpos))
      (Finset.sum_nonneg fun i _ => Finset.sum_nonneg fun k _ => by
        split <;> positivity)
  · calc
      (n : ℝ)⁻¹ * ∑ i : Fin n, ∑ k ∈ Finset.range j,
          (if (Z i sample).1 ∈ policyAtom G k ∧ (Z i sample).2 = r then 1 else 0) ≤
          (n : ℝ)⁻¹ * ∑ _i : Fin n, (1 : ℝ) :=
        mul_le_mul_of_nonneg_left
          (Finset.sum_le_sum fun i _ => hone i) (inv_nonneg.mpr (le_of_lt hnpos))
      _ = 1 := by simp [ne_of_gt hnpos]
  -- @realizes \(\widehat\Phi_r(j)\)(empirical probability-prefix range [0,1])

lemma policyCutoffs_exhausted {M : ImperfectReferenceModel} (G : PolicyGrid M) :
    ∀ t ∈ M.T, ∃ j ∈ policyIndexSet G,
      (referSet t : Set ℝ) = policyRegion G j := by
  classical
  intro t ht
  obtain ⟨j, hj, heq⟩ := G.exhaustive t ht
  refine ⟨j, ?_, by simpa [policyRegion] using heq⟩
  change j ∈ (Finset.range (G.K + 2)).filter _
  exact Finset.mem_filter.mpr ⟨Finset.mem_range.mpr (Nat.lt_succ_iff.mpr hj),
    t, ht, by simpa [policyRegion] using heq⟩

/-- Public package for the complete cutoff-generated partition construction.
Its grid is fixed independently of the sample; all empirical quantities are
functions of a later sample argument. -/
structure PolicyAtomPartitionData {Ω : Type*} (M : ImperfectReferenceModel)
    (G : PolicyGrid M) (n : ℕ) (Z : Fin n → Ω → ℝ × Bool) where
  prespecifiedGrid : PolicyGrid M
  atoms : ℕ → Set ℝ
  regions : ℕ → Set ℝ
  represented : Finset ℕ
  populationMass : Bool → ℕ → ℝ
  empiricalMass : Ω → Bool → ℕ → ℝ
  populationPrefix : Bool → ℕ → ℝ
  empiricalPrefix : Ω → Bool → ℕ → ℝ
  represented_nonempty : represented.Nonempty
  represented_bounded : ∀ j ∈ represented, j ≤ G.K + 1
  every_finite_boundary_represented : ∀ j, 1 ≤ j → j ≤ G.K → j ∈ represented
  treatAll_iff : 0 ∈ represented ↔
    ∃ t ∈ M.T, (referSet t : Set ℝ) = Set.univ
  treatNone_iff : G.K + 1 ∈ represented ↔
    ∃ t ∈ M.T, (referSet t : Set ℝ) = ∅
  cutoffs_exhausted : ∀ t ∈ M.T, ∃ j ∈ represented,
    (referSet t : Set ℝ) = regions j
  atoms_measurable : ∀ k, MeasurableSet (atoms k)
  regions_measurable : ∀ j, MeasurableSet (regions j)
  atoms_exhaustive : {s : ℝ | ∃ k ≤ G.K, s ∈ atoms k} = Set.univ
  atoms_pairwiseDisjoint : Set.PairwiseDisjoint (Set.Iic G.K) atoms
  regions_nested_by_atoms : ∀ {i j : ℕ}, i < j → j ≤ G.K + 1 →
    regions i \ regions j = {s : ℝ | ∃ k, i ≤ k ∧ k < j ∧ s ∈ atoms k}
  terminalPrefix : ∀ r, populationPrefix r (G.K + 1) = obsMass M r
  prefixDifferenceMass : ∀ r {i j : ℕ}, i ≤ j → j ≤ G.K + 1 →
    populationPrefix r j - populationPrefix r i =
      stratumMass M r (regionDifferenceBorel G i j)
  populationMass_mem_Icc : ∀ r k, populationMass r k ∈ Set.Icc (0 : ℝ) 1
  populationPrefix_mem_Icc : ∀ r j, j ≤ G.K + 1 →
    populationPrefix r j ∈ Set.Icc (0 : ℝ) 1
  empiricalMass_mem_Icc : ∀ sample r k,
    empiricalMass sample r k ∈ Set.Icc (0 : ℝ) 1
  empiricalPrefix_mem_Icc : ∀ sample r j, j ≤ G.K + 1 →
    empiricalPrefix sample r j ∈ Set.Icc (0 : ℝ) 1

/-- Policy atoms, regions, represented indices, population and empirical masses
and prefixes, and their partition/nesting/mass laws as one public construction. -/
-- @node: def:policy-atom-partition
noncomputable def policyAtomPartition {Ω : Type*} (M : ImperfectReferenceModel)
    (G : PolicyGrid M) {n : ℕ} (Z : Fin n → Ω → ℝ × Bool)
    (hn : 1 ≤ n) : PolicyAtomPartitionData M G n Z :=
  { prespecifiedGrid := G
    atoms := policyAtom G
    regions := policyRegion G
    represented := policyIndexSet G
    populationMass := atomMass M G
    empiricalMass := fun sample => empAtomFreq G Z sample
    populationPrefix := atomPrefix M G
    empiricalPrefix := fun sample => empAtomPrefix G Z sample
    represented_nonempty := policyIndexSet_nonempty G
    represented_bounded := policyIndexSet_subset_range G
    every_finite_boundary_represented := by
      intro j hj0 hjK
      exact interior_mem_policyIndexSet G hj0 hjK
    treatAll_iff := zero_mem_policyIndexSet_iff G
    treatNone_iff := terminal_mem_policyIndexSet_iff G
    cutoffs_exhausted := policyCutoffs_exhausted G
    atoms_measurable := measurableSet_policyAtom G
    regions_measurable := measurableSet_policyRegion G
    atoms_exhaustive := policyAtom_iUnion_eq_univ G
    atoms_pairwiseDisjoint := policyAtom_pairwiseDisjoint G
    regions_nested_by_atoms := by
      intro i j hij hj
      exact policyRegion_diff_eq_atom_union G hij hj
    terminalPrefix := atomPrefix_terminal M G
    prefixDifferenceMass := by
      intro r i j hij hj
      exact atomPrefix_sub_eq_regionDifference M G r hij hj
    populationMass_mem_Icc := atomMass_mem_Icc M G
    populationPrefix_mem_Icc := atomPrefix_mem_Icc M G
    empiricalMass_mem_Icc := empAtomFreq_mem_Icc G Z hn
    empiricalPrefix_mem_Icc := empAtomPrefix_mem_Icc G Z hn }
  -- @realizes \(B_k\)(complete atom family) @realizes \(E_j\)(complete region family)
  -- @realizes \(J_{\mathcal T}\)(nonempty represented index set)
  -- @realizes \(\omega_{rk}\)(population atom masses) @realizes \(\widehat\omega_{rk}\)(empirical atom frequencies)
  -- @realizes \(\Phi_r(j)\)(population prefixes and terminal q_r) @realizes \(\widehat\Phi_r(j)\)(empirical prefixes)

end
end CausalSmith.PartialID.ImperfectrefCutoffRegret
