module
public import Causalean.Stat.CLT.BerryEsseen.BerryEsseenCore
public import Causalean.Stat.CLT.BerryEsseen.BerryEsseenFourierIntegral
public import Causalean.Stat.CLT.BerryEsseen.BerryEsseenGaussian
public import Causalean.Stat.CLT.BerryEsseen.BerryEsseenIIDEnvelopes
public import Causalean.Stat.CLT.BerryEsseen.BerryEsseenLocalProduct
public import Causalean.Stat.CLT.BerryEsseen.BerryEsseenMomentLowerBound
public import Causalean.Stat.CLT.BerryEsseen.BerryEsseenPrawitzBudget
public import Causalean.Stat.CLT.BerryEsseen.BerryEsseenRefinedFourierIntegral
public import Causalean.Stat.CLT.BerryEsseen.BerryEsseenRefinedLocalProduct
public import Causalean.Stat.CLT.BerryEsseen.BerryEsseenSinc4Baseline
public import Causalean.Stat.CLT.BerryEsseen.BerryEsseenSmoothing
public import Causalean.Stat.CLT.BerryEsseen.BerryEsseenStandardize
public import Causalean.Stat.CLT.BerryEsseen.BerryEsseenTaylor
public import Causalean.Stat.CLT.BerryEsseen.BerryEsseenUnit
public import Causalean.Stat.CLT.BerryEsseen.BerryEsseenWideCharFun
public import Causalean.Stat.CLT.BerryEsseen.CDFDifferenceFourier
public import Causalean.Stat.CLT.BerryEsseen.CDFDifferenceFourierEndpoint
public import Causalean.Stat.CLT.BerryEsseen.CDFDifferenceFourierFubini
public import Causalean.Stat.CLT.BerryEsseen.CDFDifferenceFourierInterval
public import Causalean.Stat.CLT.BerryEsseen.CDFDifferenceFourierKernel
public import Causalean.Stat.CLT.BerryEsseen.CDFDifferenceFourierQuotient
public import Causalean.Stat.CLT.BerryEsseen.CDFDifferenceFourierShift
public import Causalean.Stat.CLT.BerryEsseen.CDFDifferenceIntegrable
public import Causalean.Stat.CLT.BerryEsseen.CDFDifferenceModulus
public import Causalean.Stat.CLT.BerryEsseen.CDFGeneralSandwich
public import Causalean.Stat.CLT.BerryEsseen.CDFReflection
public import Causalean.Stat.CLT.BerryEsseen.CDFSandwich
public import Causalean.Stat.CLT.BerryEsseen.CosineCubic
public import Causalean.Stat.CLT.BerryEsseen.CscSquaredSeries
public import Causalean.Stat.CLT.BerryEsseen.CscSquaredUpperHalfPlane
public import Causalean.Stat.CLT.BerryEsseen.EsseenAnalyticOneSided
public import Causalean.Stat.CLT.BerryEsseen.EsseenConvolutionDilation
public import Causalean.Stat.CLT.BerryEsseen.EsseenConvolutionTransfer
public import Causalean.Stat.CLT.BerryEsseen.EsseenInversion
public import Causalean.Stat.CLT.BerryEsseen.EsseenKernelDilation
public import Causalean.Stat.CLT.BerryEsseen.EsseenOneSided
public import Causalean.Stat.CLT.BerryEsseen.EsseenSignedKernel
public import Causalean.Stat.CLT.BerryEsseen.EsseenSignedKernelComparison
public import Causalean.Stat.CLT.BerryEsseen.EsseenSignedKernelFourier
public import Causalean.Stat.CLT.BerryEsseen.EsseenSignedKernelFourierNorm
public import Causalean.Stat.CLT.BerryEsseen.EsseenSinc4FirstMoment
public import Causalean.Stat.CLT.BerryEsseen.EsseenSinc4SecondMoment
public import Causalean.Stat.CLT.BerryEsseen.EsseenSpectralComparison
public import Causalean.Stat.CLT.BerryEsseen.EsseenUnitRawWitness
public import Causalean.Stat.CLT.BerryEsseen.EsseenUnitRegularity
public import Causalean.Stat.CLT.BerryEsseen.EsseenUnitSpectralComparison
public import Causalean.Stat.CLT.BerryEsseen.GaussianSineInversion
public import Causalean.Stat.CLT.BerryEsseen.GaussianWeightedTail
public import Causalean.Stat.CLT.BerryEsseen.IIDCharFunProduct
public import Causalean.Stat.CLT.BerryEsseen.PrawitzAbelLimit
public import Causalean.Stat.CLT.BerryEsseen.PrawitzAbelSeries
public import Causalean.Stat.CLT.BerryEsseen.PrawitzBudgetCutoffs
public import Causalean.Stat.CLT.BerryEsseen.PrawitzBudgetGaussian
public import Causalean.Stat.CLT.BerryEsseen.PrawitzBudgetHigh
public import Causalean.Stat.CLT.BerryEsseen.PrawitzBudgetHighCompact
public import Causalean.Stat.CLT.BerryEsseen.PrawitzBudgetHighSmall
public import Causalean.Stat.CLT.BerryEsseen.PrawitzBudgetLow
public import Causalean.Stat.CLT.BerryEsseen.PrawitzBudgetLowCompact
public import Causalean.Stat.CLT.BerryEsseen.PrawitzBudgetLowSmall
public import Causalean.Stat.CLT.BerryEsseen.PrawitzCompactCellIntegrals
public import Causalean.Stat.CLT.BerryEsseen.PrawitzCompactEnvelopeCells
public import Causalean.Stat.CLT.BerryEsseen.PrawitzCompactIntegrability
public import Causalean.Stat.CLT.BerryEsseen.PrawitzCompactKernelCells
public import Causalean.Stat.CLT.BerryEsseen.PrawitzCompactRationalData
public import Causalean.Stat.CLT.BerryEsseen.PrawitzCompactRealCutoffs
public import Causalean.Stat.CLT.BerryEsseen.PrawitzCutoffRationalCertificate
public import Causalean.Stat.CLT.BerryEsseen.PrawitzEnvelopes
public import Causalean.Stat.CLT.BerryEsseen.PrawitzFarGaussianTail
public import Causalean.Stat.CLT.BerryEsseen.PrawitzHighRationalCertificate
public import Causalean.Stat.CLT.BerryEsseen.PrawitzHighRealEnclosures
public import Causalean.Stat.CLT.BerryEsseen.PrawitzKernel
public import Causalean.Stat.CLT.BerryEsseen.PrawitzKernelBounds
public import Causalean.Stat.CLT.BerryEsseen.PrawitzLowGaussianMoments
public import Causalean.Stat.CLT.BerryEsseen.PrawitzLowRationalCertificate
public import Causalean.Stat.CLT.BerryEsseen.PrawitzLowRealEnclosures
public import Causalean.Stat.CLT.BerryEsseen.PrawitzRationalArithmetic
public import Causalean.Stat.CLT.BerryEsseen.PrawitzRescaledCells
public import Causalean.Stat.CLT.BerryEsseen.PrawitzSignComparison
public import Causalean.Stat.CLT.BerryEsseen.PrawitzSignIntegrability
public import Causalean.Stat.CLT.BerryEsseen.PrawitzSignSeries
public import Causalean.Stat.CLT.BerryEsseen.PrawitzSineCoefficient
public import Causalean.Stat.CLT.BerryEsseen.PrawitzSmoothing
public import Causalean.Stat.CLT.BerryEsseen.PrawitzSpatialFourier
public import Causalean.Stat.CLT.BerryEsseen.PrawitzSpectralComparison
public import Causalean.Stat.CLT.BerryEsseen.PrawitzSpectralIntegrability
public import Causalean.Stat.CLT.BerryEsseen.ReciprocalSquareTail
public import Causalean.Stat.CLT.BerryEsseen.ShiftedReciprocalSquareRegularity
public import Causalean.Stat.CLT.BerryEsseen.SincBoxConvolution
public import Causalean.Stat.CLT.BerryEsseen.SincBoxFourier
public import Causalean.Stat.CLT.BerryEsseen.SincFourthFourier
public import Causalean.Stat.CLT.BerryEsseen.SincFourthFubini
public import Causalean.Stat.CLT.BerryEsseen.SincKernelInversion
public import Causalean.Stat.CLT.BerryEsseen.SincSquaredFourier
public import Causalean.Stat.CLT.BerryEsseen.SincSquaredInversion
public import Causalean.Stat.CLT.BerryEsseen.SincSquaredPrereqs
public import Causalean.Stat.CLT.BerryEsseen.SincTriangleConvolution
public import Causalean.Stat.CLT.BerryEsseen.SmoothedCDFFourier
public import Causalean.Stat.CLT.BerryEsseen.SmoothedCDFFourierFubini
public import Causalean.Stat.CLT.BerryEsseen.SmoothedCDFFourierSwap
public import Causalean.Stat.CLT.BerryEsseen.SmoothingKernel
public import Causalean.Stat.CLT.BerryEsseen.SmoothingKernelTail
public import Causalean.Stat.CLT.BerryEsseen.SymmetrizedThirdMoment
public import Causalean.Stat.CLT.BerryEsseen.TriangularCosineIntegral

/-! # Quantitative scalar normal approximation

This barrel exports the Fourier-analytic quantitative normal approximation package for scalar iid laws with a finite third absolute moment.
-/

public section
