/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import Causalean.Stat.MEstimation.ZEstimatorCLT

/-! # Estimators defined on finite sample vectors

This module bridges the ambient-probability-space formulation used by the
asymptotic theory with estimators implemented as functions of the finite sample
vector.  It supplies the canonical `Fin n` sample vector of an `IIDSample` and
specializes the Z-estimator asymptotic-linearity and normality theorems to such
sample functions.
-/

@[expose] public section

namespace Causalean.Stat

open MeasureTheory ProbabilityTheory Filter Topology

variable {Ω X : Type*} [MeasurableSpace Ω] [MeasurableSpace X]
  {μ : Measure Ω} {P : Measure X}
  {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [FiniteDimensional ℝ E] [MeasurableSpace E] [BorelSpace E]

namespace IIDSample

/-- For [an iid sample](hyp:S), [a sample size](hyp:n), and [an outcome](hyp:ω), the
[finite sample vector](goal) sends each index below `n` to the corresponding observation. -/
def sampleVector (S : IIDSample Ω X μ P) (n : ℕ) (ω : Ω) : Fin n → X :=
  fun i => S.Z i ω

end IIDSample

/-- **Sample-function Z-estimator asymptotic linearity.** Given [a score](hyp:ψ),
[target](hyp:θ₀), [population law](hyp:P), and [Z-estimator regularity](hyp:reg), let
[an estimator function on every finite sample vector](hyp:est) be evaluated on [the finite
vector drawn from an iid sample](hyp:S). If the resulting estimator [is consistent](hyp:hConsistent),
[has stochastic equicontinuity](hyp:hStochEquicont), and [has a normalized empirical score that
is negligible in probability](hyp:hMoment), then [that sample-function estimator is
asymptotically linear with the usual inverse-Jacobian influence function](goal). -/
theorem zEstimator_asymLinear_of_sampleFn
    (ψ : E → X → E) (θ₀ : E) (P : Measure X)
    (reg : ZEstimatorRegularity ψ θ₀ P)
    [IsProbabilityMeasure μ]
    (S : IIDSample Ω X μ P) (est : (n : ℕ) → (Fin n → X) → E)
    (hConsistent : ∀ ε > 0,
      Tendsto (fun n => μ {ω | ε < ‖est n (S.sampleVector n ω) - θ₀‖}) atTop (𝓝 0))
    (hStochEquicont : StochEquicontAt ψ θ₀ P μ S
      (fun n ω => est n (S.sampleVector n ω)))
    (hMoment : IsLittleOp (fun n ω =>
      ‖(Real.sqrt (n : ℝ))⁻¹ •
        ∑ i ∈ Finset.range n, ψ (est n (S.sampleVector n ω)) (S.Z i ω)‖)
      (fun _ => (1 : ℝ)) μ) :
    IsAsymLinearVec (E := E) (fun n ω => est n (S.sampleVector n ω)) θ₀
      (fun z => -(reg.J₀_inv (ψ θ₀ z))) S (fun n => Finset.range n) :=
  zEstimator_asymLinear ψ θ₀ P reg S
    (fun n ω => est n (S.sampleVector n ω)) hConsistent hStochEquicont hMoment

/-- **Sample-function Z-estimator asymptotic normality.** Under [Z-estimator
regularity](hyp:reg), if [an estimator on finite sample vectors](hyp:est), evaluated on
[an iid sample](hyp:S), [is consistent](hyp:hConsistent), [is stochastically
equicontinuous](hyp:hStochEquicont), [has a negligible normalized sample-score
residual](hyp:hMoment), and [has measurable rescalings](hyp:hEstMeas), then [its
rescaled laws converge to the concrete Gaussian generated by the inverse-Jacobian influence
function](goal). -/
theorem zEstimator_tendsto_normal_of_sampleFn
    (ψ : E → X → E) (θ₀ : E) (P : Measure X)
    (reg : ZEstimatorRegularity ψ θ₀ P)
    [IsProbabilityMeasure μ]
    (S : IIDSample Ω X μ P) (est : (n : ℕ) → (Fin n → X) → E)
    (hConsistent : ∀ ε > 0,
      Tendsto (fun n => μ {ω | ε < ‖est n (S.sampleVector n ω) - θ₀‖}) atTop (𝓝 0))
    (hStochEquicont : StochEquicontAt ψ θ₀ P μ S
      (fun n ω => est n (S.sampleVector n ω)))
    (hMoment : IsLittleOp (fun n ω =>
      ‖(Real.sqrt (n : ℝ))⁻¹ •
        ∑ i ∈ Finset.range n, ψ (est n (S.sampleVector n ω)) (S.Z i ω)‖)
      (fun _ => (1 : ℝ)) μ)
    (hEstMeas : ∀ n, AEMeasurable
      (IsAsymLinearVec.rescaledEstimator
        (fun m ω => est m (S.sampleVector m ω)) θ₀ (fun m => Finset.range m) n) μ) :
    Tendsto (β := ProbabilityMeasure E)
      (fun n => ⟨μ.map
        (IsAsymLinearVec.rescaledEstimator
          (fun m ω => est m (S.sampleVector m ω)) θ₀ (fun m => Finset.range m) n),
        Measure.isProbabilityMeasure_map (hEstMeas n)⟩)
      atTop
      (𝓝 ⟨gaussianLimit
          (zEstimatorInfluence_measurable ψ θ₀ P reg)
          (integrable_sq_zEstimatorInfluence ψ θ₀ P reg), inferInstance⟩) :=
  zEstimator_tendsto_normal ψ θ₀ P reg S
    (fun n ω => est n (S.sampleVector n ω)) hConsistent hStochEquicont hMoment hEstMeas

end Causalean.Stat
