module
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.CitedGates
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.DictionaryScore
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.DictionaryScore.FourierInverse
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.DictionaryScore.InverseHeat
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.Estimator
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.GaussianInjective
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.ObservedMarkedChiSquare
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.LowerRegimes
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.LowerWitness
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.Packet
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.PacketEndpoint
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.PacketInterior
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.PositiveRatio
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.PublicCertificate
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.RealizedDoseMean

/-! Shared helper interface for the noisy-dose weak-design frontier. -/
public section
