/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Basic
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Frontiers
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.BinaryExchangeability
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.BinaryLaw
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.CellMoments
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.ComponentAmplitude
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.ComponentContraction
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.ComponentCounting
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.ComponentCoupling
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.ComponentFactorization
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.ComponentJointLaw
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.ComponentMeasurability
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.ComponentPartition
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.ComponentProduct
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.ComponentSpanning
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.ComponentTransport
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.Construction
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.CosineCertificate
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.CosineFamily
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.CosineRegularity
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.DatasetMarginals
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.DesignPairMoments
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.DirectCoupling
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.FrameGeometry
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.FrameRegularity
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.IntervalEvents
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.Inversion
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.MixtureOverlap
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.Occupancy
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.PartnerProbability
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.PartnerVariance
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.PointVersion
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.PrivateComparison
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.RateRegimes
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.ReleaseMoments
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.SelectionLaw
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.SignBlockFactorization
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.SignProduct
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.Stability
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.TestingPriors
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.TreeGeometry
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.TreeOrdering
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.TreeProbability
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.TreeSeries
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.TunedLength
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.TunedRisk
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.TuningEnvelope
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.Helpers.UpperGuarantees
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.TMatchedRiskFrontier
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.TRegimeAndSanity
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.TSharpIntervalFrontier
public import CausalSmith.Stat.STAT_PrivateCateRoughdesignFrontier_Research.TUniformPrivateUpper

/-! # Run barrel (auto-generated)

Aggregates every module of this causalsmith run so the whole run is ONE buildable target
(`lake build <this module>`). Research modules are not reachable from the top-level
`CausalSmith.lean` barrel, so the default lake target skips them and reports green on stale
oleans. Rewritten from the run's module set on every F-stage entry — do not hand-edit. -/
