/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Basic
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Defs.Calibration
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Defs.CalibrationRegularity
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Defs.Engine
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Defs.FrontierSpecifications
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Defs.Projection
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Defs.Upper
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.CalibratedDensityDerivatives
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.CalibratedEffects
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.CalibratedHolderModulus
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.CalibratedModelProperties
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.CalibratedPriorTesting
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.ComponentPriorRestriction
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.CoordinateBias
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.CoordinateRegularity
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.CoordinateVariance
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.CosProgram
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.EndpointCoordinates
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.EndpointQuotients
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.EndpointRadii
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.EndpointRanges
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.EngineRoutines
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.ExpProgram
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FairAmbientSmoothness
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FairAmplitudeSymmetry
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FairCellSmoothness
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FairCenterSlope
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FairComponentSupport
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FairDensityRanges
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FairEffectBounds
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FairEndpointUniqueness
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FairEquationContinuity
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FairEquationRegularity
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FairEquationSmoothness
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FairMixtureParity
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FairNumeratorSmoothness
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FairOpenNeighbourhood
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FairProductDerivatives
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FairPrognosisEnvelope
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FairRootExistence
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FairRootNearZero
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FairRootSelection
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FairRootTaylorBounds
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FairSingletonMatching
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FairSpatialOscillation
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FairTaylorDerivatives
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FairZeroAmplitude
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FairZeroEffect
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FinitePriorHellinger
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FinitePriorTesting
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FrontierAssembly
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FrontierElbows
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.FrontierMixtureRates
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.LengthSensitivity
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.LogEnclosure
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.LogProgram
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.LowerRankRates
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MachinEnclosure
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MixedAlternativePrognosisLinear
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MixedCellSmoothness
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MixedComponentSupport
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MixedCoordinateDerivatives
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MixedDensityRanges
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MixedEquationSmoothness
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MixedMixtureTaylor
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MixedNullPrognosisLinear
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MixedOpenNeighbourhood
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MixedProductDerivatives
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MixedPrognosisOscillation
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MixedPropensityLinear
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MixedPropensityOscillation
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MixedRootExistence
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MixedRootSmoothness
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MixedSingletonMatching
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MixtureAxes
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MixtureConditionalIntegration
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MixtureCovariateOccupancy
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MixtureDensities
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MixtureHellinger
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MixtureLabelTensorization
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MixtureMassNormalization
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MixtureOccupancySeries
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.MixtureProductDerivatives
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.ParametricExperiment
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.PiProgram
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.PowerClipProgram
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.PowerEnclosure
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.PowerEndpointProgram
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.PowerExpFrames
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.PowerFusion
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.PowerLogProgram
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.PowerScalarBudget
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.PowerScalarFusion
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.ProjectionApproximation
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.ProjectionCrossMoments
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.ProjectionMoments
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.ProjectionOrthogonality
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.ProjectionResidual
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.ProjectionSampling
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.RankEnclosures
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.RankRates
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.SeriesEnclosures
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.SignComponents
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.SpatialGluing
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.SpatialLipschitz
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.SqrtProgram
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.Helpers.TwoPointLength
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.T_CalibratedSupport
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.T_ConcreteArithmeticEngine
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.T_ExactCalibrations
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.T_FiniteHonestUpper
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.T_FixedBudgetRealization
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.T_FullHonestFrontierAnswer
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.T_FullHonestFrontierSolution
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.T_ObservableOdds
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.T_OriginalRecordMixtures
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.T_ParametricNullFloor
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.T_ProjectionControl
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.T_ScalarImplicitFunction
public import CausalSmith.Stat.STAT_LogoddsLowsmoothFrontier_Research.T_SharpHonestFrontier

/-! # Run barrel (auto-generated)

Aggregates every module of this causalsmith run so the whole run is ONE buildable target
(`lake build <this module>`). Research modules are not reachable from the top-level
`CausalSmith.lean` barrel, so the default lake target skips them and reports green on stale
oleans. Rewritten from the run's module set on every F-stage entry — do not hand-edit. -/
