/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Basic
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Causal
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Example
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.BandCovarianceTrace
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.BandRemainderNorms
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.CausalConstruction
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.CausalDensity
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.CausalIdentification
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.CausalIndependence
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.CausalKernels
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.CellAverageContraction
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.CellAverages
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.CellCovariance
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.CellMeanCovariance
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.CellProjectionMeans
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.CellRemainderBounds
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.ChainIndependence
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.ChainRegularity
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.ChainSquareIntegrability
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.ConditionalKernelMoments
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.ConditionalProjection
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.CorrectedMean
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.CorrectedMeanAssembly
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.CovarianceAssembly
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.CovariateKernelMoments
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.EnergyBudgets
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.EnergyDeviation
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.EnergyEnvelope
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.EnergyMoments
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.EnergyProjection
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.FrontierLower
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.FullChainCovariance
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.HighBandRemainders
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.HistogramGeometry
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.KernelDesignMeans
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.LowerMixture
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.LowerMixture.ActualPoissonMoments
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.LowerMixture.BumpIntegrals
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.LowerMixture.BumpRegularity
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.LowerMixture.Bumps
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.LowerMixture.CellLawBridge
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.LowerMixture.CellLikelihood
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.LowerMixture.CellMeasureBridge
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.LowerMixture.ChiSquare
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.LowerMixture.Depoissonize
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.LowerMixture.LocalizedDesign
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.LowerMixture.Membership
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.LowerMixture.NullOutcomes
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.LowerMixture.OrderedGrouping
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.LowerMixture.OrderedPoisson
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.LowerMixture.OutcomeCrossMoment
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.LowerMixture.OutcomeWeights
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.LowerMixture.PoissonDesign
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.LowerMixture.PoissonPartition
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.LowerMixture.RateBounds
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.LowerMixture.SampleFactorization
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.LowerMixture.UniversalAmplitude
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.MatrixTraceComparison
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.MeanAssembly
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.MeanRemainderAssembly
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.MixtureTransfer
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.ObservableRegularity
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.ObservableRule
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.ObservedDesignMeans
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.ObservedKernelMoments
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.ObservedSecondMoments
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.OperatorCovariance
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.PilotBernstein
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.PilotCellBounds
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.PilotConcentration
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.PilotCountTail
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.PilotDensityTail
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.PilotDeterministic
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.PilotPropensityBernstein
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.PilotSamplingLaw
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.ProjectedBandRemainders
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.ProjectionMeans
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.RateArithmetic
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.RateAssembly
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.RateBias
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.RateFailure
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.RatePilot
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.RateTrace
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.ResidualMoments
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.ResidualSecondMoment
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.RoleMeans
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.RoleOverlap
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.RoleOverlapBase
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.RoleOverlapMoments
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.RoleVarianceTransport
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.ScalarInversion
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.SecondOrderCovariance
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.ThirdOrderMoments
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.ThirdRoleProjections
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.TunedEnergyGuarantees
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.TunedPilotAveraging
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.TunedSamplingTransfer
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Helpers.WeightedObservedMeans
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Histogram
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Paper
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Procedure
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.TCausalCompletion
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.TMultibandCovariance
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.TNonFlatSanity
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.TSharpFrontier

/-! # Run barrel (auto-generated)

Aggregates every module of this causalsmith run so the whole run is ONE buildable target
(`lake build <this module>`). Research modules are not reachable from the top-level
`CausalSmith.lean` barrel, so the default lake target skips them and reports green on stale
oleans. Rewritten from the run's module set on every F-stage entry — do not hand-edit. -/
