/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.All
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Basic
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.AttainmentRigidity
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.BalancedBinary
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.CenteredR5Certificate
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.CenteredR5Rigidity
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.CertificateRigidity
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.Channels
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.GeneralR3Cardinality
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.GeneralR5Rigidity
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.Laplace
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.LaplaceMoments
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.LaplaceRatio
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.OAConsistency
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.OracleEnvelope
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.OracleGeometry
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.OracleValue
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.Pilot
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotAdaptiveAveraging
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotAdaptiveContinuity
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotAdaptiveInputs
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotAdaptiveLaw
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotAdaptiveLocalization
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotAdaptiveModelFields
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotAdaptiveRegularization
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotAdaptiveTransfer
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotAttainmentSupport
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotBridge
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotCDFIdentity
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotGaussianTransfer
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotGrowth
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotLocalRiskAttainment
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotLocalRiskConvergence
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotLocalRiskIdentity
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotLocalRiskSupport
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotLocalization
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotMoments
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotPrefix
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotRates
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotRowGaussianLimit
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotRowInputs
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotRowUniformization
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotRowVariance
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotSelectorBridge
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotStudentizationSupport
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotUniformTails
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotVarianceConsistency
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotVhatConsistency
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotWaldLimitSupport
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PilotWeakLimitSupport
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.PostprocessCardinality
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.Procedures
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.QuadraticConvexity
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.R3Continuity
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.R3Rigidity
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.R5Continuity
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.R5Rigidity
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.Refinement
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.RegionOpenness
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.Regions
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialAdjacentScore
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialBayesMeasurability
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialBayesOrdering
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialDomination
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialDoob
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialFisherInformation
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialFisherRecursion
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialGlobalScore
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialHistoryTransport
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialInformationEnvelope
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialJointChannel
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialLocalRiskOrder
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialLowerBound
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialMinimaxAssembly
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialObservedKernel
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialObservedLaw
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialPastScoreIntegral
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialPrefixDensity
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialPriorInformationEnvelope
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialPriorRadiusLimit
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialScore
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialScoreProjectionInputs
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialSuccessor
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialSuccessorDerivative
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialSuccessorScore
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialSuccessorScoreCharacterization
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialVanTrees
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialVanTreesAssembly
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialVanTreesIntegrals
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialVanTreesRegularity
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialVanTreesRiskBridge
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SparseSaddle
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.TranscriptUniqueness
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.TreatmentSwap
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.TBalancedReduction
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.TFiniteOracle
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.TFiveOutputRegion
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.TFiveOutputUpperBound
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.TLaplaceComparison
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.TPilotAttainment
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.TSequentialMinimax
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.TSupportTransition
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.TThreeOutputRegion

/-! # Run barrel (auto-generated)

Aggregates every module of this causalsmith run so the whole run is ONE buildable target
(`lake build <this module>`). Research modules are not reachable from the top-level
`CausalSmith.lean` barrel, so the default lake target skips them and reports green on stale
oleans. Rewritten from the run's module set on every F-stage entry — do not hand-edit. -/
