/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Basic
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.CertificateMoments
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.CitedGates
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.ConditionalMean
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.DictionaryScore
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.DictionaryScore.Fourier
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.DictionaryScore.FourierInverse
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.DictionaryScore.FourierQuantitative
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.DictionaryScore.FourierTuning
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.DictionaryScore.FourierWitness
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.DictionaryScore.HeatAlgebra
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.DictionaryScore.InverseHeat
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.DictionaryScore.PolynomialEnvelope
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.DictionaryScore.PolynomialLocalization
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.DictionaryScore.PolynomialTuning
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.DictionaryScore.PolynomialWitness
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.DirectObservedContraction
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.DirectPerturbation
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.Estimator
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.FixedNoise
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.FrontierElbows
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.GaussianConvolution
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.GaussianEnergy
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.GaussianInjective
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.GaussianMomentSeries
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.IdentificationBasics
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.InversePerturbation
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.LatentIdentification
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.LowerAssembly
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.LowerCompactTuning
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.LowerRegimes
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.LowerTuning
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.LowerWitness
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.MarkedGaussianEnergy
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.MarkedIdentification
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.ObservedMarkedChiSquare
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.ObservedPerturbationBounds
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.Packet
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.PacketDerivative
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.PacketDerivativeAssembly
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.PacketEndpoint
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.PacketEndpointFacts
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.PacketGeometry
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.PacketInterior
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.PacketInteriorEstimates
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.PacketInteriorNormalization
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.PacketKernelNormalization
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.PacketMass
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.PacketNormalization
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.PositiveRatio
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.PublicCertificate
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.RealizedDoseMean
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.ScheduleFactorization
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.ScheduleMeasurability
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.TransitionWindows
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.ZeroNoiseObserved
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Main
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.TErrorFreeReduction
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.TFiniteHonesty
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.TIdentification
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.TObservableUpper
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.TObservedLower
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.TUniformFrontier
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.TWeightedPacketConstruction

/-! # Run barrel (auto-generated)

Aggregates every module of this causalsmith run so the whole run is ONE buildable target
(`lake build <this module>`). Research modules are not reachable from the top-level
`CausalSmith.lean` barrel, so the default lake target skips them and reports green on stale
oleans. Rewritten from the run's module set on every F-stage entry — do not hand-edit. -/
