/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Basic
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.BinaryCode
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.BlockBias
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.BlockChangeOfMeasure
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.BlockChronological
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.BlockCovariance
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.BlockDecodedWindows
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.BlockDisjointPaths
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.BlockMoments
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.BlockPathMeans
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.BlockPathOverlap
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.BlockPathSupport
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.BlockPathWeights
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.BlockPhiwMoments
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.BlockSegmentDisjoint
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.BlockSegmentMoments
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.BlockSegmentOverlap
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.BlockVariance
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.FanoGate
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.FiniteStationary
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.HwExpectation
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.HwSupport
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.HwTuning
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.KLHandle
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.LowerBanditCode
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.LowerBanditInformation
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.LowerBanditKernel
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.LowerBanditObserved
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.LowerBanditTransport
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.LowerDepthTuning
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.LowerRegimeCombination
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.LowerSparseTesting
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.ObservedKLChain
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.RetentionWindowMoments
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SelectorActualBlock
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SelectorActualPrefix
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SelectorBlockHistory
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SelectorBlockTails
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SelectorChronological
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SelectorChronologicalPast
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SelectorDecodedPrefix
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SelectorExpectation
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SelectorExpectationRates
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SelectorLayercake
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SelectorMedianWitness
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SelectorMomentRates
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SelectorSegmentAction
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SelectorSegmentEndpoint
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SelectorSegmentFactorization
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SelectorSegmentGenerated
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SelectorSegmentKernelTransport
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SelectorSegmentPast
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SelectorSegmentPrefix
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SelectorSegmentSplit
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SelectorTrajectoryBridge
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SelectorTrajectoryLaw
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SelectorTuning
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SparseContextActionLaw
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SparseContraction
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SparseDensityInvariance
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SparseFairObservedLaw
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SparseFilterInformation
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SparseFilterMass
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SparseFilterPath
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SparseFilterRecursion
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SparseFilterStep
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SparseGeneratedFilterInformation
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SparseGeneratedLikelihood
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SparseGeneratedRewardInformation
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SparseInitialFilter
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SparseKLBounds
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SparseKernelFacts
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SparseObservedInformation
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SparseObservedLikelihood
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SparseObservedRewardAveraging
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SparsePacking
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SparseRetention
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SparseStationaryDensity
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SparseStationaryStart
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.TestingRegret
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.TCommonKernelLower
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.TContextualObservedKL
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.TContextualObservedWordCertificate
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.THwAlignedFiniteListFrontier
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.TMatchedRegretFrontier
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.TObservableSelectorUpper
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.TPhaseBoundary
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.TSparsePackingMembership

/-! # Run barrel (auto-generated)

Aggregates every module of this causalsmith run so the whole run is ONE buildable target
(`lake build <this module>`). Research modules are not reachable from the top-level
`CausalSmith.lean` barrel, so the default lake target skips them and reports green on stale
oleans. Rewritten from the run's module set on every F-stage entry — do not hand-edit. -/
