/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Basic
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.DornGate
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Estimators
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.AdaptationTail
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.AdmissibleOutcomeTail
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.AnalysisScale
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.BalancedBias
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.BalancedCellTail
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.BalancedConcentration
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.BalancedGram
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.BalancedMeasurability
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.BalancedScoreConcentration
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.BalancedWeights
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.BandwidthRate
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.CateLowerDesign
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.CateLowerExchangeability
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.CateLowerInformation
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.CateLowerPair
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.CateLowerRisk
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.CateLowerSampling
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.CateLowerSemantics
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.ConditionalResiduals
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.ConditionalSampling
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.ControlCellTail
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.ControlRate
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.ControlResiduals
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.ControlTail
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.CountAdmissibility
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.CountLaplace
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.HostileRayleigh
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.HostileRayleighBasic
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.Identification
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.LowerPairBounds
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.LowerPairCutoffDerivatives
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.LowerPairDesign
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.LowerPairExchangeability
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.LowerPairFiberIndependence
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.LowerPairFiberMeans
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.LowerPairHolder
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.LowerPairInformation
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.LowerPairMarginals
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.LowerPairObservation
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.LowerPairRegularity
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.LowerPairSampling
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.LowerPairSemantics
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.LowerPairTensorDerivatives
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.MassBudget
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.MinimaxLower
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.ObservedMass
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.QuadraticTilt
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.SelectedScaleNormalization
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.SelectedScaleSeries
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.SelectedScaleUnion
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.TailExpectation
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.TaylorBias
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Helpers.TwoLawRisk
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Risk
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.T_CateRate
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.T_FiniteBandwidth
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.T_HostileDesign
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.T_LowerPairMembership
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.T_SharpMinimax
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.T_UnknownTailAdaptation
public import CausalSmith.Stat.STAT_GlobaltailDesignrobustCate_Research.Witnesses

/-! # Run barrel (auto-generated)

Aggregates every module of this causalsmith run so the whole run is ONE buildable target
(`lake build <this module>`). Research modules are not reachable from the top-level
`CausalSmith.lean` barrel, so the default lake target skips them and reports green on stale
oleans. Rewritten from the run's module set on every F-stage entry — do not hand-edit. -/
