/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Basic
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Basic
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.CitedInterfaces
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.DecisionClass
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.EmpiricalProcess.EntropyChaining
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.EmpiricalProcess.PopulationCoefficient
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.EmpiricalProcess.RadialCover
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.EmpiricalProcess.ScoreL2
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.EmpiricalProcess.Separability
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.EmpiricalProcess.SeparableCover
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.EmpiricalProcess.VCExpectedMaximal
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Estimator
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.EuclideanBallsVC
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.FiniteMaxAssembly
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.FiniteMaxDecision
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.FiniteMaxLowerBound
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.BernoulliKernel
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.CommonStatisticBernoulli
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.Density
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.Design
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.Divergence
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.Family
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareAnalytic
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareClassGeometry
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareGeometry
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareGram
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareGramCertificate
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareSignedCancellation
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareSignedCertificate
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareSignedKL
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareSignedNormalized
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareSignedObservation
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareSignedOutside
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareSignedSuccess
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareSlice
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.PotentialOutcomeLaw
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.Profiles
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.Regression
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.ScoreLaw
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.SmoothEnvelope
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.LawClass
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.T3_A1A2PointIndexedConverse
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.T4_WinsorizedUpper
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.T5_MatchedFrontier
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.WinsorizedScoreMaximal
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AnalyticMeasurability
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularCellMass
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularCoordinates
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularDesign
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularFullDisc
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularGrid
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularHolder
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularLaw
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularLocality
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularMeasure
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularPacking
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularPackingOnePointKL
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularPackingTheorem
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularRadial
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularRadialAlgebra
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularRadialAssembly
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularRadialFibre
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularRadialKL
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularRadialOnePointKL
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularRadialOutcome
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularRadialQuantitative
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularScaledDelta
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.BumpHolder
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.BumpHolderScaling
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.ClassInclusion
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.CoordinateEnvelope
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.DirectProduct
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.FiniteMaxCore
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.FiniteMaxDepoisson
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.FiniteMaxExperiment
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.FiniteMaxLowerBound
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.FiniteMaxRisk
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.MaximalCoupling
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.OuterExpectation
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.Poissonization
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.Polar
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.SquareBoundary
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.T1_SameClassLogConverse
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.T2_PointIndexedLogConverse

/-! # Run barrel (auto-generated)

Aggregates every module of this causalsmith run so the whole run is ONE buildable target
(`lake build <this module>`). Research modules are not reachable from the top-level
`CausalSmith.lean` barrel, so the default lake target skips them and reports green on stale
oleans. Rewritten from the run's module set on every F-stage entry — do not hand-edit. -/
