/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import Causalean.Stat.EmpiricalProcess.Equicontinuity.LipschitzParametric

/-! # IID-sample form of the Lipschitz empirical-process bound

This module transports the finite-product expected-supremum inequality to the
sample vector generated by an `IIDSample`.
-/

@[expose] public section

namespace Causalean.Stat

open MeasureTheory ProbabilityTheory

/-- [The expected local empirical-process supremum along an i.i.d. sample
obeys the finite-dimensional Lipschitz bound](goal) for [an i.i.d.
sample](hyp:S) of [positive size](hyp:hn).  The result assumes [a measurable
Lipschitz score class with a square-integrable nonnegative
envelope](hyp:ψ,L,hψmeas,hLmeas,hL,hL2), on [a positive-radius parameter
ball](hyp:θ₀,hδ) where [the Lipschitz bound holds](hyp:hLip).

This is the `IIDSample` transport of the library's quantitative finite-product inequality,
used to derive the asymptotic equicontinuity specialization associated with van der Vaart
(1998), Example 19.7. -/
theorem IIDSample.parametricEmpProcSup_expected_le
    {Ω X E V : Type*} [MeasurableSpace Ω] [MeasurableSpace X]
    [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
    [NormedAddCommGroup V] [InnerProductSpace ℝ V] [FiniteDimensional ℝ V]
    [MeasurableSpace V] [BorelSpace V]
    {μ : Measure Ω} {P : Measure X} (S : IIDSample Ω X μ P)
    {n : ℕ} (hn : 0 < n) (ψ : E → X → V) (L : X → ℝ)
    (hψmeas : ∀ θ, Measurable (ψ θ)) (hLmeas : Measurable L)
    (hL : ∀ x, 0 ≤ L x) (hL2 : Integrable (fun x => L x ^ 2) P)
    (θ₀ : E) {δ : ℝ}
    (hLip : ∀ θ ∈ Metric.closedBall θ₀ δ, ∀ η ∈ Metric.closedBall θ₀ δ, ∀ z,
      ‖ψ θ z - ψ η z‖ ≤ L z * ‖θ - η‖)
    (hδ : 0 < δ) :
    ∫ ω, parametricEmpProcSup P ψ θ₀ hδ.le n (fun k : Fin n => S.Z k ω) ∂μ ≤
      lipschitzParametricConstant E V * δ * Real.sqrt (∫ x, L x ^ 2 ∂P) := by
  haveI : IsProbabilityMeasure μ := S.indep.isProbabilityMeasure
  letI : IsProbabilityMeasure P := by
    rw [← S.law]
    exact Measure.isProbabilityMeasure_map (S.meas 0).aemeasurable
  let W : Ω → (Fin n → X) := fun ω k => S.Z k ω
  have hWmeas : Measurable W := iidSample_finN_measurable S n
  have hUmeas : Measurable (fun T : Fin n → X =>
      parametricEmpProcSup P ψ θ₀ hδ.le n T) :=
    parametricEmpProcSup_measurable P ψ θ₀ hδ.le n hψmeas
  rw [← MeasureTheory.integral_map hWmeas.aemeasurable hUmeas.aestronglyMeasurable,
    iidSample_finN_pushforward S n]
  exact Causalean.Stat.parametricEmpProcSup_expected_le
    P hn ψ L hψmeas hLmeas hL hL2 θ₀ hLip hδ

end Causalean.Stat
