/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan

# Derived joint and observational kernels of a generalized SCM

Given a gSCM `M`, the joint kernel `jointKernel M : Kernel (FixedValues M) (RandomValues M)`
is the pushforward of the latent product measure `M.latentProduct` along the evaluation
map `M.evalMap` (see `Causal/Model/Evaluation.lean`), with the fixed-value argument `s`
threaded as the kernel parameter.  The observational kernel `obsKernel M` is then the
pushforward of `jointKernel M` onto the observed coordinates `V ⊆ V ∪ L`.

The construction uses `Kernel.compProd` of the constant kernel at `M.latentProduct`
and the deterministic kernel of `Function.uncurry M.evalMap`, followed by a
`Kernel.map Prod.snd`.  `obsCondKernel` is the jointly measurable
kernel-native conditional object built via Mathlib's `Kernel.condKernel`.

Do-calculus Rule 2 / Rule 3 kernel-level theorems (and their value-space
plumbing) have been factored out to:
  * `Causalean/Causal/Do/Rule2.lean` — Rule 2 + `fillZrW` helpers.
  * `Causalean/Causal/Do/Rule3.lean` — Rule 3 + compat bridge lemmas.

## References

* Basic Concepts.tex, Definition `def:scm-joint` (joint and observational kernels).
-/

import Causalean.SCM.Model.SCM
import Causalean.SCM.Model.Evaluation
import Causalean.SCM.Model.InterventionSet
import Mathlib.Probability.Kernel.Basic
import Mathlib.Probability.Kernel.Composition.MapComap
import Mathlib.Probability.Kernel.Composition.CompProd
import Mathlib.Probability.Kernel.CondDistrib
import Causalean.Tactic.Attr

/-! # Kernels Generated by Structural Causal Models

This file constructs the joint kernel induced by a structural causal model from
its latent distribution and evaluation map, and then obtains the observational
kernel by projecting to observed coordinates. It also provides the conditional
kernels used to state kernel-level do-calculus rules.

Do-calculus Rule 2 and Rule 3 kernel statements and their value-space helpers
live in the dedicated do-calculus files rather than in this core kernel file.

## Main definitions and results

* `SCM.jointKernel` is the law of `SCM.evalMap` under the latent product,
  parameterized by fixed values.
* `SCM.randomToObserved` and `SCM.obsKernel` project the joint law to observed
  coordinates.
* `SCM.jointKernel_apply_eq` and `SCM.jointKernel_map_commute` expose
  pushforward forms used by downstream measure proofs.
* `SCM.obsCondPairKernel` and `SCM.obsCondKernel` construct jointly measurable
  conditional laws of target coordinates given conditioning coordinates.
* `SCM.obsCondKernel_ae_eq_condDistrib` connects the kernel-native conditional
  object to the measure-level conditional distribution.
-/

namespace Causalean

variable {N : Type*} [DecidableEq N] [Fintype N]
variable {Ω : N → Type*} [∀ n, MeasurableSpace (Ω n)]

namespace SCM

open scoped MeasureTheory ProbabilityTheory

/-- For [a finite node population](hyp:N) with [measurable node-value spaces](hyp:Ω) and [a structural causal model](hyp:M), the [joint conditional law of all random-node values given fixed-node values](goal) assigns each fixed-value assignment the distribution obtained by evaluating the model under its product distribution of latent variables. It is defined [by combining that latent distribution with the deterministic evaluation rule and projecting to evaluated random values](step:1).

    The joint kernel maps each fixed-value assignment to the law of the model
evaluation under the latent product distribution.

    The joint kernel `jointKernel M : Kernel (FixedValues M) (RandomValues M)`.

    Sends each fixed assignment `s : FixedValues M` to the pushforward of the latent
    product measure `M.latentProduct` along the evaluation map `fun ℓ => M.evalMap s ℓ`.

    Implemented via `compProd` of the constant kernel at `M.latentProduct` and the
    deterministic kernel of `Function.uncurry M.evalMap`, then projected to the
    second factor: the joint `(ℓ, evalMap s ℓ)` distribution has `Prod.snd`
    pushforward equal to the pushforward of `latentProduct` by `evalMap s`. -/
noncomputable def jointKernel (M : Causalean.SCM N Ω) :
    ProbabilityTheory.Kernel (FixedValues M) (RandomValues M) :=
  ((ProbabilityTheory.Kernel.const (FixedValues M) M.latentProduct) ⊗ₖ
    (ProbabilityTheory.Kernel.deterministic
      (Function.uncurry M.evalMap) M.evalMap_measurable)).map Prod.snd

/-- For [a finite node population](hyp:N) with [measurable node-value spaces](hyp:Ω) and [a structural causal model](hyp:M), the [projection from all random-node values to observed-node values](goal) retains exactly the coordinates belonging to observed nodes. It is defined [coordinate by coordinate](step:1). -/
def randomToObserved (M : Causalean.SCM N Ω) :
    RandomValues M → ObservedValues M :=
  fun ξ v => ξ ⟨v.val, Finset.mem_union_left _ v.property⟩

/-- The observed-coordinate projection is measurable. -/
@[fun_prop]
theorem measurable_randomToObserved (M : Causalean.SCM N Ω) :
    Measurable (M.randomToObserved) := by
  refine measurable_pi_lambda _ ?_
  intro v
  exact measurable_pi_apply
    (a := (⟨v.val, Finset.mem_union_left _ v.property⟩ : {i // i ∈ M.randomVars}))

/-- For [a structural causal model `M`](hyp:M) and [a fixed-node assignment
`s`](hyp:s), [the joint kernel evaluated at `s` equals the pushforward of the
latent-variable product measure through the evaluation map at `s`](goal).

    Pointwise form of the joint kernel: at each fixed assignment `s`, the joint kernel
    is the pushforward of `M.latentProduct` along `fun ℓ => M.evalMap s ℓ`.

    This is the direct `Measure`-level form of `jointKernel`, collapsing the
    `compProd`-of-`const`-and-`deterministic` construction used in the definition. -/
lemma jointKernel_apply_eq (M : Causalean.SCM N Ω) (s : FixedValues M) :
    M.jointKernel s = M.latentProduct.map (fun ℓ => M.evalMap s ℓ) := by
  have hf : Measurable (fun ℓ : LatentValues M => M.evalMap s ℓ) := by
    fun_prop
  refine MeasureTheory.Measure.ext fun A hA => ?_
  unfold jointKernel
  rw [ProbabilityTheory.Kernel.map_apply _ measurable_snd,
      MeasureTheory.Measure.map_apply measurable_snd hA,
      ProbabilityTheory.Kernel.compProd_apply (measurable_snd hA),
      ProbabilityTheory.Kernel.const_apply,
      MeasureTheory.Measure.map_apply hf hA]
  -- LHS: ∫⁻ ℓ, (deterministic (uncurry evalMap)) (s, ℓ)
  --   (Prod.mk ℓ ⁻¹' (Prod.snd ⁻¹' A)) ∂latentProduct
  -- RHS: latentProduct ((fun ℓ => evalMap s ℓ) ⁻¹' A)
  simp only [ProbabilityTheory.Kernel.deterministic_apply, Function.uncurry_apply_pair]
  -- Simplify the preimage `Prod.mk ℓ ⁻¹' (Prod.snd ⁻¹' A) = A` (rfl on Set membership).
  have hset : ∀ ℓ : LatentValues M,
      (Prod.mk ℓ ⁻¹' (Prod.snd ⁻¹' A) : Set (RandomValues M)) = A := fun _ => rfl
  simp only [hset]
  -- Goal: ∫⁻ ℓ, Measure.dirac (M.evalMap s ℓ) A ∂latentProduct
  --     = latentProduct ((fun ℓ => evalMap s ℓ) ⁻¹' A)
  -- Bridge through indicator form.
  trans (∫⁻ ℓ, Set.indicator ((fun ℓ => M.evalMap s ℓ) ⁻¹' A) (fun _ => (1 : ENNReal)) ℓ
              ∂M.latentProduct)
  · apply MeasureTheory.lintegral_congr
    intro ℓ
    rw [MeasureTheory.Measure.dirac_apply' _ hA]
    simp only [Set.indicator, Set.mem_preimage, Pi.one_apply]
    rfl
  · exact MeasureTheory.lintegral_indicator_one (hf hA)

/-- For [a finite node population](hyp:N) with [measurable node-value spaces](hyp:Ω) and [a structural causal model](hyp:M), the [conditional law of observed-node values given fixed-node values](goal) is obtained by mapping the joint conditional law to its observed coordinates. It is defined [by that observed-coordinate projection](step:1).

    The observational kernel maps each fixed-value assignment to the induced law
of the observed nodes.

    The observational kernel `obsKernel M : Kernel (FixedValues M) (ObservedValues M)`.

    Defined by pushing `jointKernel M` through the observed-coordinate projection
    `randomToObserved : RandomValues M → ObservedValues M`. -/
noncomputable def obsKernel (M : Causalean.SCM N Ω) :
    ProbabilityTheory.Kernel (FixedValues M) (ObservedValues M) :=
  (M.jointKernel).map M.randomToObserved

/-- For [a finite, distinguishable node population with measurable node-value spaces](hyp:N,Ω) and [a structural causal model](hyp:M), the [joint conditional law of random-node values given fixed-node values](goal) is a Markov kernel: every conditional law is a probability measure.

The joint kernel is a Markov kernel. -/
instance instIsMarkovKernelJointKernel (M : Causalean.SCM N Ω) :
    ProbabilityTheory.IsMarkovKernel M.jointKernel := by
  unfold jointKernel
  exact ProbabilityTheory.Kernel.IsMarkovKernel.map _ measurable_snd

/-- For [a finite, distinguishable node population with measurable node-value spaces](hyp:N,Ω) and [a structural causal model](hyp:M), the [conditional law of observed-node values given fixed-node values](goal) is a Markov kernel: every conditional law is a probability measure.

The observational kernel is a Markov kernel. -/
instance instIsMarkovKernelObsKernel (M : Causalean.SCM N Ω) :
    ProbabilityTheory.IsMarkovKernel M.obsKernel := by
  unfold obsKernel
  exact ProbabilityTheory.Kernel.IsMarkovKernel.map _ M.measurable_randomToObserved

/-- Every slice of a Markov kernel has total mass one. -/
theorem kernel_apply_univ {α β : Type*} [MeasurableSpace α] [MeasurableSpace β]
    (κ : ProbabilityTheory.Kernel α β) [ProbabilityTheory.IsMarkovKernel κ] (a : α) :
    κ a Set.univ = 1 :=
  MeasureTheory.measure_univ

/-- Each observational-kernel slice has total mass one. -/
theorem obsKernel_apply_univ (M : Causalean.SCM N Ω) (s : FixedValues M) :
    M.obsKernel s Set.univ = 1 :=
  kernel_apply_univ M.obsKernel s

/-- The observational kernel can be written as one pushforward that evaluates
the model and then projects to observed coordinates.

    **Pushforward and projection commute.**  The observational kernel can be obtained
    either in two steps (first push the latent product along `evalMap`, then project
    onto observed coordinates), or in one step by folding the projection into the
    deterministic kernel.  This is purely `Kernel.map_comp_right`, exposed here so that
    downstream proofs can reach for the one-step form directly. -/
theorem jointKernel_map_commute (M : Causalean.SCM N Ω) :
    M.obsKernel =
      ((ProbabilityTheory.Kernel.const (FixedValues M) M.latentProduct) ⊗ₖ
        (ProbabilityTheory.Kernel.deterministic
          (Function.uncurry M.evalMap) M.evalMap_measurable)).map
        (M.randomToObserved ∘ Prod.snd) := by
  unfold obsKernel jointKernel
  exact (ProbabilityTheory.Kernel.map_comp_right _
    measurable_snd M.measurable_randomToObserved).symm

-- ============================================================
-- § `obsCondKernel` — jointly measurable conditional kernel
-- ============================================================

/-- For [a finite node population](hyp:N) with [measurable node-value spaces](hyp:Ω), [a structural causal model](hyp:M), [a target-node set](hyp:Y), [a conditioning-node set](hyp:CC), [the requirement that every target node is observed](hyp:hY), and [the requirement that every conditioning node is observed](hyp:hCC), the [joint conditional law of the conditioning and target coordinates given fixed-node values](goal) maps each observational law to the ordered pair of its conditioning-coordinate and target-coordinate restrictions. It is defined [by that paired coordinate projection](step:1).

    The conditional-pair kernel pushes the observational law to conditioning
coordinates paired with target coordinates. -/
noncomputable def obsCondPairKernel
    (M : Causalean.SCM N Ω) (Y CC : Finset (SWIGNode N))
    (hY : Y ⊆ M.observed) (hCC : CC ⊆ M.observed) :
    ProbabilityTheory.Kernel (FixedValues M)
      (ValuesOn CC (swigΩ Ω) × ValuesOn Y (swigΩ Ω)) :=
  (M.obsKernel).map (fun ω =>
    (valuesProjection hCC ω, valuesProjection hY ω))

/-- The conditional-pair kernel is the observational kernel pushed forward along the map that
records the conditioning coordinates paired with the target coordinates. -/
@[causal_defs_simps]
lemma obsCondPairKernel_eq
    (M : Causalean.SCM N Ω) (Y CC : Finset (SWIGNode N))
    (hY : Y ⊆ M.observed) (hCC : CC ⊆ M.observed) :
    M.obsCondPairKernel Y CC hY hCC =
      (M.obsKernel).map (fun ω =>
        (valuesProjection hCC ω, valuesProjection hY ω)) :=
  rfl

/-- For [a finite node population](hyp:N) with [measurable node-value spaces](hyp:Ω), [a structural causal model](hyp:M), [a target-node set](hyp:Y), [a conditioning-node set](hyp:CC), [the requirement that every target node is observed](hyp:hY), [the requirement that every conditioning node is observed](hyp:hCC), a nonempty standard-Borel target-value space, and a conditioning-value space satisfying the stipulated countable-generation condition, the [jointly measurable conditional law of target coordinates given fixed-node and conditioning-coordinate values](goal) is obtained [as a conditional law from the paired observational distribution](step:1).

    The observational conditional kernel is a jointly measurable conditional law
of target coordinates given conditioning coordinates.

    Jointly measurable conditional law of the `Y`-coordinates given the
    `CC`-coordinates under `M.obsKernel`. -/
noncomputable def obsCondKernel
    (M : Causalean.SCM N Ω) (Y CC : Finset (SWIGNode N))
    (hY : Y ⊆ M.observed) (hCC : CC ⊆ M.observed)
    [StandardBorelSpace (ValuesOn Y (swigΩ Ω))]
    [Nonempty (ValuesOn Y (swigΩ Ω))]
    [MeasurableSpace.CountableOrCountablyGenerated
      (FixedValues M) (ValuesOn CC (swigΩ Ω))] :
    ProbabilityTheory.Kernel
      (FixedValues M × ValuesOn CC (swigΩ Ω))
      (ValuesOn Y (swigΩ Ω)) :=
  letI : ProbabilityTheory.IsFiniteKernel (M.obsCondPairKernel Y CC hY hCC) := by
    letI : ProbabilityTheory.IsMarkovKernel (M.obsCondPairKernel Y CC hY hCC) := by
      simp only [causal_defs_simps]
      exact ProbabilityTheory.Kernel.IsMarkovKernel.map _
        (Measurable.prodMk
          (measurable_valuesProjection hCC)
          (measurable_valuesProjection hY))
    infer_instance
  (M.obsCondPairKernel Y CC hY hCC).condKernel

/-- At a fixed value `s` of the intervention-free (fixed) coordinates, provided [the target
coordinates `Y` are observed](hyp:hY) and [the conditioning coordinates `CC` are
observed](hyp:hCC), [the jointly-measurable conditional kernel `obsCondKernel` built from `Y`
and `CC`, evaluated at `s`, agrees almost everywhere — under the pushforward of the
observational kernel onto `CC` — with the measure-theoretic conditional distribution of `Y`
given `CC` under the observational kernel at `s`](goal).

    **Bridge: `obsCondKernel` agrees with `condDistrib` a.e.**

    This is just the kernel-vs-measure disintegration
    uniqueness specialized to `M.obsCondPairKernel = M.obsKernel.map (π_CC, π_Y)`,
    whose `condKernel` is by definition `M.obsCondKernel`. -/
theorem obsCondKernel_ae_eq_condDistrib
    (M : Causalean.SCM N Ω) (Y CC : Finset (SWIGNode N))
    (hY : Y ⊆ M.observed) (hCC : CC ⊆ M.observed)
    [StandardBorelSpace (ValuesOn Y (swigΩ Ω))]
    [Nonempty (ValuesOn Y (swigΩ Ω))]
    [MeasurableSpace.CountableOrCountablyGenerated
      (FixedValues M) (ValuesOn CC (swigΩ Ω))]
    (s : M.FixedValues) :
    (fun c => M.obsCondKernel Y CC hY hCC (s, c))
      =ᵐ[(M.obsKernel s).map (valuesProjection hCC)]
        ProbabilityTheory.condDistrib (valuesProjection hY)
          (valuesProjection hCC) (M.obsKernel s) := by
  letI : ProbabilityTheory.IsMarkovKernel (M.obsCondPairKernel Y CC hY hCC) := by
    simp only [causal_defs_simps]
    exact ProbabilityTheory.Kernel.IsMarkovKernel.map _
      (Measurable.prodMk
        (measurable_valuesProjection hCC)
        (measurable_valuesProjection hY))
  -- `Kernel.condKernel_apply_eq_condKernel` gives a.e. equality with the
  -- measure-level `condKernel`; rewrite `Kernel.fst` of the pair kernel.
  have h := ProbabilityTheory.Kernel.condKernel_apply_eq_condKernel
    (M.obsCondPairKernel Y CC hY hCC) s
  -- `Kernel.fst (M.obsKernel.map (π_CC, π_Y)) s = (M.obsKernel s).map π_CC`.
  have hfst :
      ProbabilityTheory.Kernel.fst (M.obsCondPairKernel Y CC hY hCC) s
        = (M.obsKernel s).map (valuesProjection hCC) := by
    simp only [causal_defs_simps]
    rw [ProbabilityTheory.Kernel.fst_map_prod _ (measurable_valuesProjection hY),
        ProbabilityTheory.Kernel.map_apply _ (measurable_valuesProjection hCC)]
  rw [hfst] at h
  -- `condDistrib π_Y π_CC μ = (μ.map (π_CC, π_Y)).condKernel = (obsCondPairKernel s).condKernel`.
  have hmap :
      (M.obsCondPairKernel Y CC hY hCC) s
        = MeasureTheory.Measure.map
            (fun ω => (valuesProjection hCC ω, valuesProjection hY ω))
            (M.obsKernel s) := by
    simp only [causal_defs_simps]
    exact ProbabilityTheory.Kernel.map_apply M.obsKernel
      ((measurable_valuesProjection hCC).prodMk (measurable_valuesProjection hY)) s
  have hcd :
      ProbabilityTheory.condDistrib (valuesProjection hY)
          (valuesProjection hCC) (M.obsKernel s)
        = (M.obsCondPairKernel Y CC hY hCC s).condKernel := by
    rw [ProbabilityTheory.condDistrib]
    congr 1
    exact hmap.symm
  rw [hcd]
  exact h

end SCM

end Causalean
