module
public import Mathlib.LinearAlgebra.Dimension.Constructions
public import Mathlib.LinearAlgebra.Dimension.Finrank
public import Mathlib.Analysis.Normed.Module.FiniteDimension

/-!
# Pair ranges for finite-dimensional prediction classes

This file packages the linear space containing the transformed prediction pair
`(g, g - f)`.  Its dimension is at most twice the coefficient dimension.
-/

@[expose] public section

noncomputable section

namespace CausalSmith.Substrate

open Module

variable {d : ℕ} {W : Type*} [Fintype W]

/-- The linear map sending two coefficient vectors to the prediction pair
`(g, g - f)`. -/
def pairDifferenceLinearMap
    (L : (Fin d → ℝ) →ₗ[ℝ] (W → ℝ)) :
    ((Fin d → ℝ) × (Fin d → ℝ)) →ₗ[ℝ] ((W → ℝ) × (W → ℝ)) where
  toFun θ := (L θ.1, L θ.1 - L θ.2)
  map_add' θ φ := by
    ext w <;> simp <;> ring
  map_smul' c θ := by
    ext w <;> simp <;> ring

/-- The transformed pair space generated by a `d`-dimensional linear
prediction map has real dimension at most `2*d`. -/
theorem finrank_pairDifference_range_le_two_mul
    (L : (Fin d → ℝ) →ₗ[ℝ] (W → ℝ)) :
    finrank ℝ (pairDifferenceLinearMap L).range ≤ 2 * d := by
  calc
    finrank ℝ (pairDifferenceLinearMap L).range ≤
        finrank ℝ ((Fin d → ℝ) × (Fin d → ℝ)) :=
      (pairDifferenceLinearMap L).finrank_range_le
    _ = 2 * d := by
      simp [Module.finrank_prod, Module.finrank_pi_fintype]
      omega

/-- A pair of predictions in the range of `L` yields an element of the
transformed pair range whose coordinates are exactly `(g, g-f)`. -/
theorem pairDifference_mem_range
    (L : (Fin d → ℝ) →ₗ[ℝ] (W → ℝ))
    (g f : W → ℝ)
    (hg : ∃ θ, g = L θ) (hf : ∃ θ, f = L θ) :
    (g, g - f) ∈ (pairDifferenceLinearMap L).range := by
  rcases hg with ⟨θ, rfl⟩
  rcases hf with ⟨φ, rfl⟩
  exact ⟨(θ, φ), rfl⟩

/-- If `g` and `f` are coordinatewise in `[0,1]`, then the transformed pair
`(g, g-f)` lies in the unit ball for the product supremum norm. -/
theorem norm_pair_sub_le_one
    (g f : W → ℝ)
    (hg : ∀ w, g w ∈ Set.Icc (0 : ℝ) 1)
    (hf : ∀ w, f w ∈ Set.Icc (0 : ℝ) 1) :
    ‖(g, g - f)‖ ≤ 1 := by
  rw [Prod.norm_def]
  apply max_le
  · rw [Pi.norm_def]
    norm_cast
    apply Finset.sup_le
    intro w _
    exact_mod_cast
      (abs_le.2 ⟨by linarith [(hg w).1], (hg w).2⟩)
  · rw [Pi.norm_def]
    norm_cast
    apply Finset.sup_le
    intro w _
    change ‖g w - f w‖₊ ≤ 1
    have hreal : |g w - f w| ≤ (1 : ℝ) :=
      abs_le.2 ⟨by linarith [(hg w).1, (hf w).2],
        by linarith [(hg w).2, (hf w).1]⟩
    exact_mod_cast hreal

end CausalSmith.Substrate
