module
public import Mathlib

/-!
# Finite-jump counting processes and their compensated integrals

A path is a finite set of distinct event times in a fixed positive horizon.
The intensity premise is a conditional increment identity against every bounded
observation available at the left endpoint. The predictable compensator formula
and the quadratic isometry are consequences to be proved in later modules.
-/

@[expose] public section

open MeasureTheory Set

namespace Causalean.Stat.RecurrentEvent.CountingProcess.FiniteJump

/-- Predictable cylinders pair a left-open time interval with an event
observable at the left endpoint. -/
def predictableCylinders {Ω : Type*} [MeasurableSpace Ω]
    (ℱ : ℝ → MeasurableSpace Ω) : Set (Set (ℝ × Ω)) :=
  {S | ∃ (a b : ℝ) (B : Set Ω), MeasurableSet[ℱ a] B ∧
    S = (Ioc a b) ×ˢ B}

/-- The predictable σ-algebra is generated by left-endpoint cylinders. -/
@[instance_reducible] def predictableSpace {Ω : Type*} [MeasurableSpace Ω]
    (ℱ : ℝ → MeasurableSpace Ω) : MeasurableSpace (ℝ × Ω) :=
  MeasurableSpace.generateFrom (predictableCylinders ℱ)

/-- A finite-horizon, simple counting process with an absolutely continuous
intensity `atRisk × intensity` relative to a filtration. The conditional
increment identity is stated against bounded past-measurable test functions;
all event times lie strictly after zero and at or before the horizon. -/
structure Model (Ω : Type*) [MeasurableSpace Ω] (μ : Measure Ω) where
  horizon : ℝ
  horizon_pos : 0 < horizon
  eventTimes : Ω → Finset ℝ
  eventTimes_measurable : Measurable eventTimes
  events_in_horizon : ∀ ω t, t ∈ eventTimes ω → 0 < t ∧ t ≤ horizon
  filtration : ℝ → MeasurableSpace Ω
  filtration_mono : Monotone filtration
  filtration_le : ∀ t, filtration t ≤ (inferInstance : MeasurableSpace Ω)
  atRisk : ℝ → Ω → ℝ
  intensity : ℝ → Ω → ℝ
  atRisk_joint_measurable : Measurable (fun p : ℝ × Ω => atRisk p.1 p.2)
  intensity_joint_measurable : Measurable (fun p : ℝ × Ω => intensity p.1 p.2)
  atRisk_predictable : Measurable[predictableSpace filtration]
    (fun p : ℝ × Ω => atRisk p.1 p.2)
  intensity_predictable : Measurable[predictableSpace filtration]
    (fun p : ℝ × Ω => intensity p.1 p.2)
  atRisk_nonneg : ∀ t ω, 0 ≤ atRisk t ω
  intensity_nonneg : ∀ t ω, 0 ≤ intensity t ω
  rate_integrable : ∀ ω, IntegrableOn (fun t => atRisk t ω * intensity t ω)
    (Ioc 0 horizon) volume
  rate_bounded : ∃ C : ℝ, ∀ t ω, 0 ≤ t → t ≤ horizon →
    atRisk t ω * intensity t ω ≤ C
  count_square_integrable : Integrable
    (fun ω => ((eventTimes ω).card : ℝ) ^ 2) μ
  count_adapted : ∀ t, Measurable[filtration t]
    (fun ω => ((eventTimes ω).filter (fun s => s ≤ t)).card)
  conditional_intensity_increment :
    ∀ (a b : ℝ) (F : Ω → ℝ), 0 ≤ a → a ≤ b → b ≤ horizon →
      Measurable[filtration a] F → (∃ C : ℝ, ∀ ω, |F ω| ≤ C) →
      Integrable (fun ω => F ω *
        (((eventTimes ω).filter (fun t => a < t ∧ t ≤ b)).card : ℝ)) μ →
      Integrable (fun ω => F ω *
        ∫ t in Ioc a b, atRisk t ω * intensity t ω ∂volume) μ →
      (∫ ω, F ω *
        (((eventTimes ω).filter (fun t => a < t ∧ t ≤ b)).card : ℝ) ∂μ) =
      ∫ ω, F ω *
        (∫ t in Ioc a b, atRisk t ω * intensity t ω ∂volume) ∂μ

/-- The count up to time `t` is the number of event times at or before `t`. -/
noncomputable def Model.count {Ω : Type*} [MeasurableSpace Ω] {μ : Measure Ω}
    (M : Model Ω μ) (t : ℝ) (ω : Ω) : ℕ :=
  ((M.eventTimes ω).filter (fun s => s ≤ t)).card

/-- The pathwise compensator is the integrated at-risk intensity through `t`. -/
noncomputable def Model.compensator {Ω : Type*} [MeasurableSpace Ω]
    {μ : Measure Ω} (M : Model Ω μ) (t : ℝ) (ω : Ω) : ℝ :=
  ∫ s in Ioc 0 t, M.atRisk s ω * M.intensity s ω ∂volume

/-- A predictable integrand is measurable on time and sample under the
predictable σ-algebra generated by left-endpoint observations. -/
def Model.Predictable {Ω : Type*} [MeasurableSpace Ω] {μ : Measure Ω}
    (M : Model Ω μ) (H : ℝ → Ω → ℝ) : Prop :=
  Measurable[predictableSpace M.filtration] (fun p : ℝ × Ω => H p.1 p.2)

/-- The event part of a finite-jump stochastic integral is the finite sum of
the predictable integrand evaluated at event times up to `t`. -/
noncomputable def Model.jumpIntegral {Ω : Type*} [MeasurableSpace Ω]
    {μ : Measure Ω} (M : Model Ω μ) (H : ℝ → Ω → ℝ)
    (t : ℝ) (ω : Ω) : ℝ :=
  ∑ s ∈ (M.eventTimes ω).filter (fun s => s ≤ t), H s ω

/-- The compensator part of a stochastic integral integrates the predictable
integrand against the pathwise absolutely continuous compensator. -/
noncomputable def Model.energyIntegral {Ω : Type*} [MeasurableSpace Ω]
    {μ : Measure Ω} (M : Model Ω μ) (H : ℝ → Ω → ℝ)
    (t : ℝ) (ω : Ω) : ℝ :=
  ∫ s in Ioc 0 t, H s ω * (M.atRisk s ω * M.intensity s ω) ∂volume

/-- The compensated stochastic integral is its finite event sum minus its
integral against the at-risk intensity. -/
noncomputable def Model.stochasticIntegral {Ω : Type*} [MeasurableSpace Ω]
    {μ : Measure Ω} (M : Model Ω μ) (H : ℝ → Ω → ℝ)
    (t : ℝ) (ω : Ω) : ℝ :=
  M.jumpIntegral H t ω - M.energyIntegral H t ω

/-- The strict-past compensated integral uses only events before `t`; its
continuous compensator has no atom at `t`. -/
noncomputable def Model.prefixIntegral {Ω : Type*} [MeasurableSpace Ω]
    {μ : Measure Ω} (M : Model Ω μ) (H : ℝ → Ω → ℝ)
    (t : ℝ) (ω : Ω) : ℝ :=
  (∑ s ∈ (M.eventTimes ω).filter (fun s => s < t), H s ω) -
    M.energyIntegral H t ω

/-- The quadratic payoff evaluates the square of the predictable integrand
at each time and sample. -/
def Model.quadraticPayoff {Ω : Type*} [MeasurableSpace Ω]
    {μ : Measure Ω} (_M : Model Ω μ) (H : ℝ → Ω → ℝ) : ℝ → Ω → ℝ :=
  fun t ω => (H t ω) ^ 2

/-- The mixed payoff is twice the current integrand times the strictly past
compensated integral. It is the cross term in the pathwise square expansion. -/
noncomputable def Model.prefixPayoff {Ω : Type*} [MeasurableSpace Ω]
    {μ : Measure Ω} (M : Model Ω μ) (H : ℝ → Ω → ℝ) : ℝ → Ω → ℝ :=
  fun t ω => 2 * H t ω * M.prefixIntegral H t ω

/-- The law of `n` independent copies of one counting-process subject is the
product of the subject law. -/
noncomputable def Model.copyLaw {Ω : Type*} [MeasurableSpace Ω]
    {μ : Measure Ω} (_M : Model Ω μ) (n : ℕ) : Measure (Fin n → Ω) :=
  Measure.pi (fun _ : Fin n => μ)

/-- A subject-specific integral in a finite independent sample evaluates the
single-subject integral at that subject's coordinate. -/
noncomputable def Model.copyIntegral {Ω : Type*} [MeasurableSpace Ω]
    {μ : Measure Ω} (M : Model Ω μ) {n : ℕ}
    (H : Fin n → ℝ → Ω → ℝ) (i : Fin n) (x : Fin n → Ω) : ℝ :=
  M.stochasticIntegral (H i) M.horizon (x i)

end Causalean.Stat.RecurrentEvent.CountingProcess.FiniteJump
