module
public import Causalean.Stat.RecurrentEvent.CountingProcess.FiniteJump.Isometry
public import Causalean.Stat.RecurrentEvent.CountingProcess.Isometry

/-!
# Stopped finite recurrent-event subjects in a full iid sample

This is the specialization boundary for a finite-horizon recurrent-event model.
A subject supplies finitely many distinct unit jumps and an exit time. A concrete
model supplies the conditional-increment `Model` for each subject on the whole
sample, with a common history filtration. Integrands can use every coordinate.

The proof chain follows the public counting-process API: compensate predictable
payoffs, expand squares and cross products with strict-past prefixes, and sum
subject energies. The public one-event definitions have fixed failure/censor
sample types, so they cannot represent multiple jumps; they are imported for
the established API and proof conventions, without duplicating their model.
-/

@[expose] public section

open MeasureTheory Set

namespace Causalean.Stat.RecurrentEvent.CountingProcess.FiniteJump

/-- A subject carries finitely many positive, distinct recurrent-event times
and a measurable exit time. Every represented event has multiplicity one;
repeated unit events at distinct times are retained. Batch jumps are outside
this simple counting-process model, since their quadratic variation is the
square of the batch size rather than the batch size. -/
structure FiniteJumpSubject (Ω : Type*) [MeasurableSpace Ω] where
  jumpTimes : Ω → Finset ℝ
  exitTime : Ω → ℝ
  jumpTimes_measurable : Measurable jumpTimes
  exitTime_measurable : Measurable exitTime
  jump_positive : ∀ ω t, t ∈ jumpTimes ω → 0 < t

/-- Observed recurrent events occur within the horizon and strictly before
exit. Events at exit are assigned to exit, matching the public stopping rule. -/
noncomputable def FiniteJumpSubject.observedStoppedJumps
    {Ω : Type*} [MeasurableSpace Ω] (D : FiniteJumpSubject Ω)
    (T : ℝ) (ω : Ω) : Finset ℝ :=
  (D.jumpTimes ω).filter (fun t => t ≤ T ∧ t < D.exitTime ω)

/-- The finite sample law is the iid product of the subject law. -/
noncomputable def finiteSampleLaw {Ω : Type*} [MeasurableSpace Ω]
    (n : ℕ) (μ : Measure Ω) : Measure (Fin n → Ω) :=
  Measure.pi (fun _ : Fin n => μ)

/-- The iid product of a probability subject law is a probability law. -/
instance finiteSampleLaw_isProbability {Ω : Type*} [MeasurableSpace Ω]
    (n : ℕ) (μ : Measure Ω) [IsProbabilityMeasure μ] :
    IsProbabilityMeasure (finiteSampleLaw n μ) := by
  unfold finiteSampleLaw
  infer_instance

/-- A finite iid recurrent-event model supplies subject conditional intensities
on a common full-sample filtration. Its component `Model`s contain explicit
measurability, predictable nonnegative rates, count adaptedness, bounded rates,
count second moments, and the conditional increment premise. The consistency
fields identify stopped coordinate events and the density `Y_i * lambda_i`;
no moment equality or orthogonality is a field of this record. -/
structure SampleModel (n : ℕ) (Ω : Type*) [MeasurableSpace Ω] (μ : Measure Ω) where
  subject : FiniteJumpSubject Ω
  horizon : ℝ
  horizon_pos : 0 < horizon
  filtration : ℝ → MeasurableSpace (Fin n → Ω)
  intensity : ℝ → Ω → ℝ
  process : Fin n → Model (Fin n → Ω) (finiteSampleLaw n μ)
  process_horizon : ∀ i, (process i).horizon = horizon
  process_filtration : ∀ i, (process i).filtration = filtration
  process_events : ∀ i x, (process i).eventTimes x =
    subject.observedStoppedJumps horizon (x i)
  process_atRisk : ∀ i t x, (process i).atRisk t x =
    if 0 ≤ t ∧ t ≤ subject.exitTime (x i) then 1 else 0
  process_intensity : ∀ i t x, (process i).intensity t x = intensity t (x i)

variable {n : ℕ} {Ω : Type*} [MeasurableSpace Ω] {μ : Measure Ω}

/-- A full-sample integrand is left predictable when measurable for the
σ-algebra generated by observations available at the left endpoint of time
intervals. No restriction to the integrated subject's coordinate is imposed. -/
def SampleModel.LeftPredictable (S : SampleModel n Ω μ)
    (H : ℝ → (Fin n → Ω) → ℝ) : Prop :=
  Measurable[predictableSpace S.filtration] (fun p : ℝ × (Fin n → Ω) => H p.1 p.2)

/-- Common-filtration predictability is predictability for every subject's
conditional-intensity process on the full sample space. -/
theorem SampleModel.process_predictable (S : SampleModel n Ω μ)
    (H : ℝ → (Fin n → Ω) → ℝ) (hH : S.LeftPredictable H) (i : Fin n) :
    (S.process i).Predictable H := by
  unfold Model.Predictable
  rw [S.process_filtration i]
  exact hH

/-- A subject integral sums the full-sample predictable payoff over that
subject's stopped recurrent-event times, then subtracts its intensity integral. -/
noncomputable def SampleModel.subjectIntegral (S : SampleModel n Ω μ)
    (H : ℝ → (Fin n → Ω) → ℝ) (i : Fin n) (x : Fin n → Ω) : ℝ :=
  (S.process i).stochasticIntegral H (S.process i).horizon x

/-- The subject integral is exactly the payoff sum over observed stopped
recurrent events minus the absolutely continuous `Y_i * lambda_i` integral. -/
theorem SampleModel.subjectIntegral_eq_stopped (S : SampleModel n Ω μ)
    (H : ℝ → (Fin n → Ω) → ℝ) (i : Fin n) (x : Fin n → Ω) :
    S.subjectIntegral H i x =
      (∑ t ∈ S.subject.observedStoppedJumps S.horizon (x i), H t x) -
      ∫ t in Ioc 0 S.horizon, H t x *
        ((if 0 ≤ t ∧ t ≤ S.subject.exitTime (x i) then 1 else 0) *
          S.intensity t (x i)) ∂volume := by
  classical
  unfold SampleModel.subjectIntegral Model.stochasticIntegral
    Model.jumpIntegral Model.energyIntegral
  rw [S.process_horizon i, S.process_events i x]
  have hf : (S.subject.observedStoppedJumps S.horizon (x i)).filter
      (fun t => t ≤ S.horizon) = S.subject.observedStoppedJumps S.horizon (x i) :=
    Finset.filter_eq_self.mpr (fun t ht => (Finset.mem_filter.mp ht).2.1)
  simp_rw [hf, S.process_atRisk, S.process_intensity]

/-- The aggregate compensated integral is the finite sum of subject integrals. -/
noncomputable def SampleModel.aggregateIntegral (S : SampleModel n Ω μ)
    (H : ℝ → (Fin n → Ω) → ℝ) (x : Fin n → Ω) : ℝ :=
  ∑ i : Fin n, S.subjectIntegral H i x

/-- The subject quadratic energy integrates the squared full-sample payoff
against that subject's stopped at-risk intensity. -/
noncomputable def SampleModel.subjectEnergy (S : SampleModel n Ω μ)
    (H : ℝ → (Fin n → Ω) → ℝ) (i : Fin n) (x : Fin n → Ω) : ℝ :=
  (S.process i).energyIntegral (fun t x => (H t x) ^ 2) (S.process i).horizon x

/-- The aggregate predictable quadratic energy is the sum of subject energies. -/
noncomputable def SampleModel.predictableEnergy (S : SampleModel n Ω μ)
    (H : ℝ → (Fin n → Ω) → ℝ) (x : Fin n → Ω) : ℝ :=
  ∑ i : Fin n, S.subjectEnergy H i x

/-- Quadratic-energy finiteness means the nonnegative time-sample integral
of squared payoff times at-risk intensity is finite for every subject. -/
def SampleModel.QuadraticEnergyFinite (S : SampleModel n Ω μ)
    (H : ℝ → (Fin n → Ω) → ℝ) : Prop :=
  ∀ i : Fin n,
    (∫⁻ p : ℝ × (Fin n → Ω),
      ENNReal.ofReal ((H p.1 p.2) ^ 2 *
        ((S.process i).atRisk p.1 p.2 * (S.process i).intensity p.1 p.2))
      ∂((volume.restrict (Ioc 0 S.horizon)).prod (finiteSampleLaw n μ))) < ⊤

/-- A bounded left-predictable payoff on the full sample has equal expected
subject jump sum and subject compensator integral, derived from the component
conditional intensity/increment premise. -/
theorem SampleModel.predictable_compensation (S : SampleModel n Ω μ)
    [IsProbabilityMeasure μ] (H : ℝ → (Fin n → Ω) → ℝ)
    (hH : S.LeftPredictable H)
    (hbound : ∃ C : ℝ, ∀ t x, |H t x| ≤ C) (i : Fin n) :
    (∫ x, (S.process i).jumpIntegral H (S.process i).horizon x
      ∂finiteSampleLaw n μ) =
    ∫ x, (S.process i).energyIntegral H (S.process i).horizon x
      ∂finiteSampleLaw n μ := by
  have hp := S.process_predictable H hH i
  exact (S.process i).bounded_predictable_compensator H hp hbound

/-- Subject integrals are centered for a bounded full-sample predictable
payoff, by conditional-intensity compensation. -/
theorem SampleModel.subject_integral_centered (S : SampleModel n Ω μ)
    [IsProbabilityMeasure μ] (H : ℝ → (Fin n → Ω) → ℝ)
    (hH : S.LeftPredictable H)
    (hbound : ∃ C : ℝ, ∀ t x, |H t x| ≤ C) (i : Fin n) :
    (∫ x, S.subjectIntegral H i x ∂finiteSampleLaw n μ) = 0 := by
  exact (S.process i).stochasticIntegral_centered H (S.process_predictable H hH i) hbound

/-- A subject's second moment equals its expected quadratic energy for a
bounded predictable payoff depending on the entire finite sample. [The sample
model and payoff](hyp:S,H), [left predictability](hyp:hH), [boundedness](hyp:hbound),
and [the subject index](hyp:i) give [the subjectwise isometry](goal). -/
theorem SampleModel.subject_integral_isometry (S : SampleModel n Ω μ)
    [IsProbabilityMeasure μ] (H : ℝ → (Fin n → Ω) → ℝ)
    (hH : S.LeftPredictable H)
    (hbound : ∃ C : ℝ, ∀ t x, |H t x| ≤ C) (i : Fin n) :
    (∫ x, (S.subjectIntegral H i x) ^ 2 ∂finiteSampleLaw n μ) =
      ∫ x, S.subjectEnergy H i x ∂finiteSampleLaw n μ := by
  exact (S.process i).stochasticIntegral_isometry H (S.process_predictable H hH i) hbound

/-- Bounded full-sample predictable subject integrals have integrable squares;
this supplies actual Bochner integrability independently of a moment equality. -/
theorem SampleModel.subject_square_integrable (S : SampleModel n Ω μ)
    [IsProbabilityMeasure μ] (H : ℝ → (Fin n → Ω) → ℝ)
    (hH : S.LeftPredictable H)
    (hbound : ∃ C : ℝ, ∀ t x, |H t x| ≤ C) (i : Fin n) :
    Integrable (fun x => (S.subjectIntegral H i x) ^ 2) (finiteSampleLaw n μ) := by
  exact (S.process i).integrable_stochastic_square H (S.process_predictable H hH i) hbound

end Causalean.Stat.RecurrentEvent.CountingProcess.FiniteJump
