module
public import CausalSmith.Experimentation.EXP_DenseGroupPartitionProjectionPhase_Research.Basic
public import CausalSmith.Experimentation.EXP_DenseGroupPartitionProjectionPhase_Research.Helpers
public import CausalSmith.Experimentation.EXP_DenseGroupPartitionProjectionPhase_Research.TExactKneserIdentity
public import CausalSmith.Experimentation.EXP_DenseGroupPartitionProjectionPhase_Research.TExactPameVariance
public import CausalSmith.Experimentation.EXP_DenseGroupPartitionProjectionPhase_Research.TDenseProjectionLimit
public import CausalSmith.Experimentation.EXP_DenseGroupPartitionProjectionPhase_Research.TCr2PhaseFrontier
public import CausalSmith.Experimentation.EXP_DenseGroupPartitionProjectionPhase_Research.TSparseBeyondBirthday
public import CausalSmith.Experimentation.EXP_DenseGroupPartitionProjectionPhase_Research.TClubsandwichConsumer
public import CausalSmith.Experimentation.EXP_DenseGroupPartitionProjectionPhase_Research.TEightUnitWitness
public import CausalSmith.Experimentation.EXP_DenseGroupPartitionProjectionPhase_Research.TRademacherMixtureSeparation
public import CausalSmith.Experimentation.EXP_DenseGroupPartitionProjectionPhase_Research.TQvDiagonalImpossibility

/-! Public barrel for the dense group-partition projection-phase paper. -/

public section
