module
public import CausalSmith.Stat.STAT_MarNearcompleteFrontier_Research.Helpers.PairedPrior.Atoms
public import CausalSmith.Stat.STAT_MarNearcompleteFrontier_Research.Helpers.PairedPrior.Normalization
public import CausalSmith.Stat.STAT_MarNearcompleteFrontier_Research.Helpers.Identification

/-! # Normalized paired prior and count experiment -/

@[expose] public section
namespace CausalSmith.Stat.MarNearcompleteFrontier

open MeasureTheory ProbabilityTheory Polynomial
open scoped BigOperators ENNReal NNReal

/-- Full legal law generated by one latent vector and one prior sign. -/
noncomputable def pairedFullLaw (n d : ℕ) (q σ : ℝ)
    (hn : 1 ≤ n) (hd : 1 ≤ d) (hq : q ∈ Set.Icc ((1 : ℝ) / 2) 1)
    (hσ : σ ∈ Set.Icc (-1) 1) (θ : Theta n d) : FullLaw d :=
  ⟨PMF.ofFintype (fun w => ENNReal.ofReal (pairedAtomWeight n d q σ hd θ w))
    (pairedAtomWeight_sum n d q σ hn hd hq hσ θ)⟩

-- @node: pairedFullLaw_fullMass
/-- The normalized full-law mass is the displayed atom weight. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `hn`](hyp:hn), [the specified input `hd`](hyp:hd), [the specified input `w`](hyp:w), [the stated mathematical conclusion holds](goal). Given [the specified input `σ`](hyp:σ), [the specified input `θ`](hyp:θ). Given [the specified input `hq`](hyp:hq), [the specified input `hσ`](hyp:hσ). -/
lemma pairedFullLaw_fullMass (n d : ℕ) (q σ : ℝ)
    (hn : 1 ≤ n) (hd : 1 ≤ d) (hq : q ∈ Set.Icc ((1 : ℝ) / 2) 1)
    (hσ : σ ∈ Set.Icc (-1) 1) (θ : Theta n d) (w : FullAtom d) :
    fullMass (pairedFullLaw n d q σ hn hd hq hσ θ) w =
      pairedAtomWeight n d q σ hd θ w := by
  simp [fullMass, pairedFullLaw,
    pairedAtomWeight_nonneg n d q σ hn hd hq hσ θ w]

-- @node: pairedFullLaw_consistency
/-- All atoms inconsistent with the treatment-selected potential outcomes have zero mass. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `hn`](hyp:hn), [the specified input `hd`](hyp:hd), [the stated mathematical conclusion holds](goal). Given [the specified input `σ`](hyp:σ), [the specified input `θ`](hyp:θ). Given [the specified input `hq`](hyp:hq), [the specified input `hσ`](hyp:hσ). -/
lemma pairedFullLaw_consistency (n d : ℕ) (q σ : ℝ)
    (hn : 1 ≤ n) (hd : 1 ≤ d) (hq : q ∈ Set.Icc ((1 : ℝ) / 2) 1)
    (hσ : σ ∈ Set.Icc (-1) 1) (θ : Theta n d) :
    Consistency (pairedFullLaw n d q σ hn hd hq hσ θ) := by
  intro w hw
  rw [pairedFullLaw_fullMass]
  have hbad (h0 : w.S0 = false) (h1 : w.S1 = false)
      (hs : w.S = false)
      (hy : w.Y = (if w.A then w.Y1 else w.Y0)) : False := by
    rcases hw with h | h
    · exact h (by simp [h0, h1, hs])
    · exact h hy
  unfold pairedAtomWeight
  have hf : fillerAtomWeight n d q hd θ w = 0 := by
    have hc : ¬(w.X = fillerLabel d hd ∧ w.S0 = false ∧ w.S1 = false ∧
        w.S = false ∧ w.Y0 = false ∧
        w.Y = (if w.A then w.Y1 else w.Y0) ∧ w.R = true) := by
      rintro ⟨_, h0, h1, hs, _, hy, _⟩
      exact hbad h0 h1 hs hy
    simp only [fillerAtomWeight, if_neg hc]
  rw [hf, zero_add]
  apply Finset.sum_eq_zero
  intro j _
  apply Finset.sum_eq_zero
  intro side _
  have hc : ¬(w.X = pairLabel n d hd j side ∧ w.S0 = false ∧
      w.S1 = false ∧ w.S = false ∧ w.Y0 = false ∧
      w.Y = (if w.A then w.Y1 else w.Y0)) := by
    rintro ⟨_, h0, h1, hs, _, hy⟩
    exact hbad h0 h1 hs hy
  simp only [pairAtomWeight, if_neg hc]

-- @node: pairedFullLaw_controlOutcome_zero
/-- The constructed control potential outcome is identically zero. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `hn`](hyp:hn), [the specified input `hd`](hyp:hd), [the specified input `w`](hyp:w), [the specified input `hy`](hyp:hy), [the stated mathematical conclusion holds](goal). Given [the specified input `σ`](hyp:σ), [the specified input `θ`](hyp:θ). Given [the specified input `hq`](hyp:hq), [the specified input `hσ`](hyp:hσ). -/
lemma pairedFullLaw_controlOutcome_zero (n d : ℕ) (q σ : ℝ)
    (hn : 1 ≤ n) (hd : 1 ≤ d) (hq : q ∈ Set.Icc ((1 : ℝ) / 2) 1)
    (hσ : σ ∈ Set.Icc (-1) 1) (θ : Theta n d) (w : FullAtom d)
    (hy : w.Y0 = true) :
    fullMass (pairedFullLaw n d q σ hn hd hq hσ θ) w = 0 := by
  rw [pairedFullLaw_fullMass]
  simp [pairedAtomWeight, fillerAtomWeight, pairAtomWeight, hy]

-- @node: pairedFullLaw_balanced
/-- Treatment remains a fair coin after the random cell masses are normalized. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `hn`](hyp:hn), [the specified input `hd`](hyp:hd), [the stated mathematical conclusion holds](goal). Given [the specified input `σ`](hyp:σ), [the specified input `θ`](hyp:θ). Given [the specified input `hq`](hyp:hq), [the specified input `hσ`](hyp:hσ). -/
lemma pairedFullLaw_balanced (n d : ℕ) (q σ : ℝ)
    (hn : 1 ≤ n) (hd : 1 ≤ d) (hq : q ∈ Set.Icc ((1 : ℝ) / 2) 1)
    (hσ : σ ∈ Set.Icc (-1) 1) (θ : Theta n d) :
    BalancedRandomization (pairedFullLaw n d q σ hn hd hq hσ θ) := by
  unfold BalancedRandomization armMass massOf
  simp_rw [pairedFullLaw_fullMass]
  calc
    (∑ w : FullAtom d, if w.A = true then pairedAtomWeight n d q σ hd θ w else 0) =
        (∑ w : FullAtom d, if w.A = true then fillerAtomWeight n d q hd θ w else 0) +
        ∑ j : Fin (pairCount n d), ∑ side : Bool,
          ∑ w : FullAtom d, if w.A = true then
            pairAtomWeight n d q σ hd θ j side w else 0 := by
              calc
                _ = ∑ w : FullAtom d,
                    ((if w.A = true then fillerAtomWeight n d q hd θ w else 0) +
                      (∑ j : Fin (pairCount n d), ∑ side : Bool,
                        if w.A = true then pairAtomWeight n d q σ hd θ j side w else 0)) := by
                          apply Finset.sum_congr rfl
                          intro w _
                          by_cases hw : w.A = true <;> simp [pairedAtomWeight, hw]
                _ = _ := by
                  rw [Finset.sum_add_distrib]
                  congr 1
                  rw [Finset.sum_comm]
                  apply Finset.sum_congr rfl
                  intro j _
                  rw [Finset.sum_comm]
    _ = fillerMass n d / normalizationJ n d θ / 2 +
        ∑ j : Fin (pairCount n d), ∑ side : Bool,
          latentP n (θ.1 j) / normalizationJ n d θ / 2 := by
            rw [sum_fillerAtomWeight_arm]
            simp_rw [sum_pairAtomWeight_arm]
    _ = 1 / 2 := by
      have hJ : normalizationJ n d θ ≠ 0 :=
        ne_of_gt (normalizationJ_pos n d q hn hd hq θ)
      simp_rw [Fintype.sum_bool]
      have hsum : (∑ j : Fin (pairCount n d),
          (latentP n (θ.1 j) / normalizationJ n d θ / 2 +
           latentP n (θ.1 j) / normalizationJ n d θ / 2)) =
          (2 * ∑ j : Fin (pairCount n d), latentP n (θ.1 j)) /
            normalizationJ n d θ / 2 := by
        rw [Finset.sum_add_distrib, ← Finset.sum_div, ← Finset.sum_div]
        ring
      rw [hsum]
      calc
        _ = (fillerMass n d + 2 * ∑ j : Fin (pairCount n d),
            latentP n (θ.1 j)) / normalizationJ n d θ / 2 := by ring
        _ = 1 / 2 := by
          change normalizationJ n d θ / normalizationJ n d θ / 2 = 1 / 2
          rw [div_self hJ]

-- @node: fillerAtomWeight_arm_potential_symmetry
/-- At fixed potential outcomes, the filler weight is equal in both arms. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `hd`](hyp:hd), [the specified input `v`](hyp:v), [the specified input `a`](hyp:a), [the stated mathematical conclusion holds](goal). Given [the specified input `θ`](hyp:θ). -/
lemma fillerAtomWeight_arm_potential_symmetry (n d : ℕ) (q : ℝ)
    (hd : 1 ≤ d) (θ : Theta n d) (v : PotentialAtom d) (a : Bool) :
    (∑ w : FullAtom d, if w.A = a ∧ w.potential = v then
      fillerAtomWeight n d q hd θ w else 0) =
    (∑ w : FullAtom d, if w.A = !a ∧ w.potential = v then
      fillerAtomWeight n d q hd θ w else 0) := by
  rw [Fintype.sum_equiv (fullAtomTupleEquiv d)
    (fun w => if w.A = a ∧ w.potential = v then fillerAtomWeight n d q hd θ w else 0)
    (fun t => if ((fullAtomTupleEquiv d).symm t).A = a ∧
      ((fullAtomTupleEquiv d).symm t).potential = v then
      fillerAtomWeight n d q hd θ ((fullAtomTupleEquiv d).symm t) else 0)
    (by intro w; simp)]
  rw [Fintype.sum_equiv (fullAtomTupleEquiv d)
    (fun w => if w.A = !a ∧ w.potential = v then fillerAtomWeight n d q hd θ w else 0)
    (fun t => if ((fullAtomTupleEquiv d).symm t).A = !a ∧
      ((fullAtomTupleEquiv d).symm t).potential = v then
      fillerAtomWeight n d q hd θ ((fullAtomTupleEquiv d).symm t) else 0)
    (by intro w; simp)]
  simp only [Fintype.sum_prod_type]
  cases a <;> cases v with
  | mk x s0 s1 y0 y1 =>
      simp [fullAtomTupleEquiv, fillerAtomWeight, bernoulliFactor,
        fillerLabel, FullAtom.X]

-- @node: pairAtomWeight_arm_potential_symmetry
/-- At fixed potential outcomes, an oriented pair weight is equal in both arms. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `hd`](hyp:hd), [the specified input `side`](hyp:side), [the specified input `v`](hyp:v), [the specified input `a`](hyp:a), [the stated mathematical conclusion holds](goal). Given [the specified input `σ`](hyp:σ), [the specified input `θ`](hyp:θ). Given [the specified input `j`](hyp:j). -/
lemma pairAtomWeight_arm_potential_symmetry (n d : ℕ) (q σ : ℝ)
    (hd : 1 ≤ d) (θ : Theta n d) (j : Fin (pairCount n d))
    (side : Bool) (v : PotentialAtom d) (a : Bool) :
    (∑ w : FullAtom d, if w.A = a ∧ w.potential = v then
      pairAtomWeight n d q σ hd θ j side w else 0) =
    (∑ w : FullAtom d, if w.A = !a ∧ w.potential = v then
      pairAtomWeight n d q σ hd θ j side w else 0) := by
  rw [Fintype.sum_equiv (fullAtomTupleEquiv d)
    (fun w => if w.A = a ∧ w.potential = v then
      pairAtomWeight n d q σ hd θ j side w else 0)
    (fun t => if ((fullAtomTupleEquiv d).symm t).A = a ∧
      ((fullAtomTupleEquiv d).symm t).potential = v then
      pairAtomWeight n d q σ hd θ j side ((fullAtomTupleEquiv d).symm t) else 0)
    (by intro w; simp)]
  rw [Fintype.sum_equiv (fullAtomTupleEquiv d)
    (fun w => if w.A = !a ∧ w.potential = v then
      pairAtomWeight n d q σ hd θ j side w else 0)
    (fun t => if ((fullAtomTupleEquiv d).symm t).A = !a ∧
      ((fullAtomTupleEquiv d).symm t).potential = v then
      pairAtomWeight n d q σ hd θ j side ((fullAtomTupleEquiv d).symm t) else 0)
    (by intro w; simp)]
  simp only [Fintype.sum_prod_type]
  cases a <;> cases v with
  | mk x s0 s1 y0 y1 =>
      simp [fullAtomTupleEquiv, pairAtomWeight, bernoulliFactor,
        FullAtom.X, FullAtom.S0, FullAtom.S1, FullAtom.Y0, FullAtom.Y1]
      apply Finset.sum_congr rfl
      intro x _
      split_ifs <;> ring

-- @node: pairedFullLaw_arm_potential_symmetry
/-- The complete constructed law has equal arm masses at each potential atom. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `hn`](hyp:hn), [the specified input `hd`](hyp:hd), [the specified input `v`](hyp:v), [the specified input `a`](hyp:a), [the stated mathematical conclusion holds](goal). Given [the specified input `σ`](hyp:σ), [the specified input `θ`](hyp:θ). Given [the specified input `hq`](hyp:hq), [the specified input `hσ`](hyp:hσ). -/
lemma pairedFullLaw_arm_potential_symmetry (n d : ℕ) (q σ : ℝ)
    (hn : 1 ≤ n) (hd : 1 ≤ d) (hq : q ∈ Set.Icc ((1 : ℝ) / 2) 1)
    (hσ : σ ∈ Set.Icc (-1) 1) (θ : Theta n d)
    (v : PotentialAtom d) (a : Bool) :
    massOf (pairedFullLaw n d q σ hn hd hq hσ θ)
      (fun w => w.A = a ∧ w.potential = v) =
    massOf (pairedFullLaw n d q σ hn hd hq hσ θ)
      (fun w => w.A = !a ∧ w.potential = v) := by
  simp only [massOf, pairedFullLaw_fullMass]
  have hsplit (b : Bool) :
      (∑ w : FullAtom d, if w.A = b ∧ w.potential = v then
        pairedAtomWeight n d q σ hd θ w else 0) =
      (∑ w : FullAtom d, if w.A = b ∧ w.potential = v then
        fillerAtomWeight n d q hd θ w else 0) +
      ∑ j : Fin (pairCount n d), ∑ side : Bool,
        ∑ w : FullAtom d, if w.A = b ∧ w.potential = v then
          pairAtomWeight n d q σ hd θ j side w else 0 := by
    calc
      _ = ∑ w : FullAtom d,
          ((if w.A = b ∧ w.potential = v then
            fillerAtomWeight n d q hd θ w else 0) +
          ∑ j : Fin (pairCount n d), ∑ side : Bool,
            if w.A = b ∧ w.potential = v then
              pairAtomWeight n d q σ hd θ j side w else 0) := by
                apply Finset.sum_congr rfl
                intro w _
                by_cases h : w.A = b ∧ w.potential = v
                · simp [h, pairedAtomWeight]
                · simp [h]
      _ = _ := by
        rw [Finset.sum_add_distrib, Finset.sum_comm]
        congr 1
        apply Finset.sum_congr rfl
        intro j _
        rw [Finset.sum_comm]
  rw [hsplit a, hsplit (!a), fillerAtomWeight_arm_potential_symmetry]
  congr 1
  apply Finset.sum_congr rfl
  intro j _
  apply Finset.sum_congr rfl
  intro side _
  exact pairAtomWeight_arm_potential_symmetry n d q σ hd θ j side v a

-- @node: pairedFullLaw_randomized
/-- The normalized construction is randomized independently of all potential coordinates. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `hn`](hyp:hn), [the specified input `hd`](hyp:hd), [the stated mathematical conclusion holds](goal). Given [the specified input `σ`](hyp:σ), [the specified input `θ`](hyp:θ). Given [the specified input `hq`](hyp:hq), [the specified input `hσ`](hyp:hσ). -/
lemma pairedFullLaw_randomized (n d : ℕ) (q σ : ℝ)
    (hn : 1 ≤ n) (hd : 1 ≤ d) (hq : q ∈ Set.Icc ((1 : ℝ) / 2) 1)
    (hσ : σ ∈ Set.Icc (-1) 1) (θ : Theta n d) :
    RandomizedIndependence (pairedFullLaw n d q σ hn hd hq hσ θ) := by
  let P := pairedFullLaw n d q σ hn hd hq hσ θ
  intro a x s0 s1 y0 y1
  let v : PotentialAtom d := ⟨x, s0, s1, y0, y1⟩
  have hp (w : FullAtom d) :
      (w.X = x ∧ w.S0 = s0 ∧ w.S1 = s1 ∧ w.Y0 = y0 ∧ w.Y1 = y1) ↔
        w.potential = v := by
    cases w with
    | mk p A S Y R =>
        cases p
        simp [v, FullAtom.X, FullAtom.S0, FullAtom.S1, FullAtom.Y0,
          FullAtom.Y1, PotentialAtom.mk.injEq]
  simp only [hp]
  change massOf P (fun w => w.A = a ∧ w.potential = v) =
    armMass P a * massOf P (fun w => w.potential = v)
  have hhalf : armMass P a = 1 / 2 := by
    cases a
    · exact armMass_false_eq_half P
        (pairedFullLaw_balanced n d q σ hn hd hq hσ θ)
    · exact pairedFullLaw_balanced n d q σ hn hd hq hσ θ
  have hpartition : massOf P (fun w => w.potential = v) =
      massOf P (fun w => w.A = a ∧ w.potential = v) +
      massOf P (fun w => w.A = !a ∧ w.potential = v) := by
    unfold massOf
    rw [← Finset.sum_add_distrib]
    apply Finset.sum_congr rfl
    intro w _
    cases w with
    | mk p aw s y r =>
        cases a <;> cases aw <;> simp
  have hsym := pairedFullLaw_arm_potential_symmetry
    n d q σ hn hd hq hσ θ v a
  rw [hhalf]
  linarith

-- @node: pairAtomWeight_arrival_floor_pointwise
/-- At a fixed oriented label and fixed nonarrival coordinates, the arrived
atom carries at least the fraction `q` of the two arrival possibilities. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `hn`](hyp:hn), [the specified input `hd`](hyp:hd), [the specified input `side`](hyp:side), [the specified input `v`](hyp:v), [the specified input `a`](hyp:a), [the specified input `s`](hyp:s), [the specified input `y`](hyp:y), [the stated mathematical conclusion holds](goal). Given [the specified input `σ`](hyp:σ), [the specified input `θ`](hyp:θ). Given [the specified input `hq`](hyp:hq), [the specified input `hσ`](hyp:hσ), [the specified input `j`](hyp:j). -/
lemma pairAtomWeight_arrival_floor_pointwise (n d : ℕ) (q σ : ℝ)
    (hn : 1 ≤ n) (hd : 1 ≤ d) (hq : q ∈ Set.Icc ((1 : ℝ) / 2) 1)
    (hσ : σ ∈ Set.Icc (-1) 1) (θ : Theta n d)
    (j : Fin (pairCount n d)) (side : Bool) (v : PotentialAtom d)
    (a s y : Bool) :
    q * (pairAtomWeight n d q σ hd θ j side ⟨v, a, s, y, true⟩ +
      pairAtomWeight n d q σ hd θ j side ⟨v, a, s, y, false⟩) ≤
      pairAtomWeight n d q σ hd θ j side ⟨v, a, s, y, true⟩ := by
  let w : FullAtom d := ⟨v, a, s, y, true⟩
  let w' : FullAtom d := ⟨v, a, s, y, false⟩
  have hρ := pairRho_mem_unit q σ (latentZ n (θ.1 j))
    (orientation θ j side) hq (pair_sign_mem_unit n d σ hσ θ j side)
  have hJ := normalizationJ_pos n d q hn hd hq θ
  have hp : 0 ≤ latentP n (θ.1 j) / normalizationJ n d θ / 2 *
      bernoulliFactor (pairMu q σ (latentZ n (θ.1 j))
        (orientation θ j side)) v.Y1 := by
    exact mul_nonneg
      (div_nonneg (div_nonneg (latentP_nonneg n (θ.1 j)) (le_of_lt hJ))
        (by norm_num))
      (bernoulliFactor_nonneg _
        (pairMu_mem_unit q σ (latentZ n (θ.1 j)) (orientation θ j side)
          hq (abs_le.mp (by rw [orientation_abs_one]))
          (pair_sign_mem_unit n d σ hσ θ j side)) _)
  by_cases hsupp : v.X = pairLabel n d hd j side ∧ v.S0 = false ∧
      v.S1 = false ∧ s = false ∧ v.Y0 = false ∧
      y = (if a then v.Y1 else v.Y0)
  · simp only [pairAtomWeight, if_pos hsupp]
    cases a
    · simp only [Bool.false_eq_true, ↓reduceIte, mul_one, mul_zero,
        add_zero, ge_iff_le]
      exact mul_le_of_le_one_left hp hq.2
    · cases hY : v.Y1 <;>
        simp [FullAtom.Y1, bernoulliFactor, hY] at hp ⊢ <;>
        nlinarith [mul_nonneg hp (sub_nonneg.mpr hρ.1)]
  · simp [pairAtomWeight, hsupp]

-- @node: fillerAtomWeight_arrival_floor_pointwise
/-- All filler mass has an arrived outcome. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `hn`](hyp:hn), [the specified input `hd`](hyp:hd), [the specified input `v`](hyp:v), [the specified input `a`](hyp:a), [the specified input `s`](hyp:s), [the specified input `y`](hyp:y), [the stated mathematical conclusion holds](goal). Given [the specified input `θ`](hyp:θ). Given [the specified input `hq`](hyp:hq). -/
lemma fillerAtomWeight_arrival_floor_pointwise (n d : ℕ) (q : ℝ)
    (hn : 1 ≤ n) (hd : 1 ≤ d) (hq : q ∈ Set.Icc ((1 : ℝ) / 2) 1)
    (θ : Theta n d) (v : PotentialAtom d) (a s y : Bool) :
    q * (fillerAtomWeight n d q hd θ ⟨v, a, s, y, true⟩ +
      fillerAtomWeight n d q hd θ ⟨v, a, s, y, false⟩) ≤
      fillerAtomWeight n d q hd θ ⟨v, a, s, y, true⟩ := by
  have hfalse : fillerAtomWeight n d q hd θ ⟨v, a, s, y, false⟩ = 0 := by
    simp [fillerAtomWeight]
  rw [hfalse, add_zero]
  exact mul_le_of_le_one_left
    (fillerAtomWeight_nonneg n d q hn hd hq θ ⟨v, a, s, y, true⟩) hq.2

-- @node: pairedAtomWeight_arrival_floor_pointwise
/-- The normalized atom weights retain the arrival floor after summing labels. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `hn`](hyp:hn), [the specified input `hd`](hyp:hd), [the specified input `v`](hyp:v), [the specified input `a`](hyp:a), [the specified input `s`](hyp:s), [the specified input `y`](hyp:y), [the stated mathematical conclusion holds](goal). Given [the specified input `σ`](hyp:σ), [the specified input `θ`](hyp:θ). Given [the specified input `hq`](hyp:hq), [the specified input `hσ`](hyp:hσ). -/
lemma pairedAtomWeight_arrival_floor_pointwise (n d : ℕ) (q σ : ℝ)
    (hn : 1 ≤ n) (hd : 1 ≤ d) (hq : q ∈ Set.Icc ((1 : ℝ) / 2) 1)
    (hσ : σ ∈ Set.Icc (-1) 1) (θ : Theta n d)
    (v : PotentialAtom d) (a s y : Bool) :
    q * (pairedAtomWeight n d q σ hd θ ⟨v, a, s, y, true⟩ +
      pairedAtomWeight n d q σ hd θ ⟨v, a, s, y, false⟩) ≤
      pairedAtomWeight n d q σ hd θ ⟨v, a, s, y, true⟩ := by
  simp only [pairedAtomWeight]
  have hf := fillerAtomWeight_arrival_floor_pointwise n d q hn hd hq θ v a s y
  have hp (j : Fin (pairCount n d)) (side : Bool) :=
    pairAtomWeight_arrival_floor_pointwise n d q σ hn hd hq hσ θ j side v a s y
  calc
    _ = q * (fillerAtomWeight n d q hd θ ⟨v, a, s, y, true⟩ +
        fillerAtomWeight n d q hd θ ⟨v, a, s, y, false⟩) +
        ∑ j : Fin (pairCount n d), ∑ side : Bool,
          q * (pairAtomWeight n d q σ hd θ j side ⟨v, a, s, y, true⟩ +
            pairAtomWeight n d q σ hd θ j side ⟨v, a, s, y, false⟩) := by
          simp only [mul_add, Finset.sum_add_distrib, Finset.mul_sum]
          ring
    _ ≤ _ := by
      apply add_le_add hf
      apply Finset.sum_le_sum
      intro j _
      apply Finset.sum_le_sum
      intro side _
      exact hp j side

-- @node: fullAtomArrivalEquiv
/-- Coordinates arranged with arrival last, for finite-sum calculations. Given [the specified input `d`](hyp:d), [the stated mathematical conclusion holds](goal). -/
def fullAtomArrivalEquiv (d : ℕ) :
    FullAtom d ≃ PotentialAtom d × Bool × Bool × Bool × Bool where
  toFun w := (w.potential, w.A, w.S, w.Y, w.R)
  invFun t := ⟨t.1, t.2.1, t.2.2.1, t.2.2.2.1, t.2.2.2.2⟩
  left_inv := by intro w; cases w; rfl
  right_inv := by intro t; rcases t with ⟨v, a, s, y, r⟩; rfl

-- @node: fullAtom_sum_by_arrival
/-- Rewrite a full-atom sum as nested sums, with arrival the innermost bit. Given [the specified input `d`](hyp:d), [the specified input `f`](hyp:f), [the stated mathematical conclusion holds](goal). -/
lemma fullAtom_sum_by_arrival {d : ℕ} (f : FullAtom d → ℝ) :
    (∑ w : FullAtom d, f w) =
      ∑ v : PotentialAtom d, ∑ a : Bool, ∑ s : Bool,
        ∑ y : Bool, ∑ r : Bool, f ⟨v, a, s, y, r⟩ := by
  rw [Fintype.sum_equiv (fullAtomArrivalEquiv d) f
    (fun t => f ((fullAtomArrivalEquiv d).symm t)) (by intro w; rfl)]
  simp only [Fintype.sum_prod_type, fullAtomArrivalEquiv]
  rfl

-- @node: pairedFullLaw_floor
/-- The pointwise arrival inequality gives the conditional arrival floor. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `hn`](hyp:hn), [the specified input `hd`](hyp:hd), [the stated mathematical conclusion holds](goal). Given [the specified input `σ`](hyp:σ), [the specified input `θ`](hyp:θ). Given [the specified input `hq`](hyp:hq), [the specified input `hσ`](hyp:hσ). -/
lemma pairedFullLaw_floor (n d : ℕ) (q σ : ℝ)
    (hn : 1 ≤ n) (hd : 1 ≤ d) (hq : q ∈ Set.Icc ((1 : ℝ) / 2) 1)
    (hσ : σ ∈ Set.Icc (-1) 1) (θ : Theta n d) :
    ArrivalFloor q (pairedFullLaw n d q σ hn hd hq hσ θ) := by
  intro x a s hc
  unfold arrivalProb
  apply (le_div_iff₀ hc).mpr
  unfold cellMass massOf
  rw [fullAtom_sum_by_arrival, fullAtom_sum_by_arrival]
  simp only [Finset.mul_sum]
  apply Finset.sum_le_sum
  intro v _
  apply Finset.sum_le_sum
  intro a' _
  apply Finset.sum_le_sum
  intro s' _
  apply Finset.sum_le_sum
  intro y _
  simp only [Fintype.sum_bool]
  by_cases h : v.X = x ∧ a' = a ∧ s' = s
  · rcases h with ⟨hv, ha, hs⟩
    subst a'
    subst s'
    simpa [FullAtom.X, hv, pairedFullLaw_fullMass, mul_add, add_comm] using
      (pairedAtomWeight_arrival_floor_pointwise n d q σ hn hd hq hσ θ v a s y)
  · simp [h]

-- @node: mar_of_cellwise_arrival_factor
/-- If [each observed cell has an arrival factor depending only on the observed record](hyp:h), [the full-data law satisfies missing at random](goal). -/
lemma mar_of_cellwise_arrival_factor {d : ℕ} (P : FullLaw d)
    (h : ∀ (x : Fin d) (a s : Bool), ∃ f : Bool → ℝ,
      ∀ (v : PotentialAtom d) (y r : Bool), v.X = x →
        fullMass P ⟨v, a, s, y, r⟩ =
          f r * ∑ t : Bool, fullMass P ⟨v, a, s, y, t⟩) :
    MissingAtRandom P := by
  classical
  intro x a s r y
  obtain ⟨f, hf⟩ := h x a s
  have joint (r y : Bool) :
      massOf P (fun w => w.X = x ∧ w.A = a ∧ w.S = s ∧ w.R = r ∧ w.Y = y) =
        f r * massOf P (fun w => w.X = x ∧ w.A = a ∧ w.S = s ∧ w.Y = y) := by
    unfold massOf
    rw [fullAtom_sum_by_arrival, fullAtom_sum_by_arrival]
    simp only [Finset.mul_sum]
    apply Finset.sum_congr rfl
    intro v _
    by_cases hx : v.X = x
    · cases a <;> cases s <;> cases r <;> cases y <;>
        simp [FullAtom.X, hx] <;>
        simpa only [Fintype.sum_bool, mul_add] using (hf v _ _ hx)
    · simp [FullAtom.X, hx]
  have marginal (r : Bool) :
      massOf P (fun w => w.X = x ∧ w.A = a ∧ w.S = s ∧ w.R = r) =
        f r * cellMass P x a s := by
    unfold cellMass massOf
    rw [fullAtom_sum_by_arrival, fullAtom_sum_by_arrival]
    simp only [Finset.mul_sum]
    apply Finset.sum_congr rfl
    intro v _
    by_cases hx : v.X = x
    · cases a <;> cases s <;> cases r <;>
        simp [FullAtom.X, hx] <;>
        simp only [Fintype.sum_bool, mul_add] at hf <;>
        linear_combination (hf v true _ hx) + (hf v false _ hx)
    · simp [FullAtom.X, hx]
  rw [joint, marginal]
  ring

-- @node: pairAtomWeight_arrival_factor
/-- One oriented pair has an arrival factor independent of its outcome bit. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `hd`](hyp:hd), [the specified input `side`](hyp:side), [the specified input `v`](hyp:v), [the specified input `a`](hyp:a), [the specified input `s`](hyp:s), [the specified input `y`](hyp:y), [the specified input `r`](hyp:r), [the stated mathematical conclusion holds](goal). Given [the specified input `σ`](hyp:σ), [the specified input `θ`](hyp:θ). Given [the specified input `j`](hyp:j). -/
lemma pairAtomWeight_arrival_factor (n d : ℕ) (q σ : ℝ) (hd : 1 ≤ d)
    (θ : Theta n d) (j : Fin (pairCount n d)) (side : Bool)
    (v : PotentialAtom d) (a s y r : Bool) :
    pairAtomWeight n d q σ hd θ j side ⟨v, a, s, y, r⟩ =
      (if a then bernoulliFactor
          (pairRho q σ (latentZ n (θ.1 j)) (orientation θ j side)) r
        else if r then 1 else 0) *
      ∑ t : Bool, pairAtomWeight n d q σ hd θ j side ⟨v, a, s, y, t⟩ := by
  by_cases hsupp : v.X = pairLabel n d hd j side ∧ v.S0 = false ∧
      v.S1 = false ∧ s = false ∧ v.Y0 = false ∧
      y = (if a then v.Y1 else v.Y0)
  · simp only [pairAtomWeight, if_pos hsupp]
    cases a <;> cases r <;> cases hY : v.Y1 <;>
      simp [bernoulliFactor, FullAtom.Y1, hY] <;> ring
  · simp [pairAtomWeight, hsupp]

-- @node: fillerAtomWeight_arrival_factor
/-- The filler component always arrives, independently of its outcome bit. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `hd`](hyp:hd), [the specified input `v`](hyp:v), [the specified input `a`](hyp:a), [the specified input `s`](hyp:s), [the specified input `y`](hyp:y), [the specified input `r`](hyp:r), [the stated mathematical conclusion holds](goal). Given [the specified input `θ`](hyp:θ). -/
lemma fillerAtomWeight_arrival_factor (n d : ℕ) (q : ℝ) (hd : 1 ≤ d)
    (θ : Theta n d) (v : PotentialAtom d) (a s y r : Bool) :
    fillerAtomWeight n d q hd θ ⟨v, a, s, y, r⟩ =
      (if r then (1 : ℝ) else 0) *
        ∑ t : Bool, fillerAtomWeight n d q hd θ ⟨v, a, s, y, t⟩ := by
  cases r <;> simp [fillerAtomWeight]

-- @node: pairedAtomWeight_at_filler
/-- Only the filler component contributes at the filler label. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `hd`](hyp:hd), [the specified input `w`](hyp:w), [the specified input `hw`](hyp:hw), [the stated mathematical conclusion holds](goal). Given [the specified input `σ`](hyp:σ), [the specified input `θ`](hyp:θ). -/
lemma pairedAtomWeight_at_filler (n d : ℕ) (q σ : ℝ) (hd : 1 ≤ d)
    (θ : Theta n d) (w : FullAtom d)
    (hw : w.X = fillerLabel d hd) :
    pairedAtomWeight n d q σ hd θ w = fillerAtomWeight n d q hd θ w := by
  simp [pairedAtomWeight, pairAtomWeight_filler_zero n d q σ hd θ _ _ w hw]

-- @node: pairedAtomWeight_at_pair
/-- Only its own oriented component contributes at a paired label. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `hd`](hyp:hd), [the specified input `side`](hyp:side), [the specified input `w`](hyp:w), [the specified input `hw`](hyp:hw), [the stated mathematical conclusion holds](goal). Given [the specified input `σ`](hyp:σ), [the specified input `θ`](hyp:θ). Given [the specified input `j`](hyp:j). -/
lemma pairedAtomWeight_at_pair (n d : ℕ) (q σ : ℝ) (hd : 1 ≤ d)
    (θ : Theta n d) (j : Fin (pairCount n d)) (side : Bool)
    (w : FullAtom d) (hw : w.X = pairLabel n d hd j side) :
    pairedAtomWeight n d q σ hd θ w =
      pairAtomWeight n d q σ hd θ j side w := by
  unfold pairedAtomWeight
  rw [fillerAtomWeight_pair_zero n d q hd θ j side w hw, zero_add]
  calc
    (∑ k : Fin (pairCount n d), ∑ side' : Bool,
        pairAtomWeight n d q σ hd θ k side' w) =
        ∑ side' : Bool, pairAtomWeight n d q σ hd θ j side' w := by
          apply Finset.sum_eq_single j
          · intro k _ hne
            apply Finset.sum_eq_zero
            intro side' _
            exact pairAtomWeight_other_pair_zero n d q σ hd θ k j side' side w hw
              (Or.inl hne)
          · simp
    _ = pairAtomWeight n d q σ hd θ j side w := by
          apply Finset.sum_eq_single side
          · intro side' _ hne
            exact pairAtomWeight_other_pair_zero n d q σ hd θ j j side' side w hw
              (Or.inr hne)
          · simp

/-- For [a sample size of at least one](hyp:hn), [a positive dimension](hyp:hd), [an admissible arrival floor](hyp:hq), [an admissible sign](hyp:hσ), and [a latent configuration](hyp:θ), [the paired construction is a legal law in the model class](goal). -/
lemma pairedFullLaw_legal (n d : ℕ) (q σ : ℝ)
    (hn : 1 ≤ n) (hd : 1 ≤ d) (hq : q ∈ Set.Icc ((1 : ℝ) / 2) 1)
    (hσ : σ ∈ Set.Icc (-1) 1) (θ : Theta n d) :
    LawClass d q (pairedFullLaw n d q σ hn hd hq hσ θ) := by
  refine ⟨pairedFullLaw_randomized n d q σ hn hd hq hσ θ,
    pairedFullLaw_balanced n d q σ hn hd hq hσ θ,
    pairedFullLaw_consistency n d q σ hn hd hq hσ θ,
    ?_, pairedFullLaw_floor n d q σ hn hd hq hσ θ⟩
  apply mar_of_cellwise_arrival_factor
  intro x a s
  by_cases hxF : x = fillerLabel d hd
  · refine ⟨fun r => if r then 1 else 0, ?_⟩
    intro v y r hv
    have hlabel : v.X = fillerLabel d hd := hv.trans hxF
    simp only [pairedFullLaw_fullMass]
    have hl (t : Bool) : pairedAtomWeight n d q σ hd θ ⟨v, a, s, y, t⟩ =
        fillerAtomWeight n d q hd θ ⟨v, a, s, y, t⟩ :=
      pairedAtomWeight_at_filler n d q σ hd θ ⟨v, a, s, y, t⟩ hlabel
    simp_rw [hl]
    exact fillerAtomWeight_arrival_factor n d q hd θ v a s y r
  by_cases hxP : ∃ (j : Fin (pairCount n d)) (side : Bool),
      x = pairLabel n d hd j side
  · obtain ⟨j, side, hx⟩ := hxP
    refine ⟨fun r => if a then bernoulliFactor
        (pairRho q σ (latentZ n (θ.1 j)) (orientation θ j side)) r
      else if r then 1 else 0, ?_⟩
    intro v y r hv
    have hlabel : v.X = pairLabel n d hd j side := hv.trans hx
    simp only [pairedFullLaw_fullMass]
    have hl (t : Bool) : pairedAtomWeight n d q σ hd θ ⟨v, a, s, y, t⟩ =
        pairAtomWeight n d q σ hd θ j side ⟨v, a, s, y, t⟩ :=
      pairedAtomWeight_at_pair n d q σ hd θ j side ⟨v, a, s, y, t⟩ hlabel
    simp_rw [hl]
    exact pairAtomWeight_arrival_factor n d q σ hd θ j side v a s y r
  · refine ⟨fun _ => 0, ?_⟩
    intro v y r hv
    have hzero (w : FullAtom d) (hw : w.X = x) :
        pairedAtomWeight n d q σ hd θ w = 0 := by
      have hF : fillerAtomWeight n d q hd θ w = 0 := by
        have hnF : w.X ≠ fillerLabel d hd := by
          rw [hw]
          exact hxF
        simp [fillerAtomWeight, hnF]
      have hP (j : Fin (pairCount n d)) (side : Bool) :
          pairAtomWeight n d q σ hd θ j side w = 0 := by
        have hnP : w.X ≠ pairLabel n d hd j side := by
          rw [hw]
          exact fun he => hxP ⟨j, side, he⟩
        simp [pairAtomWeight, hnP]
      simp [pairedAtomWeight, hF, hP]
    simp only [pairedFullLaw_fullMass]
    have hz (t : Bool) : pairedAtomWeight n d q σ hd θ ⟨v, a, s, y, t⟩ = 0 :=
      hzero ⟨v, a, s, y, t⟩ hv
    simp [hz]

/-- The normalized law, bundled with its MAR-class certificate. -/
noncomputable def pairedClassLaw (n d : ℕ) (q σ : ℝ)
    (hn : 1 ≤ n) (hd : 1 ≤ d) (hq : q ∈ Set.Icc ((1 : ℝ) / 2) 1)
    (hσ : σ ∈ Set.Icc (-1) 1) (θ : Theta n d) : ClassLaw d q :=
  ⟨pairedFullLaw n d q σ hn hd hq hσ θ,
    pairedFullLaw_legal n d q σ hn hd hq hσ θ⟩

-- @env: S3
variable (β : ℝ)

/-- The pair of priors on legal normalized MAR laws, indexed by prior sign. -/
noncomputable def pairedPrior (n d : ℕ) (q : ℝ)
    (hn : 1 ≤ n) (hd : 1 ≤ d) (hq : q ∈ Set.Icc ((1 : ℝ) / 2) 1) :
    PMF (ClassLaw d q) × PMF (ClassLaw d q) :=
  let π := thetaLaw n d q hn hd hq
  (π.map (pairedClassLaw n d q (-1) hn hd hq (by norm_num : (-1 : ℝ) ∈ Set.Icc (-1) 1)),
   π.map (pairedClassLaw n d q 1 hn hd hq (by norm_num : (1 : ℝ) ∈ Set.Icc (-1) 1)))
  -- @realizes PiPair(priors pushed from latent draws to legal laws)

/-- Finite prior-predictive iid mixture for either sign. -/
noncomputable def pairedPredictive (n d : ℕ) (q σ : ℝ)
    (hn : 1 ≤ n) (hd : 1 ≤ d) (hq : q ∈ Set.Icc ((1 : ℝ) / 2) 1)
    (hσ : σ ∈ Set.Icc (-1) 1) : Measure (Fin n → Obs d) :=
  ∑ θ : Theta n d,
    (thetaLaw n d q hn hd hq θ) •
      samplePi (pairedFullLaw n d q σ hn hd hq hσ θ) n
  -- @realizes QPair(finite mixture of complete iid observed-sample laws)

/-- For [a covariate dimension](hyp:d) and [an arrival floor](hyp:q), [the class of legal laws is equipped with the discrete measurable structure](goal). -/
instance (d : ℕ) (q : ℝ) : MeasurableSpace (ClassLaw d q) := ⊤
/-- For [a covariate dimension](hyp:d) and [an arrival floor](hyp:q), [every singleton legal law is measurable](goal). -/
instance (d : ℕ) (q : ℝ) : MeasurableSingletonClass (ClassLaw d q) :=
  ⟨fun _ => trivial⟩

/-- The complete observed-sample mixture induced by any prior on legal laws. -/
noncomputable def priorPredictive (n d : ℕ) (q : ℝ)
    (π : PMF (ClassLaw d q)) : Measure (Fin n → Obs d) :=
  π.toMeasure.bind (fun P => samplePi P.val n)

/-- Prior probability of a target event. -/
noncomputable def priorEventMass (d : ℕ) (q : ℝ)
    (π : PMF (ClassLaw d q)) (E : ClassLaw d q → Prop) : ℝ :=
  π.toMeasure.real {P | E P}

-- @node: pmf_toMeasure_finset_decomposition
/-- [the stated mathematical conclusion holds](goal). Given [the specified input `α`](hyp:α), [the specified input `π`](hyp:π). -/
lemma pmf_toMeasure_finset_decomposition {α : Type*} [Fintype α]
    [MeasurableSpace α] [MeasurableSingletonClass α] (π : PMF α) :
    π.toMeasure = ∑ x : α, (π x) • Measure.dirac x := by
  classical
  ext s hs
  simp [PMF.toMeasure_apply_fintype, Measure.dirac_apply' _ hs, Set.indicator]

/-- For [a sample size of at least one](hyp:hn), [a positive dimension](hyp:hd), and [an admissible arrival floor](hyp:hq), [the negative-sign paired predictive law equals the predictive law of the first paired prior](goal). -/
lemma pairedPredictive_minus_eq (n d : ℕ) (q : ℝ)
    (hn : 1 ≤ n) (hd : 1 ≤ d) (hq : q ∈ Set.Icc ((1 : ℝ) / 2) 1) :
    pairedPredictive n d q (-1) hn hd hq (by norm_num : (-1 : ℝ) ∈ Set.Icc (-1) 1) =
      priorPredictive n d q (pairedPrior n d q hn hd hq).1 := by
  classical
  letI : MeasurableSpace (Theta n d) := ⊤
  letI : MeasurableSingletonClass (Theta n d) := ⟨fun _ => trivial⟩
  simp only [pairedPrior, priorPredictive, pairedPredictive]
  rw [← PMF.toMeasure_map (pairedClassLaw n d q (-1) hn hd hq (by norm_num : (-1 : ℝ) ∈ Set.Icc (-1) 1))
    (thetaLaw n d q hn hd hq) (by exact measurable_of_finite _)]
  simp only [Measure.bind]
  rw [pmf_toMeasure_finset_decomposition]
  have hclass : Measurable (pairedClassLaw n d q (-1) hn hd hq (by norm_num : (-1 : ℝ) ∈ Set.Icc (-1) 1)) :=
    measurable_of_finite _
  have hsample : Measurable (fun P : ClassLaw d q => samplePi P.val n) := by
    intro s hs
    trivial
  rw [Measure.map_map hsample hclass]
  rw [Measure.map_finset_sum' (hsample.comp hclass).aemeasurable]
  conv_rhs => rw [← Measure.sum_fintype, Measure.join_sum, Measure.sum_fintype]
  simp_rw [Measure.map_smul, Measure.map_dirac' (hsample.comp hclass)]
  simp [pairedClassLaw]

/-- For [a sample size of at least one](hyp:hn), [a positive dimension](hyp:hd), and [an admissible arrival floor](hyp:hq), [the positive-sign paired predictive law equals the predictive law of the second paired prior](goal). -/
lemma pairedPredictive_plus_eq (n d : ℕ) (q : ℝ)
    (hn : 1 ≤ n) (hd : 1 ≤ d) (hq : q ∈ Set.Icc ((1 : ℝ) / 2) 1) :
    pairedPredictive n d q 1 hn hd hq (by norm_num : (1 : ℝ) ∈ Set.Icc (-1) 1) =
      priorPredictive n d q (pairedPrior n d q hn hd hq).2 := by
  classical
  letI : MeasurableSpace (Theta n d) := ⊤
  letI : MeasurableSingletonClass (Theta n d) := ⟨fun _ => trivial⟩
  simp only [pairedPrior, priorPredictive, pairedPredictive]
  rw [← PMF.toMeasure_map (pairedClassLaw n d q 1 hn hd hq (by norm_num : (1 : ℝ) ∈ Set.Icc (-1) 1))
    (thetaLaw n d q hn hd hq) (by exact measurable_of_finite _)]
  simp only [Measure.bind]
  rw [pmf_toMeasure_finset_decomposition]
  have hclass : Measurable (pairedClassLaw n d q 1 hn hd hq (by norm_num : (1 : ℝ) ∈ Set.Icc (-1) 1)) :=
    measurable_of_finite _
  have hsample : Measurable (fun P : ClassLaw d q => samplePi P.val n) := by
    intro s hs
    trivial
  rw [Measure.map_map hsample hclass]
  rw [Measure.map_finset_sum' (hsample.comp hclass).aemeasurable]
  conv_rhs => rw [← Measure.sum_fintype, Measure.join_sum, Measure.sum_fintype]
  simp_rw [Measure.map_smul, Measure.map_dirac' (hsample.comp hclass)]
  simp [pairedClassLaw]

/-- Unnormalized observed atom coefficient of an oriented pair. -/
noncomputable def pairObservedCoeff (q σ z u : ℝ) (o : Obs d) : ℝ :=
  if o.S ≠ false then 0
  else if o.A = false ∧ o.R = true ∧ o.RY = false then 1 / 2
  else if o.A = true ∧ o.R = false ∧ o.RY = false then
    delta q * (1 + σ * z * u) / 4
  else if o.A = true ∧ o.R = true ∧ o.RY = true then
    (1 - delta q / 2) / 4 + u / 32
  else if o.A = true ∧ o.R = true ∧ o.RY = false then
    (1 - delta q / 2) / 4 - u / 32 - σ * delta q * z * u / 4
  else 0

/-- Fixed filler observed-atom coefficient. -/
noncomputable def fillerObservedCoeff (q : ℝ) (o : Obs d) : ℝ :=
  if o.S ≠ false then 0
  else if o.A = false ∧ o.R = true ∧ o.RY = false then 1 / 2
  else if o.A = true ∧ o.R = true ∧ o.RY = true then baseMean q / 2
  else if o.A = true ∧ o.R = true ∧ o.RY = false then (1 - baseMean q) / 2
  else 0

/-- Unnormalized mass at an observed atom in the count experiment. -/
noncomputable def countAtomMass (n d : ℕ) (q σ : ℝ) (hd : 1 ≤ d)
    (θ : Theta n d) (o : Obs d) : ℝ :=
  (if o.X = fillerLabel d hd then fillerMass n d * fillerObservedCoeff q o else 0) +
    ∑ j : Fin (pairCount n d), ∑ side : Bool,
      if o.X = pairLabel n d hd j side then
        latentP n (θ.1 j) * pairObservedCoeff q σ (latentZ n (θ.1 j))
          (orientation θ j side) o
      else 0

/-- Independent Poisson counts with rate `4n` times each unnormalized atom mass. -/
noncomputable def conditionalCountLaw (n d : ℕ) (q σ : ℝ) (hd : 1 ≤ d)
    (θ : Theta n d) : Measure (Obs d → ℕ) :=
  Measure.pi (fun o : Obs d =>
    poissonMeasure (Real.toNNReal (4 * (n : ℝ) * countAtomMass n d q σ hd θ o)))

/-- Latent mixture of the unnormalized count experiment. -/
noncomputable def mixedCountLaw (n d : ℕ) (q σ : ℝ)
    (hn : 1 ≤ n) (hd : 1 ≤ d) (hq : q ∈ Set.Icc ((1 : ℝ) / 2) 1) : Measure (Obs d → ℕ) :=
  ∑ θ : Theta n d,
    (thetaLaw n d q hn hd hq θ) • conditionalCountLaw n d q σ hd θ

/-- The number of records in a finite count vector. -/
def countTotal (counts : Obs d → ℕ) : ℕ := ∑ o : Obs d, counts o

/-- An ordering has exactly the specified multiset of records. -/
def ValidOrdering (counts : Obs d → ℕ)
    (order : Fin (countTotal counts) → Obs d) : Prop :=
  ∀ o, (Finset.univ.filter (fun i => order i = o)).card = counts o

/-- For [observed-cell counts](hyp:counts), [the collection of all orderings with exactly those counts is defined](goal). -/
noncomputable def validOrders (counts : Obs d → ℕ) :
    Finset (Fin (countTotal counts) → Obs d) := by
  classical
  exact Finset.univ.filter (ValidOrdering counts)

-- @node: uniformOrdering_sum
/-- Given [the specified input `counts`](hyp:counts), [the stated mathematical conclusion holds](goal). -/
lemma uniformOrdering_sum (counts : Obs d → ℕ) :
    ∑ order : Fin (countTotal counts) → Obs d,
      (if order ∈ validOrders counts then
        (1 / (validOrders counts).card : ℝ≥0∞) else 0) = 1 := by
  classical
  have hcard : Fintype.card (Σ o : Obs d, Fin (counts o)) = countTotal counts := by
    simp [Fintype.card_sigma, countTotal]
  let e : Fin (countTotal counts) ≃ Σ o : Obs d, Fin (counts o) :=
    Fintype.equivOfCardEq (by simpa using hcard.symm)
  let order : Fin (countTotal counts) → Obs d := fun i => (e i).1
  have hvalid : ValidOrdering counts order := by
    intro o
    let fiberSigma : {s : (Σ o : Obs d, Fin (counts o)) // s.1 = o} ≃
        Fin (counts o) := {
      toFun := fun ⟨⟨o', j⟩, h⟩ => h ▸ j
      invFun := fun j => ⟨⟨o, j⟩, rfl⟩
      left_inv := by intro ⟨⟨o', j⟩, h⟩; cases h; rfl
      right_inv := by intro j; rfl
    }
    let fiber : {i : Fin (countTotal counts) // order i = o} ≃ Fin (counts o) :=
      (e.subtypeEquiv (fun _ => Iff.rfl)).trans fiberSigma
    calc
      (Finset.univ.filter (fun i => order i = o)).card =
          Fintype.card {i : Fin (countTotal counts) // order i = o} :=
            (Fintype.card_subtype _).symm
      _ = Fintype.card (Fin (counts o)) := Fintype.card_congr fiber
      _ = counts o := Fintype.card_fin _
  have hmem : order ∈ validOrders counts := by
    simp [validOrders, hvalid]
  have hpos : 0 < (validOrders counts).card := Finset.card_pos.mpr ⟨order, hmem⟩
  simp only [Finset.sum_ite, Finset.sum_const_zero, add_zero,
    Finset.sum_const, nsmul_eq_mul]
  have hc : (Finset.univ.filter (fun x => x ∈ validOrders counts)) =
      validOrders counts := by ext; simp
  rw [hc, one_div]
  apply ENNReal.mul_inv_cancel
  · exact_mod_cast hpos.ne'
  · simp

/-- Uniform ordering of the finite counted multiset. -/
noncomputable def uniformOrdering (counts : Obs d → ℕ) :
    PMF (Fin (countTotal counts) → Obs d) :=
  PMF.ofFintype (fun order => if order ∈ validOrders counts then
    (1 / (validOrders counts).card : ℝ≥0∞) else 0)
    (uniformOrdering_sum counts)

/-- Uniform ordering followed by first-`n` truncation, independent of sign and latent draws. -/
noncomputable def countOrderingKernel (n d : ℕ) (o_circle : Obs d)
    (counts : Obs d → ℕ) : PMF (Fin n → Obs d) :=
  (uniformOrdering counts).map (fun order i =>
    if h : n ≤ countTotal counts then
      order ⟨i.val, Nat.lt_of_lt_of_le i.isLt h⟩
    else o_circle)

/-- The public handle for the normalized paired-prior construction and its
associated predictive and count experiments. -/
structure PairedPriorHandle (n d : ℕ) (q : ℝ) where
  priors : PMF (ClassLaw d q) × PMF (ClassLaw d q)
  predictiveMinus : Measure (Fin n → Obs d)
  predictivePlus : Measure (Fin n → Obs d)
  countMinus : Measure (Obs d → ℕ)
  countPlus : Measure (Obs d → ℕ)
  fallback : Obs d
  kernel : (Obs d → ℕ) → PMF (Fin n → Obs d)

-- @node: def:paired-prior-handle
/-- The normalized same-experiment paired-prior handle, including the induced
sample mixtures, Poisson count experiments, and the fixed-record truncation
kernel used to transfer between them. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `o_circle`](hyp:o_circle), [the specified input `hn`](hyp:hn), [the specified input `hd`](hyp:hd), [the stated mathematical conclusion holds](goal). Given [the specified input `hq`](hyp:hq). -/
noncomputable def pairedPriorHandle (n d : ℕ) (q : ℝ) (o_circle : Obs d)
    (hn : 1 ≤ n) (hd : 1 ≤ d) (hq : q ∈ Set.Icc ((1 : ℝ) / 2) 1) :
    PairedPriorHandle n d q where
  priors := pairedPrior n d q hn hd hq
  predictiveMinus := pairedPredictive n d q (-1) hn hd hq (by norm_num : (-1 : ℝ) ∈ Set.Icc (-1) 1)
  predictivePlus := pairedPredictive n d q 1 hn hd hq (by norm_num : (1 : ℝ) ∈ Set.Icc (-1) 1)
  countMinus := mixedCountLaw n d q (-1) hn hd hq
  countPlus := mixedCountLaw n d q 1 hn hd hq
  fallback := o_circle
  kernel := countOrderingKernel n d o_circle

end CausalSmith.Stat.MarNearcompleteFrontier
