module
public import CausalSmith.Stat.STAT_SparseheterogeneityCriticalRadius_Research.Helpers.Converse.ChiSquare

/-! Helpers/Converse/Normalization.lean; scaffold of the indicated proof chain. -/

public section

namespace CausalSmith.Stat.SparseheterogeneityCriticalRadius

open MeasureTheory Set Filter
open scoped BigOperators ENNReal

lemma raw_mass_total_positive (n J : ℕ) (kappa : ℝ)
    (theta : Fin (n - 1) → LatentCell) (hn : 0 < n)
    (hkappa : 0 ≤ kappa)
    (hq : ∀ k, 0 ≤ latentIntensity (theta k)) :
    0 < rawMassTotal n J kappa theta := by
  have hnonneg : ∀ k ∈ (Finset.univ : Finset (Fin n)),
      0 ≤ rawRareMass n J kappa theta k := by
    intro k hk
    unfold rawRareMass
    split_ifs with h
    · exact mul_nonneg
        (div_nonneg (mul_nonneg hkappa (by exact_mod_cast Nat.zero_le J))
          (by positivity)) (hq _)
    · norm_num
  unfold rawMassTotal
  apply (Finset.sum_pos_iff_of_nonneg hnonneg).2
  refine ⟨⟨n - 1, by omega⟩, Finset.mem_univ _, ?_⟩
  simp [rawRareMass]

/-- The ATE of a law selected from the latent construction is the normalized
signed-score sum.  This is the exact finite-law form of roadmap equations
(69) and (75), before any concentration argument is applied. -/
lemma latentLawSpec_ateTarget_eq {n J : ℕ} {M rho kappa gamma : ℝ}
    {theta : Fin (n - 1) → LatentCell} {P : Law n}
    (hs : LatentLawSpec n M rho kappa gamma J theta P) :
    ateTarget P =
      ∑ k : Fin n,
        (rawRareMass n J kappa theta k / rawMassTotal n J kappa theta) *
          (if hk : k.val < n - 1 then
            gamma * M * rho * latentScore (theta ⟨k.val, hk⟩) / 4 *
              (if latentSign (theta ⟨k.val, hk⟩) then 1 else -1)
          else 0) := by
  classical
  unfold ateTarget DiscreteAteHeterogeneityFrontier.rawAteFormula
  apply Finset.sum_congr rfl
  intro k hk
  rw [hs.1 k]
  unfold DiscreteAteHeterogeneityFrontier.cellEffect
  rw [hs.2.2.1 k, hs.2.2.2.1 k, sub_zero]

/-- Every cell effect generated by a legal latent score has magnitude at most
one quarter of the scale times the supplied radius. -/
lemma latentLawSpec_effect_bound_general {n J : ℕ} {M rho kappa gamma : ℝ}
    {theta : Fin (n - 1) → LatentCell} {P : Law n}
    (hM : 0 ≤ M) (hrho : 0 ≤ rho ∧ rho ≤ 2)
    (hgamma : gamma ∈ Icc (0 : ℝ) 1)
    (hu : ∀ k, latentScore (theta k) ∈ Icc (0 : ℝ) 1)
    (hs : LatentLawSpec n M rho kappa gamma J theta P) (k : Fin n) :
    |DiscreteAteHeterogeneityFrontier.cellEffect P k| ≤ M * rho / 4 := by
  classical
  unfold DiscreteAteHeterogeneityFrontier.cellEffect
  rw [hs.2.2.1 k, hs.2.2.2.1 k, sub_zero]
  split_ifs with hk hz
  · have hb := hu ⟨k.val, hk⟩
    have hmrho : 0 ≤ M * rho := mul_nonneg hM hrho.1
    have hprod : 0 ≤ gamma * M * rho * latentScore (theta ⟨k.val, hk⟩) :=
      mul_nonneg (mul_nonneg (mul_nonneg hgamma.1 hM) hrho.1) hb.1
    have hgammaScore : gamma * latentScore (theta ⟨k.val, hk⟩) ≤ 1 := by
      calc
        gamma * latentScore (theta ⟨k.val, hk⟩) ≤
            1 * latentScore (theta ⟨k.val, hk⟩) :=
          mul_le_mul_of_nonneg_right hgamma.2 hb.1
        _ ≤ 1 * 1 := mul_le_mul_of_nonneg_left hb.2 (by norm_num)
        _ = 1 := one_mul 1
    have hle : gamma * M * rho * latentScore (theta ⟨k.val, hk⟩) ≤ M * rho := by
      calc
        gamma * M * rho * latentScore (theta ⟨k.val, hk⟩) =
            (M * rho) * (gamma * latentScore (theta ⟨k.val, hk⟩)) := by ring
        _ ≤ (M * rho) * 1 := mul_le_mul_of_nonneg_left hgammaScore hmrho
        _ = M * rho := mul_one _
    simp only [mul_one]
    rw [abs_of_nonneg (div_nonneg hprod (by norm_num))]
    linarith
  · have hb := hu ⟨k.val, hk⟩
    have hmrho : 0 ≤ M * rho := mul_nonneg hM hrho.1
    have hprod : 0 ≤ gamma * M * rho * latentScore (theta ⟨k.val, hk⟩) :=
      mul_nonneg (mul_nonneg (mul_nonneg hgamma.1 hM) hrho.1) hb.1
    have hgammaScore : gamma * latentScore (theta ⟨k.val, hk⟩) ≤ 1 := by
      calc
        gamma * latentScore (theta ⟨k.val, hk⟩) ≤
            1 * latentScore (theta ⟨k.val, hk⟩) :=
          mul_le_mul_of_nonneg_right hgamma.2 hb.1
        _ ≤ 1 * 1 := mul_le_mul_of_nonneg_left hb.2 (by norm_num)
        _ = 1 := one_mul 1
    have hle : gamma * M * rho * latentScore (theta ⟨k.val, hk⟩) ≤ M * rho := by
      calc
        gamma * M * rho * latentScore (theta ⟨k.val, hk⟩) =
            (M * rho) * (gamma * latentScore (theta ⟨k.val, hk⟩)) := by ring
        _ ≤ (M * rho) * 1 := mul_le_mul_of_nonneg_left hgammaScore hmrho
        _ = M * rho := mul_one _
    rw [show gamma * M * rho * latentScore (theta ⟨k.val, hk⟩) / 4 * -1 =
      -(gamma * M * rho * latentScore (theta ⟨k.val, hk⟩) / 4) by ring,
      abs_neg, abs_of_nonneg (div_nonneg hprod (by norm_num))]
    linarith
  · rw [abs_zero]
    exact div_nonneg (mul_nonneg hM hrho.1) (by norm_num)

/-- The mass-weighted target inherits the same signed-score envelope. -/
lemma latentLawSpec_target_bound_general {n J : ℕ} {M rho kappa gamma : ℝ}
    {theta : Fin (n - 1) → LatentCell} {P : Law n}
    (hM : 0 ≤ M) (hrho : 0 ≤ rho ∧ rho ≤ 2)
    (hgamma : gamma ∈ Icc (0 : ℝ) 1)
    (hu : ∀ k, latentScore (theta k) ∈ Icc (0 : ℝ) 1)
    (hs : LatentLawSpec n M rho kappa gamma J theta P) :
    |ateTarget P| ≤ M * rho / 4 := by
  unfold ateTarget DiscreteAteHeterogeneityFrontier.rawAteFormula
  calc
    |∑ k : Fin n, P.cellMass k * DiscreteAteHeterogeneityFrontier.cellEffect P k| ≤
        ∑ k : Fin n, |P.cellMass k *
          DiscreteAteHeterogeneityFrontier.cellEffect P k| :=
      Finset.abs_sum_le_sum_abs _ _
    _ ≤ ∑ k : Fin n, P.cellMass k * (M * rho / 4) := by
      apply Finset.sum_le_sum
      intro k hk
      rw [abs_mul, abs_of_nonneg (P.cellMass_range k).1]
      exact mul_le_mul_of_nonneg_left
        (latentLawSpec_effect_bound_general hM hrho hgamma hu hs k)
        (P.cellMass_range k).1
    _ = M * rho / 4 := by
      rw [← Finset.sum_mul,
        DiscreteAteHeterogeneityFrontier.sum_cellMass_eq_one, one_mul]

/-- A legal latent law obeys the supplied approximate-homogeneity radius. -/
lemma latentLawSpec_radius_general {n J : ℕ} {M rho kappa gamma : ℝ}
    {theta : Fin (n - 1) → LatentCell} {P : Law n}
    (hM : 0 ≤ M) (hrho : 0 ≤ rho ∧ rho ≤ 2)
    (hgamma : gamma ∈ Icc (0 : ℝ) 1)
    (hu : ∀ k, latentScore (theta k) ∈ Icc (0 : ℝ) 1)
    (hs : LatentLawSpec n M rho kappa gamma J theta P) : KnownRadius M rho P := by
  refine ⟨hrho, ?_⟩
  intro k hk
  change |DiscreteAteHeterogeneityFrontier.cellEffect P k - ateTarget P| ≤ rho * M
  calc
    _ ≤ |DiscreteAteHeterogeneityFrontier.cellEffect P k| + |ateTarget P| :=
      abs_sub _ _
    _ ≤ M * rho / 4 + M * rho / 4 := add_le_add
      (latentLawSpec_effect_bound_general hM hrho hgamma hu hs k)
      (latentLawSpec_target_bound_general hM hrho hgamma hu hs)
    _ ≤ rho * M := by nlinarith [mul_nonneg hM hrho.1]

/-- Binary outcomes at scale `M` give the required conditional variance
envelope for every legal latent law. -/
lemma latentLawSpec_varianceEnvelope_general {n J : ℕ} {M rho kappa gamma : ℝ}
    {theta : Fin (n - 1) → LatentCell} {P : Law n}
    (hM : 0 ≤ M) (hrho : 0 ≤ rho ∧ rho ≤ 2)
    (hgamma : gamma ∈ Icc (0 : ℝ) 1)
    (hu : ∀ k, latentScore (theta k) ∈ Icc (0 : ℝ) 1)
    (hs : LatentLawSpec n M rho kappa gamma J theta P) : VarianceEnvelope M P := by
  intro a k hk
  letI := P.outcome_isProbability a k
  have hm : |P.outcomeMean a k| ≤ M / 2 := by
    cases a with
    | false => rw [hs.2.2.1 k]; simpa using div_nonneg hM (by norm_num : (0 : ℝ) ≤ 2)
    | true =>
      have he := latentLawSpec_effect_bound_general hM hrho hgamma hu hs k
      unfold DiscreteAteHeterogeneityFrontier.cellEffect at he
      rw [hs.2.2.1 k, sub_zero] at he
      calc
        |P.outcomeMean true k| ≤ M * rho / 4 := he
        _ ≤ M / 2 := by nlinarith [mul_nonneg hM hrho.1]
  have hb : ∀ᵐ y ∂P.outcomeLaw a k, y ∈ ({-(M / 2), M / 2} : Set ℝ) := by
    rw [ae_iff]
    change P.outcomeLaw a k (({-(M / 2), M / 2} : Set ℝ)ᶜ) = 0
    exact hs.2.2.2.2.1 a k
  have hbound : ∀ᵐ y ∂P.outcomeLaw a k,
      (y - P.outcomeMean a k) ^ 2 ∈ Icc (0 : ℝ) (M ^ 2) := by
    filter_upwards [hb] with y hy
    have hm' := abs_le.mp hm
    refine ⟨sq_nonneg _, ?_⟩
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hy
    rcases hy with rfl | rfl <;> nlinarith [hm'.1, hm'.2]
  have hi : Integrable (fun y => (y - P.outcomeMean a k) ^ 2)
      (P.outcomeLaw a k) :=
    Integrable.of_mem_Icc 0 (M ^ 2) (by fun_prop) hbound
  refine ⟨hi, ?_⟩
  have hle := integral_mono_ae hi (integrable_const (M ^ 2))
    (hbound.mono (fun y hy => hy.2))
  simpa using hle

/-- Every legal selected latent law lies in the full known-radius class at
the original outcome scale. -/
lemma latentLawSpec_class_embedding_general {n J : ℕ} {M rho kappa gamma : ℝ}
    {theta : Fin (n - 1) → LatentCell} {P : Law n}
    (hn : 3 ≤ n) (hM : 1 ≤ M) (hrho : 0 ≤ rho ∧ rho ≤ 2)
    (hgamma : gamma ∈ Icc (0 : ℝ) 1)
    (he : ∀ k, latentPropensity (theta k) ∈ Icc (1 / 4 : ℝ) (3 / 4))
    (hu : ∀ k, latentScore (theta k) ∈ Icc (0 : ℝ) 1)
    (hs : LatentLawSpec n M rho kappa gamma J theta P) :
    ∃ Q : KnownRadiusClass n M rho, Q.law = P := by
  classical
  have hM0 : 0 ≤ M := zero_le_one.trans hM
  refine ⟨{ law := P
            n_ge_three := hn
            M_ge_one := hM
            consistency := hs.2.2.2.2.2.2.1
            exchangeability := hs.2.2.2.2.2.2.2
            overlap := ?_
            mean_envelope := ?_
            variance_envelope :=
              latentLawSpec_varianceEnvelope_general hM0 hrho hgamma hu hs
            radius := latentLawSpec_radius_general hM0 hrho hgamma hu hs }, rfl⟩
  · intro k hk
    rw [hs.2.1 k]
    split_ifs with h
    · have hb := he ⟨k.val, h⟩
      constructor
      · exact hb.1
      · linarith [hb.2]
    · norm_num
  · intro a k hk
    cases a with
    | false => rw [hs.2.2.1 k, abs_zero]; positivity
    | true =>
      have hb := latentLawSpec_effect_bound_general hM0 hrho hgamma hu hs k
      unfold DiscreteAteHeterogeneityFrontier.cellEffect at hb
      rw [hs.2.2.1 k, sub_zero] at hb
      calc
        |P.outcomeMean true k| ≤ M * rho / 4 := hb
        _ ≤ M / 2 := by nlinarith [mul_nonneg hM0 hrho.1]

end CausalSmith.Stat.SparseheterogeneityCriticalRadius
