/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Basic
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Defs.Estimator
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Defs.Fiber
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Defs.Model
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers.ChiSquaredObservation
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers.CompatibleModelRealization
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers.GaussianLikelihood
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers.LogClip
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers.Matching
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers.MedianOfMeans
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers.MedianOfMeansCore
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers.MomentBridge
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers.NoisyIncompleteExperiment
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers.NoisyIncompleteStructural
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers.NoisyIncompleteTargets
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers.NoisyRecovery
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers.OffsetExampleWitnesses
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers.OffsetExamples
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers.OffsetVariance
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers.PermutationExperiment
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers.PermutationLowerBound
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers.PoissonMixtureMoments
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers.RateBounds
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers.SameLawCompletionFibers
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers.SameLawCompletionRealization
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers.SharpTargetIncidence
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers.SharpTargetQueueComplete
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers.StructuralMean
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.Helpers.Triangular
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.TBoundedMomentCertificate
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.TCompatibilityCompletion
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.TDeterministicCertificate
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.TDuplicateInvariance
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.TEntrywiseCompletion
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.TFullCoverReduction
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.TLabelMechanismFrontier
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.TLabelRateLowerBound
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.TNoUniformNoisyIncompleteSharpness
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.TSeparatedNoisyIncompleteTargetSets
public import CausalSmith.ExactID.EID_CountshiftUnlabeledMatching_Research.TSharpTargetSets

/-! # Run barrel (auto-generated)

Aggregates every module of this causalsmith run so the whole run is ONE buildable target
(`lake build <this module>`). Research modules are not reachable from the top-level
`CausalSmith.lean` barrel, so the default lake target skips them and reports green on stale
oleans. Rewritten from the run's module set on every F-stage entry — do not hand-edit. -/
