/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Basic
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Basic.Cumulants
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Basic.Swaps
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Basic.World
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Handles
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.AdmissibleSwaps
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.AffineSpaceDimension
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.AffineSubspaceDimension
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.AlgebraicSetChains
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ApolarDefs
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ApolarKernel
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ApolarKernelAux
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ApolarKernelDiff
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ApolarKernelIdentity
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ApolarKernelRank
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ApolarQD
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ApolarRankBridge
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ArrowPolynomialGeometry
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.BandDimensionTransfer
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.BandParameterCoordinates
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.BandWeightKernelDimension
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.CAD.CADInterface
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.CommonAxisImageGeometry
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.CommonAxisPrincipalEquations
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.CommonAxisReversal
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.CommonAxisTwin
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ConfluentVandermonde
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.CoordinateReversalGeometry
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.DirectLatentSwaps
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.CAD.EffectiveRationalGroebnerCADInterface
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.EmptyFiber
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ExceptionalCodimension
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ExceptionalCommonAxisJacobianTop
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ExceptionalCommonAxisOrdinary
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ExceptionalGeometryBasic
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ExceptionalHeightReduction
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ExceptionalImageDimension
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ExceptionalImageDimensionUpper
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ExceptionalIncidence
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ExceptionalJacobianCoordinates
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ExceptionalJacobianMinor
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.FiberDimensionDefs
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.FiberSlopeComponents
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.FiniteCodimensionTransfer
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.FiniteCumBand
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.FixedLoadingFiberDimension
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.FullFiberSlopeRecovery
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.GenericFiberDimension
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.GenericSlopes
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.IrreducibleFiniteRange
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.LoadingWeightKernelDimension
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.LowerOrderApolarKernel
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.LowerOrderApolarRank
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.LowerOrderApolarSeparation
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.LowerOrderEmptyFiber
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.MomentGate
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.PinSubst
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.PolynomialRetractDimension
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.PrincipalHeightOne
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ReverseApolarKernel
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.SlopeUniqueness
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.Varieties
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.WeightSynthesisDimension
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ZariskiLocus
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Selector
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.TAdmissibleSwaps
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.TApolar
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.TAtlas
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.TExceptionalLocus
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.TGenericSeparation
public import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.TInfoOrder

/-! # Run barrel (auto-generated)

Aggregates every module of this causalsmith run so the whole run is ONE buildable target
(`lake build <this module>`). Research modules are not reachable from the top-level
`CausalSmith.lean` barrel, so the default lake target skips them and reports green on stale
oleans. Rewritten from the run's module set on every F-stage entry — do not hand-edit. -/
