/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan

# Proximal partial-identification — q-collapse on the on-arm σ_AX

`condExp_q_eq_stratumOddsRatio_arm_AX`: under the codebase's
**probability-ratio** q convention, the σ_AX-conditional expectation of
`q(Z, a, X)` collapses on `{A = a}` to the σ_X-measurable
`stratumOddsRatio`. This is the helper that lets the public WZ partial-ID
bound mirror the W-only theorem (no `q` factor in the public statement).

Concretely:

    μ[fun ω => q (Z ω, a, X ω) | σ_AX] =ᵐ[restrict {A = a}] stratumOddsRatio.

Proof structure: σ_AX is generated by `(A, X)`, so any σ_AX-measurable set
restricted to `{A = a}` is of the form `X⁻¹(C_a) ∩ {A = a}` for Borel
`C_a ⊆ γ_X`. Hence the σ_AX-CE check via
`ae_eq_condExp_of_forall_setIntegral_eq` reduces to: for any σ_X-measurable
indicator `g_X = 𝟙_{C_a}(X)`,

    ∫_{A=a} g_X · q dμ = ∫_{A=a} g_X · stratumOddsRatio dμ.

The chain for this identity:

    ∫_{A=a} g_X · q dμ
      = ∫_{A=a} g_X · E[q | σ_AUX] dμ        -- σ_AUX pull-out (g_X σ_X ≤ σ_AUX-meas)
      = ∫_{A=a} g_X · L_a dμ                  -- bridge_q on {A=a}
      = ∫_{A=¬a} g_X dμ                       -- LR-swap with m=σ_UX
      = ∫_{A=a} g_X · stratumOddsRatio dμ     -- LR-swap with m=σ_X

The two LR-swap applications use the weakened hypothesis-form of
`setIntegral_eq_setIntegral_mul_of_likelihoodRatio_swap` (only requires
`IntegrableOn` on the relevant arm, not global L¹). The σ_X swap consumes
`stratumOddsRatio_spec` below. The required integrability bound
`IntegrableOn stratumOddsRatio {A = a} μ` is supplied by
`integrableOn_stratumOddsRatio_arm`, via the abstract helper
`integrableOn_of_condExp_indicator_mul`.
-/

module
public import Causalean.PO.ID.Partial.Proxy.Helpers.Common
public import Causalean.Mathlib.MeasureTheory.Integral.LikelihoodRatio
public import Causalean.Mathlib.Probability.Independence.Conditional

/-! # Conditional-expectation identities for treatment bridges

This file derives the conditional-expectation identity that connects the
treatment bridge `q` to the observable stratum odds ratio. The result is used by
the two-proxy partial-identification envelope chain to eliminate the latent
treatment bridge from the public bound.
-/

public section

open Causalean.Mathlib.MeasureTheory.Integral

open Causalean.Mathlib.Probability.Independence.Conditional

namespace Causalean
namespace PO

open MeasureTheory ProbabilityTheory

namespace POProximalSystem

variable {P : POSystem}
  {γ_X γ_Z γ_W γ_U : Type*}
  [MeasurableSpace γ_X] [MeasurableSpace γ_Z]
  [MeasurableSpace γ_W] [MeasurableSpace γ_U]
  {S : POProximalSystem P γ_X γ_Z γ_W γ_U}
  {μ : Measure P.Ω} [IsFiniteMeasure μ] [StandardBorelSpace P.Ω]

/-! ### σ_X projection of the likelihood-ratio change-of-measure spec

The σ_X version of `likelihoodRatio_swapA_spec`, with `stratumOddsRatio`
playing the role of the σ_X-measurable likelihood ratio:

    μ[𝟙_{A=a} | σ_X] · stratumOddsRatio  =ᵐ[μ]  μ[𝟙_{A=¬a} | σ_X].

The σ_X positivity of `μ[𝟙_{A=a} | σ_X]` is the substantive step, supplied
by `ae_pos_condExp_indicator_of_le`; the algebraic cancellation
`den · (num/den) = num` then closes by `field_simp`. -/
private lemma stratumOddsRatio_spec
    (HA : POProximalSystem.TwoProxyAssumptions S μ) (a : Bool) :
    (fun ω =>
        (μ[Set.indicator {ω' | S.A ω' = a} (fun _ => (1 : ℝ)) | S.σ_X]) ω
        * S.stratumOddsRatio μ a ω)
      =ᵐ[μ]
    (μ[Set.indicator {ω' | S.A ω' ≠ a} (fun _ => (1 : ℝ)) | S.σ_X]) := by
  have hpos := ae_pos_condExp_indicator_of_le
    (m₁ := S.σ_X) S.σ_X_le
    (E := {ω' | S.A ω' = a})
    (S.measurable_A (measurableSet_singleton a))
    (fun s hs hnull => HA.overlap_strong a s (S.σ_X_le_σ_UX s hs) hnull)
  filter_upwards [hpos] with ω hω
  show (μ[Set.indicator {ω' | S.A ω' = a} (fun _ => (1 : ℝ)) | S.σ_X]) ω
        * S.stratumOddsRatio μ a ω
      = (μ[Set.indicator {ω' | S.A ω' ≠ a} (fun _ => (1 : ℝ)) | S.σ_X]) ω
  unfold POProximalSystem.stratumOddsRatio
  field_simp

/-! ### Integrability of `stratumOddsRatio` on the conditioning arm

The bound `∫_{A=a} stratumOddsRatio dμ ≤ μ {A=¬a}` is a one-line consequence of
`stratumOddsRatio_spec` together with the abstract Mathlib-candidate
`integrableOn_of_condExp_indicator_mul` (truncation + σ-pull-out + MCT). -/
private lemma integrableOn_stratumOddsRatio_arm
    (HA : POProximalSystem.TwoProxyAssumptions S μ) (a : Bool) :
    IntegrableOn (S.stratumOddsRatio μ a) {ω | S.A ω = a} μ := by
  set R : P.Ω → ℝ := S.stratumOddsRatio μ a with hR_def
  have hR_meas_X : Measurable[S.σ_X] R := by
    have h1 : Measurable[S.σ_X]
        (μ[Set.indicator {ω' | S.A ω' ≠ a} (fun _ => (1 : ℝ)) | S.σ_X]) := by fun_prop
    have h2 : Measurable[S.σ_X]
        (μ[Set.indicator {ω' | S.A ω' = a} (fun _ => (1 : ℝ)) | S.σ_X]) := by fun_prop
    exact h1.div h2
  have hR_nn : 0 ≤ᵐ[μ] R := by
    have hnum : 0 ≤ᵐ[μ]
        (μ[Set.indicator {ω' | S.A ω' ≠ a} (fun _ => (1 : ℝ)) | S.σ_X]) :=
      condExp_nonneg (Filter.Eventually.of_forall fun ω => by
        by_cases h : ω ∈ {ω' | S.A ω' ≠ a}
        · simp [Set.indicator_of_mem h]
        · simp [Set.indicator_of_notMem h])
    have hden : 0 ≤ᵐ[μ]
        (μ[Set.indicator {ω' | S.A ω' = a} (fun _ => (1 : ℝ)) | S.σ_X]) :=
      condExp_nonneg (Filter.Eventually.of_forall fun ω => by
        by_cases h : ω ∈ {ω' | S.A ω' = a}
        · simp [Set.indicator_of_mem h]
        · simp [Set.indicator_of_notMem h])
    filter_upwards [hnum, hden] with ω hn hd
    exact div_nonneg hn hd
  exact integrableOn_of_condExp_indicator_mul
    (m := S.σ_X) S.σ_X_le
    (B := {ω | S.A ω = a}) (C := {ω | S.A ω ≠ a})
    (S.measurable_A (measurableSet_singleton a))
    (S.measurable_A (measurableSet_singleton a)).compl
    hR_meas_X hR_nn (stratumOddsRatio_spec HA a)

/-! ### Main lemma -/

/-- **q-collapse on the on-arm σ(A,X) (TwoProxy).** Fix [a treatment arm](hyp:a) and assume [the
two-proxy bridge assumption bundle](hyp:HA). Under the
probability-ratio convention for the treatment-proxy bridge `q` encoded by
`likelihoodRatio_swapA_spec`, [restricted to the stratum
`{A = a}`, the conditional expectation of `q(Z, a, X)` given the σ-algebra generated by
treatment and covariates collapses to the σ(X)-measurable stratum odds ratio
`p(A≠a∣X)/p(A=a∣X)`](goal):

    μ[q(Z, a, X) | σ_AX] =ᵐ[restrict {A = a}] stratumOddsRatio.

This is a probability-ratio analogue of the source paper's density-ratio
normalization step, under a different bridge convention. It is the key collapse
that, combined with
`condExp_Y_eq_condExp_h_arm_AX_twoProxy`, lets the public WZ partial-ID
bound remove both `h` and `q` from the statement.

The positivity and integrability inputs are supplied by
`ae_pos_condExp_indicator_of_le` and
`integrableOn_stratumOddsRatio_arm`; the chain itself uses the weakened form of
`setIntegral_eq_setIntegral_mul_of_likelihoodRatio_swap`
(IntegrableOn-on-arm hypotheses) twice — once at σ_UX with `L_a`,
once at σ_X with `stratumOddsRatio`. -/
lemma condExp_q_eq_stratumOddsRatio_arm_AX
    (HA : POProximalSystem.TwoProxyAssumptions S μ) (a : Bool) :
    (μ[fun ω => HA.q (S.Z ω, a, S.X ω) | S.σ_AX])
      =ᵐ[μ.restrict {ω | S.A ω = a}]
    S.stratumOddsRatio μ a := by
  -- Notation.
  set q' : P.Ω → ℝ := fun ω => HA.q (S.Z ω, a, S.X ω) with hq'_def
  set L_a : P.Ω → ℝ := HA.likelihoodRatio_swapA a with hLa_def
  set R : P.Ω → ℝ := S.stratumOddsRatio μ a with hR_def
  set ind : P.Ω → ℝ := Set.indicator {ω' | S.A ω' = a} (fun _ => (1:ℝ)) with hind_def
  -- Basic measurability / integrability facts.
  have hs_meas : MeasurableSet {ω : P.Ω | S.A ω = a} :=
    S.measurable_A (measurableSet_singleton a)
  have hs_in_AX : MeasurableSet[S.σ_AX] {ω | S.A ω = a} := by
    refine ⟨Prod.fst ⁻¹' {a}, ?_, ?_⟩
    · exact measurable_fst (measurableSet_singleton a)
    · ext ω; rfl
  have hs_in_AUX : MeasurableSet[S.σ_AUX] {ω | S.A ω = a} :=
    S.σ_AX_le_σ_AUX _ hs_in_AX
  have hq'_int : Integrable q' μ := by fun_prop
  have hLa_int : Integrable L_a μ := by fun_prop
  have hLa_m_UX : Measurable[S.σ_UX] L_a := by fun_prop
  -- ind is bounded by 1 and σ_AX-measurable (lifts to mΩ).
  have hind_meas_AX : Measurable[S.σ_AX] ind := by fun_prop
  have hind_meas : Measurable ind := by fun_prop
  have hind_le : ∀ ω, ‖ind ω‖ ≤ 1 := by
    intro ω; by_cases h : ω ∈ {ω' | S.A ω' = a}
    · simp [ind, Set.indicator_of_mem h]
    · simp [ind, Set.indicator_of_notMem h]
  have hind_int : Integrable ind μ := by fun_prop
  -- f := ind * q', g := ind * R.
  set f : P.Ω → ℝ := fun ω => ind ω * q' ω with hf_def
  set g : P.Ω → ℝ := fun ω => ind ω * R ω with hg_def
  -- Integrability of f via boundedness of ind.
  have hf_int : Integrable f μ := by
    refine hq'_int.bdd_mul (c := 1) hind_meas.aestronglyMeasurable ?_
    exact Filter.Eventually.of_forall hind_le
  -- R is σ_X-measurable (hence σ_AX-meas, σ_AUX-meas).
  have hR_meas_X : Measurable[S.σ_X] R := by
    have := stronglyMeasurable_condExp (m := S.σ_X) (μ := μ)
        (f := Set.indicator {ω' | S.A ω' ≠ a} (fun _ => (1:ℝ)))
    have h1 : Measurable[S.σ_X]
        (μ[Set.indicator {ω' | S.A ω' ≠ a} (fun _ => (1:ℝ)) | S.σ_X]) := by fun_prop
    have h2 : Measurable[S.σ_X]
        (μ[Set.indicator {ω' | S.A ω' = a} (fun _ => (1:ℝ)) | S.σ_X]) := by fun_prop
    exact h1.div h2
  have hR_meas_AX : Measurable[S.σ_AX] R := hR_meas_X.mono S.σ_X_le_σ_AX le_rfl
  have hR_meas_UX : Measurable[S.σ_UX] R := hR_meas_X.mono S.σ_X_le_σ_UX le_rfl
  have hR_meas_AUX : Measurable[S.σ_AUX] R := hR_meas_X.mono S.σ_X_le_σ_AUX le_rfl
  have hR_meas : Measurable R := hR_meas_X.mono S.σ_X_le le_rfl
  -- Integrability of g: g equals ({A=a}).indicator R; combine with
  -- `integrableOn_stratumOddsRatio_arm`.
  have hR_armOn : IntegrableOn R {ω | S.A ω = a} μ :=
    integrableOn_stratumOddsRatio_arm HA a
  have hg_eq_indicator : g = ({ω | S.A ω = a}).indicator R := by
    funext ω
    by_cases h : ω ∈ {ω' | S.A ω' = a}
    · simp [g, ind, Set.indicator_of_mem h]
    · simp [g, ind, Set.indicator_of_notMem h]
  have hg_int : Integrable g μ := by
    rw [hg_eq_indicator]
    exact hR_armOn.integrable_indicator hs_meas
  -- AEStronglyMeasurable[σ_AX] g.
  have hg_aesm_AX : AEStronglyMeasurable[S.σ_AX] g μ := by fun_prop
  -- σ-finite trim for σ_AX, σ_UX, σ_AUX.
  haveI : IsFiniteMeasure (μ.trim S.σ_AX_le) := isFiniteMeasure_trim S.σ_AX_le
  haveI : SigmaFinite (μ.trim S.σ_AX_le) := inferInstance
  haveI : IsFiniteMeasure (μ.trim S.σ_UX_le) := isFiniteMeasure_trim S.σ_UX_le
  haveI : SigmaFinite (μ.trim S.σ_UX_le) := inferInstance
  haveI : IsFiniteMeasure (μ.trim S.σ_AUX_le) := isFiniteMeasure_trim S.σ_AUX_le
  haveI : SigmaFinite (μ.trim S.σ_AUX_le) := inferInstance
  haveI : IsFiniteMeasure (μ.trim S.σ_X_le) := isFiniteMeasure_trim S.σ_X_le
  haveI : SigmaFinite (μ.trim S.σ_X_le) := inferInstance
  -- ============================================================
  -- Step B: g =ᵐ[μ] μ[f | σ_AX] via the uniqueness lemma.
  -- ============================================================
  have hg_eq_CE : g =ᵐ[μ] μ[f | S.σ_AX] := by
    refine MeasureTheory.ae_eq_condExp_of_forall_setIntegral_eq S.σ_AX_le hf_int
      (fun s _ _ => hg_int.integrableOn) ?_ hg_aesm_AX
    -- Set-integral identity on σ_AX-measurable s with finite measure.
    intro s hs_meas_AX _hμs_finite
    -- Unpack s = S.AX ⁻¹' C.
    have hs_meas_mΩ : MeasurableSet s := S.σ_AX_le _ hs_meas_AX
    obtain ⟨C, hC_meas, hC_eq⟩ := hs_meas_AX
    -- Define C_a := slice of C at a, and g_X := indicator C_a (S.X ·).
    set C_a : Set γ_X := (fun x : γ_X => ((a, x) : Bool × γ_X)) ⁻¹' C with hCa_def
    have hCa_meas : MeasurableSet C_a := by
      refine (Measurable.prodMk (measurable_const : Measurable (fun _ : γ_X => a))
        measurable_id) hC_meas
    set g_X : P.Ω → ℝ := fun ω => Set.indicator C_a (fun _ => (1:ℝ)) (S.X ω)
      with hgX_def
    -- g_X is σ_X-measurable (and bounded by 1).
    have hgX_meas_X : Measurable[S.σ_X] g_X := by fun_prop
    have hgX_meas : Measurable g_X := by fun_prop
    have hgX_meas_AX : Measurable[S.σ_AX] g_X := by fun_prop
    have hgX_meas_UX : Measurable[S.σ_UX] g_X := by fun_prop
    have hgX_meas_AUX : Measurable[S.σ_AUX] g_X := by fun_prop
    have hgX_le : ∀ ω, ‖g_X ω‖ ≤ 1 := by
      intro ω
      by_cases h : S.X ω ∈ C_a
      · simp [g_X, Set.indicator_of_mem h]
      · simp [g_X, Set.indicator_of_notMem h]
    have hgX_int : Integrable g_X μ := by
      refine (integrable_const (1 : ℝ)).mono' hgX_meas.aestronglyMeasurable ?_
      exact Filter.Eventually.of_forall (by intro ω; simpa using hgX_le ω)
    -- The split identity: 1_s · ind = g_X · ind, pointwise.
    have hSplit : ∀ ω, Set.indicator s (fun _ => (1:ℝ)) ω * ind ω
        = g_X ω * ind ω := by
      intro ω
      by_cases hAa : ω ∈ {ω' | S.A ω' = a}
      · -- on {A=a}: ind = 1; LHS = 1_s ω; RHS = g_X ω.
        have hindω : ind ω = 1 := by
          simp [ind, Set.indicator_of_mem hAa]
        have hAω : S.A ω = a := hAa
        -- ω ∈ s ↔ S.AX ω ∈ C ↔ (a, S.X ω) ∈ C ↔ S.X ω ∈ C_a.
        have hs_iff : ω ∈ s ↔ S.X ω ∈ C_a := by
          rw [← hC_eq]; constructor
          · intro h
            change (S.A ω, S.X ω) ∈ C at h
            rw [hAω] at h
            exact h
          · intro h
            change (S.A ω, S.X ω) ∈ C
            rw [hAω]; exact h
        by_cases hsω : ω ∈ s
        · have hCa : S.X ω ∈ C_a := hs_iff.mp hsω
          simp [Set.indicator_of_mem hsω, Set.indicator_of_mem hCa, g_X, hindω]
        · have hCa : S.X ω ∉ C_a := fun h => hsω (hs_iff.mpr h)
          simp [Set.indicator_of_notMem hsω, Set.indicator_of_notMem hCa, g_X, hindω]
      · -- off {A=a}: ind = 0, both sides zero.
        have hindω : ind ω = 0 := by
          simp [ind, Set.indicator_of_notMem hAa]
        simp [hindω]
    -- Express ∫_s f = ∫_{A=a} g_X * q' (using Pf has ind in it).
    have h_f_split : ∫ ω in s, f ω ∂μ
        = ∫ ω in {ω | S.A ω = a}, g_X ω * q' ω ∂μ := by
      -- ∫_s f = ∫ 1_s · ind · q' (since f = ind · q')
      -- = ∫ g_X · ind · q' (Split)
      -- = ∫_{A=a} g_X · q'.
      rw [← integral_indicator (μ := μ) hs_meas_mΩ,
          ← integral_indicator (μ := μ) hs_meas]
      refine integral_congr_ae (Filter.Eventually.of_forall ?_)
      intro ω
      by_cases hsω : ω ∈ s
      · -- ω ∈ s. f = ind · q'. We have hSplit ω.
        have h1 : Set.indicator s f ω = f ω := Set.indicator_of_mem hsω f
        rw [h1]
        by_cases hAa : ω ∈ {ω' | S.A ω' = a}
        · have h2 : Set.indicator {ω | S.A ω = a} (fun ω => g_X ω * q' ω) ω
              = g_X ω * q' ω := Set.indicator_of_mem hAa _
          rw [h2]
          -- f ω = ind ω * q' ω, ind ω = 1 here.
          have hindω : ind ω = 1 := by simp [ind, Set.indicator_of_mem hAa]
          -- And 1_s ω = 1, so 1 * ind ω = g_X ω * ind ω → 1 = g_X ω
          have hSplitω := hSplit ω
          rw [Set.indicator_of_mem hsω, hindω, mul_one, mul_one] at hSplitω
          simp [f, hindω, hSplitω]
        · -- ω ∉ {A=a}: ind ω = 0, f ω = 0; RHS indicator off the set = 0.
          have h2 : Set.indicator {ω | S.A ω = a} (fun ω => g_X ω * q' ω) ω = 0 :=
            Set.indicator_of_notMem hAa _
          have hindω : ind ω = 0 := by simp [ind, Set.indicator_of_notMem hAa]
          simp [f, hindω, h2]
      · -- ω ∉ s.
        rw [Set.indicator_of_notMem hsω]
        by_cases hAa : ω ∈ {ω' | S.A ω' = a}
        · -- ω ∉ s but ω ∈ {A=a}: by hs_iff, S.X ω ∉ C_a, so g_X ω = 0.
          have hAω : S.A ω = a := hAa
          have hs_iff : ω ∈ s ↔ S.X ω ∈ C_a := by
            rw [← hC_eq]; constructor
            · intro h
              change (S.A ω, S.X ω) ∈ C at h
              rw [hAω] at h; exact h
            · intro h
              change (S.A ω, S.X ω) ∈ C
              rw [hAω]; exact h
          have hCa_not : S.X ω ∉ C_a := fun h => hsω (hs_iff.mpr h)
          have hgXω : g_X ω = 0 := by
            simp [g_X, Set.indicator_of_notMem hCa_not]
          have h2 : Set.indicator {ω | S.A ω = a} (fun ω => g_X ω * q' ω) ω
              = g_X ω * q' ω := Set.indicator_of_mem hAa _
          rw [h2, hgXω, zero_mul]
        · have h2 : Set.indicator {ω | S.A ω = a} (fun ω => g_X ω * q' ω) ω = 0 :=
            Set.indicator_of_notMem hAa _
          rw [h2]
    -- Same for g (replacing q' with R).
    have h_g_split : ∫ ω in s, g ω ∂μ
        = ∫ ω in {ω | S.A ω = a}, g_X ω * R ω ∂μ := by
      rw [← integral_indicator (μ := μ) hs_meas_mΩ,
          ← integral_indicator (μ := μ) hs_meas]
      refine integral_congr_ae (Filter.Eventually.of_forall ?_)
      intro ω
      by_cases hsω : ω ∈ s
      · have h1 : Set.indicator s g ω = g ω := Set.indicator_of_mem hsω g
        rw [h1]
        by_cases hAa : ω ∈ {ω' | S.A ω' = a}
        · have h2 : Set.indicator {ω | S.A ω = a} (fun ω => g_X ω * R ω) ω
              = g_X ω * R ω := Set.indicator_of_mem hAa _
          rw [h2]
          have hindω : ind ω = 1 := by simp [ind, Set.indicator_of_mem hAa]
          have hSplitω := hSplit ω
          rw [Set.indicator_of_mem hsω, hindω, mul_one, mul_one] at hSplitω
          simp [g, hindω, hSplitω]
        · have h2 : Set.indicator {ω | S.A ω = a} (fun ω => g_X ω * R ω) ω = 0 :=
            Set.indicator_of_notMem hAa _
          have hindω : ind ω = 0 := by simp [ind, Set.indicator_of_notMem hAa]
          simp [g, hindω, h2]
      · rw [Set.indicator_of_notMem hsω]
        by_cases hAa : ω ∈ {ω' | S.A ω' = a}
        · have hAω : S.A ω = a := hAa
          have hs_iff : ω ∈ s ↔ S.X ω ∈ C_a := by
            rw [← hC_eq]; constructor
            · intro h
              change (S.A ω, S.X ω) ∈ C at h
              rw [hAω] at h; exact h
            · intro h
              change (S.A ω, S.X ω) ∈ C
              rw [hAω]; exact h
          have hCa_not : S.X ω ∉ C_a := fun h => hsω (hs_iff.mpr h)
          have hgXω : g_X ω = 0 := by
            simp [g_X, Set.indicator_of_notMem hCa_not]
          have h2 : Set.indicator {ω | S.A ω = a} (fun ω => g_X ω * R ω) ω
              = g_X ω * R ω := Set.indicator_of_mem hAa _
          rw [h2, hgXω, zero_mul]
        · have h2 : Set.indicator {ω | S.A ω = a} (fun ω => g_X ω * R ω) ω = 0 :=
            Set.indicator_of_notMem hAa _
          rw [h2]
    -- Now reduce to: ∫_{A=a} g_X · q' = ∫_{A=a} g_X · R.
    rw [h_f_split, h_g_split]
    -- ============================================================
    -- 4-step chain.
    -- ============================================================
    -- Step 1: σ_AUX pull-out — ∫_{A=a} g_X · q' = ∫_{A=a} g_X · μ[q' | σ_AUX].
    have hStep1 : ∫ ω in {ω | S.A ω = a}, g_X ω * q' ω ∂μ
        = ∫ ω in {ω | S.A ω = a}, g_X ω * (μ[q' | S.σ_AUX]) ω ∂μ := by
      have hgXq'_int : Integrable (fun ω => g_X ω * q' ω) μ := by
        refine hq'_int.bdd_mul (c := 1) hgX_meas.aestronglyMeasurable ?_
        exact Filter.Eventually.of_forall hgX_le
      exact setIntegral_mul_condExp_of_stronglyMeasurableLeft S.σ_AUX_le
        hgX_meas_AUX.stronglyMeasurable hq'_int
        (by exact hgXq'_int) hs_in_AUX
    -- Step 2: bridge_q — μ[q' | σ_AUX] =ᵐ[restrict {A=a}] L_a.
    have hStep2 : ∫ ω in {ω | S.A ω = a}, g_X ω * (μ[q' | S.σ_AUX]) ω ∂μ
        = ∫ ω in {ω | S.A ω = a}, g_X ω * L_a ω ∂μ := by
      refine integral_congr_ae ?_
      have hbridge : (μ[q' | S.σ_AUX])
          =ᵐ[μ.restrict {ω | S.A ω = a}] L_a := HA.bridge_q a
      filter_upwards [hbridge] with ω hω
      rw [hω]
    -- Step 3: LR-swap at σ_UX — ∫_{A=a} g_X · L_a = ∫_{A=¬a} g_X.
    -- (We use the lemma in the direction ∫_{A=a'} g_X = ∫_{A=a} g_X · L, then take .symm.)
    have h_ne_eq : ({ω | S.A ω ≠ a} : Set P.Ω) = {ω | S.A ω = !a} := by
      ext ω
      change (S.A ω ≠ a) ↔ (S.A ω = !a)
      rw [Bool.eq_not_iff]
    have h_ind_eq :
        (Set.indicator ({ω' | S.A ω' = !a}) (fun _ => (1:ℝ)))
          = Set.indicator ({ω' | S.A ω' ≠ a}) (fun _ => (1:ℝ)) := by
      rw [← h_ne_eq]
    have hStep3 : ∫ ω in {ω | S.A ω = a}, g_X ω * L_a ω ∂μ
        = ∫ ω in {ω | S.A ω = !a}, g_X ω ∂μ := by
      have hSpec := HA.likelihoodRatio_swapA_spec a
      have hgXL_int : Integrable (fun ω => g_X ω * L_a ω) μ := by
        refine hLa_int.bdd_mul (c := 1) hgX_meas.aestronglyMeasurable ?_
        exact Filter.Eventually.of_forall hgX_le
      have hL2 :=
        setIntegral_eq_setIntegral_mul_of_likelihoodRatio_swap
          S.σ_UX_le {ω | S.A ω = a} {ω | S.A ω = !a}
          (S.measurable_A (measurableSet_singleton a))
          (S.measurable_A (measurableSet_singleton (!a)))
          (hgX_meas_UX.aestronglyMeasurable.mul hLa_m_UX.aestronglyMeasurable)
          hgX_meas_UX.aestronglyMeasurable
          hgX_int.integrableOn hgXL_int.integrableOn
          (by rw [h_ind_eq]; exact hSpec)
      -- hL2: ∫_{A=!a} g_X = ∫_{A=a} g_X · L_a. We want the symmetric form.
      exact hL2.symm
    -- Step 4: LR-swap at σ_X — ∫_{A=¬a} g_X = ∫_{A=a} g_X · R.
    have hStep4 : ∫ ω in {ω | S.A ω = !a}, g_X ω ∂μ
        = ∫ ω in {ω | S.A ω = a}, g_X ω * R ω ∂μ := by
      have hSpec := stratumOddsRatio_spec HA a
      have hgXR_armOn : IntegrableOn (fun ω => g_X ω * R ω) {ω | S.A ω = a} μ := by
        -- |g_X · R| ≤ |R|, so IntegrableOn from hR_armOn.
        refine hR_armOn.bdd_mul (c := 1) hgX_meas.aestronglyMeasurable.restrict ?_
        exact ae_restrict_of_ae (Filter.Eventually.of_forall hgX_le)
      have hL2 :=
        setIntegral_eq_setIntegral_mul_of_likelihoodRatio_swap
          S.σ_X_le {ω | S.A ω = a} {ω | S.A ω = !a}
          (S.measurable_A (measurableSet_singleton a))
          (S.measurable_A (measurableSet_singleton (!a)))
          (hgX_meas_X.aestronglyMeasurable.mul hR_meas_X.aestronglyMeasurable)
          hgX_meas_X.aestronglyMeasurable
          hgX_int.integrableOn hgXR_armOn
          (by rw [h_ind_eq]; exact hSpec)
      -- hL2: ∫_{A=!a} g_X = ∫_{A=a} g_X · R.
      exact hL2
    -- Combine.
    rw [hStep1, hStep2, hStep3, hStep4]
  -- ============================================================
  -- Step D: descend to restrict.
  -- ============================================================
  -- μ[f | σ_AX] =ᵐ[μ] ind · μ[q' | σ_AX] (condExp_indicator).
  have hCE_indic : μ[f | S.σ_AX] =ᵐ[μ] fun ω => ind ω * (μ[q' | S.σ_AX]) ω := by
    have h1 : μ[f | S.σ_AX]
        =ᵐ[μ] ({ω | S.A ω = a}).indicator (μ[q' | S.σ_AX]) := by
      have hf_eq : f = ({ω | S.A ω = a}).indicator q' := by
        funext ω
        by_cases h : ω ∈ {ω' | S.A ω' = a}
        · simp [f, ind, Set.indicator_of_mem h]
        · simp [f, ind, Set.indicator_of_notMem h]
      rw [hf_eq]
      exact MeasureTheory.condExp_indicator hq'_int hs_in_AX
    refine h1.trans ?_
    refine Filter.Eventually.of_forall ?_
    intro ω
    by_cases h : ω ∈ {ω' | S.A ω' = a}
    · have hindω : ind ω = 1 := by simp [ind, Set.indicator_of_mem h]
      simp [Set.indicator_of_mem h, hindω]
    · have hindω : ind ω = 0 := by simp [ind, Set.indicator_of_notMem h]
      simp [Set.indicator_of_notMem h, hindω]
  -- So g =ᵐ[μ] ind · μ[q' | σ_AX].
  have hg_eq_ind_CE : g =ᵐ[μ] fun ω => ind ω * (μ[q' | S.σ_AX]) ω :=
    hg_eq_CE.trans hCE_indic
  -- Restrict to {A=a}: ind = 1, so g ω = R ω and ind · μ[q'|σ_AX] = μ[q'|σ_AX].
  rw [Filter.EventuallyEq, ae_restrict_iff' hs_meas]
  filter_upwards [hg_eq_ind_CE] with ω hω hAa
  -- hω : g ω = ind ω * μ[q'|σ_AX] ω
  -- Goal: μ[q'|σ_AX] ω = R ω.
  have hAa_mem : ω ∈ ({ω' | S.A ω' = a} : Set P.Ω) := hAa
  have hindω : ind ω = 1 := by
    simp [ind, Set.indicator_of_mem hAa_mem]
  have hgω : g ω = R ω := by simp [g, hindω]
  rw [hgω, hindω, one_mul] at hω
  exact hω.symm

end POProximalSystem

end PO
end Causalean
