/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

import Causalean.SCM.Do.SemiGraphoid
import Causalean.Tactic.Attr

/-! # Full Conditional Independence

This file defines conditional independence on the full random state of a structural
causal model, including both observed variables and latent variables. It also
develops the semi-graphoid rules needed before projecting full-distribution Markov
statements down to observational distributions.
-/

namespace Causalean

open scoped MeasureTheory ProbabilityTheory

namespace SCM

universe uN uΩ

variable {N : Type uN} [DecidableEq N] [Fintype N]
variable {Ω : N → Type uΩ} [∀ n, MeasurableSpace (Ω n)]

-- ============================================================
-- § 1. Definition
-- ============================================================

/-- For [a population of nodes](hyp:N) that is finite and has decidable equality, [a value-space assignment to those nodes](hyp:Ω) with a measurable structure on every assigned value space, [a structural causal model](hyp:M) whose full random state is a standard Borel space, [three sets of random nodes](hyp:X) that are [each contained in the model's random-node set](hyp:hX,hY,hZ), and [a finite measure on the full random state](hyp:μ), [full conditional independence](goal) asserts that the coordinate values of the first and second node sets are conditionally independent given the σ-algebra generated by the coordinate values of the third set.

    Analogous to `ObsCondIndep` but operates on the full joint distribution
    `jointKernel M s` rather than the observational distribution `obsKernel M s`.
    The full distribution includes latent nodes, so we can condition on ALL
    parents (including latent ones).

    Used in the full local Markov property, which is the base for the
    observational global Markov via projection. -/
def FullCondIndep (M : Causalean.SCM N Ω)
    [StandardBorelSpace M.RandomValues]
    (X Y Z : Finset (SWIGNode N))
    (hX : X ⊆ M.randomVars) (hY : Y ⊆ M.randomVars)
    (hZ : Z ⊆ M.randomVars)
    (μ : MeasureTheory.Measure M.RandomValues)
    [MeasureTheory.IsFiniteMeasure μ] : Prop :=
  ProbabilityTheory.CondIndepFun
    (MeasurableSpace.comap (valuesProjection hZ) inferInstance)
    (comap_valuesProjection_le hZ)
    (valuesProjection hX)
    (valuesProjection hY)
    μ

/-- Full conditional independence of two node sets given a third, under a measure on the model's
random values, is exactly conditional independence of the two coordinate projections given the
σ-algebra generated by the conditioning projection. -/
@[causal_defs_simps]
lemma FullCondIndep_iff (M : Causalean.SCM N Ω)
    [StandardBorelSpace M.RandomValues]
    (X Y Z : Finset (SWIGNode N))
    (hX : X ⊆ M.randomVars) (hY : Y ⊆ M.randomVars)
    (hZ : Z ⊆ M.randomVars)
    (μ : MeasureTheory.Measure M.RandomValues)
    [MeasureTheory.IsFiniteMeasure μ] :
    FullCondIndep M X Y Z hX hY hZ μ ↔
      ProbabilityTheory.CondIndepFun
        (MeasurableSpace.comap (valuesProjection hZ) inferInstance)
        (comap_valuesProjection_le hZ)
        (valuesProjection hX)
        (valuesProjection hY)
        μ :=
  Iff.rfl

-- ============================================================
-- § 2. Semi-graphoid axioms for FullCondIndep
-- ============================================================

/-- Symmetry for FullCondIndep. -/
theorem fullCondIndep_symm (M : Causalean.SCM N Ω)
    [StandardBorelSpace M.RandomValues]
    {X Y Z : Finset (SWIGNode N)}
    (hX : X ⊆ M.randomVars) (hY : Y ⊆ M.randomVars) (hZ : Z ⊆ M.randomVars)
    {μ : MeasureTheory.Measure M.RandomValues} [MeasureTheory.IsFiniteMeasure μ]
    (h : FullCondIndep M X Y Z hX hY hZ μ) :
    FullCondIndep M Y X Z hY hX hZ μ := by
  simp only [causal_defs_simps] at h ⊢
  exact condIndep_valuesProjection_symm hX hY hZ h

/-- Subset right for FullCondIndep. -/
theorem fullCondIndep_subset_right (M : Causalean.SCM N Ω)
    [StandardBorelSpace M.RandomValues]
    {X Y Y' Z : Finset (SWIGNode N)}
    (hX : X ⊆ M.randomVars) (hY : Y ⊆ M.randomVars) (hY' : Y' ⊆ M.randomVars)
    (hZ : Z ⊆ M.randomVars)
    (hY'Y : Y' ⊆ Y)
    {μ : MeasureTheory.Measure M.RandomValues} [MeasureTheory.IsFiniteMeasure μ]
    (h : FullCondIndep M X Y Z hX hY hZ μ) :
    FullCondIndep M X Y' Z hX hY' hZ μ := by
  simp only [causal_defs_simps] at h ⊢
  exact condIndep_valuesProjection_subset_right hX hY hY' hZ hY'Y h

/-- Decomposition for FullCondIndep. -/
theorem fullCondIndep_decomposition (M : Causalean.SCM N Ω)
    [StandardBorelSpace M.RandomValues]
    {X Y W Z : Finset (SWIGNode N)}
    (hX : X ⊆ M.randomVars) (hYW : (Y ∪ W) ⊆ M.randomVars)
    (hZ : Z ⊆ M.randomVars)
    {μ : MeasureTheory.Measure M.RandomValues} [MeasureTheory.IsFiniteMeasure μ]
    (h : FullCondIndep M X (Y ∪ W) Z hX hYW hZ μ) :
    FullCondIndep M X Y Z hX (Finset.subset_union_left.trans hYW) hZ μ := by
  let hY : Y ⊆ M.randomVars := Finset.subset_union_left.trans hYW
  simp only [causal_defs_simps] at h ⊢
  exact condIndep_valuesProjection_decomposition hX hYW hZ h

/-- **Weak union for full conditional independence.** Let `M` be a structural causal model and
    let `μ` be a finite measure on the full random state (observed together with latent
    variables). Suppose [`X`](hyp:hX), [`Y ∪ W`](hyp:hYW), and [`Z ∪ W`](hyp:hZW) are all sets
    of `M`'s random variables, and that, under `μ`, [`X` is conditionally independent of
    `Y ∪ W` given `Z`](hyp:h). Then [`X` is conditionally independent of `Y` given
    `Z ∪ W`](goal). -/
theorem fullCondIndep_weak_union (M : Causalean.SCM N Ω)
    [StandardBorelSpace M.RandomValues]
    {X Y W Z : Finset (SWIGNode N)}
    (hX : X ⊆ M.randomVars) (hYW : (Y ∪ W) ⊆ M.randomVars)
    (hZW : (Z ∪ W) ⊆ M.randomVars)
    {μ : MeasureTheory.Measure M.RandomValues} [MeasureTheory.IsFiniteMeasure μ]
    (h : FullCondIndep M X (Y ∪ W) Z hX hYW (Finset.subset_union_left.trans hZW) μ) :
    FullCondIndep M X Y (Z ∪ W) hX (Finset.subset_union_left.trans hYW) hZW μ := by
  let hY : Y ⊆ M.randomVars := Finset.subset_union_left.trans hYW
  let hZ : Z ⊆ M.randomVars := Finset.subset_union_left.trans hZW
  simp only [causal_defs_simps] at h ⊢
  exact condIndep_valuesProjection_weak_union_axiom hX hYW hZ h

/-- **Contraction for full conditional independence.** Let `M` be a structural causal model and
    let `μ` be a finite measure on the full random state. Suppose [`X`](hyp:hX), [`Y`](hyp:hY),
    [`W`](hyp:hW), and [`Z`](hyp:hZ) are all sets of `M`'s random variables, and that, under
    `μ`, [`X` is conditionally independent of `Y` given `Z ∪ W`](hyp:h1) and [`X` is
    conditionally independent of `W` given `Z`](hyp:h2). Then [`X` is conditionally independent
    of `Y ∪ W` given `Z`](goal). -/
theorem fullCondIndep_contraction (M : Causalean.SCM N Ω)
    [StandardBorelSpace M.RandomValues]
    {X Y W Z : Finset (SWIGNode N)}
    (hX : X ⊆ M.randomVars) (hY : Y ⊆ M.randomVars)
    (hW : W ⊆ M.randomVars) (hZ : Z ⊆ M.randomVars)
    {μ : MeasureTheory.Measure M.RandomValues} [MeasureTheory.IsFiniteMeasure μ]
    (h1 : FullCondIndep M X Y (Z ∪ W) hX hY (Finset.union_subset hZ hW) μ)
    (h2 : FullCondIndep M X W Z hX hW hZ μ) :
    FullCondIndep M X (Y ∪ W) Z hX (Finset.union_subset hY hW) hZ μ := by
  let hYW : (Y ∪ W) ⊆ M.randomVars := Finset.union_subset hY hW
  let hZW : (Z ∪ W) ⊆ M.randomVars := Finset.union_subset hZ hW
  simp only [causal_defs_simps] at h1 h2 ⊢
  exact condIndep_valuesProjection_contraction_axiom hX hY hW hZ h1 h2

-- ============================================================
-- § 3. Congruence helper
-- ============================================================

/-- Transport `FullCondIndep` along a Finset equality in the first argument.
    Used in the Verma–Pearl induction to convert `{a} ∪ A'` to `insert a A'`. -/
theorem fullCondIndep_congr_left (M : Causalean.SCM N Ω)
    [StandardBorelSpace M.RandomValues]
    {X X' Y Z : Finset (SWIGNode N)} (heq : X = X')
    {hX : X ⊆ M.randomVars}
    {hY : Y ⊆ M.randomVars} {hZ : Z ⊆ M.randomVars}
    {μ : MeasureTheory.Measure M.RandomValues} [MeasureTheory.IsFiniteMeasure μ]
    (h : FullCondIndep M X Y Z hX hY hZ μ) :
    FullCondIndep M X' Y Z (heq ▸ hX) hY hZ μ := by
  subst heq; exact h

/-- Transport `FullCondIndep` along a Finset equality in the conditioning set.
    Used to align an empty conditioning set with `parents v ∩ randomVars` when
    `v` is a latent root. -/
theorem fullCondIndep_congr_right (M : Causalean.SCM N Ω)
    [StandardBorelSpace M.RandomValues]
    {X Y Z Z' : Finset (SWIGNode N)} (heq : Z = Z')
    {hX : X ⊆ M.randomVars} {hY : Y ⊆ M.randomVars}
    {hZ : Z ⊆ M.randomVars}
    {μ : MeasureTheory.Measure M.RandomValues} [MeasureTheory.IsFiniteMeasure μ]
    (h : FullCondIndep M X Y Z hX hY hZ μ) :
    FullCondIndep M X Y Z' hX hY (heq ▸ hZ) μ := by
  subst heq; exact h

/-- The empty source set is conditionally independent of anything: with `X = ∅`,
    the projection `valuesProjection ∅` is constant, so `FullCondIndep` holds
    trivially. Interprets the `nil` constructor of `OrderedLocalSG`. -/
theorem fullCondIndep_const_left (M : Causalean.SCM N Ω)
    [StandardBorelSpace M.RandomValues]
    {Y Z : Finset (SWIGNode N)} (hY : Y ⊆ M.randomVars) (hZ : Z ⊆ M.randomVars)
    {μ : MeasureTheory.Measure M.RandomValues} [MeasureTheory.IsFiniteMeasure μ] :
    FullCondIndep M ∅ Y Z (Finset.empty_subset _) hY hZ μ := by
  simp only [causal_defs_simps]
  let c : ValuesOn (∅ : Finset (SWIGNode N)) (swigΩ Ω) :=
    fun w => absurd w.property (Finset.notMem_empty _)
  have hconst : valuesProjection (Ω := swigΩ Ω) (Finset.empty_subset M.randomVars)
      = fun _ => c := by
    funext ξ w; exact absurd w.property (Finset.notMem_empty _)
  rw [hconst]
  exact ProbabilityTheory.condIndepFun_const_left c (valuesProjection hY)

end SCM

end Causalean
