/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module

public import Causalean.Mathlib.MeasureTheory.FinsetValues

/-! # Value assignments on finite sets of nodes

Value assignments on a finite set of nodes — dependent functions giving each node in the set a
value in its own measurable space — and the operations the do-calculus proofs perform on them:
restriction to a subset of nodes (measurable, compatible with composition, and generating the
σ-algebra of the retained coordinates), the measurable identification of assignments over equal
node sets, gluing two assignments into one on the union, and singleton assignments. All
declarations live in `Causalean.Mathlib.MeasureTheory.FinsetValues`; this file declares nothing
and makes them available under the `SCM.Do` path.

## Main definitions and results

* `ValuesOn`, `valuesProjection`, `measurable_valuesProjection`, `valuesProjection_comp`.
* `comap_valuesProjection_union_eq_sup` — the σ-algebra generated by the coordinates in a union
  is the join of the two coordinate σ-algebras.
* `valuesEquivOfEq`, `valuesUnionMk`, `valuesUnionMk_projection_comp`, `singletonValues`.
-/

public section
