module
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Basic
public import Causalean.Stat.Minimax.Mixture.Iid
public import Mathlib.MeasureTheory.Measure.GiryMonad
public import Mathlib.Probability.Kernel.Composition.IntegralCompProd

/-!
Arbitrary probability priors, their integral iid observation mixtures, and randomized
connected-interval length transfer.
-/

@[expose] public section

noncomputable section
open MeasureTheory ProbabilityTheory
open scoped ENNReal RealInnerProductSpace
namespace CausalSmith.Stat.DensityEffectRoughNull


/-- The law-and-version sigma-algebra is generated by measurable observation masses and
point evaluations of the two nuisance versions. -/
instance : MeasurableSpace ObsLaw :=
  MeasurableSpace.comap (fun P : ObsLaw => (P.law, P.e, P.eta)) inferInstance

/-- Finite iid sampling is a measurable probability kernel on observed laws. -/
-- @node: measurable_prior_dataLaw
@[fun_prop] lemma measurable_prior_dataLaw (n : ℕ) :
    Measurable (fun P : ObsLaw => dataLaw P n) := by
  let : ∀ P : ObsLaw, IsProbabilityMeasure (dataLaw P n) := fun P => by
    unfold dataLaw
    infer_instance
  have hlaw : Measurable (fun P : ObsLaw => P.law) :=
    measurable_fst.comp (Measurable.of_comap_le le_rfl)
  apply Measurable.measure_of_isPiSystem_of_isProbabilityMeasure
    generateFrom_pi.symm isPiSystem_pi
  rintro S ⟨s, hs, rfl⟩
  simp only [dataLaw, Measure.pi_pi]
  exact Finset.measurable_prod Finset.univ (fun i _ =>
    (Measure.measurable_coe (s := s i) (hs i (Set.mem_univ i))).comp hlaw)

/-- Observation mixture under an arbitrary prior, before independent public randomization. -/
def sampleMixture (n : ℕ) (nu : Measure ObsLaw) : Measure (Data n) :=
  nu.bind (fun P => dataLaw P n)
    -- @realizes Mixzero(integral null-prior observation mixture when nu0)
    -- @realizes Mixone(integral alternative-prior observation mixture when nu1)

/-- A finite prior is an actual finite family of laws with nonnegative weights summing to one. -/
abbrev FinitePrior := Σ k : ℕ, (Fin k → ObsLaw) ×
  {w : Fin k → ℝ≥0∞ // ∑ i : Fin k, w i = 1}
/-- Component law of a finite prior. -/
def priorLaw (ν : FinitePrior) (i : Fin ν.1) : ObsLaw := ν.2.1 i
/-- Probability weight of a finite prior. -/
def priorWeight (ν : FinitePrior) (i : Fin ν.1) : ℝ≥0∞ := ν.2.2.1 i
/-- Support predicate ignores zero-weight components. -/
def PriorSupported (ν : FinitePrior) (C : ObsLaw → Prop) : Prop :=
  ∀ i, priorWeight ν i ≠ 0 → C (priorLaw ν i)
/-- Fixed-sample observation mixture before public randomization. -/
def finiteSampleMixture (n : ℕ) (ν : FinitePrior) : Measure (Data n) :=
  ∑ i : Fin ν.1, priorWeight ν i • dataLaw (priorLaw ν i) n
/-- Uniform prior observation mixture for any finite nonempty law family. -/
def uniformSampleMixture {S : Type*} [Fintype S] [Nonempty S]
    (n : ℕ) (family : S → ObsLaw) : Measure (Data n) :=
  Causalean.Stat.Minimax.Mixture.uniformMixture (fun s => dataLaw (family s) n)

-- @env: S4
variable (nu0 nu1 : Measure ObsLaw) -- @realizes nu0(arbitrary measurable null prior)
  -- @realizes nu1(arbitrary measurable alternative prior)
variable [IsProbabilityMeasure nu0] [IsProbabilityMeasure nu1]
  -- @realizes nu0(probability normalization) @realizes nu1(probability normalization)

/-- Every subset of the reporting range has nonnegative length at most sixteen. -/
-- @node: intervalLength_mem_Icc
lemma intervalLength_mem_Icc (S : Set ℝ) (hS : S ⊆ Set.Icc 0 16) :
    intervalLength S ∈ Set.Icc 0 16 := by
  classical
  by_cases hempty : S = ∅
  · simp [intervalLength, hempty]
  · have hne : S.Nonempty := Set.nonempty_iff_ne_empty.mpr hempty
    have hlo : BddBelow S := ⟨0, fun x hx => (hS hx).1⟩
    have hhi : BddAbove S := ⟨16, fun x hx => (hS hx).2⟩
    have horder := csInf_le_csSup hne hlo hhi
    have hinf : 0 ≤ sInf S := le_csInf hne (fun x hx => (hS hx).1)
    have hsup : sSup S ≤ 16 := csSup_le hne (fun x hx => (hS hx).2)
    rw [intervalLength, if_neg hempty]
    exact ⟨sub_nonneg.mpr horder, sub_le_iff_le_add.mpr (by linarith)⟩

/-- The expected length of an admissible reporting rule is nonnegative. -/
-- @node: expectedLength_nonneg
lemma expectedLength_nonneg (P : ObsLaw) (n : ℕ) (I : IntervalRule n)
    (hRule : IsIntervalRule n I) : 0 ≤ expectedLength P n I := by
  exact integral_nonneg (fun ω => (intervalLength_mem_Icc (I ω) (hRule.1 ω).2).1)

/-- A probability prior carried by equality laws makes the worst equality length nonnegative. -/
-- @node: worstNullLength_nonneg_of_prior
lemma worstNullLength_nonneg_of_prior (n : ℕ) (nu : Measure ObsLaw)
    [IsProbabilityMeasure nu] (hnull : ∀ᵐ P ∂nu, NullModel P)
    (I : IntervalRule n) (hRule : IsIntervalRule n I) :
    0 ≤ worstNullLength n I := by
  obtain ⟨P, hP⟩ := hnull.exists
  exact Real.sSup_nonneg' ⟨expectedLength P n I, ⟨P, hP, rfl⟩,
    expectedLength_nonneg P n I hRule⟩

/-- The iid experiment as a probability kernel on observed laws. -/
-- @node: priorDataKernel
def priorDataKernel (n : ℕ) : Kernel ObsLaw (Data n) where
  toFun P := dataLaw P n
  measurable' := measurable_prior_dataLaw n

/-- Each iid experiment is normalized. -/
-- @node: priorDataKernel_markov
instance priorDataKernel_markov (n : ℕ) : IsMarkovKernel (priorDataKernel n) where
  isProbabilityMeasure P := by
    change IsProbabilityMeasure (dataLaw P n)
    unfold dataLaw
    infer_instance

/-- The public randomization is a probability law. -/
-- @node: unitVolume_probability
instance unitVolume_probability : IsProbabilityMeasure unitVolume := ⟨by simp [unitVolume]⟩

/-- Add an independent public randomization coordinate. -/
-- @node: publicRandomizationKernel
def publicRandomizationKernel (n : ℕ) : Kernel (Data n) (SampleSpace n) :=
  Kernel.id.prod (Kernel.const (Data n) unitVolume)

/-- The complete randomized experiment kernel. -/
-- @node: priorSampleKernel
def priorSampleKernel (n : ℕ) : Kernel ObsLaw (SampleSpace n) :=
  (priorDataKernel n).prod (Kernel.const ObsLaw unitVolume)

/-- Independent randomization preserves normalization. -/
-- @node: publicRandomizationKernel_markov
instance publicRandomizationKernel_markov (n : ℕ) :
    IsMarkovKernel (publicRandomizationKernel n) := by
  unfold publicRandomizationKernel
  infer_instance

/-- The randomized experiment is normalized. -/
-- @node: priorSampleKernel_markov
instance priorSampleKernel_markov (n : ℕ) : IsMarkovKernel (priorSampleKernel n) := by
  unfold priorSampleKernel
  infer_instance

/-- The kernel agrees with the frozen sampling law. -/
-- @node: priorSampleKernel_apply
lemma priorSampleKernel_apply (n : ℕ) (P : ObsLaw) :
    priorSampleKernel n P = sampleLaw P n := by
  unfold priorSampleKernel
  rw [Kernel.prod_apply]
  rfl

/-- The frozen sampling law is a probability measure. -/
-- @node: sampleLaw_probability
instance sampleLaw_probability (P : ObsLaw) (n : ℕ) : IsProbabilityMeasure (sampleLaw P n) := by
  unfold sampleLaw dataLaw
  infer_instance

/-- Mix the full randomized experiment under an arbitrary prior. -/
-- @node: randomizedSampleMixture
def randomizedSampleMixture (n : ℕ) (nu : Measure ObsLaw) : Measure (SampleSpace n) :=
  priorSampleKernel n ∘ₘ nu

/-- The randomized mixture is a probability measure. -/
-- @node: randomizedSampleMixture_probability
instance randomizedSampleMixture_probability (n : ℕ) (nu : Measure ObsLaw)
    [IsProbabilityMeasure nu] : IsProbabilityMeasure (randomizedSampleMixture n nu) := by
  unfold randomizedSampleMixture
  infer_instance

/-- Mixing and the common public randomization channel commute. -/
-- @node: randomizedSampleMixture_channel
lemma randomizedSampleMixture_channel (n : ℕ) (nu : Measure ObsLaw) :
    randomizedSampleMixture n nu = publicRandomizationKernel n ∘ₘ sampleMixture n nu := by
  change priorSampleKernel n ∘ₘ nu =
    publicRandomizationKernel n ∘ₘ (priorDataKernel n ∘ₘ nu)
  rw [Measure.comp_assoc]
  congr 1
  simp [publicRandomizationKernel, priorSampleKernel, Kernel.prod_const_comp]

/-- Public randomization cannot increase the mixture total variation. -/
-- @node: randomizedSampleMixture_tv
lemma randomizedSampleMixture_tv (n : ℕ) (nu0 nu1 : Measure ObsLaw)
    [IsProbabilityMeasure nu0] [IsProbabilityMeasure nu1] :
    Causalean.Stat.tvDist (randomizedSampleMixture n nu0) (randomizedSampleMixture n nu1) ≤
      Causalean.Stat.tvDist (sampleMixture n nu0) (sampleMixture n nu1) := by
  let : IsProbabilityMeasure (sampleMixture n nu0) :=
    show IsProbabilityMeasure (priorDataKernel n ∘ₘ nu0) from inferInstance
  let : IsProbabilityMeasure (sampleMixture n nu1) :=
    show IsProbabilityMeasure (priorDataKernel n ∘ₘ nu1) from inferInstance
  rw [randomizedSampleMixture_channel, randomizedSampleMixture_channel]
  exact Causalean.Stat.tvDist_bind_le _ _ _

/-- Mixture event probabilities are prior averages of sampling probabilities. -/
-- @node: randomizedSampleMixture_real
lemma randomizedSampleMixture_real (n : ℕ) (nu : Measure ObsLaw)
    [IsProbabilityMeasure nu] (E : Set (SampleSpace n)) (hE : MeasurableSet E) :
    (randomizedSampleMixture n nu).real E = ∫ P, (sampleLaw P n).real E ∂nu := by
  rw [measureReal_def, randomizedSampleMixture, Measure.bind_apply hE
    (Kernel.aemeasurable _), ← integral_toReal
    ((priorSampleKernel n).measurable_coe hE).aemeasurable]
  · simp only [priorSampleKernel_apply, measureReal_def]
  · filter_upwards with P
    exact measure_lt_top (priorSampleKernel n P) E

/-- For a bounded connected interval, endpoint length equals its Lebesgue mass. -/
-- @node: intervalLength_eq_volume
lemma intervalLength_eq_volume (S : Set ℝ) (hconn : Set.OrdConnected S)
    (hS : S ⊆ Set.Icc 0 16) : intervalLength S = (volume S).toReal := by
  by_cases hempty : S = ∅
  · simp [hempty, intervalLength]
  have hne : S.Nonempty := Set.nonempty_iff_ne_empty.mpr hempty
  have hlo : BddBelow S := ⟨0, fun y hy => (hS hy).1⟩
  have hhi : BddAbove S := ⟨16, fun y hy => (hS hy).2⟩
  have hupper : S ⊆ Set.Icc (sInf S) (sSup S) := by
    intro y hy
    exact ⟨csInf_le hlo hy, le_csSup hhi hy⟩
  have hlower : Set.Ioo (sInf S) (sSup S) ⊆ S := by
    intro y hy
    obtain ⟨x, hx, hxy⟩ := exists_lt_of_csInf_lt hne hy.1
    obtain ⟨z, hz, hyz⟩ := exists_lt_of_lt_csSup hne hy.2
    exact hconn.out hx hz ⟨hxy.le, hyz.le⟩
  have hmass : volume S = ENNReal.ofReal (sSup S - sInf S) := by
    apply le_antisymm
    · simpa only [Real.volume_Icc] using
        (measure_mono hupper : volume S ≤ volume (Set.Icc (sInf S) (sSup S)))
    · simpa only [Real.volume_Ioo] using
        (measure_mono hlower : volume (Set.Ioo (sInf S) (sSup S)) ≤ volume S)
  rw [hmass, ENNReal.toReal_ofReal (sub_nonneg.mpr (csInf_le_csSup hne hlo hhi))]
  exact if_neg hempty

/-- The measurable inclusion graph makes reporting length measurable, including singletons. -/
-- @node: measurable_intervalLength
@[fun_prop] lemma measurable_intervalLength (n : ℕ) (I : IntervalRule n)
    (hRule : IsIntervalRule n I) : Measurable (fun w => intervalLength (I w)) := by
  have hm := (measurable_measure_prodMk_left (ν := (volume : Measure ℝ)) hRule.2).ennreal_toReal
  have heq : (fun w : SampleSpace n => (volume (Prod.mk w ⁻¹'
      {p : SampleSpace n × ℝ | p.2 ∈ I p.1})).toReal) =
      (fun w => intervalLength (I w)) := by
    funext w
    exact (intervalLength_eq_volume (I w) (hRule.1 w).1 (hRule.1 w).2).symm
  rwa [heq] at hm

/-- Bounded reporting lengths are integrable under every finite law. -/
-- @node: intervalLength_integrable
lemma intervalLength_integrable (n : ℕ) (I : IntervalRule n) (hRule : IsIntervalRule n I)
    (hLength : Measurable (fun w => intervalLength (I w)))
    (mu : Measure (SampleSpace n)) [IsFiniteMeasure mu] :
    Integrable (fun w => intervalLength (I w)) mu := by
  exact ⟨hLength.aestronglyMeasurable, HasFiniteIntegral.of_mem_Icc 0 16
    (Filter.Eventually.of_forall fun w => intervalLength_mem_Icc (I w) (hRule.1 w).2)⟩

/-- The expectation under the mixture is the prior average of expected lengths. -/
-- @node: randomizedSampleMixture_expectedLength
lemma randomizedSampleMixture_expectedLength (n : ℕ) (nu : Measure ObsLaw)
    [IsProbabilityMeasure nu] (I : IntervalRule n) (hRule : IsIntervalRule n I)
    (hLength : Measurable (fun w => intervalLength (I w))) :
    (∫ w, intervalLength (I w) ∂randomizedSampleMixture n nu) =
      ∫ P, expectedLength P n I ∂nu := by
  have hi := intervalLength_integrable n I hRule hLength (randomizedSampleMixture n nu)
  rw [randomizedSampleMixture, Measure.comp_eq_comp_const_apply] at hi ⊢
  rw [Kernel.integral_comp hi]
  simp only [Kernel.const_apply, priorSampleKernel_apply, expectedLength]

/-- Equality laws have zero identifying functional. -/
-- @node: NullModel_Psi_zero
lemma NullModel_Psi_zero (P : ObsLaw) (hP : NullModel P) : Psi P = 0 := by
  unfold Psi l2Squared
  have hz : (fun y => (delta P y) ^ 2) =ᵐ[unitVolume] (fun _ => (0 : ℝ)) := by
    filter_upwards [ae_restrict_mem measurableSet_Icc] with y hy
    simp [hP.2 y hy]
  rw [integral_congr_ae hz]
  simp

/-- An interval containing zero and a separated point must have at least that length. -/
-- @node: intervalLength_ge_of_mem
lemma intervalLength_ge_of_mem (S : Set ℝ) (hS : S ⊆ Set.Icc 0 16)
    (hzero : 0 ∈ S) (x : ℝ) (hx : x ∈ S) : x ≤ intervalLength S := by
  have hlo : BddBelow S := ⟨0, fun y hy => (hS hy).1⟩
  have hhi : BddAbove S := ⟨16, fun y hy => (hS hy).2⟩
  have hi := csInf_le hlo hzero
  have hs := le_csSup hhi hx
  rw [intervalLength, if_neg (Set.nonempty_iff_ne_empty.mp ⟨0, hzero⟩)]
  linarith

/-- A mixture inherits a uniform almost-everywhere lower bound on event probabilities. -/
-- @node: randomizedSampleMixture_event_lower
lemma randomizedSampleMixture_event_lower (n : ℕ) (nu : Measure ObsLaw)
    [IsProbabilityMeasure nu] (E : Set (SampleSpace n)) (hE : MeasurableSet E)
    (c : ℝ) (hc : ∀ᵐ P ∂nu, c ≤ (sampleLaw P n).real E) :
    c ≤ (randomizedSampleMixture n nu).real E := by
  rw [randomizedSampleMixture_real n nu E hE]
  have hm : Measurable (fun P => (sampleLaw P n).real E) := by
    simpa only [priorSampleKernel_apply, measureReal_def] using
      ((priorSampleKernel n).measurable_coe hE).ennreal_toReal
  have hi : Integrable (fun P => (sampleLaw P n).real E) nu :=
    ⟨hm.aestronglyMeasurable, HasFiniteIntegral.of_mem_Icc 0 1
      (Filter.Eventually.of_forall fun P => ⟨measureReal_nonneg,
        by simpa using measureReal_mono (μ := sampleLaw P n) (Set.subset_univ E)⟩)⟩
  simpa using integral_mono_ae (integrable_const c) hi hc

/-- Pointwise range bounds give a uniform upper bound on expected reporting length. -/
-- @node: expectedLength_le_sixteen
lemma expectedLength_le_sixteen (n : ℕ) (I : IntervalRule n) (hRule : IsIntervalRule n I)
    (hLength : Measurable (fun w => intervalLength (I w))) (P : ObsLaw) :
    expectedLength P n I ≤ 16 := by
  have hi := intervalLength_integrable n I hRule hLength (sampleLaw P n)
  simpa [expectedLength] using integral_mono_ae hi (integrable_const (16 : ℝ))
    (Filter.Eventually.of_forall fun w => (intervalLength_mem_Icc (I w) (hRule.1 w).2).2)

/-- A prior average over equality laws is bounded by their worst expected length. -/
-- @node: randomizedSampleMixture_length_le_worst
lemma randomizedSampleMixture_length_le_worst (n : ℕ) (nu : Measure ObsLaw)
    [IsProbabilityMeasure nu] (hnull : ∀ᵐ P ∂nu, NullModel P)
    (I : IntervalRule n) (hRule : IsIntervalRule n I)
    (hLength : Measurable (fun w => intervalLength (I w))) :
    (∫ w, intervalLength (I w) ∂randomizedSampleMixture n nu) ≤ worstNullLength n I := by
  rw [randomizedSampleMixture_expectedLength n nu I hRule hLength]
  have hi : Integrable (fun P => expectedLength P n I) nu := by
    have hmix := intervalLength_integrable n I hRule hLength (randomizedSampleMixture n nu)
    have hint := Measure.integrable_integral_norm_of_integrable_comp hmix
    have heq : (fun P => ∫ w, ‖intervalLength (I w)‖ ∂priorSampleKernel n P) =
        (fun P => expectedLength P n I) := by
      funext P
      simp only [priorSampleKernel_apply, expectedLength]
      apply integral_congr_ae
      filter_upwards with w
      exact Real.norm_of_nonneg (intervalLength_mem_Icc (I w) (hRule.1 w).2).1
    rwa [heq] at hint
  have hb : BddAbove {r : ℝ | ∃ P : ObsLaw, NullModel P ∧ r = expectedLength P n I} := by
    refine ⟨16, ?_⟩
    rintro r ⟨P, hP, rfl⟩
    exact expectedLength_le_sixteen n I hRule hLength P
  have hle : ∀ᵐ P ∂nu, expectedLength P n I ≤ worstNullLength n I := by
    filter_upwards [hnull] with P hP
    exact le_csSup hb ⟨P, hP, rfl⟩
  simpa using integral_mono_ae hi (integrable_const (worstNullLength n I)) hle

/-- An event on which length exceeds rho contributes rho times its probability. -/
-- @node: intervalLength_integral_lower
lemma intervalLength_integral_lower (n : ℕ) (I : IntervalRule n) (hRule : IsIntervalRule n I)
    (hLength : Measurable (fun w => intervalLength (I w)))
    (mu : Measure (SampleSpace n)) [IsProbabilityMeasure mu]
    (rho : ℝ) (hrho : 0 ≤ rho) :
    rho * mu.real {w | rho ≤ intervalLength (I w)} ≤ ∫ w, intervalLength (I w) ∂mu := by
  classical
  let E : Set (SampleSpace n) := {w | rho ≤ intervalLength (I w)}
  have hE : MeasurableSet E := measurableSet_le measurable_const hLength
  have hi := intervalLength_integrable n I hRule hLength mu
  have hmono : E.indicator (fun _ => rho) ≤ fun w => intervalLength (I w) := by
    intro w
    by_cases hw : w ∈ E
    · simpa only [Set.indicator_of_mem hw] using (show rho ≤ intervalLength (I w) from hw)
    · simp only [Set.indicator_of_notMem hw]
      exact (intervalLength_mem_Icc (I w) (hRule.1 w).2).1
  have h := integral_mono ((integrable_const rho).indicator hE) hi hmono
  simpa only [integral_indicator hE, setIntegral_const, smul_eq_mul, mul_comm] using h

-- @node: lem:mixture-length-transfer
/-- Honest connected intervals must bridge zero and alternative energy on the overlap
of the actual observation mixtures, even with independent public randomization. -/
lemma mixture_length_transfer (n : ℕ) (nu0 nu1 : Measure ObsLaw)
    [IsProbabilityMeasure nu0] [IsProbabilityMeasure nu1] (rho alpha : ℝ)
    (hrho : rho ∈ Set.Ioc 0 16) -- @realizes rho(positive separation at most 16)
    (halpha : alpha ∈ Set.Ico 0 1) -- @realizes alpha(nonnegative error bound below one)
    (hnull : ∀ᵐ P ∂nu0, NullModel P) -- @realizes nu0(full mass on equality laws)
    (halt : ∀ᵐ P ∂nu1, Model P ∧ rho ≤ Psi P) -- @realizes nu1(full mass on separated model laws)
    (htv : Causalean.Stat.tvDist (sampleMixture n nu0) (sampleMixture n nu1) ≤ alpha)
    (I : IntervalRule n) (hRule : IsIntervalRule n I) (hHonest : IsHonest n I)
    (sampler : ObsLaw → Measure (SampleSpace n))
    (hSampling : ∀ P, SamplingLaw P n (sampler P)) :
    rho * (4 / 5 - alpha) ≤ worstNullLength n I := by
  have hLength := measurable_intervalLength n I hRule
  by_cases hsmall : alpha < 4 / 5
  · classical
    let E : Set (SampleSpace n) := {w | rho ≤ intervalLength (I w)}
    let F : Set (SampleSpace n) := {w | 0 ∉ I w}
    have hE : MeasurableSet E := measurableSet_le measurable_const hLength
    have hzero : MeasurableSet {w : SampleSpace n | 0 ∈ I w} := by
      exact hRule.2.preimage (by fun_prop : Measurable (fun w : SampleSpace n => (w, (0 : ℝ))))
    have hF : MeasurableSet F := hzero.compl
    have hnullcov : (9 / 10 : ℝ) ≤ (randomizedSampleMixture n nu0).real Fᶜ := by
      apply randomizedSampleMixture_event_lower n nu0 Fᶜ hF.compl
      filter_upwards [hnull] with P hP
      have hh := hHonest P hP.1
      simpa only [coverage, NullModel_Psi_zero P hP, F, Set.compl_ofPred, not_not] using hh
    have haltcov : (9 / 10 : ℝ) ≤ (randomizedSampleMixture n nu1).real (F ∪ E) := by
      apply randomizedSampleMixture_event_lower n nu1 (F ∪ E) (hF.union hE)
      filter_upwards [halt] with P hP
      apply (hHonest P hP.1).trans
      apply measureReal_mono (h₂ := measure_ne_top _ _)
      intro w hw
      by_cases hz : 0 ∈ I w
      · exact Or.inr (hP.2.trans (intervalLength_ge_of_mem (I w) (hRule.1 w).2 hz
          (Psi P) hw))
      · exact Or.inl hz
    have hgap := (Causalean.Stat.measureReal_sub_le_tvDist
      (μ := randomizedSampleMixture n nu0) (ν := randomizedSampleMixture n nu1)
      (hF.union hE)).trans ((randomizedSampleMixture_tv n nu0 nu1).trans htv)
    have hFmass : (randomizedSampleMixture n nu0).real F ≤ 1 / 10 := by
      have hc := measureReal_compl (μ := randomizedSampleMixture n nu0) hF
      rw [probReal_univ] at hc
      linarith
    have hunion := measureReal_union_le (μ := randomizedSampleMixture n nu0) F E
    have hEmass : 4 / 5 - alpha ≤ (randomizedSampleMixture n nu0).real E := by
      linarith
    calc
      rho * (4 / 5 - alpha) ≤ rho * (randomizedSampleMixture n nu0).real E :=
        mul_le_mul_of_nonneg_left hEmass hrho.1.le
      _ ≤ ∫ w, intervalLength (I w) ∂randomizedSampleMixture n nu0 :=
        intervalLength_integral_lower n I hRule hLength _ rho hrho.1.le
      _ ≤ worstNullLength n I :=
        randomizedSampleMixture_length_le_worst n nu0 hnull I hRule hLength
  · exact (mul_nonpos_of_nonneg_of_nonpos hrho.1.le
      (sub_nonpos.mpr (le_of_not_gt hsmall))).trans
      (worstNullLength_nonneg_of_prior n nu0 hnull I hRule)

end CausalSmith.Stat.DensityEffectRoughNull
