import CausalSmith.Experimentation.EXP_MultiarmSecondorderMinimaxFrontier_Research.Basic
import CausalSmith.Experimentation.EXP_MultiarmSecondorderMinimaxFrontier_Research.Helpers
import CausalSmith.Experimentation.EXP_MultiarmSecondorderMinimaxFrontier_Research.T_exact_response_type_game
import CausalSmith.Experimentation.EXP_MultiarmSecondorderMinimaxFrontier_Research.T_multiarm_strict_extension
import CausalSmith.Experimentation.EXP_MultiarmSecondorderMinimaxFrontier_Research.T_first_order_saddle
import CausalSmith.Experimentation.EXP_MultiarmSecondorderMinimaxFrontier_Research.T_k3_lp_certificate
import CausalSmith.Experimentation.EXP_MultiarmSecondorderMinimaxFrontier_Research.T_k3_scalar_score_not_minimax_preserving
import CausalSmith.Experimentation.EXP_MultiarmSecondorderMinimaxFrontier_Research.T_coarse_two_arm_minimax_lower
import CausalSmith.Experimentation.EXP_MultiarmSecondorderMinimaxFrontier_Research.T_embedded_two_arm_converse
import CausalSmith.Experimentation.EXP_MultiarmSecondorderMinimaxFrontier_Research.T_universal_second_order_rate
import CausalSmith.Experimentation.EXP_MultiarmSecondorderMinimaxFrontier_Research.T_rational_contrast_grid_certificate_sandwich
import CausalSmith.Experimentation.EXP_MultiarmSecondorderMinimaxFrontier_Research.T_contrast_risk_continuity
import CausalSmith.Experimentation.EXP_MultiarmSecondorderMinimaxFrontier_Research.T_real_contrast_grid_certificate_transfer
import CausalSmith.Experimentation.EXP_MultiarmSecondorderMinimaxFrontier_Research.T_k3_grid_certificate_sandwich
import CausalSmith.Experimentation.EXP_MultiarmSecondorderMinimaxFrontier_Research.T_second_order_rate_and_certificate_frontier
import CausalSmith.Experimentation.EXP_MultiarmSecondorderMinimaxFrontier_Research.T_attainment_and_k3_certified_converse

/-! Root barrel for the paper-wide multi-arm second-order minimax scaffold. -/
