/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import Causalean.Mathlib.MeasureTheory.ConditionalExpectationTransport
public import Causalean.Mathlib.Probability.Independence.Conditional
public import Causalean.PO.ID.Partial.Sensitivity.MSM.Realization

/-! # Full-data models compatible with an observed marginal sensitivity model

This file defines the arbitrary full-data models used in the converse half of
MSM sharpness.  A compatible model lives on its own standard-Borel probability
space, reproduces the observed `(X,Z,Z·Y)` law, satisfies latent
unconfoundedness given `(X,U)`, and obeys Tan's odds restriction with uniform
two-sided complete-propensity overlap.

It also constructs the conditional propensity given `(X,Y(1))`, proves the
conditional-independence bridge identifying it with the corresponding
conditional treatment probability, and factors it measurably through the pair
`(X,Y(1))`.
-/

@[expose] public section

open Causalean.Mathlib.Probability.Independence.Conditional

namespace Causalean
namespace PO

open MeasureTheory ProbabilityTheory

namespace POBackdoorSystem

universe uM uU

variable {P : POSystem} {γ : Type*} [MeasurableSpace γ]
variable (S : POBackdoorSystem P γ)

/-- The [observed propensity](hyp:S) [has a measurable factor through the factual
covariate](goal). -/
theorem exists_propensityFactor :
    ∃ eX : γ → ℝ, Measurable eX ∧ S.propScore true = eX ∘ S.factualX := by
  have hprop := S.measurable_propScore_sigmaX true
  rw [POBackdoorSystem.sigmaX] at hprop
  exact hprop.exists_eq_measurable_comp

/-- Given [an observed backdoor system](hyp:S), the [measurable propensity as a function of
the covariate value](goal) is a Doob--Dynkin factor of the observed conditional treatment
probability through the factual covariate. -/
noncomputable def propensityFactor : γ → ℝ :=
  Classical.choose (exists_propensityFactor S)

/-- The [covariate-level propensity factor](hyp:S) is [measurable](goal). -/
@[fun_prop]
theorem measurable_propensityFactor : Measurable S.propensityFactor :=
  (Classical.choose_spec (exists_propensityFactor S)).1

/-- The [observed propensity](hyp:S) [equals its covariate-level factor composed with the
factual covariate](goal). -/
theorem propScore_eq_propensityFactor_comp :
    S.propScore true = S.propensityFactor ∘ S.factualX :=
  (Classical.choose_spec (exists_propensityFactor S)).2

/-- For [an observed backdoor system](hyp:S) and [sensitivity level](hyp:Λ), an
MSM-compatible full-data model consists of its own standard-Borel probability space,
measurable `X,U,Z,Y(1)`, a complete propensity equal to the conditional treatment probability
given `(X,U)`, latent unconfoundedness, uniform complete overlap, Tan's odds bound, equality of
the observable record law, and an integrable treated potential outcome. -/
structure MSMDataCompatible (Λ : ℝ) where
  Ω : Type uM
  [measurableSpace : MeasurableSpace Ω]
  [standardBorelSpace : StandardBorelSpace Ω]
  UType : Type uU
  [measurableSpaceU : MeasurableSpace UType]
  Q : Measure Ω
  [isProbabilityMeasure : IsProbabilityMeasure Q]
  X : Ω → γ
  U : Ω → UType
  Z : Ω → Bool
  Y1 : Ω → ℝ
  completePropensity : Ω → ℝ
  measurable_X : Measurable X
  measurable_U : Measurable U
  measurable_Z : Measurable Z
  measurable_Y1 : Measurable Y1
  propensity_eq :
    completePropensity =
      Q[fun ω => if Z ω then (1 : ℝ) else 0 |
        MeasurableSpace.comap X inferInstance ⊔
          MeasurableSpace.comap U inferInstance]
  latentUnconfounded :
    CondIndepFun
      (MeasurableSpace.comap X inferInstance ⊔
        MeasurableSpace.comap U inferInstance)
      (sup_le measurable_X.comap_le measurable_U.comap_le) Z Y1 Q
  completeOverlap :
    ∃ ε : ℝ, 0 < ε ∧
      ∀ᵐ ω ∂Q, ε ≤ completePropensity ω ∧ completePropensity ω ≤ 1 - ε
  completeOdds :
    ∀ᵐ ω ∂Q,
      1 / Λ ≤ OR (completePropensity ω) (S.propensityFactor (X ω)) ∧
        OR (completePropensity ω) (S.propensityFactor (X ω)) ≤ Λ
  observedLaw :
    Q.map (fun ω => ((X ω, Z ω), if Z ω then Y1 ω else 0)) =
      P.μ.map S.factualObservedRecord
  integrable_Y1 : Integrable Y1 Q

attribute [instance] MSMDataCompatible.measurableSpace
  MSMDataCompatible.standardBorelSpace MSMDataCompatible.measurableSpaceU
  MSMDataCompatible.isProbabilityMeasure

namespace MSMDataCompatible

variable {S : POBackdoorSystem P γ} {Λ : ℝ}
variable (M : MSMDataCompatible S Λ)

/-- For [a compatible model](hyp:M), the [σ-algebra generated by its covariate and latent
variable](goal) is `σ(X,U)`. -/
noncomputable def sigmaXU : MeasurableSpace M.Ω :=
  MeasurableSpace.comap M.X inferInstance ⊔
    MeasurableSpace.comap M.U inferInstance

/-- The [latent-information σ-algebra](hyp:M) is [coarser than the ambient σ-algebra](goal). -/
theorem sigmaXU_le : M.sigmaXU ≤ (inferInstance : MeasurableSpace M.Ω) :=
  sup_le M.measurable_X.comap_le M.measurable_U.comap_le

/-- For [a compatible model](hyp:M), the [σ-algebra generated by its covariate and treated
potential outcome](goal) is `σ(X,Y(1))`. -/
noncomputable def sigmaXY1 : MeasurableSpace M.Ω :=
  MeasurableSpace.comap M.X inferInstance ⊔
    MeasurableSpace.comap M.Y1 inferInstance

/-- The [covariate--potential-outcome σ-algebra](hyp:M) is [coarser than the ambient
σ-algebra](goal). -/
theorem sigmaXY1_le : M.sigmaXY1 ≤ (inferInstance : MeasurableSpace M.Ω) :=
  sup_le M.measurable_X.comap_le M.measurable_Y1.comap_le

/-- For [a compatible model](hyp:M), the [treated-arm indicator](goal) is one exactly when
the model treatment is true. -/
def treatmentIndicator : M.Ω → ℝ := fun ω => if M.Z ω then 1 else 0

/-- The [treated-arm indicator](hyp:M) is [measurable](goal). -/
@[fun_prop]
theorem measurable_treatmentIndicator : Measurable M.treatmentIndicator := by
  unfold treatmentIndicator
  exact Measurable.ite (M.measurable_Z (measurableSet_singleton true))
    measurable_const measurable_const

/-- The [treated-arm indicator](hyp:M) is [integrable](goal). -/
@[fun_prop]
theorem integrable_treatmentIndicator : Integrable M.treatmentIndicator M.Q := by
  apply Integrable.of_bound M.measurable_treatmentIndicator.aestronglyMeasurable 1
  exact ae_of_all _ fun ω => by
    simp only [treatmentIndicator]
    split <;> simp

/-- For [a compatible model](hyp:M), the [complete propensity conditioned further down to
`σ(X,Y(1))`](goal) is the conditional expectation of `e(X,U)` given that σ-algebra. -/
noncomputable def xyPropensity : M.Ω → ℝ :=
  M.Q[M.completePropensity | M.sigmaXY1]

/-- The [complete propensity](hyp:M) is [integrable](goal). -/
@[fun_prop]
theorem integrable_completePropensity : Integrable M.completePropensity M.Q := by
  rw [M.propensity_eq]
  exact integrable_condExp

/-- **Latent-unconfoundedness bridge.** In [a compatible model](hyp:M), [the conditional
treatment probability given `(X,Y(1))` equals the conditional expectation of the complete
propensity `e(X,U)` given `(X,Y(1))`](goal). -/
theorem condExp_treatmentIndicator_eq_xyPropensity :
    M.Q[M.treatmentIndicator | M.sigmaXY1] =ᵐ[M.Q] M.xyPropensity := by
  let mFull : MeasurableSpace M.Ω :=
    M.sigmaXU ⊔ MeasurableSpace.comap M.Y1 inferInstance
  have hmFull : mFull ≤ M.measurableSpace :=
    sup_le M.sigmaXU_le M.measurable_Y1.comap_le
  have hXYFull : M.sigmaXY1 ≤ mFull := by
    unfold sigmaXY1 mFull sigmaXU
    exact sup_le (le_trans le_sup_left le_sup_left) le_sup_right
  have hdrop :
      M.Q[M.treatmentIndicator | mFull] =ᵐ[M.Q]
        M.Q[M.treatmentIndicator | M.sigmaXU] := by
    let mark : Bool → ℝ := fun z => if z then 1 else 0
    have hmark : Measurable mark := by fun_prop
    have htreat : M.treatmentIndicator = mark ∘ M.Z := by rfl
    rw [htreat]
    exact condExp_sup_comap_eq_of_condIndep M.sigmaXU_le
      M.measurable_Y1 M.measurable_Z M.latentUnconfounded
      hmark M.integrable_treatmentIndicator
  have htower :
      M.Q[M.treatmentIndicator | M.sigmaXY1] =ᵐ[M.Q]
        M.Q[M.Q[M.treatmentIndicator | mFull] | M.sigmaXY1] :=
    (condExp_condExp_of_le (μ := M.Q) (f := M.treatmentIndicator)
      hXYFull hmFull).symm
  have hinner :
      M.Q[M.Q[M.treatmentIndicator | mFull] | M.sigmaXY1] =ᵐ[M.Q]
        M.Q[M.completePropensity | M.sigmaXY1] := by
    apply condExp_congr_ae
    refine hdrop.trans ?_
    rw [M.propensity_eq]
    rfl
  exact htower.trans hinner

/-- The [conditional propensity given `(X,Y(1))`](hyp:M) [has a measurable factor through
the pair `(X,Y(1))`](goal). -/
theorem exists_xyPropensityFactor :
    ∃ g : γ × ℝ → ℝ, Measurable g ∧
      M.xyPropensity = g ∘ fun ω => (M.X ω, M.Y1 ω) := by
  have hstrong : StronglyMeasurable[M.sigmaXY1] M.xyPropensity :=
    stronglyMeasurable_condExp
  unfold sigmaXY1 at hstrong
  rw [← MeasurableSpace.comap_prodMk M.X M.Y1] at hstrong
  exact Mathlib.MeasureTheory.exists_measurable_real_comp_of_stronglyMeasurable_comap hstrong

/-- Given [a compatible model](hyp:M), the [measurable `(X,Y(1))`-level propensity
factor](goal) is a Doob--Dynkin representative of its conditional propensity. -/
noncomputable def xyPropensityFactor : γ × ℝ → ℝ :=
  Classical.choose (exists_xyPropensityFactor M)

/-- The [`(X,Y(1))`-level propensity factor](hyp:M) is [measurable](goal). -/
@[fun_prop]
theorem measurable_xyPropensityFactor : Measurable M.xyPropensityFactor :=
  (Classical.choose_spec (exists_xyPropensityFactor M)).1

/-- The [conditional propensity given `(X,Y(1))`](hyp:M) [equals its measurable factor
evaluated at `(X,Y(1))`](goal). -/
theorem xyPropensity_eq_factor_comp :
    M.xyPropensity = M.xyPropensityFactor ∘ fun ω => (M.X ω, M.Y1 ω) :=
  (Classical.choose_spec (exists_xyPropensityFactor M)).2

/-- For [a compatible model](hyp:M) at [a full-data unit](hyp:ω), the [observable record](goal)
contains its covariate, treatment, and treated observed outcome `Z·Y(1)`. -/
noncomputable def observedRecord (ω : M.Ω) : (γ × Bool) × ℝ :=
  ((M.X ω, M.Z ω), if M.Z ω then M.Y1 ω else 0)

/-- The [observable-record map](hyp:M) is [measurable](goal). -/
@[fun_prop]
theorem measurable_observedRecord : Measurable M.observedRecord := by
  unfold observedRecord
  exact (M.measurable_X.prodMk M.measurable_Z).prodMk
    (Measurable.ite (M.measurable_Z (measurableSet_singleton true))
      M.measurable_Y1 measurable_const)

/-- The [mean of the treated potential outcome](hyp:M) is the [full-data target](goal). -/
noncomputable def target : ℝ := ∫ ω, M.Y1 ω ∂M.Q

end MSMDataCompatible

end POBackdoorSystem
end PO
end Causalean
