/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import Causalean.PO.ID.Exact.ATE
public import Causalean.Tactic.Attr

/-! # Marginal Sensitivity Model (MSM) for an arm mean `E[Y(d)]`

This file sets up an odds-ratio **Marginal Sensitivity Model** over the potential-outcome
backdoor system `POBackdoorSystem`.

For either treatment arm `d`, unconfoundedness identifies `E[Y(d)]` by inverse-probability
weighting against the observed arm propensity `e_d(X) = P[D=d | σ(X)]`. The MSM relaxes
unconfoundedness by allowing the **complete propensity**
`e₀,d(X, Y(d)) = P[D=d | σ(X, Y(d))]` to differ from `e_d(X)`, with the discrepancy
controlled by a sensitivity parameter `Λ ≥ 1`
through the odds ratio:

    1/Λ ≤ OR(e₀,d(X, Y(d)), e_d(X)) ≤ Λ.

The MSM **ambiguity set** `MSMSet d Λ` collects all candidate complete propensities
satisfying this odds-ratio bound (and a.e. interiority `0 < · < 1`). The candidate
unnormalized IPW mean `candMean d ẽ = E[1{D=d}·Y/ẽ]` traced over this odds-ratio box
produces the relaxation `[msmLower d Λ, msmUpper d Λ]`. The interval-validity theorem places
`E[Y(d)]` inside it under the stated bridge and boundedness hypotheses. The calibrated candidate
set is formalized separately.

This file states the definitions and the structural theorems (IPW/tower bridge,
membership of the truth, the interval bound, monotonicity in `Λ`, and the `Λ = 1`
point-identification collapse). -/

@[expose] public section

namespace Causalean
namespace PO

open MeasureTheory ProbabilityTheory

/-- For [a first real number](hyp:p₁) and [a second real number](hyp:p₂), the [odds ratio](goal) is the first number's odds divided by the second number's odds, $(p₁/(1-p₁))/(p₂/(1-p₂))$.

The MSM measures the discrepancy between
the complete propensity and the observed propensity by this quantity. -/
noncomputable def OR (p₁ p₂ : ℝ) : ℝ := (p₁ / (1 - p₁)) / (p₂ / (1 - p₂))

namespace POBackdoorSystem

variable {P : POSystem} {γ : Type*} [MeasurableSpace γ]
variable (S : POBackdoorSystem P γ)

/-- Given [a binary-treatment backdoor system](hyp:S) and [a treatment arm](hyp:d), the [complete-information σ-algebra](goal) is the σ-algebra on the sample space generated jointly by the factual covariate and the potential outcome under that arm.

It is the σ-algebra generated by BOTH the factual covariate `X` and the arm-specific potential
outcome `Y(d)`. Conditioning on this richer information set defines the *complete*
propensity; it always refines `σ(X)`. -/
noncomputable def sigmaXY (d : Bool) : MeasurableSpace P.Ω :=
  MeasurableSpace.comap S.factualX inferInstance
    ⊔ MeasurableSpace.comap (S.YofD d) inferInstance

/-- The joint σ-algebra `σ(X, Y(d))` for [the chosen arm](hyp:d) is [coarser than the ambient σ-algebra](goal). -/
lemma sigmaXY_le (d : Bool) : S.sigmaXY d ≤ (inferInstance : MeasurableSpace P.Ω) := by
  refine sup_le ?_ ?_
  · exact S.measurable_factualX.comap_le
  · exact (S.measurable_YofD d).comap_le

/-- Deprecated treated-arm name for [the complete-information σ-algebra](goal) of
[a binary-treatment backdoor system](hyp:S). -/
@[deprecated "Use sigmaXY true." (since := "2026-09-17")]
noncomputable abbrev sigmaXY1 : MeasurableSpace P.Ω := S.sigmaXY true

/-- Deprecated treated-arm name for the ambient measurability bound. -/
@[deprecated "Use sigmaXY_le true." (since := "2026-09-17")]
lemma sigmaXY1_le : S.sigmaXY1 ≤ (inferInstance : MeasurableSpace P.Ω) :=
  S.sigmaXY_le true

/-- Given [a binary-treatment backdoor system](hyp:S) and [a treatment arm](hyp:d), the [complete propensity](goal) assigns each unit the conditional probability of receiving that arm given the factual covariate and potential outcome under that arm.

It is `e₀,d(X, Y(d)) = P[D=d | σ(X, Y(d))]`: the conditional
probability of the arm given covariates *and* the corresponding potential outcome. Under
unconfoundedness it collapses (a.e.) to the observed arm propensity `e_d(X)`; in general it
is the unobservable object the MSM bounds. -/
noncomputable def completeProp (d : Bool) : P.Ω → ℝ :=
  P.μ[S.dVar.indicator d | S.sigmaXY d]

/-- Given [a binary-treatment backdoor system](hyp:S), [a treatment arm](hyp:d), and [a candidate complete-propensity function](hyp:etilde), the [candidate inverse-probability-weighted mean](goal) is the population mean of the arm indicator times factual outcome divided by that candidate function.

It is `E[1{D=d} · Y / ẽ]` for a candidate complete propensity `ẽ`,
where `Y` is the factual outcome. Evaluated at the true complete propensity this returns
`E[Y(d)]`; traced over the ambiguity set
it sweeps out the MSM interval. -/
noncomputable def candMean (d : Bool) (etilde : P.Ω → ℝ) : ℝ :=
  ∫ ω, S.dVar.indicator d ω * S.factualY ω / etilde ω ∂P.μ

/-- The candidate inverse-probability-weighted mean for a candidate complete propensity is the
population mean of the arm indicator times the factual outcome, divided by that candidate
propensity. -/
@[causal_defs_simps]
lemma candMean_eq (d : Bool) (etilde : P.Ω → ℝ) :
    S.candMean d etilde =
      ∫ ω, S.dVar.indicator d ω * S.factualY ω / etilde ω ∂P.μ :=
  rfl

/-- Given [a binary-treatment backdoor system](hyp:S) and [a treatment arm](hyp:d), the [arm-specific potential-outcome mean](goal) is the population mean of the potential outcome under that arm. -/
noncomputable def Ymean (d : Bool) : ℝ := ∫ ω, S.YofD d ω ∂P.μ

/-- Deprecated treated-arm name for [the potential-outcome mean](goal) of
[a binary-treatment backdoor system](hyp:S). -/
@[deprecated "Use Ymean true." (since := "2026-09-17")]
noncomputable abbrev Y1mean : ℝ := S.Ymean true

/-- The [MSM ambiguity set](goal) for [a binary-treatment backdoor system](hyp:S),
[a treatment arm](hyp:d), and [a sensitivity level](hyp:Λ) consists of candidate complete
propensities that [are almost surely strictly between zero and one](step:1) and whose odds relative
to the observed arm propensity remain within the sensitivity limits.

The **MSM ambiguity set** at sensitivity level `Λ`: the set of candidate complete
propensities `ẽ` that are a.e. in `(0,1)` and whose odds ratio against the observed arm
propensity `e_d(X) = P[D=d | σ(X)]` is a.e. bounded within `[1/Λ, Λ]`. Larger `Λ`
allows more candidates, widening the resulting interval. -/
def MSMSet (d : Bool) (Λ : ℝ) : Set (P.Ω → ℝ) :=
  { etilde |
      (∀ᵐ ω ∂P.μ, 0 < etilde ω ∧ etilde ω < 1) ∧
      (∀ᵐ ω ∂P.μ,
        1 / Λ ≤ OR (etilde ω) (S.propScore d ω)
          ∧ OR (etilde ω) (S.propScore d ω) ≤ Λ) }

/-- The [MSM upper bound](goal) is the largest unnormalized inverse-probability-weighted arm
mean allowed by the odds-ratio ambiguity set for [a binary-treatment backdoor system](hyp:S),
[a treatment arm](hyp:d), and [a sensitivity level](hyp:Λ).

This is the supremum of the unnormalized candidate arm means in the odds-box relaxation; it
does not assert that every candidate is realized by a compatible full-data law. -/
noncomputable def msmUpper (d : Bool) (Λ : ℝ) : ℝ :=
  sSup (S.candMean d '' S.MSMSet d Λ)

/-- The [MSM lower bound](goal) is the smallest unnormalized inverse-probability-weighted arm
mean allowed by the odds-ratio ambiguity set for [a binary-treatment backdoor system](hyp:S),
[a treatment arm](hyp:d), and [a sensitivity level](hyp:Λ).

This is the infimum of the unnormalized candidate arm means in the odds-box relaxation; it
does not assert that every candidate is realized by a compatible full-data law. -/
noncomputable def msmLower (d : Bool) (Λ : ℝ) : ℝ :=
  sInf (S.candMean d '' S.MSMSet d Λ)

/-- Inverse-probability weighting by the complete propensity [recovers the mean potential outcome
for the selected arm](goal) in [a binary-treatment backdoor system](hyp:S) under
[consistency](hyp:hcons), [positivity of that arm's complete propensity](hyp:hpos),
[integrability of its potential outcome](hyp:hint), and [integrability of the corresponding
weighted factual outcome](hyp:hcand_int), for [the selected arm](hyp:d).

This is the inverse-probability-weighting identity at `e₀,d = P[D=d | σ(X,Y(d))]`. The ratio
`Y(d) / e₀,d` is measurable with respect to `σ(X,Y(d))`; the tower property pulls it through
the conditional expectation, and `E[1{D=d} | σ(X,Y(d))] = e₀,d` cancels the denominator. -/
theorem candMean_completeProp_eq_Ymean
    [StandardBorelSpace P.Ω] [IsFiniteMeasure P.μ]
    (d : Bool)
    (hcons : P.Consistency)
    (hpos : ∀ᵐ ω ∂P.μ, 0 < S.completeProp d ω)
    (hint : Integrable (S.YofD d) P.μ)
    (hcand_int :
      Integrable
        (fun ω => S.dVar.indicator d ω * S.factualY ω / S.completeProp d ω) P.μ) :
    S.candMean d (S.completeProp d) = S.Ymean d := by
  classical
  -- Abbreviations.
  set f : P.Ω → ℝ := S.dVar.indicator d with hf_def
  set e : P.Ω → ℝ := S.completeProp d with he_def
  set g : P.Ω → ℝ := fun ω => S.YofD d ω / e ω with hg_def
  -- (1) Consistency: `f ω * factualY ω = f ω * YofD d ω` pointwise.
  have hcons_fn :
      (fun ω => S.factualY ω * f ω) = (fun ω => S.YofD d ω * f ω) := by
    have h := POVar.factual_mul_indicator_eq_cfUnder_mul_indicator_fn
      hcons S.yVar S.dVar d (Ne.symm S.hDY)
    funext ω
    have := congr_fun h ω
    simpa [POBackdoorSystem.YofD, POBackdoorSystem.factualY, hf_def] using this
  -- `candMean e = ∫ g ω * f ω`.
  have hcandMean_eq : S.candMean d e = ∫ ω, g ω * f ω ∂P.μ := by
    unfold POBackdoorSystem.candMean
    refine integral_congr_ae (Filter.Eventually.of_forall ?_)
    intro ω
    have hcw : S.factualY ω * f ω = S.YofD d ω * f ω := congr_fun hcons_fn ω
    -- `f ω * factualY ω / e ω = (YofD d ω / e ω) * f ω`.
    simp only [hg_def, hf_def] at hcw ⊢
    rw [div_eq_mul_inv, div_eq_mul_inv]
    linear_combination (e ω)⁻¹ * hcw
  -- (2) `g` is `sigmaXY1`-strongly measurable.
  have hY1_meas : Measurable[S.sigmaXY d] (S.YofD d) := by
    have hle : MeasurableSpace.comap (S.YofD d) inferInstance ≤ S.sigmaXY d :=
      le_sup_right
    exact (comap_measurable (S.YofD d)).mono hle le_rfl
  have he_smeas : StronglyMeasurable[S.sigmaXY d] e := by
    rw [he_def]
    exact stronglyMeasurable_condExp
  have hg_smeas : StronglyMeasurable[S.sigmaXY d] g := by
    have he_meas : Measurable[S.sigmaXY d] e := he_smeas.measurable
    exact (hY1_meas.div he_meas).stronglyMeasurable
  -- Integrability of `f` and `g * f`.
  have hf_int : Integrable f P.μ :=
    S.dVar.integrable_indicator d (measurableSet_singleton d)
  have hgf_int : Integrable (fun ω => g ω * f ω) P.μ := by
    refine hcand_int.congr (Filter.Eventually.of_forall ?_)
    intro ω
    have hcw : S.factualY ω * f ω = S.YofD d ω * f ω := congr_fun hcons_fn ω
    simp only [hg_def, hf_def] at hcw ⊢
    rw [div_eq_mul_inv, div_eq_mul_inv]
    linear_combination (e ω)⁻¹ * hcw
  -- (3) Pull-out + tower: `∫ g * f = ∫ g * e`.
  have hpull :
      P.μ[fun ω => g ω * f ω | S.sigmaXY d] =ᵐ[P.μ] (fun ω => g ω * e ω) := by
    have h := MeasureTheory.condExp_mul_of_stronglyMeasurable_left
      (m := S.sigmaXY d) (μ := P.μ) hg_smeas hgf_int hf_int
    -- `μ[g * f | m] =ᵐ g * μ[f | m]`, and `μ[f | m] = e`.
    have he_cond : (P.μ[f | S.sigmaXY d]) = e := by
      rw [hf_def, he_def]; rfl
    refine h.trans ?_
    rw [he_cond]
    rfl
  have htower : ∫ ω, g ω * f ω ∂P.μ = ∫ ω, g ω * e ω ∂P.μ := by
    have h1 :
        ∫ ω, P.μ[fun ω => g ω * f ω | S.sigmaXY d] ω ∂P.μ
          = ∫ ω, g ω * f ω ∂P.μ :=
      MeasureTheory.integral_condExp (S.sigmaXY_le d)
    rw [← h1]
    exact integral_congr_ae hpull
  -- (4) Cancel: `∫ g * e = ∫ YofD d = Y1mean`.
  have hcancel : ∫ ω, g ω * e ω ∂P.μ = S.Ymean d := by
    unfold POBackdoorSystem.Ymean
    refine integral_congr_ae ?_
    filter_upwards [hpos] with ω hω
    rw [hg_def]
    field_simp
  rw [hcandMean_eq, htower, hcancel]

/-- Deprecated treated-arm specialization of the arm-uniform IPW/tower bridge. -/
@[deprecated "Use candMean_completeProp_eq_Ymean true." (since := "2026-09-17")]
theorem candMean_completeProp_eq_Y1mean
    [StandardBorelSpace P.Ω] [IsFiniteMeasure P.μ]
    (hcons : P.Consistency)
    (hpos : ∀ᵐ ω ∂P.μ, 0 < S.completeProp true ω)
    (hint : Integrable (S.YofD true) P.μ)
    (hcand_int : Integrable
      (fun ω => S.dVar.indicator true ω * S.factualY ω / S.completeProp true ω) P.μ) :
    S.candMean true (S.completeProp true) = S.Y1mean :=
  S.candMean_completeProp_eq_Ymean true hcons hpos hint hcand_int

/-- **The MSM assumption: the truth lies in the ambiguity set.** The d complete
propensity `e₀` belongs to `MSMSet Λ`, i.e. it is a.e. interior and its odds ratio
against the observed arm propensity `e_d(X)` is a.e. within `[1/Λ, Λ]`. This is precisely
the marginal sensitivity assumption; the membership facts are supplied as `hMSM`. -/
theorem completeProp_mem_MSMSet (d : Bool) (Λ : ℝ)
    (hMSM :
      (∀ᵐ ω ∂P.μ, 0 < S.completeProp d ω ∧ S.completeProp d ω < 1) ∧
      (∀ᵐ ω ∂P.μ,
        1 / Λ ≤ OR (S.completeProp d ω) (S.propScore d ω)
          ∧ OR (S.completeProp d ω) (S.propScore d ω) ≤ Λ)) :
    S.completeProp d ∈ S.MSMSet d Λ := by
  simp only [MSMSet, Set.mem_setOf_eq]
  exact hMSM

/-- The [mean potential outcome for an arm lies between the smallest and largest candidate
means](goal) in [a binary-treatment backdoor system](hyp:S) at [a sensitivity level](hyp:Λ)
when [that arm's complete propensity is admissible](hyp:hmem), [its candidate mean equals its
potential-outcome mean](hyp:hbridge), and [the candidate means are bounded below and
above](hyp:hbdd,hbdd'), for [the selected arm](hyp:d):

    msmLower d Λ ≤ E[Y(d)] ≤ msmUpper d Λ.

The boundedness hypotheses ensure the `sInf`/`sSup` are the genuine extremes. -/
theorem Ymean_mem_Icc (d : Bool) (Λ : ℝ)
    (hmem : S.completeProp d ∈ S.MSMSet d Λ)
    (hbridge : S.candMean d (S.completeProp d) = S.Ymean d)
    (hbdd : BddBelow (S.candMean d '' S.MSMSet d Λ))
    (hbdd' : BddAbove (S.candMean d '' S.MSMSet d Λ)) :
    S.Ymean d ∈ Set.Icc (S.msmLower d Λ) (S.msmUpper d Λ) := by
  have hmemImg : S.candMean d (S.completeProp d) ∈ S.candMean d '' S.MSMSet d Λ :=
    Set.mem_image_of_mem _ hmem
  rw [Set.mem_Icc, ← hbridge]
  refine ⟨?_, ?_⟩
  · exact csInf_le hbdd hmemImg
  · exact le_csSup hbdd' hmemImg

/-- Deprecated treated-arm specialization of the arm-uniform MSM interval theorem. -/
@[deprecated "Use Ymean_mem_Icc true." (since := "2026-09-17")]
theorem Y1mean_mem_Icc (Λ : ℝ)
    (hmem : S.completeProp true ∈ S.MSMSet true Λ)
    (hbridge : S.candMean true (S.completeProp true) = S.Y1mean)
    (hbdd : BddBelow (S.candMean true '' S.MSMSet true Λ))
    (hbdd' : BddAbove (S.candMean true '' S.MSMSet true Λ)) :
    S.Y1mean ∈ Set.Icc (S.msmLower true Λ) (S.msmUpper true Λ) :=
  S.Ymean_mem_Icc true Λ hmem hbridge hbdd hbdd'

/-- **Monotonicity of the ambiguity set in the sensitivity parameter.** A larger
budget `Λ ≤ Λ'` (with `1 ≤ Λ`) contains every candidate allowed by the smaller budget:
`MSMSet Λ ⊆ MSMSet Λ'`. The odds-ratio window `[1/Λ, Λ]` widens with `Λ`. -/
theorem MSMSet_mono (d : Bool) {Λ Λ' : ℝ} (hΛ : 1 ≤ Λ) (hΛΛ' : Λ ≤ Λ') :
    S.MSMSet d Λ ⊆ S.MSMSet d Λ' := by
  have hΛpos : 0 < Λ := lt_of_lt_of_le one_pos hΛ
  intro etilde hetilde
  obtain ⟨hint, hor⟩ := hetilde
  refine ⟨hint, ?_⟩
  filter_upwards [hor] with ω hω
  obtain ⟨hlo, hhi⟩ := hω
  constructor
  · have h1 : 1 / Λ' ≤ 1 / Λ := one_div_le_one_div_of_le hΛpos hΛΛ'
    exact le_trans h1 hlo
  · exact le_trans hhi hΛΛ'

/-- **The MSM interval widens with `Λ` (upper endpoint).** Since `MSMSet Λ ⊆ MSMSet Λ'`,
the supremum of the candidate mean can only increase. Boundedness of the larger image
is required for the `sSup` comparison. -/
theorem msmUpper_mono (d : Bool) {Λ Λ' : ℝ} (hΛ : 1 ≤ Λ) (hΛΛ' : Λ ≤ Λ')
    (hne : (S.candMean d '' S.MSMSet d Λ).Nonempty)
    (hbdd' : BddAbove (S.candMean d '' S.MSMSet d Λ')) :
    S.msmUpper d Λ ≤ S.msmUpper d Λ' := by
  have hsub : S.MSMSet d Λ ⊆ S.MSMSet d Λ' := S.MSMSet_mono d hΛ hΛΛ'
  have himg : S.candMean d '' S.MSMSet d Λ ⊆ S.candMean d '' S.MSMSet d Λ' :=
    Set.image_mono hsub
  exact csSup_le_csSup hbdd' hne himg

/-- **The MSM interval widens with `Λ` (lower endpoint).** Since `MSMSet Λ ⊆ MSMSet Λ'`,
the infimum of the candidate mean can only decrease. Boundedness-below of the larger
image is required for the `sInf` comparison. -/
theorem msmLower_anti (d : Bool) {Λ Λ' : ℝ} (hΛ : 1 ≤ Λ) (hΛΛ' : Λ ≤ Λ')
    (hne : (S.candMean d '' S.MSMSet d Λ).Nonempty)
    (hbdd' : BddBelow (S.candMean d '' S.MSMSet d Λ')) :
    S.msmLower d Λ' ≤ S.msmLower d Λ := by
  have hsub : S.MSMSet d Λ ⊆ S.MSMSet d Λ' := S.MSMSet_mono d hΛ hΛΛ'
  have himg : S.candMean d '' S.MSMSet d Λ ⊆ S.candMean d '' S.MSMSet d Λ' :=
    Set.image_mono hsub
  exact csInf_le_csInf hbdd' hne himg

/-- At sensitivity one, [an admissible candidate complete propensity equals the observed arm
propensity almost everywhere](goal) in [a binary-treatment backdoor system](hyp:S), for
[the selected arm](hyp:d) and [candidate](hyp:etilde), provided [the observed arm propensity is
strictly between zero and one almost surely](hyp:hprop) and [the candidate belongs to the
arm's ambiguity set](hyp:hmem).

When `Λ = 1` the odds-ratio window degenerates to `{1}`, forcing every member of the
ambiguity set to equal the observed propensity `e_d(X) = P[D=d | σ(X)]` a.e. Thus the
MSM interval collapses to the unconfounded IPW point estimate. The a.e. interiority
of `e_d(X)` is required to invert the odds ratio. -/
theorem MSMSet_one_eq (d : Bool) (etilde : P.Ω → ℝ)
    (hprop : ∀ᵐ ω ∂P.μ, 0 < S.propScore d ω ∧ S.propScore d ω < 1)
    (hmem : etilde ∈ S.MSMSet d 1) :
    ∀ᵐ ω ∂P.μ, etilde ω = S.propScore d ω := by
  obtain ⟨hint, hor⟩ := hmem
  filter_upwards [hprop, hint, hor] with ω hq hp hOR
  obtain ⟨hqpos, hqlt⟩ := hq
  obtain ⟨hppos, hplt⟩ := hp
  obtain ⟨hlo, hhi⟩ := hOR
  -- At Λ = 1, the odds-ratio window is {1}.
  rw [one_div, inv_one] at hlo
  have hOReq : OR (etilde ω) (S.propScore d ω) = 1 := le_antisymm hhi hlo
  -- Unfold OR and clear denominators.
  set p := etilde ω with hpdef
  set q := S.propScore d ω with hqdef
  have h1p : (0:ℝ) < 1 - p := by linarith
  have h1q : (0:ℝ) < 1 - q := by linarith
  have hqratio : q / (1 - q) ≠ 0 := by
    apply div_ne_zero
    · exact ne_of_gt hqpos
    · exact ne_of_gt h1q
  rw [OR, div_eq_one_iff_eq hqratio] at hOReq
  -- hOReq : p/(1-p) = q/(1-q); conclude p = q.
  field_simp at hOReq
  nlinarith [hOReq]

end POBackdoorSystem

end PO
end Causalean
