/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

import Causalean.PO.ID.Exact.ATE
import Causalean.Tactic.Attr

/-! # Marginal Sensitivity Model (MSM) for the treated mean `E[Y(1)]`

This file sets up the **Marginal Sensitivity Model** of Tan (2006) / Zhao–Small–Bhattacharya
(2019) over the potential-outcome backdoor system `POBackdoorSystem`.

Unconfoundedness identifies `E[Y(1)]` by inverse-probability weighting against the
observed propensity score `e(X) = P[D=1 | σ(X)]`. The MSM relaxes unconfoundedness
by allowing the **complete propensity** `e₀(X, Y(1)) = P[D=1 | σ(X, Y(1))]` to differ
from `e(X)`, with the discrepancy controlled by a sensitivity parameter `Λ ≥ 1`
through the odds ratio:

    1/Λ ≤ OR(e₀(X, Y(1)), e(X)) ≤ Λ.

The MSM **ambiguity set** `MSMSet Λ` collects all candidate complete propensities
satisfying this odds-ratio bound (and a.e. interiority `0 < · < 1`). The candidate
IPW mean `candMean ẽ = E[A·Y/ẽ]` traced over this uncalibrated ZSB ambiguity set
produces the valid interval `[msmLower Λ, msmUpper Λ]`, which contains the estimand
`E[Y(1)]`. The calibrated Dorn-Guo sharp set is formalized separately.

This file states the definitions and the structural theorems (IPW/tower bridge,
membership of the truth, the interval bound, monotonicity in `Λ`, and the `Λ = 1`
point-identification collapse). -/

namespace Causalean
namespace PO

open MeasureTheory ProbabilityTheory

/-- For [a first real number](hyp:p₁) and [a second real number](hyp:p₂), the [odds ratio](goal) is the first number's odds divided by the second number's odds, $(p₁/(1-p₁))/(p₂/(1-p₂))$.

The MSM measures the discrepancy between
the complete propensity and the observed propensity by this quantity. -/
noncomputable def OR (p₁ p₂ : ℝ) : ℝ := (p₁ / (1 - p₁)) / (p₂ / (1 - p₂))

namespace POBackdoorSystem

variable {P : POSystem} {γ : Type*} [MeasurableSpace γ]
variable (S : POBackdoorSystem P γ)

/-- Given [a binary-treatment backdoor system](hyp:S), the [complete-information σ-algebra](goal) is the σ-algebra on the sample space generated jointly by the factual covariate and the potential outcome under treatment.

It is the σ-algebra generated by BOTH the factual covariate `X` and the treated potential
outcome `Y(1)`. Conditioning on this richer information set defines the *complete*
propensity; it always refines `σ(X)`. -/
noncomputable def sigmaXY1 : MeasurableSpace P.Ω :=
  MeasurableSpace.comap S.factualX inferInstance
    ⊔ MeasurableSpace.comap (S.YofD true) inferInstance

/-- The joint σ-algebra `σ(X, Y(1))` is coarser than the ambient σ-algebra on `Ω`. -/
lemma sigmaXY1_le : S.sigmaXY1 ≤ (inferInstance : MeasurableSpace P.Ω) := by
  refine sup_le ?_ ?_
  · exact S.measurable_factualX.comap_le
  · exact (S.measurable_YofD true).comap_le

/-- Given [a binary-treatment backdoor system](hyp:S), the [complete propensity](goal) assigns each unit the conditional probability of treatment given the factual covariate and treated potential outcome.

It is `e₀(X, Y(1)) = P[D=1 | σ(X, Y(1))]`: the conditional
probability of treatment given covariates *and* the treated potential outcome. Under
unconfoundedness it collapses (a.e.) to the observed propensity `e(X)`; in general it
is the unobservable object the MSM bounds. -/
noncomputable def completeProp : P.Ω → ℝ :=
  P.μ[S.dVar.indicator true | S.sigmaXY1]

/-- Given [a binary-treatment backdoor system](hyp:S) and [a candidate complete-propensity function](hyp:etilde), the [candidate inverse-probability-weighted mean](goal) is the population mean of the treated-arm indicator times factual outcome divided by that candidate function.

It is `E[A · Y / ẽ]` for a candidate complete propensity `ẽ`,
where `A = 1_{D=1}` is the treatment indicator and `Y` the factual outcome. Evaluated
at the true complete propensity this returns `E[Y(1)]`; traced over the ambiguity set
it sweeps out the MSM interval. -/
noncomputable def candMean (etilde : P.Ω → ℝ) : ℝ :=
  ∫ ω, S.dVar.indicator true ω * S.factualY ω / etilde ω ∂P.μ

/-- The candidate inverse-probability-weighted mean for a candidate complete propensity is the
population mean of the treatment indicator times the factual outcome, divided by that candidate
propensity. -/
@[causal_defs_simps]
lemma candMean_eq (etilde : P.Ω → ℝ) :
    S.candMean etilde =
      ∫ ω, S.dVar.indicator true ω * S.factualY ω / etilde ω ∂P.μ :=
  rfl

/-- Given [a binary-treatment backdoor system](hyp:S), the [treated potential-outcome mean](goal) is the population mean of the potential outcome under treatment. -/
noncomputable def Y1mean : ℝ := ∫ ω, S.YofD true ω ∂P.μ

/-- Given [a binary-treatment backdoor system](hyp:S) and [a sensitivity level](hyp:Λ), the [MSM ambiguity set](goal) contains exactly the candidate complete-propensity functions that [are almost surely strictly between zero and one](step:1) and whose odds ratio relative to the observed propensity is almost surely between the reciprocal of the sensitivity level and the sensitivity level.

The **MSM ambiguity set** at sensitivity level `Λ`: the set of candidate complete
propensities `ẽ` that are a.e. in `(0,1)` and whose odds ratio against the observed
propensity `e(X) = P[D=1 | σ(X)]` is a.e. bounded within `[1/Λ, Λ]`. Larger `Λ`
admits more candidates, widening the resulting interval. -/
def MSMSet (Λ : ℝ) : Set (P.Ω → ℝ) :=
  { etilde |
      (∀ᵐ ω ∂P.μ, 0 < etilde ω ∧ etilde ω < 1) ∧
      (∀ᵐ ω ∂P.μ,
        1 / Λ ≤ OR (etilde ω) (S.propScore true ω)
          ∧ OR (etilde ω) (S.propScore true ω) ≤ Λ) }

/-- Given [a binary-treatment backdoor system](hyp:S) and [a sensitivity level](hyp:Λ), the [MSM upper bound](goal) is the supremum of candidate inverse-probability-weighted means over the MSM ambiguity set at that level.

The **MSM upper bound**: the supremum of the candidate mean over the ambiguity
set. The largest value of `E[Y(1)]` consistent with the sensitivity budget `Λ`. -/
noncomputable def msmUpper (Λ : ℝ) : ℝ := sSup (S.candMean '' S.MSMSet Λ)

/-- Given [a binary-treatment backdoor system](hyp:S) and [a sensitivity level](hyp:Λ), the [MSM lower bound](goal) is the infimum of candidate inverse-probability-weighted means over the MSM ambiguity set at that level.

The **MSM lower bound**: the infimum of the candidate mean over the ambiguity
set. The smallest value of `E[Y(1)]` consistent with the sensitivity budget `Λ`. -/
noncomputable def msmLower (Λ : ℝ) : ℝ := sInf (S.candMean '' S.MSMSet Λ)

/-- **IPW / tower bridge.** Assuming [potential and observed outcomes agree under the realized
treatment (consistency)](hyp:hcons), [the true complete propensity `e₀ = P[D=1 | σ(X, Y(1))]` is
positive almost surely](hyp:hpos), [the treated potential outcome `Y(1)` is
integrable](hyp:hint), and [the inverse-propensity-weighted candidate `A·Y/e₀` is
integrable](hyp:hcand_int), then [evaluated at the true complete propensity, the candidate IPW
mean recovers the estimand: `candMean e₀ = E[A · Y / e₀] = E[Y(1)]`](goal).

This is the inverse-probability-weighting identity at the complete propensity, where
the ratio `Y(1) / e₀` is measurable with respect to `σ(X, Y(1))`. The tower
property pulls this ratio through the conditional expectation, and
`E[A | σ(X, Y(1))] = e₀` cancels the denominator. Carries consistency (to identify
`A·Y` with `A·Y(1)`), a.e. positivity of `e₀`, and integrability of `Y(1)` as
hypotheses. -/
theorem candMean_completeProp_eq_Y1mean
    [StandardBorelSpace P.Ω] [IsFiniteMeasure P.μ]
    (hcons : P.Consistency)
    (hpos : ∀ᵐ ω ∂P.μ, 0 < S.completeProp ω)
    (hint : Integrable (S.YofD true) P.μ)
    (hcand_int :
      Integrable
        (fun ω => S.dVar.indicator true ω * S.factualY ω / S.completeProp ω) P.μ) :
    S.candMean S.completeProp = S.Y1mean := by
  classical
  -- Abbreviations.
  set f : P.Ω → ℝ := S.dVar.indicator true with hf_def
  set e : P.Ω → ℝ := S.completeProp with he_def
  set g : P.Ω → ℝ := fun ω => S.YofD true ω / e ω with hg_def
  -- (1) Consistency: `f ω * factualY ω = f ω * YofD true ω` pointwise.
  have hcons_fn :
      (fun ω => S.factualY ω * f ω) = (fun ω => S.YofD true ω * f ω) := by
    have h := POVar.factual_mul_indicator_eq_cfUnder_mul_indicator_fn
      hcons S.yVar S.dVar true (Ne.symm S.hDY)
    funext ω
    have := congr_fun h ω
    simpa [POBackdoorSystem.YofD, POBackdoorSystem.factualY, hf_def] using this
  -- `candMean e = ∫ g ω * f ω`.
  have hcandMean_eq : S.candMean e = ∫ ω, g ω * f ω ∂P.μ := by
    unfold POBackdoorSystem.candMean
    refine integral_congr_ae (Filter.Eventually.of_forall ?_)
    intro ω
    have hcw : S.factualY ω * f ω = S.YofD true ω * f ω := congr_fun hcons_fn ω
    -- `f ω * factualY ω / e ω = (YofD true ω / e ω) * f ω`.
    simp only [hg_def, hf_def] at hcw ⊢
    rw [div_eq_mul_inv, div_eq_mul_inv]
    linear_combination (e ω)⁻¹ * hcw
  -- (2) `g` is `sigmaXY1`-strongly measurable.
  have hY1_meas : Measurable[S.sigmaXY1] (S.YofD true) := by
    have hle : MeasurableSpace.comap (S.YofD true) inferInstance ≤ S.sigmaXY1 :=
      le_sup_right
    exact (comap_measurable (S.YofD true)).mono hle le_rfl
  have he_smeas : StronglyMeasurable[S.sigmaXY1] e := by
    rw [he_def]
    exact stronglyMeasurable_condExp
  have hg_smeas : StronglyMeasurable[S.sigmaXY1] g := by
    have he_meas : Measurable[S.sigmaXY1] e := he_smeas.measurable
    exact (hY1_meas.div he_meas).stronglyMeasurable
  -- Integrability of `f` and `g * f`.
  have hf_int : Integrable f P.μ :=
    S.dVar.integrable_indicator true (measurableSet_singleton true)
  have hgf_int : Integrable (fun ω => g ω * f ω) P.μ := by
    refine hcand_int.congr (Filter.Eventually.of_forall ?_)
    intro ω
    have hcw : S.factualY ω * f ω = S.YofD true ω * f ω := congr_fun hcons_fn ω
    simp only [hg_def, hf_def] at hcw ⊢
    rw [div_eq_mul_inv, div_eq_mul_inv]
    linear_combination (e ω)⁻¹ * hcw
  -- (3) Pull-out + tower: `∫ g * f = ∫ g * e`.
  have hpull :
      P.μ[fun ω => g ω * f ω | S.sigmaXY1] =ᵐ[P.μ] (fun ω => g ω * e ω) := by
    have h := MeasureTheory.condExp_mul_of_stronglyMeasurable_left
      (m := S.sigmaXY1) (μ := P.μ) hg_smeas hgf_int hf_int
    -- `μ[g * f | m] =ᵐ g * μ[f | m]`, and `μ[f | m] = e`.
    have he_cond : (P.μ[f | S.sigmaXY1]) = e := by
      rw [hf_def, he_def]; rfl
    refine h.trans ?_
    rw [he_cond]
    rfl
  have htower : ∫ ω, g ω * f ω ∂P.μ = ∫ ω, g ω * e ω ∂P.μ := by
    have h1 :
        ∫ ω, P.μ[fun ω => g ω * f ω | S.sigmaXY1] ω ∂P.μ
          = ∫ ω, g ω * f ω ∂P.μ :=
      MeasureTheory.integral_condExp S.sigmaXY1_le
    rw [← h1]
    exact integral_congr_ae hpull
  -- (4) Cancel: `∫ g * e = ∫ YofD true = Y1mean`.
  have hcancel : ∫ ω, g ω * e ω ∂P.μ = S.Y1mean := by
    unfold POBackdoorSystem.Y1mean
    refine integral_congr_ae ?_
    filter_upwards [hpos] with ω hω
    rw [hg_def]
    field_simp
  rw [hcandMean_eq, htower, hcancel]

/-- **The MSM assumption: the truth lies in the ambiguity set.** The true complete
propensity `e₀` belongs to `MSMSet Λ`, i.e. it is a.e. interior and its odds ratio
against the observed propensity `e(X)` is a.e. within `[1/Λ, Λ]`. This is precisely
the marginal sensitivity assumption; the membership facts are supplied as `hMSM`. -/
theorem completeProp_mem_MSMSet (Λ : ℝ)
    (hMSM :
      (∀ᵐ ω ∂P.μ, 0 < S.completeProp ω ∧ S.completeProp ω < 1) ∧
      (∀ᵐ ω ∂P.μ,
        1 / Λ ≤ OR (S.completeProp ω) (S.propScore true ω)
          ∧ OR (S.completeProp ω) (S.propScore true ω) ≤ Λ)) :
    S.completeProp ∈ S.MSMSet Λ := by
  simp only [MSMSet, Set.mem_setOf_eq]
  exact hMSM

/-- **The MSM bound: `E[Y(1)]` lies in the MSM interval.** Assuming [the true complete propensity
belongs to the marginal-sensitivity ambiguity set](hyp:hmem), [the IPW/tower bridge identity
`candMean e₀ = E[Y(1)]` holds](hyp:hbridge), and [the candidate mean is bounded below and above
over the ambiguity set](hyp:hbdd,hbdd'), [the estimand `E[Y(1)]` is sandwiched between the
infimum and supremum of the candidate mean over the ambiguity set](goal):

    msmLower Λ ≤ E[Y(1)] ≤ msmUpper Λ.

The boundedness hypotheses ensure the `sInf`/`sSup` are the genuine extremes. -/
theorem Y1mean_mem_Icc (Λ : ℝ)
    (hmem : S.completeProp ∈ S.MSMSet Λ)
    (hbridge : S.candMean S.completeProp = S.Y1mean)
    (hbdd : BddBelow (S.candMean '' S.MSMSet Λ))
    (hbdd' : BddAbove (S.candMean '' S.MSMSet Λ)) :
    S.Y1mean ∈ Set.Icc (S.msmLower Λ) (S.msmUpper Λ) := by
  have hmemImg : S.candMean S.completeProp ∈ S.candMean '' S.MSMSet Λ :=
    Set.mem_image_of_mem _ hmem
  rw [Set.mem_Icc, ← hbridge]
  refine ⟨?_, ?_⟩
  · exact csInf_le hbdd hmemImg
  · exact le_csSup hbdd' hmemImg

/-- **Monotonicity of the ambiguity set in the sensitivity parameter.** A larger
budget `Λ ≤ Λ'` (with `1 ≤ Λ`) admits every candidate that the smaller budget admits:
`MSMSet Λ ⊆ MSMSet Λ'`. The odds-ratio window `[1/Λ, Λ]` widens with `Λ`. -/
theorem MSMSet_mono {Λ Λ' : ℝ} (hΛ : 1 ≤ Λ) (hΛΛ' : Λ ≤ Λ') :
    S.MSMSet Λ ⊆ S.MSMSet Λ' := by
  have hΛpos : 0 < Λ := lt_of_lt_of_le one_pos hΛ
  intro etilde hetilde
  obtain ⟨hint, hor⟩ := hetilde
  refine ⟨hint, ?_⟩
  filter_upwards [hor] with ω hω
  obtain ⟨hlo, hhi⟩ := hω
  constructor
  · have h1 : 1 / Λ' ≤ 1 / Λ := one_div_le_one_div_of_le hΛpos hΛΛ'
    exact le_trans h1 hlo
  · exact le_trans hhi hΛΛ'

/-- **The MSM interval widens with `Λ` (upper endpoint).** Since `MSMSet Λ ⊆ MSMSet Λ'`,
the supremum of the candidate mean can only increase. Boundedness of the larger image
is required for the `sSup` comparison. -/
theorem msmUpper_mono {Λ Λ' : ℝ} (hΛ : 1 ≤ Λ) (hΛΛ' : Λ ≤ Λ')
    (hne : (S.candMean '' S.MSMSet Λ).Nonempty)
    (hbdd' : BddAbove (S.candMean '' S.MSMSet Λ')) :
    S.msmUpper Λ ≤ S.msmUpper Λ' := by
  have hsub : S.MSMSet Λ ⊆ S.MSMSet Λ' := S.MSMSet_mono hΛ hΛΛ'
  have himg : S.candMean '' S.MSMSet Λ ⊆ S.candMean '' S.MSMSet Λ' :=
    Set.image_mono hsub
  exact csSup_le_csSup hbdd' hne himg

/-- **The MSM interval widens with `Λ` (lower endpoint).** Since `MSMSet Λ ⊆ MSMSet Λ'`,
the infimum of the candidate mean can only decrease. Boundedness-below of the larger
image is required for the `sInf` comparison. -/
theorem msmLower_anti {Λ Λ' : ℝ} (hΛ : 1 ≤ Λ) (hΛΛ' : Λ ≤ Λ')
    (hne : (S.candMean '' S.MSMSet Λ).Nonempty)
    (hbdd' : BddBelow (S.candMean '' S.MSMSet Λ')) :
    S.msmLower Λ' ≤ S.msmLower Λ := by
  have hsub : S.MSMSet Λ ⊆ S.MSMSet Λ' := S.MSMSet_mono hΛ hΛΛ'
  have himg : S.candMean '' S.MSMSet Λ ⊆ S.candMean '' S.MSMSet Λ' :=
    Set.image_mono hsub
  exact csInf_le_csInf hbdd' hne himg

/-- **Point identification at `Λ = 1` (no-unmeasured-confounding collapse).** Assume [the
propensity score for treatment given the covariates lies strictly between 0 and 1 almost surely
(overlap)](hyp:hprop). If [a candidate complete propensity `ẽ` belongs to the marginal-sensitivity
ambiguity set at `Λ = 1`](hyp:hmem), then [it equals the observed propensity score almost
everywhere](goal).

When `Λ = 1` the odds-ratio window degenerates to `{1}`, forcing every member of the
ambiguity set to equal the observed propensity `e(X) = P[D=1 | σ(X)]` a.e. Thus the
MSM interval collapses to the unconfounded IPW point estimate. The a.e. interiority
of `e(X)` is required to invert the odds ratio. -/
theorem MSMSet_one_eq (etilde : P.Ω → ℝ)
    (hprop : ∀ᵐ ω ∂P.μ, 0 < S.propScore true ω ∧ S.propScore true ω < 1)
    (hmem : etilde ∈ S.MSMSet 1) :
    ∀ᵐ ω ∂P.μ, etilde ω = S.propScore true ω := by
  obtain ⟨hint, hor⟩ := hmem
  filter_upwards [hprop, hint, hor] with ω hq hp hOR
  obtain ⟨hqpos, hqlt⟩ := hq
  obtain ⟨hppos, hplt⟩ := hp
  obtain ⟨hlo, hhi⟩ := hOR
  -- At Λ = 1, the odds-ratio window is {1}.
  rw [one_div, inv_one] at hlo
  have hOReq : OR (etilde ω) (S.propScore true ω) = 1 := le_antisymm hhi hlo
  -- Unfold OR and clear denominators.
  set p := etilde ω with hpdef
  set q := S.propScore true ω with hqdef
  have h1p : (0:ℝ) < 1 - p := by linarith
  have h1q : (0:ℝ) < 1 - q := by linarith
  have hqratio : q / (1 - q) ≠ 0 := by
    apply div_ne_zero
    · exact ne_of_gt hqpos
    · exact ne_of_gt h1q
  rw [OR, div_eq_one_iff_eq hqratio] at hOReq
  -- hOReq : p/(1-p) = q/(1-q); conclude p = q.
  field_simp at hOReq
  nlinarith [hOReq]

end POBackdoorSystem

end PO
end Causalean
