module
public import CausalSmith.Stat.STAT_PomdpLatentOverlapMinimax_Research.Helpers.PhiwHistory
public import CausalSmith.Stat.STAT_PomdpPolicyclassRegret_Research.Helpers.SelectorTrajectoryBridge

/-!
# Uniqueness of the finite POMDP trajectory law

The initial state marginal and the two complete-history one-step
factorizations uniquely determine the full finite trajectory law.
-/

@[expose] public section

namespace CausalSmith.Stat.PomdpPolicyclassRegret

open MeasureTheory ProbabilityTheory
open CausalSmith.Stat.PomdpLatentOverlapMinimax

/-- A full path law generated by the stationary initial distribution, behavior
action kernel, and reward-transition kernel of a raw POMDP. -/
-- @node: RawGeneratedPathLaw
@[no_expose]
def RawGeneratedPathLaw {T nX nH : Nat} (M : RawPomdpExperiment T nX nH)
    (μ : Measure (FullTrajectory T nX nH)) : Prop :=
  IsProbabilityMeasure μ ∧
  (∀ s, (μ.map (stateAt 0)) {s} =
    ENNReal.ofReal (stationaryLaw (policyKernel M M.b) s)) ∧
  (∀ t : Fin T, μ.map (histActionPair t) =
    (μ.map (histStateView t)).compProd
      (Kernel.comap (behaviourKernel M) (currentObsState t)
        (measurable_currentObsState t))) ∧
  (∀ t : Fin T, μ.map (histNextPair t) =
    (μ.map (histView t)).compProd
      (Kernel.comap (kernelOfK M) (currentStateAction t)
        (measurable_currentStateAction t)))

/-- Constructor form of `RawGeneratedPathLaw`, exported so downstream structural-law modules
need not unfold its opaque definition. For [the time horizon](hyp:T),
[the observed-state count](hyp:nX), [the hidden-state count](hyp:nH),
[the candidate-policy count](hyp:M), [the measure](hyp:μ),
[the probability assumption](hyp:hprob), [the init assumption](hyp:hinit),
[the action assumption](hyp:haction), and [the kernel assumption](hyp:hkernel), this establishes
[the raw generated path law mk result](goal). -/
-- @node: rawGeneratedPathLaw_mk
lemma rawGeneratedPathLaw_mk {T nX nH : Nat}
    (M : RawPomdpExperiment T nX nH)
    (μ : Measure (FullTrajectory T nX nH))
    (hprob : IsProbabilityMeasure μ)
    (hinit : ∀ s, (μ.map (stateAt 0)) {s} =
      ENNReal.ofReal (stationaryLaw (policyKernel M M.b) s))
    (haction : ∀ t : Fin T, μ.map (histActionPair t) =
      (μ.map (histStateView t)).compProd
        (Kernel.comap (behaviourKernel M) (currentObsState t)
          (measurable_currentObsState t)))
    (hkernel : ∀ t : Fin T, μ.map (histNextPair t) =
      (μ.map (histView t)).compProd
        (Kernel.comap (kernelOfK M) (currentStateAction t)
          (measurable_currentStateAction t))) :
    RawGeneratedPathLaw M μ := by
  exact ⟨hprob, hinit, haction, hkernel⟩

/-- The assumptions on a list model certify its actual law as generated. For
[the time horizon](hyp:T), [the candidate-policy count](hyp:M), [the mixing scale](hyp:t0),
[the policy-overlap scale](hyp:zeta), [the latent-overlap radius](hyp:C), [the model](hyp:m),
and [the class assumption](hyp:hClass), this establishes
[the selector actual raw generated path law result](goal). -/
-- @node: selector_actual_rawGeneratedPathLaw
lemma selector_actual_rawGeneratedPathLaw {T M : Nat}
    (t0 zeta C : ℝ) (m : ModelIndex T M)
    (hClass : PolicyListClass t0 zeta C m) :
    RawGeneratedPathLaw m.Mx.toRawB m.Mx.law := by
  exact ⟨m.Mx.law_isProbability, hClass.stationary_start.2,
    hClass.sequential_ignorability.2, m.kernel_law.2⟩

/-- Two generated laws have the same state-history marginal at every epoch. For
[the time horizon](hyp:T), [the observed-state count](hyp:nX), [the hidden-state count](hyp:nH),
[the candidate-policy count](hyp:M), [the measure](hyp:μ), [the ν](hyp:ν),
[the measure assumption](hyp:hμ), [the ν assumption](hyp:hν), and the epoch index, this
establishes [the selector generated pre history unique result](goal). -/
-- @node: selector_generated_preHistory_unique
lemma selector_generated_preHistory_unique {T nX nH : Nat}
    (M : RawPomdpExperiment T nX nH)
    {μ ν : Measure (FullTrajectory T nX nH)}
    (hμ : RawGeneratedPathLaw M μ) (hν : RawGeneratedPathLaw M ν) :
    ∀ t : Fin T, μ.map (histStateView t) = ν.map (histStateView t) := by
  have go : ∀ d, ∀ t : Fin T, t.val = d →
      μ.map (histStateView t) = ν.map (histStateView t) := by
    intro d
    induction d using Nat.strong_induction_on with
    | h d ih =>
      intro t ht
      cases d with
      | zero =>
          have hstate : μ.map (stateAt 0) = ν.map (stateAt 0) := by
            apply Measure.ext_of_singleton
            intro s
            rw [hμ.2.1 s, hν.2.1 s]
          let embed : JointState nX nH → StateHistoryView T nX nH t :=
            fun s ↦ ((fun i ↦ (Fin.cast ht i).elim0,
              fun i ↦ (Fin.cast ht i).elim0), s)
          have hembed : Measurable embed := by unfold embed; fun_prop
          have hpre (w : FullTrajectory T nX nH) :
              embed (stateAt 0 w) = histStateView t w := by
            unfold embed histStateView curState prefixIndex stateAt
            apply Prod.ext
            · apply Prod.ext
              · funext i
                exact (Fin.cast ht i).elim0
              · funext i
                exact (Fin.cast ht i).elim0
            · apply congrArg w.1
              apply Fin.ext
              simp [ht]
          rw [show μ.map (histStateView t) = (μ.map (stateAt 0)).map embed by
                rw [Measure.map_map hembed (by unfold stateAt; fun_prop)]
                apply Measure.map_congr
                filter_upwards [] with w
                exact (hpre w).symm,
            show ν.map (histStateView t) = (ν.map (stateAt 0)).map embed by
                rw [Measure.map_map hembed (by unfold stateAt; fun_prop)]
                apply Measure.map_congr
                filter_upwards [] with w
                exact (hpre w).symm,
            hstate]
      | succ d =>
          have hdt : d + 1 < T := by simpa [ht] using t.isLt
          let u : Fin T := ⟨d, Nat.lt_of_succ_lt hdt⟩
          have hpre : μ.map (histStateView u) = ν.map (histStateView u) :=
            ih d (Nat.lt_succ_self d) u rfl
          have haction : μ.map (histActionPair u) = ν.map (histActionPair u) := by
            rw [hμ.2.2.1 u, hν.2.2.1 u, hpre]
          have hjoint : μ.map (histNextPair u) = ν.map (histNextPair u) := by
            rw [hμ.2.2.2 u, hν.2.2.2 u, haction]
          have hu : u.val + 1 < T := by dsimp [u]; omega
          have hepoch : nextEpoch u hu = t := by
            apply Fin.ext
            dsimp [nextEpoch, u]
            omega
          rw [← hepoch]
          rw [show μ.map (histStateView (nextEpoch u hu)) =
                (μ.map (histNextPair u)).map
                  (succStateHistoryEquiv (nX := nX) (nH := nH) u hu) by
                rw [Measure.map_map (measurable_succStateHistoryEquiv u hu)
                  (measurable_histNextPair u)]
                apply Measure.map_congr
                filter_upwards [] with w
                exact (succStateHistoryEquiv_histNextPair u hu w).symm,
            show ν.map (histStateView (nextEpoch u hu)) =
                (ν.map (histNextPair u)).map
                  (succStateHistoryEquiv (nX := nX) (nH := nH) u hu) by
                rw [Measure.map_map (measurable_succStateHistoryEquiv u hu)
                  (measurable_histNextPair u)]
                apply Measure.map_congr
                filter_upwards [] with w
                exact (succStateHistoryEquiv_histNextPair u hu w).symm,
            hjoint]
  intro t
  exact go t.val t rfl

/-- Generated finite path laws are unique. For [the time horizon](hyp:T),
[the observed-state count](hyp:nX), [the hidden-state count](hyp:nH),
[the candidate-policy count](hyp:M), [the measure](hyp:μ), [the ν](hyp:ν),
[the measure assumption](hyp:hμ), and [the ν assumption](hyp:hν), this establishes
[the selector generated path law unique result](goal). -/
-- @node: selector_generated_path_law_unique
lemma selector_generated_path_law_unique {T nX nH : Nat}
    (M : RawPomdpExperiment T nX nH)
    {μ ν : Measure (FullTrajectory T nX nH)}
    (hμ : RawGeneratedPathLaw M μ) (hν : RawGeneratedPathLaw M ν) : μ = ν := by
  cases T with
  | zero =>
      have hstate : μ.map (stateAt 0) = ν.map (stateAt 0) := by
        apply Measure.ext_of_singleton
        intro s
        rw [hμ.2.1 s, hν.2.1 s]
      let decode : JointState nX nH → FullTrajectory 0 nX nH :=
        fun s ↦ (fun _ ↦ s, fun i ↦ i.elim0)
      have hdecode : Measurable decode := by unfold decode; fun_prop
      have hleft (w : FullTrajectory 0 nX nH) : decode (stateAt 0 w) = w := by
        apply Prod.ext
        · funext i
          exact Fin.eq_zero i ▸ rfl
        · funext i
          exact i.elim0
      have hencode : Measurable (stateAt 0 : FullTrajectory 0 nX nH → _) := by
        unfold stateAt
        fun_prop
      have hcomp : decode ∘ (stateAt 0 : FullTrajectory 0 nX nH → _) = id := by
        funext w
        exact hleft w
      have h := congrArg (Measure.map decode) hstate
      rw [Measure.map_map hdecode hencode, Measure.map_map hdecode hencode,
        hcomp, Measure.map_id] at h
      simpa using h
  | succ d =>
      let t : Fin (d + 1) := Fin.last d
      have hpre := selector_generated_preHistory_unique M hμ hν t
      have haction : μ.map (histActionPair t) = ν.map (histActionPair t) := by
        rw [hμ.2.2.1 t, hν.2.2.1 t, hpre]
      have hjoint : μ.map (histNextPair t) = ν.map (histNextPair t) := by
        rw [hμ.2.2.2 t, hν.2.2.2 t, haction]
      let decode : ActionHistoryView (d + 1) nX nH t × Step nX nH →
          FullTrajectory (d + 1) nX nH := fun q ↦
        (Fin.snoc (Fin.snoc q.1.1.1.1 q.1.1.2) q.2.2,
          Fin.snoc q.1.1.1.2 (q.1.2, q.2.1))
      have hdecode : Measurable decode := by unfold decode; fun_prop
      have hleft (w : FullTrajectory (d + 1) nX nH) :
          decode (histNextPair t w) = w := by
        change (Fin.snoc (Fin.snoc (Fin.init (Fin.init w.1))
            ((Fin.init w.1) (Fin.last d))) (w.1 (Fin.last (d + 1))),
          Fin.snoc (Fin.init w.2) (w.2 (Fin.last d))) = w
        rw [Fin.snoc_init_self, Fin.snoc_init_self, Fin.snoc_init_self]
      have hencode : Measurable (@histNextPair (d + 1) nX nH t) :=
        measurable_histNextPair t
      have hcomp : decode ∘ (@histNextPair (d + 1) nX nH t) = id := by
        funext w
        exact hleft w
      have h := congrArg (Measure.map decode) hjoint
      rw [Measure.map_map hdecode hencode, Measure.map_map hdecode hencode,
        hcomp, Measure.map_id] at h
      simpa using h

/-- If the structural stationary segment is certified by the same history factorizations,
uniqueness identifies it with the model's actual law. For [the time horizon](hyp:T),
[the candidate-policy count](hyp:M), [the mixing scale](hyp:t0),
[the policy-overlap scale](hyp:zeta), [the latent-overlap radius](hyp:C), [the model](hyp:m),
[the class assumption](hyp:hClass), and [the segment assumption](hyp:hsegment), this establishes
[the selector actual law equality stationary segment of generated result](goal). -/
-- @node: selector_actual_law_eq_stationary_segment_of_generated
lemma selector_actual_law_eq_stationary_segment_of_generated {T M : Nat}
    (t0 zeta C : ℝ) (m : ModelIndex T M)
    (hClass : PolicyListClass t0 zeta C m)
    (hsegment : RawGeneratedPathLaw m.Mx.toRawB
      (segmentLaw m hClass.finite_state
        (stationaryLaw (policyKernel m.Mx.toRawB m.Mx.b)) T)) :
    m.Mx.law = segmentLaw m hClass.finite_state
      (stationaryLaw (policyKernel m.Mx.toRawB m.Mx.b)) T := by
  exact selector_generated_path_law_unique m.Mx.toRawB
    (selector_actual_rawGeneratedPathLaw t0 zeta C m hClass) hsegment

end CausalSmith.Stat.PomdpPolicyclassRegret
