/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan

# Indicator spans and partition-cell statistics over a weighted support

For a `WeightedSupport R` (see `Causalean/Panel/Weighted/Support.lean`) and a
classifier `G : R → 𝒢` (or two classifiers `G, T` on parallel axes), we
build:

* the **one-axis indicator span** `indicatorSpan G : Submodule ℝ (R → ℝ)`
  generated by the singleton indicators `r ↦ if G r = g then 1 else 0`,
  one per value `g : 𝒢`;
* the **two-axis indicator span** `twoAxisIndicatorSpan G T` generated by
  the union of the per-axis singleton indicators on the two classifiers;
* partition-cell statistics `cellMass G g` and positive-mass cell means
  `cellMean F G g hpos` on a `WeightedSupport R`.

This is the finite, non-measure-theoretic counterpart of the cell-bridge
constructions used elsewhere in the panel library. It is intended for weighted
finite supports where sums over observed records are the primitive operation.
-/

import Causalean.Tactic.Attr
import Causalean.Panel.Weighted.Support
import Mathlib.Algebra.Module.Submodule.Basic
import Mathlib.Algebra.Module.Submodule.Lattice
import Mathlib.Algebra.Module.Pi
import Mathlib.Algebra.BigOperators.Ring.Finset
import Mathlib.Data.Fintype.Basic
import Mathlib.Tactic.Ring

/-! # Indicator spans and partition-cell statistics

This file provides finite-cell partition algebra over a weighted support.
It defines singleton cell indicators `cellIndicator`, one-axis spans
`indicatorSpan`, two-axis spans `twoAxisIndicatorSpan`, and weighted
partition-cell statistics `WeightedSupport.cellMass`, `cellMean`, and
`jointCellMass`.

The declarations are the finite-support interface for nuisance spaces generated
by classifier cells and for weighted averages over positive-mass partition
cells. -/

open scoped BigOperators

namespace Causalean
namespace Panel.Weighted

/-! ### Cell indicators -/

/-- For [a classifier from records to cells](hyp:G) and [a chosen cell](hyp:g), the [cell-indicator array](goal) assigns one to each record in the chosen cell and zero to every other record.

The cell indicator is one on records classified into a given cell and zero elsewhere. -/
def cellIndicator {R 𝒢 : Type*} [DecidableEq 𝒢]
    (G : R → 𝒢) (g : 𝒢) : R → ℝ :=
  fun r => if G r = g then (1 : ℝ) else 0

/-- The cell indicator evaluates by checking whether the record belongs to the
chosen classifier cell. -/
@[simp, causal_defs_simps]
lemma cellIndicator_apply {R 𝒢 : Type*} [DecidableEq 𝒢]
    (G : R → 𝒢) (g : 𝒢) (r : R) :
    cellIndicator G g r = if G r = g then (1 : ℝ) else 0 := rfl

/-! ### One-axis indicator span -/

/-- For a finite collection of distinguishable cells and [a classifier from records to those cells](hyp:G), the [one-axis indicator span](goal) is the real vector space of arrays that are weighted sums of the classifier's singleton cell indicators, with one real coefficient for each cell.

The one-axis indicator span contains exactly the finite linear combinations of singleton indicators for one classifier. -/
def indicatorSpan {R 𝒢 : Type*} [Fintype 𝒢] [DecidableEq 𝒢]
    (G : R → 𝒢) : Submodule ℝ (R → ℝ) where
  carrier := { f | ∃ c : 𝒢 → ℝ, ∀ r : R, f r = ∑ g, c g * cellIndicator G g r }
  zero_mem' := by
    refine ⟨fun _ => 0, ?_⟩
    intro r; simp
  add_mem' := by
    rintro f₁ f₂ ⟨c₁, hc₁⟩ ⟨c₂, hc₂⟩
    refine ⟨fun g => c₁ g + c₂ g, ?_⟩
    intro r
    have : f₁ r + f₂ r =
        (∑ g, c₁ g * cellIndicator G g r) + ∑ g, c₂ g * cellIndicator G g r := by
      rw [hc₁ r, hc₂ r]
    calc (f₁ + f₂) r
        = f₁ r + f₂ r := rfl
      _ = (∑ g, c₁ g * cellIndicator G g r)
            + ∑ g, c₂ g * cellIndicator G g r := this
      _ = ∑ g, (c₁ g + c₂ g) * cellIndicator G g r := by
            rw [← Finset.sum_add_distrib]
            refine Finset.sum_congr rfl ?_
            intro g _
            ring
  smul_mem' := by
    rintro s f ⟨c, hc⟩
    refine ⟨fun g => s * c g, ?_⟩
    intro r
    have hsr : (s • f) r = s * f r := rfl
    rw [hsr, hc r]
    calc s * ∑ g, c g * cellIndicator G g r
        = ∑ g, s * (c g * cellIndicator G g r) := Finset.mul_sum _ _ _
      _ = ∑ g, (s * c g) * cellIndicator G g r := by
            refine Finset.sum_congr rfl ?_
            intro g _
            ring

/-- Membership in the one-axis indicator span is equivalent to having
coefficients on the classifier cells whose weighted sum reproduces the array. -/
lemma mem_indicatorSpan_iff {R 𝒢 : Type*} [Fintype 𝒢] [DecidableEq 𝒢]
    (G : R → 𝒢) (f : R → ℝ) :
    f ∈ indicatorSpan G ↔
      ∃ c : 𝒢 → ℝ, ∀ r : R, f r = ∑ g, c g * cellIndicator G g r :=
  Iff.rfl

/-- Each singleton cell indicator belongs to the span generated by all cells of
the same classifier. -/
lemma cellIndicator_mem_indicatorSpan {R 𝒢 : Type*} [Fintype 𝒢] [DecidableEq 𝒢]
    (G : R → 𝒢) (g : 𝒢) :
    cellIndicator G g ∈ indicatorSpan G := by
  classical
  refine ⟨fun g' => if g' = g then (1 : ℝ) else 0, ?_⟩
  intro r
  -- exactly one summand survives (the one with `g' = g`); equals
  -- `cellIndicator G g r`.
  have hsum :
      (∑ g' ∈ (Finset.univ : Finset 𝒢),
          (if g' = g then (1 : ℝ) else 0) * cellIndicator G g' r) =
        (if g = g then (1 : ℝ) else 0) * cellIndicator G g r := by
    refine Finset.sum_eq_single g ?_ ?_
    · intro b _ hbne
      simp [hbne]
    · intro hnot
      exact False.elim (hnot (Finset.mem_univ _))
  rw [hsum]
  simp

/-! ### Two-axis indicator span -/

/-- For two finite collections of distinguishable cells, [a first classifier](hyp:G) and [a second classifier](hyp:T) from records to their respective cells, the [two-axis indicator span](goal) is the real vector space generated jointly by the singleton indicators of both classifiers.

The two-axis indicator span contains sums of one-axis indicator functions from two classifiers. -/
def twoAxisIndicatorSpan {R 𝒢 𝒯 : Type*}
    [Fintype 𝒢] [DecidableEq 𝒢] [Fintype 𝒯] [DecidableEq 𝒯]
    (G : R → 𝒢) (T : R → 𝒯) : Submodule ℝ (R → ℝ) :=
  indicatorSpan G ⊔ indicatorSpan T

/-- The first classifier's indicator span is contained in the two-axis
indicator span. -/
lemma indicatorSpan_le_twoAxisIndicatorSpan
    {R 𝒢 𝒯 : Type*} [Fintype 𝒢] [DecidableEq 𝒢] [Fintype 𝒯] [DecidableEq 𝒯]
    (G : R → 𝒢) (T : R → 𝒯) :
    indicatorSpan G ≤ twoAxisIndicatorSpan G T := le_sup_left

/-- The second classifier's indicator span is contained in the two-axis
indicator span. -/
lemma indicatorSpan_le_twoAxisIndicatorSpan_right
    {R 𝒢 𝒯 : Type*} [Fintype 𝒢] [DecidableEq 𝒢] [Fintype 𝒯] [DecidableEq 𝒯]
    (G : R → 𝒢) (T : R → 𝒯) :
    indicatorSpan T ≤ twoAxisIndicatorSpan G T := le_sup_right

/-! ### Partition-cell statistics on a `WeightedSupport` -/

namespace WeightedSupport

variable {R : Type*} [Fintype R] [DecidableEq R]

/-- For [a finite record set](hyp:R), [a weighted support](hyp:c), [a classifier from records to distinguishable cells](hyp:G), and [a chosen cell](hyp:g), the [cell mass](goal) is the sum of the support weights of all observed records classified into that cell.

The cell mass is the total weight of observed records in one classifier cell. -/
def cellMass {𝒢 : Type*} [DecidableEq 𝒢]
    (c : WeightedSupport R) (G : R → 𝒢) (g : 𝒢) : ℝ :=
  ∑ r ∈ c.observed, c.weight r * cellIndicator G g r

/-- The cell mass unfolds to the weighted sum of the corresponding cell
indicator over observed records. -/
@[simp] lemma cellMass_def {𝒢 : Type*} [DecidableEq 𝒢]
    (c : WeightedSupport R) (G : R → 𝒢) (g : 𝒢) :
    c.cellMass G g = ∑ r ∈ c.observed, c.weight r * cellIndicator G g r := rfl

/-- Every classifier cell has nonnegative total weight. -/
lemma cellMass_nonneg {𝒢 : Type*} [DecidableEq 𝒢]
    (c : WeightedSupport R) (G : R → 𝒢) (g : 𝒢) :
    0 ≤ c.cellMass G g := by
  refine Finset.sum_nonneg ?_
  intro r hr
  by_cases h : G r = g
  · have hw : 0 ≤ c.weight r := (c.weight_pos r hr).le
    simp [cellIndicator, h, hw]
  · simp [cellIndicator, h]

/-- For [a finite record set](hyp:R), [a weighted support](hyp:c), [an outcome array](hyp:F), [a classifier from records to distinguishable cells](hyp:G), [a chosen cell](hyp:g), and [the condition that this cell has strictly positive mass](hyp:_hpos), the [cell mean](goal) is the weighted average of the outcome over observed records in that cell.

On a classifier cell with positive observed mass, the cell mean is the ordinary weighted average of the outcome over observed records in that cell.

The explicit positivity guard rules out zero-mass cells, where the ordinary
weighted average is not defined. -/
noncomputable def cellMean {𝒢 : Type*} [DecidableEq 𝒢]
    (c : WeightedSupport R) (F : R → ℝ) (G : R → 𝒢) (g : 𝒢)
    (_hpos : 0 < c.cellMass G g) : ℝ :=
  (∑ r ∈ c.observed, c.weight r * F r * cellIndicator G g r) / c.cellMass G g

/-- On [a classifier cell `g` with strictly positive total weight](hyp:hpos), [multiplying the
cell mean of `F` by the cell's mass recovers the weighted sum of `F` over observed records in
that cell](goal). -/
lemma cellMean_mul_cellMass {𝒢 : Type*} [DecidableEq 𝒢]
    (c : WeightedSupport R) (F : R → ℝ) (G : R → 𝒢) (g : 𝒢)
    (hpos : 0 < c.cellMass G g) :
    c.cellMean F G g hpos * c.cellMass G g =
      ∑ r ∈ c.observed, c.weight r * F r * cellIndicator G g r := by
  unfold cellMean
  exact div_mul_cancel₀ _ (ne_of_gt hpos)

/-- For [a finite record set](hyp:R), [a weighted support](hyp:c), [a first classifier into distinguishable cells](hyp:G), [a second classifier into distinguishable cells](hyp:T), [a chosen cell of the first classifier](hyp:g), and [a chosen cell of the second classifier](hyp:t), the [joint cell mass](goal) is the sum of the support weights of observed records lying in both chosen cells.

The joint cell mass is the total weight of observed records lying in a given pair of classifier cells. -/
def jointCellMass {𝒢 𝒯 : Type*} [DecidableEq 𝒢] [DecidableEq 𝒯]
    (c : WeightedSupport R) (G : R → 𝒢) (T : R → 𝒯)
    (g : 𝒢) (t : 𝒯) : ℝ :=
  ∑ r ∈ c.observed, c.weight r * cellIndicator G g r * cellIndicator T t r

/-- The joint cell mass unfolds to the weighted sum of the two corresponding
cell indicators over observed records. -/
@[simp] lemma jointCellMass_def {𝒢 𝒯 : Type*} [DecidableEq 𝒢] [DecidableEq 𝒯]
    (c : WeightedSupport R) (G : R → 𝒢) (T : R → 𝒯) (g : 𝒢) (t : 𝒯) :
    c.jointCellMass G T g t =
      ∑ r ∈ c.observed, c.weight r
        * cellIndicator G g r * cellIndicator T t r := rfl

end WeightedSupport

end Panel.Weighted
end Causalean
