/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan

# σ-algebra-based conditional expectation on `POCFBundle`s

Lifts the single-`POVar` conditioning machinery in `CondExpTooling.lean` to a
`POCFBundle`, i.e. conditioning on the joint cf-value map of a tuple of
regimed variables.  Used by the DTR / multi-stage backdoor identification
arguments where the conditioning σ-algebra is generated by a *bundle* of
covariates rather than a single one.
-/

import Causalean.Tactic.Attr
import Causalean.PO.Assumptions.IndepCF
import Causalean.PO.Conditioning.CondExpTooling
import Mathlib.Probability.ConditionalExpectation
import Mathlib.MeasureTheory.Function.ConditionalExpectation.PullOut

/-! # Bundle Conditional Expectations

This file defines the σ-algebra generated by a bundle of regimed
potential-outcome variables and provides conditional expectations, conditional
ratios, and bundle-conditioned independence statements relative to that
σ-algebra. It extends the single-variable conditioning interface to finite
counterfactual bundles.

The key definitions are `POCFBundle.sigma`, `POCFBundle.condExpGiven`,
`POCFBundle.condExpRatio`, and `POSystem.CondIndepCFBundle`.  The file also
provides measurability, integrability, tower, pull-out, a.e.-congruence, ratio,
and projection lemmas used by bundle-conditioned identification arguments. -/

namespace Causalean
namespace PO

open MeasureTheory ProbabilityTheory

noncomputable section

namespace POCFBundle

variable {P : POSystem} (B : POCFBundle P)

/-- For a [potential-outcome system](hyp:P) and [a finite bundle of counterfactual
variables](hyp:B), the [conditioning σ-algebra of the bundle](goal) is the σ-algebra on
the sample space generated by jointly observing every counterfactual value in that bundle.

It generalizes the conditioning σ-algebra of one counterfactual variable to the joint value map
of a finite bundle. -/
def sigma : MeasurableSpace P.Ω :=
  MeasurableSpace.comap B.jointValue inferInstance

/-- The conditioning σ-algebra `B.sigma` is a sub-σ-algebra of the ambient
σ-algebra on `P.Ω`. -/
lemma sigma_le : B.sigma ≤ (inferInstance : MeasurableSpace P.Ω) :=
  B.measurable_jointValue.comap_le

/-- The bundle's joint counterfactual-value map is measurable for the very
σ-algebra it generates: conditioning information always determines the values
that were conditioned on. This is the generator lemma that lets automation
discharge measurability of bundle-value compositions relative to `B.sigma`. -/
@[fun_prop]
lemma measurable_jointValue_sigma : Measurable[B.sigma] B.jointValue :=
  Measurable.of_comap_le le_rfl

/-- For a [potential-outcome system](hyp:P), [a counterfactual bundle](hyp:B), [a
real-valued quantity on the sample space](hyp:g), and [a measure on that sample space](hyp:μ),
the [bundle conditional expectation](goal) is the conditional expectation of the quantity
given the σ-algebra generated by jointly observing the bundle.

This is the bundle analogue of conditional expectation given a single counterfactual variable. -/
def condExpGiven (g : P.Ω → ℝ) (μ : Measure P.Ω := P.μ) : P.Ω → ℝ :=
  μ[g | B.sigma]

/-- Averaging a real-valued sample-space quantity given a counterfactual bundle
is exactly the standard conditional expectation given the σ-algebra that the
bundle generates.

This is the simp-shaped form of the definition of the bundle conditional
expectation: rewriting with it replaces the project wrapper by the underlying
measure-theoretic conditional expectation, after which the standard
conditional-expectation API applies. -/
@[condexp_simps]
lemma condExpGiven_eq (g : P.Ω → ℝ) (μ : Measure P.Ω) :
    B.condExpGiven g μ = μ[g | B.sigma] :=
  rfl

/-- `condExpGiven` yields a function strongly measurable w.r.t. `B.sigma`. -/
@[fun_prop]
lemma stronglyMeasurable_condExpGiven_comap (g : P.Ω → ℝ) {μ : Measure P.Ω} :
    StronglyMeasurable[B.sigma] (B.condExpGiven g μ) :=
  MeasureTheory.stronglyMeasurable_condExp
    (μ := μ) (m := B.sigma) (f := g)

/-- `condExpGiven` yields a strongly measurable function w.r.t. the ambient
σ-algebra. -/
@[fun_prop]
lemma stronglyMeasurable_condExpGiven (g : P.Ω → ℝ) {μ : Measure P.Ω} :
    StronglyMeasurable (B.condExpGiven g μ) :=
  (B.stronglyMeasurable_condExpGiven_comap g).mono B.sigma_le

/-- Mathlib's totalized conditional expectation given the bundle's σ-algebra is
integrable, even when the original sample-space function is not assumed
integrable. -/
@[fun_prop]
lemma integrable_condExpGiven (g : P.Ω → ℝ) {μ : Measure P.Ω} :
    Integrable (B.condExpGiven g μ) μ := by
  simpa [condexp_simps] using
    (MeasureTheory.integrable_condExp (μ := μ) (m := B.sigma) (f := g))

/-! ### Linearity (mirrors the `POVar` versions)

The primed forms take their integrability side conditions as `autoParam`s discharged by
`fun_prop`; the unprimed forms take them explicitly, matching Mathlib's
`condExp_add`/`condExp_sub`. -/

/-- Linearity of the bundle conditional expectation: additivity. -/
lemma condExpGiven_add {f g : P.Ω → ℝ} {μ : Measure P.Ω}
    (hf : Integrable f μ) (hg : Integrable g μ) :
    B.condExpGiven (f + g) μ =ᵐ[μ] B.condExpGiven f μ + B.condExpGiven g μ := by
  simpa [condexp_simps] using MeasureTheory.condExp_add (μ := μ) hf hg B.sigma

/-- Linearity of the bundle conditional expectation: subtraction. -/
lemma condExpGiven_sub {f g : P.Ω → ℝ} {μ : Measure P.Ω}
    (hf : Integrable f μ) (hg : Integrable g μ) :
    B.condExpGiven (f - g) μ =ᵐ[μ] B.condExpGiven f μ - B.condExpGiven g μ := by
  simpa [condexp_simps] using MeasureTheory.condExp_sub (μ := μ) hf hg B.sigma

/-- Additivity of the bundle conditional expectation with the integrability side
conditions discharged automatically.

Same statement as `POCFBundle.condExpGiven_add`, but the two integrability hypotheses are
`autoParam`s proved by `fun_prop`: a call site holding the witnesses in context supplies
nothing, and one whose integrands are built from `fun_prop`-tagged constructions needs no
witnesses at all. Passing them explicitly still works. -/
lemma condExpGiven_add' {f g : P.Ω → ℝ} {μ : Measure P.Ω}
    (hf : Integrable f μ := by fun_prop) (hg : Integrable g μ := by fun_prop) :
    B.condExpGiven (f + g) μ =ᵐ[μ] B.condExpGiven f μ + B.condExpGiven g μ :=
  B.condExpGiven_add hf hg

/-- Subtractivity of the bundle conditional expectation with the integrability side
conditions discharged automatically; see `POCFBundle.condExpGiven_add'`. -/
lemma condExpGiven_sub' {f g : P.Ω → ℝ} {μ : Measure P.Ω}
    (hf : Integrable f μ := by fun_prop) (hg : Integrable g μ := by fun_prop) :
    B.condExpGiven (f - g) μ =ᵐ[μ] B.condExpGiven f μ - B.condExpGiven g μ :=
  B.condExpGiven_sub hf hg

/-- Scalar homogeneity of the bundle conditional expectation. No integrability is
required. -/
lemma condExpGiven_smul (k : ℝ) (g : P.Ω → ℝ) {μ : Measure P.Ω} :
    B.condExpGiven (k • g) μ =ᵐ[μ] k • B.condExpGiven g μ := by
  simpa [condexp_simps] using MeasureTheory.condExp_smul (μ := μ) k g B.sigma

/-- Negation passes through the bundle conditional expectation. No integrability is
required. -/
lemma condExpGiven_neg (g : P.Ω → ℝ) {μ : Measure P.Ω} :
    B.condExpGiven (-g) μ =ᵐ[μ] -B.condExpGiven g μ := by
  simpa [condexp_simps] using MeasureTheory.condExp_neg (μ := μ) g B.sigma

/-- A constant is its own bundle conditional expectation: on a finite measure, averaging a
constant given a counterfactual bundle returns that constant, everywhere (not merely
almost everywhere). -/
lemma condExpGiven_const (k : ℝ) {μ : Measure P.Ω} [IsFiniteMeasure μ] :
    B.condExpGiven (fun _ => k) μ = fun _ => k :=
  MeasureTheory.condExp_const (μ := μ) B.sigma_le k

/-- The bundle conditional expectation commutes with a finite sum, with the family-wide
integrability side condition discharged automatically by `fun_prop`. -/
lemma condExpGiven_finsetSum' {ι : Type*} {s : Finset ι} {F : ι → P.Ω → ℝ}
    {μ : Measure P.Ω}
    (hF : ∀ i ∈ s, Integrable (F i) μ := by intro i _; fun_prop) :
    B.condExpGiven (∑ i ∈ s, F i) μ =ᵐ[μ] ∑ i ∈ s, B.condExpGiven (F i) μ := by
  simpa [condexp_simps] using MeasureTheory.condExp_finsetSum (μ := μ) hF B.sigma

/-! ### Tower property and pull-out (mirrors `POVar` versions) -/

/-- Tower property over an arbitrary smaller sub-σ-algebra `m ≤ B.sigma`.
Requires the usual `SigmaFinite` hypothesis on the trim of `μ` to
`B.sigma`. -/
lemma condExpGiven_tower_of_le {g : P.Ω → ℝ} {μ : Measure P.Ω}
    {m : MeasurableSpace P.Ω} (hm : m ≤ B.sigma)
    [SigmaFinite (μ.trim B.sigma_le)] :
    μ[B.condExpGiven g μ | m] =ᵐ[μ] μ[g | m] := by
  simpa [condexp_simps] using
    MeasureTheory.condExp_condExp_of_le (μ := μ) (f := g) hm B.sigma_le

/-- Pull-out-left for `condExpGiven`: if `f` is strongly measurable w.r.t.
`B.sigma`, then `μ[f·g | B.sigma] =ᵐ f · μ[g | B.sigma]`. -/
lemma condExpGiven_mul_of_stronglyMeasurable_left
    {f g : P.Ω → ℝ} {μ : Measure P.Ω}
    (hf : StronglyMeasurable[B.sigma] f)
    (hfg : Integrable (f * g) μ) (hg : Integrable g μ) :
    B.condExpGiven (f * g) μ =ᵐ[μ] f * B.condExpGiven g μ := by
  simpa [condexp_simps] using
    MeasureTheory.condExp_mul_of_stronglyMeasurable_left
      (μ := μ) (m := B.sigma) hf hfg hg

/-- Pull-out-right for `condExpGiven`. -/
lemma condExpGiven_mul_of_stronglyMeasurable_right
    {f g : P.Ω → ℝ} {μ : Measure P.Ω}
    (hg : StronglyMeasurable[B.sigma] g)
    (hfg : Integrable (f * g) μ) (hf : Integrable f μ) :
    B.condExpGiven (f * g) μ =ᵐ[μ] B.condExpGiven f μ * g := by
  simpa [condexp_simps] using
    MeasureTheory.condExp_mul_of_stronglyMeasurable_right
      (μ := μ) (m := B.sigma) hg hfg hf

/-- Indicator pull-out for `condExpGiven`: if `s` is `B.sigma`-measurable, the
indicator `1_s` factors out of the bundle conditional expectation. -/
lemma condExpGiven_indicator_mul
    {s : Set P.Ω} {g : P.Ω → ℝ} {μ : Measure P.Ω}
    (hs : MeasurableSet[B.sigma] s)
    (hg : Integrable g μ) :
    B.condExpGiven (s.indicator (fun _ => (1 : ℝ)) * g) μ
      =ᵐ[μ] s.indicator (fun _ => (1 : ℝ)) * B.condExpGiven g μ := by
  have hsg : Integrable (s.indicator (fun _ => (1 : ℝ)) * g) μ := by
    have hs_meas : AEStronglyMeasurable (s.indicator (fun _ => (1 : ℝ))) μ :=
      StronglyMeasurable.aestronglyMeasurable
        (((stronglyMeasurable_const (b := (1 : ℝ))).indicator hs).mono B.sigma_le)
    refine hg.mono
      (hs_meas.mul hg.aestronglyMeasurable) ?_
    refine Filter.Eventually.of_forall (fun ω => ?_)
    by_cases hω : ω ∈ s <;> simp [Set.indicator, hω]
  exact B.condExpGiven_mul_of_stronglyMeasurable_left
    ((stronglyMeasurable_const (b := (1 : ℝ))).indicator hs) hsg hg

/-- a.e. congruence for `condExpGiven`: if `f =ᵐ g`, then their bundle
conditional expectations agree a.e. -/
lemma condExpGiven_congr_ae {f g : P.Ω → ℝ} {μ : Measure P.Ω}
    (h : f =ᵐ[μ] g) : B.condExpGiven f μ =ᵐ[μ] B.condExpGiven g μ := by
  simp only [condexp_simps]
  exact MeasureTheory.condExp_congr_ae h

/-! ### Conditional ratio (bundle analogue of `POVar.condExpRatio`) -/

/-- For a [potential-outcome system](hyp:P), [a counterfactual bundle](hyp:B), [two
real-valued quantities on the sample space](hyp:g,h), and [a measure on that sample space](hyp:μ),
the [bundle conditional-expectation ratio](goal) maps each sample point to the conditional
expectation of the first quantity given the bundle divided by that of the second [at that
sample point](step:1).

This ratio compares two real-valued sample-space quantities after conditioning on the information
in the bundle. -/
def condExpRatio (g h : P.Ω → ℝ) (μ : Measure P.Ω := P.μ) : P.Ω → ℝ :=
  fun ω => (B.condExpGiven g μ ω) / (B.condExpGiven h μ ω)

/-- The bundle conditional-expectation ratio is, pointwise, the quotient of the
two bundle conditional expectations.

This is the simp-shaped form of the definition of the bundle conditional ratio.
It is stated in unapplied form so that it also fires on side conditions about
the ratio *as a function* (measurability, a.e. equalities); applying it to a
sample point recovers the pointwise quotient. -/
@[condexp_simps]
lemma condExpRatio_def (g h : P.Ω → ℝ) (μ : Measure P.Ω) :
    B.condExpRatio g h μ = fun ω => B.condExpGiven g μ ω / B.condExpGiven h μ ω :=
  rfl

/-- The conditional-ratio function of two real integrands given a
counterfactual bundle is measurable. -/
@[fun_prop]
lemma measurable_condExpRatio (g h : P.Ω → ℝ) {μ : Measure P.Ω} :
    Measurable (B.condExpRatio g h μ) := by
  simp only [condexp_simps]
  exact (B.stronglyMeasurable_condExpGiven g).measurable.div
    (B.stronglyMeasurable_condExpGiven h).measurable

/-- The conditional-ratio function of two real integrands given a
counterfactual bundle is strongly measurable. -/
@[fun_prop]
lemma stronglyMeasurable_condExpRatio (g h : P.Ω → ℝ) {μ : Measure P.Ω} :
    StronglyMeasurable (B.condExpRatio g h μ) :=
  (B.measurable_condExpRatio g h).stronglyMeasurable

/-- **Characterisation of bundle `condExpRatio` via a product identity.** -/
lemma condExpRatio_eq_of_mul {g h target : P.Ω → ℝ} {μ : Measure P.Ω}
    (hprod : B.condExpGiven g μ =ᵐ[μ] B.condExpGiven h μ * target)
    (hne : ∀ᵐ ω ∂μ, B.condExpGiven h μ ω ≠ 0) :
    B.condExpRatio g h μ =ᵐ[μ] target := by
  simp only [condexp_simps]
  filter_upwards [hprod, hne] with ω hω hne
  simp only [Pi.mul_apply, condexp_simps] at hω hne
  rw [hω]
  field_simp

end POCFBundle

/-- For a [potential-outcome system whose sample space is standard Borel](hyp:P), [a
measurable outcome space](hyp:α), [a potential-outcome variable taking values in that
space](hyp:a), [a counterfactual bundle](hyp:B), [a conditioning counterfactual bundle](hyp:C),
and [a finite measure on the sample space](hyp:μ), the [conditional-independence assertion](goal)
states that the variable and the first bundle are conditionally independent given the σ-algebra
generated by jointly observing the conditioning bundle.

This is the bundle analogue of conditional independence given one counterfactual variable. -/
def POSystem.CondIndepCFBundle
    (P : POSystem) [StandardBorelSpace P.Ω]
    {α : Type*} [MeasurableSpace α]
    (a : RegimedVar P α) (B : POCFBundle P) (C : POCFBundle P)
    (μ : Measure P.Ω := P.μ) [IsFiniteMeasure μ] : Prop :=
  ProbabilityTheory.CondIndepFun C.sigma C.sigma_le a.value B.jointValue μ

namespace POSystem

variable {P : POSystem}

/-- Bridge: `CondIndepCFBundle` unfolds to `CondIndepFun` w.r.t. `C.sigma`. -/
lemma CondIndepCFBundle.toCondIndepFun
    [StandardBorelSpace P.Ω]
    {α : Type*} [MeasurableSpace α]
    {a : RegimedVar P α} {B C : POCFBundle P}
    {μ : Measure P.Ω} [IsFiniteMeasure μ] :
    P.CondIndepCFBundle a B C μ →
      ProbabilityTheory.CondIndepFun C.sigma C.sigma_le a.value B.jointValue μ := id

/-- **Bundle-conditional projection.** Given [a regimed variable `a` that is
conditionally independent, given the σ-algebra generated by a counterfactual
bundle `C`, of another counterfactual bundle `B`](hyp:h), then for [any
measurable function `ψ` of the joint value of `B`](hyp:hψ), [the value of `a`
remains conditionally independent, given `C`'s σ-algebra, of `ψ` composed with
the joint value of `B`](goal). -/
lemma CondIndepCFBundle.project
    [StandardBorelSpace P.Ω]
    {α β : Type*} [MeasurableSpace α] [MeasurableSpace β]
    {a : RegimedVar P α} {B C : POCFBundle P}
    {μ : Measure P.Ω} [IsFiniteMeasure μ]
    {ψ : (∀ i, B.type i) → β} (h : P.CondIndepCFBundle a B C μ)
    (hψ : Measurable ψ) :
    ProbabilityTheory.CondIndepFun C.sigma C.sigma_le a.value (ψ ∘ B.jointValue) μ :=
  h.toCondIndepFun.comp measurable_id hψ

end POSystem

end

end PO
end Causalean
