/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

import Causalean.Tactic.Attr
import Causalean.PO.Core.Variable
import Mathlib.Probability.ConditionalExpectation
import Mathlib.Probability.Independence.Conditional
import Mathlib.MeasureTheory.Function.ConditionalExpectation.PullOut
import Mathlib.MeasureTheory.Function.FactorsThrough

/-! # Conditional Expectations Given Potential-Outcome Variables

This file wraps conditional expectation so that the conditioning information is
the σ-algebra generated by the factual value of a potential-outcome variable.
It supports regression-style identification arguments by also defining ratios of
conditional expectations and their basic algebraic properties.

The public interface is centered on `POVar.condExpGiven`,
`POVar.condExpRatio`, tower and pull-out lemmas for `condExpGiven`, the product
identity `POVar.condExpRatio_eq_of_mul`, and the CATE-to-ATE integration lemma
`POVar.integral_sub_eq_integral_sub_of_condExpGiven_ae_eq`. -/

namespace Causalean.PO
open MeasureTheory ProbabilityTheory

noncomputable section

variable {P : POSystem} {γ : Type*} [MeasurableSpace γ]

/-- For [a potential-outcome system](hyp:P), [a conditioning variable on a measurable scale](hyp:c,γ), [a real-valued sample-space function](hyp:g), and [a measure on the sample space](hyp:μ), [the conditional expectation given the variable](goal) is the conditional expectation of the function given the σ-algebra generated by that variable's factual value.

Conditional expectation of an integrand `g : P.Ω → ℝ` given the
σ-algebra generated by the factual map of a `POVar` `c`.  Equal to
`μ[g | σ(c.factual)]` in Mathlib notation. -/
def POVar.condExpGiven (c : POVar P γ) (g : P.Ω → ℝ)
    (μ : Measure P.Ω := P.μ) : P.Ω → ℝ :=
  μ[g | MeasurableSpace.comap c.factual inferInstance]

/-- Averaging a real-valued sample-space quantity given a potential-outcome
variable is exactly the standard conditional expectation given the σ-algebra
generated by that variable's factual value.

This is the simp-shaped form of the definition of the variable-conditional
expectation: rewriting with it replaces the project wrapper by the underlying
measure-theoretic conditional expectation, after which the standard
conditional-expectation API applies. -/
@[condexp_simps]
lemma POVar.condExpGiven_eq (c : POVar P γ) (g : P.Ω → ℝ) (μ : Measure P.Ω) :
    c.condExpGiven g μ = μ[g | MeasurableSpace.comap c.factual inferInstance] :=
  rfl

/-- The conditioning σ-algebra `σ(c.factual)` is a sub-σ-algebra of the ambient
σ-algebra on `P.Ω`. -/
lemma POVar.comap_factual_le (c : POVar P γ) :
    MeasurableSpace.comap c.factual inferInstance ≤ (inferInstance : MeasurableSpace P.Ω) :=
  c.measurable_factual.comap_le

/-! ### Integrability helpers -/

/-- Multiplying an integrable function by a `POVar` factual indicator preserves
integrability. -/
@[fun_prop]
lemma POVar.integrable_mul_indicator
    {α : Type*} [MeasurableSpace α]
    (a : POVar P α) (x : α) (hx : MeasurableSet ({x} : Set α))
    {f : P.Ω → ℝ} {μ : Measure P.Ω} (hf : Integrable f μ) :
    Integrable (fun ω => f ω * a.indicator x ω) μ := by
  refine hf.mono
    (hf.aestronglyMeasurable.mul
      (a.measurable_indicator x hx).aestronglyMeasurable) ?_
  refine Filter.Eventually.of_forall (fun ω => ?_)
  rcases a.indicator_eq_one_or_zero x ω with h | h <;> simp [h]

/-- Multiplying a `POVar` factual indicator by an integrable function preserves
integrability.  This is the indicator-on-the-left companion of
`POVar.integrable_mul_indicator`; the two orders are distinct goal shapes for the
function-property tactics. -/
@[fun_prop]
lemma POVar.integrable_indicator_mul
    {α : Type*} [MeasurableSpace α]
    (a : POVar P α) (x : α) (hx : MeasurableSet ({x} : Set α))
    {f : P.Ω → ℝ} {μ : Measure P.Ω} (hf : Integrable f μ) :
    Integrable (fun ω => a.indicator x ω * f ω) μ := by
  have h := a.integrable_mul_indicator x hx hf
  exact h.congr (Filter.Eventually.of_forall (fun ω => by ring))

/-- On a value space whose one-point sets are measurable, multiplying an integrable
function by a `POVar` factual indicator preserves integrability. -/
@[fun_prop]
lemma POVar.integrable_mul_indicator_of_singleton
    {α : Type*} [MeasurableSpace α] [MeasurableSingletonClass α]
    (a : POVar P α) (x : α) {f : P.Ω → ℝ} {μ : Measure P.Ω}
    (hf : Integrable f μ) :
    Integrable (fun ω => f ω * a.indicator x ω) μ :=
  a.integrable_mul_indicator x (MeasurableSet.singleton x) hf

/-- On a value space whose one-point sets are measurable, multiplying a `POVar`
factual indicator by an integrable function preserves integrability. -/
@[fun_prop]
lemma POVar.integrable_indicator_mul_of_singleton
    {α : Type*} [MeasurableSpace α] [MeasurableSingletonClass α]
    (a : POVar P α) (x : α) {f : P.Ω → ℝ} {μ : Measure P.Ω}
    (hf : Integrable f μ) :
    Integrable (fun ω => a.indicator x ω * f ω) μ :=
  a.integrable_indicator_mul x (MeasurableSet.singleton x) hf

/-! ### Basic algebra wrappers -/

/-- Linearity of `condExpGiven`: additivity. -/
lemma POVar.condExpGiven_add (c : POVar P γ) {f g : P.Ω → ℝ} {μ : Measure P.Ω}
    (hf : Integrable f μ) (hg : Integrable g μ) :
    c.condExpGiven (f + g) μ =ᵐ[μ] c.condExpGiven f μ + c.condExpGiven g μ := by
  simpa [condexp_simps] using
    MeasureTheory.condExp_add (μ := μ) hf hg (MeasurableSpace.comap c.factual inferInstance)

/-- Linearity of `condExpGiven`: subtraction. -/
lemma POVar.condExpGiven_sub (c : POVar P γ) {f g : P.Ω → ℝ} {μ : Measure P.Ω}
    (hf : Integrable f μ) (hg : Integrable g μ) :
    c.condExpGiven (f - g) μ =ᵐ[μ] c.condExpGiven f μ - c.condExpGiven g μ := by
  simpa [condexp_simps] using
    MeasureTheory.condExp_sub (μ := μ) hf hg (MeasurableSpace.comap c.factual inferInstance)

/-- Scalar homogeneity of `condExpGiven`. -/
lemma POVar.condExpGiven_smul (c : POVar P γ) (k : ℝ) (g : P.Ω → ℝ)
    {μ : Measure P.Ω} :
    c.condExpGiven (k • g) μ =ᵐ[μ] k • c.condExpGiven g μ := by
  simpa [condexp_simps] using
    MeasureTheory.condExp_smul (μ := μ) k g (MeasurableSpace.comap c.factual inferInstance)

/-- Additivity of `condExpGiven` with the integrability side conditions discharged
automatically.

Same statement as `POVar.condExpGiven_add`, but the two integrability hypotheses are
`autoParam`s proved by `fun_prop`: a call site holding the witnesses in context supplies
nothing, and one whose integrands are built from `fun_prop`-tagged constructions needs no
witnesses at all. Passing them explicitly still works. -/
lemma POVar.condExpGiven_add' (c : POVar P γ) {f g : P.Ω → ℝ} {μ : Measure P.Ω}
    (hf : Integrable f μ := by fun_prop) (hg : Integrable g μ := by fun_prop) :
    c.condExpGiven (f + g) μ =ᵐ[μ] c.condExpGiven f μ + c.condExpGiven g μ :=
  c.condExpGiven_add hf hg

/-- Subtractivity of `condExpGiven` with the integrability side conditions discharged
automatically; see `POVar.condExpGiven_add'`. -/
lemma POVar.condExpGiven_sub' (c : POVar P γ) {f g : P.Ω → ℝ} {μ : Measure P.Ω}
    (hf : Integrable f μ := by fun_prop) (hg : Integrable g μ := by fun_prop) :
    c.condExpGiven (f - g) μ =ᵐ[μ] c.condExpGiven f μ - c.condExpGiven g μ :=
  c.condExpGiven_sub hf hg

/-- Negation passes through `condExpGiven`: averaging the negation of a quantity given a
variable is the negation of averaging it. No integrability is required. -/
lemma POVar.condExpGiven_neg (c : POVar P γ) (g : P.Ω → ℝ) {μ : Measure P.Ω} :
    c.condExpGiven (-g) μ =ᵐ[μ] -c.condExpGiven g μ := by
  simpa [condexp_simps] using
    MeasureTheory.condExp_neg (μ := μ) g (MeasurableSpace.comap c.factual inferInstance)

/-- A constant is its own conditional expectation: on a finite measure, averaging a
constant given a potential-outcome variable returns that constant, everywhere (not merely
almost everywhere). -/
lemma POVar.condExpGiven_const (c : POVar P γ) (k : ℝ) {μ : Measure P.Ω}
    [IsFiniteMeasure μ] :
    c.condExpGiven (fun _ => k) μ = fun _ => k :=
  MeasureTheory.condExp_const (μ := μ) c.comap_factual_le k

/-- `condExpGiven` commutes with a finite sum, with the family-wide integrability side
condition discharged automatically by `fun_prop`. -/
lemma POVar.condExpGiven_finsetSum' {ι : Type*} {s : Finset ι} (c : POVar P γ)
    {F : ι → P.Ω → ℝ} {μ : Measure P.Ω}
    (hF : ∀ i ∈ s, Integrable (F i) μ := by intro i _; fun_prop) :
    c.condExpGiven (∑ i ∈ s, F i) μ =ᵐ[μ] ∑ i ∈ s, c.condExpGiven (F i) μ := by
  simpa [condexp_simps] using
    MeasureTheory.condExp_finsetSum (μ := μ) hF
      (MeasurableSpace.comap c.factual inferInstance)

/-- `condExpGiven` yields a function strongly measurable w.r.t. `σ(c.factual)`. -/
@[fun_prop]
lemma POVar.stronglyMeasurable_condExpGiven_comap (c : POVar P γ) (g : P.Ω → ℝ)
    {μ : Measure P.Ω} :
    StronglyMeasurable[MeasurableSpace.comap c.factual inferInstance] (c.condExpGiven g μ) :=
  MeasureTheory.stronglyMeasurable_condExp
    (μ := μ) (m := MeasurableSpace.comap c.factual inferInstance) (f := g)

/-- `condExpGiven` yields a strongly measurable function w.r.t. the ambient σ-algebra. -/
@[fun_prop]
lemma POVar.stronglyMeasurable_condExpGiven (c : POVar P γ) (g : P.Ω → ℝ)
    {μ : Measure P.Ω} : StronglyMeasurable (c.condExpGiven g μ) :=
  (c.stronglyMeasurable_condExpGiven_comap g).mono c.comap_factual_le

/-- Mathlib's totalized conditional expectation given the variable's σ-algebra
is integrable, even when the original sample-space function is not assumed
integrable. -/
@[fun_prop]
lemma POVar.integrable_condExpGiven (c : POVar P γ) (g : P.Ω → ℝ)
    {μ : Measure P.Ω} : Integrable (c.condExpGiven g μ) μ := by
  simpa [condexp_simps] using
    (MeasureTheory.integrable_condExp
      (μ := μ) (m := MeasurableSpace.comap c.factual inferInstance) (f := g))

/-! ### Pull-out-left (product with a `σ(c.factual)`-measurable factor) -/

/-- Pull-out-left for `condExpGiven`: if `f` is strongly measurable w.r.t.
`σ(c.factual)`, then `μ[f·g | σ(c.factual)] =ᵐ f · μ[g | σ(c.factual)]`. -/
lemma POVar.condExpGiven_mul_of_stronglyMeasurable_left
    (c : POVar P γ) {f g : P.Ω → ℝ} {μ : Measure P.Ω}
    (hf : StronglyMeasurable[MeasurableSpace.comap c.factual inferInstance] f)
    (hfg : Integrable (f * g) μ) (hg : Integrable g μ) :
    c.condExpGiven (f * g) μ =ᵐ[μ] f * c.condExpGiven g μ := by
  simpa [condexp_simps] using
    MeasureTheory.condExp_mul_of_stronglyMeasurable_left
      (μ := μ) (m := MeasurableSpace.comap c.factual inferInstance) hf hfg hg

/-- Pull-out-right for `condExpGiven`. -/
lemma POVar.condExpGiven_mul_of_stronglyMeasurable_right
    (c : POVar P γ) {f g : P.Ω → ℝ} {μ : Measure P.Ω}
    (hg : StronglyMeasurable[MeasurableSpace.comap c.factual inferInstance] g)
    (hfg : Integrable (f * g) μ) (hf : Integrable f μ) :
    c.condExpGiven (f * g) μ =ᵐ[μ] c.condExpGiven f μ * g := by
  simpa [condexp_simps] using
    MeasureTheory.condExp_mul_of_stronglyMeasurable_right
      (μ := μ) (m := MeasurableSpace.comap c.factual inferInstance) hg hfg hf

/-- Pull-out version specialised to indicator functions of sets measurable
w.r.t. `σ(c.factual)`.  If the event is measurable with respect to the
conditioning variable's factual σ-algebra, its indicator factors out of the
conditional expectation just like any other strongly measurable multiplier. -/
lemma POVar.condExpGiven_indicator_mul
    (c : POVar P γ) {s : Set P.Ω} {g : P.Ω → ℝ} {μ : Measure P.Ω}
    (hs : MeasurableSet[MeasurableSpace.comap c.factual inferInstance] s)
    (hg : Integrable g μ) :
    c.condExpGiven (s.indicator (fun _ => (1 : ℝ)) * g) μ
      =ᵐ[μ] s.indicator (fun _ => (1 : ℝ)) * c.condExpGiven g μ := by
  have hsg : Integrable (s.indicator (fun _ => (1 : ℝ)) * g) μ := by
    have hs_meas : AEStronglyMeasurable (s.indicator (fun _ => (1 : ℝ))) μ :=
      StronglyMeasurable.aestronglyMeasurable
        (((stronglyMeasurable_const (b := (1 : ℝ))).indicator hs).mono c.comap_factual_le)
    refine hg.mono
      (hs_meas.mul hg.aestronglyMeasurable) ?_
    refine Filter.Eventually.of_forall (fun ω => ?_)
    by_cases hω : ω ∈ s <;> simp [Set.indicator, hω]
  exact c.condExpGiven_mul_of_stronglyMeasurable_left
    ((stronglyMeasurable_const (b := (1 : ℝ))).indicator hs) hsg hg

/-! ### Tower property -/

/-- Tower property over an arbitrary smaller sub-σ-algebra `m ≤ σ(c.factual)`.
Requires the usual `SigmaFinite` hypothesis on the trim of `μ` to
`σ(c.factual)`. -/
lemma POVar.condExpGiven_tower_of_le (c : POVar P γ) {g : P.Ω → ℝ} {μ : Measure P.Ω}
    {m : MeasurableSpace P.Ω} (hm : m ≤ MeasurableSpace.comap c.factual inferInstance)
    [SigmaFinite (μ.trim c.comap_factual_le)] :
    μ[c.condExpGiven g μ | m] =ᵐ[μ] μ[g | m] := by
  simpa [condexp_simps] using
    MeasureTheory.condExp_condExp_of_le (μ := μ) (f := g) hm c.comap_factual_le

/-- Tower property between two POVars: if `σ(c₁.factual) ≤ σ(c₂.factual)`, then
`μ[μ[g|σ(c₂)] | σ(c₁)] =ᵐ μ[g|σ(c₁)]`. -/
lemma POVar.condExpGiven_tower {δ : Type*} [MeasurableSpace δ]
    (c₁ : POVar P γ) (c₂ : POVar P δ) {g : P.Ω → ℝ} {μ : Measure P.Ω}
    (h : MeasurableSpace.comap c₁.factual inferInstance
          ≤ MeasurableSpace.comap c₂.factual inferInstance)
    [SigmaFinite (μ.trim c₂.comap_factual_le)] :
    c₁.condExpGiven (c₂.condExpGiven g μ) μ =ᵐ[μ] c₁.condExpGiven g μ := by
  simpa [condexp_simps] using
    MeasureTheory.condExp_condExp_of_le (μ := μ) (f := g) h c₂.comap_factual_le

/-! ### Conditional ratios -/

/-- For [a potential-outcome system](hyp:P), [a conditioning variable on a measurable scale](hyp:c,γ), [two real-valued sample-space functions](hyp:g,h), and [a measure on the sample space](hyp:μ), [the conditional-expectation ratio](goal) maps each unit to the conditional expectation of the first function divided by that of the second, with both conditional on the σ-algebra generated by the variable's factual value.

Pointwise ratio of two conditional expectations given `σ(c.factual)`.
Used as the adjusted regression in the backdoor ATE proof:
`condExpRatio c (Y·1_{D=d}) (1_{D=d}) = E[Y|D=d,X]` under overlap. -/
def POVar.condExpRatio (c : POVar P γ) (g h : P.Ω → ℝ)
    (μ : Measure P.Ω := P.μ) : P.Ω → ℝ :=
  fun ω => (c.condExpGiven g μ ω) / (c.condExpGiven h μ ω)

/-- The variable conditional-expectation ratio is, pointwise, the quotient of
the two conditional expectations given that variable.

This is the simp-shaped form of the definition of the conditional ratio. It is
stated in unapplied form so that it also fires on side conditions about the
ratio *as a function* (measurability, a.e. equalities); applying it to a sample
point recovers the pointwise quotient. -/
@[condexp_simps]
lemma POVar.condExpRatio_def (c : POVar P γ) (g h : P.Ω → ℝ) (μ : Measure P.Ω) :
    c.condExpRatio g h μ = fun ω => c.condExpGiven g μ ω / c.condExpGiven h μ ω :=
  rfl

/-- `condExpRatio` is measurable (pointwise division of two
strongly measurable functions is measurable). -/
@[fun_prop]
lemma POVar.measurable_condExpRatio (c : POVar P γ) (g h : P.Ω → ℝ)
    {μ : Measure P.Ω} : Measurable (c.condExpRatio g h μ) := by
  simp only [condexp_simps]
  exact (c.stronglyMeasurable_condExpGiven g).measurable.div
    (c.stronglyMeasurable_condExpGiven h).measurable

/-- `condExpRatio` is strongly measurable. -/
@[fun_prop]
lemma POVar.stronglyMeasurable_condExpRatio (c : POVar P γ) (g h : P.Ω → ℝ)
    {μ : Measure P.Ω} : StronglyMeasurable (c.condExpRatio g h μ) :=
  (c.measurable_condExpRatio g h).stronglyMeasurable

/-- **Characterisation of `condExpRatio` via a product identity.**
If `μ[g|σ(c)] = μ[h|σ(c)] · target` a.s. and `μ[h|σ(c)] ≠ 0` a.s., then
`condExpRatio c g h =ᵐ target`.  This is the reusable algebraic step for
turning a conditional-expectation product identity into a ratio identity. -/
lemma POVar.condExpRatio_eq_of_mul (c : POVar P γ) {g h target : P.Ω → ℝ}
    {μ : Measure P.Ω}
    (hprod : c.condExpGiven g μ =ᵐ[μ] c.condExpGiven h μ * target)
    (hne : ∀ᵐ ω ∂μ, c.condExpGiven h μ ω ≠ 0) :
    c.condExpRatio g h μ =ᵐ[μ] target := by
  simp only [condexp_simps]
  filter_upwards [hprod, hne] with ω hω hne
  simp only [Pi.mul_apply, condexp_simps] at hω hne
  rw [hω]
  field_simp

/-- **CATE-to-ATE integrator.** Fix a conditioning variable `c` and
[integrable functions `f` and `g`](hyp:hf,hg) on the same probability space.
If [`f'` is an almost-everywhere representative of the conditional expectation
of `f` given `c`](hyp:hf') and [`g'` is an almost-everywhere representative of
the conditional expectation of `g` given `c`](hyp:hg'), then [the integral of
`f - g` equals the integral of `f' - g'`](goal).

This is the last step of any outcome-regression identification: turn a
CATE-level identity (`μ[Y(1)|σX] =ᵐ adjusted₁`, `μ[Y(0)|σX] =ᵐ adjusted₀`)
into an ATE-level identity (`∫ (Y(1) − Y(0)) dμ = ∫ (adjusted₁ − adjusted₀) dμ`). -/
theorem POVar.integral_sub_eq_integral_sub_of_condExpGiven_ae_eq
    (c : POVar P γ) {f g f' g' : P.Ω → ℝ} {μ : Measure P.Ω}
    [SigmaFinite (μ.trim c.comap_factual_le)]
    (hf : Integrable f μ) (hg : Integrable g μ)
    (hf' : c.condExpGiven f μ =ᵐ[μ] f')
    (hg' : c.condExpGiven g μ =ᵐ[μ] g') :
    ∫ ω, f ω - g ω ∂μ = ∫ ω, f' ω - g' ω ∂μ := by
  have hIf : ∫ ω, f ω ∂μ = ∫ ω, c.condExpGiven f μ ω ∂μ := by
    simp only [condexp_simps]
    exact (MeasureTheory.integral_condExp c.comap_factual_le).symm
  have hIg : ∫ ω, g ω ∂μ = ∫ ω, c.condExpGiven g μ ω ∂μ := by
    simp only [condexp_simps]
    exact (MeasureTheory.integral_condExp c.comap_factual_le).symm
  rw [MeasureTheory.integral_sub hf hg, hIf, hIg,
    ← MeasureTheory.integral_sub (c.integrable_condExpGiven f)
      (c.integrable_condExpGiven g)]
  exact MeasureTheory.integral_congr_ae (hf'.sub hg')

end

/-! ## Conditional independence from finite fibers -/

/-- The normalized real mass of an event inside one fiber of a finite-valued map. -/
private noncomputable def finiteCondProb
    {Ω T : Type*} [MeasurableSpace Ω] [MeasurableSpace T]
    (μ : Measure Ω) (X : Ω → T) (A : Set Ω) (x : T) : ℝ :=
  (μ.real (X ⁻¹' {x}))⁻¹ * μ.real ((X ⁻¹' {x}) ∩ A)

/-- A finite-fiber conditional probability is nonnegative. -/
private lemma finiteCondProb_nonneg
    {Ω T : Type*} [MeasurableSpace Ω] [MeasurableSpace T]
    (μ : Measure Ω) (X : Ω → T) (A : Set Ω) (x : T) :
    0 ≤ finiteCondProb μ X A x :=
  mul_nonneg (inv_nonneg.mpr measureReal_nonneg) measureReal_nonneg

/-- Under a finite measure, a finite-fiber conditional probability is at most one. -/
private lemma finiteCondProb_le_one
    {Ω T : Type*} [MeasurableSpace Ω] [MeasurableSpace T]
    (μ : Measure Ω) [IsFiniteMeasure μ] (X : Ω → T) (A : Set Ω) (x : T) :
    finiteCondProb μ X A x ≤ 1 := by
  unfold finiteCondProb
  by_cases hzero : μ.real (X ⁻¹' {x}) = 0
  · simp [hzero]
  · rw [inv_mul_le_one₀ (lt_of_le_of_ne measureReal_nonneg (Ne.symm hzero))]
    exact measureReal_mono Set.inter_subset_left

/-- The conditional expectation of an event indicator given a finite-valued map equals the
elementary conditional-probability ratio on each fiber. -/
private lemma condExp_indicator_finite_comap
    {Ω T : Type*} [Finite T] [MeasurableSpace T]
    [MeasurableSingletonClass T] [MeasurableSpace Ω]
    (μ : Measure Ω) [IsFiniteMeasure μ]
    (X : Ω → T) (hX : Measurable X) (A : Set Ω) (hA : MeasurableSet A) :
    μ[A.indicator (fun _ => (1 : ℝ)) | MeasurableSpace.comap X inferInstance] =ᵐ[μ]
      fun ω => finiteCondProb μ X A (X ω) := by
  letI := Fintype.ofFinite T
  let q : T → ℝ := finiteCondProb μ X A
  have hq : Measurable q := measurable_of_finite q
  have hqm : StronglyMeasurable[MeasurableSpace.comap X
      (inferInstance : MeasurableSpace T)] (q ∘ X) :=
    (hq.comp (comap_measurable X)).stronglyMeasurable
  have hqΩ : StronglyMeasurable (q ∘ X) := (hq.comp hX).stronglyMeasurable
  have hq_int : Integrable (q ∘ X) μ := by
    apply Integrable.of_bound hqΩ.aestronglyMeasurable 1
    filter_upwards [] with ω
    rw [Real.norm_eq_abs, abs_le]
    constructor
    · exact (by norm_num : (-1 : ℝ) ≤ 0).trans
        (finiteCondProb_nonneg μ X A (X ω))
    · exact finiteCondProb_le_one μ X A (X ω)
  have hind : Integrable (A.indicator fun _ => (1 : ℝ)) μ :=
    (integrable_const 1).indicator hA
  have hversion :
      (q ∘ X) =ᵐ[μ]
        μ[A.indicator (fun _ => (1 : ℝ)) |
          MeasurableSpace.comap X (inferInstance : MeasurableSpace T)] := by
    apply ae_eq_condExp_of_forall_setIntegral_eq hX.comap_le hind
    · intro x _ _
      exact hq_int.integrableOn
    · intro x hx _
      rcases hx with ⟨u, hu, rfl⟩
      classical
      let U : Finset T := Finset.univ.filter (· ∈ u)
      rw [show X ⁻¹' u = ⋃ x ∈ U, X ⁻¹' {x} by
        ext ω
        simp [U]]
      rw [integral_biUnion_finset, integral_biUnion_finset]
      · apply Finset.sum_congr rfl
        intro x hx
        have heq : (q ∘ X) =ᵐ[μ.restrict (X ⁻¹' {x})] fun _ => q x := by
          filter_upwards [ae_restrict_mem
            (hX (measurableSet_singleton x))] with ω hω
          simp only [Set.mem_preimage, Set.mem_singleton_iff] at hω
          exact congrArg q hω
        rw [integral_congr_ae heq, integral_const]
        change ((μ.restrict (X ⁻¹' {x})) Set.univ).toReal * q x =
          ∫ y in X ⁻¹' {x}, A.indicator (fun _ => (1 : ℝ)) y ∂μ
        rw [Measure.restrict_apply_univ]
        rw [integral_indicator hA, setIntegral_const, smul_eq_mul, mul_one]
        unfold q finiteCondProb
        change μ.real (X ⁻¹' {x}) *
            ((μ.real (X ⁻¹' {x}))⁻¹ * μ.real ((X ⁻¹' {x}) ∩ A)) =
          ((μ.restrict (X ⁻¹' {x})) A).toReal
        rw [Measure.restrict_apply hA, Set.inter_comm A]
        change μ.real (X ⁻¹' {x}) *
            ((μ.real (X ⁻¹' {x}))⁻¹ * μ.real ((X ⁻¹' {x}) ∩ A)) =
          μ.real ((X ⁻¹' {x}) ∩ A)
        by_cases hzero : μ.real (X ⁻¹' {x}) = 0
        · have hsub : μ.real ((X ⁻¹' {x}) ∩ A) = 0 :=
            le_antisymm (hzero ▸ measureReal_mono Set.inter_subset_left)
              measureReal_nonneg
          simp [hzero, hsub]
        · field_simp
      · intro x _
        exact hX (measurableSet_singleton x)
      · exact Set.pairwiseDisjoint_fiber X U
      · intro x _
        exact hind.integrableOn
      · intro x _
        exact hX (measurableSet_singleton x)
      · exact Set.pairwiseDisjoint_fiber X U
      · intro x _
        exact hq_int.integrableOn
    · exact hqm.aestronglyMeasurable
  exact hversion.symm

/-- For a finite-valued conditioning map, if [the conditioning map and the two conditioned
maps are measurable](hyp:hX,hf,hg) and [their ordinary real masses factor on every measurable
pair of events inside every conditioning fiber](hyp:hfactor), then [the two maps are
conditionally independent given the σ-algebra generated by the conditioning map](goal). -/
theorem condIndepFun_finite_of_measureReal_fibers
    {Ω T A B : Type*} [MeasurableSpace Ω] [StandardBorelSpace Ω]
    [Finite T] [MeasurableSpace T] [MeasurableSingletonClass T]
    [MeasurableSpace A] [MeasurableSpace B]
    (μ : Measure Ω) [IsFiniteMeasure μ]
    (X : Ω → T) (hX : Measurable X) (f : Ω → A) (hf : Measurable f)
    (g : Ω → B) (hg : Measurable g)
    (hfactor : ∀ (x : T) (s : Set A) (t : Set B), MeasurableSet s → MeasurableSet t →
      μ.real (((f ⁻¹' s) ∩ (g ⁻¹' t)) ∩ X ⁻¹' {x}) * μ.real (X ⁻¹' {x}) =
        μ.real ((f ⁻¹' s) ∩ X ⁻¹' {x}) * μ.real ((g ⁻¹' t) ∩ X ⁻¹' {x})) :
    CondIndepFun (MeasurableSpace.comap X inferInstance) hX.comap_le f g μ := by
  rw [condIndepFun_iff_condExp_inter_preimage_eq_mul hf hg]
  intro s t hs ht
  have hfg : MeasurableSet (f ⁻¹' s ∩ g ⁻¹' t) := (hf hs).inter (hg ht)
  have hleft := condExp_indicator_finite_comap μ X hX _ hfg
  have hfiber := condExp_indicator_finite_comap μ X hX _ (hf hs)
  have hgiber := condExp_indicator_finite_comap μ X hX _ (hg ht)
  filter_upwards [hleft, hfiber, hgiber] with ω hleftω hfω hgω
  rw [hleftω, hfω, hgω]
  unfold finiteCondProb
  let m := μ.real (X ⁻¹' {X ω})
  by_cases hm : m = 0
  · simp only [m] at hm
    simp [hm]
  · have hfac := hfactor (X ω) s t hs ht
    simp only [Set.inter_assoc] at hfac
    change m⁻¹ * μ.real (X ⁻¹' {X ω} ∩ (f ⁻¹' s ∩ g ⁻¹' t)) =
      (m⁻¹ * μ.real (X ⁻¹' {X ω} ∩ f ⁻¹' s)) *
        (m⁻¹ * μ.real (X ⁻¹' {X ω} ∩ g ⁻¹' t))
    have hfac' :
        μ.real (X ⁻¹' {X ω} ∩ (f ⁻¹' s ∩ g ⁻¹' t)) * m =
          μ.real (X ⁻¹' {X ω} ∩ f ⁻¹' s) *
            μ.real (X ⁻¹' {X ω} ∩ g ⁻¹' t) := by
      simpa [m, Set.inter_comm, Set.inter_left_comm, Set.inter_assoc] using hfac
    field_simp
    simpa [mul_comm] using hfac'

end Causalean.PO
