import CausalSmith.ExactID.EID_CrlCoverratioMmdGenericity_Research.Helpers.Decoder
import CausalSmith.ExactID.EID_CrlCoverratioMmdGenericity_Research.Helpers.Inference
import Mathlib.Analysis.Calculus.ContDiff.Defs
import Mathlib.Analysis.SpecialFunctions.Pow.Real
import Mathlib.LinearAlgebra.Determinant

/-!
# Bounded Hölder subclass and first-stage contract

This file records the determinate bounded statistical regime and its uniform
first-stage ratio event. The unresolved generated-rank estimator remains a
descriptive payload rather than a fabricated construction.
-/

open MeasureTheory Set Filter
open scoped BigOperators ENNReal Topology

noncomputable section

namespace CausalSmith.ExactID.EID_CrlCoverratioMmdGenericity

/-- Parameters of the bounded generated-rank regime. -/
structure BoundedRegime {n : ℕ} {G : Causalean.DAG (Fin n)} {θ : Mechanism n G}
    (W : ObservedWorld G θ) where
  order : Fin n → ℕ
  sampleSizeSequence : ℕ → Fin (n + 1) → ℕ -- @realizes \(N_e\)(sample-size sequence)
  ratioRate : ℕ → ℝ -- @realizes \(b_N\)(uniform first-stage C1 rate)
  ratioRate_pos : ∀ N, 0 < ratioRate N -- @realizes \(b_N\)(positive sequence)
  ratioRate_zero : Tendsto ratioRate atTop (𝓝 0) -- @realizes \(b_N\)(converges to zero)
  failureRate : ℕ → ℝ -- @realizes \(\eta_N\)(first-stage failure sequence)
  failureRate_pos : ∀ N, 0 < failureRate N -- @realizes \(\eta_N\)(positive sequence)
  failureRate_zero : Tendsto failureRate atTop (𝓝 0) -- @realizes \(\eta_N\)(converges to zero)
  bandwidth : ℕ → ℝ -- @realizes \(h_N\)(second-stage bandwidth)
  bandwidth_pos : ∀ N, 0 < bandwidth N -- @realizes \(h_N\)(positive sequence)
  bandwidth_zero : Tendsto bandwidth atTop (𝓝 0) -- @realizes \(h_N\)(converges to zero)

/-- An observed world generated by the latent mechanism through a shared `C²` diffeomorphism
and one relabeled perfect intervention per latent node. -/
abbrev ModelGeneratedObservedWorld {n : ℕ} (G : Causalean.DAG (Fin n))
    (θ : Mechanism n G) :=
  {W : ObservedWorld G θ //
    SharedDiffeomorphicMixing G θ W ∧ OnePerfectInterventionPerNode G θ W}

/-- A bounded regime whose predecessor sets use exactly the ordering selected by the
law-only population decoder. -/
abbrev DecoderSelectedBoundedRegime {n : ℕ} {G : Causalean.DAG (Fin n)}
    {θ : Mechanism n G} (W : ModelGeneratedObservedWorld G θ) :=
  {R : BoundedRegime W.1 //
    R.order = selectedTopologicalOrder (observedProbabilityLawFamily W.1.law)}

-- @env: S6
variable {n : ℕ} {G : Causalean.DAG (Fin n)} {s : SignVector n}
  {θ : Mechanism n G} {W : ObservedWorld G θ} (R : BoundedRegime W)

/-- Conditioning-coordinate domain induced by the log-ratios on `K`. -/
def conditioningDomain (K : Set (LatentState n)) (i : Fin n) :
    Set ((j : {j // j ∈ predecessorSet R.order i}) → ℝ) :=
  familyProjection (logRatio G W) (predecessorSet R.order i) '' K
  -- @realizes \(\mathcal Z_i(K)\)(image of K under L_Bi)

/-- Maximum conditioning dimension of the selected ordering. -/
def maximumConditioningDimension : ℕ :=
  Finset.univ.sup (fun i : Fin n => (predecessorSet R.order i).card)
  -- @realizes \(d_\star\)(maximum cardinality of B_i)

/-- Minimum environment sample size at global index `N`. -/
def regimeMinimumSampleSize (N : ℕ) : ℕ :=
  Finset.univ.inf' ⟨0, Finset.mem_univ 0⟩ (R.sampleSizeSequence N)
  -- @realizes \(\underline N\)(minimum of N_e across environments)

/-- Hölder-ball predicate of real order `β`: every derivative through `⌊β⌋` is bounded by
`M`, and the top derivative has the corresponding fractional Hölder modulus. -/
def HolderOrderBound {E F : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [NormedAddCommGroup F] [NormedSpace ℝ F]
    (β M : ℝ) (f : E → F) (K : Set E) : Prop :=
  let k := ⌊β⌋₊
  ContDiffOn ℝ k f K ∧
  (∀ m : ℕ, m ≤ k → ∀ x ∈ K, ‖iteratedFDerivWithin ℝ m f K x‖ ≤ M) ∧
  ∀ x ∈ K, ∀ y ∈ K,
    ‖iteratedFDerivWithin ℝ k f K x - iteratedFDerivWithin ℝ k f K y‖ ≤
      M * ‖x - y‖ ^ (β - k)

-- @node: ass:bounded-holder-radius
/-- All observational mechanisms, intervention densities, and unmixed log ratios lie in the
common Hölder ball of order `β` and radius `M`. -/
def BoundedHolderRadius (_R : BoundedRegime W) (β M : ℝ) : Prop :=
  2 < β ∧ -- @realizes \(\beta\)(range (2,infinity))
  1 < M ∧ -- @realizes M(range (1,infinity))
  (∀ i, HolderOrderBound β M (θ.p i) (latentCube n)) ∧
  (∀ i, HolderOrderBound β M (θ.q i) (Set.Icc (0 : ℝ) 1)) ∧
  (∀ i, HolderOrderBound β M
    (fun v => logRatio G W i (W.mix v)) (latentCube n))

-- @node: ass:density-lower-envelope
/-- Every observational and intervention density is uniformly bounded below by `c`. -/
def DensityLowerEnvelope (_R : BoundedRegime W) (c : ℝ) : Prop :=
  c ∈ Set.Ioo (0 : ℝ) 1 ∧ -- @realizes c(range (0,1))
  (∀ i v, v ∈ latentCube n → c ≤ θ.p i v) ∧
  (∀ i z, z ∈ Set.Icc (0 : ℝ) 1 → c ≤ θ.q i z)

-- @node: ass:own-derivative-margin
/-- Every signed own-coordinate observed log-ratio derivative is at least `c`. -/
def OwnDerivativeMargin (_R : BoundedRegime W) (c : ℝ) : Prop :=
  ∀ i v, v ∈ latentCube n →
    c ≤ s.value i *
      derivWithin (fun z => logRatio G W i (W.mix (Function.update v i z)))
        (Set.Icc (0 : ℝ) 1) (v i)

-- @node: ass:common-interior-domain
/-- The latent preimage of `K` is at least `ρ` from the boundary of the latent cube. -/
def CommonInteriorDomain (_R : BoundedRegime W) (K : Set (LatentState n)) (ρ : ℝ) : Prop :=
  ρ ∈ Set.Ioo (0 : ℝ) (1 / 2) ∧ -- @realizes \(\rho\)(range (0,1/2))
  IsCompact K ∧ -- @realizes \(K\)(compactness)
  K ⊆ interior (observedSupport G W) ∧ -- @realizes \(K\)(common interior domain)
  ∀ v ∈ W.unmix '' K,
    ρ ≤ Metric.infDist v (frontier (latentCube n))

/-- The Jacobian determinant of a Euclidean self-map relative to its stated domain. -/
def jacobianDeterminantWithin (f : LatentState n → LatentState n)
    (S : Set (LatentState n)) (x : LatentState n) : ℝ :=
  LinearMap.det (fderivWithin ℝ f S x).toLinearMap

-- @node: ass:bounded-shared-mixing-geometry
/-- The shared map, inverse map, and both Jacobian determinants obey the uniform `C²` envelope. -/
def BoundedSharedMixingGeometry (_R : BoundedRegime W) (M : ℝ) : Prop :=
  ContDiffOn ℝ 2 W.mix (latentCube n) ∧
  ContDiffOn ℝ 2 W.unmix (observedSupport G W) ∧
  (∀ v ∈ latentCube n,
    ‖W.mix v‖ ≤ M ∧ ‖fderivWithin ℝ W.mix (latentCube n) v‖ ≤ M ∧
      ‖iteratedFDerivWithin ℝ 2 W.mix (latentCube n) v‖ ≤ M ∧
      |jacobianDeterminantWithin W.mix (latentCube n) v| ≤ M) ∧
  (∀ x ∈ observedSupport G W,
    ‖W.unmix x‖ ≤ M ∧ ‖fderivWithin ℝ W.unmix (observedSupport G W) x‖ ≤ M ∧
      ‖iteratedFDerivWithin ℝ 2 W.unmix (observedSupport G W) x‖ ≤ M ∧
      |jacobianDeterminantWithin W.unmix (observedSupport G W) x| ≤ M)

-- @node: ass:observed-log-ratio-regularity
/-- Every observed log ratio has uniformly bounded value and first two derivatives on `K`. -/
def ObservedLogRatioRegularity
    (_R : BoundedRegime W) (K : Set (LatentState n)) (M : ℝ) : Prop :=
  (∀ i, ContDiffOn ℝ 2 (logRatio G W i) K) ∧
  ∀ i x, x ∈ K →
      |logRatio G W i x| ≤ M ∧
      ‖fderivWithin ℝ (logRatio G W i) K x‖ ≤ M ∧
      ‖iteratedFDerivWithin ℝ 2 (logRatio G W i) K x‖ ≤ M

-- @node: ass:conditional-design-envelope
/-- For each environment, some density version of the law of its conditioning coordinates obeys
the empty-predecessor convention and lies between `c` and `M` on its induced domain. -/
def ConditionalDesignEnvelope
    (R : BoundedRegime W) (c M : ℝ) (K : Set (LatentState n)) : Prop :=
  ∀ i, ∃ hmeas : AEMeasurable
      (familyProjection (logRatio G W) (predecessorSet R.order i)) (W.law i.succ),
    ∃ g : (((j : {j // j ∈ predecessorSet R.order i}) → ℝ) → ℝ),
      (predecessorSet R.order i = ∅ → g = fun _ => 1) ∧
        -- @realizes \(g_i\)(identically one when B_i is empty)
      Measure.map
          (hmeas.mk (familyProjection (logRatio G W) (predecessorSet R.order i)))
          (W.law i.succ) =
        volume.withDensity (fun z => ENNReal.ofReal (g z)) ∧
        -- @realizes \(g_i\)(law-derived density version of L_Bi(X) under P^i)
      ∀ z, z ∈ conditioningDomain R K i →
        c ≤ g z ∧ g z ≤ M
        -- @realizes \(g_i\)(range between c and M on Z_i(K))

-- @node: def:bounded-holder-subclass
/-- Membership evidence for the bounded Hölder subclass, indexed by a point of the full model
stratum. Its extension is `boundedSubclassSet`. -/
structure BoundedHolderSubclass
    (world : ∀ θs : StratumPoint G s, ModelGeneratedObservedWorld G θs.1)
    (regime : ∀ θs : StratumPoint G s, DecoderSelectedBoundedRegime (world θs))
    (β c M : ℝ) (K : Set (LatentState n)) (ρ : ℝ)
    (θs : StratumPoint G s) : Prop where
  holderRadius : BoundedHolderRadius (regime θs).1 β M
  densityLower : DensityLowerEnvelope (regime θs).1 c
  derivativeMargin : OwnDerivativeMargin (s := s) (regime θs).1 c
  interiorDomain : CommonInteriorDomain (regime θs).1 K ρ
  mixingGeometry : BoundedSharedMixingGeometry (regime θs).1 M
  ratioRegularity : ObservedLogRatioRegularity (regime θs).1 K M
  designEnvelope : ConditionalDesignEnvelope (regime θs).1 c M K

/-- The bounded Hölder subclass as a subset of the population stratum. -/
def boundedSubclassSet
    (world : ∀ θs : StratumPoint G s, ModelGeneratedObservedWorld G θs.1)
    (regime : ∀ θs : StratumPoint G s, DecoderSelectedBoundedRegime (world θs))
    (β c M : ℝ) (K : Set (LatentState n)) (ρ : ℝ) :
    Set (StratumPoint G s) :=
  {θs | BoundedHolderSubclass world regime β c M K ρ θs}
  -- @realizes \(\Theta^{\beta}_{G,s}(c,M,K,\rho)\)(seven-property bounded subset)

/-- The uniform `C¹` log-ratio error event, including `C¹` membership of the fitted and true
log-ratios rather than only pointwise derivative inequalities. -/
def uniformC1RatioEvent {Ω : Type*} [MeasurableSpace Ω]
    (S : SampleSplitWorld W Ω) (b : ℝ) : Set Ω :=
  {ω | ∀ i,
    ContDiffOn ℝ 1 (fun y => Real.log (S.ratioEstimate ω i y)) (observedSupport G W) ∧
    ContDiffOn ℝ 1 (logRatio G W i) (observedSupport G W) ∧
    ∀ x ∈ observedSupport G W,
      |Real.log (S.ratioEstimate ω i x) - logRatio G W i x| ≤ b ∧
      ‖fderivWithin ℝ (fun y => Real.log (S.ratioEstimate ω i y))
          (observedSupport G W) x -
        fderivWithin ℝ (logRatio G W i) (observedSupport G W) x‖ ≤ b}
  -- @realizes \(\mathcal E_N^{\infty}(b_N)\)(uniform C1 log-ratio event)

-- @node: def:first-stage-ratio-contract
/-- The common `N`-indexed first-stage contract over the bounded subclass. Each sampling world
uses the regime's environment sample-size sequence, and the event is explicitly measurable. -/
def firstStageRatioContract {Ω : Type*} [MeasurableSpace Ω]
    (world : ∀ θs : StratumPoint G s, ModelGeneratedObservedWorld G θs.1)
    (regime : ∀ θs : StratumPoint G s, DecoderSelectedBoundedRegime (world θs))
    (sampling : ∀ (θs : StratumPoint G s) (_N : ℕ),
      SampleSplitWorld (world θs).1 Ω)
    (sampleSizeSequence : ℕ → Fin (n + 1) → ℕ)
    (bN etaN : ℕ → ℝ)
    (β c M : ℝ) (K : Set (LatentState n)) (ρ : ℝ) : Prop :=
  (∀ N, 0 < bN N) ∧ Tendsto bN atTop (𝓝 0) ∧
  (∀ N, 0 < etaN N) ∧ Tendsto etaN atTop (𝓝 0) ∧
  ∀ N θs, θs ∈ boundedSubclassSet world regime β c M K ρ →
    (regime θs).1.sampleSizeSequence = sampleSizeSequence ∧
    (regime θs).1.ratioRate = bN ∧
    (regime θs).1.failureRate = etaN ∧
    IndependentEnvironmentSampling (sampling θs N) ∧
    (sampling θs N).sampleSize = sampleSizeSequence N ∧
    MeasurableSet (uniformC1RatioEvent (sampling θs N) (bN N)) ∧
    1 - etaN N ≤
      (sampling θs N).probability.real
        (uniformC1RatioEvent (sampling θs N) (bN N))

/-- The proposed uniform coordinate-rate expression. -/
def coordinateRate (N : ℕ) : ℝ :=
  R.bandwidth N ^ 2 +
    Real.sqrt (Real.log (regimeMinimumSampleSize R N) /
      ((regimeMinimumSampleSize R N : ℝ) *
        R.bandwidth N ^ maximumConditioningDimension R)) +
    R.ratioRate N / R.bandwidth N
  -- @realizes \(r_N\)(h_N^2 + sqrt(log Nbar/(Nbar h_N^dstar)) + b_N/h_N)

-- @node: def:generated-rank-handle
/-- @realizes \(\mathfrak H_{\mathrm{rank}}\)(open generated-rank proof-strategy handle)
@realizes \(\widehat U_i\)(open second-stage cross-fitted rank estimator) -/
def generatedRankHandle : _root_.String :=
  "Nonassertive generated-rank handle: adapt Xie's local-linear conditional-CDF estimator to \
  cross-fitted log-ratio responses and covariates; decompose the second stage into the oracle \
  conditional-CDF process, indicator boundary crossings from the generated threshold, and \
  local-design perturbations from generated conditioning arguments; then linearize that last \
  component using Mammen--Rothe--Schienle generated-covariate expansion. No second-stage weight \
  convention, bandwidth selector, influence representation, attainment claim, or sharpness claim \
  is supplied here."

end CausalSmith.ExactID.EID_CrlCoverratioMmdGenericity
