import CausalSmith.ExactID.EID_CrlCoverratioMmdGenericity_Research.Helpers.Kernel
import Causalean.Mathlib.Indep
import Mathlib.Analysis.InnerProductSpace.Basic

/-!
# Independent sample-splitting and the confidence graph

This file defines the multi-environment evaluation sample, arbitrary
training-fold ratio estimates, empirical MMDs, and the simultaneous threshold.
-/

open MeasureTheory ProbabilityTheory Set
open scoped BigOperators ENNReal

noncomputable section

namespace CausalSmith.ExactID.EID_CrlCoverratioMmdGenericity

/-- A sample-split experiment over a fixed observed environment family. -/
structure SampleSplitWorld {n : ℕ} {G : Causalean.DAG (Fin n)} {θ : Mechanism n G}
    (W : ObservedWorld G θ) (Ω : Type*) [MeasurableSpace Ω] where
  probability : Measure Ω
  sampleSize : Fin (n + 1) → ℕ -- @realizes \(N_e\)(environment sample sizes)
  evaluation : ∀ e, Fin (sampleSize e) → Ω → LatentState n
  trainingSize : Fin (n + 1) → ℕ
  training : ∀ e, Fin (trainingSize e) → Ω → LatentState n
  ratioFit : (∀ e, Fin (trainingSize e) → LatentState n) →
    Fin n → LatentState n → ℝ
    -- @realizes \(\widehat R_i\)(measurable function fitted from the full training fold)
  ratioFit_joint_measurable : ∀ i,
    Measurable (Function.uncurry (fun T x => ratioFit T i x))
    -- @realizes \(\widehat R_i\)(joint measurability in training data and evaluation point)
  ratioFit_measurable : ∀ T i, Measurable (ratioFit T i)
    -- @realizes \(\widehat R_i\)(measurable as a function of the observation)
  ratioFit_pos : ∀ T i x, 0 < ratioFit T i x
    -- @realizes \(\widehat R_i\)(strictly positive range)
  firstStageRadius : ℝ → ℝ -- @realizes \(a_N\)(radius indexed by first-stage failure level)
  firstStageRadius_nonneg : ∀ η, 0 ≤ firstStageRadius η
    -- @realizes \(a_N\)(nonnegative range)
  alpha : ℝ -- @realizes \(\alpha\)(familywise evaluation error level)
  alpha_mem : alpha ∈ Set.Ioo (0 : ℝ) 1 -- @realizes \(\alpha\)(range (0,1))
  eta : ℝ -- @realizes \(\eta\)(first-stage failure level)
  eta_mem : eta ∈ Set.Ioo (0 : ℝ) 1 -- @realizes \(\eta\)(range (0,1))

/-- The complete training fold, retained rather than compressed to an arbitrary summary. -/
def trainingFold {n : ℕ} {G : Causalean.DAG (Fin n)} {θ : Mechanism n G}
    {W : ObservedWorld G θ} {Ω : Type*} [MeasurableSpace Ω]
    (S : SampleSplitWorld W Ω) (ω : Ω) :
    ∀ e, Fin (S.trainingSize e) → LatentState n :=
  fun e r => S.training e r ω

-- @node: trainingSigma
/-- The σ-algebra generated by the complete training fold. -/
def trainingSigma {n : ℕ} {G : Causalean.DAG (Fin n)} {θ : Mechanism n G}
    {W : ObservedWorld G θ} {Ω : Type*} [MeasurableSpace Ω]
    (S : SampleSplitWorld W Ω) : MeasurableSpace Ω :=
  MeasurableSpace.comap (trainingFold S) inferInstance

/-- The fitted ratio, definitionally factored through the complete training fold. -/
def SampleSplitWorld.ratioEstimate {n : ℕ} {G : Causalean.DAG (Fin n)}
    {θ : Mechanism n G} {W : ObservedWorld G θ} {Ω : Type*} [MeasurableSpace Ω]
    (S : SampleSplitWorld W Ω) (ω : Ω) : Fin n → LatentState n → ℝ :=
  S.ratioFit (trainingFold S ω)

/-- The training-fold finite `L¹` ratio-error event used by the confidence theorem. -/
def firstStageL1Event {n : ℕ} {G : Causalean.DAG (Fin n)} {θ : Mechanism n G}
    {W : ObservedWorld G θ} {Ω : Type*} [MeasurableSpace Ω]
    (S : SampleSplitWorld W Ω) : Set Ω :=
  {ω | ∀ i : Fin n, ∀ e : Fin (n + 1),
    Integrable (fun x => |S.ratioEstimate ω i x - observedLawRatio W.law i x|) (W.law e) ∧
    ∫ x, |S.ratioEstimate ω i x - observedLawRatio W.law i x| ∂W.law e ≤
      S.firstStageRadius S.eta}

/-- All evaluation observations as a single dependent array. -/
def allEvaluationData {n : ℕ} {G : Causalean.DAG (Fin n)} {θ : Mechanism n G}
    {W : ObservedWorld G θ} {Ω : Type*} [MeasurableSpace Ω]
    (S : SampleSplitWorld W Ω) (ω : Ω) :
    ∀ e, Fin (S.sampleSize e) → LatentState n := fun e r => S.evaluation e r ω

-- @env: S5
variable {n : ℕ} {G : Causalean.DAG (Fin n)} {θ : Mechanism n G}
  {W : ObservedWorld G θ} {Ω : Type*} [MeasurableSpace Ω]
  (S : SampleSplitWorld W Ω)

-- @node: ass:independent-environment-sampling
/-- Evaluation observations are independent within each environment, have the stated environment
law, and the complete evaluation fold is independent of the training fold. -/
def IndependentEnvironmentSampling : Prop :=
  IsProbabilityMeasure S.probability ∧
  (∀ e, IsProbabilityMeasure (W.law e)) ∧
  (∀ e r, Measurable (S.training e r)) ∧
  (∀ e, ProbabilityTheory.iIndepFun (S.training e) S.probability) ∧
  (∀ e r, Measure.map (S.training e r) S.probability = W.law e) ∧
  (∀ e r, Measurable (S.evaluation e r)) ∧
  (∀ e, ProbabilityTheory.iIndepFun (S.evaluation e) S.probability) ∧
  (∀ e r, Measure.map (S.evaluation e r) S.probability = W.law e) ∧
  ProbabilityTheory.IndepFun (trainingFold S) (allEvaluationData S) S.probability ∧
  (∀ i x, @Measurable Ω ℝ (MeasurableSpace.comap (trainingFold S) inferInstance)
    inferInstance (fun ω => S.ratioEstimate ω i x)) ∧
  (∀ i, @Measurable (Ω × LatentState n) ℝ
    ((MeasurableSpace.comap (trainingFold S) inferInstance).prod inferInstance)
    inferInstance (fun p => S.ratioEstimate p.1 i p.2)) ∧
  @MeasurableSet Ω (MeasurableSpace.comap (trainingFold S) inferInstance)
    (firstStageL1Event S)

/-- The part of the sample-splitting assumptions needed to condition an evaluation-sample
concentration bound on the training fold. It deliberately omits the unused training-sample law and
i.i.d. clauses and the measurability of the separate first-stage event. -/
def ConditionalEvaluationSampling : Prop :=
  IsProbabilityMeasure S.probability ∧
  (∀ e, IsProbabilityMeasure (W.law e)) ∧
  Measurable (trainingFold S) ∧
  (∀ e r, Measurable (S.evaluation e r)) ∧
  (∀ e, ProbabilityTheory.iIndepFun (S.evaluation e) S.probability) ∧
  (∀ e r, Measure.map (S.evaluation e r) S.probability = W.law e) ∧
  ProbabilityTheory.IndepFun (trainingFold S) (allEvaluationData S) S.probability ∧
  (∀ i, @Measurable (Ω × LatentState n) ℝ
    ((MeasurableSpace.comap (trainingFold S) inferInstance).prod inferInstance)
    inferInstance (fun p => S.ratioEstimate p.1 i p.2))

/-- The full independent-environment sampling contract supplies the smaller collection of
assumptions needed for conditional evaluation-fold concentration. -/
lemma IndependentEnvironmentSampling.toConditionalEvaluationSampling
    (h : IndependentEnvironmentSampling S) : ConditionalEvaluationSampling S := by
  rcases h with
    ⟨hprob, hlaw, htrainMeas, _htrainIndep, _htrainLaw,
      hevalMeas, hevalIndep, hevalLaw, hsplit, _hratioMeas,
      hratioJoint, _hfirstMeas⟩
  have htrain : Measurable (trainingFold S) := by
    apply measurable_pi_lambda
    intro e
    apply measurable_pi_lambda
    intro r
    exact htrainMeas e r
  exact ⟨hprob, hlaw, htrain, hevalMeas, hevalIndep, hevalLaw, hsplit, hratioJoint⟩

/-- Event `E` has conditional probability at least `p`, on event `A`, relative to `m`.
The setwise formulation avoids selecting a conditional-expectation version. -/
def ConditionalProbabilityAtLeast
    {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω) (m : MeasurableSpace Ω)
    (E A : Set Ω) (p : ℝ) : Prop :=
  ∀ B : Set Ω, @MeasurableSet Ω m B →
    p * μ.real (A ∩ B) ≤ μ.real (E ∩ A ∩ B)

/-- The minimum sample size across observational and intervention environments. -/
def minimumSampleSize : ℕ :=
  Finset.univ.inf' ⟨0, Finset.mem_univ 0⟩ S.sampleSize
  -- @realizes \(\underline N\)(minimum over all environment sample sizes)

/-- Empirical mean embedding for ratio estimate `i` in environment `e`. -/
def empiricalMeanEmbedding
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H]
    (U : UnitNormFeatureMap H) (e : Fin (n + 1)) (i : Fin n) (ω : Ω) : H :=
  (S.sampleSize e : ℝ)⁻¹ •
    ∑ r, U.Φ (S.ratioEstimate ω i (S.evaluation e r ω))

/-- The sample-split empirical Gaussian-kernel MMD. -/
def empiricalDiscrepancy
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H]
    (U : UnitNormFeatureMap H) (j i : Fin n) (ω : Ω) : ℝ :=
  ‖empiricalMeanEmbedding S U j.succ i ω - empiricalMeanEmbedding S U 0 i ω‖
  -- @realizes \(\widehat D_{ji}\)(norm of empirical embedding difference)

/-- The paper's simultaneous confidence radius. -/
def confidenceRadius : ℝ :=
  2 * Real.sqrt 2 * S.firstStageRadius S.eta +
    2 * (1 + Real.sqrt (2 * Real.log
      ((n : ℝ) * (n + 1 : ℝ) / S.alpha))) /
      Real.sqrt (minimumSampleSize S)
  -- @realizes \(\varepsilon_N(\alpha,\eta)\)(explicit simultaneous radius)

-- @node: def:sample-split-confidence-graph
/-- The graph selected by positive lower confidence bounds for population discrepancies. -/
def sampleSplitConfidenceGraph
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H]
    (U : UnitNormFeatureMap H) (_hSampling : IndependentEnvironmentSampling S)
    (ω : Ω) : Fin n → Fin n → Prop :=
  fun j i => j ≠ i ∧ 0 < empiricalDiscrepancy S U j i ω - confidenceRadius S
  -- @realizes \(\widehat H\)(edge iff empirical MMD minus radius is positive)

end CausalSmith.ExactID.EID_CrlCoverratioMmdGenericity
