module
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareSignedObservation
public import Causalean.Mathlib.InformationTheory.CommonStatisticBernoulli

/-!
# Re-exported common-statistic Bernoulli substrate

The measure-theoretic construction now lives in Causalean; this module retains
the accepted run’s original aliases.
-/

public section

namespace CausalSmith.Stat.BddUniformLogPenalty

export Causalean.Mathlib.InformationTheory (statisticSuccessMeasure statisticSuccessParameter statisticSuccessMeasure_absolutelyContinuous statisticSuccessParameter_setIntegral statisticSuccessParameter_mem_Icc_ae clippedStatisticSuccessParameter clippedStatisticSuccessParameter_measurable clippedStatisticSuccessParameter_mem_Icc clippedStatisticSuccessParameter_ae_eq commonStatisticBernoulliKernel_setLIntegral_eq statisticBernoulliOutcomeLaw_eq_map_swap_compProd clippedStatisticSuccessParameter_abs_sub_le_ae statisticBernoulliOutcome_klDiv_le_of_localized_success_bound statisticBernoulliOutcome_restrict_compl_eq_of_localized_success_bound)

end CausalSmith.Stat.BddUniformLogPenalty
