/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import CausalSmith.Experimentation.EXP_DesignPm1ExactnessBoundaryV1_Research.Helpers.SymRedPSD
public import CausalSmith.Experimentation.EXP_DesignPm1ExactnessBoundaryV1_Research.Helpers.SymRedDesign

/-! # Symmetry reduction (orbit averaging over the two-block automorphism group)

Orbit-averaging over the finite group `H` generated by within-`A_m`, within-`B_m`
permutations and the community swap: convexity of the PSD cone, `H`-invariance of
`L_m`, `L_m^†`, `J_n`, and orthogonal-invariance/convexity of the Frobenius norm
give a no-worse `H`-symmetrized point/law. Hence the relaxed and implementable
infima are attained on the block-symmetric slices. -/

public section

namespace CausalSmith.Experimentation.DesignPm1

open scoped BigOperators
open Causalean.Experimentation.DesignBased

-- @node: prop:symmetry-reduction
/-- Symmetry reduction. The orbit-average over the full two-block automorphism group
(permutations within `A_m`, within `B_m`, and the community swap) is the *explicit,
named* no-worse witness — not merely some existing block-symmetric point (the note's
load-bearing clauses):

* every PSD unit-diagonal matrix `X` is mapped by orbit averaging to the block-symmetric
  elliptope point `blockSymMatrix m (uOf m X) (vOf m X) ∈ E_m^blk`, whose block entries
  `uOf m X`, `vOf m X` are the averaged within- and across-community entries of `X`, with
  weakly smaller objective, and
* every balanced law `D ∈ P_m^bal` is mapped by the same orbit averaging to the
  block-exchangeable law `orbitAvgDesign m D ∈ P_m^sym`, with the same zero one-point
  margins and weakly smaller objective.

The two `sInf` equalities (relaxed = block-symmetric slice, implementable = symmetry
reduced) are the consequences. (`0 ≤ r` and `0 ≤ κ` are the definitional-domain
regularity premises, reflected in the assumption table.) -/
lemma symmetry_reduction (m : ℕ) (a b r kappa : ℝ)
    (hHom : TwoBlockHomophily m a b) (hr0 : 0 ≤ r) (hk : 0 ≤ kappa) :
    (∀ X : Matrix (Fin (2 * m)) (Fin (2 * m)) ℝ, X.PosSemidef → (∀ i, X i i = 1) →
      BlockElliptopeMem m a b (uOf m X) (vOf m X) ∧
        designObjective m a b r kappa (blockSymMatrix m (uOf m X) (vOf m X))
          ≤ designObjective m a b r kappa X) ∧
    (∀ D : FiniteDesign (Fin (2 * m) → Bool), BalancedDesignClass m D →
        orbitAvgDesign m D ∈ blockExchangeableDesignClass m ∧
        (∀ i, (orbitAvgDesign m D).E (fun z => signOf m z i) = 0) ∧
        designObjective m a b r kappa (assignmentSecondMoment m (orbitAvgDesign m D))
          ≤ designObjective m a b r kappa (assignmentSecondMoment m D)) ∧
    sInf (designObjective m a b r kappa ''
        { X : Matrix (Fin (2 * m)) (Fin (2 * m)) ℝ | X.PosSemidef ∧ ∀ i, X i i = 1 })
      = sInf (designObjective m a b r kappa '' blockElliptope m a b) ∧
    sInf ((fun D => designObjective m a b r kappa (assignmentSecondMoment m D)) ''
        { D | BalancedDesignClass m D })
      = sInf ((fun D => designObjective m a b r kappa (assignmentSecondMoment m D)) ''
        blockExchangeableDesignClass m) := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · -- Conjunct 1: matrix-side symmetrization — witness is the orbit average `(uOf, vOf)`.
    intro X hpsd hdiag
    exact symmetrize_objective_le m a b r kappa hHom hk X hpsd hdiag
  · -- Conjunct 2: design-side symmetrization — witness is `orbitAvgDesign m D`.
    intro D hD
    exact design_symmetrize m a b r kappa hHom hk D hD
  · -- Conjunct 3: relaxed inf = block-symmetric-slice inf.
    refine sInf_image_reduce (designObjective m a b r kappa)
      { X : Matrix (Fin (2 * m)) (Fin (2 * m)) ℝ | X.PosSemidef ∧ ∀ i, X i i = 1 }
      (blockElliptope m a b) (blockElliptope_subset_elliptope m a b) ?_
      (designObjective_bddBelow m a b r kappa hHom hk) ?_
    · exact ⟨blockSymMatrix m 0 0, 0, 0, rfl, ⟨hHom, by norm_num, by norm_num, by norm_num⟩⟩
    · intro X hX
      obtain ⟨hpsd, hdiag⟩ := hX
      obtain ⟨hmem, hle⟩ := symmetrize_objective_le m a b r kappa hHom hk X hpsd hdiag
      exact ⟨blockSymMatrix m (uOf m X) (vOf m X),
        ⟨uOf m X, vOf m X, rfl, hmem⟩, hle⟩
  · -- Conjunct 4: implementable inf = symmetry-reduced inf.
    refine sInf_image_reduce
      (fun D => designObjective m a b r kappa (assignmentSecondMoment m D))
      { D | BalancedDesignClass m D } (blockExchangeableDesignClass m)
      (fun D hD => hD.1) ⟨iidDesign m, iidDesign_mem_blockExchangeable m⟩ ?_ ?_
    · -- Bounded below: second moments are PSD unit-diagonal, so land in the elliptope.
      refine BddBelow.mono ?_ (designObjective_bddBelow m a b r kappa hHom hk)
      rintro _ ⟨D, _, rfl⟩
      exact ⟨assignmentSecondMoment m D,
        ⟨assignmentSecondMoment_posSemidef m D, assignmentSecondMoment_diag m D⟩, rfl⟩
    · intro D hD
      obtain ⟨hmem, _, hle⟩ := design_symmetrize m a b r kappa hHom hk D hD
      exact ⟨orbitAvgDesign m D, hmem, hle⟩

end CausalSmith.Experimentation.DesignPm1
