import CausalSmith.SCM.SCM_SelectiveLabelUntrialedImpact_Research.Basic
import Mathlib.Data.Fin.VecNotation
import Mathlib.Tactic.FinCases
import Mathlib.Tactic.NormNum

/-!
# The balanced thirty-two-type witness

Concrete three-performance design, its complete quotient table, and the
four-coordinate positive mixture used by the exact refinement certificate.
-/

namespace CausalSmith.SCM.SelectiveLabelUntrialedImpact

open scoped BigOperators
open Set

noncomputable section

-- @env: S3
-- @realizes S_32_set(singleton stratum Fin 1)
-- @realizes J_32(three policies Fin 3)
-- @realizes J_32_0(two trial arms Fin 2)
-- @realizes Q_32_set(three ordered performance levels Fin 3)
-- @realizes I_32(thirty-two row indices Fin 32)
variable (i32 : Fin 32)

/-- Low and high trial policies, with policy `1` reserved for the untrialed middle policy. -/
def witnessTrialPolicy (j : Fin 2) : Fin 3 := if j = 0 then 0 else 2

/-- The concrete singleton-stratum, three-performance, balanced design. -/
-- @node: def:32-design-specialization
noncomputable def witness32Design : SLCCDesign where
  Stratum := Fin 1
  Policy := Fin 3
  TrialArm := Fin 2
  Performance := Fin 3
  untrialed := 1 -- @realizes e_32(untrialed middle policy)
  trialPolicy := witnessTrialPolicy
  trialPolicy_injective := by
    intro a b h
    fin_cases a <;> fin_cases b
    all_goals simp_all [witnessTrialPolicy]
  untrialed_not_trial := by
    intro j
    fin_cases j <;> simp [witnessTrialPolicy]
  qValue := fun q => (q.val + 1 : ℝ) / 4
  qValue_strictMono := by
    intro a b h
    dsimp
    apply (div_lt_div_iff_of_pos_right (by norm_num)).2
    exact_mod_cast Nat.add_lt_add_right h 1
  qValue_pos := by intro q; fin_cases q <;> norm_num
  qValue_lt_one := by intro q; fin_cases q <;> norm_num
  config := fun j _ => (true, j) -- @realizes c_32(low, middle, high configurations)
  rho := fun _ => 1 / 2 -- @realizes rho_32(balanced probabilities 1/2)
  rho_pos := by intro j; norm_num
  rho_sum := by norm_num [Fin.sum_univ_two]

/-- The displayed action array in row `i`. -/
def witness32Action (i : Fin 32) (c : Bool × Fin 3) : Bool :=
  if !c.1 then false
  else if c.2 = 0 then decide (i.val % 4 ≥ 2)
  else if c.2 = 2 then decide (i.val % 2 = 1)
  else false

/-- The displayed legal outcome path in row `i`. -/
def witness32Outcome (i : Fin 32) (c : Bool × Fin 3) : Bool :=
  if i.val < 16 then
    if !c.1 then true
    else decide (c.2.val < i.val / 4)
  else
    if !c.1 then false
    else decide (3 - c.2.val ≤ (i.val - 16) / 4)

/-- The raw displayed response type in row `i`. -/
def witness32Raw (i : Fin 32) : RawResponseType witness32Design where
  stratum := ⟨0, Nat.zero_lt_one⟩
  truth := decide (16 ≤ i.val)
  actionResponse := witness32Action i
  outcomeResponse := witness32Outcome i

/-- Every displayed row satisfies the four legality restrictions. -/
lemma witness32_legal (i : Fin 32) :
    CounterfactualCorrectness witness32Design (witness32Raw i).truth
        (witness32Raw i).outcomeResponse ∧
      CorrectPerformanceOrder witness32Design (witness32Raw i).truth
        (witness32Raw i).outcomeResponse ∧
      IncorrectPerformanceOrder witness32Design (witness32Raw i).truth
        (witness32Raw i).outcomeResponse ∧
      NeutralPerformanceInvariance witness32Design (witness32Raw i).outcomeResponse := by
  sorry

/-- The displayed legal response type. -/
noncomputable def witness32Type (i : Fin 32) : LegalResponseType witness32Design where
  raw := witness32Raw i
  correctness := (witness32_legal i).1
  correctOrder := (witness32_legal i).2.1
  incorrectOrder := (witness32_legal i).2.2.1
  neutralInvariant := (witness32_legal i).2.2.2

/-- Row offset within one trial arm's six selectively-labelled cells. -/
def witnessCellOffset (a y z : Bool) : Fin 6 :=
  if !a then if y then 1 else 0
  else if !y then if z then 3 else 2
  else if z then 5 else 4

/-- The observable row generated by arm `j` and displayed type `i`. -/
def witnessObservableRow (j : Fin 2) (i : Fin 32) : Fin 12 :=
  ⟨6 * j.val + (witnessCellOffset
    (witness32Action i (true, if j = 0 then 0 else 2))
    (witness32Outcome i (true, if j = 0 then 0 else 2))
    (decide (16 ≤ i.val))).val, by
      have hj : j.val ≤ 1 := Nat.le_of_lt_succ j.isLt
      have ho := (witnessCellOffset
        (witness32Action i (true, if j = 0 then 0 else 2))
        (witness32Outcome i (true, if j = 0 then 0 else 2))
        (decide (16 ≤ i.val))).isLt
      omega⟩

/-- The exact twelve-by-thirty-two balanced incidence table. -/
def witness32Incidence : Matrix (Fin 12) (Fin 32) ℝ := fun o i =>
  if o = witnessObservableRow 0 i ∨ o = witnessObservableRow 1 i then 1 / 2 else 0
  -- @realizes B_32(two half-mass observable rows per column)

/-- The middle-performance outcome target in the displayed table. -/
def witness32Target (i : Fin 32) : ℝ :=
  if witness32Outcome i (true, 1) then 1 else 0
  -- @realizes h_32(middle-performance outcome)

/-- The eight-by-twelve label-blind aggregation matrix. -/
def witness32Coarsening : Matrix (Fin 8) (Fin 12) ℝ := fun b o =>
  let arm := o.val / 6
  let localRow := o.val % 6
  let action : Nat := if localRow < 2 then 0 else 1
  let outcome : Nat := if localRow = 1 ∨ 4 ≤ localRow then 1 else 0
  if b.val = 4 * arm + 2 * action + outcome then 1 else 0
  -- @realizes K_32(forget revealed label, retain arm-action-outcome)

/-- The concrete table and all of its incidence-side data. -/
structure Witness32Table where
  types : Fin 32 → LegalResponseType witness32Design
  B : Matrix (Fin 12) (Fin 32) ℝ
  polytope : Set (Fin 12 → ℝ)
  target : Fin 32 → ℝ
  coarsening : Matrix (Fin 8) (Fin 12) ℝ

/-- Complete thirty-two-row quotient table with its twelve observable rows. -/
-- @node: def:complete-32-type-table
noncomputable def witness32TypeTable : Witness32Table where
  types := witness32Type -- @realizes t_32(indexed legal response types)
  B := witness32Incidence
  polytope := {p | ∃ w ∈ stdSimplex ℝ (Fin 32), witness32Incidence.mulVec w = p}
    -- @realizes O_32_poly(B_32 Delta_31)
  target := witness32Target
  coarsening := witness32Coarsening

/-- The admissible four-coordinate parameter region. -/
def Witness32Parameter (pi : Fin 4 → ℝ) : Prop :=
  pi ∈ stdSimplex ℝ (Fin 4) ∧ (∀ k, 0 < pi k) ∧ pi 1 = pi 2 ∧ pi 3 / 8 < pi 1
  -- @realizes pi_32(relative-interior simplex coordinates and restrictions)

/-- The common small row weight. -/
def witness32Epsilon (pi : Fin 4 → ℝ) : ℝ := pi 3 / 24
  -- @realizes epsilon_32(pi_4 / 24)

/-- The exceptional row-20 weight. -/
def witness32A (pi : Fin 4 → ℝ) : ℝ := pi 1 - pi 3 / 8
  -- @realizes a_32(pi_2 - pi_4 / 8)

/-- The exceptional row-32 weight. -/
def witness32B (pi : Fin 4 → ℝ) : ℝ := pi 0 + pi 1 - pi 3 / 8
  -- @realizes b_32(pi_1 + pi_2 - pi_4 / 8)

/-- The strictly positive thirty-two-coordinate mixture. -/
def witness32Weights (pi : Fin 4 → ℝ) (i : Fin 32) : ℝ :=
  if i.val = 19 then witness32A pi
  else if i.val = 31 then witness32B pi
  else witness32Epsilon pi
  -- @realizes w_32(epsilon except rows 20 and 32)

/-- The symmetric coordinate. -/
def witness32Pi0 : Fin 4 → ℝ := fun _ => 1 / 4
  -- @realizes pi_32_0((1,1,1,1)/4)

/-- The perturbed relative-interior coordinate. -/
def witness32PiCirc : Fin 4 → ℝ := ![198 / 800, 199 / 800, 199 / 800, 204 / 800]
  -- @realizes pi_32_circ((198,199,199,204)/800)

/-- The two rational full observable laws. -/
def witness32Law (pi : Fin 4 → ℝ) : Fin 12 → ℝ :=
  witness32Incidence.mulVec (witness32Weights pi)

/-- All data in the four-coordinate witness mixture. -/
structure Witness32MixtureData where
  parameter : Set (Fin 4 → ℝ)
  epsilon : (Fin 4 → ℝ) → ℝ
  a : (Fin 4 → ℝ) → ℝ
  b : (Fin 4 → ℝ) → ℝ
  weights : (Fin 4 → ℝ) → Fin 32 → ℝ
  symmetricLaw : Fin 12 → ℝ
  perturbedLaw : Fin 12 → ℝ

/-- The four-coordinate mixture and its two distinguished rational laws. -/
-- @node: def:32-coordinate-mixture
def witness32Mixture : Witness32MixtureData where
  parameter := {pi | Witness32Parameter pi}
  epsilon := witness32Epsilon
  a := witness32A
  b := witness32B
  weights := witness32Weights
  symmetricLaw := witness32Law witness32Pi0 -- @realizes p_32(B_32 w_32(pi_32_0))
  perturbedLaw := witness32Law witness32PiCirc -- @realizes p_32_circ(B_32 w_32(pi_32_circ))

/-- The primitive bracket-stratum design condition. -/
-- @node: def:bracket-stratum-design
def BracketSLCC (d : SLCCDesign) : Prop :=
  ∃ sStar : d.Stratum, ∃ qLow qMid qHigh : d.Performance,
    qLow < qMid ∧ qMid < qHigh ∧
    d.config d.untrialed sStar = (true, qMid) ∧
    (∀ j, d.config (d.trialPolicy j) sStar = (true, qLow) ∨
      d.config (d.trialPolicy j) sStar = (true, qHigh)) ∧
    (∃ j, d.config (d.trialPolicy j) sStar = (true, qLow)) ∧
    (∃ j, d.config (d.trialPolicy j) sStar = (true, qHigh)) ∧
    ∀ j, 0 < d.rho j
  -- @realizes Bracket_SLCC(bracketing at one stratum with positive arm weights)

end

end CausalSmith.SCM.SelectiveLabelUntrialedImpact
