module
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Estimator

/-!
# Cited CTY interfaces

These three named propositions record external source statements.  They are
never proved here; every consumer takes an explicit inhabitant.
-/

@[expose] public section

open Filter MeasureTheory ProbabilityTheory Set
open scoped BigOperators ENNReal NNReal Topology

namespace CausalSmith.Stat.BddUniformLogPenalty

/-- A metric on the score space which is uniformly equivalent to Euclidean
distance on the score support, exactly as in CTY Assumption 2(ii). -/
def CtyIdentificationMetric (P : A1A2Law)
    (d : Score → Score → ℝ) : Prop :=
  (∀ x, d x x = 0) ∧
  (∀ x z, 0 ≤ d x z ∧ (d x z = 0 ↔ x = z)) ∧
  (∀ x z, d x z = d z x) ∧
  (∀ x y z, d x z ≤ d x y + d y z) ∧
  ∃ c C : ℝ, 0 < c ∧ c ≤ C ∧
    ∀ x ∈ P.support, ∀ z ∈ P.support,
      c * dist x z ≤ d x z ∧ d x z ≤ C * dist x z

/-- Signed distance for the general metric admitted by the cited
identification theorem. -/
noncomputable def identificationSignedDistance (P : A1A2Law)
    (d : Score → Score → ℝ) (x z : Score) : ℝ :=
  (P.A1.indicator (fun _ => (1 : ℝ)) z -
    P.A0.indicator (fun _ => (1 : ℝ)) z) * d z x

/-- The Hausdorff slice denominator in CTY Assumption 2(v). -/
noncomputable def identificationSliceDensityMass (P : A1A2Law)
    (d : Score → Score → ℝ) (t : Bool) (x : Score) (s : ℝ) : ℝ≥0∞ :=
  ∫⁻ z in {z | z ∈ (if t then P.A1 else P.A0) ∧ d z x = s},
    ENNReal.ofReal (P.density z) ∂Measure.hausdorffMeasure 1

/-- Exactly CTY Assumptions 1(i)--(iii) and 2(i), (ii), and (v), with i.i.d.
sampling supplied by `causalSampleLaw`.  Armwise potential-outcome
integrability records the genuine scope in which the conditional means in
Assumption 1(iii) exist.  No variance envelope, higher-moment envelope,
kernel, Gram, VC, local-mass, or quantitative derivative-envelope clause is
imposed. -/
def CtyIdentificationAssumptions (p : ℕ) (P : A1A2Law)
    (d : Score → Score → ℝ) : Prop :=
  (∃ lo hi : ℝ, lo < hi ∧
    P.support = {x | ∀ i, lo ≤ x i ∧ x i ≤ hi}) ∧
  ContinuousOn P.density P.support ∧
  (∀ x ∈ P.support, 0 < P.density x) ∧
  (∀ t : Bool, Integrable (armCoord t) P.law) ∧
  (∀ t, ∃ U : Set Score, IsOpen U ∧ P.support ⊆ U ∧
    ∃ g : Score → ℝ, ContDiffOn ℝ (p + 1 : ℕ) g U ∧
      Set.EqOn g (P.muPO t) P.support) ∧
  RectifiableCurve P.boundary ∧
  0 < Measure.hausdorffMeasure 1 P.boundary ∧
  CtyIdentificationMetric P d ∧
  ∀ x ∈ P.boundary, ∀ t : Bool, ∃ ε : ℝ, 0 < ε ∧
    ∀ s : ℝ, 0 < s → s ≤ ε →
      0 < identificationSliceDensityMass P d t x s ∧
        identificationSliceDensityMass P d t x s < ∞

/-- One source-coherent selected pair of armwise signed-distance
conditional-mean versions.  The disintegration identity pins both one-sided
functions to one selected conditional law, avoiding arbitrary pointwise
choices of `condDistrib`. -/
def SignedDistanceMeanVersions (P : A1A2Law) (d : Score → Score → ℝ) (x : Score)
    (θ₁ θ₀ : ℝ → ℝ) : Prop :=
  ∃ κ : Kernel ℝ ℝ,
    IsMarkovKernel κ ∧
    (Measure.map (fun w => identificationSignedDistance P d x (causalScore w)) P.law).compProd κ =
      Measure.map (fun w =>
        (identificationSignedDistance P d x (causalScore w), observedOutcome P w)) P.law ∧
    (∀ r, 0 < r → θ₁ r = ∫ y, y ∂κ r) ∧
    (∀ r, r < 0 → θ₀ r = ∫ y, y ∂κ r)

-- @node: lem:cty-distance-identification
/-- **Cattaneo, Titiunik, and Yu (2026), Theorem 1**, printed p. 4,
DOI `10.1016/j.jeconom.2026.106266`: under the displayed Assumptions 1(i)--(iii)
and 2(i),(ii),(v), there is a selected source-coherent signed-distance
conditional-mean version whose one-sided limits identify the boundary effect.
The statement does not range over every arbitrary disintegration or version. -/
def CtyDistanceIdentification (p : ℕ) (_ν _L : ℝ) : Prop :=
  ∀ P : A1A2Law, ∀ d : Score → Score → ℝ,
    CtyIdentificationAssumptions p P d → ∀ x ∈ P.boundary,
    ∃ θ₁ θ₀ : ℝ → ℝ, SignedDistanceMeanVersions P d x θ₁ θ₀ ∧
      ∃ rightLimit leftLimit : ℝ,
        Tendsto θ₁ (nhdsWithin 0 (Set.Ioi 0)) (nhds rightLimit) ∧
        Tendsto θ₀ (nhdsWithin 0 (Set.Iio 0)) (nhds leftLimit) ∧
        P.tau x = rightLimit - leftLimit

/-- A finite set is shattered by the distance balls generated by `d`, with
centres restricted to the score support as in CTY Assumption 2(iii). -/
def ShatteredByMetricBalls (P : A1A2Law) (d : Score → Score → ℝ)
    (S : Finset Score) : Prop :=
  ∀ T : Finset Score, T ⊆ S →
    ∃ x ∈ P.support, ∃ r : ℝ, 0 ≤ r ∧
      ∀ z ∈ S, (z ∈ T ↔ d z x ≤ r)

/-- The distance-ball family in CTY's uniform-kernel alternative has finite
VC index.  No Euclidean specialization or fixed numerical index is imposed. -/
def CtyMetricBallsVCProperty (P : A1A2Law)
    (d : Score → Score → ℝ) : Prop :=
  ∃ v : ℕ, ∀ S : Finset Score, v ≤ S.card →
    ¬ ShatteredByMetricBalls P d S

/-- The two kernel alternatives in CTY Assumption 2(iii): a nonnegative,
compactly supported Lipschitz kernel, or the uniform kernel together with a
finite-VC distance-ball family. -/
def CtyUniformBiasKernel (P : A1A2Law) (d : Score → Score → ℝ)
    (K : ℝ → ℝ) : Prop :=
  (∀ u, 0 ≤ K u) ∧
  ((HasCompactSupport K ∧ ∃ C : ℝ≥0, LipschitzWith C K) ∨
    (K = uniformKernel ∧ CtyMetricBallsVCProperty P d))

/-- The population Gram matrix for the general metric/kernel regime of CTY
Theorem 2. -/
noncomputable def ctyUniformBiasPopulationGram (P : A1A2Law) (p : ℕ)
    (d : Score → Score → ℝ) (K : ℝ → ℝ) (t : Bool)
    (x : Score) (h : ℝ) : Matrix (Fin (p + 1)) (Fin (p + 1)) ℝ := by
  classical
  exact fun j k => ∫ w,
    h⁻¹ ^ 2 *
      (if signedArm t (identificationSignedDistance P d x (causalScore w))
        then 1 else 0) *
      K (identificationSignedDistance P d x (causalScore w) / h) *
      polyBasis p (identificationSignedDistance P d x (causalScore w) / h) j *
      polyBasis p (identificationSignedDistance P d x (causalScore w) / h) k ∂P.law

/-- The population score in the general metric/kernel normal equations. -/
noncomputable def ctyUniformBiasPopulationScore (P : A1A2Law) (p : ℕ)
    (d : Score → Score → ℝ) (K : ℝ → ℝ) (t : Bool)
    (x : Score) (h : ℝ) : Fin (p + 1) → ℝ := by
  classical
  exact fun j => ∫ w,
    h⁻¹ ^ 2 *
      (if signedArm t (identificationSignedDistance P d x (causalScore w))
        then 1 else 0) *
      K (identificationSignedDistance P d x (causalScore w) / h) *
      polyBasis p (identificationSignedDistance P d x (causalScore w) / h) j *
      observedOutcome P w ∂P.law

/-- The original, unwinsorized population coefficient in CTY's full
metric/kernel regime. -/
noncomputable def ctyUniformBiasPopulationCoefficient (P : A1A2Law) (p : ℕ)
    (d : Score → Score → ℝ) (K : ℝ → ℝ) (t : Bool)
    (x : Score) (h : ℝ) : Fin (p + 1) → ℝ :=
  Matrix.mulVec (ctyUniformBiasPopulationGram P p d K t x h)
    ⁻¹ (ctyUniformBiasPopulationScore P p d K t x h)

/-- The smallest Rayleigh quotient of the population Gram matrix, represented
in `ℝ≥0∞` so the infimum is total. -/
noncomputable def ctyUniformBiasGramFloor (P : A1A2Law) (p : ℕ)
    (d : Score → Score → ℝ) (K : ℝ → ℝ) (t : Bool)
    (h : ℝ) : ℝ≥0∞ :=
  ⨅ x : Score, ⨅ (_hx : x ∈ P.boundary),
    ⨅ v : Fin (p + 1) → ℝ, ⨅ (_hv : ∑ i, (v i) ^ 2 = 1),
      ENNReal.ofReal
        (matrixQuadratic (ctyUniformBiasPopulationGram P p d K t x h) v)

/-- Lebesgue mass of a general metric/kernel arm neighborhood. -/
noncomputable def ctyUniformBiasArmLocalMass (P : A1A2Law)
    (d : Score → Score → ℝ) (K : ℝ → ℝ) (t : Bool)
    (x : Score) (h : ℝ) : ℝ≥0∞ :=
  ∫⁻ z in (if t then P.A1 else P.A0),
    ENNReal.ofReal (h⁻¹ ^ 2 *
      K (((if t then 1 else -1 : ℝ) * d z x) / h)) ∂volume

/-- The source-sized class in CTY Theorem 2.  It retains Assumptions
1(i)--(iii), all of Assumption 2, the displayed uniform density and derivative
envelopes, and the two genuine liminf small-bandwidth restrictions.  It is not
the Euclidean/uniform-kernel `P₁₂` specialization. -/
def CtyUniformBiasLawClass (p : ℕ) (L : ℝ) (P : A1A2Law)
    (d : Score → Score → ℝ) (K : ℝ → ℝ) : Prop :=
  1 ≤ L ∧
  CtyIdentificationAssumptions p P d ∧
  P.support ⊆ scoreCube L ∧
  (∀ x ∈ P.support, L⁻¹ ≤ P.density x ∧ P.density x ≤ L) ∧
  (∀ t, EuclideanCExtEnvelope (P.muPO t) p L P.support) ∧
  CtyUniformBiasKernel P d K ∧
  (∀ t : Bool, ∃ c : ℝ, 0 < c ∧
    ENNReal.ofReal c ≤
      liminf (ctyUniformBiasGramFloor P p d K t)
        (nhdsWithin 0 (Set.Ioi 0))) ∧
  ∀ t : Bool,
    ENNReal.ofReal L⁻¹ ≤
      liminf
        (fun h => ⨅ x : Score, ⨅ (_hx : x ∈ P.boundary),
          ctyUniformBiasArmLocalMass P d K t x h)
        (nhdsWithin 0 (Set.Ioi 0))

/-- Uniform absolute population-contrast bias normalized by bandwidth over
the exact Euclidean/uniform-kernel `P₁₂(p,ν,L)` specialization used by the
upper theorem. -/
noncomputable def causalUniformBiasRatio (p : ℕ) (ν L h : ℝ) : ℝ≥0∞ :=
  ⨆ P : A1A2Law, ⨆ (_hP : A1A2Class p ν L P),
    ⨆ x : Score, ⨆ (_hx : x ∈ P.boundary), ENNReal.ofReal
      (|(populationCoefficient P p true x h 0 -
          populationCoefficient P p false x h 0) - P.tau x| / h)

-- @node: lem:cty-uniform-first-order-bias
/-- **Cattaneo, Titiunik, and Yu (2026), Theorem 2**, printed pp. 5--6,
DOI `10.1016/j.jeconom.2026.106266`: the upper-only corollary used here on
the exact `P₁₂(p,ν,L)` specialization.  A constant depending only on `p` and
`L` controls the finite limsup uniformly in `ν`, along every positive
antitone deterministic bandwidth sequence with `h_n → 0` and
`n h_n² → ∞`. -/
def CtyUniformFirstOrderBias (p : ℕ) (L : ℝ) : Prop :=
  ∃ C : ℝ, 0 < C ∧ ∀ ν : ℝ, 2 ≤ ν → ∀ hseq : ℕ → ℝ,
    (∀ n : ℕ, 0 < hseq n) → Antitone hseq →
    Tendsto hseq atTop (nhds 0) →
    Tendsto (fun n : ℕ => (n : ℝ) * (hseq n) ^ 2) atTop atTop →
    limsup (fun n => causalUniformBiasRatio p ν L (hseq n)) atTop ≤
      ENNReal.ofReal C

/-- The unwinsorized empirical score vector. -/
noncomputable def rawEmpiricalScore (n p : ℕ) (t : Bool) (h : ℝ)
    (u : SignedDistanceSample n) : Fin (p + 1) → ℝ := by
  classical
  exact fun j => (n : ℝ)⁻¹ * h⁻¹ ^ 2 * ∑ i,
    (if signedArm t (u i).2 then 1 else 0) * uniformKernel ((u i).2 / h) *
      polyBasis p ((u i).2 / h) j * (u i).1

/-- Uniform empirical Gram deviation for one sample. -/
noncomputable def causalGramDeviation (n p : ℕ) (P : A1A2Law)
    (h : ℝ) (w : CausalSample n) : ℝ≥0∞ :=
  ⨆ t : Bool, ⨆ x : Score, ⨆ (_hx : x ∈ P.boundary),
    ⨆ j : Fin (p + 1), ⨆ k : Fin (p + 1), ENNReal.ofReal
      |empiricalGram n p t h (signedDistanceData n P w x) j k -
        populationGram P p t x h j k|

/-- Uniform centered raw-score deviation for one sample. -/
noncomputable def causalRawScoreDeviation (n p : ℕ) (P : A1A2Law)
    (h : ℝ) (w : CausalSample n) : ℝ≥0∞ :=
  ⨆ t : Bool, ⨆ x : Score, ⨆ (_hx : x ∈ P.boundary),
    ENNReal.ofReal ‖rawEmpiricalScore n p t h
      (signedDistanceData n P w x) - populationScore P p t x h‖

-- @node: lem:cty-expected-local-polynomial-maximal-bounds
/-- **Cattaneo, Titiunik, and Yu (2026), Supplemental Appendix SA-8.3--8.4**,
printed pp. 32--35, DOI `10.1016/j.jeconom.2026.106266`: the expected outer
Gram and centered-score suprema satisfy the two displayed maximal bounds in
the small-bandwidth regime. -/
def CtyExpectedLocalPolynomialMaximalBounds (p : ℕ) (ν L : ℝ) : Prop :=
  ∃ C : ℝ, 0 < C ∧ ∀ hseq : ℕ → ℝ,
    (∀ n : ℕ, 0 < hseq n) → Tendsto hseq atTop (nhds 0) →
    Tendsto (fun n : ℕ =>
      (n : ℝ) ^ ((1 + ν) / (2 + ν)) * (hseq n) ^ 2 /
        Real.log ((hseq n)⁻¹)) atTop atTop →
    ∀ᶠ n in atTop, ∀ P : A1A2Law, A1A2Class p ν L P →
      MeasureTheory.outerLIntegral (causalSampleLaw P n)
          (causalGramDeviation n p P (hseq n)) ≤
        ENNReal.ofReal (C * Real.sqrt
          (Real.log ((hseq n)⁻¹) / ((n : ℝ) * (hseq n) ^ 2))) ∧
      MeasureTheory.outerLIntegral (causalSampleLaw P n)
          (causalRawScoreDeviation n p P (hseq n)) ≤
        ENNReal.ofReal (C *
          (Real.sqrt (Real.log ((hseq n)⁻¹) / ((n : ℝ) * (hseq n) ^ 2)) +
            Real.log ((hseq n)⁻¹) /
              ((n : ℝ) ^ ((1 + ν) / (2 + ν)) * (hseq n) ^ 2)))

end CausalSmith.Stat.BddUniformLogPenalty
