/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import Causalean.Estimation.ATE.DML
public import Causalean.Estimation.ATE.InfluenceFunction
public import Causalean.Estimation.ATE.PlugIn
public import Causalean.Estimation.ATE.Remainder
public import Causalean.Estimation.ATE.Remainder.Bound
public import Causalean.Estimation.ATE.Remainder.Identity
public import Causalean.Estimation.ATE.Score.AIPWMoment
public import Causalean.Estimation.ATE.Score.AIPWScoreL2
public import Causalean.Estimation.ATE.Score.FiniteVar
public import Causalean.Estimation.ATE.Score.MeanZero
public import Causalean.Estimation.ATE.Score.ScorePullout
public import Causalean.Estimation.ATE.Setup
public import Causalean.Estimation.ATT
public import Causalean.Estimation.CATE.Core.ConditionalBias
public import Causalean.Estimation.CATE.Core.PhiEtaDeriv
public import Causalean.Estimation.CATE.Core.PseudoOutcome
public import Causalean.Estimation.CATE.Core.PseudoOutcomeMean
public import Causalean.Estimation.CATE.Core.SecondOrderBias
public import Causalean.Estimation.CATE.Kennedy.DRLearner
public import Causalean.Estimation.CATE.Kennedy.LinearSmootherCATE
public import Causalean.Estimation.CATE.Kennedy.OracleExpansion
public import Causalean.Estimation.CATE.OrthogonalLearning.DRLearner
public import Causalean.Estimation.CATE.OrthogonalLearning.DRLearner.Analytic
public import Causalean.Estimation.CATE.OrthogonalLearning.LocalEmpProcess.DRLearner
public import Causalean.Estimation.CATE.OrthogonalLearning.LocalEmpProcess.DRLearnerEndToEnd
public import Causalean.Estimation.CATE.OrthogonalLearning.LocalEmpProcess.DRLearnerFixedNuisance
public import Causalean.Estimation.CATE.OrthogonalLearning.LocalEmpProcess.DRLearnerRandomNuisance
public import Causalean.Estimation.CATE.OrthogonalLearning.LocalEmpProcess.LocalizedDRLearner
public import Causalean.Estimation.CATE.OrthogonalLearning.LocalEmpProcess.LocalizedDRLearnerEndToEnd
public import Causalean.Estimation.CATE.OrthogonalLearning.SecondOrderBias
public import Causalean.Estimation.CATE.Setup
public import Causalean.Estimation.DTR.Constructor
public import Causalean.Estimation.DTR.DML
public import Causalean.Estimation.DTR.DTRInstance
public import Causalean.Estimation.DTR.FiniteVar
public import Causalean.Estimation.DTR.MeanZero
public import Causalean.Estimation.DTR.RemainderBound
public import Causalean.Estimation.DTR.RemainderIdentity
public import Causalean.Estimation.DTR.RemainderIdentity.Helpers
public import Causalean.Estimation.DTR.ScoreL2
public import Causalean.Estimation.DTR.ScoreL2.Helpers
public import Causalean.Estimation.DTR.ScorePullout
public import Causalean.Estimation.DTR.SeqDRMoment
public import Causalean.Estimation.DTR.Setup
public import Causalean.Estimation.Efficiency.ATEEfficientIF
public import Causalean.Estimation.Efficiency.ATETangent
public import Causalean.Estimation.Efficiency.ATEVariance
public import Causalean.Estimation.Efficiency.ArmMeanEfficientIF
public import Causalean.Estimation.Efficiency.ExponentialTilt
public import Causalean.Estimation.Efficiency.LAN.Convolution.Basic
public import Causalean.Estimation.Efficiency.LAN.Convolution.Convolution
public import Causalean.Estimation.Efficiency.LAN.Convolution.ConvolutionCore
public import Causalean.Estimation.Efficiency.LAN.Convolution.ExponentialTilt
public import Causalean.Estimation.Efficiency.LAN.Convolution.IIDDQM
public import Causalean.Estimation.Efficiency.LAN.Convolution.IIDDQMLAN
public import Causalean.Estimation.Efficiency.LAN.Convolution.LikelihoodNormalization
public import Causalean.Estimation.Efficiency.LAN.Convolution.LogTaylor
public import Causalean.Estimation.Efficiency.LAN.Convolution.TriangularArray
public import Causalean.Estimation.Efficiency.LAN.Convolution.Variance
public import Causalean.Estimation.Efficiency.LAN
public import Causalean.Estimation.Efficiency.PathwiseGradient
public import Causalean.Estimation.Efficiency.TangentProjection
public import Causalean.Estimation.Efficiency.TiltTangent
public import Causalean.Estimation.Efficiency.VonMises
public import Causalean.Estimation.MinimaxATE
public import Causalean.Estimation.NPIV.DR.AsymptoticLinear
public import Causalean.Estimation.NPIV.DR.AsymptoticNormal
public import Causalean.Estimation.NPIV.DR.Estimator
public import Causalean.Estimation.NPIV.MixedBias
public import Causalean.Estimation.NPIV.Operator
public import Causalean.Estimation.NPIV.Operator.Adjoint
public import Causalean.Estimation.NPIV.Operator.Complexification
public import Causalean.Estimation.NPIV.Operator.SpectralCalculus
public import Causalean.Estimation.NPIV.Operator.Tikhonov
public import Causalean.Estimation.NPIV.Primal.EmpiricalProcessEvent
public import Causalean.Estimation.NPIV.Primal.Estimator
public import Causalean.Estimation.NPIV.Primal.Rate
public import Causalean.Estimation.NPIV.Setup
public import Causalean.Estimation.NPIV.SourceCondition
public import Causalean.Estimation.OrthogonalLearning.LocalEmpProcess.Local
public import Causalean.Estimation.OrthogonalLearning.LocalEmpProcess.Localized
public import Causalean.Estimation.OrthogonalLearning.LocalEmpProcess.Rademacher
public import Causalean.Estimation.OrthogonalLearning.LocalEmpProcess.RandomNuisance
public import Causalean.Estimation.OrthogonalLearning.LocalEmpProcess.RandomParam
public import Causalean.Estimation.OrthogonalLearning.OracleInequality
public import Causalean.Estimation.OrthogonalLearning.PluginERM
public import Causalean.Estimation.OrthogonalLearning.Population.DirectionalDeriv
public import Causalean.Estimation.OrthogonalLearning.Population.NeymanOrthogonal
public import Causalean.Estimation.OrthogonalLearning.Population.SecondOrderBias
public import Causalean.Estimation.OrthogonalLearning.Setup
public import Causalean.Estimation.OrthogonalLearning.Sparse.PluginGuarantee
public import Causalean.Estimation.OrthogonalLearning.Sparse.RSC
public import Causalean.Estimation.OrthogonalLearning.Sparse.Setup
public import Causalean.Estimation.OrthogonalMoments.AIPWInstance
public import Causalean.Estimation.OrthogonalMoments.AutoDebias.ATE
public import Causalean.Estimation.OrthogonalMoments.AutoDebias.DML
public import Causalean.Estimation.OrthogonalMoments.AutoDebias.General
public import Causalean.Estimation.OrthogonalMoments.AutoDebias.GeneralDML
public import Causalean.Estimation.OrthogonalMoments.AutoDebias.Linear
public import Causalean.Estimation.OrthogonalMoments.DMLChernozhukov
public import Causalean.Estimation.OrthogonalMoments.DMLCrossFit
public import Causalean.Estimation.OrthogonalMoments.DirectionalDeriv
public import Causalean.Estimation.OrthogonalMoments.LinearSmoother
public import Causalean.Estimation.OrthogonalMoments.MomentFunctional
public import Causalean.Estimation.OrthogonalMoments.NeymanOrthogonal
public import Causalean.Estimation.OrthogonalMoments.Parametric
public import Causalean.Estimation.OrthogonalMoments.RemainderBound
public import Causalean.Estimation.OrthogonalMoments.Riesz
public import Causalean.Estimation.OrthogonalMoments.SecondStageOperator
public import Causalean.Estimation.PLR.DML
public import Causalean.Estimation.PLR.Feasible
public import Causalean.Estimation.PLR.JacobianConsistency
public import Causalean.Estimation.PLR.MeanZero
public import Causalean.Estimation.PLR.Moment
public import Causalean.Estimation.PLR.Nuisance
public import Causalean.Estimation.PLR.RemainderBound
public import Causalean.Estimation.PLR.ScoreL2
public import Causalean.Estimation.PLR.Setup

/-!
Estimation theory for causal and inverse problems, including orthogonal learning, NPIV, CATEs, minimax ATEs, and efficiency bounds. It develops the statistical guarantees needed for causal procedures.
-/
