import { describe, it, expect } from "vitest";
import { auditSubstrateGates, citedBlockers } from "../src/formalization/gate_ops.js";
import { isContentGateTag, toAssumptionClass } from "../src/formalization/proof_filler.js";
import { normalizeNodes } from "../bin/bank_entry.js";

/**
 * Regression fixture: the REAL pre-discharge state of `exp_bipartite_minimax_design/v1`.
 *
 * `EnvelopeLineC2Data` was disclosed in `state.added_assumptions` with
 * `classification: "substrate-gate"`, but was NEVER registered as a gate — the graph node stayed
 * `kind: "definition"` with no `gate` key, no plan `gate:true`, and no consumer threading it. The
 * entry banked `accepted` with an undischarged proof-step gate. `auditSubstrateGates` is the lint
 * that must catch exactly this.
 */
const BIPARTITE_DISCLOSURE = {
  label: "thm:heterogeneity-separation:EnvelopeLineC2Data",
  anchor: "thm:heterogeneity-separation",
  statement: "EnvelopeLineC2Data (segment C² + first-derivative identity + curvature bound)",
  source: "F3 substrate-debt: the quantitative gap is DERIVED …",
  classification: "substrate-gate" as const,
};

const REGULARITY_DISCLOSURE = {
  label: "thm:hetero-clt:epsilonFloor",
  anchor: "thm:hetero-clt",
  statement: "eventual positivity floor on ε_n",
  classification: "regularity-bookkeeping" as const,
};

describe("auditSubstrateGates", () => {
  it("FAILS the real exp_bipartite pre-discharge state: disclosed substrate-gate, unregistered node", () => {
    const findings = auditSubstrateGates({
      addedAssumptions: [BIPARTITE_DISCLOSURE, REGULARITY_DISCLOSURE],
      planNodes: [{ id: "envelope_segment_descent_gate", lean_name: "EnvelopeLineC2Data" }],
      graphNodes: [{ id: "envelope_segment_descent_gate", kind: "definition" }],
    });
    expect(findings).toHaveLength(1);
    expect(findings[0].label).toBe("thm:heterogeneity-separation:EnvelopeLineC2Data");
    expect(findings[0].reason).toMatch(/not registered/i);
  });

  it("passes once the node carries gate:true (properly registered gate)", () => {
    const findings = auditSubstrateGates({
      addedAssumptions: [BIPARTITE_DISCLOSURE],
      planNodes: [
        { id: "envelope_segment_descent_gate", lean_name: "EnvelopeLineC2Data", gate: true, gate_class: "gated" },
      ],
      graphNodes: [{ id: "envelope_segment_descent_gate", kind: "gate" }],
    });
    expect(findings).toEqual([]);
  });

  // Load-bearing PLAN side: registration recorded only in plan.json (graph node still `definition`,
  // e.g. a graph regenerated by an F2 re-scaffold) must still count as registered. Without reading
  // plan.json's map form this returns a finding, and bankEntry refuses a CORRECTLY registered gate
  // while `gate.ts --audit` — which reads the map — says clean.
  it("passes on a plan-only registration (graph node not yet kind:gate)", () => {
    const findings = auditSubstrateGates({
      addedAssumptions: [BIPARTITE_DISCLOSURE],
      planNodes: [
        { id: "envelope_segment_descent_gate", lean_name: "EnvelopeLineC2Data", gate: true, gate_class: "gated" },
      ],
      graphNodes: [{ id: "envelope_segment_descent_gate", kind: "definition" }],
    });
    expect(findings).toEqual([]);
  });

  it("passes once the gate is discharged (disclosure removed)", () => {
    const findings = auditSubstrateGates({
      addedAssumptions: [REGULARITY_DISCLOSURE],
      planNodes: [{ id: "envelope_segment_descent_gate", lean_name: "EnvelopeLineC2Data" }],
      graphNodes: [{ id: "envelope_segment_descent_gate", kind: "definition" }],
    });
    expect(findings).toEqual([]);
  });

  it("ignores non-substrate-gate classifications", () => {
    const findings = auditSubstrateGates({
      addedAssumptions: [
        { label: "thm:x:Foo", classification: "faithful-refinement" },
        { label: "thm:y:Bar", classification: "regularity-bookkeeping" },
      ],
      planNodes: [],
      graphNodes: [],
    });
    expect(findings).toEqual([]);
  });

  it("flags a disclosure whose node does not exist at all", () => {
    const findings = auditSubstrateGates({
      addedAssumptions: [{ label: "thm:z:GhostGate", classification: "substrate-gate" }],
      planNodes: [],
      graphNodes: [],
    });
    expect(findings).toHaveLength(1);
    expect(findings[0].reason).toMatch(/no plan\/graph node/i);
  });

  it("matches the graph node via lean.decl_name — the real shape, where id and Lean name differ", () => {
    // The exp_bipartite node id is `envelope_segment_descent_gate` while the disclosure is keyed
    // `…:EnvelopeLineC2Data`; the graph links them only through `lean.decl_name`. Without this the
    // finding misreports as "no plan/graph node" instead of "not registered".
    const findings = auditSubstrateGates({
      addedAssumptions: [BIPARTITE_DISCLOSURE],
      planNodes: [],
      graphNodes: [
        {
          id: "envelope_segment_descent_gate",
          kind: "definition",
          lean: { decl_name: "CausalSmith.Experimentation.BipartiteMinimaxDesign.EnvelopeLineC2Data" },
        },
      ],
    });
    expect(findings).toHaveLength(1);
    expect(findings[0].reason).toMatch(/not registered/i);
    expect(findings[0].reason).not.toMatch(/no plan\/graph node/i);
  });

  it("matches the node by Lean name as well as node id (F5 keys disclosures by Lean name)", () => {
    const findings = auditSubstrateGates({
      addedAssumptions: [BIPARTITE_DISCLOSURE],
      planNodes: [{ id: "some_other_id", lean_name: "EnvelopeLineC2Data", gate: true, gate_class: "gated" }],
      graphNodes: [{ id: "some_other_id", kind: "gate" }],
    });
    expect(findings).toEqual([]);
  });
});

describe("citedBlockers", () => {
  // The cited block was enforced ONLY inside the proof–review loop, in-process. `bank_entry.ts
  // --tier accepted` (and a resume re-entering at F5) banked a mismatched cited def silently,
  // because `check_status` was never persisted. bankEntry now re-checks `state.cited_checks`.
  it("blocks on cited-mismatch and cited-underspecified", () => {
    const blockers = citedBlockers([
      { name: "aCited", check_status: "cited-mismatch" },
      { name: "bCited", check_status: "cited-underspecified" },
    ]);
    expect(blockers.map((c) => c.name)).toEqual(["aCited", "bCited"]);
  });

  it("passes verified / attested / unverifiable, and an absent status", () => {
    expect(
      citedBlockers([
        { name: "a", check_status: "cited-verified" },
        { name: "b", check_status: "cited-verified-attested" },
        { name: "c", check_status: "cited-unverifiable" },
        { name: "d" },
      ]),
    ).toEqual([]);
  });

  it("is empty on an empty ledger (a run with no cited nodes banks freely)", () => {
    expect(citedBlockers([])).toEqual([]);
  });
});

describe("toAssumptionClass", () => {
  it("maps the documented tags", () => {
    expect(toAssumptionClass("faithful-refinement")).toBe("faithful-refinement");
    expect(toAssumptionClass("regularity-bookkeeping")).toBe("regularity-bookkeeping");
    expect(toAssumptionClass("substrate-gate")).toBe("substrate-gate");
  });

  it("falls back to substrate-gate (the conservative, banking-blocking class) on an unknown tag", () => {
    expect(toAssumptionClass("wat")).toBe("substrate-gate");
    expect(toAssumptionClass("")).toBe("substrate-gate");
  });
});

describe("isContentGateTag", () => {
  // The silent-cover bug: `content-gate` is the laundering tag (REJECT). The old fallback rewrote it
  // to `substrate-gate`, turning a reject into a bankable disclosure. It is now detected upstream and
  // escalated (`statement-wrong` → `fix-source`), never mapped to an AssumptionClass.
  it("detects the laundering tag, case- and whitespace-insensitively", () => {
    expect(isContentGateTag("content-gate")).toBe(true);
    expect(isContentGateTag("  Content-Gate ")).toBe(true);
    expect(isContentGateTag("content")).toBe(true);
  });

  it("does not fire on the honest classes", () => {
    expect(isContentGateTag("faithful-refinement")).toBe(false);
    expect(isContentGateTag("regularity-bookkeeping")).toBe(false);
    expect(isContentGateTag("substrate-gate")).toBe(false);
    expect(isContentGateTag("")).toBe(false);
  });
});

describe("normalizeNodes", () => {
  // plan.json's `nodes` is an OBJECT keyed by id; graph.json's is an ARRAY. Reading only the array
  // form silently returned [] for every real plan, disabling the plan half of the audit and making
  // bankEntry disagree with the `gate.ts --audit` pre-flight.
  it("reads graph.json's ARRAY form", () => {
    expect(normalizeNodes([{ id: "a", kind: "gate" }, { id: "b" }])).toEqual([
      { id: "a", kind: "gate" },
      { id: "b" },
    ]);
  });

  it("reads plan.json's OBJECT/map form, injecting the key as `id`", () => {
    const out = normalizeNodes({ envelope_segment_descent_gate: { gate: true, gate_class: "gated" } });
    expect(out).toEqual([{ id: "envelope_segment_descent_gate", gate: true, gate_class: "gated" }]);
  });

  it("returns [] for null/undefined/scalar nodes rather than throwing", () => {
    expect(normalizeNodes(undefined)).toEqual([]);
    expect(normalizeNodes(null)).toEqual([]);
    expect(normalizeNodes("nope")).toEqual([]);
  });
});
