module
public import CausalSmith.Stat.STAT_SemisupervisedDiscreteAteAnnotationFrontier_Research.Basic
public import Causalean.Stat.Minimax.SideInformation.Finite.Measurable

/-!
# The finite-coordinate bridge for the known-marginal limit

This file reparameterizes overlap laws by cell probabilities, propensities,
and outcome regressions.  In these coordinates all probabilities and the ATE
are polynomial, including at null cells.
-/

@[expose] public section

namespace CausalSmith.Stat.SemisupervisedDiscreteAteAnnotationFrontier

open MeasureTheory ProbabilityTheory Set Filter Topology
open scoped BigOperators ENNReal
open Causalean.Stat.Minimax.FiniteSideInformation
open Causalean.Experimentation.DesignBased

/-- Compact variation-independent coordinates for a finite overlap law.  [the stated conditions](hyp:d,eps) [the stated conclusion](goal). -/
abbrev KnownMarginalParam (d : Nat) (eps : Real) :=
  FinitePmf (Fin d) ×
    (Fin d → Set.Icc eps (1 - eps)) ×
    (Bool → Fin d → Set.Icc (0 : Real) 1)

/-- The observed atom probability represented by variation-independent coordinates.  [the stated conditions](hyp:theta,z) [the stated conclusion](goal). -/
def knownMarginalAtom {d : Nat} {eps : Real} (theta : KnownMarginalParam d eps)
    (z : Obs d) : Real :=
  theta.1.1 z.1 *
    (if z.2.1 then (theta.2.1 z.1 : Real) else 1 - (theta.2.1 z.1 : Real)) *
    (if z.2.2 then (theta.2.2 z.2.1 z.1 : Real)
      else 1 - (theta.2.2 z.2.1 z.1 : Real))

private lemma knownMarginalAtom_nonneg {d : Nat} {eps : Real}
    (theta : KnownMarginalParam d eps) (heps : 0 ≤ eps) (z : Obs d) :
    0 ≤ knownMarginalAtom theta z := by
  unfold knownMarginalAtom
  apply mul_nonneg (mul_nonneg (theta.1.2.1 z.1) ?_) ?_
  · split
    · exact heps.trans (theta.2.1 z.1).2.1
    · linarith [(theta.2.1 z.1).2.2]
  · split
    · exact (theta.2.2 z.2.1 z.1).2.1
    · linarith [(theta.2.2 z.2.1 z.1).2.2]
/-- [the stated conditions](hyp:heps) establishes [the stated conclusion](goal). -/

lemma knownMarginalAtom_sum {d : Nat} {eps : Real}
    (theta : KnownMarginalParam d eps) (heps : 0 ≤ eps) :
    ∑ z : Obs d, ENNReal.ofReal (knownMarginalAtom theta z) = 1 := by
  rw [← ENNReal.ofReal_sum_of_nonneg (fun z _ ↦ knownMarginalAtom_nonneg theta heps z)]
  simp only [Fintype.sum_prod_type, Fintype.sum_bool, knownMarginalAtom]
  simp
  ring_nf
  rw [theta.1.2.2]

/-- The discrete law generated by compact overlap coordinates.  [the stated conditions](hyp:theta,heps) [the stated conclusion](goal). -/
noncomputable def knownMarginalLaw {d : Nat} {eps : Real}
    (theta : KnownMarginalParam d eps) (heps : 0 ≤ eps) : DiscreteLaw d :=
  ⟨PMF.ofFintype (fun z ↦ ENNReal.ofReal (knownMarginalAtom theta z))
    (knownMarginalAtom_sum theta heps)⟩
/-- [the stated conditions](hyp:heps) establishes [the stated conclusion](goal). -/

lemma knownMarginalLaw_jointMass {d : Nat} {eps : Real}
    (theta : KnownMarginalParam d eps) (heps : 0 ≤ eps) (x : Fin d) (a y : Bool) :
    jointMass (knownMarginalLaw theta heps) x a y = knownMarginalAtom theta (x, a, y) := by
  rw [jointMass, knownMarginalLaw, PMF.ofFintype_apply,
    ENNReal.toReal_ofReal (knownMarginalAtom_nonneg theta heps _)]
/-- [the stated conditions](hyp:heps) establishes [the stated conclusion](goal). -/

lemma knownMarginalLaw_cellMass {d : Nat} {eps : Real}
    (theta : KnownMarginalParam d eps) (heps : 0 ≤ eps) (x : Fin d) :
    cellMass (knownMarginalLaw theta heps) x = theta.1.1 x := by
  simp [cellMass, knownMarginalLaw_jointMass, knownMarginalAtom, Fintype.sum_bool]
  ring
/-- [the stated conditions](hyp:heps) establishes [the stated conclusion](goal). -/

lemma knownMarginalLaw_armMass {d : Nat} {eps : Real}
    (theta : KnownMarginalParam d eps) (heps : 0 ≤ eps) (x : Fin d) (a : Bool) :
    armMass (knownMarginalLaw theta heps) x a =
      theta.1.1 x * (if a then (theta.2.1 x : Real)
        else 1 - (theta.2.1 x : Real)) := by
  simp [armMass, knownMarginalLaw_jointMass, knownMarginalAtom, Fintype.sum_bool]
  cases a <;> simp <;> ring
/-- [the stated conditions](hyp:hcell,heps) establishes [the stated conclusion](goal). -/

lemma knownMarginalLaw_outcomeMean_of_pos {d : Nat} {eps : Real}
    (theta : KnownMarginalParam d eps) (x : Fin d) (a : Bool)
    (hcell : 0 < theta.1.1 x) (heps : 0 < eps) :
    outcomeMean (knownMarginalLaw theta heps.le) a x = theta.2.2 a x := by
  have he : 0 < (if a then (theta.2.1 x : Real) else 1 - theta.2.1 x) := by
    split_ifs
    · exact heps.trans_le (theta.2.1 x).2.1
    · linarith [(theta.2.1 x).2.2]
  have hne : theta.1.1 x ≠ 0 := ne_of_gt hcell
  rw [outcomeMean, knownMarginalLaw_armMass, knownMarginalLaw_jointMass,
    knownMarginalAtom]
  cases a
  · simp at he ⊢
    exact mul_div_cancel_left₀ _
      (mul_ne_zero hne (sub_ne_zero.mpr (ne_of_gt he)))
  · simp at he ⊢
    exact mul_div_cancel_left₀ _ (mul_ne_zero hne (ne_of_gt he))
/-- [the stated conditions](hyp:heps) establishes [the stated conclusion](goal). -/

lemma knownMarginalLaw_ate {d : Nat} {eps : Real}
    (theta : KnownMarginalParam d eps) (heps : 0 < eps) :
    ateFunctional (knownMarginalLaw theta heps.le) =
      ∑ x, theta.1.1 x * ((theta.2.2 true x : Real) - theta.2.2 false x) := by
  rw [ateFunctional]
  apply Finset.sum_congr rfl
  intro x _
  rw [knownMarginalLaw_cellMass]
  by_cases hx : theta.1.1 x = 0
  · simp [hx]
  · have hxpos : 0 < theta.1.1 x := lt_of_le_of_ne (theta.1.2.1 x) (Ne.symm hx)
    rw [knownMarginalLaw_outcomeMean_of_pos theta x true hxpos heps,
      knownMarginalLaw_outcomeMean_of_pos theta x false hxpos heps]

/-- Compact coordinates generate a member of the paper's overlap class.  [the stated conditions](hyp:hd,heps,heps2,theta) [the stated conclusion](goal). -/
noncomputable def knownMarginalParamToClass {d : Nat} {eps : Real}
    (hd : 2 ≤ d) (heps : 0 < eps) (heps2 : eps < 1 / 2)
    (theta : KnownMarginalParam d eps) : ClassLaw d eps := by
  refine ⟨knownMarginalLaw theta heps.le, hd, heps, heps2, ?_⟩
  intro x hx
  rw [propensity, knownMarginalLaw_armMass, knownMarginalLaw_cellMass]
  have hne : theta.1.1 x ≠ 0 := ne_of_gt (by simpa [knownMarginalLaw_cellMass] using hx)
  rw [mul_div_cancel_left₀ _ hne]
  exact (theta.2.1 x).2

private lemma cellMass_sum_eq_one_local {d : Nat} (P : DiscreteLaw d) :
    ∑ x, cellMass P x = 1 := by
  have h := PMF.integral_eq_sum P.pmf (fun _ : Obs d ↦ (1 : Real))
  simpa [cellMass, jointMass, Fintype.sum_prod_type] using h.symm

/-- Every overlap law is represented by the compact variation-independent coordinates.  [the stated conditions](hyp:hd,heps,heps2) [the stated conclusion](goal). -/
theorem knownMarginalParamToClass_surjective {d : Nat} {eps : Real}
    (hd : 2 ≤ d) (heps : 0 < eps) (heps2 : eps < 1 / 2) :
    Function.Surjective (knownMarginalParamToClass hd heps heps2) := by
  classical
  intro P
  let p : FinitePmf (Fin d) :=
    ⟨fun x ↦ cellMass P.1 x,
      ⟨fun x ↦ (cellMass_mem_unitInterval P.1 x).1, cellMass_sum_eq_one_local P.1⟩⟩
  let e : Fin d → Set.Icc eps (1 - eps) := fun x ↦
    if hx : cellMass P.1 x = 0 then ⟨eps, le_rfl, by linarith⟩
    else ⟨propensity P.1 x, P.2.overlap x
      (lt_of_le_of_ne (cellMass_mem_unitInterval P.1 x).1 (Ne.symm hx))⟩
  let mu : Bool → Fin d → Set.Icc (0 : Real) 1 :=
    fun a x ↦ ⟨outcomeMean P.1 a x, outcomeMean_mem_unitInterval P.1 a x⟩
  let theta : KnownMarginalParam d eps := (p, e, mu)
  refine ⟨theta, Subtype.ext ?_⟩
  cases P with
  | mk law hP =>
   cases law with
   | mk P =>
    dsimp only at *
    change DiscreteLaw.mk _ = DiscreteLaw.mk P
    congr 1
    apply PMF.ext
    intro z
    apply (ENNReal.toReal_eq_toReal_iff' (PMF.apply_ne_top _ _)
      (PMF.apply_ne_top _ _)).mp
    rw [PMF.ofFintype_apply,
      ENNReal.toReal_ofReal (knownMarginalAtom_nonneg theta heps.le z)]
    change knownMarginalAtom theta z = jointMass ⟨P⟩ z.1 z.2.1 z.2.2
    rcases z with ⟨x, a, y⟩
    by_cases hx : cellMass ⟨P⟩ x = 0
    · have h00 : 0 ≤ jointMass ⟨P⟩ x false false :=
        (jointMass_mem_unitInterval ⟨P⟩ x false false).1
      have h01 : 0 ≤ jointMass ⟨P⟩ x false true :=
        (jointMass_mem_unitInterval ⟨P⟩ x false true).1
      have h10 : 0 ≤ jointMass ⟨P⟩ x true false :=
        (jointMass_mem_unitInterval ⟨P⟩ x true false).1
      have h11 : 0 ≤ jointMass ⟨P⟩ x true true :=
        (jointMass_mem_unitInterval ⟨P⟩ x true true).1
      have hz : jointMass ⟨P⟩ x a y = 0 := by
        simp only [cellMass, Fintype.sum_bool] at hx
        cases a <;> cases y <;> nlinarith
      simp [knownMarginalAtom, theta, p, hx, hz]
    · have hxpos : 0 < cellMass ⟨P⟩ x :=
        lt_of_le_of_ne (cellMass_mem_unitInterval ⟨P⟩ x).1 (Ne.symm hx)
      have hov := hP.overlap x hxpos
      have htpos : 0 < armMass ⟨P⟩ x true := by
        have := lt_of_lt_of_le heps hov.1
        rw [propensity] at this
        rcases div_pos_iff.mp this with h | h
        · exact h.1
        · linarith
      have hfpos : 0 < armMass ⟨P⟩ x false := by
        have hdecomp : cellMass ⟨P⟩ x =
            armMass ⟨P⟩ x false + armMass ⟨P⟩ x true := by
          simp [cellMass, armMass, Fintype.sum_bool]
          ring
        have hlt : propensity ⟨P⟩ x < 1 := lt_of_le_of_lt hov.2 (by linarith)
        rw [propensity, div_lt_one hxpos] at hlt
        linarith
      have heval : (e x : Real) = propensity ⟨P⟩ x := by
        simp [e, hx]
      cases a <;> cases y <;>
        simp only [knownMarginalAtom, theta, p, mu, Prod.fst, Prod.snd,
          Bool.false_eq_true, Bool.true_eq, if_false, if_true, Subtype.coe_mk] <;>
        rw [heval] <;>
        simp only [propensity, outcomeMean] <;>
        field_simp [ne_of_gt hxpos, ne_of_gt htpos, ne_of_gt hfpos] <;>
        simp [armMass, cellMass, Fintype.sum_bool] <;> ring

/-- The simplex of complete-record atom probabilities in compact coordinates.  [the stated conditions](hyp:theta,heps) [the stated conclusion](goal). -/
def knownMarginalObsPmf {d : Nat} {eps : Real}
    (theta : KnownMarginalParam d eps) (heps : 0 ≤ eps) : FinitePmf (Obs d) :=
  ⟨knownMarginalAtom theta, by
    constructor
    · exact fun z ↦ knownMarginalAtom_nonneg theta heps z
    · simp only [Fintype.sum_prod_type, Fintype.sum_bool, knownMarginalAtom]
      simp
      ring_nf
      exact theta.1.2.2⟩

/-- Labeled-sample atom probabilities in compact coordinates.  [the stated conditions](hyp:theta,heps,sample) [the stated conclusion](goal). -/
def knownMarginalLabelProb {n d : Nat} {eps : Real}
    (theta : KnownMarginalParam d eps) (heps : 0 ≤ eps)
    (sample : Fin n → Obs d) : Real :=
  productProbability (Obs d) (knownMarginalObsPmf theta heps) sample

/-- Auxiliary atom probabilities in compact coordinates.  [the stated conditions](hyp:theta,z) [the stated conclusion](goal). -/
def knownMarginalAuxProb {d : Nat} {eps : Real}
    (theta : KnownMarginalParam d eps) (z : AuxObs d) : Real :=
  ∑ y : Bool, knownMarginalAtom theta (z.1, z.2, y)

/-- The ATE coordinate, polynomial even at null covariate cells.  [the stated conditions](hyp:theta) [the stated conclusion](goal). -/
def knownMarginalTarget {d : Nat} {eps : Real}
    (theta : KnownMarginalParam d eps) : Real :=
  ∑ x, theta.1.1 x * ((theta.2.2 true x : Real) - theta.2.2 false x)
/-- [the stated conditions](hyp:heps) establishes [the stated conclusion](goal). -/

lemma knownMarginalLabelProb_simplex {n d : Nat} {eps : Real}
    (theta : KnownMarginalParam d eps) (heps : 0 ≤ eps) :
    knownMarginalLabelProb theta heps ∈ stdSimplex Real (Fin n → Obs d) := by
  exact ⟨fun z ↦ productProbability_nonneg _ _ _, sum_productProbability _ _⟩
/-- [the stated conditions](hyp:heps) establishes [the stated conclusion](goal). -/

lemma knownMarginalAuxProb_simplex {d : Nat} {eps : Real}
    (theta : KnownMarginalParam d eps) (heps : 0 ≤ eps) :
    knownMarginalAuxProb theta ∈ stdSimplex Real (AuxObs d) := by
  constructor
  · intro z
    exact Finset.sum_nonneg fun y _ ↦ knownMarginalAtom_nonneg theta heps _
  · simp only [knownMarginalAuxProb, Fintype.sum_prod_type, Fintype.sum_bool,
      knownMarginalAtom]
    simp
    ring_nf
    exact theta.1.2.2

private lemma continuous_knownMarginalAtom {d : Nat} {eps : Real} (z : Obs d) :
    Continuous (fun theta : KnownMarginalParam d eps ↦ knownMarginalAtom theta z) := by
  rcases z with ⟨x, a, y⟩
  have hp : Continuous (fun theta : KnownMarginalParam d eps ↦ (theta.1.1 x : Real)) :=
    (continuous_apply x).comp (continuous_subtype_val.comp continuous_fst)
  have he : Continuous (fun theta : KnownMarginalParam d eps ↦ (theta.2.1 x : Real)) :=
    continuous_subtype_val.comp
      ((continuous_apply x).comp (continuous_fst.comp continuous_snd))
  have hmu (a : Bool) :
      Continuous (fun theta : KnownMarginalParam d eps ↦ (theta.2.2 a x : Real)) :=
    continuous_subtype_val.comp ((continuous_apply x).comp
      ((continuous_apply a).comp (continuous_snd.comp continuous_snd)))
  cases a <;> cases y <;> simp [knownMarginalAtom]
  · exact (hp.mul (continuous_const.sub he)).mul (continuous_const.sub (hmu false))
  · exact (hp.mul (continuous_const.sub he)).mul (hmu false)
  · exact (hp.mul he).mul (continuous_const.sub (hmu true))
  · exact (hp.mul he).mul (hmu true)
/-- [the stated conditions](hyp:heps) establishes [the stated conclusion](goal). -/

lemma continuous_knownMarginalLabelProb {n d : Nat} {eps : Real} (heps : 0 ≤ eps)
    (sample : Fin n → Obs d) :
    Continuous (fun theta : KnownMarginalParam d eps ↦
      knownMarginalLabelProb theta heps sample) := by
  unfold knownMarginalLabelProb productProbability knownMarginalObsPmf
  apply continuous_finsetProd
  intro i _
  exact continuous_knownMarginalAtom (sample i)
/-- The formal statement establishes [the stated conclusion](goal). -/

lemma continuous_knownMarginalAuxProb {d : Nat} {eps : Real} (z : AuxObs d) :
    Continuous (fun theta : KnownMarginalParam d eps ↦ knownMarginalAuxProb theta z) := by
  unfold knownMarginalAuxProb knownMarginalAtom
  apply continuous_finsetSum
  intro y _
  exact continuous_knownMarginalAtom _
/-- The formal statement establishes [the stated conclusion](goal). -/

lemma continuous_knownMarginalTarget {d : Nat} {eps : Real} :
    Continuous (knownMarginalTarget : KnownMarginalParam d eps → Real) := by
  unfold knownMarginalTarget
  apply continuous_finsetSum
  intro x _
  have hp : Continuous (fun theta : KnownMarginalParam d eps ↦ (theta.1.1 x : Real)) :=
    (continuous_apply x).comp (continuous_subtype_val.comp continuous_fst)
  have hmu (a : Bool) :
      Continuous (fun theta : KnownMarginalParam d eps ↦ (theta.2.2 a x : Real)) :=
    continuous_subtype_val.comp ((continuous_apply x).comp
      ((continuous_apply a).comp (continuous_snd.comp continuous_snd)))
  exact hp.mul ((hmu true).sub (hmu false))
/-- The formal statement establishes [the stated conclusion](goal). -/

lemma knownMarginalTarget_mem {d : Nat} {eps : Real}
    (theta : KnownMarginalParam d eps) : knownMarginalTarget theta ∈ Set.Icc (-1 : Real) 1 := by
  have hp := theta.1.2
  constructor
  · calc
      (-1 : Real) = ∑ x, theta.1.1 x * (-1) := by rw [← Finset.sum_mul, hp.2]; ring
      _ ≤ knownMarginalTarget theta := by
        apply Finset.sum_le_sum
        intro x _
        apply mul_le_mul_of_nonneg_left _ (hp.1 x)
        rcases (theta.2.2 true x).2 with ⟨h1lo, h1hi⟩
        rcases (theta.2.2 false x).2 with ⟨h0lo, h0hi⟩
        linarith
  · calc
      knownMarginalTarget theta ≤ ∑ x, theta.1.1 x * 1 := by
        apply Finset.sum_le_sum
        intro x _
        apply mul_le_mul_of_nonneg_left _ (hp.1 x)
        rcases (theta.2.2 true x).2 with ⟨h1lo, h1hi⟩
        rcases (theta.2.2 false x).2 with ⟨h0lo, h0hi⟩
        linarith
      _ = 1 := by rw [← Finset.sum_mul, hp.2]; ring

/-- The generic finite-side-information values converge on the compact paper coordinates.  [the stated conditions](hyp:heps,heps2,hd) [the stated conclusion](goal). -/
theorem knownMarginalGeneric_tendsto {eps : Real} (heps : 0 < eps) (heps2 : eps < 1 / 2)
    (n d : Nat) (hd : 2 ≤ d) :
    Tendsto (fun m : Nat ↦ empiricalSideMinimaxValue
        (fun theta : KnownMarginalParam d eps ↦
          knownMarginalLabelProb (n := n) theta heps.le)
        (knownMarginalAuxProb (d := d))
        (fun theta : KnownMarginalParam d eps ↦ knownMarginalAuxProb_simplex theta heps.le)
        (knownMarginalTarget (d := d)) (-1) 1 m) atTop
      (nhds (exactSideMinimaxValue
        (fun theta : KnownMarginalParam d eps ↦
          knownMarginalLabelProb (n := n) theta heps.le)
        (knownMarginalAuxProb (d := d))
        (fun theta : KnownMarginalParam d eps ↦ knownMarginalAuxProb_simplex theta heps.le)
        (knownMarginalTarget (d := d)) (-1) 1)) := by
  letI : Nonempty (Fin d) := Fin.pos_iff_nonempty.mp (lt_of_lt_of_le (by omega) hd)
  letI : Nonempty (Set.Icc eps (1 - eps)) :=
    ⟨⟨eps, le_rfl, by linarith⟩⟩
  letI : Nonempty (KnownMarginalParam d eps) := inferInstance
  apply finiteSideInfo_minimax_tendsto
    (fun theta : KnownMarginalParam d eps ↦ knownMarginalLabelProb (n := n) theta heps.le)
    (knownMarginalAuxProb (d := d)) (knownMarginalTarget (d := d))
    (fun theta ↦ knownMarginalLabelProb_simplex theta heps.le)
    (fun theta ↦ knownMarginalAuxProb_simplex theta heps.le)
    (continuous_knownMarginalLabelProb heps.le)
    continuous_knownMarginalAuxProb continuous_knownMarginalTarget
    (by norm_num)
    knownMarginalTarget_mem
/-- [the stated conditions](hyp:heps) establishes [the stated conclusion](goal). -/

lemma finitePmfMeasure_knownMarginalObsPmf {d : Nat} {eps : Real}
    (theta : KnownMarginalParam d eps) (heps : 0 ≤ eps) :
    finitePmfMeasure (knownMarginalObsPmf theta heps) =
      obsLaw (knownMarginalLaw theta heps) := by
  apply Measure.ext_of_singleton
  intro z
  unfold finitePmfMeasure obsLaw
  rw [FiniteDesign.toMeasure_apply]
  simp [finitePmfMeasure, finitePmfDesign, knownMarginalObsPmf,
    knownMarginalLaw, PMF.toMeasure_apply_singleton,
    knownMarginalAtom_nonneg theta heps]
  rw [Finset.sum_eq_single z]
  · simp
  · intro z' _ hz'
    simp [Pi.single_apply, Ne.symm hz']
  · intro hz
    simp at hz
/-- [the stated conditions](hyp:heps) establishes [the stated conclusion](goal). -/

lemma knownMarginalAuxProb_eq_table {d : Nat} {eps : Real}
    (theta : KnownMarginalParam d eps) (heps : 0 ≤ eps) :
    knownMarginalAuxProb theta = auxTableOf (knownMarginalLaw theta heps) := by
  funext z
  simp [knownMarginalAuxProb, auxTableOf, armMass, knownMarginalLaw_jointMass]
/-- [the stated conditions](hyp:heps) establishes [the stated conclusion](goal). -/

lemma knownMarginalTarget_eq_ate {d : Nat} {eps : Real}
    (theta : KnownMarginalParam d eps) (heps : 0 < eps) :
    knownMarginalTarget theta = ateFunctional (knownMarginalLaw theta heps.le) := by
  exact (knownMarginalLaw_ate theta heps).symm

/-- Bounded measurable estimators on the paper's known-table sample space are
equivalent to the promoted measurable ambient exact-table procedures.  [the stated conditions](hyp:n,d) [the stated conclusion](goal). -/
noncomputable def knownEstimatorEquivAmbient (n d : Nat) :
    {f : KnownSample n d → Real //
        Measurable f ∧ ∀ z, f z ∈ Set.Icc (-1 : Real) 1} ≃
      MeasurableAmbientExactSideProcedure (Fin n → Obs d) (AuxObs d) (-1) 1 where
  toFun est := ⟨fun x w ↦ ⟨est.1 (x, w), est.2.2 (x, w)⟩,
    by
      intro x
      apply Measurable.subtype_mk
      exact est.2.1.comp (measurable_const.prodMk measurable_id)⟩
  invFun proc := ⟨fun z ↦ proc.1 z.1 z.2,
    (measurable_uncurry_of_continuous_of_measurable
      (fun w ↦ continuous_of_discreteTopology) proc.2).subtype_val,
    fun z ↦ (proc.1 z.1 z.2).2⟩
  left_inv est := by ext z; rfl
  right_inv proc := by ext x w; rfl
/-- [the stated conditions](hyp:heps) establishes [the stated conclusion](goal). -/

lemma knownMarginal_integral_eq_tableRisk {n d : Nat} {eps : Real}
    (theta : KnownMarginalParam d eps) (heps : 0 < eps)
    (proc : MeasurableAmbientExactSideProcedure
      (Fin n → Obs d) (AuxObs d) (-1) 1) :
    (∫ x, ((proc.1 x (auxTableOf (knownMarginalLaw theta heps.le)) : Real) -
          ateFunctional (knownMarginalLaw theta heps.le)) ^ 2
        ∂(labeledProductLaw (knownMarginalLaw theta heps.le) n)) =
      measurableExactTableRisk
        (fun theta : KnownMarginalParam d eps ↦
          knownMarginalLabelProb (n := n) theta heps.le)
        (knownMarginalAuxProb (d := d)) (knownMarginalTarget (d := d)) proc theta := by
  rw [labeledProductLaw, ← finitePmfMeasure_knownMarginalObsPmf theta heps.le,
    integral_pi_finitePmfMeasure_eq_sum_productProbability]
  unfold measurableExactTableRisk knownMarginalLabelProb
  rw [knownMarginalAuxProb_eq_table theta heps.le,
    knownMarginalTarget_eq_ate theta heps]

/-- The paper's known-marginal minimax risk is exactly the promoted measurable
ambient exact-table value in compact coordinates.  [the stated conditions](hyp:heps,heps2,hd) [the stated conclusion](goal). -/
theorem knownMarginalRisk_eq_measurableValue {eps : Real}
    (heps : 0 < eps) (heps2 : eps < 1 / 2) (n d : Nat) (hd : 2 ≤ d) :
    knownMarginalRisk n d eps = measurableExactTableMinimaxValue
      (fun theta : KnownMarginalParam d eps ↦
        knownMarginalLabelProb (n := n) theta heps.le)
      (knownMarginalAuxProb (d := d)) (knownMarginalTarget (d := d)) (-1) 1 := by
  let paperRisk := fun
      (est : {f : KnownSample n d → Real //
        Measurable f ∧ ∀ z, f z ∈ Set.Icc (-1 : Real) 1})
      (P : ClassLaw d eps) ↦
        ∫ x, (est.1 (x, auxTableOf P.1) - ateFunctional P.1) ^ 2
          ∂(labeledProductLaw P.1 n)
  let phi := knownMarginalParamToClass hd heps heps2
  have hsurj : Function.Surjective phi :=
    knownMarginalParamToClass_surjective hd heps heps2
  rw [show knownMarginalRisk n d eps = Causalean.Stat.minimaxValueReal paperRisk by
    rfl]
  rw [← Causalean.Stat.Minimax.FiniteSideInformation.minimaxValueReal_comp_surjective
    paperRisk phi hsurj]
  unfold Causalean.Stat.minimaxValueReal
  rw [← (knownEstimatorEquivAmbient n d).symm.iInf_comp]
  apply iInf_congr
  intro proc
  unfold Causalean.Stat.worstCaseRiskReal
  congr 1
  funext theta
  change (∫ x, ((proc.1 x (auxTableOf (knownMarginalLaw theta heps.le)) : Real) -
      ateFunctional (knownMarginalLaw theta heps.le)) ^ 2
      ∂(labeledProductLaw (knownMarginalLaw theta heps.le) n)) = _
  exact knownMarginal_integral_eq_tableRisk theta heps proc

private lemma auxMarginal_toReal {d : Nat} (P : DiscreteLaw d) (z : AuxObs d) :
    (auxMarginal P z).toReal = auxTableOf P z := by
  unfold auxMarginal auxTableOf armMass jointMass
  rw [PMF.map_apply, tsum_fintype]
  rcases z with ⟨x, a⟩
  cases a <;> simp only [Fintype.sum_prod_type] <;> simp
  all_goals
    rw [ENNReal.toReal_add (PMF.apply_ne_top _ _) (PMF.apply_ne_top _ _)]
/-- [the stated conditions](hyp:heps) establishes [the stated conclusion](goal). -/

lemma finitePmfMeasure_knownMarginalAuxPmf {d : Nat} {eps : Real}
    (theta : KnownMarginalParam d eps) (heps : 0 ≤ eps) :
    finitePmfMeasure
        ⟨knownMarginalAuxProb theta, knownMarginalAuxProb_simplex theta heps⟩ =
      (auxMarginal (knownMarginalLaw theta heps)).toMeasure := by
  apply Measure.ext_of_singleton
  intro z
  unfold finitePmfMeasure
  rw [FiniteDesign.toMeasure_apply, PMF.toMeasure_apply_singleton]
  simp only [finitePmfDesign, FiniteDesign.p, Measure.dirac_apply'
    _ (MeasurableSet.singleton _), if_pos]
  rw [Finset.sum_eq_single z]
  · rw [Set.indicator_of_mem (Set.mem_singleton z)]
    simp only [Pi.one_apply, mul_one]
    apply (ENNReal.toReal_eq_toReal_iff' (ENNReal.ofReal_ne_top)
      (PMF.apply_ne_top _ _)).mp
    rw [ENNReal.toReal_ofReal ((knownMarginalAuxProb_simplex theta heps).1 z),
      auxMarginal_toReal, knownMarginalAuxProb_eq_table theta heps]
  · intro z' _ hz'
    simp [Pi.single_apply, Ne.symm hz']
  · intro hz
    simp at hz
  · exact MeasurableSet.singleton z
/-- [the stated conditions](hyp:heps) establishes [the stated conclusion](goal). -/

lemma twoSampleMSE_eq_empiricalSideRisk {n m d : Nat} {eps : Real}
    (theta : KnownMarginalParam d eps) (heps : 0 < eps)
    (est : EmpiricalSideProcedure (Fin n → Obs d) (AuxObs d) m (-1) 1) :
    twoSampleMSE (annotationLaw (knownMarginalLaw theta heps.le) n m)
        (fun z ↦ (est z.1 z.2 : Real))
        (ateFunctional (knownMarginalLaw theta heps.le)) =
      empiricalSideRisk
        (fun theta : KnownMarginalParam d eps ↦
          knownMarginalLabelProb (n := n) theta heps.le)
        (knownMarginalAuxProb (d := d))
        (fun theta : KnownMarginalParam d eps ↦ knownMarginalAuxProb_simplex theta heps.le)
        (knownMarginalTarget (d := d)) m est theta := by
  letI : IsProbabilityMeasure (labeledProductLaw (knownMarginalLaw theta heps.le) n) := by
    unfold labeledProductLaw
    infer_instance
  letI : IsProbabilityMeasure (auxProductLaw (knownMarginalLaw theta heps.le) m) := by
    unfold auxProductLaw
    infer_instance
  unfold twoSampleMSE annotationLaw
  rw [MeasureTheory.integral_prod _ Integrable.of_finite]
  unfold labeledProductLaw auxProductLaw
  rw [← finitePmfMeasure_knownMarginalObsPmf theta heps.le,
    ← finitePmfMeasure_knownMarginalAuxPmf theta heps.le]
  simp_rw [integral_pi_finitePmfMeasure_eq_sum_productProbability]
  unfold empiricalSideRisk knownMarginalLabelProb
  rw [knownMarginalTarget_eq_ate theta heps]
  rfl

private noncomputable def paperEstimatorOfEmpirical {n m d : Nat}
    (est : EmpiricalSideProcedure (Fin n → Obs d) (AuxObs d) m (-1) 1) :
    {f : Sample n m d → Real // Measurable f} :=
  ⟨fun z ↦ est z.1 z.2, measurable_of_finite _⟩

private noncomputable def clippedEmpiricalOfPaper {n m d : Nat}
    (est : {f : Sample n m d → Real // Measurable f}) :
    EmpiricalSideProcedure (Fin n → Obs d) (AuxObs d) m (-1) 1 :=
  fun x z ↦ ⟨clipAte (est.1 (x, z)), by
    exact (Set.projIcc (-1 : Real) 1 (by norm_num) (est.1 (x, z))).property⟩

private lemma clippedEmpirical_sq_le {n m d : Nat}
    (est : {f : Sample n m d → Real // Measurable f}) (z : Sample n m d)
    (target : Real) (htarget : target ∈ Set.Icc (-1 : Real) 1) :
    (((clippedEmpiricalOfPaper est z.1 z.2 : Set.Icc (-1 : Real) 1) : Real) - target) ^ 2 ≤
      (est.1 z - target) ^ 2 := by
  have habs : |clipAte (est.1 z) - target| ≤ |est.1 z - target| := by
    simpa [clipAte, Set.coe_projIcc,
      Set.projIcc_of_mem (by norm_num : (-1 : Real) ≤ 1) htarget] using
      (Set.abs_projIcc_sub_projIcc (a := (-1 : Real)) (b := 1)
        (c := est.1 z) (d := target) (by norm_num))
  exact sq_le_sq.mpr habs

/-- The paper's two-sample minimax risk is exactly the generic empirical-side
minimax value in compact coordinates.  [the stated conditions](hyp:heps,heps2,hd) [the stated conclusion](goal). -/
theorem minimaxRisk_eq_empiricalValue {eps : Real}
    (heps : 0 < eps) (heps2 : eps < 1 / 2) (n m d : Nat) (hd : 2 ≤ d) :
    minimaxRisk n m d eps = empiricalSideMinimaxValue
      (fun theta : KnownMarginalParam d eps ↦
        knownMarginalLabelProb (n := n) theta heps.le)
      (knownMarginalAuxProb (d := d))
      (fun theta : KnownMarginalParam d eps ↦ knownMarginalAuxProb_simplex theta heps.le)
      (knownMarginalTarget (d := d)) (-1) 1 m := by
  letI : Nonempty (Fin d) := Fin.pos_iff_nonempty.mp (lt_of_lt_of_le (by omega) hd)
  letI : Nonempty (Set.Icc eps (1 - eps)) := ⟨⟨eps, le_rfl, by linarith⟩⟩
  letI : Nonempty (KnownMarginalParam d eps) := inferInstance
  letI : Nonempty (EmpiricalSideProcedure
      (Fin n → Obs d) (AuxObs d) m (-1) 1) :=
    ⟨fun _ _ ↦ ⟨0, by norm_num⟩⟩
  let paperRisk := fun (est : {f : Sample n m d → Real // Measurable f})
      (P : ClassLaw d eps) ↦
    twoSampleMSE (annotationLaw P.1 n m) est.1 (ateFunctional P.1)
  let paramRisk := fun (est : {f : Sample n m d → Real // Measurable f})
      (theta : KnownMarginalParam d eps) ↦
    paperRisk est (knownMarginalParamToClass hd heps heps2 theta)
  let genericRisk : EmpiricalSideProcedure (Fin n → Obs d) (AuxObs d) m (-1) 1 →
      KnownMarginalParam d eps → Real := empiricalSideRisk
      (fun theta : KnownMarginalParam d eps ↦
        knownMarginalLabelProb (n := n) theta heps.le)
      (knownMarginalAuxProb (d := d))
      (fun theta : KnownMarginalParam d eps ↦ knownMarginalAuxProb_simplex theta heps.le)
      (knownMarginalTarget (d := d)) m
  have hsurj := knownMarginalParamToClass_surjective hd heps heps2
  rw [show minimaxRisk n m d eps = Causalean.Stat.minimaxValueReal paperRisk by rfl]
  rw [← minimaxValueReal_comp_surjective paperRisk
    (knownMarginalParamToClass hd heps heps2) hsurj]
  change Causalean.Stat.minimaxValueReal paramRisk = Causalean.Stat.minimaxValueReal genericRisk
  apply le_antisymm
  · apply Causalean.Stat.minimaxValue_le_minimaxValue
      (Causalean.Stat.bddBelow_range_worstCaseRisk (fun est theta ↦
        integral_nonneg fun z ↦ sq_nonneg _))
    intro est
    refine ⟨paperEstimatorOfEmpirical est, ?_⟩
    unfold Causalean.Stat.worstCaseRiskReal
    apply le_of_eq
    congr 1
    funext theta
    exact twoSampleMSE_eq_empiricalSideRisk theta heps est
  · letI : Nonempty {f : Sample n m d → Real // Measurable f} :=
      ⟨⟨fun _ ↦ 0, measurable_const⟩⟩
    apply Causalean.Stat.minimaxValue_le_minimaxValue
      (Causalean.Stat.bddBelow_range_worstCaseRisk (fun est theta ↦
        empiricalSideRisk_nonneg _ _
          (fun theta ↦ knownMarginalLabelProb_simplex theta heps.le)
          (fun theta ↦ knownMarginalAuxProb_simplex theta heps.le) _ _ _ _))
    intro est
    refine ⟨clippedEmpiricalOfPaper est, ?_⟩
    apply Causalean.Stat.worstCaseRisk_le
    intro theta
    rw [← twoSampleMSE_eq_empiricalSideRisk theta heps]
    letI : IsProbabilityMeasure
        (annotationLaw (knownMarginalLaw theta heps.le) n m) := by
      unfold annotationLaw labeledProductLaw auxProductLaw
      infer_instance
    have hclip : twoSampleMSE
        (annotationLaw (knownMarginalLaw theta heps.le) n m)
        (fun z ↦ (clippedEmpiricalOfPaper est z.1 z.2 : Real))
        (ateFunctional (knownMarginalLaw theta heps.le)) ≤
        paramRisk est theta := by
      apply integral_mono_ae Integrable.of_finite Integrable.of_finite
      exact ae_of_all _ fun z ↦ clippedEmpirical_sq_le est z _
        (ateFunctional_mem_Icc_neg_one_one _
          (knownMarginalParamToClass hd heps heps2 theta).2.overlap)
    refine hclip.trans (Causalean.Stat.le_worstCaseRisk ?_ theta)
    let B : Real := ∑ z : Sample n m d, (|est.1 z| + 1) ^ 2
    refine ⟨B, ?_⟩
    rintro _ ⟨theta', rfl⟩
    letI : IsProbabilityMeasure
        (annotationLaw (knownMarginalLaw theta' heps.le) n m) := by
      unfold annotationLaw labeledProductLaw auxProductLaw
      infer_instance
    change twoSampleMSE (annotationLaw (knownMarginalLaw theta' heps.le) n m)
      est.1 (ateFunctional (knownMarginalLaw theta' heps.le)) ≤ B
    calc
      twoSampleMSE (annotationLaw (knownMarginalLaw theta' heps.le) n m)
          est.1 (ateFunctional (knownMarginalLaw theta' heps.le)) ≤
          ∫ _z, B ∂(annotationLaw
          (knownMarginalLaw theta' heps.le) n m) := by
        unfold twoSampleMSE
        apply integral_mono_ae Integrable.of_finite Integrable.of_finite
        exact ae_of_all _ fun z ↦ by
          have ht := ateFunctional_mem_Icc_neg_one_one _
            (knownMarginalParamToClass hd heps heps2 theta').2.overlap
          have habs : |ateFunctional (knownMarginalLaw theta' heps.le)| ≤ 1 :=
            abs_le.mpr ht
          have hs : (est.1 z - ateFunctional (knownMarginalLaw theta' heps.le)) ^ 2 ≤
              (|est.1 z| + 1) ^ 2 := by
            apply sq_le_sq.mpr
            have htri : |est.1 z - ateFunctional (knownMarginalLaw theta' heps.le)| ≤
                |est.1 z| + |ateFunctional (knownMarginalLaw theta' heps.le)| := by
              simpa using abs_sub_le (est.1 z) 0
                (ateFunctional (knownMarginalLaw theta' heps.le))
            refine htri.trans ?_
            simpa [abs_of_nonneg (by positivity : 0 ≤ |est.1 z| + 1)] using
              (add_le_add_left habs |est.1 z|)
          exact hs.trans (Finset.single_le_sum
            (fun w _ ↦ sq_nonneg (|est.1 w| + 1)) (Finset.mem_univ z))
      _ = B := by simp

end CausalSmith.Stat.SemisupervisedDiscreteAteAnnotationFrontier
