module
public import CausalSmith.Stat.STAT_DiscreteAteHeterogeneityFrontier_Research.Helpers.RadialMembership
public import CausalSmith.Stat.STAT_DiscreteAteHeterogeneityFrontier_Research.Helpers.ConcreteExactHandle

/-!
# Concrete radial-family handle facts

This module identifies the observed experiment generated by the padded
Bernoulli contraction and records the mass identities needed by the concrete
least-favorable handle.
-/

public section

namespace CausalSmith.Stat.DiscreteAteHeterogeneityFrontier

open MeasureTheory ProbabilityTheory Set
open scoped ProbabilityTheory ENNReal NNReal

-- @node: radialPaddedAffine_observedLaw
/-- If [the source alphabet embeds in the target alphabet](hyp:hmd) and [the heterogeneity radius
  is nonnegative](hyp:hs0) and [the heterogeneity radius is at most two](hyp:hs2), [padding,
  Bernoulli contraction, and affine outcome scaling agree exactly with applying the common
  observed-data Markov kernel to the source law](goal). -/
lemma radialPaddedAffine_observedLaw {m d : ℕ} (hmd : m ≤ d) (M sigma : ℝ)
    (hs0 : 0 ≤ sigma) (hs2 : sigma ≤ 2) (P : BinLaw m) :
    (affineBinaryRealLaw M
      (binaryPadLaw hmd (radialContractedBinaryLaw P sigma hs0 hs2))).observedLaw =
      bernoulliContractionObservedKernel
        (fun k : Fin m => ⟨k, lt_of_lt_of_le k.isLt hmd⟩) M sigma ∘ₘ
        CausalSmith.Stat.DiscreteAteMinimaxLoggap.obsLaw P := by
  rw [(affineBinaryRealLaw_embedding M _).1, binaryPadLaw_obsLaw]
  ext E hE
  rw [Measure.map_apply (measurable_affineObserved M) hE,
    Measure.map_apply (measurable_of_finite _)
      (hE.preimage (measurable_affineObserved M)),
    Measure.bind_apply hE (Kernel.aemeasurable _)]
  unfold bernoulliContractionObservedKernel
  rw [CausalSmith.Stat.DiscreteAteMinimaxLoggap.obsLaw]
  rw [radialContractedBinaryLaw, PMF.toMeasure_bind_apply
    (p := P.pmf)
    (f := fun z => (radialContractionPMF sigma z.2.2 hs0 hs2).map
      (fun b' => (⟨z.1, z.2.1, b'⟩ : BinObs m)))
    (s := binaryPadObs hmd ⁻¹' affineObserved M ⁻¹' E)
    ((hE.preimage (measurable_affineObserved M)).preimage
      (measurable_of_finite _))]
  rw [tsum_fintype, lintegral_fintype]
  classical
  apply Finset.sum_congr rfl
  intro z _hz
  rw [show CausalSmith.Stat.DiscreteAteMinimaxLoggap.obsLaw P {z} = P.pmf z by
    exact PMF.toMeasure_apply_singleton P.pmf z (MeasurableSet.singleton z)]
  have hinner :
      ((radialContractionPMF sigma z.2.2 hs0 hs2).map
        (fun b' => (⟨z.1, z.2.1, b'⟩ : BinObs m))).toMeasure
          (binaryPadObs hmd ⁻¹' affineObserved M ⁻¹' E) =
        (bernoulliContractionObservedKernel
          (fun k : Fin m => ⟨k, lt_of_lt_of_le k.isLt hmd⟩) M sigma z) E := by
    change _ = (Measure.map
      (fun r : ℝ => (⟨⟨z.1, lt_of_lt_of_le z.1.isLt hmd⟩,
        z.2.1, M * (r - 1 / 2)⟩ : Obs d))
      (Causalean.Mathlib.Probability.bernoulliLaw
        (bernoulliContractionSuccess sigma z.2.2))) E
    have hout : Measurable (fun r : ℝ =>
        (⟨⟨z.1, lt_of_lt_of_le z.1.isLt hmd⟩,
          z.2.1, M * (r - 1 / 2)⟩ : Obs d)) := by
      rw [measurable_comap_iff]
      change Measurable (fun r : ℝ =>
        ((⟨z.1, lt_of_lt_of_le z.1.isLt hmd⟩ : Fin d),
          z.2.1, M * (r - 1 / 2)))
      fun_prop
    rw [Measure.map_apply hout hE]
    rw [PMF.toMeasure_map_apply
      (f := fun b' => (⟨z.1, z.2.1, b'⟩ : BinObs m))
      (p := radialContractionPMF sigma z.2.2 hs0 hs2)
      (s := binaryPadObs hmd ⁻¹' affineObserved M ⁻¹' E)
      (measurable_of_finite _)
      ((hE.preimage (measurable_affineObserved M)).preimage
        (measurable_of_finite _))]
    have hleft : MeasurableSet
        ((fun b' => (⟨z.1, z.2.1, b'⟩ : BinObs m)) ⁻¹'
          binaryPadObs hmd ⁻¹' affineObserved M ⁻¹' E) :=
      ((hE.preimage (measurable_affineObserved M)).preimage
        (measurable_of_finite _)).preimage (measurable_of_finite _)
    rw [PMF.toMeasure_apply
      (p := radialContractionPMF sigma z.2.2 hs0 hs2) hleft,
      tsum_fintype, Fintype.sum_bool]
    unfold Causalean.Mathlib.Probability.bernoulliLaw
    rw [Measure.add_apply, Measure.smul_apply, Measure.smul_apply]
    simp only [Measure.dirac_apply, smul_eq_mul]
    by_cases h1 : (fun r : ℝ =>
        (⟨⟨z.1, lt_of_lt_of_le z.1.isLt hmd⟩,
          z.2.1, M * (r - 1 / 2)⟩ : Obs d)) 1 ∈ E <;>
      by_cases h0 : (fun r : ℝ =>
        (⟨⟨z.1, lt_of_lt_of_le z.1.isLt hmd⟩,
          z.2.1, M * (r - 1 / 2)⟩ : Obs d)) 0 ∈ E <;>
      simp [Set.indicator_apply, binaryPadObs, affineObserved, h1, h0,
        radialContractionPMF, PMF.ofFintype_apply]
  rw [hinner, mul_comm]
  rfl

-- @node: radialPaddedAffine_cellMass_image
/-- If [the source alphabet embeds in the target alphabet](hyp:hmd) and [the heterogeneity radius
  is nonnegative](hyp:hs0) and [the heterogeneity radius is at most two](hyp:hs2), [the concrete
  radial embedding preserves every positive source coordinate's cell mass](goal). -/
lemma radialPaddedAffine_cellMass_image {m d : ℕ} (hmd : m ≤ d)
    (M sigma : ℝ) (hs0 : 0 ≤ sigma) (hs2 : sigma ≤ 2)
    (P : BinLaw m) (k : Fin m) :
    (affineBinaryRealLaw M
      (binaryPadLaw hmd (radialContractedBinaryLaw P sigma hs0 hs2))).cellMass
        ⟨k, lt_of_lt_of_le k.isLt hmd⟩ =
      CausalSmith.Stat.DiscreteAteMinimaxLoggap.cellMass P k := by
  rw [affineBinaryPadded_cellMass_image, radialContractedBinaryLaw_cellMass]

-- @node: radialPaddedAffine_cellMass_off_image
/-- If [the source alphabet embeds in the target alphabet](hyp:hmd) and [the heterogeneity radius
  is nonnegative](hyp:hs0) and [the heterogeneity radius is at most two](hyp:hs2) and [the stated
  condition on the cell holds](hyp:hk), [every ambient coordinate outside the radial padding image
  has zero mass](goal). -/
lemma radialPaddedAffine_cellMass_off_image {m d : ℕ} (hmd : m ≤ d)
    (M sigma : ℝ) (hs0 : 0 ≤ sigma) (hs2 : sigma ≤ 2)
    (P : BinLaw m) (k : Fin d)
    (hk : ∀ r : Fin m, (⟨r, lt_of_lt_of_le r.isLt hmd⟩ : Fin d) ≠ k) :
    (affineBinaryRealLaw M
      (binaryPadLaw hmd (radialContractedBinaryLaw P sigma hs0 hs2))).cellMass k = 0 := by
  exact affineBinaryPadded_cellMass_off_image hmd M _ k hk

end CausalSmith.Stat.DiscreteAteHeterogeneityFrontier
