/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Basic
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.AdaptiveHinge
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.BinaryGap
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.BinaryWitness
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.BowConstruction
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.CapBridge
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.CdfMaps
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.CitedGates
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.Classes
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.CondClasses
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.ConditionalConstruction
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.Divergence
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.FiniteBandCoverage
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.FiniteQuery
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.Frontier
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.KernelPasting
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.Legality
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.OpenIllegal
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.ProductPerturbation
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.QueryEndpoints
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.Sampling
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.Statements
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.TieConstruction
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TBowMixtureCompleteness
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TCdfEndpointsSharp
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TConditionalAdaptiveHingeExactness
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TConditionalBowMixtureCompleteness
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TConditionalMutualSupportIntersection
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TConditionalOneSidedBowMixtureCompleteness
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TFiniteSampleSimultaneousBand
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TGeneratorIffFrontier
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.THeterogeneousPropensityElbow
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TMutualSupportIntersection
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TOneSidedBowMixtureCompleteness
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TOneSidedGeneratorIffFrontier
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TOneSidedQueryLegalityCorrection
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TOpenIllegalDichotomy
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TQueryLegalityCorrection
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TSupportRegimeCdfEndpointsSharp
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TSupportRegimeOpenIllegalDichotomy
public import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TTieInclusiveBandImpossibility

/-! # Run barrel (auto-generated)

Aggregates every module of this causalsmith run so the whole run is ONE buildable target
(`lake build <this module>`). Research modules are not reachable from the top-level
`CausalSmith.lean` barrel, so the default lake target skips them and reports green on stale
oleans. Rewritten from the run's module set on every F-stage entry — do not hand-edit. -/
