/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Basic
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.AdaptiveHinge
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.BinaryGap
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.BinaryWitness
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.BowConstruction
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.CapBridge
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.CdfMaps
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.CitedGates
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.Classes
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.CondClasses
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.ConditionalConstruction
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.Divergence
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.FiniteBandCoverage
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.FiniteQuery
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.Frontier
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.KernelPasting
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.Legality
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.OpenIllegal
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.ProductPerturbation
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.QueryEndpoints
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.Sampling
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.Statements
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.Helpers.TieConstruction
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TBowMixtureCompleteness
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TCdfEndpointsSharp
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TConditionalAdaptiveHingeExactness
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TConditionalBowMixtureCompleteness
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TConditionalMutualSupportIntersection
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TConditionalOneSidedBowMixtureCompleteness
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TFiniteSampleSimultaneousBand
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TGeneratorIffFrontier
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.THeterogeneousPropensityElbow
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TMutualSupportIntersection
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TOneSidedBowMixtureCompleteness
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TOneSidedGeneratorIffFrontier
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TOneSidedQueryLegalityCorrection
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TOpenIllegalDichotomy
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TQueryLegalityCorrection
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TSupportRegimeCdfEndpointsSharp
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TSupportRegimeOpenIllegalDichotomy
import CausalSmith.SCM.SCM_PropensityLvSharpnessFrontier_Research.TTieInclusiveBandImpossibility

/-! # Run barrel (auto-generated)

Aggregates every module of this causalsmith run so the whole run is ONE buildable target
(`lake build <this module>`). Research modules are not reachable from the top-level
`CausalSmith.lean` barrel, so the default lake target skips them and reports green on stale
oleans. Rewritten from the run's module set on every F-stage entry — do not hand-edit. -/
