module
public import Causalean.Mathlib.Analysis.NormedSpace.Duality.L1Linf.NonemptyDuality
public import CausalSmith.Stat.STAT_DiscreteAteMinimaxLoggap_Research.Helpers.OneArmSignedPrior

/-!
# Finite-grid best-approximation dual certificates

This file packages the finite-dimensional Hahn--Banach argument needed to turn
a positive uniform approximation error on a finite grid into a signed witness.
The approximation space is the range of an arbitrary linear map, so its basis
may contain polynomial evaluations, inverse evaluations, or any other finite
family of test functions.
-/

@[expose] public section

namespace CausalSmith.Stat.DiscreteAteMinimaxLoggap

open Causalean.Mathlib.Analysis.FiniteDimL1LinfDuality

variable {k : ℕ} {κ : Type*} [Fintype κ]

/-- Errors attainable when approximating `f` by the range of `A`, measured in
the finite-grid sup norm. -/
def finiteGridErrorSet (A : (κ → ℝ) →ₗ[ℝ] (Fin (k + 1) → ℝ))
    (f : Fin (k + 1) → ℝ) : Set ℝ :=
  {e | ∃ c, e = ninf (f - A c)}

/-- Best finite-grid uniform approximation error. -/
noncomputable def finiteGridBestError
    (A : (κ → ℝ) →ₗ[ℝ] (Fin (k + 1) → ℝ)) (f : Fin (k + 1) → ℝ) : ℝ :=
  sInf (finiteGridErrorSet A f)

/-- Evaluation map generated by an arbitrary finite family of grid functions.
In particular, a basis entry may be `fun i => (x i)⁻¹`. -/
def finiteGridBasisEval (basis : κ → Fin (k + 1) → ℝ) :
    (κ → ℝ) →ₗ[ℝ] (Fin (k + 1) → ℝ) where
  toFun c := fun i => ∑ j, c j * basis j i
  map_add' := by
    intro c d
    ext i
    simp only [Pi.add_apply, add_mul, Finset.sum_add_distrib]
  map_smul' := by
    intro r c
    ext i
    simp [Finset.mul_sum, mul_assoc]

/-- Evaluating the linear map generated by a finite family of grid functions at a
coefficient vector `c` and a grid point `i` returns the linear combination
`∑ⱼ cⱼ · basisⱼ(i)`.  This is the computation rule that lets grid arguments unfold
the approximation space to explicit sums. -/
@[simp] lemma finiteGridBasisEval_apply
    (basis : κ → Fin (k + 1) → ℝ) (c : κ → ℝ) (i : Fin (k + 1)) :
    finiteGridBasisEval basis c i = ∑ j, c j * basis j i := rfl

/-- The set of achievable uniform approximation errors on the grid is nonempty:
the zero coefficient vector already produces one error value.  Needed so that the
infimum defining the best error is taken over a nonempty set. -/
lemma finiteGridErrorSet_nonempty
    (A : (κ → ℝ) →ₗ[ℝ] (Fin (k + 1) → ℝ)) (f : Fin (k + 1) → ℝ) :
    (finiteGridErrorSet A f).Nonempty := by
  exact ⟨ninf (f - A 0), 0, rfl⟩

/-- The set of achievable uniform approximation errors on the grid is bounded below,
since every such error is a sup norm and hence nonnegative.  Together with
nonemptiness this makes the best-error infimum well behaved. -/
lemma finiteGridErrorSet_bddBelow
    (A : (κ → ℝ) →ₗ[ℝ] (Fin (k + 1) → ℝ)) (f : Fin (k + 1) → ℝ) :
    BddBelow (finiteGridErrorSet A f) := by
  refine ⟨0, ?_⟩
  rintro e ⟨c, rfl⟩
  exact ninf_nonneg _

/-- The best finite-grid uniform approximation error is at most the error produced
by any particular choice of coefficients.  This is the standard way to bound the
best error from above by exhibiting one candidate approximant. -/
lemma finiteGridBestError_le
    (A : (κ → ℝ) →ₗ[ℝ] (Fin (k + 1) → ℝ)) (f : Fin (k + 1) → ℝ)
    (c : κ → ℝ) :
    finiteGridBestError A f ≤ ninf (f - A c) := by
  exact csInf_le (finiteGridErrorSet_bddBelow A f) ⟨c, rfl⟩

/-- A positive best finite-grid approximation error has a dual unit-ball
witness.  The witness annihilates the entire approximation space and pairs
with the target to exactly the best error. -/
theorem exists_finiteGrid_dual_witness
    (A : (κ → ℝ) →ₗ[ℝ] (Fin (k + 1) → ℝ)) (f : Fin (k + 1) → ℝ)
    (hpos : 0 < finiteGridBestError A f) :
    ∃ w : Fin (k + 1) → ℝ,
      (∀ c, ∑ i, w i * A c i = 0) ∧
      (∑ i, |w i| ≤ 1) ∧
      ∑ i, w i * f i = finiteGridBestError A f := by
  classical
  let E := Fin (k + 1) → ℝ
  let D := (κ → ℝ) × ℝ
  let δ := finiteGridBestError A f
  let B : D →ₗ[ℝ] E := {
    toFun := fun z => A z.1 + z.2 • f
    map_add' := by
      intro x y
      ext i
      change A (x.1 + y.1) i + (x.2 + y.2) * f i =
        (A x.1 i + x.2 * f i) + (A y.1 i + y.2 * f i)
      rw [map_add]
      change (A x.1 i + A y.1 i) + (x.2 + y.2) * f i = _
      ring
    map_smul' := by
      intro r x
      ext i
      change A (r • x.1) i + (r * x.2) * f i =
        r * (A x.1 i + x.2 * f i)
      rw [map_smul]
      change r * A x.1 i + (r * x.2) * f i = _
      ring
  }
  let L : D →ₗ[ℝ] ℝ := {
    toFun := fun z => z.2 * δ
    map_add' := by intro x y; change (x.2 + y.2) * δ = _; ring
    map_smul' := by intro r x; change (r * x.2) * δ = r * (x.2 * δ); ring
  }
  have hker : LinearMap.ker B ≤ LinearMap.ker L := by
    intro z hz
    change L z = 0
    by_contra hL
    have ht : z.2 ≠ 0 := by
      intro ht
      apply hL
      simp [L, ht]
    let c : κ → ℝ := fun j => -(z.2)⁻¹ * z.1 j
    have hzero : f - A c = 0 := by
      have hz0 : B z = 0 := hz
      ext i
      have hzi : A z.1 i + z.2 * f i = 0 := by
        have hi := congr_fun hz0 i
        change A z.1 i + z.2 * f i = (0 : ℝ) at hi
        simpa [B] using hi
      simp only [Pi.sub_apply]
      have hAc : A c i = -(z.2)⁻¹ * A z.1 i := by
        have hc : c = (-(z.2)⁻¹) • z.1 := by ext j; simp [c]
        rw [hc, map_smul]
        rfl
      rw [hAc]
      calc
        f i - (-z.2⁻¹ * A z.1 i) =
            z.2⁻¹ * (A z.1 i + z.2 * f i) := by
              field_simp [ht]
              <;> ring
        _ = 0 := by rw [hzi]; simp
    have := finiteGridBestError_le A f c
    rw [hzero] at this
    have hnzero : ninf (0 : Fin (k + 1) → ℝ) = 0 := by
      apply le_antisymm
      · rw [ninf]
        apply Finset.sup'_le ⟨0, Finset.mem_univ 0⟩
        intro i hi
        simp
      · exact ninf_nonneg _
    rw [hnzero] at this
    exact (not_lt_of_ge this hpos)
  let Lq : (D ⧸ LinearMap.ker B) →ₗ[ℝ] ℝ :=
    (LinearMap.ker B).liftQ L hker
  let φ : LinearMap.range B →ₗ[ℝ] ℝ :=
    Lq.comp B.quotKerEquivRange.symm.toLinearMap
  let sublinear : E → ℝ := ninf
  have hφ_image (z : D) :
      φ ⟨B z, LinearMap.mem_range_self B z⟩ = L z := by
    simp [φ, Lq, LinearMap.quotKerEquivRange_symm_apply_image]
  have hφ_le : ∀ x : LinearMap.range B, φ x ≤ sublinear x := by
    rintro ⟨_, ⟨z, rfl⟩⟩
    rw [hφ_image]
    change z.2 * δ ≤ ninf (A z.1 + z.2 • f)
    by_cases ht : 0 < z.2
    · let c : κ → ℝ := fun j => -(z.2)⁻¹ * z.1 j
      have hbase := finiteGridBestError_le A f c
      have hAc : A c = (-(z.2)⁻¹) • A z.1 := by
        have hc : c = (-(z.2)⁻¹) • z.1 := by ext j; simp [c]
        rw [hc, map_smul]
      have hscale : A z.1 + z.2 • f = z.2 • (f - A c) := by
        rw [hAc]
        ext i
        simp only [Pi.add_apply, Pi.smul_apply, smul_eq_mul, Pi.sub_apply]
        field_simp
        ring
      rw [hscale, ninf_smul, abs_of_pos ht]
      exact mul_le_mul_of_nonneg_left hbase ht.le
    · exact le_trans (mul_nonpos_of_nonpos_of_nonneg (le_of_not_gt ht) hpos.le)
        (ninf_nonneg _)
  have N_hom : ∀ c : ℝ, 0 < c → ∀ x, sublinear (c • x) = c * sublinear x := by
    intro c hc x
    change ninf (c • x) = c * ninf x
    rw [ninf_smul, abs_of_pos hc]
  have N_add : ∀ x y, sublinear (x + y) ≤ sublinear x + sublinear y := by
    exact fun x y => ninf_add_le x y
  let bundled : E →ₗ.[ℝ] ℝ := ⟨LinearMap.range B, φ⟩
  obtain ⟨g, hg_ext, hg_le⟩ :=
    exists_extension_of_le_sublinear bundled sublinear N_hom N_add hφ_le
  let w : Fin (k + 1) → ℝ := fun i => g (Pi.single i (1 : ℝ))
  have hg_expand (x : E) : g x = ∑ i, x i * w i := by
    have hxsum : (∑ i, Pi.single i (x i) : E) = x := by
      simpa using (Finset.univ_sum_single x)
    calc
      g x = g (∑ i, Pi.single i (x i)) := by rw [hxsum]
      _ = ∑ i, g (Pi.single i (x i)) := by rw [map_sum]
      _ = ∑ i, x i * w i := by
        refine Finset.sum_congr rfl ?_
        intro i _
        have hs : Pi.single i (x i) = (x i) • (Pi.single i (1 : ℝ) : E) := by
          ext j
          by_cases hji : j = i
          · subst j; simp
          · simp [hji]
        rw [hs, map_smul]
        simp [w]
  refine ⟨w, ?_, ?_, ?_⟩
  · intro c
    let z : D := (c, 0)
    have hext : g (B z) = L z := by
      let x : LinearMap.range B := ⟨B z, LinearMap.mem_range_self B z⟩
      exact (hg_ext x).trans (hφ_image z)
    have hBA : B z = A c := by ext i; simp [B, z]
    rw [hBA, hg_expand] at hext
    simpa [L, z, mul_comm] using hext
  · let σ : E := fun i => if 0 ≤ w i then (1 : ℝ) else -1
    have hσ_abs : ∀ i, |σ i| = 1 := by
      intro i
      by_cases hi : 0 ≤ w i <;> simp [σ, hi]
    have hninf : sublinear σ = 1 := by
      simp [sublinear, ninf_sign σ hσ_abs]
    have habs : ∑ i, |w i| = ∑ i, σ i * w i := by
      refine Finset.sum_congr rfl ?_
      intro i _
      by_cases hi : 0 ≤ w i
      · simp [σ, hi, abs_of_nonneg hi]
      · have hilt : w i < 0 := lt_of_not_ge hi
        simp [σ, hi, abs_of_neg hilt]
    calc
      ∑ i, |w i| = ∑ i, σ i * w i := habs
      _ = g σ := (hg_expand σ).symm
      _ ≤ sublinear σ := hg_le σ
      _ = 1 := hninf
  · let z : D := (0, 1)
    have hext : g (B z) = L z := by
      let x : LinearMap.range B := ⟨B z, LinearMap.mem_range_self B z⟩
      exact (hg_ext x).trans (hφ_image z)
    have hBf : B z = f := by ext i; simp [B, z]
    rw [hBf, hg_expand] at hext
    simpa [L, z, δ, mul_comm] using hext

/-- Basis-indexed form of `exists_finiteGrid_dual_witness`. -/
theorem exists_finiteGrid_basis_dual_witness
    (basis : κ → Fin (k + 1) → ℝ) (f : Fin (k + 1) → ℝ)
    (hpos : 0 < finiteGridBestError (finiteGridBasisEval basis) f) :
    ∃ w : Fin (k + 1) → ℝ,
      (∀ j, ∑ i, w i * basis j i = 0) ∧
      (∑ i, |w i| ≤ 1) ∧
      ∑ i, w i * f i = finiteGridBestError (finiteGridBasisEval basis) f := by
  classical
  obtain ⟨w, hann, hnorm, hatt⟩ :=
    exists_finiteGrid_dual_witness (finiteGridBasisEval basis) f hpos
  refine ⟨w, ?_, hnorm, hatt⟩
  intro j
  have hsingle : finiteGridBasisEval basis (Pi.single j (1 : ℝ)) = basis j := by
    ext i
    rw [finiteGridBasisEval_apply, Fintype.sum_eq_single j]
    · simp
    · intro b hb
      simp [Pi.single_eq_of_ne hb]
  have h := hann (Pi.single j (1 : ℝ))
  rw [hsingle] at h
  exact h

/-- A dual witness for a space containing constants has zero total mass. -/
lemma finiteGrid_dual_witness_sum_zero
    (A : (κ → ℝ) →ₗ[ℝ] (Fin (k + 1) → ℝ)) (w : Fin (k + 1) → ℝ)
    (hann : ∀ c, ∑ i, w i * A c i = 0)
    (cOne : κ → ℝ) (hOne : A cOne = fun _ => 1) :
    ∑ i, w i = 0 := by
  have h := hann cOne
  simpa [hOne] using h

/-- If the approximation space contains constants, the dual witness splits
into two probability masses with identical expectations on the whole space.
Their target expectations differ by at least twice the best grid error. -/
theorem exists_finiteGrid_jordan_priors
    (A : (κ → ℝ) →ₗ[ℝ] (Fin (k + 1) → ℝ)) (f : Fin (k + 1) → ℝ)
    (cOne : κ → ℝ) (hOne : A cOne = fun _ => 1)
    (hpos : 0 < finiteGridBestError A f) :
    ∃ (w : Fin (k + 1) → ℝ)
      (hzero : ∑ i, w i = 0)
      (hmass : 0 < positiveJordanMass w),
      (∑ i, |w i| ≤ 1) ∧
      (∀ c,
        ∑ i, (positiveJordanPMF w hmass i).toReal * A c i =
          ∑ i, (negativeJordanPMF w
            (by simpa [positiveJordanMass_eq_negativeJordanMass w hzero] using hmass) i).toReal *
              A c i) ∧
      2 * finiteGridBestError A f ≤
        (∑ i, (positiveJordanPMF w hmass i).toReal * f i) -
          ∑ i, (negativeJordanPMF w
            (by simpa [positiveJordanMass_eq_negativeJordanMass w hzero] using hmass) i).toReal *
              f i := by
  classical
  obtain ⟨w, hann, hnorm, hatt⟩ := exists_finiteGrid_dual_witness A f hpos
  have hzero : ∑ i, w i = 0 :=
    finiteGrid_dual_witness_sum_zero A w hann cOne hOne
  have hmass : 0 < positiveJordanMass w := by
    have hmass_nonneg : 0 ≤ positiveJordanMass w :=
      Finset.sum_nonneg fun i _ => le_max_right (w i) 0
    by_contra hnot
    have hmass_zero : positiveJordanMass w = 0 :=
      le_antisymm (le_of_not_gt hnot) hmass_nonneg
    have habs_zero : ∑ i, |w i| = 0 := by
      have htv := two_mul_positiveJordanMass_eq_sum_abs w hzero
      rw [hmass_zero] at htv
      simpa using htv.symm
    have hwzero : w = 0 := by
      funext i
      apply abs_eq_zero.mp
      exact (Finset.sum_eq_zero_iff_of_nonneg
        (fun j _ => abs_nonneg (w j))).mp habs_zero i (Finset.mem_univ i)
    have : finiteGridBestError A f = 0 := by
      rw [← hatt, hwzero]
      simp
    exact (ne_of_gt hpos) this
  refine ⟨w, hzero, hmass, hnorm, ?_, ?_⟩
  · intro c
    exact positiveJordanPMF_sum_eq_negativeJordanPMF_sum_of_weighted_sum_eq_zero
      w (A c) hzero hmass (hann c)
  · rw [positiveJordanPMF_sum_sub_negativeJordanPMF_sum w f hzero hmass, hatt]
    have hmass_le : positiveJordanMass w ≤ 1 / 2 := by
      have htv := two_mul_positiveJordanMass_eq_sum_abs w hzero
      nlinarith
    rw [le_div_iff₀ hmass]
    nlinarith

end CausalSmith.Stat.DiscreteAteMinimaxLoggap
