module
public import CausalSmith.Stat.STAT_DiscreteAteMinimaxLoggap_Research.Helpers.OneArmConditioning
public import CausalSmith.Stat.STAT_DiscreteAteMinimaxLoggap_Research.Helpers.OneArmConfiguration
public import CausalSmith.Stat.STAT_DiscreteAteMinimaxLoggap_Research.Helpers.OneArmShiftedPrior
public import Causalean.Stat.Concentration.Matrix.IidSums

/-!
# Finite product-prior conditioning for the one-arm converse

This module packages an iid finite prior as both a product measure and a PMF,
gives the two Chebyshev bounds used to condition on mass and functional
concentration, and normalizes every good realization into a control-zero law.
-/

@[expose] public section

namespace CausalSmith.Stat.DiscreteAteMinimaxLoggap

open MeasureTheory ProbabilityTheory
open scoped BigOperators ENNReal

/-- The iid product measure generated by a finite PMF. -/
noncomputable def oneArmFiniteIidMeasure {α : Type*} [Fintype α]
    [MeasurableSpace α] (ω : PMF α) (m : ℕ) : Measure (Fin m → α) :=
  Measure.pi (fun _ : Fin m => ω.toMeasure)

/-- The iid product measure built from a finite probability mass function is
itself a probability measure. -/
noncomputable instance oneArmFiniteIidMeasure_isProbabilityMeasure
    {α : Type*} [Fintype α] [MeasurableSpace α]
    (ω : PMF α) (m : ℕ) : IsProbabilityMeasure (oneArmFiniteIidMeasure ω m) := by
  unfold oneArmFiniteIidMeasure
  infer_instance

/-- The discrete PMF underlying the iid product measure. -/
noncomputable def oneArmFiniteIidPMF {α : Type*} [Fintype α]
    [MeasurableSpace α] [MeasurableSingletonClass α]
    (ω : PMF α) (m : ℕ) : PMF (Fin m → α) :=
  (oneArmFiniteIidMeasure ω m).toPMF

/-- The discrete mass function attached to the iid product prior induces exactly
the iid product measure it came from, so the two views may be used
interchangeably. -/
lemma oneArmFiniteIidPMF_toMeasure {α : Type*} [Fintype α]
    [MeasurableSpace α] [MeasurableSingletonClass α]
    (ω : PMF α) (m : ℕ) :
    (oneArmFiniteIidPMF ω m).toMeasure = oneArmFiniteIidMeasure ω m := by
  unfold oneArmFiniteIidPMF
  exact Measure.toPMF_toMeasure _

/-- Chebyshev concentration of any square-integrable atom statistic under the
finite iid product prior. -/
lemma oneArmFiniteIid_sum_chebyshev {α : Type*} [Fintype α]
    [MeasurableSpace α] (ω : PMF α) (m : ℕ) (g : α → ℝ)
    (hg : MemLp g 2 ω.toMeasure) {δ : ℝ} (hδ : 0 < δ) :
    oneArmFiniteIidMeasure ω m
        {z | δ ≤ |(∑ i, g (z i)) - m * ∫ x, g x ∂ω.toMeasure|} ≤
      ENNReal.ofReal (m * Var[g; ω.toMeasure] / δ ^ 2) := by
  simpa [oneArmFiniteIidMeasure] using
    (Causalean.Stat.Concentration.iid_sum_chebyshev
      (N := m) ω.toMeasure g hg hδ)

/-- The two concentration failures needed in the fuzzy-prior conditioning
step are controlled by the sum of their two Chebyshev envelopes. -/
lemma oneArmFiniteIid_two_sum_bad_le {α : Type*} [Fintype α]
    [MeasurableSpace α] (ω : PMF α) (m : ℕ) (g h : α → ℝ)
    (hg : MemLp g 2 ω.toMeasure) (hh : MemLp h 2 ω.toMeasure)
    {δg δh : ℝ} (hδg : 0 < δg) (hδh : 0 < δh) :
    oneArmFiniteIidMeasure ω m
        ({z | δg ≤ |(∑ i, g (z i)) - m * ∫ x, g x ∂ω.toMeasure|} ∪
         {z | δh ≤ |(∑ i, h (z i)) - m * ∫ x, h x ∂ω.toMeasure|}) ≤
      ENNReal.ofReal (m * Var[g; ω.toMeasure] / δg ^ 2) +
        ENNReal.ofReal (m * Var[h; ω.toMeasure] / δh ^ 2) := by
  calc
    _ ≤ oneArmFiniteIidMeasure ω m
          {z | δg ≤ |(∑ i, g (z i)) - m * ∫ x, g x ∂ω.toMeasure|} +
        oneArmFiniteIidMeasure ω m
          {z | δh ≤ |(∑ i, h (z i)) - m * ∫ x, h x ∂ω.toMeasure|} :=
      measure_union_le _ _
    _ ≤ _ := add_le_add
      (oneArmFiniteIid_sum_chebyshev ω m g hg hδg)
      (oneArmFiniteIid_sum_chebyshev ω m h hh hδh)

/-- Cell-mass statistic of one inverse-tilted lifted atom. -/
noncomputable def oneArmProductMassAtom {ι : Type*}
    (scale : ℝ) (x : ι → ℝ) : Option ι → ℝ :=
  liftedCellMass scale x

/-- Treated-functional statistic of one inverse-tilted lifted atom. -/
noncomputable def oneArmProductFunctionalAtom {ι : Type*}
    (scale a : ℝ) (x : ι → ℝ) (z : Option ι) : ℝ :=
  liftedCellMass scale x z * liftedOutcomeMean a x z

/-- Simultaneous mass and treated-functional concentration for a finite iid
inverse-tilted prior. -/
lemma oneArmProduct_mass_functional_bad_le {ι : Type*} [Fintype ι]
    [MeasurableSpace (Option ι)]
    (ω : PMF (Option ι)) (m : ℕ) (scale a : ℝ) (x : ι → ℝ)
    (hmass : MemLp (oneArmProductMassAtom scale x) 2 ω.toMeasure)
    (hfun : MemLp (oneArmProductFunctionalAtom scale a x) 2 ω.toMeasure)
    {δmass δfun : ℝ} (hδmass : 0 < δmass) (hδfun : 0 < δfun) :
    oneArmFiniteIidMeasure ω m
        ({z | δmass ≤
            |(∑ i, oneArmProductMassAtom scale x (z i)) -
              m * ∫ u, oneArmProductMassAtom scale x u ∂ω.toMeasure|} ∪
         {z | δfun ≤
            |(∑ i, oneArmProductFunctionalAtom scale a x (z i)) -
              m * ∫ u, oneArmProductFunctionalAtom scale a x u ∂ω.toMeasure|}) ≤
      ENNReal.ofReal
          (m * Var[oneArmProductMassAtom scale x; ω.toMeasure] / δmass ^ 2) +
        ENNReal.ofReal
          (m * Var[oneArmProductFunctionalAtom scale a x; ω.toMeasure] / δfun ^ 2) := by
  exact oneArmFiniteIid_two_sum_bad_le ω m _ _ hmass hfun hδmass hδfun

/-- Coordinatewise normalization of a nonnegative mass vector. -/
noncomputable def oneArmNormalizedMass {d : ℕ} (p : Fin d → ℝ) : Fin d → ℝ :=
  fun r => p r / ∑ t, p t

/-- Normalizing a nonnegative mass vector with strictly positive total leaves
every coordinate nonnegative. -/
lemma oneArmNormalizedMass_nonneg {d : ℕ} (p : Fin d → ℝ)
    (hp : ∀ r, 0 ≤ p r) (hS : 0 < ∑ r, p r) :
    ∀ r, 0 ≤ oneArmNormalizedMass p r := by
  intro r
  exact div_nonneg (hp r) hS.le

/-- Every coordinate of the normalized mass vector is at most one, since a single
nonnegative summand cannot exceed the total. -/
lemma oneArmNormalizedMass_le_one {d : ℕ} (p : Fin d → ℝ)
    (hp : ∀ r, 0 ≤ p r) (hS : 0 < ∑ r, p r) :
    ∀ r, oneArmNormalizedMass p r ≤ 1 := by
  intro r
  rw [oneArmNormalizedMass, div_le_one hS]
  exact Finset.single_le_sum (fun i _ => hp i) (Finset.mem_univ r)

/-- The normalized mass vector sums to one, so it is a valid category
distribution. -/
lemma oneArmNormalizedMass_sum {d : ℕ} (p : Fin d → ℝ)
    (hS : 0 < ∑ r, p r) :
    ∑ r, oneArmNormalizedMass p r = 1 := by
  calc
    ∑ r, oneArmNormalizedMass p r = (∑ r, p r) / (∑ r, p r) := by
      simp only [oneArmNormalizedMass]
      rw [Finset.sum_div]
    _ = 1 := div_self (show (∑ r, p r) ≠ 0 from ne_of_gt hS)

/-- Every good product-prior realization (positive total cell mass, valid
propensities, and valid outcome means) normalizes to the public control-zero
model class. -/
noncomputable def oneArmNormalizedControlZero
    {n d : ℕ} {epsilon : ℝ} (p pi mu : Fin d → ℝ)
    (he0 : 0 < epsilon) (hehalf : epsilon ≤ 1 / 2)
    (hp : ∀ r, 0 ≤ p r) (hS : 0 < ∑ r, p r)
    (hpi : ∀ r, pi r ∈ Set.Icc epsilon (1 - epsilon))
    (hmu : ∀ r, mu r ∈ Set.Icc (0 : ℝ) 1) :
    ControlZeroLaw n d epsilon :=
  oneArmConfigurationControlZero (oneArmNormalizedMass p) pi mu
    he0 hehalf
    (fun r => ⟨oneArmNormalizedMass_nonneg p hp hS r,
      oneArmNormalizedMass_le_one p hp hS r⟩)
    hpi hmu (oneArmNormalizedMass_sum p hS)

/-- The treated functional of the normalized configuration remains within the
mass defect of its unnormalized product-prior sum. -/
lemma oneArmNormalizedControlZero_functional_sub_le
    {n d : ℕ} {epsilon : ℝ} (p pi mu : Fin d → ℝ)
    (he0 : 0 < epsilon) (hehalf : epsilon ≤ 1 / 2)
    (hp : ∀ r, 0 ≤ p r) (hS : 0 < ∑ r, p r)
    (hpi : ∀ r, pi r ∈ Set.Icc epsilon (1 - epsilon))
    (hmu : ∀ r, mu r ∈ Set.Icc (0 : ℝ) 1)
    (hpi_pos : ∀ r, 0 < pi r) :
    |treatedFunctional
          ((oneArmNormalizedControlZero (n := n) p pi mu he0 hehalf hp hS hpi hmu :
            ControlZeroLaw n d epsilon)).1 -
        ∑ r, p r * mu r| ≤
      |(∑ r, p r) - 1| := by
  let hpIcc : ∀ r, oneArmNormalizedMass p r ∈ Set.Icc (0 : ℝ) 1 :=
    fun r => ⟨oneArmNormalizedMass_nonneg p hp hS r,
      oneArmNormalizedMass_le_one p hp hS r⟩
  let hpi01 : ∀ r, pi r ∈ Set.Icc (0 : ℝ) 1 := fun r => by
    exact ⟨he0.le.trans (hpi r).1, by linarith [(hpi r).2, he0]⟩
  change |treatedFunctional
      (oneArmConfigurationLaw (oneArmNormalizedMass p) pi mu hpIcc hpi01 hmu
        (oneArmNormalizedMass_sum p hS)) - ∑ r, p r * mu r| ≤ _
  rw [oneArmConfigurationLaw_treatedFunctional
    (oneArmNormalizedMass p) pi mu hpIcc hpi01 hmu
    (oneArmNormalizedMass_sum p hS) hpi_pos]
  exact normalized_oneArmFunctional_sub_le_massDefect p mu hp hmu hS

/-! ## Anchor completion

The lower-bound construction must retain the small active-cell scale.  It
therefore fills the unused mass with one deterministic anchor, rather than
renormalizing the active cells.
-/

/-- Extends a vector of active-cell masses by one extra anchor cell carrying all
the leftover mass, so the resulting vector of length one more is a probability
vector without rescaling the active cells. -/
noncomputable def oneArmAnchoredMass {m : ℕ} (q : Fin m → ℝ) : Fin (m + 1) → ℝ :=
  Fin.cases (1 - ∑ i, q i) q

/-- Extends the active cells' propensities by giving the anchor cell propensity
exactly ε, the smallest value overlap allows. -/
noncomputable def oneArmAnchoredPropensity {m : ℕ} (epsilon : ℝ)
    (pi : Fin m → ℝ) : Fin (m + 1) → ℝ :=
  Fin.cases epsilon pi

/-- Extends the active cells' treated outcome means by giving the anchor cell
treated mean zero, so the anchor contributes nothing to the treated
functional. -/
noncomputable def oneArmAnchoredOutcomeMean {m : ℕ}
    (mu : Fin m → ℝ) : Fin (m + 1) → ℝ :=
  Fin.cases 0 mu

/-- The anchor-completed mass vector sums to one by construction. -/
lemma oneArmAnchoredMass_sum {m : ℕ} (q : Fin m → ℝ) :
    ∑ r, oneArmAnchoredMass q r = 1 := by
  rw [Fin.sum_univ_succ]
  simp [oneArmAnchoredMass]

/-- If the active masses are nonnegative and do not overshoot one, every
coordinate of the anchor-completed vector — the anchor included — is
nonnegative. -/
lemma oneArmAnchoredMass_nonneg {m : ℕ} (q : Fin m → ℝ)
    (hq : ∀ i, 0 ≤ q i) (hS : ∑ i, q i ≤ 1) :
    ∀ r, 0 ≤ oneArmAnchoredMass q r := by
  intro r
  refine Fin.cases ?_ (fun i => hq i) r
  simp [oneArmAnchoredMass, sub_nonneg.mpr hS]

/-- Under the same hypotheses every coordinate of the anchor-completed vector is
at most one, so the vector is a genuine category distribution. -/
lemma oneArmAnchoredMass_le_one {m : ℕ} (q : Fin m → ℝ)
    (hq : ∀ i, 0 ≤ q i) (hS : ∑ i, q i ≤ 1) :
    ∀ r, oneArmAnchoredMass q r ≤ 1 := by
  intro r
  have hnonneg := oneArmAnchoredMass_nonneg q hq hS
  rw [← oneArmAnchoredMass_sum q]
  exact Finset.single_le_sum (fun i _ => hnonneg i) (Finset.mem_univ r)

/-- Complete `m` active cells by a residual anchor of mass `1-Σqᵢ`.
The anchor has propensity `epsilon` and treated mean zero, so it preserves
overlap and contributes nothing to the treated functional. -/
noncomputable def oneArmAnchoredControlZero
    {n m : ℕ} {epsilon : ℝ} (q pi mu : Fin m → ℝ)
    (he0 : 0 < epsilon) (hehalf : epsilon ≤ 1 / 2)
    (hq : ∀ i, 0 ≤ q i) (hS : ∑ i, q i ≤ 1)
    (hpi : ∀ i, pi i ∈ Set.Icc epsilon (1 - epsilon))
    (hmu : ∀ i, mu i ∈ Set.Icc (0 : ℝ) 1) :
    ControlZeroLaw n (m + 1) epsilon := by
  let p := oneArmAnchoredMass q
  let pi' := oneArmAnchoredPropensity epsilon pi
  let mu' := oneArmAnchoredOutcomeMean mu
  apply oneArmConfigurationControlZero p pi' mu' he0 hehalf
  · exact fun r => ⟨oneArmAnchoredMass_nonneg q hq hS r,
      oneArmAnchoredMass_le_one q hq hS r⟩
  · intro r
    refine Fin.cases ?_ (fun i => hpi i) r
    change epsilon ∈ Set.Icc epsilon (1 - epsilon)
    exact ⟨le_rfl, by linarith⟩
  · intro r
    refine Fin.cases ?_ (fun i => hmu i) r
    change (0 : ℝ) ∈ Set.Icc 0 1
    norm_num
  · exact oneArmAnchoredMass_sum q

/-- The treated functional of the anchor-completed control-zero law is exactly the
active cells' mass-weighted average treated outcome, with no contribution from
the anchor. -/
lemma oneArmAnchoredControlZero_functional
    {n m : ℕ} {epsilon : ℝ} (q pi mu : Fin m → ℝ)
    (he0 : 0 < epsilon) (hehalf : epsilon ≤ 1 / 2)
    (hq : ∀ i, 0 ≤ q i) (hS : ∑ i, q i ≤ 1)
    (hpi : ∀ i, pi i ∈ Set.Icc epsilon (1 - epsilon))
    (hmu : ∀ i, mu i ∈ Set.Icc (0 : ℝ) 1)
    (hpi_pos : ∀ i, 0 < pi i) :
    treatedFunctional
        ((oneArmAnchoredControlZero (n := n) q pi mu he0 hehalf hq hS hpi hmu :
          ControlZeroLaw n (m + 1) epsilon)).1 =
      ∑ i, q i * mu i := by
  let p := oneArmAnchoredMass q
  let pi' := oneArmAnchoredPropensity epsilon pi
  let mu' := oneArmAnchoredOutcomeMean mu
  have hpi'_pos : ∀ r, 0 < pi' r := by
    intro r
    refine Fin.cases he0 (fun i => hpi_pos i) r
  change treatedFunctional
      (oneArmConfigurationLaw p pi' mu'
        (fun r => ⟨oneArmAnchoredMass_nonneg q hq hS r,
          oneArmAnchoredMass_le_one q hq hS r⟩)
        (fun r => by
          refine Fin.cases ?_ (fun i => ?_) r
          · change epsilon ∈ Set.Icc (0 : ℝ) 1
            exact ⟨he0.le, by linarith⟩
          · change pi i ∈ Set.Icc (0 : ℝ) 1
            exact ⟨he0.le.trans (hpi i).1, by linarith [(hpi i).2, he0]⟩)
        (fun r => by
          refine Fin.cases ?_ (fun i => hmu i) r
          change (0 : ℝ) ∈ Set.Icc 0 1
          norm_num)
        (oneArmAnchoredMass_sum q)) = _
  calc
    treatedFunctional (oneArmConfigurationLaw p pi' mu' _ _ _ _) =
        ∑ r, p r * mu' r := by
      exact oneArmConfigurationLaw_treatedFunctional p pi' mu' _ _ _ _ hpi'_pos
    _ = ∑ i, q i * mu i := by
      rw [Fin.sum_univ_succ]
      simp [p, mu', oneArmAnchoredMass, oneArmAnchoredOutcomeMean]

end CausalSmith.Stat.DiscreteAteMinimaxLoggap
