module
public import CausalSmith.Stat.STAT_DiscreteAteMinimaxLoggap_Research.Helpers.OneArmShiftedFiniteGrid
public import CausalSmith.Stat.STAT_DiscreteAteMinimaxLoggap_Research.Helpers.OneArmGridPriorLift

/-!
# Inverse tilt on the overlap-shifted selected grid

The pole `bκ` is no larger than the smallest grid node, so the Jordan priors
can be inverse-tilted and their approximation gap becomes a functional gap.
-/

public section

namespace CausalSmith.Stat.DiscreteAteMinimaxLoggap

/-- Every point of the shifted selection grid is strictly positive. -/
lemma oneArmShiftedSelectionGrid_pos
    {κ : ℝ} {D : ℕ} (hκ : 0 < κ) (hκ1 : κ ≤ 1) (hD : 1 ≤ D)
    (i : Fin (2 * D + 4)) : 0 < oneArmShiftedSelectionGrid κ D i :=
  (oneArmShiftedNodeScale_pos hκ hD).trans_le
    (oneArmShiftedSelectionGrid_mem_Icc hκ hκ1 hD i).1

/-- The pole location never exceeds any grid point, since it is `κ ≤ 1` times
the smallest grid node.  This is the condition making the inverse tilt a valid
(nonnegative) reweighting. -/
lemma oneArmShiftedPole_le_grid
    {κ : ℝ} {D : ℕ} (hκ : 0 < κ) (hκ1 : κ ≤ 1) (hD : 1 ≤ D)
    (i : Fin (2 * D + 4)) :
    oneArmShiftedPoleScale κ D ≤ oneArmShiftedSelectionGrid κ D i := by
  have ha0 := oneArmShiftedNodeScale_pos hκ hD
  have hb_a : oneArmShiftedPoleScale κ D ≤ oneArmShiftedNodeScale κ D := by
    unfold oneArmShiftedPoleScale
    nlinarith
  exact hb_a.trans (oneArmShiftedSelectionGrid_mem_Icc hκ hκ1 hD i).1

/-- Inverse tilting any prior on the shifted grid by the pole produces
nonnegative weights, so the tilted object is again a valid distribution. -/
lemma oneArmShiftedSelectionGrid_inverseTiltWeight_nonneg
    (D : ℕ) { κ : ℝ} (hκ : 0 < κ) (hκ1 : κ ≤ 1) (hD : 1 ≤ D)
    (ω : PMF (Fin (2 * D + 4))) :
    ∀ z, 0 ≤ inverseTiltWeight ω (oneArmShiftedSelectionGrid κ D)
      (oneArmShiftedPoleScale κ D) z := by
  exact inverseTiltWeight_nonneg ω (oneArmShiftedSelectionGrid κ D)
    (oneArmShiftedPoleScale_pos hκ hD).le
    (oneArmShiftedPole_le_grid hκ hκ1 hD)

/-- For a polynomial of degree at most `D`, the function `P(x)/x` lies in the
span of the reciprocal-monomial basis: evaluating the basis at the coefficient
vector extracted from `P` reproduces `P(x)/x` at every grid point. -/
lemma oneArmShiftedSelectionBasis_represents_polynomial_div
    {D : ℕ} (hD : 1 ≤ D) {κ : ℝ} (hκ : 0 < κ) (hκ1 : κ ≤ 1)
    (P : Polynomial ℝ) (hdeg : P.natDegree ≤ D) (i : Fin (2 * D + 4)) :
    finiteGridBasisEval (oneArmShiftedSelectionBasis κ D)
        (oneArmPolynomialDivCoeff D P) i =
      P.eval (oneArmShiftedSelectionGrid κ D i) /
        oneArmShiftedSelectionGrid κ D i := by
  let x := oneArmShiftedSelectionGrid κ D i
  have hx : x ≠ 0 := ne_of_gt (oneArmShiftedSelectionGrid_pos hκ hκ1 hD i)
  rw [finiteGridBasisEval_apply, oneArmShiftedSelectionBasis_sum_eq]
  have hpoly := congrArg (fun Q : Polynomial ℝ => Q.eval x)
    (oneArmPolynomial_eq_constant_add_X_mul_divPolynomial D P hdeg)
  simp only [Polynomial.eval_add, Polynomial.eval_C, Polynomial.eval_mul,
    Polynomial.eval_X] at hpoly
  dsimp [oneArmPolynomialDivCoeff]
  change P.coeff 0 / x +
      (oneArmSelectionPolynomial D (oneArmPolynomialDivCoeff D P)).eval x =
    P.eval x / x
  field_simp [hx]
  nlinarith [hpoly]

/-- Matching the shifted reciprocal-monomial basis matches every rational
triple test generated by the inverse tilt. -/
lemma oneArmShiftedSelection_moment_matching_tripleTest
    {D : ℕ} (hD : 1 ≤ D) {κ : ℝ} (hκ : 0 < κ) (hκ1 : κ ≤ 1)
    (omega0 omega1 : PMF (Fin (2 * D + 4)))
    (hmom : ∀ c,
      ∑ r, (omega0 r).toReal *
          finiteGridBasisEval (oneArmShiftedSelectionBasis κ D) c r =
        ∑ r, (omega1 r).toReal *
          finiteGridBasisEval (oneArmShiftedSelectionBasis κ D) c r)
    (i j k : ℕ) (hdegree : i + j + k ≤ D) :
    ∑ r, (omega0 r).toReal *
        (oneArmShiftedSelectionGrid κ D r ^ (i + k) *
          (oneArmShiftedSelectionGrid κ D r + oneArmShiftedPoleScale κ D) ^ j /
            oneArmShiftedSelectionGrid κ D r) =
      ∑ r, (omega1 r).toReal *
        (oneArmShiftedSelectionGrid κ D r ^ (i + k) *
          (oneArmShiftedSelectionGrid κ D r + oneArmShiftedPoleScale κ D) ^ j /
            oneArmShiftedSelectionGrid κ D r) := by
  let P : Polynomial ℝ := Polynomial.X ^ (i + k) *
    (Polynomial.X + Polynomial.C (oneArmShiftedPoleScale κ D)) ^ j
  have hPdeg : P.natDegree ≤ D := by
    calc
      P.natDegree ≤ (i + k) + j := by
        dsimp [P]
        calc
          _ ≤ (Polynomial.X ^ (i + k)).natDegree +
              ((Polynomial.X + Polynomial.C (oneArmShiftedPoleScale κ D)) ^ j).natDegree :=
            Polynomial.natDegree_mul_le
          _ ≤ (i + k) + j := by
            gcongr
            · simp
            · exact Polynomial.natDegree_pow_le.trans (by
                calc
                  j * (Polynomial.X + Polynomial.C
                    (oneArmShiftedPoleScale κ D)).natDegree ≤ j * 1 := by
                      gcongr
                      exact (Polynomial.natDegree_add_le _ _).trans (by simp)
                  _ = j := Nat.mul_one j)
      _ ≤ D := by omega
  have h := hmom (oneArmPolynomialDivCoeff D P)
  simpa only [oneArmShiftedSelectionBasis_represents_polynomial_div
      hD hκ hκ1 P hPdeg, P, Polynomial.eval_mul, Polynomial.eval_pow,
    Polynomial.eval_X, Polynomial.eval_add, Polynomial.eval_C] using h

/-- Shifted-grid basis matching transports through inverse tilting to every
raw observable moment through degree `D`. -/
lemma oneArmShiftedSelection_inverseTilt_liftedRawMoment_eq
    {D : ℕ} (hD : 1 ≤ D) {κ : ℝ} (hκ : 0 < κ) (hκ1 : κ ≤ 1)
    (omega0 omega1 : PMF (Fin (2 * D + 4)))
    (hmom : ∀ c,
      ∑ r, (omega0 r).toReal *
          finiteGridBasisEval (oneArmShiftedSelectionBasis κ D) c r =
        ∑ r, (omega1 r).toReal *
          finiteGridBasisEval (oneArmShiftedSelectionBasis κ D) c r)
    (scale epsilon : ℝ) (i j k : ℕ) (hdegree : i + j + k ≤ D) :
    ∑ z, (inverseTiltPMF omega0 (oneArmShiftedSelectionGrid κ D)
          (oneArmShiftedPoleScale κ D)
          (oneArmShiftedSelectionGrid_inverseTiltWeight_nonneg D hκ hκ1 hD omega0) z).toReal *
        (liftedCellMass scale (oneArmShiftedSelectionGrid κ D) z ^ i *
          (liftedCellMass scale (oneArmShiftedSelectionGrid κ D) z *
            liftedPropensity epsilon (oneArmShiftedPoleScale κ D)
              (oneArmShiftedSelectionGrid κ D) z) ^ j *
          (liftedCellMass scale (oneArmShiftedSelectionGrid κ D) z *
            liftedPropensity epsilon (oneArmShiftedPoleScale κ D)
              (oneArmShiftedSelectionGrid κ D) z *
            liftedOutcomeMean (oneArmShiftedPoleScale κ D)
              (oneArmShiftedSelectionGrid κ D) z) ^ k) =
      ∑ z, (inverseTiltPMF omega1 (oneArmShiftedSelectionGrid κ D)
          (oneArmShiftedPoleScale κ D)
          (oneArmShiftedSelectionGrid_inverseTiltWeight_nonneg D hκ hκ1 hD omega1) z).toReal *
        (liftedCellMass scale (oneArmShiftedSelectionGrid κ D) z ^ i *
          (liftedCellMass scale (oneArmShiftedSelectionGrid κ D) z *
            liftedPropensity epsilon (oneArmShiftedPoleScale κ D)
              (oneArmShiftedSelectionGrid κ D) z) ^ j *
          (liftedCellMass scale (oneArmShiftedSelectionGrid κ D) z *
            liftedPropensity epsilon (oneArmShiftedPoleScale κ D)
              (oneArmShiftedSelectionGrid κ D) z *
            liftedOutcomeMean (oneArmShiftedPoleScale κ D)
              (oneArmShiftedSelectionGrid κ D) z) ^ k) := by
  apply inverseTilt_liftedRawMoment_eq omega0 omega1
    (oneArmShiftedSelectionGrid κ D)
    (oneArmShiftedSelectionGrid_inverseTiltWeight_nonneg D hκ hκ1 hD omega0)
    (oneArmShiftedSelectionGrid_inverseTiltWeight_nonneg D hκ hκ1 hD omega1)
    (fun r => ne_of_gt (oneArmShiftedSelectionGrid_pos hκ hκ1 hD r))
    (fun r => by
      have hx := oneArmShiftedSelectionGrid_pos hκ hκ1 hD r
      have hb := oneArmShiftedPoleScale_pos hκ hD
      nlinarith) D
  · intro i' j' k' hpos hdeg
    exact oneArmShiftedSelection_moment_matching_tripleTest hD hκ hκ1
      omega0 omega1 hmom i' j' k' hdeg
  · exact hdegree

/-- The approximation target gap becomes exactly `scale · bκ` times the
lifted treated-functional expectation gap. -/
lemma inverseTilt_shifted_liftedFunctional_sum
    {D : ℕ} {κ : ℝ} (hκ : 0 < κ) (hκ1 : κ ≤ 1) (hD : 1 ≤ D)
    (ω : PMF (Fin (2 * D + 4))) (scale : ℝ) :
    ∑ z, (inverseTiltPMF ω (oneArmShiftedSelectionGrid κ D)
          (oneArmShiftedPoleScale κ D)
          (oneArmShiftedSelectionGrid_inverseTiltWeight_nonneg D hκ hκ1 hD ω) z).toReal *
        (liftedCellMass scale (oneArmShiftedSelectionGrid κ D) z *
          liftedOutcomeMean (oneArmShiftedPoleScale κ D)
            (oneArmShiftedSelectionGrid κ D) z) =
      scale * oneArmShiftedPoleScale κ D *
        ∑ r, (ω r).toReal * oneArmShiftedSelectionTarget κ D r := by
  rw [inverseTiltPMF_sum_of_none_eq_zero]
  · rw [Finset.mul_sum]
    apply Finset.sum_congr rfl
    intro r _
    simp only [inverseTiltWeight, liftedCellMass, liftedOutcomeMean,
      oneArmShiftedSelectionTarget]
    have hxpos := oneArmShiftedSelectionGrid_pos hκ hκ1 hD r
    have hx := ne_of_gt hxpos
    have hbpos := oneArmShiftedPoleScale_pos hκ hD
    have hxb : oneArmShiftedSelectionGrid κ D r +
        oneArmShiftedPoleScale κ D ≠ 0 := ne_of_gt (add_pos hxpos hbpos)
    field_simp [hx, hxb]
  · simp [liftedCellMass]

/-- A Jordan target separation on the shifted grid transfers to a positive
inverse-tilted functional separation. -/
lemma inverseTilt_shifted_liftedFunctional_gap
    {D : ℕ} {κ scale gap : ℝ} (hκ : 0 < κ) (hκ1 : κ ≤ 1) (hD : 1 ≤ D)
    (hscale : 0 ≤ scale) (omega0 omega1 : PMF (Fin (2 * D + 4)))
    (hgap : gap ≤
      (∑ r, (omega0 r).toReal * oneArmShiftedSelectionTarget κ D r) -
        ∑ r, (omega1 r).toReal * oneArmShiftedSelectionTarget κ D r) :
    scale * oneArmShiftedPoleScale κ D * gap ≤
      (∑ z, (inverseTiltPMF omega0 (oneArmShiftedSelectionGrid κ D)
          (oneArmShiftedPoleScale κ D)
          (oneArmShiftedSelectionGrid_inverseTiltWeight_nonneg D hκ hκ1 hD omega0) z).toReal *
        (liftedCellMass scale (oneArmShiftedSelectionGrid κ D) z *
          liftedOutcomeMean (oneArmShiftedPoleScale κ D)
            (oneArmShiftedSelectionGrid κ D) z)) -
      ∑ z, (inverseTiltPMF omega1 (oneArmShiftedSelectionGrid κ D)
          (oneArmShiftedPoleScale κ D)
          (oneArmShiftedSelectionGrid_inverseTiltWeight_nonneg D hκ hκ1 hD omega1) z).toReal *
        (liftedCellMass scale (oneArmShiftedSelectionGrid κ D) z *
          liftedOutcomeMean (oneArmShiftedPoleScale κ D)
            (oneArmShiftedSelectionGrid κ D) z) := by
  rw [inverseTilt_shifted_liftedFunctional_sum hκ hκ1 hD,
    inverseTilt_shifted_liftedFunctional_sum hκ hκ1 hD]
  have h := mul_le_mul_of_nonneg_left hgap
    (mul_nonneg hscale (oneArmShiftedPoleScale_pos hκ hD).le)
  nlinarith

end CausalSmith.Stat.DiscreteAteMinimaxLoggap
