module
public import CausalSmith.Stat.STAT_MarNearcompleteFrontier_Research.Helpers.Converse.Interpolation
public import CausalSmith.Stat.STAT_MarNearcompleteFrontier_Research.Helpers.Converse.PairTV
public import CausalSmith.Stat.STAT_MarNearcompleteFrontier_Research.Helpers.LowerBound.NormalizedScale
public import Causalean.Stat.Concentration.Poisson.SelfNormalized.Chernoff
public import Causalean.Stat.Minimax.Mixture.MomentMatched.ExponentialEnergy
public import Causalean.Stat.Minimax.TotalVariation
public import Mathlib.Data.List.Nodup
public import Mathlib.MeasureTheory.Measure.Dirac
public import Causalean.Stat.Concentration.Poisson.Threshold

/-! # Basic for the paired count-mixture comparison -/

public section

namespace CausalSmith.Stat.MarNearcompleteFrontier

open Causalean.Stat.Concentration.Poisson

open Causalean.Stat

open MeasureTheory ProbabilityTheory
open scoped ENNReal NNReal




-- @node: normalizationJ_ge_half
/-- The random count normalizer is uniformly at least one half. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `hn`](hyp:hn), [the stated mathematical conclusion holds](goal). Given [the specified input `θ`](hyp:θ). -/
lemma normalizationJ_ge_half (n d : ℕ) (θ : Theta n d) (hn : 1 ≤ n) :
    (1 / 2 : ℝ) ≤ normalizationJ n d θ := by
  have hnpos : (0 : ℝ) < n := by exact_mod_cast hn
  have hL := ell_pos_for_normalization n
  have hK := priorK_lower_for_normalization n
  have hKpos : (0 : ℝ) < priorK n := by linarith
  have hM : (pairCount n d : ℝ) ≤ (n : ℝ) * ell n := by
    have hm : pairCount n d ≤ Nat.floor ((n : ℝ) * ell n) := by
      unfold pairCount
      exact min_le_right _ _
    have hf : ((Nat.floor ((n : ℝ) * ell n) : ℕ) : ℝ) ≤
        (n : ℝ) * ell n := Nat.floor_le (le_of_lt (mul_pos hnpos hL))
    exact (Nat.cast_le.mpr hm).trans hf
  have hbound : 8 * (pairCount n d : ℝ) ≤ (n : ℝ) * priorK n := by
    nlinarith [mul_nonneg (le_of_lt hnpos) (sub_nonneg.mpr hK)]
  have hrewrite :
      2 * (pairCount n d : ℝ) * priorH n * priorB n =
        (pairCount n d : ℝ) / (512 * n * priorK n) := by
    unfold priorH priorB
    field_simp
    <;> ring
  have hsmall : (pairCount n d : ℝ) / (512 * n * priorK n) ≤ 1 / 2 := by
    apply (div_le_iff₀ (by positivity)).2
    nlinarith
  have hsum : 0 ≤ ∑ j : Fin (pairCount n d), latentP n (θ.1 j) := by
    exact Finset.sum_nonneg fun j _ => latentP_nonneg n (θ.1 j)
  unfold normalizationJ fillerMass
  rw [hrewrite]
  linarith


-- @node: normalization_count_poisson_tail
/-- The conditional total-count Poisson rate generated by the paired prior has
a uniformly small lower tail. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `hn`](hyp:hn), [the stated mathematical conclusion holds](goal). Given [the specified input `θ`](hyp:θ). -/
lemma normalization_count_poisson_tail (n d : ℕ) (θ : Theta n d)
    (hn : 1 ≤ n) :
    (poissonMeasure
      (Real.toNNReal (4 * (n : ℝ) * normalizationJ n d θ))
      (Set.Iio n)).toReal ≤ 8 / (n : ℝ) := by
  apply poisson_lower_tail_of_two_mul_le n _ hn
  have hJ := normalizationJ_ge_half n d θ hn
  have hx0 : 0 ≤ 4 * (n : ℝ) * normalizationJ n d θ := by
    have : 0 ≤ normalizationJ n d θ := le_trans (by norm_num) hJ
    positivity
  rw [Real.coe_toNNReal _ hx0]
  nlinarith

-- @node: normalization_count_poisson_tail_eventual
/-- Uniformly over every latent parameter and dimension, the conditional
short-count probability is eventually below any positive tolerance. [the stated mathematical conclusion holds](goal). Given [the specified input `β`](hyp:β), [the specified input `hβ`](hyp:hβ). -/
lemma normalization_count_poisson_tail_eventual (β : ℝ) (hβ : 0 < β) :
    ∃ N : ℕ, 1 ≤ N ∧ ∀ (n d : ℕ), N ≤ n → ∀ θ : Theta n d,
      (poissonMeasure
        (Real.toNNReal (4 * (n : ℝ) * normalizationJ n d θ))
        (Set.Iio n)).toReal ≤ β := by
  obtain ⟨N₀, hN₀⟩ := exists_nat_gt (8 / β)
  refine ⟨max N₀ 1, le_max_right _ _, ?_⟩
  intro n d hn θ
  have hn1 : 1 ≤ n := le_trans (le_max_right _ _) hn
  have hnN : N₀ ≤ n := le_trans (le_max_left _ _) hn
  have hnR : 8 / β < (n : ℝ) := lt_of_lt_of_le hN₀ (by exact_mod_cast hnN)
  calc
    _ ≤ 8 / (n : ℝ) := normalization_count_poisson_tail n d θ hn1
    _ ≤ β := by
      apply (div_le_iff₀ (by positivity : (0 : ℝ) < n)).2
      have := (div_lt_iff₀ hβ).1 hnR
      nlinarith

-- @node: thetaLaw_normalization_count_poisson_tail
/-- Averaging over the latent prior preserves the uniform `8 / n` short-count
bound required by random-scale transfer. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `hn`](hyp:hn), [the specified input `hd`](hyp:hd), [the stated mathematical conclusion holds](goal). Given [the specified input `hq`](hyp:hq). -/
lemma thetaLaw_normalization_count_poisson_tail (n d : ℕ) (q : ℝ)
    (hn : 1 ≤ n) (hd : 1 ≤ d) (hq : q ∈ Set.Icc ((1 : ℝ) / 2) 1) :
    (∫ θ,
      (poissonMeasure
        (Real.toNNReal (4 * (n : ℝ) * normalizationJ n d θ))
        (Set.Iio n)).toReal
      ∂(thetaLaw n d q hn hd hq).toMeasure) ≤ 8 / (n : ℝ) := by
  letI : IsProbabilityMeasure (thetaLaw n d q hn hd hq).toMeasure := inferInstance
  calc
    _ ≤ ∫ _θ : Theta n d, 8 / (n : ℝ)
        ∂(thetaLaw n d q hn hd hq).toMeasure :=
      integral_mono_of_nonneg
        (Filter.Eventually.of_forall fun _ => ENNReal.toReal_nonneg)
        (integrable_const _)
        (Filter.Eventually.of_forall fun θ =>
          normalization_count_poisson_tail n d θ hn)
    _ = _ := by simp

private def obsTupleEquiv (d : ℕ) :
    Obs d ≃ Fin d × Bool × Bool × Bool × Bool where
  toFun o := (o.X, o.A, o.S, o.R, o.RY)
  invFun t := ⟨t.1, t.2.1, t.2.2.1, t.2.2.2.1, t.2.2.2.2⟩
  left_inv := by intro o; rcases o with ⟨x, a, s, r, ry⟩; rfl
  right_inv := by intro t; rcases t with ⟨x, a, s, r, ry⟩; rfl

-- @node: sum_fillerObservedCoeff_at_label
/-- At any fixed baseline label, the filler observed coefficients have total
mass one. Given [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `x`](hyp:x), [the stated mathematical conclusion holds](goal). -/
lemma sum_fillerObservedCoeff_at_label (d : ℕ) (q : ℝ) (x : Fin d) :
    (∑ o : Obs d, if o.X = x then fillerObservedCoeff q o else 0) = 1 := by
  rw [Fintype.sum_equiv (obsTupleEquiv d)
    (fun o => if o.X = x then fillerObservedCoeff q o else 0)
    (fun t => if ((obsTupleEquiv d).symm t).X = x then
      fillerObservedCoeff q ((obsTupleEquiv d).symm t) else 0)
    (by intro o; simp)]
  simp only [Fintype.sum_prod_type]
  simp [obsTupleEquiv, fillerObservedCoeff]
  ring

-- @node: sum_pairObservedCoeff_at_label
/-- At any fixed baseline label, each oriented pair's observed coefficients
have total mass one. Given [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `z`](hyp:z), [the specified input `u`](hyp:u), [the specified input `x`](hyp:x), [the stated mathematical conclusion holds](goal). Given [the specified input `σ`](hyp:σ). -/
lemma sum_pairObservedCoeff_at_label (d : ℕ) (q σ z u : ℝ) (x : Fin d) :
    (∑ o : Obs d, if o.X = x then pairObservedCoeff q σ z u o else 0) = 1 := by
  rw [Fintype.sum_equiv (obsTupleEquiv d)
    (fun o => if o.X = x then pairObservedCoeff q σ z u o else 0)
    (fun t => if ((obsTupleEquiv d).symm t).X = x then
      pairObservedCoeff q σ z u ((obsTupleEquiv d).symm t) else 0)
    (by intro o; simp)]
  simp only [Fintype.sum_prod_type]
  simp [obsTupleEquiv, pairObservedCoeff]
  ring

-- @node: countAtomMass_sum
/-- The unnormalized count-cell intensities sum exactly to the random
normalizer, independently of the sign parameter. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `hd`](hyp:hd), [the stated mathematical conclusion holds](goal). Given [the specified input `σ`](hyp:σ), [the specified input `θ`](hyp:θ). -/
lemma countAtomMass_sum (n d : ℕ) (q σ : ℝ) (hd : 1 ≤ d)
    (θ : Theta n d) :
    (∑ o : Obs d, countAtomMass n d q σ hd θ o) = normalizationJ n d θ := by
  classical
  have hfiller :
      (∑ o : Obs d, if o.X = fillerLabel d hd then
        fillerMass n d * fillerObservedCoeff q o else 0) = fillerMass n d := by
    calc
      _ = fillerMass n d *
          (∑ o : Obs d, if o.X = fillerLabel d hd then
            fillerObservedCoeff q o else 0) := by
        rw [Finset.mul_sum]
        apply Finset.sum_congr rfl
        intro o _
        split_ifs <;> ring
      _ = _ := by rw [sum_fillerObservedCoeff_at_label]; ring
  have hpair (j : Fin (pairCount n d)) (side : Bool) :
      (∑ o : Obs d, if o.X = pairLabel n d hd j side then
        latentP n (θ.1 j) * pairObservedCoeff q σ (latentZ n (θ.1 j))
          (orientation θ j side) o else 0) = latentP n (θ.1 j) := by
    calc
      _ = latentP n (θ.1 j) *
          (∑ o : Obs d, if o.X = pairLabel n d hd j side then
            pairObservedCoeff q σ (latentZ n (θ.1 j))
              (orientation θ j side) o else 0) := by
        rw [Finset.mul_sum]
        apply Finset.sum_congr rfl
        intro o _
        split_ifs <;> ring
      _ = _ := by rw [sum_pairObservedCoeff_at_label]; ring
  unfold countAtomMass normalizationJ
  rw [Finset.sum_add_distrib, hfiller]
  have hreorder :
      (∑ o : Obs d, ∑ j : Fin (pairCount n d), ∑ side : Bool,
        if o.X = pairLabel n d hd j side then
          latentP n (θ.1 j) * pairObservedCoeff q σ (latentZ n (θ.1 j))
            (orientation θ j side) o else 0) =
      ∑ j : Fin (pairCount n d), ∑ side : Bool, ∑ o : Obs d,
        if o.X = pairLabel n d hd j side then
          latentP n (θ.1 j) * pairObservedCoeff q σ (latentZ n (θ.1 j))
            (orientation θ j side) o else 0 := by
    rw [Finset.sum_comm]
    apply Finset.sum_congr rfl
    intro j _
    rw [Finset.sum_comm]
  rw [hreorder]
  simp_rw [hpair]
  simp
  rw [Finset.mul_sum]

-- @node: pairObservedCoeff_sign_flip
/-- Flipping the experiment sign is exactly the same as flipping the latent
sign in every oriented pair coefficient. Given [the specified input `q`](hyp:q), [the specified input `z`](hyp:z), [the specified input `u`](hyp:u), [the specified input `o`](hyp:o), [the stated mathematical conclusion holds](goal). -/
lemma pairObservedCoeff_sign_flip (q z u : ℝ) (o : Obs d) :
    pairObservedCoeff q (-1) z u o = pairObservedCoeff q 1 (-z) u o := by
  simp only [pairObservedCoeff]
  split_ifs <;> ring

-- @node: pairObservedCoeff_orientation_linear_cancel
/-- After averaging the two opposite orientations, every degree-one observed
coefficient is independent of the experiment sign. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `z`](hyp:z), [the specified input `o`](hyp:o), [the stated mathematical conclusion holds](goal). Given [the specified input `θ`](hyp:θ). Given [the specified input `j`](hyp:j). -/
lemma pairObservedCoeff_orientation_linear_cancel (n d : ℕ) (q z : ℝ)
    (θ : Theta n d) (j : Fin (pairCount n d)) (o : Obs d) :
    (∑ side : Bool,
      pairObservedCoeff q (-1) z (orientation θ j side) o) =
    ∑ side : Bool,
      pairObservedCoeff q 1 z (orientation θ j side) o := by
  cases hside : θ.2 j <;>
    simp [orientation, hside, pairObservedCoeff] <;> split_ifs <;> ring

-- @node: pairObservedCoeff_bool_orientation_linear_cancel
/-- Explicit averaging over the base orientation removes every degree-one
experiment-sign dependence. Given [the specified input `q`](hyp:q), [the specified input `z`](hyp:z), [the specified input `target`](hyp:target), [the specified input `o`](hyp:o), [the stated mathematical conclusion holds](goal). -/
lemma pairObservedCoeff_bool_orientation_linear_cancel (q z : ℝ)
    (target : Bool) (o : Obs d) :
    (∑ base : Bool,
      pairObservedCoeff q (-1) z (if base == target then 1 else -1) o) =
    ∑ base : Bool,
      pairObservedCoeff q 1 z (if base == target then 1 else -1) o := by
  cases target <;>
    simp [pairObservedCoeff] <;> split_ifs <;> ring

-- @node: pairObservedCoeff_orientation_square_gap
/-- At the treated observed-failure mark, the orientation-averaged quadratic
coefficient has a nonzero signed-latent gap. This is the first term for which
moment cancellation is needed. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `z`](hyp:z), [the specified input `o`](hyp:o), [the specified input `hA`](hyp:hA), [the specified input `hS`](hyp:hS), [the specified input `hR`](hyp:hR), [the specified input `hRY`](hyp:hRY), [the stated mathematical conclusion holds](goal). Given [the specified input `θ`](hyp:θ). Given [the specified input `j`](hyp:j). -/
lemma pairObservedCoeff_orientation_square_gap (n d : ℕ) (q z : ℝ)
    (θ : Theta n d) (j : Fin (pairCount n d)) (o : Obs d)
    (hA : o.A = true) (hS : o.S = false) (hR : o.R = true)
    (hRY : o.RY = false) :
    (∑ side : Bool,
      pairObservedCoeff q (-1) z (orientation θ j side) o ^ 2) -
      (∑ side : Bool,
        pairObservedCoeff q 1 z (orientation θ j side) o ^ 2) =
      -delta q * z / 16 := by
  cases hside : θ.2 j <;>
    simp [orientation, hside, pairObservedCoeff, hA, hS, hR, hRY] <;> ring

-- @node: pairObservedCoeff_le_one
/-- Every legal oriented-pair observed coefficient is at most one. Given [the specified input `q`](hyp:q), [the specified input `z`](hyp:z), [the specified input `u`](hyp:u), [the specified input `o`](hyp:o), [the specified input `hz`](hyp:hz), [the specified input `hu`](hyp:hu), [the stated mathematical conclusion holds](goal). Given [the specified input `σ`](hyp:σ), [the specified input `hσ`](hyp:hσ). Given [the specified input `hq`](hyp:hq). -/
lemma pairObservedCoeff_le_one (q σ z u : ℝ) (o : Obs d)
    (hq : q ∈ Set.Icc ((1 : ℝ) / 2) 1)
    (hσ : σ = -1 ∨ σ = 1) (hz : z = -1 ∨ z = 1)
    (hu : u = -1 ∨ u = 1) :
    pairObservedCoeff q σ z u o ≤ 1 := by
  have hdlo : 0 ≤ delta q := by unfold delta; linarith [hq.2]
  have hdhi : delta q ≤ 1 / 2 := by unfold delta; linarith [hq.1]
  rcases hσ with rfl | rfl <;> rcases hz with rfl | rfl <;>
    rcases hu with rfl | rfl
  all_goals simp only [pairObservedCoeff] <;> split_ifs <;> norm_num <;> linarith

-- @node: conditionalCountLaw_singleton_product
/-- The singleton likelihood of a conditional count vector is the finite
product of its scalar Poisson probabilities. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `hd`](hyp:hd), [the specified input `counts`](hyp:counts), [the stated mathematical conclusion holds](goal). Given [the specified input `σ`](hyp:σ), [the specified input `θ`](hyp:θ). -/
lemma conditionalCountLaw_singleton_product (n d : ℕ) (q σ : ℝ) (hd : 1 ≤ d)
    (θ : Theta n d) (counts : Obs d → ℕ) :
    (conditionalCountLaw n d q σ hd θ).real {counts} =
      ∏ o : Obs d,
        Real.exp (-(Real.toNNReal
          (4 * (n : ℝ) * countAtomMass n d q σ hd θ o) : ℝ)) *
        (Real.toNNReal
          (4 * (n : ℝ) * countAtomMass n d q σ hd θ o) : ℝ) ^ counts o /
        (counts o).factorial := by
  unfold conditionalCountLaw
  rw [Measure.real_def, Measure.pi_singleton, ENNReal.toReal_prod]
  apply Finset.prod_congr rfl
  intro o _
  rw [poissonMeasure_singleton, ENNReal.toReal_ofReal]
  positivity

-- @node: conditionalCountLaw_singleton_likelihood
/-- In the legal sign regime, the conditional count-vector likelihood has one
shared exponential factor determined by `normalizationJ`. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `hn`](hyp:hn), [the specified input `hd`](hyp:hd), [the specified input `counts`](hyp:counts), [the stated mathematical conclusion holds](goal). Given [the specified input `σ`](hyp:σ), [the specified input `hσ`](hyp:hσ), [the specified input `θ`](hyp:θ). Given [the specified input `hq`](hyp:hq). -/
lemma conditionalCountLaw_singleton_likelihood (n d : ℕ) (q σ : ℝ)
    (hn : 1 ≤ n) (hd : 1 ≤ d) (hq : q ∈ Set.Icc ((1 : ℝ) / 2) 1)
    (hσ : σ = -1 ∨ σ = 1) (θ : Theta n d) (counts : Obs d → ℕ) :
    (conditionalCountLaw n d q σ hd θ).real {counts} =
      Real.exp (-4 * (n : ℝ) * normalizationJ n d θ) *
        ∏ o : Obs d,
          (4 * (n : ℝ) * countAtomMass n d q σ hd θ o) ^ counts o /
            (counts o).factorial := by
  rw [conditionalCountLaw_singleton_product n d q σ hd θ counts]
  have hmass (o : Obs d) :
      0 ≤ 4 * (n : ℝ) * countAtomMass n d q σ hd θ o :=
    mul_nonneg (mul_nonneg (by norm_num) (Nat.cast_nonneg _))
      (countAtomMass_nonneg n d q σ hn hd hq θ o hσ)
  simp_rw [Real.coe_toNNReal _ (hmass _)]
  rw [show (∏ o : Obs d,
      Real.exp (-(4 * (n : ℝ) * countAtomMass n d q σ hd θ o)) *
        (4 * (n : ℝ) * countAtomMass n d q σ hd θ o) ^ counts o /
          (counts o).factorial) =
      ∏ o : Obs d,
        Real.exp (-(4 * (n : ℝ) * countAtomMass n d q σ hd θ o)) *
          ((4 * (n : ℝ) * countAtomMass n d q σ hd θ o) ^ counts o /
            (counts o).factorial) by
    apply Finset.prod_congr rfl
    intro o _
    ring]
  rw [Finset.prod_mul_distrib, ← Real.exp_sum]
  rw [show (∑ o : Obs d,
      -(4 * (n : ℝ) * countAtomMass n d q σ hd θ o)) =
      -4 * (n : ℝ) * normalizationJ n d θ by
    rw [show (fun o : Obs d =>
        -(4 * (n : ℝ) * countAtomMass n d q σ hd θ o)) =
      fun o => (-4 * (n : ℝ)) * countAtomMass n d q σ hd θ o by
        funext o
        ring,
      ← Finset.mul_sum, countAtomMass_sum]]

-- @node: mixedCountLaw_singleton_likelihood
/-- The mixed count-vector likelihood is the finite latent average of the
conditional product likelihood, with a sign-independent exponential factor. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `hn`](hyp:hn), [the specified input `hd`](hyp:hd), [the specified input `counts`](hyp:counts), [the stated mathematical conclusion holds](goal). Given [the specified input `σ`](hyp:σ), [the specified input `hσ`](hyp:hσ). Given [the specified input `hq`](hyp:hq). -/
lemma mixedCountLaw_singleton_likelihood (n d : ℕ) (q σ : ℝ)
    (hn : 1 ≤ n) (hd : 1 ≤ d) (hq : q ∈ Set.Icc ((1 : ℝ) / 2) 1)
    (hσ : σ = -1 ∨ σ = 1) (counts : Obs d → ℕ) :
    (mixedCountLaw n d q σ hn hd hq).real {counts} =
      ∑ θ : Theta n d,
        (thetaLaw n d q hn hd hq θ).toReal *
          (Real.exp (-4 * (n : ℝ) * normalizationJ n d θ) *
            ∏ o : Obs d,
              (4 * (n : ℝ) * countAtomMass n d q σ hd θ o) ^ counts o /
                (counts o).factorial) := by
  unfold mixedCountLaw
  rw [Measure.real, Measure.coe_finsetSum, Finset.sum_apply, ENNReal.toReal_sum]
  · apply Finset.sum_congr rfl
    intro θ _
    rw [Measure.smul_apply, smul_eq_mul, ENNReal.toReal_mul]
    congr 1
    exact conditionalCountLaw_singleton_likelihood
      n d q σ hn hd hq hσ θ counts
  · intro θ _
    apply ENNReal.mul_ne_top (PMF.apply_ne_top _ _)
    letI : IsProbabilityMeasure (conditionalCountLaw n d q σ hd θ) := by
      unfold conditionalCountLaw
      infer_instance
    exact measure_ne_top _ _

-- @node: countAtomMass_at_pair_label
/-- At a paired baseline label, exactly one pair component contributes to the
unnormalized observed-atom mass. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `hd`](hyp:hd), [the specified input `o`](hyp:o), [the specified input `side`](hyp:side), [the specified input `ho`](hyp:ho), [the stated mathematical conclusion holds](goal). Given [the specified input `σ`](hyp:σ), [the specified input `θ`](hyp:θ). Given [the specified input `j`](hyp:j). -/
lemma countAtomMass_at_pair_label (n d : ℕ) (q σ : ℝ) (hd : 1 ≤ d)
    (θ : Theta n d) (o : Obs d) (j : Fin (pairCount n d)) (side : Bool)
    (ho : o.X = pairLabel n d hd j side) :
    countAtomMass n d q σ hd θ o =
      latentP n (θ.1 j) * pairObservedCoeff q σ (latentZ n (θ.1 j))
        (orientation θ j side) o := by
  unfold countAtomMass
  have hfiller : o.X ≠ fillerLabel d hd := by
    rw [ho]
    exact (fillerLabel_ne_pairLabel n d hd j side).symm
  rw [if_neg hfiller]
  simp only [zero_add]
  rw [Finset.sum_eq_single j]
  · rw [Finset.sum_eq_single side]
    · rw [if_pos ho]
    · intro side' _ hside'
      rw [if_neg]
      intro hlabel
      exact hside' (pairLabel_injective n d hd j j side' side
        (hlabel.symm.trans ho)).2
    · simp
  · intro k _ hkj
    apply Finset.sum_eq_zero
    intro side' _
    rw [if_neg]
    intro hlabel
    exact hkj (pairLabel_injective n d hd k j side' side
      (hlabel.symm.trans ho)).1
  · simp

-- @node: countAtomMass_at_filler_label
/-- At the filler baseline label, every paired component vanishes. Given [the specified input `n`](hyp:n), [the specified input `d`](hyp:d), [the specified input `q`](hyp:q), [the specified input `hd`](hyp:hd), [the specified input `o`](hyp:o), [the specified input `ho`](hyp:ho), [the stated mathematical conclusion holds](goal). Given [the specified input `σ`](hyp:σ), [the specified input `θ`](hyp:θ). -/
lemma countAtomMass_at_filler_label (n d : ℕ) (q σ : ℝ) (hd : 1 ≤ d)
    (θ : Theta n d) (o : Obs d) (ho : o.X = fillerLabel d hd) :
    countAtomMass n d q σ hd θ o =
      fillerMass n d * fillerObservedCoeff q o := by
  unfold countAtomMass
  rw [if_pos ho]
  suffices (∑ j : Fin (pairCount n d), ∑ side : Bool,
      if o.X = pairLabel n d hd j side then
        latentP n (θ.1 j) * pairObservedCoeff q σ (latentZ n (θ.1 j))
          (orientation θ j side) o else 0) = 0 by linarith
  apply Finset.sum_eq_zero
  intro j _
  apply Finset.sum_eq_zero
  intro side _
  rw [if_neg]
  rw [ho]
  exact fillerLabel_ne_pairLabel n d hd j side

-- @node: prod_by_observed_label
/-- A finite product over observed atoms factors into products over baseline
labels. Given [the specified input `f`](hyp:f), [the stated mathematical conclusion holds](goal). -/
lemma prod_by_observed_label (f : Obs d → ℝ) :
    (∏ o : Obs d, f o) =
      ∏ x : Fin d, ∏ o : Obs d, if o.X = x then f o else 1 := by
  classical
  symm
  calc
    _ = ∏ x : Fin d, ∏ o ∈ (Finset.univ : Finset (Obs d)) with o.X = x, f o := by
      apply Finset.prod_congr rfl
      intro x _
      simpa using (Finset.prod_filter (s := (Finset.univ : Finset (Obs d)))
        (fun o : Obs d => o.X = x) f).symm
    _ = ∏ o ∈ (Finset.univ : Finset (Obs d)), f o :=
      Finset.prod_fiberwise (Finset.univ : Finset (Obs d)) (fun o => o.X) f
    _ = _ := by simp


end CausalSmith.Stat.MarNearcompleteFrontier
