import Mathlib.Analysis.Convex.StdSimplex
import Mathlib.MeasureTheory.Integral.Bochner.Basic
import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
import Mathlib.Probability.Independence.Basic
import Mathlib.Probability.Kernel.CondDistrib
import Causalean.Stat.Sample

/-!
# Finite-plate hierarchical SCM world

This file fixes the binary four-cell state space, the overlap-restricted simplex,
the causal functional, and the paper's six explicitly threaded model assumptions.
The SCM/PO substrate is deliberately bypassed because this model is a latent
mixture plate with no graph or intervention-regime index.
-/

namespace CausalSmith.SCM.FiniteplateBernsteinAteBounds

open MeasureTheory ProbabilityTheory
open scoped BigOperators ENNReal

/-- A cell is the observed treatment/outcome pair. -/
abbrev Cell := Bool × Bool

/-- A four-cell real vector. -/
abbrev CellLaw := Cell → ℝ -- @realizes q(carrier Δ₃ before simplex restriction)

/-- Treatment probability obtained by summing the two treated cells. -/
def treatmentProb (q : CellLaw) : ℝ :=
  q (true, false) + q (true, true) -- @realizes p(p(q)=q₁₀+q₁₁)

/-- The overlap-restricted four-cell simplex. -/
def overlapSimplex (ε : ℝ) : Set CellLaw :=
  {q | q ∈ stdSimplex ℝ Cell ∧
    ε ≤ treatmentProb q ∧ treatmentProb q ≤ 1 - ε}
  -- @realizes K_epsilon(q∈Δ₃ and ε≤p(q)≤1-ε)

lemma treatmentProb_mem_Icc (ε : ℝ) (q : CellLaw) (hq : q ∈ overlapSimplex ε) :
    treatmentProb q ∈ Set.Icc 0 1 := by
  sorry
  -- @realizes p(p(q)∈[0,1] on the simplex)

/-- The conditional binary-outcome contrast at a latent cell law. -/
noncomputable def causalIntegrand (q : CellLaw) : ℝ :=
  q (true, true) / treatmentProb q -
    q (false, true) / (1 - treatmentProb q)
  -- @realizes f(f(q)=q₁₁/p(q)-q₀₁/(1-p(q)))

/-- A probability measure supported on the overlap simplex. -/
def IsMixingLaw (ε : ℝ) (μ : Measure CellLaw) : Prop :=
  IsProbabilityMeasure μ ∧ μ (overlapSimplex ε)ᶜ = 0
  -- @realizes mu(probability measure supported on K_epsilon)

/-- The cluster-equally-weighted ATE functional. -/
noncomputable def ateFunctional (μ : Measure CellLaw) : ℝ :=
  ∫ q, causalIntegrand q ∂μ
  -- @realizes tau(tau(mu)=integral f dmu)

lemma causalIntegrand_mem_Icc (ε : ℝ) (q : CellLaw)
    (hq : q ∈ overlapSimplex ε) : causalIntegrand q ∈ Set.Icc (-1) 1 := by
  sorry
  -- @realizes f(f maps K_epsilon into [-1,1])

lemma ateFunctional_mem_Icc (ε : ℝ) (μ : Measure CellLaw)
    (hμ : IsMixingLaw ε μ) : ateFunctional μ ∈ Set.Icc (-1) 1 := by
  sorry
  -- @realizes tau(tau maps mixing laws into [-1,1])

/-- The finite set of bounded four-cell count vectors summing to the plate size. -/
def countIndexFinset (m : ℕ) : Finset (Cell → Fin (m + 1)) :=
  Finset.univ.filter (fun c => ∑ x, (c x).val = m)

/-- Count vectors whose four entries sum to the plate size. -/
abbrev CountIndex (m : ℕ) := {c // c ∈ countIndexFinset m}
  -- @realizes I_m(sum of four nonnegative counts equals m)

/-- A count vector exists for every plate size (put all mass in one cell). -/
lemma countIndex_nonempty (m : ℕ) : Nonempty (CountIndex m) := by
  sorry

noncomputable instance (m : ℕ) : Nonempty (CountIndex m) := countIndex_nonempty m

/-- The number of possible within-cluster count vectors. -/
noncomputable def countIndexCard (m : ℕ) : ℕ :=
  Fintype.card (CountIndex m) -- @realizes N_m(cardinality of I_m)

lemma countIndexCard_formula (m : ℕ) :
    countIndexCard m = Nat.choose (m + 3) 3 := by
  sorry
  -- @realizes N_m(N_m=choose(m+3,3))

/-- The observed pair generated by treatment and observed outcome. -/
def observedPair {Ω : Type*} {m n : ℕ}
    (A Y : Fin n → Fin m → Ω → Bool) (i : Fin n) (j : Fin m) (ω : Ω) : Cell :=
  (A i j ω, Y i j ω) -- @realizes O_ij(O_ij=(A_ij,Y_ij))

/-- The latent individual causal vector. -/
def causalVector {Ω : Type*} {m n : ℕ}
    (A Y0 Y1 : Fin n → Fin m → Ω → Bool)
    (i : Fin n) (j : Fin m) (ω : Ω) : Bool × Bool × Bool :=
  (A i j ω, Y0 i j ω, Y1 i j ω)

/-- Independent and identically distributed cluster-level latent/causal vectors. -/
-- @node: ass:clusters-iid
def IndependentClusterSampling {Ω : Type*} [MeasurableSpace Ω] {m n : ℕ}
    (P : Measure Ω) (Q : Fin n → Ω → CellLaw)
    (A Y0 Y1 : Fin n → Fin m → Ω → Bool) : Prop :=
  iIndepFun
      (fun i ω => (Q i ω, fun j => causalVector A Y0 Y1 i j ω)) P ∧
    ∀ i i', Measure.map
        (fun ω => (Q i ω, fun j => causalVector A Y0 Y1 i j ω)) P =
      Measure.map
        (fun ω => (Q i' ω, fun j => causalVector A Y0 Y1 i' j ω)) P

/-- Every latent environment has the common overlap-supported mixing law. -/
-- @node: ass:environment-law
def EnvironmentLaw {Ω : Type*} [MeasurableSpace Ω] {n : ℕ}
    (P : Measure Ω) (ε : ℝ) (μ : Measure CellLaw)
    (Q : Fin n → Ω → CellLaw) : Prop :=
  IsMixingLaw ε μ ∧ ∀ i, Measure.map (Q i) P = μ
  -- @realizes Q_i(common law supported on K_epsilon)

/-- Conditional on the latent law, individual causal vectors have a common
conditional marginal and their finite joint point probabilities factor. -/
-- @node: ass:conditional-iid-plate
def ConditionalIidPlate {Ω : Type*} [MeasurableSpace Ω] {m n : ℕ}
    (P : Measure Ω) [IsProbabilityMeasure P]
    (Q : Fin n → Ω → CellLaw)
    (A Y0 Y1 : Fin n → Fin m → Ω → Bool) : Prop :=
  (∀ i j j', condDistrib (causalVector A Y0 Y1 i j) (Q i) P =
      condDistrib (causalVector A Y0 Y1 i j') (Q i) P) ∧
  (∀ i (x : Fin m → Bool × Bool × Bool),
    ∀ᵐ q ∂Measure.map (Q i) P,
      condDistrib (fun ω j => causalVector A Y0 Y1 i j ω) (Q i) P q {x} =
        ∏ j, condDistrib (causalVector A Y0 Y1 i j) (Q i) P q {x j})

/-- The latent four-cell vector is the conditional law of the observed pair. -/
-- @node: ass:observed-cell-calibration
def ObservedCellCalibration {Ω : Type*} [MeasurableSpace Ω] {m n : ℕ}
    (P : Measure Ω) [IsProbabilityMeasure P]
    (Q : Fin n → Ω → CellLaw) (A Y : Fin n → Fin m → Ω → Bool) : Prop :=
  ∀ i j c, ∀ᵐ q ∂Measure.map (Q i) P,
    condDistrib (observedPair A Y i j) (Q i) P q {c} = ENNReal.ofReal (q c)

/-- Potential outcomes and treatment factor conditionally on the latent law. -/
-- @node: ass:latent-ignorability
def LatentIgnorability {Ω : Type*} [MeasurableSpace Ω] {m n : ℕ}
    (P : Measure Ω) [IsProbabilityMeasure P]
    (Q : Fin n → Ω → CellLaw)
    (A Y0 Y1 : Fin n → Fin m → Ω → Bool) : Prop :=
  ∀ i j (a : Bool) (y : Bool × Bool),
    ∀ᵐ q ∂Measure.map (Q i) P,
      condDistrib (fun ω => ((Y0 i j ω, Y1 i j ω), A i j ω)) (Q i) P q {(y, a)} =
        condDistrib (fun ω => (Y0 i j ω, Y1 i j ω)) (Q i) P q {y} *
          condDistrib (A i j) (Q i) P q {a}

/-- Observed outcomes equal the potential outcome indexed by treatment. -/
-- @node: ass:consistency
def PlateConsistency {Ω : Type*} {m n : ℕ}
    (A Y0 Y1 Y : Fin n → Fin m → Ω → Bool) : Prop :=
  ∀ i j ω, Y i j ω = if A i j ω then Y1 i j ω else Y0 i j ω

-- @env: S1
-- @realizes m(positive plate size via model field)
-- @realizes n(positive cluster count via model field)
-- @realizes epsilon((0,1/2) via model field)
variable (m n : ℕ) (ε : ℝ)
  {Ω : Type*} [MeasurableSpace Ω] (P : Measure Ω) [IsProbabilityMeasure P]

/-- A positive fixed-plate hierarchical observational model. -/
-- @node: def:hierarchical-scm-class
structure HierarchicalPlateModel where
  positivePlate : 0 < m -- @realizes m(m∈ℕ≥1)
  positiveClusters : 0 < n -- @realizes n(n∈ℕ≥1)
  overlapPositive : 0 < ε -- @realizes epsilon(0<epsilon)
  overlapBelowHalf : ε < (1 / 2 : ℝ) -- @realizes epsilon(epsilon<1/2)
  mu : Measure CellLaw -- @realizes mu(mixing-law carrier)
  Q : Fin n → Ω → CellLaw -- @realizes Q_i(latent K_epsilon-valued random vector)
  A : Fin n → Fin m → Ω → Bool -- @realizes A_ij(binary treatment)
  Y0 : Fin n → Fin m → Ω → Bool -- @realizes Y0_ij(binary untreated potential outcome)
  Y1 : Fin n → Fin m → Ω → Bool -- @realizes Y1_ij(binary treated potential outcome)
  Y : Fin n → Fin m → Ω → Bool -- @realizes Y_ij(binary observed outcome)
  C : Fin n → Ω → CountIndex m -- @realizes C_i(within-cluster four-cell count in I_m)
  count_def : ∀ i ω c,
    (C i ω).1 c = ∑ j, if observedPair A Y i j ω = c then 1 else 0
  measurableQ : ∀ i, Measurable (Q i)
  measurableA : ∀ i j, Measurable (A i j)
  measurableY0 : ∀ i j, Measurable (Y0 i j)
  measurableY1 : ∀ i j, Measurable (Y1 i j)
  measurableY : ∀ i j, Measurable (Y i j)
  clusters_iid : IndependentClusterSampling P Q A Y0 Y1
  environment_law : EnvironmentLaw P ε mu Q
  conditional_iid : ConditionalIidPlate P Q A Y0 Y1
  observed_calibration : ObservedCellCalibration P Q A Y
  latent_ignorability : LatentIgnorability P Q A Y0 Y1
  consistency : PlateConsistency A Y0 Y1 Y
  -- @realizes M_hscm(members of the positive fixed-plate hierarchical model class)

end CausalSmith.SCM.FiniteplateBernsteinAteBounds
