/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import Causalean.Estimation.ATE.Score.ScorePullout
public import Causalean.Mathlib.MeasureTheory.CondExpWithDensity
public import Causalean.Mathlib.Probability.Independence.Conditional.Transport.AeRetraction

/-!
# The average treatment effect as a functional of an observed-data law

This module defines the propensity score, arm regressions, and g-formula ATE
directly from a probability law on observed triples `(X, D, Y)`.  All nuisance
functions are recomputed from the supplied law by conditioning on the
σ-algebra generated by the covariate projection.  The final lemmas identify
these canonical observed-law nuisances at a backdoor system's true law with
the system's existing value-space representatives.
-/

@[expose] public section

noncomputable section

open Causalean.Mathlib.Probability.Independence.Conditional.Transport

namespace Causalean.Estimation.Efficiency

open Filter MeasureTheory ProbabilityTheory
open Causalean Estimation ATE Causalean.PO

variable {γ : Type*} [MeasurableSpace γ]

/-- For [a covariate space `γ`](hyp:γ), the [covariate σ-algebra on observed triples](goal)
is generated by the projection `(x,d,y) ↦ x`. -/
@[instance_reducible] def observedCovariateSigma : MeasurableSpace (γ × Bool × ℝ) :=
  MeasurableSpace.comap ATE.BackdoorEstimationSystem.projX inferInstance

/-- The [covariate σ-algebra on observed triples](goal) is contained in the ambient product
σ-algebra. -/
lemma observedCovariateSigma_le :
    observedCovariateSigma (γ := γ) ≤ (inferInstance : MeasurableSpace (γ × Bool × ℝ)) :=
  (measurable_fst : Measurable (fun z : γ × Bool × ℝ => z.1)).comap_le

/-- For [a treatment arm `d`](hyp:d) and [an observed triple `z`](hyp:z), the [arm
indicator](goal) is one when the observed treatment equals `d` and zero otherwise. -/
def observedArmIndicator (d : Bool) (z : γ × Bool × ℝ) : ℝ :=
  if ATE.BackdoorEstimationSystem.projA z = d then 1 else 0

/-- For [a treatment arm `d`](hyp:d), the [observed arm indicator is measurable](goal). -/
@[fun_prop] lemma measurable_observedArmIndicator (d : Bool) :
    Measurable (observedArmIndicator (γ := γ) d) := by
  exact (Measurable.of_discrete
    (f := fun b : Bool => if b = d then (1 : ℝ) else 0)).comp
      (measurable_snd.fst : Measurable (fun z : γ × Bool × ℝ => z.2.1))

/-- For [a probability law `Q` on observed triples](hyp:Q) and [a treatment arm `d`](hyp:d),
the [law's arm propensity](goal) is the conditional expectation of the arm indicator given
the covariate σ-algebra. -/
def observedPropensity (Q : Measure (γ × Bool × ℝ)) (d : Bool) :
    γ × Bool × ℝ → ℝ :=
  @condExp (γ × Bool × ℝ) ℝ (observedCovariateSigma (γ := γ)) _ _ _ Q
    (observedArmIndicator d)

/-- For [a probability law `Q` on observed triples](hyp:Q) and [a treatment arm `d`](hyp:d),
the [law's arm outcome numerator](goal) is the conditional expectation of
`Y 1{D=d}` given the covariate σ-algebra. -/
def observedArmNumerator (Q : Measure (γ × Bool × ℝ)) (d : Bool) :
    γ × Bool × ℝ → ℝ :=
  @condExp (γ × Bool × ℝ) ℝ (observedCovariateSigma (γ := γ)) _ _ _ Q
    (fun z => ATE.BackdoorEstimationSystem.projY z * observedArmIndicator d z)

/-- For [a probability law `Q` on observed triples](hyp:Q) and [a treatment arm `d`](hyp:d),
the [law's arm outcome regression](goal) is the conditional `Y 1{D=d}` numerator divided by
the corresponding arm propensity. -/
def observedArmRegression (Q : Measure (γ × Bool × ℝ)) (d : Bool) :
    γ × Bool × ℝ → ℝ :=
  fun z => observedArmNumerator Q d z / observedPropensity Q d z

/-- For [a probability law `Q` on observed triples](hyp:Q) and [a treatment arm `d`](hyp:d),
the [observed-law arm mean functional](goal) integrates the recomputed arm regression
`μ_d(X)` against `Q`. -/
def observedArmMean (Q : Measure (γ × Bool × ℝ)) (d : Bool) : ℝ :=
  ∫ z, observedArmRegression Q d z ∂Q

/-- For [a probability law `Q` on observed triples](hyp:Q), the [observed-law average
treatment-effect functional](goal) integrates the recomputed treated-minus-control arm
regression against `Q`. -/
def observedATE (Q : Measure (γ × Bool × ℝ)) : ℝ :=
  ∫ z, observedArmRegression Q true z - observedArmRegression Q false z ∂Q

/-- For [an observed-data law `Q`](hyp:Q) whose [two arm regressions are
integrable](hyp:hμ), [the observed ATE is the treated-arm mean minus the
control-arm mean](goal). -/
theorem observedATE_eq_observedArmMean_sub
    (Q : Measure (γ × Bool × ℝ))
    (hμ : ∀ d, Integrable (observedArmRegression Q d) Q) :
    observedATE Q = observedArmMean Q true - observedArmMean Q false := by
  unfold observedATE observedArmMean
  exact integral_sub (hμ true) (hμ false)

/-- For [a base observed-data law `Q`](hyp:Q) and [an observed triple `z`](hyp:z), the
[law-recomputed AIPW influence function](goal) is the arm-regression contrast centered by
`observedATE Q`, augmented by the two inverse-arm-propensity residuals. -/
def observedAIPW (Q : Measure (γ × Bool × ℝ)) (z : γ × Bool × ℝ) : ℝ :=
  observedArmRegression Q true z - observedArmRegression Q false z - observedATE Q +
    observedArmIndicator true z / observedPropensity Q true z *
      (ATE.BackdoorEstimationSystem.projY z - observedArmRegression Q true z) -
    observedArmIndicator false z / observedPropensity Q false z *
      (ATE.BackdoorEstimationSystem.projY z - observedArmRegression Q false z)

/-- For [a base observed-data law `Q`](hyp:Q), [a treatment arm `d`](hyp:d), and
[an observed triple `z`](hyp:z), the [efficient-influence-function candidate for the
arm mean](goal) is the inverse-propensity-weighted arm residual plus `μ_d(X)`, centered
by the arm mean. -/
def observedArmEIF (Q : Measure (γ × Bool × ℝ)) (d : Bool)
    (z : γ × Bool × ℝ) : ℝ :=
  observedArmIndicator d z / observedPropensity Q d z *
      (ATE.BackdoorEstimationSystem.projY z - observedArmRegression Q d z) +
    observedArmRegression Q d z - observedArmMean Q d

/-- For [an observed-data law `Q`](hyp:Q) whose [two arm regressions are
integrable](hyp:hμ) and [an observed triple `z`](hyp:z), [the AIPW influence function is
the treated-arm influence function minus the control-arm influence function](goal). -/
theorem observedAIPW_eq_armEIF_sub (Q : Measure (γ × Bool × ℝ))
    (hμ : ∀ d, Integrable (observedArmRegression Q d) Q)
    (z : γ × Bool × ℝ) :
    observedAIPW Q z = observedArmEIF Q true z - observedArmEIF Q false z := by
  unfold observedAIPW observedArmEIF observedArmMean observedATE
  rw [integral_sub (hμ true) (hμ false)]
  ring

/-- For [a law `Q`](hyp:Q) and [an arm `d`](hyp:d), [the observed propensity is
measurable](goal). -/
@[fun_prop] lemma measurable_observedPropensity (Q : Measure (γ × Bool × ℝ)) (d : Bool) :
    Measurable (observedPropensity Q d) :=
  (stronglyMeasurable_condExp (μ := Q) (m := observedCovariateSigma)
    (f := observedArmIndicator d)).measurable.mono observedCovariateSigma_le le_rfl

/-- For [a law `Q`](hyp:Q) and [an arm `d`](hyp:d), [the observed propensity is strongly
measurable for the covariate σ-algebra](goal). -/
@[fun_prop] lemma stronglyMeasurable_observedPropensity
    (Q : Measure (γ × Bool × ℝ)) (d : Bool) :
    StronglyMeasurable[observedCovariateSigma] (observedPropensity Q d) :=
  stronglyMeasurable_condExp

/-- For [a law `Q`](hyp:Q) and [an arm `d`](hyp:d), [the observed arm numerator is
measurable](goal). -/
@[fun_prop] lemma measurable_observedArmNumerator (Q : Measure (γ × Bool × ℝ)) (d : Bool) :
    Measurable (observedArmNumerator Q d) :=
  (stronglyMeasurable_condExp (μ := Q) (m := observedCovariateSigma)
    (f := fun z => ATE.BackdoorEstimationSystem.projY z * observedArmIndicator d z)).measurable.mono
      observedCovariateSigma_le le_rfl

/-- For [a law `Q`](hyp:Q) and [an arm `d`](hyp:d), [the observed arm numerator is strongly
measurable for the covariate σ-algebra](goal). -/
@[fun_prop] lemma stronglyMeasurable_observedArmNumerator
    (Q : Measure (γ × Bool × ℝ)) (d : Bool) :
    StronglyMeasurable[observedCovariateSigma] (observedArmNumerator Q d) :=
  stronglyMeasurable_condExp

/-- For [a law `Q`](hyp:Q) and [an arm `d`](hyp:d), [the observed arm regression is
measurable](goal). -/
@[fun_prop] lemma measurable_observedArmRegression (Q : Measure (γ × Bool × ℝ)) (d : Bool) :
    Measurable (observedArmRegression Q d) := by
  unfold observedArmRegression
  fun_prop

/-- For [a law `Q`](hyp:Q) and [an arm `d`](hyp:d), [the observed arm regression is strongly
measurable for the covariate σ-algebra](goal). -/
@[fun_prop] lemma stronglyMeasurable_observedArmRegression
    (Q : Measure (γ × Bool × ℝ)) (d : Bool) :
    StronglyMeasurable[observedCovariateSigma] (observedArmRegression Q d) := by
  unfold observedArmRegression
  fun_prop

namespace ATE.BackdoorEstimationSystem

variable {P : POSystem} [StandardBorelSpace P.Ω] [IsFiniteMeasure P.μ]

private lemma observedArmIndicator_comp_factualZ
    (S : ATE.BackdoorEstimationSystem P γ) (d : Bool) :
    observedArmIndicator d ∘ S.factualZ = S.toPOBackdoorSystem.dVar.indicator d := by
  funext ω
  simp only [Function.comp_apply, observedArmIndicator,
    ATE.BackdoorEstimationSystem.projA, ATE.BackdoorEstimationSystem.factualZ]
  by_cases h : S.toPOBackdoorSystem.factualD ω = d
  · have hind := S.toPOBackdoorSystem.dVar.indicator_apply_eq_one h
    simpa only [h, if_true] using hind.symm
  · have hind := S.toPOBackdoorSystem.dVar.indicator_apply_eq_zero h
    simpa only [h, if_false] using hind.symm

private lemma observedOutcomeIndicator_comp_factualZ
    (S : ATE.BackdoorEstimationSystem P γ) (d : Bool) :
    (fun z => ATE.BackdoorEstimationSystem.projY z * observedArmIndicator d z) ∘ S.factualZ =
      fun ω => S.toPOBackdoorSystem.factualY ω * S.toPOBackdoorSystem.dVar.indicator d ω := by
  funext ω
  simp only [Function.comp_apply, ATE.BackdoorEstimationSystem.projY]
  rw [show observedArmIndicator d (S.factualZ ω) =
      S.toPOBackdoorSystem.dVar.indicator d ω by
    exact congrFun (observedArmIndicator_comp_factualZ S d) ω]
  rfl

/-- At [a backdoor system's observed law](hyp:S), [the law-recomputed arm propensity equals
the system's label-specific value-space propensity](goal) almost everywhere, under [the
backdoor assumptions](hyp:hA). -/
lemma observedPropensity_P_Z_ae
    (S : ATE.BackdoorEstimationSystem P γ)
    (hA : S.toPOBackdoorSystem.Assumptions) (d : Bool) :
    observedPropensity S.P_Z d =ᵐ[S.P_Z]
      fun z => S.e_val_label d (ATE.BackdoorEstimationSystem.projX z) := by
  letI : IsProbabilityMeasure S.P_Z := by
    unfold ATE.BackdoorEstimationSystem.P_Z
    exact Measure.isProbabilityMeasure_map S.measurable_factualZ.aemeasurable
  have hi : Integrable (observedArmIndicator (γ := γ) d) S.P_Z := by
    apply Integrable.of_bound (measurable_observedArmIndicator d).aestronglyMeasurable 1
    filter_upwards with z
    by_cases h : ATE.BackdoorEstimationSystem.projA z = d <;>
      simp [observedArmIndicator, h]
  have htransport := condExp_comp_of_map_eq S.factualZ S.measurable_factualZ
    S.P_Z_eq (observedCovariateSigma (γ := γ)) observedCovariateSigma_le hi
  have hcomap : MeasurableSpace.comap S.factualZ (observedCovariateSigma (γ := γ)) =
      S.toPOBackdoorSystem.sigmaX := by
    unfold observedCovariateSigma POBackdoorSystem.sigmaX
    rw [MeasurableSpace.comap_comp]
    congr 1
  rw [hcomap, observedArmIndicator_comp_factualZ S d] at htransport
  have hsource : (observedPropensity S.P_Z d) ∘ S.factualZ =ᵐ[P.μ]
      (fun z => S.e_val_label d (ATE.BackdoorEstimationSystem.projX z)) ∘ S.factualZ := by
    exact htransport.symm.trans (S.propScore_eq_e_val_label_ae d)
  rw [S.P_Z_eq] at hsource
  rw [S.P_Z_eq]
  apply (ae_map_iff S.measurable_factualZ.aemeasurable ?_).2
  · filter_upwards [hsource] with x hx
    exact hx
  · exact measurableSet_eq_fun (measurable_observedPropensity S.P_Z d)
      ((S.measurable_e_val_label d).comp measurable_fst)

/-- At [a backdoor system's observed law](hyp:S), [the law-recomputed arm outcome regression
equals the system's value-space arm regression](goal) almost everywhere, under [the backdoor
assumptions](hyp:hA). -/
lemma observedArmRegression_P_Z_ae
    (S : ATE.BackdoorEstimationSystem P γ)
    (hA : S.toPOBackdoorSystem.Assumptions) (d : Bool) :
    observedArmRegression S.P_Z d =ᵐ[S.P_Z]
      fun z => S.μ_val d (ATE.BackdoorEstimationSystem.projX z) := by
  letI : IsProbabilityMeasure S.P_Z := by
    unfold ATE.BackdoorEstimationSystem.P_Z
    exact Measure.isProbabilityMeasure_map S.measurable_factualZ.aemeasurable
  have hYind : Integrable
      (fun z : γ × Bool × ℝ => ATE.BackdoorEstimationSystem.projY z *
        observedArmIndicator d z) S.P_Z := by
    rw [S.P_Z_eq]
    have hmeas : Measurable (fun z : γ × Bool × ℝ =>
        ATE.BackdoorEstimationSystem.projY z * observedArmIndicator d z) :=
      (measurable_snd.snd : Measurable (fun z : γ × Bool × ℝ => z.2.2)).mul
        (measurable_observedArmIndicator d)
    apply (integrable_map_measure hmeas.aestronglyMeasurable
      S.measurable_factualZ.aemeasurable).2
    rw [observedOutcomeIndicator_comp_factualZ S d]
    exact S.toPOBackdoorSystem.dVar.integrable_mul_indicator d
      (measurableSet_singleton d) hA.integrable_factualY
  have htransport := condExp_comp_of_map_eq S.factualZ S.measurable_factualZ
    S.P_Z_eq (observedCovariateSigma (γ := γ)) observedCovariateSigma_le hYind
  have hcomap : MeasurableSpace.comap S.factualZ (observedCovariateSigma (γ := γ)) =
      S.toPOBackdoorSystem.sigmaX := by
    unfold observedCovariateSigma POBackdoorSystem.sigmaX
    rw [MeasurableSpace.comap_comp]
    congr 1
  rw [hcomap, observedOutcomeIndicator_comp_factualZ S d] at htransport
  have hprop := observedPropensity_P_Z_ae S hA d
  have hnum_source : (observedArmNumerator S.P_Z d) ∘ S.factualZ =ᵐ[P.μ]
      P.μ[fun ω => S.toPOBackdoorSystem.factualY ω *
        S.toPOBackdoorSystem.dVar.indicator d ω | S.toPOBackdoorSystem.sigmaX] :=
    htransport.symm
  have hreg_source : (observedArmRegression S.P_Z d) ∘ S.factualZ =ᵐ[P.μ]
      (fun z => S.μ_val d (ATE.BackdoorEstimationSystem.projX z)) ∘ S.factualZ := by
    rw [S.P_Z_eq] at hprop
    have hprop_source := ae_of_ae_map S.measurable_factualZ.aemeasurable hprop
    have hprop_source' : (observedPropensity S.P_Z d) ∘ S.factualZ =ᵐ[P.μ]
        (fun z => S.e_val_label d (ATE.BackdoorEstimationSystem.projX z)) ∘
          S.factualZ := by
      filter_upwards [hprop_source] with x hx
      exact hx
    have hbaseprop := S.propScore_eq_e_val_label_ae d
    filter_upwards [hnum_source, hprop_source', S.μ_reg_compat d, hbaseprop]
      with ω hnum hprop hμ hbaseprop
    change observedArmNumerator S.P_Z d (S.factualZ ω) /
        observedPropensity S.P_Z d (S.factualZ ω) = _
    change observedArmNumerator S.P_Z d (S.factualZ ω) = _ at hnum
    change observedPropensity S.P_Z d (S.factualZ ω) =
      S.e_val_label d (ATE.BackdoorEstimationSystem.projX (S.factualZ ω)) at hprop
    rw [hnum, hprop]
    change P.μ[fun ω => S.toPOBackdoorSystem.factualY ω *
        S.toPOBackdoorSystem.dVar.indicator d ω | S.toPOBackdoorSystem.sigmaX] ω /
      S.e_val_label d (S.toPOBackdoorSystem.factualX ω) =
        S.μ_val d (S.toPOBackdoorSystem.factualX ω)
    rw [← hbaseprop]
    simpa [POBackdoorSystem.adjustedCE, ATE.BackdoorEstimationSystem.factualZ] using hμ.symm
  rw [S.P_Z_eq] at hreg_source
  rw [S.P_Z_eq]
  apply (ae_map_iff S.measurable_factualZ.aemeasurable ?_).2
  · filter_upwards [hreg_source] with x hx
    exact hx
  · exact measurableSet_eq_fun (measurable_observedArmRegression S.P_Z d)
      ((S.μ_meas d).comp measurable_fst)

/-- Under [the backdoor assumptions](hyp:hA), [the observed-law ATE functional at a
backdoor system's true law equals its value-space ATE](goal). -/
theorem observedATE_P_Z_eq
    (S : ATE.BackdoorEstimationSystem P γ)
    (hA : S.toPOBackdoorSystem.Assumptions) :
    observedATE S.P_Z = S.θ₀ := by
  unfold observedATE ATE.BackdoorEstimationSystem.θ₀
  apply Eq.trans (integral_congr_ae ((observedArmRegression_P_Z_ae S hA true).sub
    (observedArmRegression_P_Z_ae S hA false)))
  rw [← S.P_Z_map_projX_eq_P_X]
  simpa only [ATE.BackdoorEstimationSystem.projX, Pi.sub_apply, Function.comp_apply] using
    (integral_map measurable_fst.aemeasurable
      ((S.μ_meas true).sub (S.μ_meas false)).aestronglyMeasurable).symm

/-- Under [the backdoor assumptions](hyp:hA), [the law-recomputed AIPW function at the true
observed law equals the system's existing AIPW influence function](goal) almost everywhere. -/
theorem observedAIPW_P_Z_ae
    (S : ATE.BackdoorEstimationSystem P γ)
    (hA : S.toPOBackdoorSystem.Assumptions) :
    observedAIPW S.P_Z =ᵐ[S.P_Z] S.ψ_AIPW := by
  filter_upwards [observedArmRegression_P_Z_ae S hA true,
    observedArmRegression_P_Z_ae S hA false,
    observedPropensity_P_Z_ae S hA true,
    observedPropensity_P_Z_ae S hA false] with z hμ1 hμ0 he1 he0
  rw [observedAIPW, hμ1, hμ0, he1, he0, observedATE_P_Z_eq S hA]
  unfold ATE.BackdoorEstimationSystem.ψ_AIPW ATE.BackdoorEstimationSystem.aipwMoment
    ATE.BackdoorEstimationSystem.e_val_label ATE.BackdoorEstimationSystem.indA
    observedArmIndicator
  by_cases hd : ATE.BackdoorEstimationSystem.projA z = true
  · have hd' : ATE.BackdoorEstimationSystem.projA z ≠ false := by
      simpa [hd]
    simp [hd]
    ring
  · have hd' : ATE.BackdoorEstimationSystem.projA z = false := by
      cases h : ATE.BackdoorEstimationSystem.projA z <;> simp [h] at hd ⊢
    simp [hd, hd']
    ring

end ATE.BackdoorEstimationSystem

end Causalean.Estimation.Efficiency
