/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/
import Causalean.Estimation.Efficiency.TangentProjection
import Mathlib.Analysis.Calculus.Deriv.Basic

/-!
# Regular submodels and pathwise gradients (abstract semiparametric layer)

This is the abstract **pathwise-gradient / regular-submodel** layer that upgrades
the projection algebra of `Causalean.Estimation.Efficiency.TangentProjection`
(`IsGradient`, `efficientIF`) into the genuine Hahn (1998) statement: an influence
function is the *efficient influence function* when it is the canonical
(projected) pathwise gradient of the target functional along **every** regular
submodel.

Fix a real Hilbert space `H` (in applications `Lp ℝ 2 P`), a distinguished vector
`one : H` (in applications the constant function, so `mean-zero` means
`⟪·, one⟫ = 0`), and a base law `P₀ : 𝓛` in an abstract type of laws `𝓛` on which
functionals `ψ : 𝓛 → ℝ` are evaluated.

* `RegularSubmodel one P₀` packages a one-parameter path of laws `t ↦ path t`
  through `P₀` at `t = 0`, together with a mean-zero L² **score** `s ∈ H` (the
  tangent direction). The path and score are *abstract fields*: we never build
  parametric families from raw measures here.
* `IsPathwiseGradient one P₀ ψ g` says `g` represents the derivative of `ψ` along
  every submodel: `t ↦ ψ (path t)` is differentiable at `0` with derivative
  `⟪g, s⟫`.
* `IsTangentSpace one P₀ T` says the closed subspace `T` is a genuine tangent
  space: it contains every score and is contained in the closure of their span
  (so `T` equals the closed span of the score set).

The main results: the orthogonal projection of any pathwise gradient onto a
tangent space `T` is again a pathwise gradient (`orthogonalProjection_isPathwiseGradient`);
all pathwise gradients share the *same* projection onto `T`
(`efficientIF_eq_of_isPathwiseGradient`); hence a pathwise gradient lying in `T`
is the unique such and equals `efficientIF T g` for every gradient `g`
(`isPathwiseGradient_eq_efficientIF_of_mem`) — the efficient influence function is
well-defined as the canonical gradient.

Reference: Hahn (1998, Econometrica); Bickel–Klaassen–Ritov–Wellner (1993);
Tsiatis (2006), Ch. 3; van der Vaart (1998), Ch. 25.
-/

namespace Causalean.Estimation.Efficiency

open Causalean.Estimation.Efficiency
open scoped InnerProductSpace RealInnerProductSpace

variable {𝓛 : Type*} {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H]

/-- A **regular submodel** through the base law `P₀` bundles [a one-parameter path of laws,
indexed by a real perturbation parameter](hyp:path), that [passes through `P₀` at parameter
zero](hyp:path_zero), together with [its tangent direction, an L² score vector](hyp:score)
required to be [mean-zero, i.e. orthogonal to the distinguished vector `one`](hyp:score_meanZero).

The path and score are abstract interface fields: we do not construct parametric families from
measures. -/
structure RegularSubmodel (one : H) (P₀ : 𝓛) where
  /-- The one-parameter path of laws. -/
  path : ℝ → 𝓛
  /-- The path passes through the base law at parameter `0`. -/
  path_zero : path 0 = P₀
  /-- The L² score (tangent direction) of the submodel. -/
  score : H
  /-- The score is mean-zero: orthogonal to the distinguished vector `one`. -/
  score_meanZero : ⟪score, one⟫_ℝ = 0

/-- Given [a real normed inner-product space with a distinguished vector](hyp:H,one) and [a base
law in an abstract collection of laws](hyp:𝓛,P₀), the [score set](goal) is the set of
score vectors of all regular one-parameter submodels through that base law. -/
def scoreSet (one : H) (P₀ : 𝓛) : Set H :=
  Set.range (fun m : RegularSubmodel one P₀ => m.score)

/-- Given [a real normed inner-product space with a distinguished vector](hyp:H,one) and [a base
law in an abstract collection of laws](hyp:𝓛,P₀), the [tangent space](goal) is the
topological closure of the linear span of the score set of regular submodels through
that base law.

The **tangent space** generated by the regular submodels through `P₀`: the
topological closure of the linear span of the score set. -/
noncomputable def tangentSpace (one : H) (P₀ : 𝓛) : Submodule ℝ H :=
  (Submodule.span ℝ (scoreSet one P₀)).topologicalClosure

/-- A candidate closed subspace `T` of the Hilbert space is a genuine **tangent space** for the
regular submodels through the base law `P₀` when [every submodel's score lies in
`T`](hyp:scores_mem) and [`T` is contained in the closed linear span of all submodel
scores](hyp:le_closure) — together these force `T` to equal that closed span, the tangent space
generated by the available parametric perturbations.

In applications this is the closed subspace of mean-zero L² functions spanned by the available
scores (all of mean-zero L² in the nonparametric model). -/
structure IsTangentSpace (one : H) (P₀ : 𝓛) (T : Submodule ℝ H) : Prop where
  /-- Every submodel score lies in `T`. -/
  scores_mem : ∀ m : RegularSubmodel one P₀, m.score ∈ T
  /-- `T` is contained in the closed span of the score set. -/
  le_closure : T ≤ tangentSpace one P₀

/-- Given [a real normed inner-product space with a distinguished vector](hyp:H,one), [a base law
in an abstract collection of laws](hyp:𝓛,P₀), [a real-valued functional of laws](hyp:ψ),
and [a candidate influence-function vector](hyp:g), the [candidate is a pathwise
gradient of the functional at the base law](goal) exactly when, along every regular
one-parameter submodel through that law, the functional is differentiable at zero and
its derivative equals the inner product of the candidate vector with that submodel's
score.

`g : H` is a **pathwise gradient** of the functional `ψ : 𝓛 → ℝ` at `P₀`:
along every regular submodel, `t ↦ ψ (path t)` is differentiable at `0` with
derivative `⟪g, score⟫`. This is the abstract semiparametric characterization of
an influence function as the pathwise derivative of the target functional. -/
def IsPathwiseGradient (one : H) (P₀ : 𝓛) (ψ : 𝓛 → ℝ) (g : H) : Prop :=
  ∀ m : RegularSubmodel one P₀,
    HasDerivAt (fun t => ψ (m.path t)) (⟪g, m.score⟫_ℝ) 0

/-- Two pathwise gradients of the same functional pair identically with every
submodel score: `⟪g, s⟫ = ⟪g', s⟫`. (Both equal the pathwise derivative
`d/dt ψ(path t)|₀`, which is unique.) -/
theorem inner_score_eq_of_isPathwiseGradient {one : H} {P₀ : 𝓛} {ψ : 𝓛 → ℝ}
    {g g' : H} (hg : IsPathwiseGradient one P₀ ψ g)
    (hg' : IsPathwiseGradient one P₀ ψ g') (m : RegularSubmodel one P₀) :
    ⟪g, m.score⟫_ℝ = ⟪g', m.score⟫_ℝ :=
  (hg m).unique (hg' m)

/-- The difference of two pathwise gradients is orthogonal to every submodel
score. -/
theorem inner_sub_score_eq_zero_of_isPathwiseGradient {one : H} {P₀ : 𝓛}
    {ψ : 𝓛 → ℝ} {g g' : H} (hg : IsPathwiseGradient one P₀ ψ g)
    (hg' : IsPathwiseGradient one P₀ ψ g') (m : RegularSubmodel one P₀) :
    ⟪g - g', m.score⟫_ℝ = 0 := by
  rw [inner_sub_left, inner_score_eq_of_isPathwiseGradient hg hg' m, sub_self]

/-- The difference of two pathwise gradients lies in the orthogonal complement of
any tangent space `T`.

Strategy: `g - g'` is orthogonal to every score, hence to the span of the score
set, hence (orthogonal complements are closed) to its topological closure
`tangentSpace one P₀`; antitonicity of `·ᗮ` with `T ≤ tangentSpace` then places
`g - g'` in `Tᗮ`. Use `Submodule.orthogonal_closure` to drop the closure. -/
theorem sub_mem_orthogonal_of_isPathwiseGradient {one : H} {P₀ : 𝓛} {ψ : 𝓛 → ℝ}
    {g g' : H} {T : Submodule ℝ H} (hT : IsTangentSpace one P₀ T)
    (hg : IsPathwiseGradient one P₀ ψ g)
    (hg' : IsPathwiseGradient one P₀ ψ g') :
    g - g' ∈ Tᗮ := by
  apply Submodule.orthogonal_le hT.le_closure
  rw [tangentSpace, Submodule.orthogonal_closure]
  rw [Submodule.mem_orthogonal']
  intro u hu
  let Z : Submodule ℝ H := {
    carrier := {v | ⟪g - g', v⟫_ℝ = 0}
    zero_mem' := by simp
    add_mem' := by
      intro v w hv hw
      change ⟪g - g', v + w⟫_ℝ = 0
      rw [inner_add_right, hv, hw, add_zero]
    smul_mem' := by
      intro a v hv
      change ⟪g - g', a • v⟫_ℝ = 0
      rw [inner_smul_right, hv, mul_zero] }
  have hspan : Submodule.span ℝ (scoreSet one P₀) ≤ Z := by
    rw [Submodule.span_le]
    rintro x ⟨m, rfl⟩
    exact inner_sub_score_eq_zero_of_isPathwiseGradient hg hg' m
  exact hspan hu

/-- **Two pathwise gradients differ by an orthogonal-complement element**, i.e.
either is a `TangentProjection`-gradient of the other relative to any tangent
space `T`. This is the bridge from the pathwise (`HasDerivAt`) layer to the inner
product `IsGradient` algebra of `TangentProjection.lean`. -/
theorem isGradient_of_isPathwiseGradient {one : H} {P₀ : 𝓛} {ψ : 𝓛 → ℝ}
    {g g' : H} {T : Submodule ℝ H} (hT : IsTangentSpace one P₀ T)
    (hg : IsPathwiseGradient one P₀ ψ g)
    (hg' : IsPathwiseGradient one P₀ ψ g') :
    IsGradient T g g' :=
  (isGradient_iff_sub_mem_orthogonal g g').2
    (sub_mem_orthogonal_of_isPathwiseGradient hT hg' hg)

section Projection

variable {T : Submodule ℝ H} [T.HasOrthogonalProjection]

/-- **The projection of a pathwise gradient is a pathwise gradient.** Suppose
[`T` is a tangent space for the regular submodels through the base law
`P₀`](hyp:hT), and suppose [`g` reproduces the pathwise derivative of the
functional `ψ` along every such submodel — it is a pathwise gradient of `ψ` at
`P₀`](hyp:hg). Then [the orthogonal projection of `g` onto `T`, written
`efficientIF T g`, is again a pathwise gradient of `ψ`](goal).

Strategy: for each submodel `m`, `m.score ∈ T` (`hT.scores_mem`), so
`⟪efficientIF T g, m.score⟫ = ⟪g, m.score⟫` by
`inner_orthogonalProjection_eq_of_mem`; rewrite and apply `hg m`. -/
theorem orthogonalProjection_isPathwiseGradient {one : H} {P₀ : 𝓛} {ψ : 𝓛 → ℝ}
    {g : H} (hT : IsTangentSpace one P₀ T) (hg : IsPathwiseGradient one P₀ ψ g) :
    IsPathwiseGradient one P₀ ψ (efficientIF T g) := by
  intro m
  have hinner : ⟪efficientIF T g, m.score⟫_ℝ = ⟪g, m.score⟫_ℝ := by
    rw [efficientIF]
    exact T.inner_orthogonalProjection_eq_of_mem_right ⟨m.score, hT.scores_mem m⟩ g
  simpa [hinner] using hg m

/-- **All pathwise gradients share the same projection onto a tangent space.**
Hence the efficient influence function `efficientIF T g` does not depend on the
chosen pathwise gradient `g`: it is the canonical gradient. -/
theorem efficientIF_eq_of_isPathwiseGradient {one : H} {P₀ : 𝓛} {ψ : 𝓛 → ℝ}
    {g g' : H} (hT : IsTangentSpace one P₀ T)
    (hg : IsPathwiseGradient one P₀ ψ g)
    (hg' : IsPathwiseGradient one P₀ ψ g') :
    efficientIF T g = efficientIF T g' := by
  have hgrad : IsGradient T g g' := isGradient_of_isPathwiseGradient hT hg hg'
  have hproj : (T.orthogonalProjection g' : H) = efficientIF T g :=
    orthogonalProjection_eq_of_isGradient hgrad
  simpa [efficientIF] using hproj.symm

/-- **The efficient influence function is the unique pathwise gradient in `T`.**
If `g` is any pathwise gradient and `g'` is a pathwise gradient lying in the
tangent space `T`, then `g' = efficientIF T g`. Thus a pathwise gradient inside
`T` is uniquely determined and equals the projection of every gradient — the
efficient influence function / canonical gradient. -/
theorem isPathwiseGradient_eq_efficientIF_of_mem {one : H} {P₀ : 𝓛} {ψ : 𝓛 → ℝ}
    {g g' : H} (hT : IsTangentSpace one P₀ T)
    (hg : IsPathwiseGradient one P₀ ψ g)
    (hg' : IsPathwiseGradient one P₀ ψ g') (hmem : g' ∈ T) :
    g' = efficientIF T g := by
  exact efficientIF_unique (isGradient_of_isPathwiseGradient hT hg hg') hmem

/-- **A pathwise gradient lying in `T` equals its own projection.** This recovers
`efficientIF_eq_self_of_mem`, now as a corollary of "`g` is the efficient
influence function": a gradient already in the tangent space is the canonical
gradient. -/
theorem efficientIF_eq_self_of_isPathwiseGradient_mem {one : H} {P₀ : 𝓛}
    {ψ : 𝓛 → ℝ} {g : H} (hT : IsTangentSpace one P₀ T)
    (hg : IsPathwiseGradient one P₀ ψ g) (hmem : g ∈ T) :
    efficientIF T g = g :=
  (isPathwiseGradient_eq_efficientIF_of_mem hT hg hg hmem).symm

end Projection

end Causalean.Estimation.Efficiency
