module
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.SequentialObservedKernel
public import CausalSmith.Stat.STAT_LdpAteEfficiencySurface_Research.Helpers.TranscriptUniqueness

/-! # Exact law of the observed sequential experiment

This file marginalizes the finite IID four-cell input path and identifies the
resulting transcript law with the law generated by the observed kernels. -/

public section
noncomputable section

namespace CausalSmith.Stat.LdpAteEfficiencySurface

open MeasureTheory ProbabilityTheory
open scoped BigOperators ENNReal
open Causalean.Mathlib.Probability.Kernel.FiniteSequence

private lemma sum_pathWeight_current_coordinate {n : ℕ}
    (θ : TrialParameter) (p : ℝ) (hp : InteriorAssignment p)
    (hθ : InteriorMeans θ) (k : ℕ) (hk : k + 1 ≤ n)
    (F : (Fin n → Fin 4) → Fin 4 → ℝ≥0∞)
    (hF : ∀ x y : Fin n → Fin 4,
      (∀ i : Fin n, i.val < k → x i = y i) → ∀ a, F x a = F y a) :
    (∑ x : Fin n → Fin 4,
      ENNReal.ofReal (inputPathProbability θ p x) *
        F x (x (nextIndex hk))) =
    ∑ x : Fin n → Fin 4,
      ENNReal.ofReal (inputPathProbability θ p x) *
        ∑ a : Fin 4, ENNReal.ofReal (piTheta θ p a) * F x a := by
  let j : Fin n := nextIndex hk
  let w : Fin 4 → ℝ≥0∞ := fun a => ENNReal.ofReal (piTheta θ p a)
  have hw : (∑ a : Fin 4, w a) = 1 := by
    simp only [w, ← ENNReal.ofReal_sum_of_nonneg
      (fun a _ => (piTheta_pos_interior θ p hp hθ a).le), piTheta_sum_eq_one]
    norm_num
  have hpath (x : Fin n → Fin 4) :
      ENNReal.ofReal (inputPathProbability θ p x) = ∏ i : Fin n, w (x i) := by
    simp [inputPathProbability, w, ENNReal.ofReal_prod_of_nonneg
      (fun i _ => (piTheta_pos_interior θ p hp hθ (x i)).le)]
  let e : ((Fin n → Fin 4) × Fin 4) ≃ ((Fin n → Fin 4) × Fin 4) :=
    Equiv.ofBijective
      (fun q => (Function.update q.1 j q.2, q.1 j))
      (by
        apply Function.Involutive.bijective
        rintro ⟨x, a⟩
        simp [Function.update_idem])
  have he (x : Fin n → Fin 4) (a : Fin 4) :
      e (x, a) = (Function.update x j a, x j) := rfl
  have hprefix (x : Fin n → Fin 4) (a b : Fin 4) :
      F (Function.update x j a) b = F x b := by
    apply hF
    intro i hi
    apply Function.update_of_ne
    intro hij
    have : i.val = k := by simpa [j, nextIndex] using congrArg Fin.val hij
    omega
  have hswap (x : Fin n → Fin 4) (a : Fin 4) :
      w a * (∏ i : Fin n, w (x i)) =
        w (x j) * (∏ i : Fin n, w ((Function.update x j a) i)) := by
    have hprod : (∏ i : Fin n, w ((Function.update x j a) i)) =
        w a * ∏ i ∈ (Finset.univ : Finset (Fin n)).erase j, w (x i) := by
      have hfun : (fun i : Fin n => w ((Function.update x j a) i)) =
          Function.update (fun i : Fin n => w (x i)) j (w a) := by
        funext i
        by_cases hi : i = j <;> simp [Function.update, hi]
      rw [hfun]
      simpa only [Finset.erase_eq] using (Finset.prod_update_of_mem
        (Finset.mem_univ j) (fun i : Fin n => w (x i)) (w a))
    rw [hprod, ← Finset.mul_prod_erase (Finset.univ : Finset (Fin n))
      (fun i => w (x i)) (Finset.mem_univ j)]
    ac_rfl
  calc
    (∑ x : Fin n → Fin 4,
        ENNReal.ofReal (inputPathProbability θ p x) * F x (x j)) =
        ∑ x : Fin n → Fin 4, ∑ a : Fin 4,
          (w a * ENNReal.ofReal (inputPathProbability θ p x)) * F x (x j) := by
            simp_rw [mul_assoc, ← Finset.sum_mul, hw, one_mul]
    _ = ∑ q : (Fin n → Fin 4) × Fin 4,
          (w q.2 * ENNReal.ofReal (inputPathProbability θ p q.1)) *
            F q.1 (q.1 j) := by
            rw [Fintype.sum_prod_type]
    _ = ∑ q : (Fin n → Fin 4) × Fin 4,
          (ENNReal.ofReal (inputPathProbability θ p q.1) * w q.2) *
            F q.1 q.2 := by
            apply Fintype.sum_equiv e
            rintro ⟨x, a⟩
            simp only [he, hpath, hprefix]
            rw [hswap]
            ac_rfl
    _ = ∑ x : Fin n → Fin 4,
          ENNReal.ofReal (inputPathProbability θ p x) *
            ∑ a : Fin 4, ENNReal.ofReal (piTheta θ p a) * F x a := by
            rw [Fintype.sum_prod_type]
            simp only [w, Finset.mul_sum, mul_assoc]

private lemma prefixLaw_eq_of_agree {n : ℕ} {Z : Fin n → Type*}
    [∀ i, MeasurableSpace (Z i)]
    (Q : KernelFamily (Fin 4) Z) (x y : Fin n → Fin 4)
    (k : ℕ) (hk : k ≤ n)
    (hxy : ∀ i : Fin n, i.val < k → x i = y i) :
    prefixLaw Q x k hk = prefixLaw Q y k hk := by
  induction k with
  | zero => rfl
  | succ k ih =>
    rw [prefixLaw_succ, prefixLaw_succ,
      ih (Nat.le_of_succ_le hk) (fun i hi => hxy i (Nat.lt_succ_of_lt hi))]
    have hlast : x (nextIndex hk) = y (nextIndex hk) :=
      hxy (nextIndex hk) (by simp [nextIndex])
    simp only [hlast]

private def prefixMixtureLaw {n : ℕ} {Z : Fin n → Type*}
    [∀ i, MeasurableSpace (Z i)]
    (Q : KernelFamily (Fin 4) Z) (θ : TrialParameter) (p : ℝ)
    (k : ℕ) (hk : k ≤ n) : Measure (History Z k hk) :=
  ∑ x : Fin n → Fin 4,
    ENNReal.ofReal (inputPathProbability θ p x) • prefixLaw Q x k hk

private lemma prefixMixture_compProd {Z : OutputFamily}
    [∀ n i, MeasurableSpace (Z n i)] {ε : ℝ}
    (P : ProcedureSequence Z ε) (θ : TrialParameter) (p : ℝ)
    (hp : InteriorAssignment p) (hθ : InteriorMeans θ)
    (n k : ℕ) (hk : k + 1 ≤ n) :
    (∑ x : Fin n → Fin 4,
      ENNReal.ofReal (inputPathProbability θ p x) •
        (prefixLaw (finiteSequenceKernel (P.channel n)) x k
            (Nat.le_of_succ_le hk) ⊗ₘ
          (finiteSequenceKernel (P.channel n) (nextIndex hk)).comap
            (fun h => (x (nextIndex hk), h)) (by fun_prop))) =
      prefixMixtureLaw (finiteSequenceKernel (P.channel n)) θ p k
          (Nat.le_of_succ_le hk) ⊗ₘ
        (observedStageKernel P θ p n (nextIndex hk)).comap
          (fun h => ((), h)) (by fun_prop) := by
  have hmarkov (r : Fin n) : IsMarkovKernel (P.channel n r) :=
    (P.privacy n).1 r
  letI : IsMarkovKernel (P.channel n (nextIndex hk)) := hmarkov _
  have hQ (r : Fin n) : IsMarkovKernel (finiteSequenceKernel (P.channel n) r) := by
    letI : IsMarkovKernel (P.channel n r) := hmarkov r
    dsimp [finiteSequenceKernel]
    infer_instance
  letI : IsMarkovKernel (finiteSequenceKernel (P.channel n) (nextIndex hk)) := hQ _
  letI : IsMarkovKernel (observedStageKernel P θ p n (nextIndex hk)) :=
    observedStageKernel_isMarkov P θ p hp hθ n _
  let toPrivate : History (Z n) k (Nat.le_of_succ_le hk) →
      PrivateHistory (Z := Z n) (nextIndex hk) :=
    fun h => fsHistoryToPrivate (nextIndex hk) h
  let Kx (x : Fin n → Fin 4) :
      Kernel (History (Z n) k (Nat.le_of_succ_le hk)) (Z n (nextIndex hk)) :=
    (finiteSequenceKernel (P.channel n) (nextIndex hk)).comap
      (fun h => (x (nextIndex hk), h)) (by fun_prop)
  let Kobs : Kernel (History (Z n) k (Nat.le_of_succ_le hk))
      (Z n (nextIndex hk)) :=
    (observedStageKernel P θ p n (nextIndex hk)).comap
      (fun h => ((), h)) (by fun_prop)
  haveI hKx (x : Fin n → Fin 4) : IsMarkovKernel (Kx x) := by
    dsimp only [Kx]
    infer_instance
  haveI hprefixProb (x : Fin n → Fin 4) : IsProbabilityMeasure
      (prefixLaw (finiteSequenceKernel (P.channel n)) x k
        (Nat.le_of_succ_le hk)) :=
    isProbabilityMeasure_prefixLaw _ hQ x k _
  letI : IsMarkovKernel Kobs := by dsimp only [Kobs]; infer_instance
  have hKx_apply (x : Fin n → Fin 4)
      (h : History (Z n) k (Nat.le_of_succ_le hk)) :
      Kx x h = (P.channel n (nextIndex hk))
        (x (nextIndex hk), toPrivate h) := by rfl
  have hKobs_apply (h : History (Z n) k (Nat.le_of_succ_le hk)) :
      Kobs h = ∑ a : Fin 4, ENNReal.ofReal (piTheta θ p a) •
        (P.channel n (nextIndex hk)) (a, toPrivate h) := by rfl
  letI : IsFiniteMeasure
      (prefixMixtureLaw (finiteSequenceKernel (P.channel n)) θ p k
        (Nat.le_of_succ_le hk)) := by
    refine ⟨?_⟩
    simp only [prefixMixtureLaw, Measure.finsetSum_apply,
      Measure.smul_apply, smul_eq_mul]
    simp_rw [show ∀ x : Fin n → Fin 4,
      prefixLaw (finiteSequenceKernel (P.channel n)) x k
        (Nat.le_of_succ_le hk) Set.univ = 1 from fun x =>
          (isProbabilityMeasure_prefixLaw _ hQ x k _).measure_univ]
    simp only [mul_one]
    rw [← ENNReal.ofReal_sum_of_nonneg]
    · rw [inputPathProbability_sum_eq_one]
      norm_num
    · intro x _
      unfold inputPathProbability
      exact Finset.prod_nonneg fun r _ =>
        (piTheta_pos_interior θ p hp hθ (x r)).le
  change (∑ x : Fin n → Fin 4,
      ENNReal.ofReal (inputPathProbability θ p x) •
        (prefixLaw (finiteSequenceKernel (P.channel n)) x k
          (Nat.le_of_succ_le hk) ⊗ₘ Kx x)) =
    prefixMixtureLaw (finiteSequenceKernel (P.channel n)) θ p k
      (Nat.le_of_succ_le hk) ⊗ₘ Kobs
  ext s hs
  simp only [Measure.finsetSum_apply, Measure.smul_apply, smul_eq_mul]
  rw [Measure.compProd_apply hs]
  simp_rw [Measure.compProd_apply hs]
  simp_rw [hKx_apply, hKobs_apply]
  change (∑ x : Fin n → Fin 4,
      ENNReal.ofReal (inputPathProbability θ p x) *
        ∫⁻ h, (P.channel n (nextIndex hk))
          (x (nextIndex hk), toPrivate h) (Prod.mk h ⁻¹' s)
          ∂prefixLaw (finiteSequenceKernel (P.channel n)) x k
            (Nat.le_of_succ_le hk)) = _
  rw [show prefixMixtureLaw (finiteSequenceKernel (P.channel n)) θ p k
      (Nat.le_of_succ_le hk) =
      ∑ x : Fin n → Fin 4,
        ENNReal.ofReal (inputPathProbability θ p x) •
          prefixLaw (finiteSequenceKernel (P.channel n)) x k
            (Nat.le_of_succ_le hk) by rfl]
  rw [lintegral_finset_sum_measure]
  simp only [lintegral_smul_measure, smul_eq_mul]
  have hsection (a : Fin 4) : Measurable (fun h =>
      (P.channel n (nextIndex hk))
        (a, toPrivate h) (Prod.mk h ⁻¹' s)) := by
    let Ka : Kernel (History (Z n) k (Nat.le_of_succ_le hk))
        (Z n (nextIndex hk)) :=
      (P.channel n (nextIndex hk)).comap (fun h => (a, toPrivate h))
        (measurable_const.prodMk (measurable_fsHistoryToPrivate (nextIndex hk)))
    exact Ka.measurable_kernel_prodMk_left hs
  simp_rw [Measure.finsetSum_apply, Measure.smul_apply, smul_eq_mul]
  have hinter (x : Fin n → Fin 4) :
      (∫⁻ h, ∑ a : Fin 4, ENNReal.ofReal (piTheta θ p a) *
          (P.channel n (nextIndex hk)) (a, toPrivate h) (Prod.mk h ⁻¹' s)
        ∂prefixLaw (finiteSequenceKernel (P.channel n)) x k
          (Nat.le_of_succ_le hk)) =
      ∑ a : Fin 4, ENNReal.ofReal (piTheta θ p a) *
        ∫⁻ h, (P.channel n (nextIndex hk))
          (a, toPrivate h) (Prod.mk h ⁻¹' s)
          ∂prefixLaw (finiteSequenceKernel (P.channel n)) x k
            (Nat.le_of_succ_le hk) := by
    rw [lintegral_finset_sum]
    · apply Finset.sum_congr rfl
      intro a _
      rw [lintegral_const_mul _ (hsection a)]
    · intro a _
      exact (measurable_const.mul (hsection a))
  simp_rw [hinter]
  refine sum_pathWeight_current_coordinate θ p hp hθ k hk
    (F := fun x a =>
      ∫⁻ h, (P.channel n (nextIndex hk))
        (a, toPrivate h) (Prod.mk h ⁻¹' s)
        ∂prefixLaw (finiteSequenceKernel (P.channel n)) x k
          (Nat.le_of_succ_le hk)) ?_
  intro x y hxy a
  congr 1
  exact prefixLaw_eq_of_agree (finiteSequenceKernel (P.channel n)) x y k
    (Nat.le_of_succ_le hk) hxy

private lemma prefixMixtureLaw_eq_observed {Z : OutputFamily}
    [∀ n i, MeasurableSpace (Z n i)] {ε : ℝ}
    (P : ProcedureSequence Z ε) (θ : TrialParameter) (p : ℝ)
    (hp : InteriorAssignment p) (hθ : InteriorMeans θ)
    (n k : ℕ) (hk : k ≤ n) :
    prefixMixtureLaw (finiteSequenceKernel (P.channel n)) θ p k hk =
      prefixLaw (fun i => observedStageKernel P θ p n i)
        (fun _ => ()) k hk := by
  induction k with
  | zero =>
      let emptyHistory : History (Z n) 0 hk := fun j => j.elim0
      change (∑ x : Fin n → Fin 4,
        ENNReal.ofReal (inputPathProbability θ p x) •
          Measure.dirac emptyHistory) = Measure.dirac emptyHistory
      have hnonneg (x : Fin n → Fin 4) : 0 ≤ inputPathProbability θ p x := by
        unfold inputPathProbability
        exact Finset.prod_nonneg fun i _ =>
          (piTheta_pos_interior θ p hp hθ (x i)).le
      have hw : (∑ x : Fin n → Fin 4,
          ENNReal.ofReal (inputPathProbability θ p x)) = 1 := by
        rw [← ENNReal.ofReal_sum_of_nonneg (fun x _ => hnonneg x),
          inputPathProbability_sum_eq_one]
        norm_num
      ext A hA
      simp only [Measure.finsetSum_apply, Measure.smul_apply, smul_eq_mul,
        Measure.dirac_apply' _ hA]
      by_cases hmem : emptyHistory ∈ A
      · simp [hmem, hw]
      · simp [hmem]
  | succ k ih =>
      have hsnoc : Measurable (fun q :
          History (Z n) k (Nat.le_of_succ_le hk) × Z n (nextIndex hk) =>
          snoc hk q.1 q.2) := measurable_snoc hk
      have hQ (i : Fin n) : IsMarkovKernel
          (finiteSequenceKernel (P.channel n) i) := by
        letI : IsMarkovKernel (P.channel n i) := (P.privacy n).1 i
        dsimp [finiteSequenceKernel]
        infer_instance
      change (∑ x : Fin n → Fin 4,
        ENNReal.ofReal (inputPathProbability θ p x) •
          prefixLaw (finiteSequenceKernel (P.channel n)) x (k + 1) hk) = _
      simp_rw [prefixLaw_succ, ← Measure.map_smul]
      rw [← Measure.map_finset_sum' hsnoc.aemeasurable]
      rw [prefixMixture_compProd P θ p hp hθ n k hk]
      rw [ih (Nat.le_of_succ_le hk)]

/-- Marginalizing the IID four-cell input path in the paper transcript law
gives exactly the promoted finite-sequence law of the observed kernels. [The stated result](goal) follows. For [the displayed quantities and conditions](hyp:P,v,p,hp,n,u,hu), these specify the stated inputs. -/
theorem transcriptLaw_eq_observedKernelLaw {Z : OutputFamily}
    [∀ n i, MeasurableSpace (Z n i)] {ε : ℝ}
    (P : ProcedureSequence Z ε) (θ v : TrialParameter) (p : ℝ)
    (hp : InteriorAssignment p) (n : ℕ) (u : ℝ)
    (hu : InteriorMeans (parameterPath θ v u)) :
    transcriptLaw P (parameterPath θ v u) p n =
      Causalean.Stat.Minimax.SequentialScore.law
        (observedKernelFamily P θ v p n) u := by
  let θu := parameterPath θ v u
  have hQ (i : Fin n) : IsMarkovKernel (P.channel n i) := (P.privacy n).1 i
  have hdet (x : Fin n → Fin 4) :
      P.transcript n x = finiteSequenceTranscript (P.channel n) x :=
    (P.factorizes n).eq_finiteSequenceTranscript hQ x
  unfold transcriptLaw
  simp_rw [hdet]
  unfold finiteSequenceTranscript
  simp_rw [← Measure.map_smul]
  rw [← Measure.map_finset_sum' measurable_fsTranscriptToTranscript.aemeasurable]
  change Measure.map fsTranscriptToTranscript
      (prefixMixtureLaw (finiteSequenceKernel (P.channel n)) θu p n le_rfl) = _
  rw [prefixMixtureLaw_eq_observed P θu p hp hu n n le_rfl]
  unfold Causalean.Stat.Minimax.SequentialScore.law observedKernelFamily
  dsimp only [θu]
  ext A hA
  rw [Measure.map_apply measurable_fsTranscriptToTranscript hA]
  congr 1

end CausalSmith.Stat.LdpAteEfficiencySurface
