import CausalSmith.Stat.STAT_PomdpLatentOverlapMinimax_Research.Helpers.FiniteEncodingTransport

set_option linter.style.longLine false

/-!
# Finite witness encoding

A finite-symbol construction device for the paper's explicit hard families and
application.  It is used only to build witnesses; the ambient model in `Basic`
continues to allow arbitrary probability laws on real rewards.
-/

namespace CausalSmith.Stat.PomdpLatentOverlapMinimax

open MeasureTheory ProbabilityTheory
open scoped BigOperators ENNReal NNReal

/-- Embedding preserves the POMDP factorization generated by a finite path law. [the stated conclusion](goal). -/
lemma embed_pomdpKernelLaw {T nX nH nR : Nat} (F : FiniteRewardModel T nX nH nR) :
    PomdpKernelLaw (embed F) := by
  constructor
  · intro s a
    change IsProbabilityMeasure ((F.kernel s a).map (decodeFiniteStep F.rew)).toMeasure
    infer_instance
  · intro t
    letI : IsMarkovKernel (finiteRewardTransitionKernel F t) :=
      ⟨fun h ↦ by
        change IsProbabilityMeasure (F.kernel h.1.2 h.2).toMeasure
        infer_instance⟩
    letI : IsMarkovKernel (kernelOfK (embed F)) :=
      ⟨fun sa ↦ by
        rw [realKernel_embed_apply]
        exact Measure.isProbabilityMeasure_map
          (measurable_of_finite _).aemeasurable⟩
    rw [law_map_next_decode, law_map_action_decode,
      finite_next_factorization]
    symm
    refine map_compProd_of_fiber
      ((F.law.map (finiteHistActionPair t)).toMeasure)
      (finiteRewardTransitionKernel F t)
      (Kernel.comap (kernelOfK (embed F)) (currentStateAction t)
        (measurable_currentStateAction t))
      (decodeFiniteActionHistory t F.rew) (measurable_of_finite _)
      (decodeFiniteStep F.rew) (measurable_of_finite _) ?_
    intro ha
    rw [Kernel.comap_apply, realKernel_embed_apply]
    rfl

/-- Embedding preserves behavior-policy sequential randomization. [the stated conclusion](goal). -/
lemma embed_sequentialIgnorability {T nX nH nR : Nat}
    (F : FiniteRewardModel T nX nH nR) : SequentialIgnorability (embed F) := by
  constructor
  · intro x
    constructor
    · intro a
      exact ENNReal.toReal_nonneg
    · exact sum_pmf_toReal_eq_one (F.b x)
  · intro t
    letI : IsMarkovKernel (finiteBehaviourKernel F t) :=
      ⟨fun h ↦ by
        change IsProbabilityMeasure (F.b h.2.1).toMeasure
        infer_instance⟩
    letI : IsMarkovKernel (behaviourKernel (embed F)) :=
      ⟨fun x ↦ by
        rw [behaviourKernel_embed_apply]
        infer_instance⟩
    rw [law_map_action_decode, law_map_state_decode,
      finite_action_factorization]
    rw [show decodeFiniteActionHistory t F.rew =
        Prod.map (decodeFiniteStateHistory t F.rew) id by
      funext h
      rfl]
    symm
    refine map_compProd_of_fiber
      ((F.law.map (finiteHistStateView t)).toMeasure)
      (finiteBehaviourKernel F t)
      (Kernel.comap (behaviourKernel (embed F)) (currentObsState t)
        (measurable_currentObsState t))
      (decodeFiniteStateHistory t F.rew) (measurable_of_finite _)
      id measurable_id ?_
    intro h
    rw [Kernel.comap_apply, behaviourKernel_embed_apply]
    change (F.b h.2.1).toMeasure = Measure.map id (F.b h.2.1).toMeasure
    rw [Measure.map_id]

/-- Embedding transfers the pointwise reward-value bound to every observed trajectory epoch. [the stated conclusion](goal). -/
lemma embed_boundedReward {T nX nH nR : Nat} (F : FiniteRewardModel T nX nH nR) :
    BoundedReward (embed F) := by
  intro t
  let S : Set (FullTrajectory T nX nH) := {tau | |rewardAt t tau| ≤ 1}
  have hS : MeasurableSet S := by
    apply measurableSet_le
    · exact continuous_abs.measurable.comp
        (measurable_snd.comp (measurable_pi_apply t |>.comp measurable_snd))
    · exact measurable_const
  change (F.law.map (decodeTraj F.rew)).toMeasure S = 1
  rw [← PMF.toMeasure_map _ _ (measurable_of_finite _)]
  rw [Measure.map_apply (measurable_of_finite _) hS]
  have hpre : decodeTraj F.rew ⁻¹' S = Set.univ := by
    ext tau
    simp only [Set.mem_preimage, Set.mem_univ, iff_true]
    exact abs_le.mpr (F.rew_mem (tau.2 t).2)
  rw [hpre, measure_univ]

/-- Decoding reward symbols does not change the policy-induced state transition matrix. [the stated conclusion](goal). -/
lemma embed_policyKernel_eq {T nX nH nR : Nat} (F : FiniteRewardModel T nX nH nR)
    (p : Fin nX → PMF Bool) :
    policyKernel (embed F) (fun x a ↦ (p x a).toReal) = finitePolicyKernel F p := by
  funext s s'
  unfold policyKernel finitePolicyKernel embed
  apply Finset.sum_congr rfl
  intro a _
  congr 1
  congr 1
  change ((F.kernel s a).map (fun q ↦ (F.rew q.1, q.2))).toMeasure
      (Prod.snd ⁻¹' {s'}) = ∑ r, F.kernel s a (r, s')
  rw [PMF.toMeasure_map_apply _ _ _ (measurable_of_finite _)
    ((MeasurableSet.singleton s').preimage measurable_snd),
    PMF.toMeasure_apply_fintype, Fintype.sum_prod_type]
  classical
  simp only [Set.indicator_apply]
  simp

/-- The totalized stationary law agrees after finite reward decoding. [the stated conclusion](goal). -/
lemma embed_stationaryLaw_eq {T nX nH nR : Nat} (F : FiniteRewardModel T nX nH nR)
    (p : Fin nX → PMF Bool) :
    stationaryLaw (policyKernel (embed F) (fun x a ↦ (p x a).toReal)) =
      stationaryLaw (finitePolicyKernel F p) := by
  rw [embed_policyKernel_eq]

/-- The real-reward target equals the finite reward-symbol target. [the stated conclusion](goal). -/
lemma embed_targetValue_eq {T nX nH nR : Nat} (F : FiniteRewardModel T nX nH nR) :
    targetValue (embed F) = finiteTargetValue F := by
  unfold targetValue finiteTargetValue rewardRegression
  have he : (embed F).e = fun x a ↦ (F.e x a).toReal := rfl
  rw [he, embed_policyKernel_eq]
  apply Finset.sum_congr rfl
  intro s _
  congr 1
  apply Finset.sum_congr rfl
  intro a _
  congr 1
  change (∫ q, q.1 ∂(((F.kernel s a).map
      (fun p ↦ (F.rew p.1, p.2))).toMeasure)) = _
  rw [← PMF.toMeasure_map _ _ (measurable_of_finite _)]
  rw [MeasureTheory.integral_map (measurable_of_finite _).aemeasurable
    measurable_fst.aestronglyMeasurable, PMF.integral_eq_sum]
  simp only [smul_eq_mul]

/-- The embedded observed law is the decoded finite observed law. [the stated conclusion](goal). -/
lemma embed_obsLaw_eq {T nX nH nR : Nat} (F : FiniteRewardModel T nX nH nR) :
    obsLaw (embed F) =
      (F.obsPMF.map (fun w t ↦ ((w t).1, (w t).2.1, F.rew (w t).2.2))).toMeasure := by
  unfold obsLaw FiniteRewardModel.obsPMF
  change Measure.map obsProj ((F.law.map (decodeTraj F.rew)).toMeasure) = _
  rw [PMF.toMeasure_map _ _ (by
    unfold obsProj curState actionAt rewardAt
    measurability)]
  rw [PMF.map_comp, PMF.map_comp]
  congr 2

/-- Absolute continuity of finite observed laws survives reward decoding. [the hrew condition](hyp:hrew). [the stated conclusion](goal). -/
lemma embed_absolutelyContinuous {T nX nH nR : Nat}
    {F G : FiniteRewardModel T nX nH nR}
    (h : F.obsPMF.toMeasure ≪ G.obsPMF.toMeasure) (hrew : F.rew = G.rew) :
    obsLaw (embed F) ≪ obsLaw (embed G) := by
  rw [embed_obsLaw_eq, embed_obsLaw_eq,
    ← PMF.toMeasure_map _ _ (measurable_of_finite _),
    ← PMF.toMeasure_map _ _ (measurable_of_finite _), hrew]
  exact h.map (measurable_of_finite _)

/-- Data processing transports a finite observed-law KL budget to the decoded laws. [the hrew condition](hyp:hrew). [the stated conclusion](goal). -/
lemma embed_klDiv_le {T nX nH nR : Nat}
    {F G : FiniteRewardModel T nX nH nR} (hrew : F.rew = G.rew) :
    InformationTheory.klDiv (obsLaw (embed F)) (obsLaw (embed G)) ≤
      InformationTheory.klDiv F.obsPMF.toMeasure G.obsPMF.toMeasure := by
  rw [embed_obsLaw_eq, embed_obsLaw_eq,
    ← PMF.toMeasure_map _ _ (measurable_of_finite _),
    ← PMF.toMeasure_map _ _ (measurable_of_finite _), hrew]
  exact InformationTheory.klDiv_map_le _ _ (measurable_of_finite _)

end CausalSmith.Stat.PomdpLatentOverlapMinimax
