import CausalSmith.Stat.STAT_DiscreteOptimalValueMinimaxMatched_Research.Helpers.TwoPointLower
import Causalean.Estimation.MinimaxATE.ConstCenterHalf.Parametric
import Mathlib.Analysis.Complex.ExponentialBounds

/-! A regular parametric submodel for the bounded-alphabet lower bound. -/

namespace CausalSmith.Stat.DiscreteOptimalValueMinimaxMatched

open MeasureTheory

/-- For [the specified validity certificate](hyp:hv), the [regular null law is the discrete observed law generated by the valid null parametric data-generating process](goal). -/
noncomputable def regularNullLaw {d : ℕ} [Nonempty (Fin d)]
    {g : ℝ} (hv : Causalean.Estimation.MinimaxATE.ValidDGP
      (Causalean.Estimation.MinimaxATE.Parametric.mC (C := Fin d) (1 / 2))
      (Causalean.Estimation.MinimaxATE.Parametric.gNull (C := Fin d) g g)) :
    DiscreteLaw d :=
  ⟨Causalean.Estimation.MinimaxATE.obsPMF hv⟩

/-- For [the specified validity certificate](hyp:hv), the [regular perturbed law is the discrete observed law generated by the valid perturbed parametric data-generating process](goal). -/
noncomputable def regularPerturbedLaw {d : ℕ} [Nonempty (Fin d)]
    {g delta : ℝ} (hv : Causalean.Estimation.MinimaxATE.ValidDGP
      (Causalean.Estimation.MinimaxATE.Parametric.mC (C := Fin d) (1 / 2))
      (Causalean.Estimation.MinimaxATE.Parametric.gPert (C := Fin d) g g delta)) :
    DiscreteLaw d :=
  ⟨Causalean.Estimation.MinimaxATE.obsPMF hv⟩

/-- If [the stated v condition holds](hyp:hv), then [the stated regular null law joint mass relation holds](goal). -/
lemma regularNullLaw_jointMass {d : ℕ} [Nonempty (Fin d)]
    {g : ℝ} (hv : Causalean.Estimation.MinimaxATE.ValidDGP
      (Causalean.Estimation.MinimaxATE.Parametric.mC (C := Fin d) (1 / 2))
      (Causalean.Estimation.MinimaxATE.Parametric.gNull (C := Fin d) g g))
    (x : Fin d) (a y : Bool) :
    jointMass (regularNullLaw hv) x a y =
      Causalean.Estimation.MinimaxATE.obsReal
        (Causalean.Estimation.MinimaxATE.Parametric.mC (C := Fin d) (1 / 2))
        (Causalean.Estimation.MinimaxATE.Parametric.gNull (C := Fin d) g g) (x, a, y) := by
  simp [jointMass, regularNullLaw, Causalean.Estimation.MinimaxATE.obsPMF]
  simpa [one_div] using Causalean.Estimation.MinimaxATE.obsReal_nonneg hv (x, a, y)

/-- If [the stated v condition holds](hyp:hv), then [the stated regular perturbed law joint mass relation holds](goal). -/
lemma regularPerturbedLaw_jointMass {d : ℕ} [Nonempty (Fin d)]
    {g delta : ℝ} (hv : Causalean.Estimation.MinimaxATE.ValidDGP
      (Causalean.Estimation.MinimaxATE.Parametric.mC (C := Fin d) (1 / 2))
      (Causalean.Estimation.MinimaxATE.Parametric.gPert (C := Fin d) g g delta))
    (x : Fin d) (a y : Bool) :
    jointMass (regularPerturbedLaw hv) x a y =
      Causalean.Estimation.MinimaxATE.obsReal
        (Causalean.Estimation.MinimaxATE.Parametric.mC (C := Fin d) (1 / 2))
        (Causalean.Estimation.MinimaxATE.Parametric.gPert (C := Fin d) g g delta) (x, a, y) := by
  simp [jointMass, regularPerturbedLaw, Causalean.Estimation.MinimaxATE.obsPMF]
  simpa [one_div] using Causalean.Estimation.MinimaxATE.obsReal_nonneg hv (x, a, y)

/-- If [the alphabet size satisfies its stated restriction](hyp:hd), and [the overlap parameter satisfies its stated range restriction](hyp:hepsilon), and [the stated v condition holds](hyp:hv), then [the stated regular null law model relation holds](goal). -/
lemma regularNullLaw_model {d : ℕ} [Nonempty (Fin d)] {epsilon g : ℝ}
    (hd : 2 ≤ d)
    (hepsilon : 0 < epsilon ∧ epsilon < 1 / 2)
    (hv : Causalean.Estimation.MinimaxATE.ValidDGP
      (Causalean.Estimation.MinimaxATE.Parametric.mC (C := Fin d) (1 / 2))
      (Causalean.Estimation.MinimaxATE.Parametric.gNull (C := Fin d) g g)) :
    ObservedModelClass epsilon (regularNullLaw hv) := by
  refine ⟨hd, hepsilon.1, hepsilon.2, ?_⟩
  intro x hx
  have hcard : (Fintype.card (Fin d) : ℝ) ≠ 0 :=
    Nat.cast_ne_zero.mpr Fintype.card_ne_zero
  have hmass : cellMass (regularNullLaw hv) x =
      (Fintype.card (Fin d) : ℝ)⁻¹ := by
    simp [cellMass, regularNullLaw_jointMass,
      Causalean.Estimation.MinimaxATE.obsReal,
      Causalean.Estimation.MinimaxATE.Parametric.mC,
      Causalean.Estimation.MinimaxATE.Parametric.gNull]
    ring
  have harm : armMass (regularNullLaw hv) true x =
      (1 / 2) * (Fintype.card (Fin d) : ℝ)⁻¹ := by
    simp [armMass, regularNullLaw_jointMass,
      Causalean.Estimation.MinimaxATE.obsReal,
      Causalean.Estimation.MinimaxATE.Parametric.mC,
      Causalean.Estimation.MinimaxATE.Parametric.gNull]
    ring
  rw [propensity, hmass, harm]
  field_simp
  constructor <;> linarith

/-- If [the alphabet size satisfies its stated restriction](hyp:hd), and [the overlap parameter satisfies its stated range restriction](hyp:hepsilon), and [the stated v condition holds](hyp:hv), then [the stated regular perturbed law model relation holds](goal). -/
lemma regularPerturbedLaw_model {d : ℕ} [Nonempty (Fin d)] {epsilon g delta : ℝ}
    (hd : 2 ≤ d)
    (hepsilon : 0 < epsilon ∧ epsilon < 1 / 2)
    (hv : Causalean.Estimation.MinimaxATE.ValidDGP
      (Causalean.Estimation.MinimaxATE.Parametric.mC (C := Fin d) (1 / 2))
      (Causalean.Estimation.MinimaxATE.Parametric.gPert (C := Fin d) g g delta)) :
    ObservedModelClass epsilon (regularPerturbedLaw hv) := by
  refine ⟨hd, hepsilon.1, hepsilon.2, ?_⟩
  intro x hx
  have hcard : (Fintype.card (Fin d) : ℝ) ≠ 0 :=
    Nat.cast_ne_zero.mpr Fintype.card_ne_zero
  have hmass : cellMass (regularPerturbedLaw hv) x =
      (Fintype.card (Fin d) : ℝ)⁻¹ := by
    simp [cellMass, regularPerturbedLaw_jointMass,
      Causalean.Estimation.MinimaxATE.obsReal,
      Causalean.Estimation.MinimaxATE.Parametric.mC,
      Causalean.Estimation.MinimaxATE.Parametric.gPert]
    ring
  have harm : armMass (regularPerturbedLaw hv) true x =
      (1 / 2) * (Fintype.card (Fin d) : ℝ)⁻¹ := by
    simp [armMass, regularPerturbedLaw_jointMass,
      Causalean.Estimation.MinimaxATE.obsReal,
      Causalean.Estimation.MinimaxATE.Parametric.mC,
      Causalean.Estimation.MinimaxATE.Parametric.gPert]
    ring
  rw [propensity, hmass, harm]
  field_simp
  constructor <;> linarith

/-- If [the stated v condition holds](hyp:hv), and [the observed law satisfies the stated model restrictions](hyp:hP), then [the stated regular null law value relation holds](goal). -/
lemma regularNullLaw_value {d : ℕ} [Nonempty (Fin d)] {epsilon g : ℝ}
    (hv : Causalean.Estimation.MinimaxATE.ValidDGP
      (Causalean.Estimation.MinimaxATE.Parametric.mC (C := Fin d) (1 / 2))
      (Causalean.Estimation.MinimaxATE.Parametric.gNull (C := Fin d) g g))
    (hP : ObservedModelClass epsilon (regularNullLaw hv)) :
    observedOptimalValue (regularNullLaw hv) hP = g := by
  rw [observedOptimalValue, observedOptimalValueRaw]
  have hcard : (Fintype.card (Fin d) : ℝ) ≠ 0 :=
    Nat.cast_ne_zero.mpr Fintype.card_ne_zero
  have hdcast : (d : ℝ) ≠ 0 := by simpa using hcard
  simp [cellMass, outcomeMean, armMass, regularNullLaw_jointMass,
    Causalean.Estimation.MinimaxATE.obsReal,
    Causalean.Estimation.MinimaxATE.Parametric.mC,
    Causalean.Estimation.MinimaxATE.Parametric.gNull]
  field_simp [hdcast] <;> ring_nf <;> simp

/-- If [the stated delta condition holds](hyp:hdelta), and [the stated v condition holds](hyp:hv), and [the observed law satisfies the stated model restrictions](hyp:hP), then [the stated regular perturbed law value relation holds](goal). -/
lemma regularPerturbedLaw_value {d : ℕ} [Nonempty (Fin d)] {epsilon g delta : ℝ}
    (hdelta : 0 ≤ delta)
    (hv : Causalean.Estimation.MinimaxATE.ValidDGP
      (Causalean.Estimation.MinimaxATE.Parametric.mC (C := Fin d) (1 / 2))
      (Causalean.Estimation.MinimaxATE.Parametric.gPert (C := Fin d) g g delta))
    (hP : ObservedModelClass epsilon (regularPerturbedLaw hv)) :
    observedOptimalValue (regularPerturbedLaw hv) hP = g + delta := by
  rw [observedOptimalValue, observedOptimalValueRaw]
  have hcard : (Fintype.card (Fin d) : ℝ) ≠ 0 :=
    Nat.cast_ne_zero.mpr Fintype.card_ne_zero
  have hdcast : (d : ℝ) ≠ 0 := by simpa using hcard
  simp [cellMass, outcomeMean, armMass, regularPerturbedLaw_jointMass,
    Causalean.Estimation.MinimaxATE.obsReal,
    Causalean.Estimation.MinimaxATE.Parametric.mC,
    Causalean.Estimation.MinimaxATE.Parametric.gPert]
  field_simp [hdcast] <;> ring_nf <;>
    simp [max_eq_right (by linarith : g ≤ g + delta)] <;> ring

/-- If [the overlap parameter satisfies its stated range restriction](hyp:hepsilon), and [the sample size satisfies its stated restriction](hyp:hn), and [the alphabet size satisfies its stated restriction](hyp:hd), then [every admissible model has minimax risk at least $1/(100n)$](goal). -/
lemma regular_parametric_lower {epsilon : ℝ}
    (hepsilon : 0 < epsilon ∧ epsilon < 1 / 2)
    (n d : ℕ) (hn : 1 ≤ n) (hd : 2 ≤ d) :
    1 / (100 * (n : ℝ)) ≤ minimaxRisk n d epsilon := by
  letI : Nonempty (Fin d) := ⟨⟨0, lt_of_lt_of_le Nat.zero_lt_two hd⟩⟩
  let delta : ℝ := (2 / 5) / Real.sqrt n
  have hnR : (0 : ℝ) < n := by exact_mod_cast hn
  have hdelta0 : 0 ≤ delta := by dsimp [delta]; positivity
  have hdeltasq : delta ^ 2 = 4 / (25 * (n : ℝ)) := by
    dsimp [delta]
    rw [div_pow, Real.sq_sqrt hnR.le]
    ring
  let hv0 := Causalean.Estimation.MinimaxATE.Parametric.validDGP_null
    (C := Fin d) (m₀ := (1 / 2 : ℝ)) (g₀ := (1 / 2 : ℝ)) (g₁ := (1 / 2 : ℝ))
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
  have hdeltaU : (1 / 2 : ℝ) + delta ≤ 1 := by
    have hsqrt_one : 1 ≤ Real.sqrt (n : ℝ) := Real.one_le_sqrt.mpr (by exact_mod_cast hn)
    have : delta ≤ 2 / 5 := by
      dsimp [delta]
      exact div_le_self (by norm_num) hsqrt_one
    linarith
  let hv1 := Causalean.Estimation.MinimaxATE.Parametric.validDGP_pert
    (C := Fin d) (m₀ := (1 / 2 : ℝ)) (g₀ := (1 / 2 : ℝ)) (g₁ := (1 / 2 : ℝ))
    (δ := delta) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) hdelta0 hdeltaU
  let P0 : DiscreteLaw d := regularNullLaw hv0
  let P1 : DiscreteLaw d := regularPerturbedLaw hv1
  have hP0 : ObservedModelClass epsilon P0 := regularNullLaw_model hd hepsilon hv0
  have hP1 : ObservedModelClass epsilon P1 := regularPerturbedLaw_model hd hepsilon hv1
  let MP0 : ModelLaw d epsilon := ⟨P0, hP0⟩
  let MP1 : ModelLaw d epsilon := ⟨P1, hP1⟩
  have ht0 : observedOptimalValue P0 hP0 = 1 / 2 := regularNullLaw_value hv0 hP0
  have ht1 : observedOptimalValue P1 hP1 = 1 / 2 + delta :=
    regularPerturbedLaw_value hdelta0 hv1 hP1
  have hreg : (n : ℝ) *
      ((1 / 2 : ℝ) * delta ^ 2 / ((1 / 2 : ℝ) * (1 - 1 / 2))) ≤ Real.log 2 := by
    rw [hdeltasq]
    have hlog : (8 / 25 : ℝ) ≤ Real.log 2 :=
      le_trans (by norm_num) (le_of_lt Real.log_two_gt_d9)
    convert hlog using 1 <;> field_simp <;> ring
  have htv : Causalean.Stat.tvDist (productLaw P0 n) (productLaw P1 n) ≤ 1 / 2 := by
    simpa [P0, P1, regularNullLaw, regularPerturbedLaw, productLaw, obsLaw,
      Causalean.Estimation.MinimaxATE.productLaw,
      Causalean.Estimation.MinimaxATE.obsLaw] using
      (Causalean.Estimation.MinimaxATE.Parametric.tvDist_productLaw_le_half
        hv0 hv1 (by norm_num) (by norm_num) (by norm_num) (by norm_num)
        (by norm_num) (by norm_num) hreg)
  have hsep : 2 * (delta / 2) ≤
      |observedOptimalValue MP0.1 MP0.2 - observedOptimalValue MP1.1 MP1.2| := by
      rw [show observedOptimalValue MP0.1 MP0.2 = (1 / 2 : ℝ) by
        simpa [MP0] using ht0,
        show observedOptimalValue MP1.1 MP1.2 = (1 / 2 : ℝ) + delta by
          simpa [MP1] using ht1]
      rw [show (1 / 2 : ℝ) - (1 / 2 + delta) = -delta by ring,
        abs_neg, abs_of_nonneg hdelta0]
      ring_nf
      exact le_refl delta
  have hlow := minimaxRisk_ge_two_model_tv MP0 MP1 (s := delta / 2)
    (by positivity) hsep htv
  calc
    1 / (100 * (n : ℝ)) = (delta / 2) ^ 2 / 4 := by
      rw [show (delta / 2) ^ 2 = delta ^ 2 / 4 by ring, hdeltasq]
      field_simp <;> ring_nf
    _ ≤ minimaxRisk n d epsilon := hlow

end CausalSmith.Stat.DiscreteOptimalValueMinimaxMatched
