/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan

# Marginal Sensitivity Model — constructing the calibrating cutoff

`msmUpperCalib_eq_cutoff` and `cutoffProp_mem_MSMSetCalib_of_survival` reduce the calibrated
upper endpoint to one construction: a `σ(X)`-measurable cutoff `c` solving the
conditional-survival equation `treatedSurv c =ᵐ survTarget Λ`. This file begins that construction,
whose capstone assumes universal cutoff integrability.

The cutoff is the conditional quantile `Q_{τ}(X)` of `Y` among the treated, where the level
`τ(X) = 1 − survTarget(X)/e(X)` (`calibLevel`) is set by the sensitivity budget. The construction uses:
* the **treated push-forward law** `treatedXYLaw = ((μ↾{D=1}) ∘ (X,Y))` and Mathlib's `condCDF` of it —
  the conditional CDF of `Y` given `X` among the treated;
* the **bridge** `treatedSurv_const_eq`: `E[Z·1{Y>t}|σ(X)] = e(X)·(1 − F(t|X))` (relating the weighted
  conditional survival to the treated conditional CDF);
* the **measurable conditional quantile** `Causalean.Mathlib.measurable_condQuantile_and_attains`
  (atomless conditional law ⇒ a measurable cutoff attaining any interior level), at level `τ(X)`.

**Atomless / continuous-outcome hypothesis.** Exact attainment needs the treated conditional law of `Y`
to be atomless (`condCDF` continuous) — the Dorn–Guo continuous-outcome caveat, carried as a hypothesis.

Scope: the upper bound (treated). The lower bound and the ATE specialization mirror this. -/

module
public import Causalean.Mathlib.Probability.MeasurableCondQuantile
public import Causalean.PO.ID.Partial.Sensitivity.MSM.CutoffSelection
public import Causalean.PO.ID.Partial.Sensitivity.MSM.QuantileBalance
public import Causalean.Tactic.Attr

/-! # Treated-law definitions and the constant-cutoff survival bridge

This part defines the treated push-forward law, its conditional distribution function, the
calibration level, and proves the constant-cutoff conditional-survival identity. -/

@[expose] public section

namespace Causalean
namespace PO

open MeasureTheory ProbabilityTheory

namespace POBackdoorSystem

variable {P : POSystem} {γ : Type*} [MeasurableSpace γ]
variable (S : POBackdoorSystem P γ)

/-- Given [a backdoor system and an event in its sample space](hyp:P,γ,S,s), if [the event is
measurable with respect to the σ-algebra generated by the factual covariate](hyp:hs), then [it is
the preimage under that covariate of some measurable covariate set](goal). -/
lemma exists_measurableSet_through_factualX {s : Set P.Ω}
    (hs : MeasurableSet[S.sigmaX] s) :
    ∃ B : Set γ, MeasurableSet B ∧ S.factualX ⁻¹' B = s := by
  rw [POBackdoorSystem.sigmaX] at hs
  exact MeasurableSpace.measurableSet_comap.mp hs

/-- For [a potential-outcomes system](hyp:P), [a measurable covariate space](hyp:γ), and
[a back-door system on them](hyp:S), [the treated set](goal) is the set of all units whose factual
treatment status is treatment. -/
def treatedSet : Set P.Ω := S.factualD ⁻¹' {true}

/-- For [a potential-outcomes system](hyp:P), [a measurable covariate space](hyp:γ), and
[a back-door system on them](hyp:S), [the treated covariate--outcome law](goal) is the image law
of the factual covariate and factual outcome under the population measure restricted to treated
units. -/
noncomputable def treatedXYLaw : Measure (γ × ℝ) :=
  (P.μ.restrict S.treatedSet).map (fun ω => (S.factualX ω, S.factualY ω))

/-- The treated push-forward law of the covariate and outcome is the image, under the map
recording the factual covariate and factual outcome, of the population measure restricted to the
treated set. -/
@[causal_defs_simps]
lemma treatedXYLaw_eq :
    S.treatedXYLaw =
      (P.μ.restrict S.treatedSet).map (fun ω => (S.factualX ω, S.factualY ω)) :=
  rfl

/-- For [a potential-outcomes system](hyp:P), [a measurable covariate space](hyp:γ),
[a back-door system on them](hyp:S), [a unit](hyp:ω), and [a real threshold](hyp:t), [the treated
conditional distribution-function value](goal) is the probability that a treated unit's factual
outcome does not exceed the threshold, conditional on having that unit's factual covariate value. -/
noncomputable def treatedCondCDF (ω : P.Ω) (t : ℝ) : ℝ :=
  condCDF S.treatedXYLaw (S.factualX ω) t

/-- For [a backdoor system](hyp:P,γ,S), [the event of receiving treatment is measurable](goal). -/
lemma measurableSet_treatedSet : MeasurableSet S.treatedSet := by
  unfold POBackdoorSystem.treatedSet
  exact MeasurableSet.singleton true |>.preimage S.measurable_factualD

/-- For [a backdoor system](hyp:P,γ,S), [the indicator of factual treatment being true equals
the indicator of the treated event](goal). -/
lemma treated_indicator_eq :
    S.dVar.indicator true = S.treatedSet.indicator (fun _ : P.Ω => (1 : ℝ)) := by
  funext ω
  unfold POBackdoorSystem.treatedSet POVar.indicator POVar.event POBackdoorSystem.factualD
  rfl

/-- For [a backdoor system](hyp:P,γ,S), [the covariate marginal of the unnormalized treated
covariate-outcome law is the factual-covariate law restricted to the treated event](goal). -/
lemma treatedXYLaw_fst :
    S.treatedXYLaw.fst = (P.μ.restrict S.treatedSet).map S.factualX := by
  unfold POBackdoorSystem.treatedXYLaw MeasureTheory.Measure.fst
  rw [MeasureTheory.Measure.map_map measurable_fst
    (S.measurable_factualX.prodMk S.measurable_factualY)]
  rfl

private lemma treated_le_indicator_eq (t : ℝ) :
    (fun ω => S.dVar.indicator true ω * (if S.factualY ω ≤ t then (1 : ℝ) else 0))
      = fun ω => (S.treatedSet ∩ {ω | S.factualY ω ≤ t}).indicator
          (fun _ : P.Ω => (1 : ℝ)) ω := by
  funext ω
  unfold POBackdoorSystem.treatedSet POVar.indicator POVar.event POBackdoorSystem.factualD
  by_cases hD : S.dVar.factual ω = true <;> by_cases hY : S.factualY ω ≤ t <;>
    simp [hD, hY]

private lemma measurableSet_factualY_le (t : ℝ) : MeasurableSet {ω | S.factualY ω ≤ t} :=
  measurableSet_le S.measurable_factualY measurable_const

private lemma integrable_treated_le_indicator (t : ℝ) :
    Integrable (fun ω => S.dVar.indicator true ω *
      (if S.factualY ω ≤ t then (1 : ℝ) else 0)) P.μ := by
  rw [treated_le_indicator_eq]
  exact (integrable_const (α := P.Ω) (μ := P.μ) (c := (1 : ℝ))).indicator
    ((S.measurableSet_treatedSet).inter (S.measurableSet_factualY_le t))

/-- At a fixed outcome level, the treated conditional CDF depends on the unit only through the
observed covariate, so it is measurable for the covariate σ-algebra. -/
@[fun_prop]
lemma measurable_treatedCondCDF_const (t : ℝ) :
    Measurable[S.sigmaX] (fun ω => S.treatedCondCDF ω t) := by
  rw [POBackdoorSystem.sigmaX]
  unfold POBackdoorSystem.treatedCondCDF
  exact (ProbabilityTheory.measurable_condCDF S.treatedXYLaw t).comp
    (comap_measurable S.factualX)

/-- The strongly-measurable form, for the covariate σ-algebra, of the treated conditional CDF at a
fixed outcome level. -/
@[fun_prop]
lemma stronglyMeasurable_treatedCondCDF_const (t : ℝ) :
    StronglyMeasurable[S.sigmaX] (fun ω => S.treatedCondCDF ω t) :=
  (S.measurable_treatedCondCDF_const t).stronglyMeasurable

/-- The treated conditional CDF at a fixed outcome level is measurable for the ambient σ-algebra as
well as for the covariate one. -/
@[fun_prop]
lemma measurable_treatedCondCDF_const_ambient (t : ℝ) :
    Measurable (fun ω => S.treatedCondCDF ω t) :=
  (S.measurable_treatedCondCDF_const t).mono S.sigmaX_le le_rfl

private lemma eventually_norm_treatedCondCDF_le_one (t : ℝ) :
    ∀ᵐ ω ∂P.μ, ‖S.treatedCondCDF ω t‖ ≤ 1 := by
  exact Filter.Eventually.of_forall fun ω => by
    unfold POBackdoorSystem.treatedCondCDF
    rw [Real.norm_of_nonneg (ProbabilityTheory.condCDF_nonneg S.treatedXYLaw (S.factualX ω) t)]
    exact ProbabilityTheory.condCDF_le_one S.treatedXYLaw (S.factualX ω) t

private lemma integrable_propScore_mul_treatedCondCDF (t : ℝ) :
    Integrable (fun ω => S.propScore true ω * S.treatedCondCDF ω t) P.μ := by
  have he : Integrable (S.propScore true) P.μ := by
    unfold POBackdoorSystem.propScore
    exact MeasureTheory.integrable_condExp
  exact he.mul_bdd
    ((S.measurable_treatedCondCDF_const_ambient t).aestronglyMeasurable)
    (S.eventually_norm_treatedCondCDF_le_one t)

private lemma integrable_treated_indicator_mul_treatedCondCDF (t : ℝ) :
    Integrable (fun ω => S.dVar.indicator true ω * S.treatedCondCDF ω t) P.μ := by
  exact (S.dVar.integrable_indicator true (MeasurableSet.singleton true)).mul_bdd
    ((S.measurable_treatedCondCDF_const_ambient t).aestronglyMeasurable)
    (S.eventually_norm_treatedCondCDF_le_one t)

private lemma setIntegral_propScore_mul_treatedCondCDF_eq_le (t : ℝ)
    (s : Set P.Ω) (hs : MeasurableSet[S.sigmaX] s) :
    ∫ ω in s, S.propScore true ω * S.treatedCondCDF ω t ∂P.μ =
      ∫ ω in s, S.dVar.indicator true ω *
        (if S.factualY ω ≤ t then (1 : ℝ) else 0) ∂P.μ := by
  classical
  obtain ⟨B, hB, rfl⟩ := S.exists_measurableSet_through_factualX hs
  let F : γ → ℝ := fun a => condCDF S.treatedXYLaw a t
  have hpre_m : MeasurableSet[S.sigmaX] (S.factualX ⁻¹' B) := by
    rw [POBackdoorSystem.sigmaX]
    exact ⟨B, hB, rfl⟩
  have hpre : MeasurableSet (S.factualX ⁻¹' B) := hB.preimage S.measurable_factualX
  have hpull :
      P.μ[fun ω => S.dVar.indicator true ω * S.treatedCondCDF ω t | S.sigmaX]
        =ᵐ[P.μ] (fun ω => S.propScore true ω * S.treatedCondCDF ω t) := by
    have h := MeasureTheory.condExp_mul_of_stronglyMeasurable_right
      (m := S.sigmaX) (μ := P.μ)
      (S.stronglyMeasurable_treatedCondCDF_const t)
      (S.integrable_treated_indicator_mul_treatedCondCDF t)
      (S.dVar.integrable_indicator true (MeasurableSet.singleton true))
    exact h.trans (Filter.EventuallyEq.of_eq (by funext ω; rfl))
  have hleft_to_ZF :
      ∫ ω in S.factualX ⁻¹' B, S.propScore true ω * S.treatedCondCDF ω t ∂P.μ =
        ∫ ω in S.factualX ⁻¹' B, S.dVar.indicator true ω *
          S.treatedCondCDF ω t ∂P.μ := by
    calc
      ∫ ω in S.factualX ⁻¹' B, S.propScore true ω * S.treatedCondCDF ω t ∂P.μ
          = ∫ ω in S.factualX ⁻¹' B,
              P.μ[fun ω => S.dVar.indicator true ω * S.treatedCondCDF ω t | S.sigmaX] ω
                ∂P.μ := by
              refine MeasureTheory.setIntegral_congr_ae hpre ?_
              filter_upwards [hpull] with ω hω _hmem
              exact hω.symm
      _ = ∫ ω in S.factualX ⁻¹' B, S.dVar.indicator true ω *
            S.treatedCondCDF ω t ∂P.μ := by
          exact MeasureTheory.setIntegral_condExp S.sigmaX_le
            (S.integrable_treated_indicator_mul_treatedCondCDF t) hpre_m
  have hZF_indicator :
      ∫ ω in S.factualX ⁻¹' B, S.dVar.indicator true ω *
          S.treatedCondCDF ω t ∂P.μ =
        ∫ ω in (S.factualX ⁻¹' B) ∩ S.treatedSet, S.treatedCondCDF ω t ∂P.μ := by
    have hcongr : Set.EqOn
        (fun ω => S.dVar.indicator true ω * S.treatedCondCDF ω t)
        (fun ω => S.treatedSet.indicator (fun ω => S.treatedCondCDF ω t) ω)
        (S.factualX ⁻¹' B) := by
      intro ω _hω
      rw [S.treated_indicator_eq]
      by_cases hT : ω ∈ S.treatedSet <;>
        simp [Set.indicator_of_mem, Set.indicator_of_notMem, hT]
    calc
      ∫ ω in S.factualX ⁻¹' B, S.dVar.indicator true ω *
          S.treatedCondCDF ω t ∂P.μ
          = ∫ ω in S.factualX ⁻¹' B,
              S.treatedSet.indicator (fun ω => S.treatedCondCDF ω t) ω ∂P.μ :=
            MeasureTheory.setIntegral_congr_fun hpre hcongr
      _ = ∫ ω in (S.factualX ⁻¹' B) ∩ S.treatedSet, S.treatedCondCDF ω t ∂P.μ := by
            rw [MeasureTheory.setIntegral_indicator S.measurableSet_treatedSet]
  have hmap :
      ∫ a in B, F a ∂S.treatedXYLaw.fst =
        ∫ ω in (S.factualX ⁻¹' B) ∩ S.treatedSet, S.treatedCondCDF ω t ∂P.μ := by
    have hF_aesm : AEStronglyMeasurable F S.treatedXYLaw.fst :=
      (ProbabilityTheory.measurable_condCDF S.treatedXYLaw t).aestronglyMeasurable
    calc
      ∫ a in B, F a ∂S.treatedXYLaw.fst
          = ∫ a in B, F a ∂((P.μ.restrict S.treatedSet).map S.factualX) := by
              rw [S.treatedXYLaw_fst]
      _ = ∫ ω in S.factualX ⁻¹' B, F (S.factualX ω) ∂(P.μ.restrict S.treatedSet) := by
              exact MeasureTheory.setIntegral_map hB (by simpa [S.treatedXYLaw_fst] using hF_aesm)
                S.measurable_factualX.aemeasurable
      _ = ∫ ω in (S.factualX ⁻¹' B) ∩ S.treatedSet, F (S.factualX ω) ∂P.μ := by
              rw [MeasureTheory.Measure.restrict_restrict hpre]
      _ = ∫ ω in (S.factualX ⁻¹' B) ∩ S.treatedSet, S.treatedCondCDF ω t ∂P.μ := by
              rfl
  haveI : IsFiniteMeasure S.treatedXYLaw := by
    unfold POBackdoorSystem.treatedXYLaw
    infer_instance
  have hcondcdf :
      ∫ a in B, F a ∂S.treatedXYLaw.fst = S.treatedXYLaw.real (B ×ˢ Set.Iic t) := by
    simpa [F] using ProbabilityTheory.setIntegral_condCDF S.treatedXYLaw t hB
  have hpush :
      S.treatedXYLaw (B ×ˢ Set.Iic t) =
        P.μ ((S.factualX ⁻¹' B ∩ {ω | S.factualY ω ≤ t}) ∩ S.treatedSet) := by
    unfold POBackdoorSystem.treatedXYLaw
    have hpair : Measurable (fun ω : P.Ω => (S.factualX ω, S.factualY ω)) :=
      S.measurable_factualX.prodMk S.measurable_factualY
    have hprod : MeasurableSet (B ×ˢ Set.Iic t : Set (γ × ℝ)) :=
      hB.prod measurableSet_Iic
    rw [MeasureTheory.Measure.map_apply hpair hprod]
    rw [MeasureTheory.Measure.restrict_apply (hprod.preimage hpair)]
    apply congrArg P.μ
    ext ω
    simp [Set.mem_prod, Set.mem_Iic, and_assoc]
  have hleft_measure :
      ∫ ω in S.factualX ⁻¹' B, S.propScore true ω * S.treatedCondCDF ω t ∂P.μ =
        P.μ.real ((S.factualX ⁻¹' B ∩ {ω | S.factualY ω ≤ t}) ∩ S.treatedSet) := by
    rw [hleft_to_ZF, hZF_indicator, ← hmap, hcondcdf]
    rw [MeasureTheory.measureReal_def, hpush, MeasureTheory.measureReal_def]
  have hright_measure :
      ∫ ω in S.factualX ⁻¹' B,
        S.dVar.indicator true ω * (if S.factualY ω ≤ t then (1 : ℝ) else 0) ∂P.μ =
        P.μ.real ((S.factualX ⁻¹' B ∩ {ω | S.factualY ω ≤ t}) ∩ S.treatedSet) := by
    rw [S.treated_le_indicator_eq t]
    rw [MeasureTheory.setIntegral_indicator
      ((S.measurableSet_treatedSet).inter (S.measurableSet_factualY_le t))]
    rw [MeasureTheory.setIntegral_const]
    simp only [smul_eq_mul, mul_one]
    rw [MeasureTheory.measureReal_def]
    apply congrArg ENNReal.toReal
    congr 1
    ext ω
    simp [and_assoc, and_comm]
  rw [hleft_measure, hright_measure]

private lemma treatedLe_const_eq (t : ℝ) :
    P.μ[fun ω => S.dVar.indicator true ω *
      (if S.factualY ω ≤ t then (1 : ℝ) else 0) | S.sigmaX]
      =ᵐ[P.μ] fun ω => S.propScore true ω * S.treatedCondCDF ω t := by
  classical
  set f : P.Ω → ℝ := fun ω => S.dVar.indicator true ω *
    (if S.factualY ω ≤ t then (1 : ℝ) else 0)
  set g : P.Ω → ℝ := fun ω => S.propScore true ω * S.treatedCondCDF ω t
  have hf : Integrable f P.μ := by
    change Integrable (fun ω => S.dVar.indicator true ω *
      (if S.factualY ω ≤ t then (1 : ℝ) else 0)) P.μ
    exact S.integrable_treated_le_indicator t
  have hg_int : ∀ (s : Set P.Ω), MeasurableSet[S.sigmaX] s → P.μ s < ⊤ →
      IntegrableOn g s P.μ := by
    intro s _hs _hfin
    change IntegrableOn (fun ω => S.propScore true ω * S.treatedCondCDF ω t) s P.μ
    exact (S.integrable_propScore_mul_treatedCondCDF t).integrableOn
  have hg_eq : ∀ (s : Set P.Ω), MeasurableSet[S.sigmaX] s → P.μ s < ⊤ →
      ∫ x in s, g x ∂P.μ = ∫ x in s, f x ∂P.μ := by
    intro s hs _hfin
    change (∫ x in s, S.propScore true x * S.treatedCondCDF x t ∂P.μ) =
      ∫ x in s, S.dVar.indicator true x *
        (if S.factualY x ≤ t then (1 : ℝ) else 0) ∂P.μ
    exact S.setIntegral_propScore_mul_treatedCondCDF_eq_le t s hs
  have hprop_smeas : StronglyMeasurable[S.sigmaX] (S.propScore true) := by
    unfold POBackdoorSystem.propScore
    exact MeasureTheory.stronglyMeasurable_condExp
  have hg_sm : StronglyMeasurable[S.sigmaX] g := by
    change StronglyMeasurable[S.sigmaX]
      (fun ω => S.propScore true ω * S.treatedCondCDF ω t)
    exact hprop_smeas.mul (S.stronglyMeasurable_treatedCondCDF_const t)
  have hle : S.sigmaX ≤ (inferInstance : MeasurableSpace P.Ω) := S.sigmaX_le
  have h := MeasureTheory.ae_eq_condExp_of_forall_setIntegral_eq
    hle hf hg_int hg_eq hg_sm.aestronglyMeasurable
  exact h.symm

/-- For [a potential-outcomes system](hyp:P), [a measurable covariate space](hyp:γ),
[a back-door system on them](hyp:S), [a sensitivity level](hyp:Λ), and [a unit](hyp:ω), [the
calibration quantile level](goal) is one minus the target treated-survival probability divided by
that unit's propensity for treatment. It is the treated conditional-distribution-function level
whose quantile supplies the calibrating cutoff. -/
noncomputable def calibLevel (Λ : ℝ) (ω : P.Ω) : ℝ :=
  1 - S.survTarget Λ ω / S.propScore true ω

/-- For [a potential-outcome system and measurable covariate space](hyp:P,γ), [a back-door
system](hyp:S), and [a fixed outcome cutoff](hyp:t), [the conditional mean of treatment times
the indicator that the outcome exceeds the cutoff equals the propensity times one minus the
treated conditional distribution at that cutoff, almost surely](goal).

**The survival bridge (constant cutoff).** The weighted conditional survival equals the treated
conditional survival scaled by the propensity:
`E[Z·1{Y>t} | σ(X)] = e(X)·(1 − F(t | X))` a.e. The genuine measure-theoretic
content relates a conditional expectation under `μ` (weighted by the treatment
indicator) to the conditional CDF of the treated push-forward law. -/
theorem treatedSurv_const_eq (t : ℝ) :
    P.μ[fun ω => S.dVar.indicator true ω * (if t < S.factualY ω then (1 : ℝ) else 0) | S.sigmaX]
      =ᵐ[P.μ] fun ω => S.propScore true ω * (1 - S.treatedCondCDF ω t) := by
  classical
  have hpoint :
      (fun ω => S.dVar.indicator true ω * (if t < S.factualY ω then (1 : ℝ) else 0))
        =ᵐ[P.μ]
      (fun ω => S.dVar.indicator true ω -
        S.dVar.indicator true ω * (if S.factualY ω ≤ t then (1 : ℝ) else 0)) := by
    exact Filter.Eventually.of_forall fun ω => by
      by_cases hle : S.factualY ω ≤ t
      · have hnot : ¬ t < S.factualY ω := not_lt.mpr hle
        simp [hle, hnot]
      · have hlt : t < S.factualY ω := lt_of_not_ge hle
        simp [hle, hlt]
  refine (MeasureTheory.condExp_congr_ae (m := S.sigmaX) (μ := P.μ) hpoint).trans ?_
  have hsub := MeasureTheory.condExp_sub
    (μ := P.μ) (m := S.sigmaX)
    (f := S.dVar.indicator true)
    (g := fun ω => S.dVar.indicator true ω *
      (if S.factualY ω ≤ t then (1 : ℝ) else 0))
    (S.dVar.integrable_indicator true (MeasurableSet.singleton true))
      (S.integrable_treated_le_indicator t)
  have hle_bridge := S.treatedLe_const_eq t
  filter_upwards [hsub, hle_bridge] with ω hsubω hleω
  change P.μ[S.dVar.indicator true - (fun ω => S.dVar.indicator true ω *
      (if S.factualY ω ≤ t then (1 : ℝ) else 0)) | S.sigmaX] ω =
    S.propScore true ω * (1 - S.treatedCondCDF ω t)
  rw [hsubω]
  change S.propScore true ω -
      P.μ[fun ω => S.dVar.indicator true ω *
        (if S.factualY ω ≤ t then (1 : ℝ) else 0) | S.sigmaX] ω =
    S.propScore true ω * (1 - S.treatedCondCDF ω t)
  rw [hleω]
  ring


end POBackdoorSystem

end PO
end Causalean
