module
public import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Basic
public import Causalean.Mathlib.MeasureTheory.Function.Analytic.UniversalMeasurability

/-!
# Analytic-set interface for completed boundary risks

The common-map loss is jointly Borel, so its boundary-superlevel projections
are analytic. Causalean's universal-measurability substrate turns those analytic
projections into completion-measurable sets and identifies completed integration
with outer integration.
-/

public section

open MeasureTheory Set
open scoped ENNReal

namespace CausalSmith.Stat.BddUniformLogPenalty

/-- The loss generated by one common measurable map is jointly Borel on the
compact boundary and the sample space. -/
lemma commonMapBoundarySup_jointlyBorel
    {n q : ℕ} {L : ℝ} (P : CtyLaw) (hP : CtyNonparametricClass q L P)
    (T : CtyRule n) :
    Measurable
      (fun z : {x : Score // x ∈ frontier P.support} × Sample n =>
        ENNReal.ofReal
          |T.map (distanceData n z.2 z.1.1) - P.mu z.1.1|) := by
  rcases hP with ⟨hq, hL, hdensity, hcompact, hcube, hdenv,
    hrect, hholder, hsigma, hsigmaenv⟩
  have hfrontier : frontier P.support ⊆ P.support := by
    exact frontier_subset_closure.trans_eq P.support_closed.closure_eq
  have hmu : ContinuousOn P.mu P.support := hholder.1.continuousOn
  have hmu' : Continuous (fun x : {x : Score // x ∈ frontier P.support} => P.mu x.1) :=
    continuousOn_iff_continuous_restrict.mp (hmu.mono hfrontier)
  have hdist : Measurable
      (fun z : {x : Score // x ∈ frontier P.support} × Sample n =>
        distanceData n z.2 z.1.1) := by
    unfold distanceData
    fun_prop
  have hT : Measurable
      (fun z : {x : Score // x ∈ frontier P.support} × Sample n =>
        T.map (distanceData n z.2 z.1.1)) := T.measurable.comp hdist
  have hmuM : Measurable
      (fun z : {x : Score // x ∈ frontier P.support} × Sample n => P.mu z.1.1) :=
    hmu'.measurable.comp measurable_fst
  exact ENNReal.measurable_ofReal.comp (hT.sub hmuM).norm

/-- The common-map boundary loss is upper-semi-analytic: each strict superlevel
set is an analytic projection of a Borel set. -/
lemma commonMapBoundarySup_upperSemianalytic
    {n q : ℕ} {L : ℝ} (P : CtyLaw) (hP : CtyNonparametricClass q L P)
    (rho : RuleFun n) (hrho : rho ∈ CtyDistanceDecisionClass n q L) :
    UpperSemianalytic (boundaryLoss rho P) := by
  rcases hrho with ⟨T, hT⟩
  intro a
  let B := {x : Score // x ∈ frontier P.support}
  letI : PolishSpace B := isClosed_frontier.polishSpace
  let loss : B × Sample n → ℝ≥0∞ := fun z =>
    ENNReal.ofReal |T.map (distanceData n z.2 z.1.1) - P.mu z.1.1|
  have hloss : Measurable loss := commonMapBoundarySup_jointlyBorel P hP T
  have hevent : {w | a < boundaryLoss rho P w} =
      Prod.snd '' {z : B × Sample n | a < loss z} := by
    ext w
    constructor
    · intro hw
      simp only [boundaryLoss, lt_iSup_iff] at hw
      rcases hw with ⟨x, hx, hax⟩
      refine ⟨⟨⟨x, hx⟩, w⟩, ?_, rfl⟩
      change a < ENNReal.ofReal |T.map (distanceData n w x) - P.mu x|
      simpa only [hT P hP w x hx] using hax
    · rintro ⟨⟨⟨x, hx⟩, w'⟩, hax, rfl⟩
      change a < ENNReal.ofReal |T.map (distanceData n w' x) - P.mu x| at hax
      rw [← hT P hP w' x hx] at hax
      exact hax.trans_le (le_iSup_of_le x (le_iSup_of_le hx le_rfl))
  rw [hevent]
  exact (hloss measurableSet_Ioi).analyticSet_image measurable_snd

/-- The boundary supremum of a common-map rule is measurable on the completed
sample space. -/
lemma commonMapBoundarySup_completionMeasurable
    {n q : ℕ} {L : ℝ} (P : CtyLaw) (hP : CtyNonparametricClass q L P)
    (rho : RuleFun n) (hrho : rho ∈ CtyDistanceDecisionClass n q L) :
    Measurable
      (fun w : NullMeasurableSpace (Sample n) (sampleLaw P n) =>
        boundaryLoss rho P w) := by
  letI : IsProbabilityMeasure P.law := P.law_isProbability
  letI : IsProbabilityMeasure (sampleLaw P n) := by
    unfold sampleLaw
    infer_instance
  exact (commonMapBoundarySup_upperSemianalytic P hP rho hrho).measurable_completion
    (sampleLaw P n)

/-- The completed expectation of a common-map boundary loss equals its outer
expectation. -/
lemma ctyBoundarySup_completed_eq_outer
    {n q : ℕ} {L : ℝ} (P : CtyLaw) (hP : CtyNonparametricClass q L P)
    (rho : RuleFun n) (hrho : rho ∈ CtyDistanceDecisionClass n q L) :
    (∫⁻ w, boundaryLoss rho P w ∂(sampleLaw P n).completion) =
      MeasureTheory.outerLIntegral (sampleLaw P n) (boundaryLoss rho P) := by
  letI : IsProbabilityMeasure P.law := P.law_isProbability
  letI : IsProbabilityMeasure (sampleLaw P n) := by
    unfold sampleLaw
    infer_instance
  exact (commonMapBoundarySup_upperSemianalytic P hP rho hrho).lintegral_completion_eq_outerLIntegral
    (sampleLaw P n)

/-- The completed common-map risk dominates the outer point-indexed risk. -/
lemma ctyRisk_ge_pointIndexedRisk
    (n q : ℕ) (L : ℝ) :
    pointIndexedDistanceRisk n q L ≤ ctyDistanceRisk n q L := by
  unfold pointIndexedDistanceRisk ctyDistanceRisk
  refine le_iInf fun rho => le_iInf fun hrho => ?_
  have hpi : rho ∈ PointIndexedDecisionClass n q L := by
    rcases hrho with ⟨T, hT⟩
    let Tpi : PIRule n :=
      { map := fun _x => T.map
        section_measurable := fun _x => T.measurable }
    refine ⟨Tpi, ?_⟩
    intro P hP w x hx
    exact hT P hP w x hx
  refine iInf₂_le_of_le rho hpi ?_
  refine iSup_le fun P => iSup_le fun hP => ?_
  refine le_iSup_of_le P (le_iSup_of_le hP ?_)
  exact le_of_eq (ctyBoundarySup_completed_eq_outer P hP rho hrho).symm

end CausalSmith.Stat.BddUniformLogPenalty
