module
public import Causalean.Mathlib.Analysis.HalfDiscPolar

/-!
# Re-exported half-disc polar identities

The general planar identities now live in Causalean.
-/

public section

namespace CausalSmith.Stat.BddUniformLogPenalty

export Causalean.Mathlib.Analysis (planarRadius planarRadius_measurable planarAngle integral_cos_zero_to_pi integral_cos_sq_zero_to_pi halfDisc_weighted_polar_integral halfDisc_weighted_cos_cancellation halfDisc_radialSet_weighted_cos_cancellation planarFirst_div_radius_eq_cos halfDisc_weighted_first_div_radius_cancellation closedHalfDisc_weighted_first_div_radius_cancellation translatedClosedHalfDisc_weighted_first_div_radius_cancellation halfDisc_weighted_cos_sq halfDisc_radial_integral halfDisc_cos_radial_cancellation translatedHalfDisc_weighted_cos_cancellation translatedHalfDisc_radialSet_weighted_cos_cancellation)

end CausalSmith.Stat.BddUniformLogPenalty
