/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import Causalean.PO.ID.Exact.Proximal.Setup
public import Causalean.Tactic.Attr

/-!
# Proximal partial identification — data layer

Reuses the `POProximalSystem` data structure from
`Causalean/PO/ID/Exact/Proximal/Setup.lean` (six POVars: X, A, Z, W, Y, U)
and adds:

* The `(A, X)` and `(X)` tuple maps and σ-algebras (`σ_AX`, `σ_X`) used as
  conditioning targets in the partial-identification proofs.
* Target parameters `meanYofA` (E[Y(a)]) and `condMeanYofA` (E[Y(a) | A = ¬a]).
* The σ_X-measurable `stratumOddsRatio` (`p(A=¬a|X) / p(A=a|X)`) used to
  normalise stratum-conditional integrals across the two arms.
* Three abstract upper/lower envelope predicates (`IsUpperEnvW`/`IsLowerEnvW`,
  `IsUpperEnvZ`/`IsLowerEnvZ`, `IsUpperEnvWZ`/`IsLowerEnvWZ`), one per
  proximal bound family. They directly assume the operational integral or
  conditional-expectation inequalities consumed by the downstream proofs;
  no density-ratio extremum or sharpness result is formalized here.

No assumption bundles live here — see `Assumptions.lean`.
-/

@[expose] public section

namespace Causalean
namespace PO

open MeasureTheory ProbabilityTheory

namespace POProximalSystem

variable {P : POSystem}
  {γ_X γ_Z γ_W γ_U : Type*}
  [MeasurableSpace γ_X] [MeasurableSpace γ_Z]
  [MeasurableSpace γ_W] [MeasurableSpace γ_U]
  (S : POProximalSystem P γ_X γ_Z γ_W γ_U)

/-! ### Additional tuple maps and σ-algebras for partial-identification proofs -/

/-- The [joint treatment-and-covariate map](goal) of [a proximal
potential-outcome system](hyp:S) assigns each unit its factual binary treatment
and covariate. -/
noncomputable def AX : P.Ω → Bool × γ_X := fun ω => (S.A ω, S.X ω)

/-- The treatment-covariate tuple map is measurable. -/
@[fun_prop]
lemma measurable_AX : Measurable S.AX :=
  Measurable.prodMk S.measurable_A S.measurable_X

/-- The [σ-algebra generated by factual treatment and the covariate](goal) in
[a proximal potential-outcome system](hyp:S) is the pullback of their product
σ-algebra to the sample space. -/
noncomputable def σ_AX : MeasurableSpace P.Ω :=
  MeasurableSpace.comap S.AX inferInstance

/-- The sigma-algebra generated by treatment and covariates is a sub-sigma-algebra
of the ambient measurable space. -/
lemma σ_AX_le : S.σ_AX ≤ (inferInstance : MeasurableSpace P.Ω) :=
  S.measurable_AX.comap_le

/-- The [σ-algebra generated by the factual covariate](goal) in [a proximal
potential-outcome system](hyp:S) is the pullback of the covariate's σ-algebra
to the sample space. -/
noncomputable def σ_X : MeasurableSpace P.Ω :=
  MeasurableSpace.comap S.X inferInstance

/-- [The σ-algebra generated by the covariates is a sub-σ-algebra of the ambient
measurable space](goal). -/
lemma σ_X_le : S.σ_X ≤ (inferInstance : MeasurableSpace P.Ω) :=
  S.measurable_X.comap_le

/-- The covariate is measurable with respect to the σ-algebra it generates. -/
@[fun_prop]
lemma measurable_X_σ_X : Measurable[S.σ_X] S.X := fun _ ht => ⟨_, ht, rfl⟩

/-- The treatment is measurable with respect to the σ-algebra generated by treatment and
covariate, being the first coordinate of that tuple. -/
@[fun_prop]
lemma measurable_A_σ_AX : Measurable[S.σ_AX] S.A := by
  intro t ht
  refine ⟨Prod.fst ⁻¹' t, measurable_fst ht, ?_⟩
  ext ω; rfl

/-- The covariate is measurable with respect to the σ-algebra generated by treatment and
covariate, being the second coordinate of that tuple. -/
@[fun_prop]
lemma measurable_X_σ_AX : Measurable[S.σ_AX] S.X := by
  intro t ht
  refine ⟨Prod.snd ⁻¹' t, measurable_snd ht, ?_⟩
  ext ω; rfl

/-- σ_X is coarser than σ_AX: `X` factors through `(A, X)` via the second projection. -/
lemma σ_X_le_σ_AX : S.σ_X ≤ S.σ_AX := by
  -- X = snd ∘ (A, X). So comap X ≤ comap (A, X).
  have hX_eq : S.X = (fun p : Bool × γ_X => p.2) ∘ S.AX := by funext ω; rfl
  intro s hs
  obtain ⟨t, ht_meas, ht_eq⟩ := hs
  refine ⟨(fun p : Bool × γ_X => p.2) ⁻¹' t, measurable_snd ht_meas, ?_⟩
  rw [← ht_eq, hX_eq]; rfl

/-- σ_X ≤ σ_UX, since `X` factors through `(U, X)` via the second projection. -/
lemma σ_X_le_σ_UX : S.σ_X ≤ S.σ_UX := by
  intro s hs
  obtain ⟨t, ht_meas, ht_eq⟩ := hs
  refine ⟨(fun p : γ_U × γ_X => p.2) ⁻¹' t, measurable_snd ht_meas, ?_⟩
  rw [← ht_eq]; rfl

/-- σ_AZX ≤ σ_AZUX, since `(A, Z, X)` factors through `(A, Z, U, X)`. -/
lemma σ_AZX_le_σ_AZUX : S.σ_AZX ≤ S.σ_AZUX := by
  intro s hs
  obtain ⟨t, ht_meas, ht_eq⟩ := hs
  refine ⟨(fun p : Bool × γ_Z × γ_U × γ_X => (p.1, p.2.1, p.2.2.2)) ⁻¹' t, ?_, ?_⟩
  · refine Measurable.prodMk measurable_fst (Measurable.prodMk ?_ ?_) ht_meas
    · exact measurable_fst.comp measurable_snd
    · exact measurable_snd.comp (measurable_snd.comp measurable_snd)
  · rw [← ht_eq]; rfl

/-- The sigma-algebra on treatment, unobserved confounder, and covariates is coarser
than the sigma-algebra that also includes the Z proxy.

This relation is reserved for tower-property steps from the larger proxy sigma-algebra. -/
lemma σ_AUX_le_σ_AZUX : S.σ_AUX ≤ S.σ_AZUX := by
  intro s hs
  obtain ⟨t, ht_meas, ht_eq⟩ := hs
  refine ⟨(fun p : Bool × γ_Z × γ_U × γ_X => (p.1, p.2.2.1, p.2.2.2)) ⁻¹' t, ?_, ?_⟩
  · refine Measurable.prodMk measurable_fst (Measurable.prodMk ?_ ?_) ht_meas
    · exact measurable_fst.comp (measurable_snd.comp measurable_snd)
    · exact measurable_snd.comp (measurable_snd.comp measurable_snd)
  · rw [← ht_eq]; rfl

/-- σ_AX is coarser than σ_AUX, since `(A, X)` factors through `(A, U, X)` via
the projection `(a, u, x) ↦ (a, x)`. -/
lemma σ_AX_le_σ_AUX : S.σ_AX ≤ S.σ_AUX := by
  -- The map S.AX = (A, X) factors as (proj) ∘ S.AUX where proj (a,u,x) = (a,x).
  -- So σ_AX = comap S.AX = comap (proj ∘ S.AUX) ≤ comap S.AUX = σ_AUX.
  have hAX_eq :
      S.AX = (fun p : Bool × γ_U × γ_X => (p.1, p.2.2)) ∘ S.AUX := by
    funext ω; rfl
  have hproj_meas : Measurable (fun p : Bool × γ_U × γ_X => (p.1, p.2.2)) :=
    Measurable.prodMk measurable_fst (measurable_snd.comp measurable_snd)
  -- Now show comap S.AX ≤ comap S.AUX directly.
  intro s hs
  obtain ⟨t, ht_meas, ht_eq⟩ := hs
  refine ⟨(fun p : Bool × γ_U × γ_X => (p.1, p.2.2)) ⁻¹' t, hproj_meas ht_meas, ?_⟩
  rw [← ht_eq, hAX_eq]
  rfl

/-- σ_X ≤ σ_AUX, by composition `σ_X ≤ σ_AX ≤ σ_AUX`. -/
lemma σ_X_le_σ_AUX : S.σ_X ≤ S.σ_AUX :=
  le_trans S.σ_X_le_σ_AX S.σ_AX_le_σ_AUX

/-! ### Target parameters -/

/-- The [marginal potential-outcome mean](goal) for [a proximal
potential-outcome system](hyp:S), [a population measure](hyp:μ), and [a
treatment arm](hyp:a) averages the outcome each unit would have under that arm. -/
noncomputable def meanYofA (μ : Measure P.Ω) (a : Bool) : ℝ :=
  ∫ ω, S.YofA a ω ∂μ

/-- The [opposite-arm conditional potential-outcome mean](goal) for [a proximal
potential-outcome system](hyp:S), [a population measure](hyp:μ), and [a
treatment arm](hyp:a) averages that arm's potential outcome among units whose
factual treatment differs from it.

Conditional potential outcome mean `E[Y(a) | A = ¬a]`.
Defined as `(μ {A ≠ a})⁻¹ · ∫_{A ≠ a} Y(a) dμ`. -/
noncomputable def condMeanYofA (μ : Measure P.Ω) (a : Bool) : ℝ :=
  (μ {ω | S.A ω ≠ a}).toReal⁻¹ * ∫ ω in {ω | S.A ω ≠ a}, S.YofA a ω ∂μ

/-- The conditional potential outcome mean of an arm on the opposite-arm stratum is the
integral of that arm's potential outcome over the stratum where treatment differs from the arm,
divided by the mass of that stratum. -/
@[causal_defs_simps]
lemma condMeanYofA_eq (μ : Measure P.Ω) (a : Bool) :
    S.condMeanYofA μ a =
      (μ {ω | S.A ω ≠ a}).toReal⁻¹ * ∫ ω in {ω | S.A ω ≠ a}, S.YofA a ω ∂μ :=
  rfl

/-- The [average treatment effect](goal) for [a proximal potential-outcome
system](hyp:S) under [a population measure](hyp:μ) is the marginal mean
potential outcome under treatment one minus that under treatment zero. -/
noncomputable def ATE (μ : Measure P.Ω) : ℝ :=
  S.meanYofA μ true - S.meanYofA μ false

/-! ### Stratum odds ratio `p(A = ¬a | X) / p(A = a | X)` -/

/-- The [stratum odds-ratio function](goal) for [a proximal
potential-outcome system](hyp:S), [a population measure](hyp:μ), and [a
treatment arm](hyp:a) divides the conditional probability of the opposite arm
by that of the specified arm at each covariate value.

The σ_X-measurable function `ω ↦ E[𝟙{A ≠ a} | X](ω) / E[𝟙{A = a} | X](ω)`,
which equals `p(A = ¬a | X) / p(A = a | X)` in the discrete case. Used to
re-normalise integrals against `μ.restrict {A = a}` to the `{A ≠ a}` arm. -/
noncomputable def stratumOddsRatio (μ : Measure P.Ω) (a : Bool) : P.Ω → ℝ :=
  fun ω =>
    (μ[Set.indicator {ω' | S.A ω' ≠ a} (fun _ => (1:ℝ)) | S.σ_X]) ω /
    (μ[Set.indicator {ω' | S.A ω' = a}  (fun _ => (1:ℝ)) | S.σ_X]) ω

/-! ### Operational envelope predicates for the W-proxy ratio -/

/-- The [upper operational W-proxy envelope condition](goal) for [a proximal
system](hyp:S), [a population measure](hyp:μ), [a treatment arm](hyp:a), and
[an envelope depending on treatment and covariates](hyp:Uenv) requires [the
envelope to be measurable](step:1) and [every admissible nonnegative proxy test
function to satisfy the stated opposite-arm versus weighted on-arm integral
inequality](step:2).

Operational surrogate for an upper envelope on the W-proxy density ratio
`p(W | A = ¬a, X) / p(W | A = a, X)` under treatment level `a`.

Operational integrated form used by the W-based bound:
for any nonneg measurable test function `φ(W, X)` whose unweighted and weighted
right-hand sides are integrable,
  `∫_{A=¬a} φ(W,X) dμ ≤ ∫_{A=a} stratumOddsRatio · Uenv(a, X) · φ(W,X) dμ`.

This predicate assumes that integral comparison directly. The library does not
construct conditional densities or prove equivalence with a pointwise ratio
bound. -/
def IsUpperEnvW (μ : Measure P.Ω) (a : Bool) (Uenv : Bool × γ_X → ℝ) : Prop :=
  Measurable Uenv ∧
  ∀ (φ : γ_W × γ_X → ℝ), Measurable φ → (∀ x, 0 ≤ φ x) →
    Integrable (fun ω => φ (S.W ω, S.X ω)) μ →
    Integrable
      (fun ω => S.stratumOddsRatio μ a ω * Uenv (a, S.X ω) * φ (S.W ω, S.X ω)) μ →
    ∫ ω in {ω | S.A ω ≠ a}, φ (S.W ω, S.X ω) ∂μ
      ≤ ∫ ω in {ω | S.A ω = a},
          S.stratumOddsRatio μ a ω * Uenv (a, S.X ω) * φ (S.W ω, S.X ω) ∂μ

/-- The [lower operational W-proxy envelope condition](goal) for [a proximal
system](hyp:S), [a population measure](hyp:μ), [a treatment arm](hyp:a), and
[an envelope depending on treatment and covariates](hyp:Lenv) requires [the
envelope to be measurable](step:1) and [every admissible nonnegative proxy test
function to satisfy the stated weighted on-arm versus opposite-arm integral
inequality](step:2).

Operational surrogate for a lower W-proxy density-ratio envelope. It mirrors
`IsUpperEnvW` with the inequality reversed and includes integrability of the
weighted left-hand side. -/
def IsLowerEnvW (μ : Measure P.Ω) (a : Bool) (Lenv : Bool × γ_X → ℝ) : Prop :=
  Measurable Lenv ∧
  ∀ (φ : γ_W × γ_X → ℝ), Measurable φ → (∀ x, 0 ≤ φ x) →
    Integrable (fun ω => φ (S.W ω, S.X ω)) μ →
    Integrable
      (fun ω => S.stratumOddsRatio μ a ω * Lenv (a, S.X ω) * φ (S.W ω, S.X ω)) μ →
    ∫ ω in {ω | S.A ω = a},
        S.stratumOddsRatio μ a ω * Lenv (a, S.X ω) * φ (S.W ω, S.X ω) ∂μ
      ≤ ∫ ω in {ω | S.A ω ≠ a}, φ (S.W ω, S.X ω) ∂μ

/-! ### Operational envelope predicates for the Z-proxy outcome model -/

/-- The [upper Z-proxy conditional-mean envelope condition](goal) for [a
proximal system](hyp:S), [a population measure](hyp:μ), [a treatment
arm](hyp:a), and [an envelope depending on treatment and covariates](hyp:Uenv)
requires [the envelope to be measurable](step:1) and [the conditional outcome
mean given treatment, the treatment-side proxy, and covariates to lie below it
almost everywhere in that arm](step:2).

Upper envelope for `E[Y | Z, X, A = a]` under treatment level `a`.
A σ_X-measurable function `Uenv(a, X)` such that, μ-a.e. on `{A = a}`,
`(μ[Y | σ_AZX]) ≤ Uenv(a, X)`. No extremal construction or attainability
claim is included. -/
def IsUpperEnvZ (μ : Measure P.Ω) (a : Bool) (Uenv : Bool × γ_X → ℝ) : Prop :=
  Measurable Uenv ∧
  ∀ᵐ ω ∂(μ.restrict {ω | S.A ω = a}),
    (μ[S.Y | S.σ_AZX]) ω ≤ Uenv (a, S.X ω)

/-- The [lower Z-proxy conditional-mean envelope condition](goal) for [a
proximal system](hyp:S), [a population measure](hyp:μ), [a treatment
arm](hyp:a), and [an envelope depending on treatment and covariates](hyp:Lenv)
requires [the envelope to be measurable](step:1) and [the conditional outcome
mean given treatment, the treatment-side proxy, and covariates to lie above it
almost everywhere in that arm](step:2).

Lower envelope for `E[Y | Z, X, A = a]`. Mirror of `IsUpperEnvZ`. -/
def IsLowerEnvZ (μ : Measure P.Ω) (a : Bool) (Lenv : Bool × γ_X → ℝ) : Prop :=
  Measurable Lenv ∧
  ∀ᵐ ω ∂(μ.restrict {ω | S.A ω = a}),
    Lenv (a, S.X ω) ≤ (μ[S.Y | S.σ_AZX]) ω

/-! ### Operational envelope predicates for the joint W-Z proxy ratio -/

/-- The [upper operational joint-proxy envelope condition](goal) for [a
proximal system](hyp:S), [a population measure](hyp:μ), [a treatment
arm](hyp:a), and [an envelope depending on treatment and covariates](hyp:Uenv)
requires [the envelope to be measurable](step:1) and [every admissible pair of
nonnegative proxy test functions to satisfy the stated conditional product
inequality almost everywhere in that arm](step:2).

Operational surrogate for an upper envelope on the same-arm joint-versus-product
W-Z density ratio under treatment level `a`:
    ρ(w, z, x) := p(w, z | A = a, x) / (p(w | A = a, x) · p(z | A = a, x)).

Operational integrated form (avoids materialising densities): for any nonneg
measurable test functions `φ_W(W, X)` and `φ_Z(Z, X)`, μ-a.e. on `{A = a}`,

  μ[ φ_W · φ_Z | σ_AX ]
    ≤ Uenv(a, X) · μ[ φ_W | σ_AX ] · μ[ φ_Z | σ_AX ].

The predicate assumes this conditional-expectation inequality directly. The
library does not construct a supremum envelope, prove a pointwise density-ratio
equivalence, or establish sharpness. -/
def IsUpperEnvWZ (μ : Measure P.Ω) (a : Bool) (Uenv : Bool × γ_X → ℝ) : Prop :=
  Measurable Uenv ∧
  ∀ (φ_W : γ_W × γ_X → ℝ) (φ_Z : γ_Z × γ_X → ℝ),
    Measurable φ_W → Measurable φ_Z →
    (∀ x, 0 ≤ φ_W x) → (∀ x, 0 ≤ φ_Z x) →
    Integrable (fun ω => φ_W (S.W ω, S.X ω) * φ_Z (S.Z ω, S.X ω)) μ →
    Integrable (fun ω => φ_W (S.W ω, S.X ω)) μ →
    Integrable (fun ω => φ_Z (S.Z ω, S.X ω)) μ →
    (μ[fun ω => φ_W (S.W ω, S.X ω) * φ_Z (S.Z ω, S.X ω) | S.σ_AX])
      ≤ᵐ[μ.restrict {ω | S.A ω = a}]
      fun ω => Uenv (a, S.X ω) *
        ((μ[fun ω' => φ_W (S.W ω', S.X ω') | S.σ_AX]) ω)
        * ((μ[fun ω' => φ_Z (S.Z ω', S.X ω') | S.σ_AX]) ω)

/-- The [lower operational joint-proxy envelope condition](goal) for [a
proximal system](hyp:S), [a population measure](hyp:μ), [a treatment
arm](hyp:a), and [an envelope depending on treatment and covariates](hyp:Lenv)
requires [the envelope to be measurable](step:1) and [every admissible pair of
nonnegative proxy test functions to satisfy the reverse conditional product
inequality almost everywhere in that arm](step:2).

Lower operational envelope for the same-arm joint-vs-product W-Z comparison.
It mirrors `IsUpperEnvWZ` with the inequality reversed and makes no extremal or
sharpness claim. -/
def IsLowerEnvWZ (μ : Measure P.Ω) (a : Bool) (Lenv : Bool × γ_X → ℝ) : Prop :=
  Measurable Lenv ∧
  ∀ (φ_W : γ_W × γ_X → ℝ) (φ_Z : γ_Z × γ_X → ℝ),
    Measurable φ_W → Measurable φ_Z →
    (∀ x, 0 ≤ φ_W x) → (∀ x, 0 ≤ φ_Z x) →
    Integrable (fun ω => φ_W (S.W ω, S.X ω) * φ_Z (S.Z ω, S.X ω)) μ →
    Integrable (fun ω => φ_W (S.W ω, S.X ω)) μ →
    Integrable (fun ω => φ_Z (S.Z ω, S.X ω)) μ →
    (fun ω => Lenv (a, S.X ω) *
        ((μ[fun ω' => φ_W (S.W ω', S.X ω') | S.σ_AX]) ω)
        * ((μ[fun ω' => φ_Z (S.Z ω', S.X ω') | S.σ_AX]) ω))
      ≤ᵐ[μ.restrict {ω | S.A ω = a}]
      (μ[fun ω => φ_W (S.W ω, S.X ω) * φ_Z (S.Z ω, S.X ω) | S.σ_AX])

end POProximalSystem

end PO
end Causalean
