/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

import Causalean.PO.ID.Exact.Proximal.Setup
import Causalean.Tactic.Attr

/-!
# Proximal partial identification — data layer

Reuses the `POProximalSystem` data structure from
`Causalean/PO/ID/Exact/Proximal/Setup.lean` (six POVars: X, A, Z, W, Y, U)
and adds:

* The `(A, X)` and `(X)` tuple maps and σ-algebras (`σ_AX`, `σ_X`) used as
  conditioning targets in the partial-identification proofs.
* Target parameters `meanYofA` (E[Y(a)]) and `condMeanYofA` (E[Y(a) | A = ¬a]).
* The σ_X-measurable `stratumOddsRatio` (`p(A=¬a|X) / p(A=a|X)`) used to
  normalise stratum-conditional integrals across the two arms.
* Three abstract upper/lower envelope predicates (`IsUpperEnvW`/`IsLowerEnvW`,
  `IsUpperEnvZ`/`IsLowerEnvZ`, `IsUpperEnvWZ`/`IsLowerEnvWZ`), one per
  partial-identification theorem (Ghassami-Shpitser-Tchetgen Tchetgen 2024,
  Thms 1, 2, 3). Each envelope is the operational integrated form of the
  paper's `min_w` / `max_w` proxy-density-ratio bound.

No assumption bundles live here — see `Assumptions.lean`.
-/


namespace Causalean
namespace PO

open MeasureTheory ProbabilityTheory

namespace POProximalSystem

variable {P : POSystem}
  {γ_X γ_Z γ_W γ_U : Type*}
  [MeasurableSpace γ_X] [MeasurableSpace γ_Z]
  [MeasurableSpace γ_W] [MeasurableSpace γ_U]
  (S : POProximalSystem P γ_X γ_Z γ_W γ_U)

/-! ### Additional tuple maps and σ-algebras for partial-identification proofs -/

/-- For [a proximal potential-outcome system](hyp:S), the [joint treatment-and-covariate map](goal) assigns to each unit its factual binary treatment and covariate. -/
noncomputable def AX : P.Ω → Bool × γ_X := fun ω => (S.A ω, S.X ω)

/-- The treatment-covariate tuple map is measurable. -/
@[fun_prop]
lemma measurable_AX : Measurable S.AX :=
  Measurable.prodMk S.measurable_A S.measurable_X

/-- For [a proximal potential-outcome system](hyp:S), the [σ-algebra generated by factual treatment and covariate](goal) is the pullback to the sample space of their product σ-algebra. -/
noncomputable def σ_AX : MeasurableSpace P.Ω :=
  MeasurableSpace.comap S.AX inferInstance

/-- The sigma-algebra generated by treatment and covariates is a sub-sigma-algebra
of the ambient measurable space. -/
lemma σ_AX_le : S.σ_AX ≤ (inferInstance : MeasurableSpace P.Ω) :=
  S.measurable_AX.comap_le

/-- For [a proximal potential-outcome system](hyp:S), the [σ-algebra generated by the factual covariate](goal) is the pullback to the sample space of the covariate's σ-algebra. -/
noncomputable def σ_X : MeasurableSpace P.Ω :=
  MeasurableSpace.comap S.X inferInstance

/-- [The σ-algebra generated by the covariates is a sub-σ-algebra of the ambient
measurable space](goal). -/
lemma σ_X_le : S.σ_X ≤ (inferInstance : MeasurableSpace P.Ω) :=
  S.measurable_X.comap_le

/-- The covariate is measurable with respect to the σ-algebra it generates. -/
@[fun_prop]
lemma measurable_X_σ_X : Measurable[S.σ_X] S.X := fun _ ht => ⟨_, ht, rfl⟩

/-- The treatment is measurable with respect to the σ-algebra generated by treatment and
covariate, being the first coordinate of that tuple. -/
@[fun_prop]
lemma measurable_A_σ_AX : Measurable[S.σ_AX] S.A := by
  intro t ht
  refine ⟨Prod.fst ⁻¹' t, measurable_fst ht, ?_⟩
  ext ω; rfl

/-- The covariate is measurable with respect to the σ-algebra generated by treatment and
covariate, being the second coordinate of that tuple. -/
@[fun_prop]
lemma measurable_X_σ_AX : Measurable[S.σ_AX] S.X := by
  intro t ht
  refine ⟨Prod.snd ⁻¹' t, measurable_snd ht, ?_⟩
  ext ω; rfl

/-- σ_X is coarser than σ_AX: `X` factors through `(A, X)` via the second projection. -/
lemma σ_X_le_σ_AX : S.σ_X ≤ S.σ_AX := by
  -- X = snd ∘ (A, X). So comap X ≤ comap (A, X).
  have hX_eq : S.X = (fun p : Bool × γ_X => p.2) ∘ S.AX := by funext ω; rfl
  intro s hs
  obtain ⟨t, ht_meas, ht_eq⟩ := hs
  refine ⟨(fun p : Bool × γ_X => p.2) ⁻¹' t, measurable_snd ht_meas, ?_⟩
  rw [← ht_eq, hX_eq]; rfl

/-- σ_X ≤ σ_UX, since `X` factors through `(U, X)` via the second projection. -/
lemma σ_X_le_σ_UX : S.σ_X ≤ S.σ_UX := by
  intro s hs
  obtain ⟨t, ht_meas, ht_eq⟩ := hs
  refine ⟨(fun p : γ_U × γ_X => p.2) ⁻¹' t, measurable_snd ht_meas, ?_⟩
  rw [← ht_eq]; rfl

/-- σ_AZX ≤ σ_AZUX, since `(A, Z, X)` factors through `(A, Z, U, X)`. -/
lemma σ_AZX_le_σ_AZUX : S.σ_AZX ≤ S.σ_AZUX := by
  intro s hs
  obtain ⟨t, ht_meas, ht_eq⟩ := hs
  refine ⟨(fun p : Bool × γ_Z × γ_U × γ_X => (p.1, p.2.1, p.2.2.2)) ⁻¹' t, ?_, ?_⟩
  · refine Measurable.prodMk measurable_fst (Measurable.prodMk ?_ ?_) ht_meas
    · exact measurable_fst.comp measurable_snd
    · exact measurable_snd.comp (measurable_snd.comp measurable_snd)
  · rw [← ht_eq]; rfl

/-- The sigma-algebra on treatment, unobserved confounder, and covariates is coarser
than the sigma-algebra that also includes the Z proxy.

This relation is reserved for tower-property steps from the larger proxy sigma-algebra. -/
lemma σ_AUX_le_σ_AZUX : S.σ_AUX ≤ S.σ_AZUX := by
  intro s hs
  obtain ⟨t, ht_meas, ht_eq⟩ := hs
  refine ⟨(fun p : Bool × γ_Z × γ_U × γ_X => (p.1, p.2.2.1, p.2.2.2)) ⁻¹' t, ?_, ?_⟩
  · refine Measurable.prodMk measurable_fst (Measurable.prodMk ?_ ?_) ht_meas
    · exact measurable_fst.comp (measurable_snd.comp measurable_snd)
    · exact measurable_snd.comp (measurable_snd.comp measurable_snd)
  · rw [← ht_eq]; rfl

/-- σ_AX is coarser than σ_AUX, since `(A, X)` factors through `(A, U, X)` via
the projection `(a, u, x) ↦ (a, x)`. -/
lemma σ_AX_le_σ_AUX : S.σ_AX ≤ S.σ_AUX := by
  -- The map S.AX = (A, X) factors as (proj) ∘ S.AUX where proj (a,u,x) = (a,x).
  -- So σ_AX = comap S.AX = comap (proj ∘ S.AUX) ≤ comap S.AUX = σ_AUX.
  have hAX_eq :
      S.AX = (fun p : Bool × γ_U × γ_X => (p.1, p.2.2)) ∘ S.AUX := by
    funext ω; rfl
  have hproj_meas : Measurable (fun p : Bool × γ_U × γ_X => (p.1, p.2.2)) :=
    Measurable.prodMk measurable_fst (measurable_snd.comp measurable_snd)
  -- Now show comap S.AX ≤ comap S.AUX directly.
  intro s hs
  obtain ⟨t, ht_meas, ht_eq⟩ := hs
  refine ⟨(fun p : Bool × γ_U × γ_X => (p.1, p.2.2)) ⁻¹' t, hproj_meas ht_meas, ?_⟩
  rw [← ht_eq, hAX_eq]
  rfl

/-- σ_X ≤ σ_AUX, by composition `σ_X ≤ σ_AX ≤ σ_AUX`. -/
lemma σ_X_le_σ_AUX : S.σ_X ≤ S.σ_AUX :=
  le_trans S.σ_X_le_σ_AX S.σ_AX_le_σ_AUX

/-! ### Target parameters -/

/-- For [a proximal potential-outcome system](hyp:S), [a measure on its sample space](hyp:μ), and [a treatment level](hyp:a), the [marginal potential-outcome mean](goal) is the integral of the outcome that each unit would have under that treatment level with respect to that measure. -/
noncomputable def meanYofA (μ : Measure P.Ω) (a : Bool) : ℝ :=
  ∫ ω, S.YofA a ω ∂μ

/-- For [a proximal potential-outcome system](hyp:S), [a measure on its sample space](hyp:μ), and [a treatment level](hyp:a), the [opposite-arm conditional potential-outcome mean](goal) is the integral of that level's potential outcome over units whose factual treatment differs from that level, divided by the measure of that stratum.

Conditional potential outcome mean `E[Y(a) | A = ¬a]`.
Defined as `(μ {A ≠ a})⁻¹ · ∫_{A ≠ a} Y(a) dμ`. -/
noncomputable def condMeanYofA (μ : Measure P.Ω) (a : Bool) : ℝ :=
  (μ {ω | S.A ω ≠ a}).toReal⁻¹ * ∫ ω in {ω | S.A ω ≠ a}, S.YofA a ω ∂μ

/-- The conditional potential outcome mean of an arm on the opposite-arm stratum is the
integral of that arm's potential outcome over the stratum where treatment differs from the arm,
divided by the mass of that stratum. -/
@[causal_defs_simps]
lemma condMeanYofA_eq (μ : Measure P.Ω) (a : Bool) :
    S.condMeanYofA μ a =
      (μ {ω | S.A ω ≠ a}).toReal⁻¹ * ∫ ω in {ω | S.A ω ≠ a}, S.YofA a ω ∂μ :=
  rfl

/-- For [a proximal potential-outcome system](hyp:S) and [a measure on its sample space](hyp:μ), the [average treatment effect](goal) is the marginal mean potential outcome under treatment one minus that under treatment zero. -/
noncomputable def ATE (μ : Measure P.Ω) : ℝ :=
  S.meanYofA μ true - S.meanYofA μ false

/-! ### Stratum odds ratio `p(A = ¬a | X) / p(A = a | X)` -/

/-- For [a proximal potential-outcome system](hyp:S), [a measure on its sample space](hyp:μ), and [a treatment level](hyp:a), the [stratum odds-ratio function](goal) assigns each unit the conditional expected indicator of the opposite treatment arm given its covariates divided by the conditional expected indicator of its own arm given those covariates.

The σ_X-measurable function `ω ↦ E[𝟙{A ≠ a} | X](ω) / E[𝟙{A = a} | X](ω)`,
which equals `p(A = ¬a | X) / p(A = a | X)` in the discrete case. Used to
re-normalise integrals against `μ.restrict {A = a}` to the `{A ≠ a}` arm. -/
noncomputable def stratumOddsRatio (μ : Measure P.Ω) (a : Bool) : P.Ω → ℝ :=
  fun ω =>
    (μ[Set.indicator {ω' | S.A ω' ≠ a} (fun _ => (1:ℝ)) | S.σ_X]) ω /
    (μ[Set.indicator {ω' | S.A ω' = a}  (fun _ => (1:ℝ)) | S.σ_X]) ω

/-! ### Envelope predicates for the W-proxy ratio (Theorem 1) -/

/-- For [a proximal potential-outcome system](hyp:S), [a measure on its sample space](hyp:μ), [a treatment level](hyp:a), and [a proposed upper-envelope function of treatment and covariates](hyp:Uenv), the [upper W-proxy envelope condition](goal) holds exactly when the function is measurable [step:1] and, for every measurable nonnegative test function of the outcome-side proxy and covariates whose unweighted and envelope-weighted versions are integrable, its integral over the opposite treatment arm is at most its stratum-odds-ratio- and envelope-weighted integral over the specified treatment arm [step:2].

Upper envelope for the W-proxy density ratio `p(W | A = ¬a, X) / p(W | A = a, X)`
under treatment level `a`.

Operational integrated form (the form used in Theorem 1's proof):
for any nonneg measurable test function `φ(W, X)` whose unweighted and weighted
right-hand sides are integrable,
  `∫_{A=¬a} φ(W,X) dμ ≤ ∫_{A=a} stratumOddsRatio · Uenv(a, X) · φ(W,X) dμ`.

This is equivalent (up to standard density-change steps) to the pointwise
bound `Uenv(a, X(ω)) ≥ p(W=W(ω) | A=¬a, X(ω)) / p(W=W(ω) | A=a, X(ω))`.
Working with the integrated form avoids materialising conditional densities. -/
def IsUpperEnvW (μ : Measure P.Ω) (a : Bool) (Uenv : Bool × γ_X → ℝ) : Prop :=
  Measurable Uenv ∧
  ∀ (φ : γ_W × γ_X → ℝ), Measurable φ → (∀ x, 0 ≤ φ x) →
    Integrable (fun ω => φ (S.W ω, S.X ω)) μ →
    Integrable
      (fun ω => S.stratumOddsRatio μ a ω * Uenv (a, S.X ω) * φ (S.W ω, S.X ω)) μ →
    ∫ ω in {ω | S.A ω ≠ a}, φ (S.W ω, S.X ω) ∂μ
      ≤ ∫ ω in {ω | S.A ω = a},
          S.stratumOddsRatio μ a ω * Uenv (a, S.X ω) * φ (S.W ω, S.X ω) ∂μ

/-- For [a proximal potential-outcome system](hyp:S), [a measure on its sample space](hyp:μ), [a treatment level](hyp:a), and [a proposed lower-envelope function of treatment and covariates](hyp:Lenv), the [lower W-proxy envelope condition](goal) holds exactly when the function is measurable [step:1] and, for every measurable nonnegative test function of the outcome-side proxy and covariates whose unweighted and envelope-weighted versions are integrable, its stratum-odds-ratio- and envelope-weighted integral over the specified treatment arm is at most its integral over the opposite treatment arm [step:2].

Lower envelope for the W-proxy density ratio. Mirror of `IsUpperEnvW`
with the inequality reversed, including integrability of the weighted left-hand
side. -/
def IsLowerEnvW (μ : Measure P.Ω) (a : Bool) (Lenv : Bool × γ_X → ℝ) : Prop :=
  Measurable Lenv ∧
  ∀ (φ : γ_W × γ_X → ℝ), Measurable φ → (∀ x, 0 ≤ φ x) →
    Integrable (fun ω => φ (S.W ω, S.X ω)) μ →
    Integrable
      (fun ω => S.stratumOddsRatio μ a ω * Lenv (a, S.X ω) * φ (S.W ω, S.X ω)) μ →
    ∫ ω in {ω | S.A ω = a},
        S.stratumOddsRatio μ a ω * Lenv (a, S.X ω) * φ (S.W ω, S.X ω) ∂μ
      ≤ ∫ ω in {ω | S.A ω ≠ a}, φ (S.W ω, S.X ω) ∂μ

/-! ### Envelope predicates for the Z-proxy outcome model (Theorem 2) -/

/-- For [a proximal potential-outcome system](hyp:S), [a measure on its sample space](hyp:μ), [a treatment level](hyp:a), and [a proposed upper-envelope function of treatment and covariates](hyp:Uenv), the [upper Z-proxy envelope condition](goal) holds exactly when the function is measurable [step:1] and, for almost every unit in the specified treatment arm, the conditional mean of the factual outcome given treatment, treatment-side proxy, and covariates does not exceed the envelope evaluated at that treatment and covariate [step:2].

Upper envelope for `E[Y | Z, X, A = a]` under treatment level `a`.
A σ_X-measurable function `Uenv(a, X)` such that, μ-a.e. on `{A = a}`,
`(μ[Y | σ_AZX]) ≤ Uenv(a, X)`. The paper's `max_z E[Y | z, X, A = a]`
is the canonical (sharp) instance. -/
def IsUpperEnvZ (μ : Measure P.Ω) (a : Bool) (Uenv : Bool × γ_X → ℝ) : Prop :=
  Measurable Uenv ∧
  ∀ᵐ ω ∂(μ.restrict {ω | S.A ω = a}),
    (μ[S.Y | S.σ_AZX]) ω ≤ Uenv (a, S.X ω)

/-- For [a proximal potential-outcome system](hyp:S), [a measure on its sample space](hyp:μ), [a treatment level](hyp:a), and [a proposed lower-envelope function of treatment and covariates](hyp:Lenv), the [lower Z-proxy envelope condition](goal) holds exactly when the function is measurable [step:1] and, for almost every unit in the specified treatment arm, the envelope evaluated at that treatment and covariate does not exceed the conditional mean of the factual outcome given treatment, treatment-side proxy, and covariates [step:2].

Lower envelope for `E[Y | Z, X, A = a]`. Mirror of `IsUpperEnvZ`. -/
def IsLowerEnvZ (μ : Measure P.Ω) (a : Bool) (Lenv : Bool × γ_X → ℝ) : Prop :=
  Measurable Lenv ∧
  ∀ᵐ ω ∂(μ.restrict {ω | S.A ω = a}),
    Lenv (a, S.X ω) ≤ (μ[S.Y | S.σ_AZX]) ω

/-! ### Envelope predicates for the joint W-Z proxy ratio (Theorem 3) -/

/-- For [a proximal potential-outcome system](hyp:S), [a measure on its sample space](hyp:μ), [a treatment level](hyp:a), and [a proposed upper-envelope function of treatment and covariates](hyp:Uenv), the [upper joint W--Z envelope condition](goal) holds exactly when the function is measurable [step:1] and, for every pair of measurable nonnegative test functions of respectively the outcome-side and treatment-side proxies with all three displayed products integrable, the conditional expectation of their product given treatment and covariates is at most the envelope times the product of their conditional expectations, almost everywhere in the specified treatment arm [step:2].

Upper envelope for the same-arm joint-vs-product W-Z density ratio under
treatment level `a`:
    ρ(w, z, x) := p(w, z | A = a, x) / (p(w | A = a, x) · p(z | A = a, x)).

Operational integrated form (avoids materialising densities): for any nonneg
measurable test functions `φ_W(W, X)` and `φ_Z(Z, X)`, μ-a.e. on `{A = a}`,

  μ[ φ_W · φ_Z | σ_AX ]
    ≤ Uenv(a, X) · μ[ φ_W | σ_AX ] · μ[ φ_Z | σ_AX ].

The canonical sharp choice is `Uenv(a, x) = sup_{w, z} ρ(w, z, x)`. In the
discrete case this is equivalent to a pointwise ratio bound; the integrated
form above is what Theorem 3's proof actually consumes. -/
def IsUpperEnvWZ (μ : Measure P.Ω) (a : Bool) (Uenv : Bool × γ_X → ℝ) : Prop :=
  Measurable Uenv ∧
  ∀ (φ_W : γ_W × γ_X → ℝ) (φ_Z : γ_Z × γ_X → ℝ),
    Measurable φ_W → Measurable φ_Z →
    (∀ x, 0 ≤ φ_W x) → (∀ x, 0 ≤ φ_Z x) →
    Integrable (fun ω => φ_W (S.W ω, S.X ω) * φ_Z (S.Z ω, S.X ω)) μ →
    Integrable (fun ω => φ_W (S.W ω, S.X ω)) μ →
    Integrable (fun ω => φ_Z (S.Z ω, S.X ω)) μ →
    (μ[fun ω => φ_W (S.W ω, S.X ω) * φ_Z (S.Z ω, S.X ω) | S.σ_AX])
      ≤ᵐ[μ.restrict {ω | S.A ω = a}]
      fun ω => Uenv (a, S.X ω) *
        ((μ[fun ω' => φ_W (S.W ω', S.X ω') | S.σ_AX]) ω)
        * ((μ[fun ω' => φ_Z (S.Z ω', S.X ω') | S.σ_AX]) ω)

/-- For [a proximal potential-outcome system](hyp:S), [a measure on its sample space](hyp:μ), [a treatment level](hyp:a), and [a proposed lower-envelope function of treatment and covariates](hyp:Lenv), the [lower joint W--Z envelope condition](goal) holds exactly when the function is measurable [step:1] and, for every pair of measurable nonnegative test functions of respectively the outcome-side and treatment-side proxies with all three displayed products integrable, the envelope times the product of their conditional expectations given treatment and covariates is at most the conditional expectation of their product, almost everywhere in the specified treatment arm [step:2].

Lower envelope for the same-arm joint-vs-product W-Z density ratio. Mirror
of `IsUpperEnvWZ` with the inequality reversed: the canonical sharp choice is
`Lenv(a, x) = inf_{w, z} ρ(w, z, x)`. -/
def IsLowerEnvWZ (μ : Measure P.Ω) (a : Bool) (Lenv : Bool × γ_X → ℝ) : Prop :=
  Measurable Lenv ∧
  ∀ (φ_W : γ_W × γ_X → ℝ) (φ_Z : γ_Z × γ_X → ℝ),
    Measurable φ_W → Measurable φ_Z →
    (∀ x, 0 ≤ φ_W x) → (∀ x, 0 ≤ φ_Z x) →
    Integrable (fun ω => φ_W (S.W ω, S.X ω) * φ_Z (S.Z ω, S.X ω)) μ →
    Integrable (fun ω => φ_W (S.W ω, S.X ω)) μ →
    Integrable (fun ω => φ_Z (S.Z ω, S.X ω)) μ →
    (fun ω => Lenv (a, S.X ω) *
        ((μ[fun ω' => φ_W (S.W ω', S.X ω') | S.σ_AX]) ω)
        * ((μ[fun ω' => φ_Z (S.Z ω', S.X ω') | S.σ_AX]) ω))
      ≤ᵐ[μ.restrict {ω | S.A ω = a}]
      (μ[fun ω => φ_W (S.W ω, S.X ω) * φ_Z (S.Z ω, S.X ω) | S.σ_AX])

end POProximalSystem

end PO
end Causalean
