module
public import CausalSmith.Stat.STAT_DensityeffectRoughnullFrontier_Research.Histogram
public import Mathlib.Analysis.SpecialFunctions.Log.Base
public import Mathlib.Data.Nat.Log
public import Mathlib.Probability.Independence.InfinitePi

/-!
Thirteen roles, clipped normalized pilots, observable correction chains, public budgets and the
tuned interval rule.
-/

@[expose] public section

noncomputable section
open MeasureTheory ProbabilityTheory
open scoped ENNReal RealInnerProductSpace
namespace CausalSmith.Stat.DensityEffectRoughNull


/-- Role sample size. -/
def roleSize (n : ℕ) : ℕ := n / 13 -- @realizes m(floor(n/13))

/-- The planned fold indices really lie in the original sample. -/
-- @node: foldIndex_lt
lemma foldIndex_lt (n : ℕ) (b : Fin 13) (i : Fin (roleSize n)) :
    b.val * roleSize n + i.val < n := by
  have hblock : b.val + 1 ≤ 13 := b.isLt
  have hi := i.isLt
  have hmul := Nat.mul_le_mul_right (roleSize n) hblock
  have htotal : 13 * roleSize n ≤ n := by
    simpa [roleSize, Nat.mul_comm] using Nat.div_mul_le_self n 13
  calc
    b.val * roleSize n + i.val < b.val * roleSize n + roleSize n :=
      Nat.add_lt_add_left hi _
    _ = (b.val + 1) * roleSize n := by ring
    _ ≤ 13 * roleSize n := hmul
    _ ≤ n := htotal

-- @node: def:folds
/-- Zero-based form of the thirteen consecutive role blocks. -/
def foldIndex (n : ℕ) (b : Fin 13) (i : Fin (roleSize n)) : Fin n :=
  ⟨b.val * roleSize n + i.val, foldIndex_lt n b i⟩
    -- @realizes Dfold(consecutive record roles) @realizes b(Fin 13) @realizes i(Fin m)

/-- Extract one role block. -/
def foldData (n : ℕ) (data : Data n) (b : Fin 13) : Fin (roleSize n) → Omega :=
  fun i => data (foldIndex n b i)

/-- Training field generated by the first role's records. -/
abbrev trainingField (n : ℕ) : MeasurableSpace (Data n) :=
  MeasurableSpace.comap (fun data => foldData n data 0) inferInstance
    -- @realizes Fpilot(sigma-field generated by D_0 records)

/-- No two role-position pairs select the same observation. -/
-- @node: foldIndex_injective
lemma foldIndex_injective (n : ℕ) :
    Function.Injective (fun p : Fin 13 × Fin (roleSize n) => foldIndex n p.1 p.2) := by
  rintro ⟨b, i⟩ ⟨c, j⟩ h
  have hm : 0 < roleSize n := lt_of_le_of_lt (Nat.zero_le i.val) i.isLt
  have hv : b.val * roleSize n + i.val = c.val * roleSize n + j.val :=
    congrArg Fin.val h
  have hb : b.val = c.val := by
    have hd := congrArg (fun k => k / roleSize n) hv
    simpa [Nat.add_comm, Nat.add_mul_div_right _ _ hm,
      Nat.div_eq_of_lt i.isLt, Nat.div_eq_of_lt j.isLt] using hd
  have hi : i.val = j.val := by
    rw [hb] at hv
    exact Nat.add_left_cancel hv
  exact Prod.ext (Fin.ext hb) (Fin.ext hi)

/-- The first thirteen complete blocks have their canonical independent product law. -/
-- @node: fold_product_law
lemma fold_product_law (P : ObsLaw) (n : ℕ) :
    (dataLaw P n).map (fun data b => foldData n data b) =
      Measure.pi (fun _ : Fin 13 => Measure.pi (fun _ : Fin (roleSize n) => P.law)) := by
  have hselect := Measure.map_infinitePi_infinitePi_of_inj
    (P := fun _ : Fin n => P.law) (foldIndex_injective n)
  have hcurry := Measure.infinitePi_map_curry
    (μ := fun (_ : Fin 13) (_ : Fin (roleSize n)) => P.law)
  simp only [Measure.infinitePi_eq_pi] at hselect hcurry
  rw [← hcurry, ← hselect, Measure.map_map (by fun_prop) (by fun_prop)]
  rfl

/-- Scalar clipping. -/
def clip (lo hi z : ℝ) : ℝ := max lo (min hi z)

/-- Number of training records in a covariate cell. -/
def cellCount {m : ℕ} (train : Fin m → Omega) (mx : ℕ) (x : ℝ) : ℕ :=
  (Finset.univ.filter (fun i => cell mx (X (train i)) = cell mx x)).card
/-- Number of training records in an arm/covariate cell. -/
def armCellCount {m : ℕ} (train : Fin m → Omega) (mx : ℕ) (a : Bool) (x : ℝ) : ℕ :=
  (Finset.univ.filter (fun i => cell mx (X (train i)) = cell mx x ∧ A (train i) = a)).card
/-- Number in an arm/covariate/outcome cell. -/
def outcomeCellCount {m : ℕ} (train : Fin m → Omega) (mx my : ℕ)
    (a : Bool) (x y : ℝ) : ℕ :=
  (Finset.univ.filter (fun i => cell mx (X (train i)) = cell mx x ∧
    A (train i) = a ∧ cell my (Y (train i)) = cell my y)).card

/-- Clipped propensity pilot; an empty cell uses one half. -/
def propensityPilot {m : ℕ} (train : Fin m → Omega) (mx : ℕ) (x : ℝ) : ℝ :=
  clip (1 / 4) (3 / 4) (if cellCount train mx x = 0 then 1 / 2 else
    (armCellCount train mx true x : ℝ) / cellCount train mx x)
    -- @realizes ehat(clipped cell treatment fraction, empty value 1/2)
/-- Pilot arm probabilities. -/
def pilotPi {m : ℕ} (train : Fin m → Omega) (mx : ℕ) (a : Bool) (x : ℝ) : ℝ :=
  armProbability (propensityPilot train mx) a x -- @realizes pihat(ehat or 1-ehat)
/-- Clipped raw outcome histogram. -/
def clippedDensityPilot {m : ℕ} (train : Fin m → Omega) (mx my : ℕ)
    (a : Bool) (x y : ℝ) : ℝ :=
  clip (1 / 8) 8 (if armCellCount train mx a x = 0 then 1 else
    (my : ℝ) * outcomeCellCount train mx my a x y / armCellCount train mx a x)
/-- Clip and divide by the exact outcome integral. -/
def densityPilot {m : ℕ} (train : Fin m → Omega) (mx my : ℕ)
    (a : Bool) (x y : ℝ) : ℝ :=
  clippedDensityPilot train mx my a x y / 
    (∫ yp, clippedDensityPilot train mx my a x yp ∂unitVolume)
    -- @realizes etahat(clipped normalized density, uniform for empty arm cell)

-- @node: def:pilots
/-- The two pilots produced by the specified training algorithm. -/
def pilotHistograms {m : ℕ} (train : Fin m → Omega) (mx my : ℕ) :
    (ℝ → ℝ) × (Bool → ℝ → ℝ → ℝ) :=
  (propensityPilot train mx, densityPilot train mx my)
    -- @realizes mx(pilot covariate rank; dyadic in consuming lemmas)
    -- @realizes my(pilot outcome rank; dyadic in consuming lemmas)

/-- Normalized pilot coefficient vector. -/
def pilotCoefficients {m : ℕ} (train : Fin m → Omega) (mx my J : ℕ)
    (a : Bool) (x : ℝ) : Hj J :=
  coefficients J (densityPilot train mx my a x) -- @realizes bhat(integral Phi_J etahat)
/-- Observable propensity residual. -/
def Rres {m : ℕ} (train : Fin m → Omega) (mx : ℕ) (a : Bool) (o : Omega) : ℝ :=
  ((if A o = a then 1 else 0) - pilotPi train mx a (X o)) / pilotPi train mx a (X o)
    -- @realizes Rres(centered treatment indicator divided by pihat)
/-- Observable outcome coefficient residual. -/
def Vres {m : ℕ} (train : Fin m → Omega) (mx my J : ℕ)
    (a : Bool) (o : Omega) : Hj J :=
  ((if A o = a then 1 else 0) / pilotPi train mx a (X o)) •
    (phiCoefficients J (Y o) - pilotCoefficients train mx my J a (X o))
    -- @realizes Vres(arm indicator times Phi-bhat divided by pihat)

/-- Conditional evaluation records, with the training block fixed externally. -/
abbrev EvalData (m : ℕ) := Fin 12 → Fin m → Omega
/-- Product law of the twelve evaluation roles. -/
def evalLaw (P : ObsLaw) (m : ℕ) : Measure (EvalData m) :=
  Measure.pi (fun _ => Measure.pi (fun _ => P.law))
/-- Chain offset in the twelve evaluation roles (chain indices are zero-based). -/
def chainOffset (b : Fin 2) : ℕ := 6 * b.val -- @realizes offset(6(b-1) with zero-based chain)
/-- A chain's evaluation role. -/
def chainRole (b : Fin 2) (r : ℕ) : Fin 12 := Fin.ofNat 12 (chainOffset b + r)

/-- First-order independent-role coefficient average. -/
def Uone {m : ℕ} (train : Fin m → Omega) (mx my J : ℕ) (eval : EvalData m)
    (b : Fin 2) (a : Bool) : Hj J :=
  (m : ℝ)⁻¹ • ∑ i : Fin m, Vres train mx my J a (eval (chainRole b 0) i)
    -- @realizes Uone(m^-1 sum over first role)
/-- Multiband second-order independent-role average. -/
def Utwo {m : ℕ} (train : Fin m → Omega) (mx my L T J : ℕ) (kt : ℕ → ℕ)
    (eval : EvalData m) (b : Fin 2) (a : Bool) : Hj J :=
  (m : ℝ) ^ (-2 : ℤ) • ∑ t ∈ Finset.range (T + 1), Qband L J t
    (∑ i : Fin m, ∑ iprime : Fin m,
      (Rres train mx a (eval (chainRole b 1) i) * 
        covariateKernel (kt t) (X (eval (chainRole b 1) i)) (X (eval (chainRole b 2) iprime))) •
      Vres train mx my J a (eval (chainRole b 2) iprime))
      -- @realizes Utwo(multiband m^-2 cross average) @realizes iprime(second role index)
/-- Third-order independent-role average on the dense covariate grid. -/
def Uthree {m : ℕ} (train : Fin m → Omega) (mx my J q : ℕ)
    (eval : EvalData m) (b : Fin 2) (a : Bool) : Hj J :=
  (m : ℝ) ^ (-3 : ℤ) • ∑ i : Fin m, ∑ iprime : Fin m, ∑ isecond : Fin m,
    (Rres train mx a (eval (chainRole b 3) i) * 
      covariateKernel q (X (eval (chainRole b 3) i)) (X (eval (chainRole b 4) iprime)) * 
      Rres train mx a (eval (chainRole b 4) iprime) * 
      covariateKernel q (X (eval (chainRole b 4) iprime)) (X (eval (chainRole b 5) isecond))) •
      Vres train mx my J a (eval (chainRole b 5) isecond)
      -- @realizes Uthree(m^-3 triple cross average) @realizes isecond(third role index)

-- @node: def:chain
/-- Observable corrected treatment-minus-control coefficient chain. -/
def coefficientChain {m : ℕ} (train : Fin m → Omega) (mx my L T J q : ℕ)
    (kt : ℕ → ℕ) (eval : EvalData m) (b : Fin 2) : Hj J :=
  ∑ a : Bool, (if a then (1 : ℝ) else - 1) •
    ((∫ x, pilotCoefficients train mx my J a x ∂unitVolume) + 
      Uone train mx my J eval b a - Utwo train mx my L T J kt eval b a + 
      Uthree train mx my J q eval b a) -- @realizes Dhat(corrected arm contrast)

/-- Independent-chain energy. -/
def energy {m : ℕ} (train : Fin m → Omega) (mx my L T J q : ℕ)
    (kt : ℕ → ℕ) (eval : EvalData m) : ℝ :=
  inner ℝ (coefficientChain train mx my L T J q kt eval 0)
    (coefficientChain train mx my L T J q kt eval 1) -- @realizes Z(inner Dhat1 Dhat2)

/-- Analysis-only relative propensity error. -/
def uerr {m : ℕ} (P : ObsLaw) (train : Fin m → Omega) (mx : ℕ) (a : Bool) (x : ℝ) : ℝ :=
  (pi P a x - pilotPi train mx a x) / pilotPi train mx a x -- @realizes uerr((pi-pihat)/pihat)
/-- Analysis-only conditional density error. -/
def werr {m : ℕ} (P : ObsLaw) (train : Fin m → Omega) (mx my : ℕ)
    (a : Bool) (x y : ℝ) : ℝ :=
  P.eta a x y - densityPilot train mx my a x y -- @realizes werr(eta-etahat)
/-- Weighted density error. -/
def verr {m : ℕ} (P : ObsLaw) (train : Fin m → Omega) (mx my : ℕ)
    (a : Bool) (x y : ℝ) : ℝ :=
  (1 + uerr P train mx a x) * werr P train mx my a x y -- @realizes verr((1+u)w)
/-- Maximum uniform pilot error over both arms and the two unit domains. -/
def pilotError {m : ℕ} (P : ObsLaw) (train : Fin m → Omega) (mx my : ℕ) : ℝ :=
  max (sSup {r | ∃ a x, x ∈ Set.Icc 0 1 ∧
    r = |pilotPi train mx a x - pi P a x|})
    (sSup {r | ∃ a x y, x ∈ Set.Icc 0 1 ∧ y ∈ Set.Icc 0 1 ∧
      r = |densityPilot train mx my a x y - P.eta a x y|})
      -- @realizes epsilon(maximum sup-norm pilot error)

/-- Pilot allowance, with the paper's small-sample convention. -/
def hAllow (C0 : ℝ) (m mx my : ℕ) : ℝ :=
  if m < 3 then 1 else C0 * ((mx : ℝ) ^ (-1 / 10 : ℝ) + (my : ℝ)⁻¹ + 
    Real.sqrt ((mx : ℝ) * my * Real.log m / m) + (mx : ℝ) * my * Real.log m / m)
    -- @realizes h(public pilot allowance) @realizes C0(public pilot multiplier)
/-- Pilot failure budget. -/
def zetaAllow (m mx my : ℕ) : ℝ :=
  if m < 3 then 1 else 2 * mx * Real.exp (-(m : ℝ) / (32 * mx)) + 
    (4 * mx * my + 2 * mx) * (m : ℝ) ^ (-30 : ℤ) -- @realizes zeta(public failure allowance)
/-- Bias allowance. -/
def BAllow (C h : ℝ) (m K L T q : ℕ) (kt : ℕ → ℕ) : ℝ :=
  if m = 0 then 1 else C * (h ^ 4 + (K : ℝ) ^ (-1 / 5 : ℝ) + 
    Real.sqrt (∑ t ∈ Finset.range T,
      (kt (t + 1) : ℝ) ^ (-1 / 5 : ℝ) / ((2 ^ t * L : ℕ) : ℝ) ^ 2) + h * (q : ℝ) ^ (-1 / 5 : ℝ))
    -- @realizes B(public norm bias allowance)
/-- Covariance operator allowance. -/
def WAllow (C : ℝ) (m T : ℕ) (kt : ℕ → ℕ) : ℝ :=
  if m = 0 then 1 else C * ((m : ℝ)⁻¹ + (m : ℝ) ^ (-2 : ℤ) * 
    (Finset.range (T + 1)).sup kt) -- @realizes W(operator norm allowance)
/-- Squared covariance trace allowance. -/
def VAllow (C : ℝ) (m J L T : ℕ) (kt : ℕ → ℕ) : ℝ :=
  if m = 0 then 1 else 2 * C ^ 2 * ((J : ℝ) / (m : ℝ) ^ 2 + 
    (m : ℝ) ^ (-4 : ℤ) * ∑ t ∈ Finset.range (T + 1), (bandDimension L t : ℝ) * (kt t : ℝ) ^ 2)
    -- @realizes V(squared covariance trace allowance)

-- @node: def:allowances
/-- All five explicit public finite-resolution budgets. -/
def allowances (C0 C : ℝ) (m mx my K L T J q : ℕ) (kt : ℕ → ℕ) :
    ℝ × ℝ × ℝ × ℝ × ℝ :=
  let h := hAllow C0 m mx my
  (h, zetaAllow m mx my, BAllow C h m K L T q kt, WAllow C m T kt, VAllow C m J L T kt)

/-- Signal coefficient used in scalar inversion. -/
def aci (B W : ℝ) : ℝ := 2 * B + 10 * Real.sqrt W -- @realizes aci(2B+10 sqrt W)
/-- Constant allowance used in scalar inversion. -/
def dci (B W V : ℝ) (J : ℕ) : ℝ :=
  B ^ 2 + 400 * (J : ℝ) ^ (-2 : ℤ) + 10 * B * Real.sqrt W + 5 * Real.sqrt V
    -- @realizes dci(B^2+400 J^-2+10B sqrt W+5 sqrt V)

/-- Good-pilot event for a fixed training block. -/
def GoodPilot {m : ℕ} (P : ObsLaw) (train : Fin m → Omega) (C0 : ℝ) (mx my : ℕ) : Prop :=
  pilotError P train mx my ≤ hAllow C0 m mx my -- @realizes G(epsilon <= h)

/-- Contrast mean under the independent evaluation-block law. -/
def contrastMean {m : ℕ} (P : ObsLaw) (train : Fin m → Omega) (mx my L T J q : ℕ)
    (kt : ℕ → ℕ) : Hj J :=
  ∫ eval, coefficientChain train mx my L T J q kt eval 0 ∂evalLaw P m
    -- @realizes mu(conditional mean at fixed training realization)
/-- Covariance entries under the independent evaluation-block law. -/
def contrastCovariance {m : ℕ} (P : ObsLaw) (train : Fin m → Omega) (mx my L T J q : ℕ)
    (kt : ℕ → ℕ) : Matrix (Fin J) (Fin J) ℝ :=
  let μ := contrastMean P train mx my L T J q kt
  fun i j => ∫ eval,
    (coefficientChain train mx my L T J q kt eval 0 i - μ i) * 
    (coefficientChain train mx my L T J q kt eval 0 j - μ j) ∂evalLaw P m
    -- @realizes Sigma(conditional covariance matrix)
/-- Covariance quadratic form. -/
def covarianceForm {J : ℕ} (sigma : Matrix (Fin J) (Fin J) ℝ) (f : Hj J) : ℝ :=
  ∑ i : Fin J, ∑ j : Fin J, f i * sigma i j * f j
/-- Operator norm expressed by unit-vector quadratic forms for a symmetric positive matrix. -/
def covarianceOpNorm {J : ℕ} (sigma : Matrix (Fin J) (Fin J) ℝ) : ℝ :=
  sSup {r | ∃ f : Hj J, ‖f‖ ≤ 1 ∧ r = |covarianceForm sigma f|}
/-- Trace of the matrix square. -/
def covarianceSquareTrace {J : ℕ} (sigma : Matrix (Fin J) (Fin J) ℝ) : ℝ :=
  ∑ i : Fin J, ∑ j : Fin J, sigma i j * sigma j i

-- @node: def:inversion
/-- Candidate-energy inversion, replacing the empty feasible set by the singleton zero. -/
def invSet (z a d : ℝ) : Set ℝ :=
  let S := {s : ℝ | s ∈ Set.Icc 0 16 ∧ |z - s| ≤ a * Real.sqrt s + d}
    -- @realizes s(candidate energy in [0,16])
  if S = ∅ then {0} else S -- @realizes Inv(exact scalar inversion) @realizes s(energy in [0,16])
    -- @realizes z(real statistic argument)
/-- Quadratic discriminant. -/
def invDiscriminant (z a d : ℝ) : ℝ := a ^ 2 + 4 * (z + d)
/-- Lower endpoint in square-root coordinates. -/
def invLowerV (z a d : ℝ) : ℝ :=
  max (max 0 ((-a + Real.sqrt (a ^ 2 + 4 * max (z - d) 0)) / 2))
    ((a - Real.sqrt (invDiscriminant z a d)) / 2) -- @realizes vcoord(lower square-root coordinate)
/-- Upper endpoint in square-root coordinates. -/
def invUpperV (z a d : ℝ) : ℝ := min 4 ((a + Real.sqrt (invDiscriminant z a d)) / 2)
    -- @realizes vcoord(upper square-root coordinate bounded by 4)
/-- Explicit endpoint version, including both failure branches. -/
def invEndpoints (z a d : ℝ) : Set ℝ :=
  if invDiscriminant z a d < 0 then {0} else
    if invLowerV z a d ≤ invUpperV z a d then
      Set.Icc ((invLowerV z a d) ^ 2) ((invUpperV z a d) ^ 2) else {0}

/-- Largest power of two no larger than a positive input (totalized below one). -/
def dyadicFloor (z : ℝ) : ℕ := 2 ^ (Nat.log 2 ⌊z⌋₊)
/-- Tuned pilot covariate rank. -/
def tunedMx (m : ℕ) : ℕ := dyadicFloor (((m : ℝ) / Real.log m) ^ (10 / 13 : ℝ))
/-- Tuned pilot outcome rank. -/
def tunedMy (m : ℕ) : ℕ := dyadicFloor (((m : ℝ) / Real.log m) ^ (1 / 13 : ℝ))
/-- Tuned initial outcome rank. -/
def tunedL (m : ℕ) : ℕ := 2 ^ ⌈(4 / 29 : ℝ) * Real.logb 2 m⌉₊ -- @realizes L(dyadic outcome rank)
/-- Number of outcome bands. -/
def tunedT (m : ℕ) : ℕ := Nat.log 2 (tunedL m) -- @realizes T(log_2 L)
/-- Initial correction rank. -/
def tunedK (m : ℕ) : ℕ := (tunedL m) ^ 10 -- @realizes K(L^10)
/-- Third-order rank. -/
def tunedQ (m : ℕ) : ℕ := dyadicFloor m -- @realizes q(dyadic floor of m)
/-- Final outcome rank. -/
def tunedJ (m : ℕ) : ℕ := (tunedL m) ^ 2 -- @realizes J(L^2=2^T L)
/-- Sparse correction ranks. -/
def tunedKt (m t : ℕ) : ℕ :=
  if t = 0 then tunedK m else max (tunedMx m) (tunedK m / 2 ^ (5 * t))
    -- @realizes kt(max(mx,K 2^-5t), initial value K)
/-- Exact rate with no logarithmic factor. -/
def frontierRate (n : ℕ) : ℝ := (n : ℝ) ^ (-16 / 29 : ℝ) -- @realizes r(n^-16/29)

/-- Tuned statistic computed from the thirteen observed blocks. -/
def tunedEnergy (n : ℕ) (data : Data n) : ℝ :=
  let m := roleSize n
  energy (foldData n data 0) (tunedMx m) (tunedMy m) (tunedL m) (tunedT m)
    (tunedJ m) (tunedQ m) (tunedKt m)
    (fun b => foldData n data (Fin.ofNat 13 (b.val + 1)))
/-- Nontrivial reporting branch. -/
def reportingBranch (n : ℕ) : Prop :=
  3 ≤ roleSize n ∧ hAllow (2 ^ 16) (roleSize n) (tunedMx (roleSize n))
    (tunedMy (roleSize n)) ≤ 1 ∧
    zetaAllow (roleSize n) (tunedMx (roleSize n)) (tunedMy (roleSize n)) ≤ 1 / 100
/-- Tuned moment budgets. -/
def tunedB (n : ℕ) : ℝ :=
  let m := roleSize n
  BAllow (2 ^ 24) (hAllow (2 ^ 16) m (tunedMx m) (tunedMy m)) m
    (tunedK m) (tunedL m) (tunedT m) (tunedQ m) (tunedKt m)
/-- Tuned operator budget. -/
def tunedW (n : ℕ) : ℝ := WAllow (2 ^ 24) (roleSize n) (tunedT (roleSize n)) (tunedKt (roleSize n))
/-- Tuned trace budget. -/
def tunedV (n : ℕ) : ℝ :=
  let m := roleSize n
  VAllow (2 ^ 24) m (tunedJ m) (tunedL m) (tunedT m) (tunedKt m)

open Classical in
/-- Total observable attaining rule, ignoring the public randomization coordinate. -/
def starRule (n : ℕ) : IntervalRule n := fun ω =>
  if reportingBranch n then
    invSet (tunedEnergy n ω.1) (aci (tunedB n) (tunedW n))
      (dci (tunedB n) (tunedW n) (tunedV n) (tunedJ (roleSize n)))
  else Set.Icc 0 16 -- @realizes Istar(total data-only tuned interval)

-- @node: def:frontier-handle
/-- The asymptotically attaining output pair selected by the sharp-frontier construction:
the rate is n^(-16/29) and the rule uses the displayed tuned ranks and public budgets.
The minimax objective is `worstNullLength` among all full-class honest interval rules.
Selection is the explicit witness certified by `sharp_frontier`, with rate normalized at
n = 1; the asymptotic criterion is `AttainsFrontierRate` up to universal positive constants. -/
def frontierHandle (n : ℕ) : ℝ × IntervalRule n := (frontierRate n, starRule n)

/-- Selection conditions for an asymptotically attaining rate and data-only procedure:
positive rate normalized at n = 1, finite-sample full-class honesty, and universal
two-sided frontier bounds for the minimax expected null length objective. -/
def AttainsFrontierRate (r : ℕ → ℝ) (I : (n : ℕ) → IntervalRule n) : Prop :=
  (∀ n, 0 < n → 0 < r n) ∧ r 1 = 1 ∧
  (∀ n, IsIntervalRule n (I n) ∧ IsHonest n (I n) ∧
    ∀ data : Data n, ∀ u up : ℝ, I n (data,u) = I n (data,up)) ∧
  ∃ c C : ℝ, ∃ n0 : ℕ, 0 < c ∧ c ≤ C ∧
    ∀ n, n0 ≤ n → c * r n ≤ honestLengthFrontier n ∧
      honestLengthFrontier n ≤ worstNullLength n (I n) ∧
      worstNullLength n (I n) ≤ C * r n

end CausalSmith.Stat.DensityEffectRoughNull
