module
public import Causalean.Stat.OrderStatistic.WeightedConcomitant.ConcomitantCore

/-!
# Tagged rank concomitant expectations

This module derives the conditional-mean identity for one tagged observation
in a continuous rank-weighted marked sample.
-/

public section

namespace Causalean.Stat.OrderStatistic.WeightedConcomitant

open MeasureTheory
open Causalean.Stat.OrderStatistic
open scoped BigOperators

noncomputable section

/-- For a [bounded marked iid law](hyp:μ,hmark), a [continuous coordinate CDF](hyp:hcont),
 a [tagged coordinate and rank](hyp:i,j), and a [conditional mean function and version](hyp:m,hm), [one tagged mark restricted to one rank](goal)
 has the same expectation after replacing the mark by its conditional mean. -/
theorem integral_tagged_rank_mark_eq_conditionalMean {N : ℕ}
    (μ : Measure (ℝ × ℝ)) [IsProbabilityMeasure μ]
    (hcont : Continuous (fun t => ProbabilityTheory.cdf (μ.map Prod.fst) t))
    (hmark : ∀ᵐ p ∂μ, p.2 ∈ Set.Icc (0 : ℝ) 1)
    (i j : Fin N) (m : ℝ → ℝ)
    (hm : (fun p : ℝ × ℝ => m (ProbabilityTheory.cdf (μ.map Prod.fst) p.1))
      =ᵐ[μ] μ[(fun p : ℝ × ℝ => p.2) |
        MeasurableSpace.comap
          (fun p : ℝ × ℝ => ProbabilityTheory.cdf (μ.map Prod.fst) p.1)
          inferInstance]) :
    (∫ x, (if (Tuple.sort (fun k => (x k).1)).symm i = j then
        (x i).2 else 0) ∂Measure.pi (fun _ : Fin N => μ)) =
      ∫ x, (if (Tuple.sort (fun k => (x k).1)).symm i = j then
        m (ProbabilityTheory.cdf (μ.map Prod.fst) (x i).1) else 0)
        ∂Measure.pi (fun _ : Fin N => μ) := by
  -- Conditional expectation is taken in the tagged factor. The rank event is
  -- measurable in the sigma algebra generated by the transported coordinates;
  -- use `sort_cdf_eq_ae` before conditioning to remove dependence on raw marks.
  classical
  obtain ⟨g, hg, hmg⟩ := conditionalMean_exists_measurable_version μ m hm
  let F : ℝ × ℝ → ℝ := fun p => ProbabilityTheory.cdf (μ.map Prod.fst) p.1
  have hF : Measurable F := hcont.measurable.comp measurable_fst
  have hgm : (fun p => g (F p)) =ᵐ[μ]
      μ[(fun p : ℝ × ℝ => p.2) | MeasurableSpace.comap F inferInstance] :=
    hmg.symm.trans hm
  have hgbound : ∀ᵐ p ∂μ, |g (F p)| ≤ 1 := by
    filter_upwards [conditionalMean_comp_mem_Icc_ae μ hmark m hm, hmg] with p hp he
    rw [he] at hp
    exact abs_le.mpr ⟨by linarith [hp.1], hp.2⟩
  have hreplace :
      (∫ x, (if (Tuple.sort (fun k => (x k).1)).symm i = j then
        m (F (x i)) else 0) ∂Measure.pi (fun _ : Fin N => μ)) =
      ∫ x, (if (Tuple.sort (fun k => (x k).1)).symm i = j then
        g (F (x i)) else 0) ∂Measure.pi (fun _ : Fin N => μ) := by
    apply integral_congr_ae
    have he : ∀ᵐ x ∂Measure.pi (fun _ : Fin N => μ), m (F (x i)) = g (F (x i)) := by
      exact ae_of_ae_map (μ := Measure.pi (fun _ : Fin N => μ))
        (f := fun x : Fin N → ℝ × ℝ => x i)
        (p := fun p => m (F p) = g (F p))
        (measurable_pi_apply i).aemeasurable
        (by rw [(measurePreserving_eval (fun _ : Fin N => μ) i).map_eq]
            exact hmg)
    filter_upwards [he] with x hx
    split_ifs <;> simp [hx]
  rw [hreplace]
  cases N with
  | zero => exact i.elim0
  | succ n =>
    let ν : Measure (Fin (n + 1) → ℝ × ℝ) := Measure.pi (fun _ => μ)
    let ρ : Measure (Fin n → ℝ × ℝ) := Measure.pi (fun _ => μ)
    let e := MeasurableEquiv.piFinSuccAbove
      (fun _ : Fin (n + 1) => ℝ × ℝ) i
    let C : Set (Fin (n + 1) → ℝ × ℝ) :=
      {x | (((Finset.univ : Finset (Fin (n + 1))).erase i).filter
        (fun k => F (x k) < F (x i))).card = j.val}
    have hC : MeasurableSet C := by
      dsimp [C]
      apply measurableSet_eq_fun
      · simp_rw [Finset.card_filter]
        apply Finset.measurable_sum
        intro k _
        apply Measurable.ite
        · exact measurableSet_lt (hF.comp (measurable_pi_apply k))
            (hF.comp (measurable_pi_apply i))
        · exact measurable_const
        · exact measurable_const
      · exact measurable_const
    have hrank : ∀ᵐ x ∂ν,
        ((Tuple.sort (fun k => (x k).1)).symm i = j) ↔ x ∈ C := by
      have htransport := cdf_transport_iid (N := n + 1) μ hcont
      have hinj : ∀ᵐ x ∂ν, Function.Injective (fun k => F (x k)) := by
        have hu := iid_uniform_coordinates_injective_ae (N := n + 1)
        rw [← htransport] at hu
        exact ae_of_ae_map
          (by
            apply Measurable.aemeasurable
            apply measurable_pi_iff.mpr
            intro k
            exact hF.comp (measurable_pi_apply k)
            : AEMeasurable (fun x : Fin (n + 1) → ℝ × ℝ => fun k => F (x k)) ν) hu
      filter_upwards [sort_cdf_eq_ae μ hcont, hinj] with x hs hx
      have hc : ((Tuple.sort (fun k => F (x k))).symm i = j) ↔ x ∈ C := by
        change ((Tuple.sort (fun k => F (x k))).symm i = j) ↔
          (((Finset.univ : Finset (Fin (n + 1))).erase i).filter
            (fun k => F (x k) < F (x i))).card = j.val
        rw [← uniform_tagged_rank_eq_count (fun k => F (x k)) i hx]
        exact Fin.ext_iff
      rw [hs]
      exact hc
    let L : (Fin (n + 1) → ℝ × ℝ) → ℝ := fun x =>
      if x ∈ C then (x i).2 else 0
    let R : (Fin (n + 1) → ℝ × ℝ) → ℝ := fun x =>
      if x ∈ C then g (F (x i)) else 0
    have hLint : Integrable L ν := by
      have hmeas : Measurable L :=
        (measurable_snd.comp (measurable_pi_apply i)).ite hC measurable_const
      have hb : ∀ᵐ x ∂ν, |(x i).2| ≤ 1 := by
        have hbμ : ∀ᵐ p ∂μ, |p.2| ≤ 1 := hmark.mono fun p hp =>
          abs_le.mpr ⟨by linarith [hp.1], hp.2⟩
        exact ae_of_ae_map (μ := ν) (f := fun x : Fin (n + 1) → ℝ × ℝ => x i)
          (p := fun p => |p.2| ≤ 1) (measurable_pi_apply i).aemeasurable
          (by rw [(measurePreserving_eval (fun _ : Fin (n + 1) => μ) i).map_eq]
              exact hbμ)
      apply Integrable.of_bound hmeas.aestronglyMeasurable 1
      filter_upwards [hb] with x hx
      by_cases hc : x ∈ C
      · simpa [L, hc, Real.norm_eq_abs] using hx
      · simp [L, hc]
    have hRint : Integrable R ν := by
      have hmeas : Measurable R :=
        (hg.comp (hF.comp (measurable_pi_apply i))).ite hC measurable_const
      have hb : ∀ᵐ x ∂ν, |g (F (x i))| ≤ 1 := by
        exact ae_of_ae_map (μ := ν) (f := fun x : Fin (n + 1) → ℝ × ℝ => x i)
          (p := fun p => |g (F p)| ≤ 1) (measurable_pi_apply i).aemeasurable
          (by rw [(measurePreserving_eval (fun _ : Fin (n + 1) => μ) i).map_eq]
              exact hgbound)
      apply Integrable.of_bound hmeas.aestronglyMeasurable 1
      filter_upwards [hb] with x hx
      by_cases hc : x ∈ C
      · simpa [R, hc, Real.norm_eq_abs] using hx
      · simp [R, hc]
    have hsplit (T : (Fin (n + 1) → ℝ × ℝ) → ℝ) (hT : Integrable T ν) :
        (∫ x, T x ∂ν) = ∫ w, ∫ p, T (e.symm (p, w)) ∂μ ∂ρ := by
      have he := measurePreserving_piFinSuccAbove
        (fun _ : Fin (n + 1) => μ) i
      have hcomp : (fun z => T (e.symm z)) ∘ e = T := by
        funext x
        simp
      calc
        _ = ∫ z : (ℝ × ℝ) × (Fin n → ℝ × ℝ),
            T (e.symm z) ∂μ.prod ρ := by
              have hh := he.integral_comp' (fun z => T (e.symm z))
              change (∫ x, ((fun z => T (e.symm z)) ∘ e) x ∂ν) = _ at hh
              rw [hcomp] at hh
              exact hh
        _ = _ := by
          apply integral_prod_symm
          apply (he.integrable_comp_emb e.measurableEmbedding).mp
          change Integrable (((fun z => T (e.symm z)) ∘ e)) ν
          rw [hcomp]
          exact hT
    have hcount (p : ℝ × ℝ) (w : Fin n → ℝ × ℝ) :
        (((Finset.univ : Finset (Fin (n + 1))).erase i).filter
          (fun k => F ((e.symm (p, w)) k) < F p)).card =
        ((Finset.univ : Finset (Fin n)).filter
          (fun k => F (w k) < F p)).card := by
      have hindex : ((Finset.univ : Finset (Fin (n + 1))).erase i) =
          (Finset.univ : Finset (Fin n)).image i.succAbove := by
        ext k
        simp only [Finset.mem_erase, Finset.mem_univ, and_true,
          Finset.mem_image, Finset.mem_univ, true_and]
        rw [← Set.mem_range]
        simp [Fin.range_succAbove]
      rw [hindex, Finset.filter_image, Finset.card_image_of_injective]
      · simp [e]
      · exact Fin.succAbove_right_injective
    have hinner (w : Fin n → ℝ × ℝ) :
        (∫ p, L (e.symm (p, w)) ∂μ) =
          ∫ p, R (e.symm (p, w)) ∂μ := by
      let S : Set (ℝ × ℝ) :=
        {p | ((Finset.univ : Finset (Fin n)).filter
          (fun k => F (w k) < F p)).card = j.val}
      have hS : MeasurableSet[MeasurableSpace.comap F inferInstance] S := by
        dsimp [S]
        apply measurableSet_eq_fun
        · simp_rw [Finset.card_filter]
          apply Finset.measurable_sum
          intro k _
          apply Measurable.ite
          · exact measurableSet_lt measurable_const (comap_measurable F)
          · exact measurable_const
          · exact measurable_const
        · exact measurable_const
      have hS' : MeasurableSet S := hF.comap_le S hS
      have hL : (fun p => L (e.symm (p, w))) = S.indicator (fun p => p.2) := by
        funext p
        have hi : (e.symm (p,w)) i = p := by simp [e]
        have hc : e.symm (p,w) ∈ C ↔ p ∈ S := by
          change (((Finset.univ : Finset (Fin (n + 1))).erase i).filter
            (fun k => F ((e.symm (p,w)) k) < F ((e.symm (p,w)) i))).card = j.val ↔
            ((Finset.univ : Finset (Fin n)).filter
              (fun k => F (w k) < F p)).card = j.val
          rw [hi, hcount]
        simp only [L, Set.indicator, hi, hc]
      have hR : (fun p => R (e.symm (p, w))) = S.indicator (fun p => g (F p)) := by
        funext p
        have hi : (e.symm (p,w)) i = p := by simp [e]
        have hc : e.symm (p,w) ∈ C ↔ p ∈ S := by
          change (((Finset.univ : Finset (Fin (n + 1))).erase i).filter
            (fun k => F ((e.symm (p,w)) k) < F ((e.symm (p,w)) i))).card = j.val ↔
            ((Finset.univ : Finset (Fin n)).filter
              (fun k => F (w k) < F p)).card = j.val
          rw [hi, hcount]
        simp only [R, Set.indicator, hi, hc]
      rw [hL, hR]
      rw [integral_indicator hS', integral_indicator hS']
      calc
        (∫ p in S, p.2 ∂μ) =
            ∫ p in S, (μ[(fun p : ℝ × ℝ => p.2) |
              MeasurableSpace.comap F inferInstance]) p ∂μ :=
          (setIntegral_condExp hF.comap_le
            (Integrable.of_bound measurable_snd.aestronglyMeasurable 1
              (hmark.mono fun p hp => by
                simpa only [Real.norm_eq_abs] using
                  (abs_le.mpr ⟨by linarith [hp.1], hp.2⟩))) hS).symm
        _ = ∫ p in S, g (F p) ∂μ := by
          apply setIntegral_congr_ae hS'
          exact hgm.symm.mono (fun p hp _ => hp)
    calc
      (∫ x, (if (Tuple.sort (fun k => (x k).1)).symm i = j then
          (x i).2 else 0) ∂ν) = ∫ x, L x ∂ν := by
            apply integral_congr_ae
            filter_upwards [hrank] with x hx
            simp only [L, if_congr hx rfl rfl]
      _ = ∫ w, ∫ p, L (e.symm (p, w)) ∂μ ∂ρ := hsplit L hLint
      _ = ∫ w, ∫ p, R (e.symm (p, w)) ∂μ ∂ρ := by
        exact integral_congr_ae (Filter.Eventually.of_forall hinner)
      _ = ∫ x, R x ∂ν := (hsplit R hRint).symm
      _ = ∫ x, (if (Tuple.sort (fun k => (x k).1)).symm i = j then
          g (F (x i)) else 0) ∂ν := by
            apply integral_congr_ae
            filter_upwards [hrank] with x hx
            simp only [R, if_congr hx rfl rfl]

end
end Causalean.Stat.OrderStatistic.WeightedConcomitant
