/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Basic
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.AllLabelAmbiguityBridge
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.AllLabelCellScaling
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.AllLabelCouplingRange
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.AllLabelDefinitions
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.AllLabelFairCell
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.AllLabelSupremumUpper
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.AllLabelUpperCell
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.CompandingReleaseGeometry
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.CompatibilityFullLawConstruction
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.CompatibilityReconstruction
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.External
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerBasic
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerCertificate
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerCertificateAssembly
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerCertificateTransfer
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerScoreLogArmCell
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerScoreLogAttainment
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerScoreLogCalibration
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerScoreLogCellIdentification
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerScoreLogCertificate
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerScoreLogExperiment
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerScoreLogFinal
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerScoreLogFullLaw
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerScoreLogHonestLength
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerScoreLogInverseQuantile
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerScoreLogLimit
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerScoreLogPair
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerScoreLogQuantileBridge
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerScoreLogQuantileExact
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerScoreLogQuantileIntegrals
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerScoreLogSharp
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerScoreLogSharpATE
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerScoreLogTesting
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerScoreLogThresholds
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerTrialPair
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerTrialSharp
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ExternalLowerTrialTesting
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.FixedLaw
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.FixedLawAttainment
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.FixedLawCellCoupling
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.FixedLawConvexity
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.FixedLawCoverage
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.FixedLawEndpointAssembly
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.FixedLawEndpointConstruction
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.FixedLawEndpointFullRow
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.FixedLawMembership
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.HighResolutionCost
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.HighResolutionFiniteInfimum
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.HighResolutionObjective
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.HighResolutionOptimal
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.HighResolutionOrderedCost
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.HighResolutionOrderedRelease
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.HighResolutionPartitionRelease
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.Inference
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.InferenceMidpointBias
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.InferenceMidpointConcentration
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.InferenceMidpointProcedure
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.KLabelDefinitions
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.KLabelFiniteGeometry
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.KLabelFiniteLower
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.KLabelRateLower
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.MinimaxHonestLengthFiniteLabel
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.MinimaxHonestLengthFiniteLabelOuter
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.MinimaxHonestLengthRateAssembly
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.MinimaxHonestLengthSamplingLower
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.MinimaxHonestLengthSamplingPair
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.MinimaxHonestLengthSamplingTV
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.MinimaxHonestLengthTesting
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.MinimaxHonestLengthUpper
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.OrderedIntervalPartition
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.Projection
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ProjectionCDFTransport
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ProjectionCandidateStability
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ProjectionCellStability
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ProjectionCellTransport
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ProjectionCoverage
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ProjectionDistanceTriangle
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ProjectionEmpirical
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ProjectionEmpiricalFinite
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ProjectionEmpiricalMean
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ProjectionEndpointAlgebra
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ProjectionEndpointBounds
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ProjectionEndpointGeometryMeasurable
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ProjectionEndpointMeasurable
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ProjectionGeometry
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ProjectionInference
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ProjectionIntegrated
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ProjectionPopulation
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ProjectionRiskEnvelope
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ProjectionRiskExpectation
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ProjectionScorePopulation
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ProjectionSharpLength
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ProjectionSieveApproximation
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ProjectionSieveDensity
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.ProjectionSieveDensityBridge
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.Helpers.Quantization
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.OpenQuestions
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.TAllLabelAmbiguity
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.TCompatibility
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.TExternalScoreRootOrder
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.TKLabelRate
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.TMinimaxHonestLength
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.TSharpHighResolutionConstant
public import CausalSmith.PartialID.PID_UnlinkedPropensityAte_Research.TUniversalPointIdentification

/-! # Run barrel (auto-generated)

Aggregates every module of this causalsmith run so the whole run is ONE buildable target
(`lake build <this module>`). Research modules are not reachable from the top-level
`CausalSmith.lean` barrel, so the default lake target skips them and reports green on stale
oleans. Rewritten from the run's module set on every F-stage entry — do not hand-edit. -/
