/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan

# Concrete projection operator for the TRAE rate theorem

This file defines the concrete projection operator
    `T h := Π_{Q̄} ∘ E[· | σ(Z)]`
used in the simplified rate theorem of
`doc/basic_concepts/po/estimation/trae_inverse_problems.tex` (lines 250–384).

## Design

`Setup.lean` keeps `Hbar`, `Qbar` as plain function sets without
Hilbert structure, since the mixed-bias proof only needs algebraic linearity.
The rate theorem requires an L² realization: closed subspaces
`Hbar_L2`, `Qbar_L2 : Submodule ℝ (Lp ℝ 2 μ)` of the *ambient* `Lp ℝ 2 μ`,
together with embeddings of function-level members.  We choose the ambient
`Lp ℝ 2 μ` (rather than pushforward `Lp ℝ 2 (μ.map X)`) so the conditional
expectation `condExpL2` can be applied directly without pushforward
identifications.

The σ-algebra "generated by `Z`" is encoded as
`m_Z := MeasurableSpace.comap S.zOf S.inst𝒵 ∘ (... lifted along W)` —
concretely `MeasurableSpace.comap (zOf ∘ W) inst𝒵`, with a hypothesis
`m_Z_le : m_Z ≤ m₀`.

The operator `T h` is then:
1.  lift `h ∘ X : Ω → ℝ` into `Lp ℝ 2 μ` (via a `MemLp` hypothesis on
    `OperatorSystem`);
2.  apply `MeasureTheory.condExpL2 ℝ ℝ m_Z_le` (a continuous linear map into
    the σ(Z)-measurable subspace);
3.  project onto `Qbar_L2` via `Submodule.orthogonalProjectionFn`.

The single population identity exported here, `T_inner_eq_integral`, is what
the rate theorem consumes.  Its proof combines `condExpL2` self-adjointness
with the orthogonality characterization of `Qbar_L2`-projection; it is fully
proved (no sorries).

The adjoint `T*` and the self-adjoint composite `T†T` are bundled in
`Operator/Adjoint.lean`; this file focuses on the unbundled projection operator
and the population identity needed by the DR rate argument.
-/

import Causalean.Estimation.NPIV.Setup
import Mathlib.MeasureTheory.Function.ConditionalExpectation.CondexpL2
import Mathlib.Analysis.InnerProductSpace.Projection.Basic

/-!
Extends the inverse-problem system with population operators for NPIV
estimation. The module defines the operator interface connecting structural
functions, instruments, and conditional-moment equations.
-/

namespace Causalean
namespace Estimation
namespace NPIV

open MeasureTheory
open scoped InnerProductSpace

/-! ## Operator-system extension of `InverseProblemSystem` -/

/-- An **operator system**: an `InverseProblemSystem` enriched with the L² data needed to
define the concrete population projection operator `T = Π_{Q̄} ∘ E[· | σ(Z)]`. On top of the
base system it packages [the σ-algebra generated by the instrument `Z`](hyp:m_Z), with the
facts that [it is coarser than the ambient σ-algebra on the sample space](hyp:m_Z_le) and
[coincides with the σ-algebra pulled back along `Z`](hyp:m_Z_eq), that [the ambient
probability measure is finite](hyp:isFiniteMeasure), and [closed submodules of the ambient
`L²(μ)` space realizing the primal and dual candidate function classes](hyp:Hbar_L2,Qbar_L2),
the dual one further required to [admit an orthogonal projection](hyp:Qbar_L2_hasProj);
finally, every candidate primal or dual function is [square-integrable once composed with the
covariate or instrument map](hyp:toHbarL2,toQbarL2), with [its `L²` class coherently landing
inside the matching submodule](hyp:hbar_mem_L2,qbar_mem_L2). -/
structure OperatorSystem
    (Ω : Type*) [m₀ : MeasurableSpace Ω] (μ : Measure Ω)
    extends InverseProblemSystem Ω μ where
  /-- The σ-algebra generated by `Z = zOf ∘ W : Ω → 𝒵`. -/
  m_Z : MeasurableSpace Ω
  /-- `m_Z` is coarser than `m₀`. -/
  m_Z_le : m_Z ≤ m₀
  /-- (Optional consistency:) `m_Z = comap (zOf ∘ W) inst𝒵`.  This pins the
  σ-algebra to the one generated by `Z`. -/
  m_Z_eq : m_Z =
    @MeasurableSpace.comap Ω 𝒵 (fun ω => zOf (W ω)) inst𝒵
  /-- `μ` is finite (sufficient for the conditional-expectation identities
  used in the rate proof). -/
  isFiniteMeasure : IsFiniteMeasure μ
  /-- L² realization of `Hbar`: a closed submodule of the ambient `Lp ℝ 2 μ`. -/
  Hbar_L2 : Submodule ℝ (Lp ℝ 2 μ)
  /-- L² realization of `Qbar`. -/
  Qbar_L2 : Submodule ℝ (Lp ℝ 2 μ)
  /-- `Qbar_L2` admits an orthogonal projection (in particular, is closed). -/
  Qbar_L2_hasProj : Qbar_L2.HasOrthogonalProjection
  /-- Embedding witness: for every `h ∈ Hbar`, the function
  `ω ↦ h (X ω) = h (xOf (W ω))` is square-integrable. -/
  toHbarL2 : ∀ h ∈ Hbar, MemLp (fun ω => h (xOf (W ω))) 2 μ
  /-- Embedding witness: for every `q ∈ Qbar`, the function
  `ω ↦ q (Z ω) = q (zOf (W ω))` is square-integrable. -/
  toQbarL2 : ∀ q ∈ Qbar, MemLp (fun ω => q (zOf (W ω))) 2 μ
  /-- Coherence: the `Lp` class of `h ∘ X` lies in the closed subspace
  `Hbar_L2`. -/
  hbar_mem_L2 :
    ∀ h (hh : h ∈ Hbar), (toHbarL2 h hh).toLp _ ∈ Hbar_L2
  /-- Coherence: the `Lp` class of `q ∘ Z` lies in `Qbar_L2`. -/
  qbar_mem_L2 :
    ∀ q (hq : q ∈ Qbar), (toQbarL2 q hq).toLp _ ∈ Qbar_L2

namespace OperatorSystem

variable {Ω : Type*} [MeasurableSpace Ω] {μ : Measure Ω}

/-- For [an NPIV operator system](hyp:S) and [a covariate function belonging to its primal candidate set](hyp:hh), [the lifted primal candidate is the $L^2$ equivalence class of that function evaluated at the covariates](goal).

Lift `h ∈ Hbar` to its L² class
`(h ∘ X)_{Lp} ∈ Lp ℝ 2 μ`.  This is just a name. -/
noncomputable def hL2 (S : OperatorSystem Ω μ) {h : S.𝒳 → ℝ}
    (hh : h ∈ S.Hbar) : Lp ℝ 2 μ :=
  (S.toHbarL2 h hh).toLp _

/-- For [an NPIV operator system](hyp:S) and [an instrument function belonging to its dual candidate set](hyp:hq), [the lifted dual candidate is the $L^2$ equivalence class of that function evaluated at the instruments](goal).

Lift `q ∈ Qbar` to its L² class
`(q ∘ Z)_{Lp} ∈ Lp ℝ 2 μ`. -/
noncomputable def qL2 (S : OperatorSystem Ω μ) {q : S.𝒵 → ℝ}
    (hq : q ∈ S.Qbar) : Lp ℝ 2 μ :=
  (S.toQbarL2 q hq).toLp _

/-! ## The projection operator `T`

We define `T` on the ambient `Lp ℝ 2 μ` (so its action on `Hbar`-side
elements is `T (S.hL2 hh)`).  Composition order:
`T = orthogonalProjectionFn Qbar_L2 ∘ (condExpL2 ℝ ℝ m_Z_le)`. -/

/-- For [an NPIV operator system](hyp:S), [the conditional-expectation operator maps every ambient $L^2$ random variable to its conditional expectation given the σ-algebra generated by the instrument](goal).

The conditional-expectation step `E[· | σ(Z)]`, viewed as a self-map
of `Lp ℝ 2 μ` (via the canonical inclusion of the σ(Z)-measurable
subspace).

This is the composition
`Lp 2 μ →L[ℝ] lpMeas ℝ ℝ m_Z 2 μ → Lp 2 μ`
where the second arrow is the structural inclusion (each `lpMeas` element
*is* an `Lp` element). -/
noncomputable def condExpStep (S : OperatorSystem Ω μ) :
    Lp ℝ 2 μ → Lp ℝ 2 μ :=
  haveI := S.isFiniteMeasure
  fun f => (MeasureTheory.condExpL2 ℝ ℝ S.m_Z_le f : Lp ℝ 2 μ)

/-- For [an NPIV operator system](hyp:S) and [an ambient $L^2$ random variable](hyp:f), [the NPIV projection operator is the orthogonal projection onto the closed dual candidate space of that variable's conditional expectation given the instrument](goal).

The concrete projection operator
`T = Π_{Q̄} ∘ E[· | σ(Z)]`.

Acts on the ambient `Lp ℝ 2 μ`; the rate theorem applies it to
`S.hL2 hh - S.hL2 hh' = (S.hL2 hh) - (S.hL2 hh')`. -/
noncomputable def T (S : OperatorSystem Ω μ) (f : Lp ℝ 2 μ) : Lp ℝ 2 μ :=
  haveI := S.Qbar_L2_hasProj
  S.Qbar_L2.orthogonalProjectionFn (S.condExpStep f)

/-! ## Linearity helpers for `T`

`T = Π_{Q̄} ∘ condExpL2` is a composition of two ℝ-linear maps:

* `condExpL2 ℝ ℝ S.m_Z_le : Lp 2 μ →L[ℝ] (lpMeas ℝ ℝ S.m_Z 2 μ)`, then
  embedded into `Lp 2 μ` (linear by definition of `condExpStep`).
* `Submodule.orthogonalProjectionFn` agrees with the bundled
  `Submodule.orthogonalProjection : E →L[ℝ] K` followed by the
  subtype embedding (`Submodule.orthogonalProjectionFn_eq`), so it is
  ℝ-linear too.

We expose the two basic linearity lemmas the rate proof consumes
(`T_add`, `T_sub`); a `LinearMap` form is not needed at this stage. -/

/-- `condExpStep` distributes over subtraction (linearity of
`condExpL2`). -/
lemma condExpStep_sub (S : OperatorSystem Ω μ) (f g : Lp ℝ 2 μ) :
    S.condExpStep (f - g) = S.condExpStep f - S.condExpStep g := by
  haveI := S.isFiniteMeasure
  unfold condExpStep
  simp [map_sub]

/-- `T` distributes over subtraction. -/
lemma T_sub (S : OperatorSystem Ω μ) (f g : Lp ℝ 2 μ) :
    S.T (f - g) = S.T f - S.T g := by
  haveI := S.Qbar_L2_hasProj
  unfold T
  rw [S.condExpStep_sub]
  -- Reduce `orthogonalProjectionFn (a - b)` to
  -- `orthogonalProjectionFn a - orthogonalProjectionFn b` via the
  -- rfl-equality `orthogonalProjectionFn = ((orthogonalProjection ·) : _)`
  -- and `map_sub` on the bundled CLM `orthogonalProjection`.
  change ((S.Qbar_L2.orthogonalProjection (S.condExpStep f - S.condExpStep g)) : Lp ℝ 2 μ)
        = ((S.Qbar_L2.orthogonalProjection (S.condExpStep f)) : Lp ℝ 2 μ)
            - ((S.Qbar_L2.orthogonalProjection (S.condExpStep g)) : Lp ℝ 2 μ)
  rw [map_sub]
  rfl

/-- `T` distributes over addition (companion to `T_sub`). -/
lemma T_add (S : OperatorSystem Ω μ) (f g : Lp ℝ 2 μ) :
    S.T (f + g) = S.T f + S.T g := by
  haveI := S.Qbar_L2_hasProj
  haveI := S.isFiniteMeasure
  unfold T condExpStep
  change ((S.Qbar_L2.orthogonalProjection
            ((MeasureTheory.condExpL2 ℝ ℝ S.m_Z_le (f + g) : Lp ℝ 2 μ))) : Lp ℝ 2 μ)
        = ((S.Qbar_L2.orthogonalProjection
            ((MeasureTheory.condExpL2 ℝ ℝ S.m_Z_le f : Lp ℝ 2 μ))) : Lp ℝ 2 μ)
          + ((S.Qbar_L2.orthogonalProjection
            ((MeasureTheory.condExpL2 ℝ ℝ S.m_Z_le g : Lp ℝ 2 μ))) : Lp ℝ 2 μ)
  simp [map_add]

/-! ## Population identity

The rate theorem (`trae_inverse_problems.tex` lines 250–384) needs exactly
one population identity for `T`:

    ⟨T (h - h'), f⟩_{L²(μ)}
      = ∫ ω, (h (X ω) - h' (X ω)) · f (Z ω) ∂μ

for `h, h' ∈ Hbar` and `f ∈ Qbar`.  Sketch of proof:

1.  By `Submodule.orthogonalProjectionFn_inner_eq_zero` applied to
    `S.Qbar_L2` and `S.qL2 hf ∈ S.Qbar_L2`, the projection step is
    invisible in the inner product:
        ⟨T u, qL2 hf⟩ = ⟨condExpStep u, qL2 hf⟩.

2.  By `MeasureTheory.inner_condExpL2_left_eq_right` (self-adjointness of
    `condExpL2`) and the fact that `qL2 hf` is already
    σ(Z)-measurable (so `condExpL2 (qL2 hf) = qL2 hf`), we get
        ⟨condExpStep u, qL2 hf⟩ = ⟨u, qL2 hf⟩.

3.  Unwinding `Lp` inner products to integrals (`L2.inner_def`) yields
    the right-hand side.

Step 2 needs `S.qL2 hf` to actually live in the σ(Z)-measurable subspace;
that is the content of `qbar_aestrongly_measurable_mZ` below (proven from
`m_Z_eq` and `meas_of_Qbar`, no extra hypothesis required). -/

/-- For [an NPIV operator system](hyp:S), [this predicate asserts that every dual candidate, evaluated at the instrument of a sampled observation, is almost-everywhere strongly measurable with respect to the instrument-generated σ-algebra](goal).

Hypothesis used by `T_inner_eq_integral`: `q ∘ Z` is `m_Z`-strongly
measurable (a.e.).  Derivable from `m_Z_eq` and `meas_of_Qbar`; see
`qbar_aestrongly_measurable_mZ` below.  Kept as a `def` so existing call
sites (which take it as a separate hypothesis) continue to compile. -/
def QbarAEMeasurableMZ (S : OperatorSystem Ω μ) : Prop :=
  ∀ q, q ∈ S.Qbar →
    AEStronglyMeasurable[S.m_Z] (fun ω => q (S.zOf (S.W ω))) μ

/-- `q ∘ zOf ∘ W` is `m_Z`-strongly measurable for every `q ∈ Qbar`.
Direct consequence of `m_Z_eq : m_Z = comap (zOf ∘ W) inst𝒵` and
`meas_of_Qbar`: the canonical map `(zOf ∘ W) : Ω → 𝒵` is measurable from
`comap (zOf ∘ W) inst𝒵` to `inst𝒵` (`comap_measurable`), so its
composition with the `inst𝒵`-measurable `q : 𝒵 → ℝ` is
`m_Z`-measurable, hence `m_Z`-strongly measurable into ℝ. -/
lemma qbar_aestrongly_measurable_mZ (S : OperatorSystem Ω μ) :
    S.QbarAEMeasurableMZ := by
  intro q hq
  have hZ : @Measurable Ω S.𝒵 S.m_Z S.inst𝒵 (fun ω => S.zOf (S.W ω)) := by
    rw [S.m_Z_eq]
    exact comap_measurable _
  have hq_meas : @Measurable S.𝒵 ℝ S.inst𝒵 _ q := S.meas_of_Qbar q hq
  have h_meas :
      @Measurable Ω ℝ S.m_Z _ (fun ω => q (S.zOf (S.W ω))) :=
    @Measurable.comp Ω S.𝒵 ℝ S.m_Z S.inst𝒵 _ q
      (fun ω => S.zOf (S.W ω)) hq_meas hZ
  exact h_meas.aestronglyMeasurable

/-- **Population identity for `T`.** Consider an operator system `S` — an inverse-problem
system enriched with an L² realization of the candidate sets — and fix [two primal candidate
functions `h`, `h'` in the primal candidate set `Hbar`](hyp:hh,hh') together with [a dual
candidate function `f` in the dual candidate set `Qbar`](hyp:hf). Writing `T` for the operator
that conditions on the σ-algebra generated by the instrument `Z` and then orthogonally
projects onto the L² realization of `Qbar`, [the `L²(μ)` inner product of `T` applied to the
lifted residual `h − h'` against the lifted `f` equals the expectation of the pointwise
product `(h(X) − h'(X))·f(Z)`](goal).

    ⟨T (hL2 hh - hL2 hh'), qL2 hf⟩_{L²(μ)}
      = ∫ ω, (h (X ω) - h' (X ω)) · f (Z ω) ∂μ.

This is the only identity the simplified TRAE rate proof requires from `T`.
The proof composes:

* invisibility of `Π_{Q̄}` against a `Q̄`-element
  (`Submodule.orthogonalProjectionFn_inner_eq_zero` on the residual);
* self-adjointness of `condExpL2` and idempotence on σ(Z)-measurable
  L² classes (uses `qbar_meas_mZ`);
* unwinding `Lp` inner products to Bochner integrals.
-/
theorem T_inner_eq_integral
    (S : OperatorSystem Ω μ)
    {h h' : S.𝒳 → ℝ} (hh : h ∈ S.Hbar) (hh' : h' ∈ S.Hbar)
    {f : S.𝒵 → ℝ} (hf : f ∈ S.Qbar) :
    inner ℝ (S.T (S.hL2 hh - S.hL2 hh')) (S.qL2 hf)
      = ∫ ω, (h (S.xOf (S.W ω)) - h' (S.xOf (S.W ω))) *
              f (S.zOf (S.W ω)) ∂μ := by
  haveI := S.isFiniteMeasure
  haveI := S.Qbar_L2_hasProj
  let u : Lp ℝ 2 μ := S.hL2 hh - S.hL2 hh'
  have hq_mem : S.qL2 hf ∈ S.Qbar_L2 := S.qbar_mem_L2 f hf
  have h_proj :
      inner ℝ (S.T u) (S.qL2 hf) =
        inner ℝ (S.condExpStep u) (S.qL2 hf) := by
    have h_zero :
        inner ℝ (S.condExpStep u - S.Qbar_L2.orthogonalProjectionFn (S.condExpStep u))
          (S.qL2 hf) = 0 :=
      S.Qbar_L2.orthogonalProjectionFn_inner_eq_zero (S.condExpStep u) (S.qL2 hf) hq_mem
    have h_eq :
        inner ℝ (S.condExpStep u) (S.qL2 hf) =
          inner ℝ (S.Qbar_L2.orthogonalProjectionFn (S.condExpStep u)) (S.qL2 hf) := by
      rw [inner_sub_left] at h_zero
      exact sub_eq_zero.mp h_zero
    simpa [OperatorSystem.T] using h_eq.symm
  have hq_meas :
      AEStronglyMeasurable[S.m_Z] (S.qL2 hf : Ω → ℝ) μ :=
    (S.qbar_aestrongly_measurable_mZ f hf).congr (S.toQbarL2 f hf).coeFn_toLp.symm
  have h_cond :
      inner ℝ (S.condExpStep u) (S.qL2 hf) =
        inner ℝ u (S.qL2 hf) := by
    simpa [OperatorSystem.condExpStep] using
      (MeasureTheory.inner_condExpL2_eq_inner_fun (E := ℝ) (𝕜 := ℝ)
        S.m_Z_le u (S.qL2 hf) hq_meas)
  have h_inner :
      inner ℝ u (S.qL2 hf) =
        ∫ ω, (h (S.xOf (S.W ω)) - h' (S.xOf (S.W ω))) *
              f (S.zOf (S.W ω)) ∂μ := by
    rw [MeasureTheory.L2.inner_def]
    refine integral_congr_ae ?_
    filter_upwards [Lp.coeFn_sub (S.hL2 hh) (S.hL2 hh'),
      (S.toHbarL2 h hh).coeFn_toLp, (S.toHbarL2 h' hh').coeFn_toLp,
      (S.toQbarL2 f hf).coeFn_toLp] with ω hu hhω hh'ω hfω
    calc
      ⟪u ω, (S.qL2 hf) ω⟫_ℝ
          = ⟪(S.hL2 hh) ω - (S.hL2 hh') ω, (S.qL2 hf) ω⟫_ℝ := by
            have huω : u ω = (S.hL2 hh) ω - (S.hL2 hh') ω := by
              simpa [u, Pi.sub_apply] using hu
            rw [huω]
      _ = ⟪h (S.xOf (S.W ω)) - h' (S.xOf (S.W ω)),
            f (S.zOf (S.W ω))⟫_ℝ := by
            simp [OperatorSystem.hL2, OperatorSystem.qL2, hhω, hh'ω, hfω]
      _ = (h (S.xOf (S.W ω)) - h' (S.xOf (S.W ω))) *
            f (S.zOf (S.W ω)) := by
            change f (S.zOf (S.W ω)) *
                (h (S.xOf (S.W ω)) - h' (S.xOf (S.W ω))) =
              (h (S.xOf (S.W ω)) - h' (S.xOf (S.W ω))) *
                f (S.zOf (S.W ω))
            ring
  calc
    inner ℝ (S.T (S.hL2 hh - S.hL2 hh')) (S.qL2 hf)
        = inner ℝ (S.T u) (S.qL2 hf) := by simp [u]
    _ = inner ℝ (S.condExpStep u) (S.qL2 hf) := h_proj
    _ = inner ℝ u (S.qL2 hf) := h_cond
    _ = ∫ ω, (h (S.xOf (S.W ω)) - h' (S.xOf (S.W ω))) *
              f (S.zOf (S.W ω)) ∂μ := h_inner

/-! ## Norm helpers

The simplified rate theorem packages two seminorms:

* the **strong norm** `‖h - h'‖_{strong} := ‖hL2 hh - hL2 hh'‖_{L²(μ)}`,
  i.e. the ambient `Lp` norm of the lifted residual;
* the **weak norm** `‖h - h'‖_{weak} := ‖T (hL2 hh - hL2 hh')‖_{L²(μ)}`,
  i.e. the `Lp` norm after projection.

We expose them on the lifted `Lp ℝ 2 μ` argument (no ambient `MemLp`
witness juggling). -/

/-- For [an NPIV operator system](hyp:_S) and [an ambient $L^2$ random variable](hyp:f), [the strong norm is that variable's $L^2$ norm](goal). -/
noncomputable def strongNorm (_S : OperatorSystem Ω μ) (f : Lp ℝ 2 μ) : ℝ :=
  ‖f‖

/-- For [an NPIV operator system](hyp:S) and [an ambient $L^2$ random variable](hyp:f), [the weak norm is the $L^2$ norm of its projected conditional expectation](goal).

Weak norm associated to `T`: `‖T f‖_{L²(μ)}`. -/
noncomputable def weakNorm (S : OperatorSystem Ω μ) (f : Lp ℝ 2 μ) : ℝ :=
  ‖S.T f‖

/-- The projected conditional-expectation norm is bounded by the ambient
`L²` norm. -/
lemma weakNorm_le_strongNorm (S : OperatorSystem Ω μ) (f : Lp ℝ 2 μ) :
    S.weakNorm f ≤ S.strongNorm f := by
  haveI := S.isFiniteMeasure
  haveI := S.Qbar_L2_hasProj
  calc
    S.weakNorm f = ‖S.Qbar_L2.starProjection (S.condExpStep f)‖ := by
      rw [weakNorm, T]
    _ ≤ ‖S.condExpStep f‖ := S.Qbar_L2.norm_starProjection_apply_le (S.condExpStep f)
    _ ≤ ‖f‖ := by
      simpa [condExpStep] using
        (MeasureTheory.norm_condExpL2_coe_le (E := ℝ) (𝕜 := ℝ) S.m_Z_le f)
    _ = S.strongNorm f := by
      rw [strongNorm]

/-- Squared strong norm of a lifted `Hbar` member, unfolded as the integral
of the squared representative. -/
lemma strongNorm_sq_hL2_eq_integral
    (S : OperatorSystem Ω μ) {h : S.𝒳 → ℝ} (hh : h ∈ S.Hbar) :
    (S.strongNorm (S.hL2 hh)) ^ 2 = ∫ ω, (h (S.xOf (S.W ω))) ^ 2 ∂μ := by
  calc
    (S.strongNorm (S.hL2 hh)) ^ 2 = inner ℝ (S.hL2 hh) (S.hL2 hh) := by
      rw [OperatorSystem.strongNorm, real_inner_self_eq_norm_sq]
    _ = ∫ ω, ⟪(S.hL2 hh) ω, (S.hL2 hh) ω⟫_ℝ ∂μ := by
      rw [MeasureTheory.L2.inner_def]
    _ = ∫ ω, (h (S.xOf (S.W ω))) ^ 2 ∂μ := by
      refine integral_congr_ae ?_
      filter_upwards [(S.toHbarL2 h hh).coeFn_toLp] with ω hω
      simp [OperatorSystem.hL2, hω, pow_two]

end OperatorSystem

end NPIV
end Estimation
end Causalean
