/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import Causalean.Stat.CLT.SampleFnEstimator
public import Causalean.Stat.MEstimation.SmoothZEstimator

/-! # Smooth-score Z-estimators defined on finite sample vectors

This module specializes the smooth-score asymptotic-linearity and normality
theorems to estimators implemented as functions of `IIDSample.sampleVector`.
The wrappers retain the approximate estimating-equation condition and inherit
the internally derived root-sample-size rate.
-/

public section

namespace Causalean.Stat

open MeasureTheory ProbabilityTheory Filter Topology

variable {Ω X : Type*} [MeasurableSpace Ω] [MeasurableSpace X]
  {μ : Measure Ω} {P : Measure X}
  {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [FiniteDimensional ℝ E] [MeasurableSpace E] [BorelSpace E]

/-- **Sample-function smooth-score asymptotic linearity.** Given [a score,
target, population law, and smooth regularity package](hyp:ψ,θ₀,P,reg),
evaluate [an estimator on finite sample vectors](hyp:est) using [an iid
sample](hyp:S). If the resulting estimator [is consistent](hyp:hConsistent)
and [has an `o_p(n⁻¹/²)` estimating-equation residual](hyp:hMoment), then [it
is asymptotically linear with influence function `-V⁻¹ ψ(θ₀,·)`](goal). -/
theorem zEstimator_asymLinear_of_smoothScore_of_sampleFn
    (ψ : E → X → E) (θ₀ : E) (P : Measure X)
    (reg : SmoothZEstimatorRegularity ψ θ₀ P)
    [IsProbabilityMeasure μ]
    (S : IIDSample Ω X μ P) (est : (n : ℕ) → (Fin n → X) → E)
    (hConsistent : ∀ ε > 0,
      Tendsto
        (fun n => μ {ω | ε < ‖est n (S.sampleVector n ω) - θ₀‖})
        atTop (𝓝 0))
    (hMoment : IsLittleOp
      (fun n ω => ‖(Real.sqrt (n : ℝ))⁻¹ •
        ∑ i ∈ Finset.range n,
          ψ (est n (S.sampleVector n ω)) (S.Z i ω)‖)
      (fun _ => (1 : ℝ)) μ) :
    IsAsymLinearVec (E := E)
      (fun n ω => est n (S.sampleVector n ω)) θ₀ reg.influence S
      (fun n => Finset.range n) :=
  zEstimator_asymLinear_of_smoothScore ψ θ₀ P reg S
    (fun n ω => est n (S.sampleVector n ω)) hConsistent hMoment

/-- **Sample-function smooth-score asymptotic normality.** Given [a score,
target, population law, and smooth regularity package](hyp:ψ,θ₀,P,reg),
evaluate [an estimator on finite sample vectors](hyp:est) using [an iid
sample](hyp:S). If it [is consistent](hyp:hConsistent), [has an
`o_p(n⁻¹/²)` estimating-equation residual](hyp:hMoment), and [has measurable
rescalings](hyp:hEstMeas), then [its rescaled laws converge to the centered
Gaussian generated by `-V⁻¹ ψ(θ₀,·)`](goal). -/
theorem zEstimator_tendsto_normal_of_smoothScore_of_sampleFn
    (ψ : E → X → E) (θ₀ : E) (P : Measure X)
    (reg : SmoothZEstimatorRegularity ψ θ₀ P)
    [IsProbabilityMeasure μ]
    (S : IIDSample Ω X μ P) (est : (n : ℕ) → (Fin n → X) → E)
    (hConsistent : ∀ ε > 0,
      Tendsto
        (fun n => μ {ω | ε < ‖est n (S.sampleVector n ω) - θ₀‖})
        atTop (𝓝 0))
    (hMoment : IsLittleOp
      (fun n ω => ‖(Real.sqrt (n : ℝ))⁻¹ •
        ∑ i ∈ Finset.range n,
          ψ (est n (S.sampleVector n ω)) (S.Z i ω)‖)
      (fun _ => (1 : ℝ)) μ)
    (hEstMeas : ∀ n, AEMeasurable
      (IsAsymLinearVec.rescaledEstimator
        (fun m ω => est m (S.sampleVector m ω)) θ₀
        (fun m => Finset.range m) n) μ) :
    Tendsto (β := ProbabilityMeasure E)
      (fun n => ⟨μ.map
        (IsAsymLinearVec.rescaledEstimator
          (fun m ω => est m (S.sampleVector m ω)) θ₀
          (fun m => Finset.range m) n),
        Measure.isProbabilityMeasure_map (hEstMeas n)⟩)
      atTop
      (𝓝 ⟨gaussianLimit reg.influence_measurable reg.influence_integrable_sq,
        inferInstance⟩) :=
  zEstimator_tendsto_normal_of_smoothScore ψ θ₀ P reg S
    (fun n ω => est n (S.sampleVector n ω)) hConsistent hMoment hEstMeas

end Causalean.Stat
