module
public import CausalSmith.Experimentation.EXP_SnipeDegreeFrontier_Research.Helpers.BlockScore
public import Causalean.Experimentation.DesignBased.ProductBlock
public import Causalean.Experimentation.DesignBased.ProductVariance
public import Causalean.Experimentation.DesignBased.Risk
public import Mathlib.MeasureTheory.Constructions.Pi
public import Mathlib.Order.ConditionallyCompleteLattice.Basic

/-!
# Fixed-graph block-local linear class

The graph is fixed in this restricted problem.  Locality is expressed directly:
a unit's weight is unchanged whenever two assignments agree on its
in-neighborhood.  The moment restrictions then encode design unbiasedness for
all eligible raw monomials.
-/

@[expose] public section

open scoped BigOperators
open Finset

namespace CausalSmith.Experimentation.SnipeDegreeFrontier

open Causalean.Experimentation.DesignBased

universe u

variable {V : Type u} [Fintype V] [DecidableEq V]

/-- Low-order bounded-mass schedules on one fixed graph. -/
-- @node: def:local-linear-class
structure LocLinSchedClass
    (G : V → V → Prop) (d β : ℕ) (B : ℝ) where
  coef : V → Finset V → ℝ -- @realizes \mathcal M_t(G_t)(fixed-graph schedule)
  supported : ∀ i S, ¬ S ⊆ nbhd G i → coef i S = 0
  low_order : LowOrder coef (effBeta β d)
  mass_le : BoundedCoeffMass G coef B
-- @realizes G_t(fixed directed complete-block graph)
-- @realizes N_i^{G_t}(nbhd G_t i)
-- @realizes n_t(Fintype.card V)
-- @realizes V_{n_t}(finite carrier V)
-- @realizes d_t(fixed block size d)

/-- A collection of block-local weights satisfying all unbiasedness moments. -/
structure LocLinWeights
    (G : V → V → Prop) (d β : ℕ)
    (p : ℝ) (hp0 : 0 ≤ p) (hp1 : p ≤ 1) where
  weight : V → (V → Bool) → ℝ -- @realizes w_{i,t}(block-local assignment weight)
  blockIndex : V → Fin (Fintype.card V / d)
    -- @realizes b(i)(typed block index in Fin (n_t/d_t))
  complete_block : ∀ i j, j ∈ nbhd G i ↔ blockIndex j = blockIndex i
  local_dep : ∀ i z z',
    (∀ j ∈ nbhd G i, z j = z' j) → weight i z = weight i z'
  mean_zero : ∀ i,
    (bernoulliDesign (fun _ : V => p) (fun _ => hp0) (fun _ => hp1)).E
      (weight i) = 0
  moment_one : ∀ i (S : Finset V), S.Nonempty → S ⊆ nbhd G i →
    S.card ≤ effBeta β d →
    (bernoulliDesign (fun _ : V => p) (fun _ => hp0) (fun _ => hp1)).E
      (fun z => weight i z *
        ∏ j ∈ S, if z j then (1 : ℝ) else 0) = 1
-- @realizes Z_{b(i)}(locality through restriction to N_i^{G_t})

/-- The block-local linear data rule generated by a weight collection. -/
noncomputable def locLinEstimator
    (G : V → V → Prop) (d β : ℕ) (p : ℝ)
    (hp0 : 0 ≤ p) (hp1 : p ≤ 1)
    (w : LocLinWeights G d β p hp0 hp1)
    (z : V → Bool) (y : V → ℝ) : ℝ :=
  (Fintype.card V : ℝ)⁻¹ * ∑ i : V, w.weight i z * y i
-- @realizes \widehat\tau_{w,t}(n_t⁻¹ sum w_i Y_i)

/-- The block-local linear design-unbiased estimator class.  Membership is
type-level: a rule is generated by a weight collection carrying the locality,
centering, and raw-monomial moment restrictions above. -/
-- @node: def:local-linear-estimator-class
noncomputable def locLinEstimatorClass
    (G : V → V → Prop) (d β : ℕ) (p : ℝ)
    (hp0 : 0 ≤ p) (hp1 : p ≤ 1) :
    Set ((V → Bool) → (V → ℝ) → ℝ) :=
  Set.range (locLinEstimator G d β p hp0 hp1)
-- @realizes \mathcal E_t^{\mathrm{loc,lin}}(moment-restricted local estimator rules)

/-- MSE of a fixed local weight collection at a fixed schedule. -/
noncomputable def locLinRiskAt
    (G : V → V → Prop) (d β : ℕ) (B p : ℝ)
    (hp0 : 0 ≤ p) (hp1 : p ≤ 1)
    (w : LocLinWeights G d β p hp0 hp1)
    (M : LocLinSchedClass G d β B) : ℝ :=
  (bernoulliDesign (fun _ : V => p) (fun _ => hp0) (fun _ => hp1)).mse
    (fun z =>
      locLinEstimator G d β p hp0 hp1 w z
        (obsOutcome G M.coef z))
    (tte G M.coef)

/-- Worst-case fixed-graph risk of local weights. -/
noncomputable def locLinWorstRisk
    (G : V → V → Prop) (d β : ℕ) (B p : ℝ)
    (hp0 : 0 ≤ p) (hp1 : p ≤ 1)
    (w : LocLinWeights G d β p hp0 hp1) : ℝ :=
  sSup (Set.range fun M : LocLinSchedClass G d β B =>
    locLinRiskAt G d β B p hp0 hp1 w M)

/-- Restricted minimax risk over block-local linear unbiased weights. -/
-- @node: def:local-linear-risk
noncomputable def locLinMinimaxRisk
    (G : V → V → Prop) (d β : ℕ) (B p : ℝ)
    (hp0 : 0 ≤ p) (hp1 : p ≤ 1) : ℝ :=
  sInf (Set.range fun w : LocLinWeights G d β p hp0 hp1 =>
    locLinWorstRisk G d β B p hp0 hp1 w)
-- @realizes R_t^{\mathrm{loc,lin}}(fixed-graph restricted inf-sup risk)

/-- The exact finite block extremal functional.  `block` is the set of units
in the block whose joint error is maximized over signed raw-monomial extreme
points. -/
noncomputable def blockExtremal
    (G : V → V → Prop) (d β : ℕ) (p : ℝ)
    (hp0 : 0 ≤ p) (hp1 : p ≤ 1)
    (w : LocLinWeights G d β p hp0 hp1) (block : Finset V) : ℝ :=
  by
    classical
    let candidates : Finset ((V → Bool) × (V → Finset V)) :=
      Finset.univ.filter (fun choice =>
        ∀ i ∈ block,
          choice.2 i ⊆ block ∧ (choice.2 i).card ≤ effBeta β d)
    have hne : candidates.Nonempty := by
      refine ⟨(fun _ => false, fun _ => ∅), ?_⟩
      simp [candidates]
    exact candidates.sup' hne (fun choice =>
      (bernoulliDesign (fun _ : V => p) (fun _ => hp0) (fun _ => hp1)).E
        (fun z =>
          (∑ i ∈ block, (if choice.1 i then (1 : ℝ) else -1) *
            (w.weight i z *
              (∏ j ∈ choice.2 i, if z j then (1 : ℝ) else 0) -
                if (choice.2 i).Nonempty then 1 else 0)) ^ 2))

end CausalSmith.Experimentation.SnipeDegreeFrontier
