/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Basic
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.AnchorHypercubeGap
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.AnchorLocalizedConverse
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.AnchorLocalizedMeasurability
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.AnchorRiskCongruence
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.AnchorUpper
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.AnchorVariance
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.BernoulliHypercube
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.BernoulliHypercubeKL
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.BindIntegral
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.Converse
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.EventCoupling
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedAdditiveRepresentation
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedBranchAssembly
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedBranches
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedBump
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedCardinality
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedCellPushforward
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedConstruction
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedCoverage
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedCubeBounds
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedCubeDensity
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedDensity
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedDensityAssembly
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedDensityTransfer
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedFamilyGeometry
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedFamilyPackaging
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedFoldPushforward
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedFubini
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedFubiniDensity
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedGeometryBounds
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedHolderBounds
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedHolderScore
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedIntervalPartition
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedJointDensity
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedKLAssembly
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedLinearBounds
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedLinearCube
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedLinearDensity
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedLinearFamily
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedLinearMeshBounds
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedLinearModel
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedLinearPushforward
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedLinearSlice
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedModelAssembly
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedModelConstruction
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedPerturbedCoverage
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedPerturbedPushforward
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedPushforward
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedReflectedDensity
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedReflectedReindex
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedRegularPushforward
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedScalarLipschitz
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedScoreAlgebra
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedScoreLocality
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedSignedCoverage
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedSignedEnvelope
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedSignedPushforward
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedSliceAgreement
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedSliceLaw
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedSliceMeasurability
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.FoldedSmallMesh
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.GaussianAnchorInformation
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.GaussianAnchorLaw
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.Geometry
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.Histogram
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.Information
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.LocalizedConverse
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.Matching
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.OracleSpacing
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.Spacing
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.VarianceAdaptiveResidual
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.VarianceAdaptiveResidualIntegration
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.VarianceAdaptiveResidualPaper
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.VarianceNormalization
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.Helpers.VarianceSuperpopulation
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.TAnchorClassGeometricMinimax
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.TArbitraryPairingConverse
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.TJointMinimaxFrontier
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.TPhaseAndEndpointReductions
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.TRegularDensityHypercube
public import CausalSmith.Experimentation.EXP_PilotscorePairingFrontier_Research.TSelectorUpper

/-! # Run barrel (auto-generated)

Aggregates every module of this causalsmith run so the whole run is ONE buildable target
(`lake build <this module>`). Research modules are not reachable from the top-level
`CausalSmith.lean` barrel, so the default lake target skips them and reports green on stale
oleans. Rewritten from the run's module set on every F-stage entry — do not hand-edit. -/
