/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.Basic
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.Helpers
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.Helpers.CanonicalRepresentatives
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.Helpers.Certificate
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.Helpers.CitedGates
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.Helpers.Estimators
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.Helpers.FiniteCategoricalCounts
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.Helpers.GaussianGame
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.Helpers.HitFactorization
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.Helpers.LocalPath
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.Helpers.ScheduleLawBridge
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.Helpers.WeakCompactness
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.TEfficientExactHitBernoulli
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.TEfficientExactHitCR
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.TEfficientExactHitCRFace
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.TGaussianFiniteCertificate
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.THanStrictRefinement
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.TMechanismClusterCount
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.TMechanismLoss
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.TNuisanceDeletionBernoulli
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.TNuisanceDeletionCR
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.TOracleTransferBernoulli
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.TOracleTransferCR
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.TRankSetCoverageBernoulli
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.TRankSetCoverageCR
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.TRawPoolingGap
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.TTargetTangentLanBernoulli
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.TTargetTangentLanCR
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.TTwoPolicyMinimax
import CausalSmith.Experimentation.EXP_SaturationExacthitDeficiencyDesign_Research.TUniformBoundaryCertificate

/-! # Run barrel (auto-generated)

Aggregates every module of this causalsmith run so the whole run is ONE buildable target
(`lake build <this module>`). Research modules are not reachable from the top-level
`CausalSmith.lean` barrel, so the default lake target skips them and reports green on stale
oleans. Rewritten from the run's module set on every F-stage entry — do not hand-edit. -/
