/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

import CausalSmith.Experimentation.EXP_BanditRandomQvStudentizationFrontier_Research.Basic
import CausalSmith.Experimentation.EXP_BanditRandomQvStudentizationFrontier_Research.Helpers
import CausalSmith.Experimentation.EXP_BanditRandomQvStudentizationFrontier_Research.Helpers.BasinCovariance
import CausalSmith.Experimentation.EXP_BanditRandomQvStudentizationFrontier_Research.Helpers.Classes
import CausalSmith.Experimentation.EXP_BanditRandomQvStudentizationFrontier_Research.Helpers.CovarianceLaws
import CausalSmith.Experimentation.EXP_BanditRandomQvStudentizationFrontier_Research.Helpers.Estimator
import CausalSmith.Experimentation.EXP_BanditRandomQvStudentizationFrontier_Research.Helpers.GuoXuRecursion
import CausalSmith.Experimentation.EXP_BanditRandomQvStudentizationFrontier_Research.Helpers.MartingaleCLT
import CausalSmith.Experimentation.EXP_BanditRandomQvStudentizationFrontier_Research.Helpers.SelfNormalizedCLT
import CausalSmith.Experimentation.EXP_BanditRandomQvStudentizationFrontier_Research.Helpers.StochasticApproximation
import CausalSmith.Experimentation.EXP_BanditRandomQvStudentizationFrontier_Research.Helpers.Witness
import CausalSmith.Experimentation.EXP_BanditRandomQvStudentizationFrontier_Research.P_DirectionalMatrixSeparation
import CausalSmith.Experimentation.EXP_BanditRandomQvStudentizationFrontier_Research.P_EndogenousQVObstruction
import CausalSmith.Experimentation.EXP_BanditRandomQvStudentizationFrontier_Research.Saco.CitedClaim
import CausalSmith.Experimentation.EXP_BanditRandomQvStudentizationFrontier_Research.Saco.Class
import CausalSmith.Experimentation.EXP_BanditRandomQvStudentizationFrontier_Research.Saco.P_Counterexample
import CausalSmith.Experimentation.EXP_BanditRandomQvStudentizationFrontier_Research.Saco.P_StrictInclusion
import CausalSmith.Experimentation.EXP_BanditRandomQvStudentizationFrontier_Research.Saco.T_EarlyStabilizedPivot
import CausalSmith.Experimentation.EXP_BanditRandomQvStudentizationFrontier_Research.Saco.World
import CausalSmith.Experimentation.EXP_BanditRandomQvStudentizationFrontier_Research.T_BasinStableIPWZ
import CausalSmith.Experimentation.EXP_BanditRandomQvStudentizationFrontier_Research.T_ContrastwiseSandwich
import CausalSmith.Experimentation.EXP_BanditRandomQvStudentizationFrontier_Research.T_GuoXuInclusionObstruction
import CausalSmith.Experimentation.EXP_BanditRandomQvStudentizationFrontier_Research.T_MatrixwiseSandwich
import CausalSmith.Experimentation.EXP_BanditRandomQvStudentizationFrontier_Research.T_UniformRealizedQVPivot

/-! # Run barrel (auto-generated)

Aggregates every module of this causalsmith run so the whole run is ONE buildable target
(`lake build <this module>`). Research modules are not reachable from the top-level
`CausalSmith.lean` barrel, so the default lake target skips them and reports green on stale
oleans. Rewritten from the run's module set on every F-stage entry — do not hand-edit. -/
