module
public import CausalSmith.Stat.STAT_NoisydoseWeakdesignTransition_Research.Helpers.ConditionalMean
public import Mathlib.MeasureTheory.Function.ConditionalExpectation.Basic

/-! Helpers — RealizedDoseMean -/
@[expose] public section
set_option linter.style.longLine false
set_option linter.style.whitespace false
set_option linter.unusedVariables false
noncomputable section
attribute [local instance] Classical.propDecidable
open MeasureTheory ProbabilityTheory Set Filter
open scoped ENNReal Topology BigOperators
namespace CausalSmith.Stat.NoisydoseWeakdesignTransition
variable {S : Type*} [MeasurableSpace S]


/-- The sigma algebra generated by dose, stratum and error. -/
abbrev doseXZSigma : MeasurableSpace (StructSpace S) :=
  MeasurableSpace.comap (fun w : StructSpace S => (sA w, sX w, sZ w)) inferInstance
/-- The sigma algebra generated by dose and stratum. -/
abbrev doseXSigma : MeasurableSpace (StructSpace S) :=
  MeasurableSpace.comap (fun w : StructSpace S => (sA w, sX w)) inferInstance
/-- Schedule exchangeability derives both realized-dose conditional means and the observed outcome bound. [Under the stated conditions](hyp:hP,hbeta,hkappa,hsigma). [This is the stated conclusion](goal). -/
-- @node: lem:realized-dose-mean
lemma realized_dose_mean (E : PathSpace S) (beta kappa sigma : ℝ)
    (hbeta : beta ∈ Ioc (0 : ℝ) 1) (hkappa : kappa ∈ Icc (0 : ℝ) 2)
    (hsigma : sigma ∈ Icc (0 : ℝ) (1/4))
    (P : Measure (StructSpace S)) [IsProbabilityMeasure P]
    {K : ClassConstants} (hP : NoisyDoseModelClass E K beta kappa sigma P) :
    (∀ᵐ w ∂P, sY w ∈ Icc 0 1) ∧ -- @realizes Y(derived observed a.s. range [0,1])
    (P[sY | doseXZSigma] =ᵐ[P] fun w => condPotMean E P (sX w) (sA w)) ∧
    (P[sY | doseXSigma] =ᵐ[P] fun w => condPotMean E P (sX w) (sA w)) ∧
    (∀ F : (ℝ × Bool × ℝ) → ℝ, Measurable F → (∃ B : ℝ, ∀ z, |F z| ≤ B) →
      ∫ w, F (sA w, sX w, sZ w)*sY w ∂P =
        ∫ w, F (sA w, sX w, sZ w)*condPotMean E P (sX w) (sA w) ∂P) := by
  refine ⟨realized_outcome_mem_Icc E P hP.strataPos hP.scheduleUnconfoundedness
    hP.latentSupport hP.boundedPO hP.consistency, ?_⟩
  have hb : 0 < beta := hbeta.1
  have hiY := realized_outcome_integrable E P hP.strataPos hP.scheduleUnconfoundedness
    hP.latentSupport hP.boundedPO hP.consistency
  have hiM := projectedMean_random_integrable E P beta hb hP.holderMean hP.meanRange
  have hm := projectedMean_measurable E P beta hb hP.holderMean
  have hactual : (fun w => projectedMean E P (sA w) (sX w)) =ᵐ[P]
      (fun w => condPotMean E P (sX w) (sA w)) := by
    filter_upwards [hP.latentSupport] with w hw
    simp only [projectedMean, Set.projIcc_of_mem zero_le_one hw]
  have htests : ∀ F : (ℝ × Bool × ℝ) → ℝ, Measurable F →
      (∃ B : ℝ, ∀ z, |F z| ≤ B) →
      (∫ w, F (sA w,sX w,sZ w)*sY w ∂P) =
        ∫ w, F (sA w,sX w,sZ w)*projectedMean E P (sA w) (sX w) ∂P := by
    intro F hF hbound
    obtain ⟨B,hB⟩ := hbound
    exact bounded_test_mean E beta kappa sigma hb P hP F hF B hB
  have hXZ : P[sY | doseXZSigma] =ᵐ[P]
      (fun w => projectedMean E P (sA w) (sX w)) := by
    apply condExp_eq_of_bounded_tests P (fun w => (sA w,sX w,sZ w))
      (by fun_prop) sY hiY (fun p => projectedMean E P p.1 p.2.1)
      (hm.comp (show Measurable (fun p : ℝ × Bool × ℝ => (p.1,p.2.1)) by fun_prop)) hiM
    exact htests
  have hX : P[sY | doseXSigma] =ᵐ[P]
      (fun w => projectedMean E P (sA w) (sX w)) := by
    apply condExp_eq_of_bounded_tests P (fun w => (sA w,sX w))
      (by fun_prop) sY hiY (fun p => projectedMean E P p.1 p.2) hm hiM
    intro F hF hbound
    apply htests (fun p => F (p.1,p.2.1))
      (hF.comp (show Measurable (fun p : ℝ × Bool × ℝ => (p.1,p.2.1)) by fun_prop))
    obtain ⟨B,hB⟩ := hbound
    exact ⟨B, fun p => hB (p.1,p.2.1)⟩
  refine ⟨hXZ.trans hactual, hX.trans hactual, ?_⟩
  intro F hF hbound
  apply (htests F hF hbound).trans
  apply integral_congr_ae
  filter_upwards [hactual] with w hw
  rw [hw]

end CausalSmith.Stat.NoisydoseWeakdesignTransition
